cupy/cupy

docs/source/index.rst

This PR adds the link to the official repository to the top page of the readthedocs

Add link to CuPy repository

---

cupy/sorting/count.py
cupy/sorting/search.py
tests/cupy_tests/test_init.py

This PR fixes the format of some code in CuPy, which has [autopep8 failure in Travis](https://travis-ci.org/cupy/cupy/jobs/210055674).

Fix format to pass autopep8

---

README.md
docs/source/install.rst

This PR reduce support environment. 
CUDA 6.5: This SDK does not have NVRTC.
cuDNN v2, v3: These library is too old. And, some API does not have API compatibility.

Reduce support environment

---

cupy/manipulation/basic.py
tests/cupy_tests/manipulation_tests/test_basic.py

Fixes https://github.com/pfnet/chainer/issues/720

Allow cupy.copyto from python scalar

---

cupy/core/core.pyx

There is "Chainer" word left in an error message of`cupy.sort`. This PR fixes it to "CuPy" .

Small fix on cupy.sort error message

---

cupy_setup_build.py

https://github.com/BVLC/caffe/issues/4046

Fix CUDA 7.5 nvcc compilation error in string.h

---

setup.py

This PR provides correct pip archive file by `python setup.py sdist --cupy--no-cuda` command.

Include cu files in --cupy-no-cuda mode

---

setup.py

This is a fix over #76 (I missed this point on reviewing, sorry).

Fix cupy-thrust packaging

---

cupy/cuda/memory.pyx
cupy/cuda/pinned_memory.pyx

When using CuPy default memory pool from multiple threads simultaneously, sometimes it causes invalid memory access.  I confirmed this issue using the official Docker image with [this code](https://gist.github.com/kmaehashi/ef5931ab758db1fdaa08474596eec5ec).
The issue (generally) occur when the initial trial of `malloc` failed with out-of-memory error and `free_all_blocks` is called.
https://github.com/cupy/cupy/blob/v1.0.0/cupy/cuda/memory.pyx#L359-L364
The code of [`free_all_blocks`](https://github.com/cupy/cupy/blob/v1.0.0/cupy/cuda/memory.pyx#L386-L387) internally does the following (according to the generated Cython source code):
1. Construct new `collections.defaultdict(list)` instance.
2. Decrement ref count for `self._free`, which triggers garbage collection.
3. Set the new …

Memory pool is thread unsafe

---

tests/cupy_tests/random_tests/test_generator.py

I found in numpy 1.9, this test does not work:
```
>>> numpy.random.choice(3, p=numpy.array([.2, .3, .5], 'f'))
File "mtrand.pyx", line 1094, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:11476)
ValueError: probabilities do not sum to 1
```
To stabilize the test, I replaced constants with exponential of 2.

Use exponential of 2 for stability

---

cupy_setup_build.py
install/build.py

Currently, installing cupy fails with the following error message when nvcc is not found in PATH.
```
building 'cupy.cuda.thrust' extension
error: unknown file type '.cu' (from 'cupy/cuda/cupy_thrust.cu')
```
This PR fix it to skip installing thrust support itself to avoid this inappropriate situation on environments where nvcc is not found.

Skip installing thrust support in case nvcc not found in PATH.

---

cupy/core/core.pxd
cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

I implemented order option support in `astype` method.
It uses `elementwise_copy`. Is it better to use `ndarray.copy_from_device`?

Support order option in astype method

---

cupy/__init__.py
cupy/core/core.pyx
cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx
cupy/sorting/sort.py
cupy_setup_build.py
docs/source/reference/sorting.rst
tests/cupy_tests/sorting_tests/test_sort.py

This implements `cupy.argsort` following the implementation of `cupy.sort` merged in #55.
As `cupy.sort` does, `cupy.argsort` has restricted support of the features `numpy.argsort` has because its implementation reason using Thrust behind. `cupy.argsort` currently supports only arrays with their rank of one and does not support `axis`, `kind` and `order` parameters that `numpy.argsort` supports.

Implement cupy.argsort

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_core.py
tests/cupy_tests/creation_tests/test_from_data.py

Fixes #119 
This PR also adds unit tests of `cupy.array`.

Put the value of copy option of cupy.array appropriately to ndarray.astype

---

tests/cupy_tests/linalg_tests/test_decomposition.py

This PR as `condition.retry` decorator to decomposition functions (`xp.linalg.svd` and `xp.linalg.qr`) as they are numerically-unstable.

Add retry to unit tests of decomposition functions

---

cupy/core/core.pyx
tests/cupy_tests/creation_tests/test_from_data.py

Rel #111.
`astype` method raises error when it receives ndarray on other GPU.

Fix array method on multi GPU

---

docs/source/reference/difference.rst

This bug is fixed on NumPy 1.13.0
related to #137

Remove description about exponential of boolean array

---

cupy/core/core.pyx

When `src.data.device` is `None`, `src.data.device.id` is `0`. But this behavior is not expected. I fixed this code to check if the device is `None`. 
See #122

Check if device is None on array method

---

cupy/core/core.pyx
cupy/creation/from_data.py
tests/cupy_tests/core_tests/test_elementwise.py

I supported order option in `copy` method using `astype`.
merge #111 first

`order` option for `copy`

---

cupy/core/core.pyx

Array function uses `fill` when input is single value.

Avoid synchronize in array function

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/math_tests/test_arithmetic.py

Fixes #147 
(Additional notes)
I removed all numpy-cupy comparison tests in `test_fusion.py`.
Instead, equality is tested between non-fused cupy computation and fused cupy computation.

Deny numpy arrays in ufunc outside fuse decorator

---

cupy/core/core.pyx
cupy/cuda/pinned_memory.pxd
cupy/cuda/pinned_memory.pyx

This PR implement asynchronous copy to `cupy.array`.
Please see also chainer/chainer#2238.

Improve asynchronous host to device copy

---

cupy/sorting/count.py
tests/cupy_tests/sorting_tests/test_count.py

I fixed `count_nonzero` to return `ndarray` instead of `int`. It is faster because there is not synchronization between CPU and GPU.
see also #95

Make count_nonzero to return array

---

cupy/cuda/memory.pyx

I investigated the least alignment of cudaMalloc, and it was 512 bytes, not 256 bytes with GeForce GTX TITAN X and NVIDIA Tesla k80 (AWS p2.xlarge).
See https://gist.github.com/sonots/41daaa6432b1c8b27ef782cd14064269
It is better to change the round size (`allocation_unit_size`) from 256 bytes to 512 bytes.

Change allocation_unit_size from 256 to 512

---

tests/cupy_tests/random_tests/test_generator.py

Even though this test (before this PR) succeeds in the current configuration, it will fail if the value of `trial` is increased.

Fix expected histogram in RandomState.interval test

---

cupy/sparse/__init__.py
cupy/sparse/base.py
cupy/testing/__init__.py
cupy/testing/helper.py
setup.py
tests/cupy_tests/sparse_tests/test_base.py

I implemented spmatrix that is a base class of all other sparse matrixes. It is compatible with `scipy.sparse.spmatrix`.
related to #36 
merge #39 before this PR.

Implement spmatrix that is a base class of sparse matrixes

---

LICENSE
cupy/sparse/base.py

I added scipy license to LICENSE file because cupy.sparse is based on scipy.sparse.

Scipy license

---

tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
tests/cupy_tests/core_tests/test_ndarray_scatter.py

NumPy is emitting `VisibleDeprecationWarning` in these tests because of dimension mismatch with boolean index.
```
/home/niboshi/w/repos/cupy/tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py:283: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 1
a[self.indexes] = self.value
```

Fix Numpy VisibleDeprecationWarning in indexing tests

---

cupy/cuda/function.pyx

I think this check is not needed because Python scalars should have been converted to NumPy scalars.

Remove superfluous type check for Python scalars

---

examples/gemm/sgemm.cu
examples/gemm/sgemm.py

This PR fixes bugs I found in the SGEMM example.
Most importantly, there were unsafe memory accesses when reading from matrices A and B.
Also, brackets around inside for loops were necessary. The behavior unexpectedly changed without them (ex. line 149~155).

Fix sgemm example

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

I propose to add API to get total bytes, free bytes, and bytes used in the MemoryPool.
With this API, users of chainer will be able to examine memory usage as:
```
from chainer.cuda import memory_pool
print(memory_pool.total_bytes())
```
Note that `free_bytes()` does not mean free bytes in the GPU, but means that memory acquired to the pool, but not used.

Add total_bytes(), free_bytes(), and used_bytes() methods to memory pool

---

cupy/core/core.pyx
cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx
cupy/sorting/sort.py
tests/cupy_tests/sorting_tests/test_sort.py

Follows #186. This PR is a set of small fixes for `cupy.sort`.

Small fixes for cupy.sort

---

cupy/core/core.pyx
cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx
cupy/sorting/sort.py
tests/cupy_tests/sorting_tests/test_sort.py

Fix #152 .
With this change, `cupy.sort` supports sorting arrays with two or more rank along the last axis.

cupy.sort sorting arrays with two or more rank along last axis

---

cupy/__init__.py
cupy/sorting/sort.py
tests/cupy_tests/sorting_tests/test_sort.py

This PR implements `cupy.msort`. Please merge #132 first. 
``cupy.msort(a)``, the CuPy counterpart of ``numpy.msort(a)``, is equivalent to ``cupy.sort(a, axis=0)``. For its implementation reason, ``cupy.sort`` currently supports only sorting an array with its rank of one, so ``cupy.msort(a)`` is actually the same as ``cupy.sort(a)`` for now.

Implement cupy.msort.

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/math_tests/test_arithmetic.py

[backport] Deny numpy arrays in ufunc outside fuse decorator

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py

Fixes `ndarray` deepcopy issue reported in https://github.com/chainer/chainer/issues/2972.

Fix deepcopy with multiple devices

---

examples/gemm/README.md

The current README has some ambiguity in describing the purpose of the kernel.
I updated the README to be clear that the kernel needed to configure `grid size` and `block size` directly.

Fix the README for SGEMM example

---

tests/cupy_tests/linalg_tests/test_norms.py

I found that `numpy_cupy_raises` requires keyword argument.

Add keyword argument

---

tests/cupy_tests/sorting_tests/test_sort.py

Use `testing.for_all_dtypes` with `no_float16=True` and `no_bool=True` instead of `testing.for_dtypes`.

Use testing.for_all_dtypes.

---

cupy/cuda/function.pyx
tests/cupy_tests/core_tests/test_function.py
tests/cupy_tests/core_tests/test_userkernel.py

Reverts #206.
#206 causes an error when `cupy.compile_with_cache` is used directly.

Revert "Remove superfluous type check for Python scalars"

---

cupy/core/core.pyx

This PR fixes `cupy.sort` to use `cupy.cuda.thrust_enabled` for checking if Thrust is enabled, instead of catching `NameError`.

Use cupy.cuda.thrust_enabled to check Thrust enabled

---

cupy/core/core.pyx
cupy/cuda/thrust.pyx
tests/cupy_tests/sorting_tests/test_sort.py

Small fixes for `cupy.argsort`.

Small fixes for cupy.argsort

---

cupy_setup_build.py

The setup script has duplicated codes to add OpenMP build option passed to the compiler.
- https://github.com/cupy/cupy/blob/master/cupy_setup_build.py#L214
- https://github.com/cupy/cupy/blob/master/cupy_setup_build.py#L280
I guess the option is intended for cusolver, so the first section would be unnecessary.
This change does not need backporting because the change is included at v2.0.0a1 (https://github.com/cupy/cupy/pull/46).

Remove duplicated build option in setup script.

---

cupy_setup_build.py

This PR is a backport of #244.
The original change has mixed changes to be backported and not to be backported, so this backport PR has different change from #244, only to be backported.

[backport] Add compile option to build on Windows

---

.coveragerc

I added include option in covreagerc. It prevents to include lines of system libraries to coverage result.

Add include option for covreage

---

tests/cupy_tests/sorting_tests/test_sort.py

This PR make `argsort` tests clearer in terms of parameterizing tests for `cupy.argsort` and `cupy.ndarray.argsort` before supporting sort multi rank arrays.

Refactor argsort tests.

---

cupy/core/core.pyx
tests/cupy_tests/sorting_tests/test_sort.py

Merge #282 first.
This PR fixes `cupy.argsort` for non-contiguous arrays. Arrays need to be C contiguous when using Thrust sorting operations.
```Python
>>> a = cupy.array([1, 0, 2, 3])[::2]
>>> a.argsort()
[1, 0]  # should be [0, 1]
```
This PR does not need to backport to v1 because `cupy.argsort` is introduced at v2.0.0.a1.

Fix argsort for non-contiguous arrays

---

install/build.py

When I build cupy as:
```
git clean -fdx
python setup.py develop
```
I always get `a.out`, but it should be written to temp_dir and removed after built.

Do not create a.out on running python setup.py develop

---

install/build.py

[backport] Do not create a.out on running python setup.py develop

---

cupy/__init__.py
cupy/cuda/__init__.py
tests/cupy_tests/test_init.py

Currently, `chainer.cuda.available` is `True` even if there is no available CUDA device (by setting `CUDA_VISIBLE_DEVICES=-1`).
In order to avoid that, this PR introduces ~~`cupy.available`~~ `cupy.is_available()` which takes account of device availability.
(Corresponding issue in PyTorch: https://github.com/pytorch/pytorch/issues/306)

Introduce cupy.is_available()

---

cupy/cuda/pinned_memory.pyx

`itervalues` does not exist in Python 3. I replaced it.

Stop using itervalue

---

cupy/core/core.pyx
cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx

Merge #284 first.
This PR replaces `cupy.argsort` implementation employing `thrust::sort_by_key` to make significant improvement in time efficiency.
It does not need backport to v1 because `cupy.argsort` is introduced at v2.0.0a1.

Improve cupy.argsort efficiency in time

---

cupy/core/core.pyx
cupy/sorting/sort.py
tests/cupy_tests/sorting_tests/test_sort.py

Please merge #224 first.
Previously, #186 made `cupy.sort` support sorting two or higher rank arrays, but it is only along the last axis.
This PR allows `cupy.sort` to sort such arrays along other axes but last, as well as `axis=None` option that `numpy.sort` has.
Finding no efficient way to operate such sorting on GPU, I have implemented the operation in terms of rolling axes.

Sort arrays along axes but last

---

cupy/cuda/cupy_cusparse.h
cupy/cuda/cusparse.pyx
cupy/cusparse.py
cupy/sparse/csc.py
cupy/sparse/csr.py

I found `cusparseScsc2dense` API, that can convert csc matrix to f-contiguous array. I fixed `csr_matrix.toarray` with this method to return c-contiguous array.

Use csc2dense to convert csr-matrix to dense

---

docs/source/reference/difference.rst

I wrote difference of reduction functions in the document.

Write differentce of reduction functions

---

README.md

Fixed how to run tests that I've written on README.
`python -m unittest discover test "test_*.py"` was wrong because it runs even tests not included in cupy. Also added about doctest.

README: Fix how to run test

---

README.md
docs/source/contribution.rst

follow-up: https://github.com/cupy/cupy/pull/310

Move development guides from README to docs

---

cupy/sorting/sort.py
tests/cupy_tests/sorting_tests/test_sort.py

This PR fixes `cupy.msort` so that it can sort multi rank arrays, along the first axis.

cupy.msort supporting multi rank arrays.

---

cupy/sparse/base.py

https://docs.python.org/3.6/library/constants.html#NotImplemented

Return NotImplemented instead of NotImplementedError

---

cupy/core/core.pyx
cupy/manipulation/join.py
cupy/manipulation/rearrange.py
cupy/math/sumprod.py
cupy/statistics/histogram.py
tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_unary_op.py
tests/cupy_tests/manipulation_tests/test_dims.py
tests/cupy_tests/manipulation_tests/test_join.py
tests/cupy_tests/manipulation_tests/test_rearrange.py
tests/cupy_tests/math_tests/test_sumprod.py
tests/cupy_tests/statics_tests/test_histogram.py

Fix #137 
- Use `numpy.AxisError`.
- Skip bool test case.

Support NumPy 1.13

---

README.md
docs/source/install.rst

Reverts cupy/cupy#336
We will revert https://github.com/cupy/cupy/pull/281, so we also have to revert https://github.com/cupy/cupy/pull/336

Revert "Fix document about numpy version"

---

tests/cupy_tests/core_tests/test_fusion.py

Rel: #281 
Jenkins is failing in stable test
(`tests/cupy_tests/core_tests/test_fusion.py:TestFusionFuse.test_fuse3`)

Skip bool unary negative test

---

cupy/sparse/compressed.py
cupy/sparse/csc.py
cupy/sparse/csr.py
cupy/sparse/util.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

It support this type of initializer: `csc_matrix((m, n))`
merge #236 first

csr and csc matrixes' initializers support shape

---

cupy/sparse/csc.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

It supports `order` argument in `toarray` method of sparse matrixes.

Support order argument in toarray method of csc and csr

---

cupy/core/core.pyx
cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx
cupy/sorting/sort.py
tests/cupy_tests/sorting_tests/test_sort.py

Merge #285 first.
This PR makes `cupy.argsort` support sort multi rank arrays which are of rank two or more. It also supports sort along axes but last.

cupy.argsort for arrays of rank two or more

---

cupy/core/core.pyx
cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx

This PR removes device memory allocation out of memory pool form `cupy.sort`.

Remove device memory allocation out of memory pool

---

cupy_setup_build.py

I am not sure whether this is acceptable, but this patch made the building time of `python setup.py develop` faster from `3:24.88` to `2:30.71` by skipping cross compile. This makes me feel good on development.

Skip cross compile on setup.py develop to build faster

---

cupy/sparse/compressed.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

csr_matrix and csc_matrix support conversion from scipy.spmatrix with this patch.
related to #36

Support conversion from scipy.sparse matrix to cupy.sparse

---

docs/source/conf.py

I found the [source] link does not work for an object which is an alias of an external module (e.g. `cupy.isscalar` = `numpy.isscalar`. See https://docs-cupy.chainer.org/en/v1.0.2/reference/generated/cupy.isscalar.html).
In these cases the link should be hidden.
TODO: Port to Chainer

Hide source link for alien objects

---

cupy/sparse/compressed.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented __getitem__ for major dimension of compressed matrixes.
Please merge #240 first.
related to #36

Getitem for major dimension

---

cupy/cuda/compiler.py

Fixes #378 by avoiding decoding nvcc output.
Notes:
- The result of this function (`preprocess`) is only used to generate md5 digest. So there's no need to decode it.
- The result (`bytes`) is used in `str` formatting (https://github.com/cupy/cupy/blob/accf3ad237f6cf63710852df2d5d7d37f05830ee/cupy/cuda/compiler.py#L126), but the type difference doesn't matter; different values of `preprocess(...)` will result in  different `pp_src`, even if it's `bytes`. It's enough as a key to generate hash digest.

Avoid decoding nvcc output with UTF-8

---

cupy/sparse/compressed.py
tests/cupy_tests/sparse_tests/test_csr.py

It supports ellipsis in __getitem__ for sparse matrix.
Please merge #301 first.
related to #36

Support ellipsis in __getitem__ for sparse matrix

---

cupy/cusparse.py
cupy/sparse/coo.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_coo.py

I found a bug about coo_matrix. It does not work correctly when it is empty.
merge #316 first

Fix bug about empty coo_matrix

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

Fix https://github.com/cupy/cupy/issues/185
Error message becomes as following:
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate XXXX bytes (total YYYY bytes)
instead of:
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

Tell the memory size when cudaErrorMemoryAllocation occurred

---

cupy/linalg/util.py

This small PR speedups `_tril()` and `_triu()` in `cupy/linalg/util.py` with the ElementwiseKernel.

Improve _tril() and _triu() with an ElementwiseKernel

---

cupy/sparse/dia.py
tests/cupy_tests/sparse_tests/test_dia.py

I implemented array conversion method for dia_matrix.
Merge #320 first.
Related to #36

Array conversion from dia_matrix

---

cupy/sparse/coo.py
cupy/sparse/util.py
tests/cupy_tests/sparse_tests/test_coo.py

I implemented `sum_duplicates` for `coo_matrix`. Its bottleneck is `cumsum`, but we can make more efficient implementation:
http://people.cs.vt.edu/yongcao/teaching/cs5234/spring2013/slides/Lecture10.pdf
merge #328 first.
related to #36

Implement sum_duplicates

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

For https://github.com/cupy/cupy/issues/317#issue-245007720,
Referring http://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#finalization-method-dealloc,
> You need to be careful what you do in a `__dealloc__()` method. By the
> time your` __dealloc__()` method is called, **the object may already have
> been partially destroyed** and may not be in a valid state as far as
> Python is concerned, so you should avoid invoking any Python
> operations which might touch the object. In particular, don’t call any
> other methods of the object or do anything which might cause the
> object to be resurrected. It’s best if you stick to just deallocating
> C data.
Therefore, the pool object potentially can be None in `__dealloc__()`, and
we should not call any python methods in …

Avoid to call python methods in __dealloc__(), use __del__() instead.

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
cupy_setup_build.py
setup.py

For https://github.com/cupy/cupy/issues/317#issuecomment-317614730
1. Remove in_use flag to avoid race-condition
2. Change free list from `list` to `set` so that we can find a free block fast without in_use flag
3. Add _free_lock and _in_use_lock to avoid race-condition with free_all_blocks, n_free_blocks(), used_bytes(), free_bytes(), and total_bytes().
* Operations on `set` or `dict` are atomic in python, but locks are required for these functions which iterate set or dict.

Fix race-condition on memory pool

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

[backport] Avoid to call python methods in __dealloc__(), use __del__() instead.

---

cupy/sparse/construct.py

This PR fixes a typo in the docstring of `spdiags`.

Fix typo in spdiags docstring.

---

tests/cupy_tests/testing_tests/test_array.py

[backport] Use randint instead of random_integer that is deprecated

---

cupy/sparse/compressed.py
cupy/sparse/csc.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented `sum_duplicates` method for csr and csc. It uses `coo_matrix.sum_duplicates`.
It depends on #326 and #328 
related to #36

sum_duplicates for compressed matrices

---

tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

SciPy causes DeprecationWarning when order argument has more than two characters before it raises an actual error. To prevent it, I changed the test argument.

Changed order argument for unknown order test as SciPy causes DeprecationWarning

---

cupy/core/core.pyx
tests/cupy_tests/sorting_tests/test_sort.py

Rel #347.
This PR fixes argsort to raise `AxisError` on numpy >= 1.13.

Use AxisError with numpy compat.

---

cupy/cuda/compiler.py

Python 3 prints a line feed in bytes as `\n` and `e.output` is `bytes`, so `e.output` should be converted to `str` for readability.

Make compilation error readable

---

tests/cupy_tests/sparse_tests/test_coo.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I added a test case when `axes` argument is not `None`. It causes `ValueError`.

Add test for transpose when axes is not none

---

cupy/core/elementwise.pxi
cupy/core/reduction.pxi

Clear warnings in doctest.
This is needed before merging https://github.com/cupy/cupy/pull/442 .

Clear doctest warnings

---

cupy/linalg/decomposition.py
cupy/linalg/solve.py

This PR adds ``Returns:`` sections to ``cupy.linalg`` functions.

Add documents of cupy.linalg

---

cupy/cuda/compiler.py
docs/source/reference/environment.rst

I often insert this code to inspect generated CUDA source.
It would be useful if this can be enabled by an environment variable.

Save CUDA source with environment variable

---

cupy/cuda/__init__.py
cupy/cuda/cupy_cuda.h
cupy/cuda/memory.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx
tests/cupy_tests/cuda_tests/test_memory.py

follow-up: https://github.com/cupy/cupy/pull/163
The advantage using unified memory in CuPy is that device memory
oversubscription is possible for GPUs that have a non-zero value for the
device attribute cudaDevAttrConcurrentManagedAccess.
CUDA >= 8.0 with GPUs later than or equal to Pascal is preferrable.
Read more at: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#axzz4qygc1Ry1
Without memory pool:
```
set_allocator(malloc_managed)
```
With memory pool:
```
set_allocator(MemoryPool(malloc_managed).malloc)
```
* Using unified memory, we should be able to eliminate CPU <=> GPU memory transfer codes. But, it is not supported in this PR.
* We've added `ManagedMemory.prefetch` and `ManagedMemory.advice` API, but we still do not have easy interfaces to call them for …

Unified memory

---

cupy/sparse/dia.py
tests/cupy_tests/sparse_tests/test_dia.py

I added a test for an empty dia matrix and found a bug.

Fix tocsc behavior for an empty dia matrix

---

tests/cupy_tests/math_tests/test_arithmetic.py

The result of numpy.power on Windows is different from ubuntu's.

Fix tolerance.

---

tests/cupy_tests/sparse_tests/test_csr.py

I wrote test for `__iter__`. Note that this method uses `__getitem__` and int index is only supported in csr_matrix.

Added test for __iter__

---

tests/cupy_tests/linalg_tests/test_solve.py

I found `axes` argument in `tensorsolve` is not tested.

Fix test for tensorsolve

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

* Use target function name as the kernel name by default
* Add `kernel_name` option to `fuse` to override the kernel name

Fusion kernel name

---

cupy/linalg/__init__.py
cupy/linalg/solve.py
docs/source/reference/linalg.rst
tests/cupy_tests/linalg_tests/test_solve.py

This PR implements `cupy.linalg.pinv`.

Implement cupy.linalg.pinv

---

cupy/cuda/__init__.py

This is needed to use `cupy.cuda.memory_hooks` without explicitly importing it.

import memory_hooks

---

cupy/prof/time_range.py

This PR makes performance and behavior analysis using a `time_range` method a little convenient.
Using the `time_range` method makes it easier to analyze when some processing of interest were run on CPU and the corresponding GPU kernels were launched on NVVP. However it is not so easy to identify exactly which GPU kernels are corresponding to the processing and when they are executed. That is mainly because kernels are usually launched non-blocking way and they are not executed in sync with the launch.
With this PR, by just adding `sync=True` to the `time_range` method, the marked range is extended until the completion of the kernels that are launched with in the range.

Add a sync option to time_range

---

cupy/cuda/thrust.pyx

@okuta found the following warnings. This PR split variable declarations to supress them.
```
warning: cupy/cuda/thrust.pyx:94:16: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
warning: cupy/cuda/thrust.pyx:94:29: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
```

Fix Cython warning

---

cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h

This PR adds an interface to use a function `cudnnGetTensor4dDescriptor` in cuDNN library.

Add interface to use cudnnGetTensor4dDescriptor

---

cupy/cuda/memory.pyx

Sometimes, we get following error.
`Exception TypeError: "'NoneType' object is not callable" in <bound method PooledMemory.__del__ of <cupy.cuda.memory.PooledMemory object at 0x7f397a991c90>> ignored`
This PR will fix that error.

Fix multi thread problem in PooledMemory

---

cupy/core/reduction.pxi
cupy/logic/truth.py
tests/cupy_tests/logic_tests/test_truth.py
tests/cupy_tests/sorting_tests/test_search.py

Fix #266
`simple_reduction_function` returns zero-sized array, even if `self.identity == None`.

Fix simple reduction

---

cupy/cuda/memory_hooks/__init__.py
cupy/cuda/memory_hooks/line_profile.py
docs/source/reference/cuda.rst
tests/cupy_tests/cuda_tests/memory_hooks_tests/test_line_profile.py

This PR requires https://github.com/cupy/cupy/pull/264.
Code example::
import cupy.cuda.memory_hooks
hook = cupy.cuda.memory_hooks.LineProfileHook()
with hook:
hook.print_report()
Output example::
_root (4.00KB, 4.00KB)
lib/python3.6/runpy.py:193:_run_module_as_main (4.00KB, 4.00KB)
lib/python3.6/runpy.py:85:_run_code (4.00KB, 4.00KB)
lib/python3.6/unittest/__main__.py:18:<module> (4.00KB, 4.00KB)
lib/python3.6/unittest/main.py:94:__init__ (4.00KB, 4.00KB)
lib/python3.6/unittest/main.py:255:runTests (4.00KB, 4.00KB)
tests/cupy_tests/cuda_tests/memory_hooks_tests/test_line_profile.py:37:test_print_report (1.00KB, 1.00KB)
tests/cupy_tests/cuda_tests/memory_hooks_tests/test_line_profile.py:38:test_print_report (1.00KB, 1.00KB)
tests/cupy_tests/cuda_tests/memory_hooks_tests/test_line_profile.p …

Line memory profiler using memory hook and traceback

---

examples/finance/black_scholes.py

This PR adds an example of option pricing using Black-Scholes equation and CuPy.
I created this example in order to illustrate how to write our own kernels with CuPy and its performance.
In my environment (CPU: Intel(R) Xeon(R) CPU E5-2623 v3 @ 3.00GHz, GPU: TITAN X(Pascal)), These performances are the following:
```
CPU (NumPy, Naive implementation):     19.997561 sec
GPU (CuPy, Naive implementation):      0.319212 sec
GPU (CuPy, Elementwise kernel):        0.012139 sec
```

Add an example of option pricing using Black-Scholes equation

---

cupy/core/elementwise.pxi

The loop index `i` is used twice in nested loops.

Avoid duplicate loop index

---

cupy/__init__.py
tests/cupy_tests/test_init.py

We improved memory allocator #168.
So, CuPy should use memory pool by default.

Set default memory allocator

---

cupy_setup_build.py

Ctyhon version 0.26.0 was released. We should use latest Cython.
https://github.com/cython/cython/blob/master/CHANGES.rst

Change minimum Cython version

---

docs/source/install.rst

doc: Increase required cython version: 0.24 -> 0.26.1

---

cupy_setup_build.py
docs/source/contribution.rst
docs/source/install.rst
docs/source/reference/environment.rst
install/build.py

CuPy installer use CUDA_PATH/bin/nvcc when CUDA_PATH is set.
In this case, PATH is ignored. Also ccache is ignored.

Support NVCC environment variable

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cudnn.py
tests/cupy_tests/test_cudnn.py

I implemented function wrappers for dropout functions which cuDNN provides (cuDNN v5 or later is required).
Some of cuDNN interfaces ( `cudnnDropoutForward` and `cudnnDropoutBackward` ) take the states which indicate the random number generators for creating dropout masks and created dropout masks, so I also implemented the utility class which provides `forward` and `backward` methods to conceal the internal cuDNN states.

Add cuDNN support for dropout.

---

cupy/cuda/nvrtc.pyx

Error code is useful for debugging (especially when you get `NVRTC_ERROR unknown`).

Show NVRTC error code

---

.travis.yml

[backport] Travis fails with cython 0.27. Use cython 0.26.1 for a while

---

cupy/core/core.pyx
cupy/cuda/cublas.pxd
cupy/cuda/cublas.pyx
cupy/cuda/cupy_cuda.h

The aim of this PR is to enable use of Tensor-Core via cuBLAS. The following modifications are mainly included in this PR.
- Add interfaces to use `cublasSetMathMode()`, `cublasGetMathMode()` and `cublasGemmEx()` in cuBLAS.
- Use `cublasGemmEx()` with Tensor-Core configs instead of `cublasSgemmEx()` when Tensor-Core is available.

Tensor-Core support (cuBLAS)

---

docs/source/install.rst

I think the document contains old ulr (github.com/pfnet/cupy)
Please see following document.
https://docs-cupy.chainer.org/en/stable/install.html#install-cupy
https://github.com/cupy/cupy/blob/e51b311608545870c1ee0bb70a48adcc60b5cbd2/docs/source/install.rst
I fix `github.com/pfnet/cupy` to `github.com/cupy/cupy`

Fix wrong urls in document

---

cupy_setup_build.py

Cython 0.27.0 and Python3 causes install error.
This PR avoids it.

Avoid Cython 0.27.0

---

cupy/cusparse.py
tests/cupy_tests/test_cusparse.py

I noticed that I misunderstood arguments `m` and `n` in `csrmm2` especially when `transa=True`.
fix #552

Fix csrmm2 to support transa

---

tests/cupy_tests/test_cusparse.py

The backport of #570 .
Merge #601, which is the backport of #565, first.

[backport] Test csrgemm

---

cupy/testing/random.py
tests/cupy_tests/random_tests/test_generator.py

`dtype` option for `randint` method is supported since v1.11. We need to support v1.10.

Remove dtype option which is introduced in v1.11

---

tests/cupy_tests/random_tests/test_sample.py

I replaced `Mock` with `mock.patch` where functions are directly replaced with `Mock`. It causes a critical bug. After replacing them other tests also uses these Mocks. Always we need to use `mock.patch` to replace functions.

Use mock.patch instead of directly replacing function with Mock

---

docs/source/install.rst

CUDA 9 and cuDNN 7 are supported.
merge https://github.com/chainer/chainer-test/pull/334 first.

Fix supported CUDA and cuDNN version

---

cupy/sparse/coo.py
tests/cupy_tests/sparse_tests/test_coo.py

`coo_matrix.__init__` supports initialization with sparse matrix.

Support coo matrix initialization with other types of sparse matrices

---

README.md

https://docs-cupy.chainer.org/en/stable/developers.html does not exist now

fix link for developers

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

In this PR, `random.RandomState.interval` supports sampling up to `0xffffffff`.
It returns `numpy.int32` array if `mx` <= 0x7fffffff for backward compatibility.
Otherwise it returns `numpy.uint32`.

Support uint32 sampling in random.RandomState.interval

---

.travis.yml

https://github.com/cython/cython/releases/tag/0.27.1 is released on 9 days ago.
follow-up: https://github.com/cupy/cupy/pull/529
ref. https://github.com/cython/cython/issues/1885

cython 0.27.1 is released. revert .travis.yml to use the latest cython

---

cupy/cuda/memory_hooks/__init__.py
cupy/cuda/memory_hooks/line_profile.py
docs/source/reference/cuda.rst
tests/cupy_tests/cuda_tests/memory_hooks_tests/test_line_profile.py

backport of https://github.com/cupy/cupy/pull/265
I want to backport line memory profiler to v2 because cupy memory profiler https://github.com/chainer/chainer/pull/2979 is already merged in chainer v3.
I wanted to introduce them together.
(I actually overlooked the line memory profiler was not merged into v2 yet)

[backport] Line memory profiler using memory hook and traceback

---

cupy/sparse/coo.py
tests/cupy_tests/sparse_tests/test_coo.py

[backport] Support coo matrix initialization with other types of sparse matrices

---

cupy/cuda/function.pyx

This PR changes maximum x-dimension of a grid of cupy kernel from **65536** to **2147483647** to match the actual upper limit. Please refer to 'Table 14. Technical Specifications per Compute Capability' of http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-capabilities.

Change max size of grid

---

.travis.yml

[backport] cython 0.27.1 is released. revert .travis.yml to use the latest cython

---

cupy/core/core.pyx
cupy/cuda/function.pyx
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

Fixes a part of #503.
This allows boolean mask on a 0-dim array:
```
a = cupy.ones(())
a[a != 0]
```

Fix indexing 0-dim array with boolean mask

---

tests/cupy_tests/indexing_tests/test_generate.py

[backport] fix typo in test_generate.py

---

docs/source/reference/difference.rst

Related: https://github.com/chainer/chainer-test/pull/342
Fixed doctest to pass with python 3.5.

Use python 3.5 for doctest

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h
cupy/cudnn.py

This is a work-around for an issue in cuDNN7's `cudnnSetRNNDescriptor_v5`. We found there is potential issue in `cudnnSetRNNDescriptor_v5` of cuDNN7. Our proposal for this issue is to use `cudnnSetRNNDescriptor_v6` instead, which is a new API introduced in cuDNN6 and is the default in cuDNN7. 
With this PR, when cuDNN version is 7.0 or newer, `cudnnSetRNNDescritpor_v6` is automatically used. No modification to Chainer is necessary since there is no change in terms of user APIs.
We've confirmed that this PR works correctly with following combinations.
* CUDA 9 and cuDNN 7.0
* CUDA 8 and cuDNN 6.0
* CUDA 8 and cuDNN 5.1

Use v6 RNN API with cuDNN7

---

docs/source/reference/difference.rst

[backport] Use python 3.5 for doctest

---

docs/source/conf.py

to_cpu, to_gpu link is dead.
https://docs-cupy.chainer.org/en/stable/tutorial/basic.html#move-array-from-a-device-to-the-host

add missing chainer interreference

---

docs/source/tutorial/basic.rst

Fix typo in function name and broken heading.

fix document typo and broken heading

---

docs/source/license.rst

I think NumPy is intended here.

fix typo in license page

---

cupy/cuda/function.pyx

This PR avoids PyInt in `linear_launch`.

Avoid PyInt in linear_launch

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

On Windows x64, cupy.int_ is int32 but six.MAXSIZE is 64bit.

Fix the difference between six.MAXSIZE and max of cupy.int_

---

tests/cupy_tests/padding_tests/test_pad.py

NumPy<1.12 can emit ComplexWarning (fixed in later versions).
This PR ignores this warning in unit tests.

Ignore ComplexWarning in numpy.pad

---

tests/cupy_tests/padding_tests/test_pad.py

[backport] Ignore ComplexWarning in numpy.pad

---

cupy/cuda/compiler.py

Passing `arch` option to nvrtc is necessary on some modern GPUs (e.g. one on Drive PX 2), even when compiling the empty program. This PR makes `_preprocess` method to pass the `arch` option.
Without the patch, the following error occurred when executing `./train_mnist.py -g 0` (with cupy 2.0.0).
I note that a similar issue also exists on MXNet <https://github.com/apache/incubator-mxnet/issues/8387>.
```
Exception in main training loop: nvrtc: error: failed to load builtins
File "/home/nvidia/.virtualenvs/bench/lib/python3.5/site-packages/chainer/training/trainer.py", line 299, in run
update()
File "/home/nvidia/.virtualenvs/bench/lib/python3.5/site-packages/chainer/training/updater.py", line 223, in update
self.update_core()
File …
```

Set arch option when calling `_preprocess`, as the option is necesary on some modern GPUs (e.g. Drive PX 2)

---

cupy/cuda/cupy_cuda.h
cupy/cuda/driver.pxd
cupy/cuda/driver.pyx
cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

This fixes #72.
I use `memGetInfo()` Runtime API, which seems to be most harmless, to explicitly bind the context to the current thread.
(I first tried `getDevice()`, but seems that it does not create a context)

Fix multi-threaded application fail when memory pool is enabled

---

cupy/cuda/compiler.py

[backport] Set arch option when calling `_preprocess`, as the option is necesary on some modern GPUs (e.g. Drive PX 2)

---

cupy/random/sample.py
tests/cupy_tests/random_tests/test_sample.py

Limitation:
* `high - low <= 0x7fffffff` must be met
Merge after #564.

Support dtype argument in random.randint

---

examples/finance/monte_carlo.py
tests/example_tests/test_finance.py

Merge #473 first.
This PR computes the price of a call option using Monte-Carlo simulation. In my environment (GPU: TITAN X(Pascal)), the performance is the following:
```
python monte_carlo.py 
initializing...
start computation
GPU (CuPy, Monte Carlo method): 39.067884 sec
Error: 0.007679
```

Add an example of option pricing using Monte-Carlo simulation

---

tests/cupy_tests/core_tests/test_fusion.py

Latest NumPy emits DeprecationWarning.
```
cupy/cupy/core/fusion.py:699: DeprecationWarning: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
return self._numpy_op(*args, **kwargs)
```

Fix test about bool and complex

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

To align with NumPy, `cupy.random.RandomState.seed` should only accept integer types.
This fix supresses `ComplexWarning` in unit tests:
```
tests/cupy_tests/random_tests/test_generator.py::TestRandomState2::test_seed_not_none
/work/cupy/cupy/random/generator.py:243: ComplexWarning: Casting complex values to real discards the imaginary part
seed = numpy.uint64(seed)
```

Fix RandomState.seed to only accept integer types

---

tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/sorting_tests/test_search.py

As mentioned in #698, we need to set seeds to avoid unintended correlation between arrays in thses tests.

Fix where tests

---

cupy/core/core.pyx
cupy/statistics/meanvar.py
tests/cupy_tests/statics_tests/test_meanvar.py

The `ddof` parameter is not currently passed from `std` and `var` to `_std` and `_var` respectively, though the code for ddof is implemented in both `_std` and `_var`. The follow code illustrates the problem:
```
np.random.seed(0)
samples = np.random.random(size=(20,)).astype(np.float64)
for i in range(5):
print('with ddof=%d:' % i)
print('np:', np.var(samples, ddof=i, axis=0))
print('cp:', cp.array(samples).var(ddof=i, axis=0))
print(' ')
```
With the current `master`, the output is:
```
with ddof=0:
np: 0.0761292085833
cp: 0.07612920858325248
with ddof=1:
np: 0.080136009035
cp: 0.07612920858325248
with ddof=2:
np: 0.0845880095369
cp: 0.07612920858325248
with ddof=3:
np: 0.0895637748038
cp: 0.07612920858325248
with ddof=4:
np: 0.0951615107291
cp: 0.07612920858325248
``` …

pass ddof from var/std to _var/_std

---

docs/source/contribution.rst

CuPy verseion of https://github.com/chainer/chainer/pull/3625
* Nose -> PyTest.
* Removed pararell testing section, as it is inefficient.
See also: https://github.com/chainer/chainer-test/pull/315#issuecomment-330204874 and https://github.com/chainer/chainer-test/pull/320
* Fix description on how Travis-CI works.
Please merge https://github.com/cupy/cupy/pull/662 first.

update testing guide of contirbution guide

---

cupy/core/core.pyx

For #419 
benchmark code:
```
from itertools import product
import cupy as xp
from cupy import cuda
cnt = 1000
xs = xp.random.rand(256, 256, 256)
for axis, order, transpose in product([0, -1], ['C', 'F'], [True, False]):
arr = [x.copy() if order is 'C' else xp.asfortranarray(x.copy()) for x in xs]
tup = [a.T if transpose else a for a in arr]
stream = cuda.Stream.null
start = stream.record()
for _ in range(cnt):
_ = xp.concatenate(tup, axis=axis)
end = stream.record()
end.synchronize()
elapsed = xp.cuda.get_elapsed_time(start, end) / cnt
print("axis: {}, order: {}, T: {}, elapsed: {}".format(axis, order, transpose, elapsed))
```
This pull request:
```
axis: 0, order: C, T: True, elapsed: 7.17641357421875
axis: 0, order: C, T: False, elapsed: 2.462125732421875
axis: 0, order: F, T: True, …
```

use continuous copies for concatenate if arrays are not contiguous on axis

---

tests/cupy_tests/fft_tests/test_fft.py

FFT functions of numpy 1.9 does not have the `norm` keyword argument.

Skip test_fft when the version of numpy is 1.9

---

cupy/cuda/memory.pyx

The check is unnecessary because C++ standard containers do [value initialization](http://en.cppreference.com/w/cpp/language/value_initialization).

Eliminate a redundant check

---

cupy/cuda/memory.pxd
install/build.py

follow-up: https://github.com/cupy/cupy/pull/306
But, note that std::map is slower than std::unordered_map

Use std::map instead of std::unordered_map to avoid c++11

---

tests/cupy_tests/linalg_tests/test_einsum.py

This PR fixes test with numpy 1.9.

Use skip_dtypes properly in test_einsum

---

tests/cupy_tests/linalg_tests/test_einsum.py

[backport] Use skip_dtypes properly in test_einsum

---

tests/cupy_tests/linalg_tests/test_product.py
tests/cupy_tests/statics_tests/test_order.py

These tests fails when using old numpy. They make CI unstable.

Skip some tests when using old numpy

---

tests/cupy_tests/linalg_tests/test_product.py

#744
Only backport `tests/cupy_tests/linalg_tests/test_product.py` .

[backport] Skip some tests when using old numpy

---

docs/source/install.rst

CuPy v4.0 will require GPU with CC >= 3.0.
Fixes #638.

document Compute Capability requirement

---

cupy/__init__.py
cupy/core/__init__.py
cupy/core/core.pyx
cupy/linalg/einsum.py
cupy/manipulation/transpose.py
docs/source/reference/manipulation.rst
tests/cupy_tests/manipulation_tests/test_transpose.py

Extracted `moveaxis` as numpy>=1.11 API.
Also I want to use `normalize_axis_tuple` in `moveaxis` and `einsum`, I transport it to `cupy.core`.

Extract moveaxis and normalize_axis_tuple from einsum.

---

cupy/cuda/compiler.py

File name of CUDA dump (shown when `CUPY_DUMP_CUDA_SOURCE_ON_ERROR=1` is set) is broken.
```
Name: / t m p / t m p 3 8 0 z 2 j 8 a / k e r n . c u
Options: -I/home/kenichi/.pyenv/versions/local-3.6.3/lib/python3.6/site-packages/cupy/core/include -I /usr/local/cuda/include -ftz=true -arch=compute_52
CUDA source:
... snip ...
```
This PR fixes the issue.

fix to correctly display filename of CUDA dump

---

.gitignore

[backport] add pytest cache directory to gitignore

---

cupy/core/core.pxd
cupy/core/core.pyx
cupy/math/misc.py
tests/cupy_tests/math_tests/test_misc.py

The default argument for `a_min` and `a_max` in `clip` is ``None``. This patch supports it.

Support None as an argument for clip method

---

cupy/core/elementwise.pxi
cupy/core/reduction.pxi
cupy_setup_build.py

Added `embedsignature` cython compile option to show signatures of methods in API reference generated by Sphinx.
http://cython.readthedocs.io/en/latest/src/reference/compilation.html
I also removed existing explicit signatures, because internally it becames duplicate declaration of signature and raise warning.

Expose signatures to Reference

---

cupy/core/elementwise.pxi

Fix document of ``size`` as variable ``n`` seems no longer be used in generated CUDA source of ElementwiseKernel.
Note that currently ``__call__`` is not exposed to API reference (#458)

fix ElementwiseKernel.__call__ docs

---

cupy/indexing/generate.py
tests/cupy_tests/indexing_tests/test_generate.py

`order=None` is supported in #764. However, the behaviour is different from numpy.
```python
np.unravel_index((4, 6), (4, 3), order=None)
cupy.unravel_index(cupy.array((4, 6)), (4, 3), order=None)
```
In the case of `order='C'`,
```python
np.unravel_index((4, 6), (4, 3), order='C')
cupy.unravel_index(cupy.array((4, 6)), (4, 3), order='C')
```

Fix order=None of unravel_index

---

cupy/testing/helper.py
tests/cupy_tests/testing_tests/test_helper.py

For tests that assert errors to be thrown, allow derived errors to be treated as equal errors and pass the tests. I am not sure if this goes agains the design but it makes sense as these errors can be caught by the same try/except.
A concrete example is `cupy.stack` throwing `IndexOrValueError` which is an error defined by CuPy meaning that it won't pass the equality test with any NumPy error. This PR would allow it to pass.

Allow derived errors to pass equality tests

---

tests/cupy_tests/manipulation_tests/test_join.py

[backport] fix test to pass with numpy 1.9

---

tests/cupy_tests/math_tests/test_matmul.py

I fixed test of #737. Current test is failed on NumPy 1.9 .

Fix matmul test for old NumPy

---

cupy/core/core.pyx
tests/cupy_tests/math_tests/test_matmul.py

[backport] Fix matmul to raise ValueError on invalid shapes

---

cupy/core/core.pyx
tests/cupy_tests/manipulation_tests/test_tiling.py

Issue 1: NumPy works with `len(repeats) == 1`, while CuPy does not.
```
>>> import numpy as np
>>> np.array([1,2,3]).repeat((2,))
array([1, 1, 2, 2, 3, 3])
>>> cp.array([1,2,3]).repeat((2,))
File "cupy/core/core.pyx", line 691, in cupy.core.core.ndarray.repeat
File "cupy/core/core.pyx", line 699, in cupy.core.core.ndarray.repeat
File "cupy/core/core.pyx", line 2392, in cupy.core.core._repeat
ValueError: 'axis' should be specified if 'repeats' is sequence
```
Issue 2: NumPy works with `isinstance(repeats, list) == True` and `axis is None`, while CuPy does not.
```
>>> np.array([1,2,3]).repeat((2,2,2))
array([1, 1, 2, 2, 3, 3])
>>> cp.array([1,2,3]).repeat((2,2,2)) …
```

Fix repeat behave differently with numpy

---

cupy/__init__.py
cupy/core/__init__.py
cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py

I implemented `cupy.size` method. It does not generate a tuple but only returns `int`.
Note `numpy.size` exists but is not documented.

Implement size method

---

cupy/sparse/coo.py
tests/cupy_tests/sparse_tests/test_coo.py

With this patch, coo matrix supports initializer with scipy sparse matrix.

Implement coo initializer for scipy sparse matrix

---

cupy/linalg/decomposition.py
tests/cupy_tests/linalg_tests/test_decomposition.py

Input matrixes are destroyed in SVD method of cuSOLVER.
fix #842

Make a copy when SVD is calculated

---

cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_driver.py
tests/cupy_tests/cuda_tests/test_memory.py

When context is initialized in main thread, but not in sub thread, `ctxGetCurrent` returns:
*  valid pointer in main thread
* `0` in sub thread
Related to #72.

Fix memory pool to correctly detect that memory pool is not established

---

tests/cupy_tests/manipulation_tests/test_join.py

Remove unnecessary try catch from `stack` test (fixed by https://github.com/cupy/cupy/pull/788).

Remove unnecessary try catch

---

examples/cg/cg.py

- Some uses of `.T` had no effect.
- I used `xp.inner` for clarification, while `xp.dot(v, v)` also works for a 1-dim vector `v`.
-  It was slow (especially with cpu) to multiply the constant `a` earlier as in `xp.dot(A * a, p)`.

Improve the conjugate gradient example

---

cupy/core/fusion.py

When `out` argument is given, we need to use only `nin` input variables here.

Fix out argument in fusion

---

cupy/sparse/base.py
cupy/sparse/util.py
tests/cupy_tests/sparse_tests/test_coo.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py
tests/cupy_tests/sparse_tests/test_dia.py

This patch includes most general sum implementation ported from `scipy.sparse.spmatrix`. We can implement more efficient one for each matrix type.
fix #595

Implement sum for cupy.sparse

---

cupy/ext/scatter.py
docs/source/reference/difference.rst
docs/source/tutorial/kernel.rst

This fixes doctests for modern textual representation introduced in NumPy 1.14.
From now on, doctest only succeeds with NumPy 1.14+.
~Merge https://github.com/chainer/chainer-test/pull/385 first.~ (done)

fix docs to use NumPy 1.14 textual representation

---

cupy/ext/scatter.py
docs/source/reference/difference.rst
docs/source/tutorial/kernel.rst

[backport] fix docs to use NumPy 1.14 textual representation

---

cupy/cuda/memory.pyx
cupy/cuda/pinned_memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

This changes these two methods to accept `None` as an argument.
When `None` is specified, it uses the default allocator (i.e., no memory pool.)
During the discussion with @sonots san, we found that `set_allocator()` sounds like resetting the memory allocator to the "default" one.
As CuPy v4 introduced default memory pool, I want to make this API more explicit.
After merging this PR, users can disable the memory pool using `set_allocator(None)`, which is more explicit and easy to understand than `set_allocator()` for users.
For backward compatibility, `set_allocator()` is still kept.

accept None in set_allocator and set_pinned_memory_allocator

---

cupy/cuda/stream.pyx
tests/cupy_tests/cuda_tests/test_stream.py

During the discussion with @niboshi san and @sonots san, we concluded that it is better to keep backward compatibility for null Stream creation, as null Stream is used in some of the user code.
After mergin this PR, creation of new null stream emits DeprecationWarning, instead of raising error.
This issue was first intorduced in https://github.com/cupy/cupy/pull/306 (no backport needed)

emit DeprecationWarning instead of error for new null stream

---

cupy/__init__.py
cupy/cuda/memory.pyx
cupy/cuda/pinned_memory.pyx
docs/source/reference/cuda.rst

This PR exposes some useful memory allocator APIs to documents.
Also includes fixes for some typos.
~~This PR assumes https://github.com/cupy/cupy/pull/885 will be merged.~~ (done)

Fix memory allocator docs

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_core.py

This fixes the overflow in `cupy.size`.
```py
>>> a = cupy.ndarray(2 ** 32, 'b')  # 4 GiB
>>> cupy.size(a)
0
```

Fix cupy.size overflow in 32-bit

---

cupy/cuda/stream.pyx
tests/cupy_tests/cuda_tests/test_stream.py

As we discussed in https://github.com/cupy/cupy/pull/888, Stream(null=True) should not emit warnings.

avoid emitting DeprecationWarning when creating a new null stream object

---

cupy/core/include/cupy/carray.cuh

This PR fixes unintended downcast of `size()` from `ptrdiff_t` to `int`.
This affects some functions when processing array with number of elements >= 2^31.
For example, before applying this PR:
```py
>>> a = cp.ones(2**31, dtype='b')
>>> cp.core.core.scan(a)
array([0, 0, 0, ..., 0, 0, 0], dtype=int8)
```
After applying this PR, the above code should work as expected:
```py
array([ 1,  2,  3, ..., -2, -1,  0], dtype=int8)
```

fix downcast of size in CArray and CIndexer

---

tests/example_tests/test_finance.py

The test fails when single GPU is used.

test_monte_carlo_multigpu needs multiple GPUs

---

cupy/core/core.pyx

I found performance degradation of asynchronous copy.
This bug appeared [here](https://github.com/cupy/cupy/commit/2d4b5dc937190eaaa5d453aa2708f065130fe866#diff-bebe923819e806ae22e9923de58e954cL1698).

Fix get and set method with async mode

---

cupy/random/sample.py

The current document is misleading so that users may be confused with `cupy.random.rand((2, 3))` which causes an error. I slightly fixed the document and added examples.

Improve the document of rand/randn with examples

---

cupy/cuda/memory.pyx

The size of `SingleDeviceMemoryPool._free` increases in some case. Sometimes it may exceed 100000.
Therefore malloc gets slower when we use CuPy long time. Especially in Chainer's workload there is a huge performance degradation.
In this PR, I suggest using None instead of empty `set` object and compressing `_free` arrays.

Implement memory pool index compaction

---

cupy/cuda/stream.pyx
tests/cupy_tests/cuda_tests/test_stream.py

In now, `get_current_stream_ptr` does not detect stream deletion.

Fix bug about stream deletion

---

cupy/cuda/cufft.pyx
cupy/cuda/cupy_cufft.h
cupy/cufft.py

Original implementation of cupy.fft does not use memory pool at the stage of making a FFT plan.
It spoils the computation speed and has possibility to raise out of memory exception.

Support memory pool for FFT functions

---

cupy/core/include/cupy/carray.cuh
tests/cupy_tests/core_tests/test_carray.py

This fixes #854.
The minimum code to reproduce this issue is:
```py
size = 2 ** 32 - 127
a = cupy.ndarray((size,), dtype='b')
f = cupy.core.create_ufunc('test', ('b->b',), 'out0 = in0;')
out = f(a)
```
The computation `blockDim.x * gridDim.x` (both are typed as `unsigned int`) overflows and becomes 0, which makes CUPY_FOR run forever.

fix array iteration index overflow

---

MANIFEST.in
cupy_setup_build.py

This PR fixes #906.
* Exclude Cython source files from sdist distribution (on PyPI).
* If Cython source is missing on installation, fallback to use `*.cpp`.

exclude Cython files from sdist

---

cupy/core/core.pyx
tests/cupy_tests/linalg_tests/test_einsum.py
tests/cupy_tests/math_tests/test_matmul.py

Also changed tests to include complex arrays. Relates to issue #915.

enable complex tensors for cupy.matmul and cupy.einsum

---

cupy/cuda/cufft.pyx
cupy/cuda/cupy_cufft.h
examples/stream/cufft.py

Support CUDA stream on `cupy.cuda.cufft`.
I verified by running `nvprof --print-gpu-trace python examples/stream/cufft.py`.

Support CUDA stream on FFT

---

cupy_setup_build.py
install/build.py
tests/install_tests/test_build.py

This PR tries to fix issue #669.
Currently many users are frequently trapped with installation issues.
I want to mitigate this situation by making messages more friendly.
By applying this PR, the following configuration summary is printed.
```
************************************************************
* CuPy Configuration Summary                               *
************************************************************
Build Environment:
Include directories: ['/usr/local/cuda/include']   
Library directories: ['/usr/local/cuda/lib64']
nvcc command       : ['/usr/local/cuda/bin/nvcc']
Environment Variables:
CFLAGS          : (none)
LDFLAGS         : (none)
LIBRARY_PATH    : /home/kenichi/.nccl/active/cuda/lib64:/home/kenichi/.cudnn/active/cuda/lib64:/home/kenichi/.cudnn/active/cuda/lib6 …
```

improve message during installation

---

cupy/core/__init__.py
cupy/core/core.pyx
tests/cupy_tests/manipulation_tests/test_join.py

This bug is from #452.
`concatenate` crash when it gets mixed dtype array.
And, this PR improve performance. The test code is [here](https://gist.github.com/okuta/ea732a251feea32ab80226ab6fa5ffe3)
```
shape: (256, 256, 256), axis: 0, order: C, elapsed: 16.1625622559
shape: (256, 256, 256), axis: 0, order: F, elapsed: 131.348251953
shape: (256, 256, 256), axis: 1, order: C, elapsed: 16.1895678711
shape: (256, 256, 256), axis: 1, order: F, elapsed: 130.555195312
shape: (256, 256, 256), axis: 2, order: C, elapsed: 16.4942749023
shape: (256, 256, 256), axis: 2, order: F, elapsed: 131.340351562
shape: (128, 128, 128), axis: 0, order: C, elapsed: 2.06588348389
shape: (128, 128, 128), axis: 0, order: F, elapsed: 10.6780529785
shape: (128, 128, 128), axis: 1, order: C, elapsed: 2.08701797485 …
```

Fix concatenate bug and improve performance

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
cupy/cuda/stream.pyx
tests/cupy_tests/cuda_tests/test_memory.py

I checked generated code by Cython. If object has no cycle reference, __dealloc__ is safe IMO.
Please see also #381.
And, this PR uses `atexit` to avoid error at exit.

Use __dealloc__ in memory object

---

.gitignore
cupy_setup_build.py
setup.py

This PR implements #768.  ~~Depends on #762.~~ (done)
The usage is as follows:
```
pip install wheel
python setup.py bdist_wheel \
--cupy-package-name cupy-cuda90                                          \
--cupy-wheel-lib ~/.cudnn/versions/v7.0.4-cuda9/cuda/lib64/libcudnn.so.7 \
--cupy-wheel-lib ~/.nccl/versions/v2.1-cuda9/cuda/lib64/libnccl.so.2     \
```
* Wheel packages are named `cupy-cuda{70,75,80,90}`.
`cupy` package remains as is (i.e., source install).
* cuDNN/NCCL shared library binaries are copied into the wheel.
The package size become approx. 50 (CUDA 7.0) to 250 MB (CUDA 9.0)
* CUDA shared library binaries are not copied into the wheel.
This is because CuPy depends on some non-redistributable CUDA files (e.g., headers and `libnvrtc-builtins.so`), so it is mandatory to have …

Support wheel build

---

cupy/fft/fft.py

The parameters `s` and `axes` of `_fft` are expected not to be integers. The implementation of master accepts integers unexpectedly. This PR fixes the behavior.

Remove unnecessary code in cupy.fft

---

cupy_setup_build.py
setup.py

This PR adds the option to inject long description from file, so that we can insert additional information for each wheel (like below) to be shown on each PyPI package page.
```
This wheel package requires CUDA 9.0.
Please see `Installation Guide <https://docs-cupy.chainer.org/en/latest/install.html>`_ for wheels for other CUDA versions or installation from source.
```

add --cupy-long-description option to inject long description for wheels

---

cupy/__init__.py
cupy/logic/comparison.py
tests/cupy_tests/logic_tests/test_comparison.py

I implemented isclose.
I want to discuss its specification for scalar values. When input values are scalars, numpy returns `bool` object. But in cupy, we need to transfer the data. I use `cupy.ndarray` in such case in this PR same as `cupy.sum`. How do you think about this problem?

Implement isclose

---

cupy/core/core.pyx
cupy/sorting/sort.py
tests/cupy_tests/sorting_tests/test_sort.py

This PR will improve the performance of cupy.partition and solve #478.
The algorithm is a simplification of [Jhonson et al. 2017](https://arxiv.org/abs/1702.08734).
I have not tuned the parameters yet and use naive selection sort internally.
In addition, in the worst case (the order of the input array is reversed) it will take a very long time.
Therefore, there are still room for improvement.
Now, the speed is several times faster than the naive sorting.
The benchmark data is [here](https://docs.google.com/spreadsheets/d/1JYoueD-ZoTMI2vlw8Ou64C4yJpgygznRqGSfDyuK6xk/edit?usp=sharing) and the benchmark code is same as #478.

Improve cupy.partition performance

---

cupy/core/core.pyx
cupy/core/internal.pxd
cupy/core/internal.pyx

~Please merge #747 first.~
This PR refactor `__getitem__` and `__setitem__` .
These have same code. So, I create new helper functions.
And, this PR contains some small  fixing.

Simplify __getitem__ and __setitem__

---

tests/cupy_tests/test_cudnn.py

`CUDNN_ACTIVATION_ELU` is a feature introduced in cuDNN v6.
https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v6/prod/Doc/cuDNN_v6.0_ReleaseNotes-pdf

fix test failure in cuDNN v5 which does not support CUDNN_ACTIVATION_ELU

---

cupy/core/fusion.py

Removed warnings for fuse.
See discussion in https://github.com/chainer/chainer/pull/4002 for details.

remove warning in cupy.core.fusion

---

cupy/__init__.py
cupy/_environment_check.pyx
cupy_setup_build.py

As wheel distribution is intorudced, it is more likely that environment mismatch happen.
This PR adds environment check ([as done in Chainer](https://github.com/chainer/chainer/blob/master/chainer/_environment_check.py)) so that runtime version is validated.

implement environment check

---

cupy_setup_build.py

fix to use rpath only when wheel libs are specified

---

cupy/core/core.pyx
cupy/cuda/stream.pxd
cupy/cuda/stream.pyx

Currently, we provides `set_default_stream` method.
I want to use default stream in `array` method.

Use current stream in array method

---

cupy/cuda/nccl.pyx

TL; DR: this pull request is for fault tolerance in ChainerMN.
To continue distributed training in ChainerMN, the training cluster must endure process failure and also the communicator must be reconstructed. The simplest way to enable reconstruction is to add explicit `destroy()` method, rather than reconstruction method. This change enables reconstruction like this:
```python
comm = nccl.NcclCommunicator(8, comm_id, 3)
...(node failure detected)...
comm.destroy()
new_rank = renew_rank()
comm = nccl.NcclCommunicator(7, comm_id, new_rank)
...(resume computation)...
```
See [another example](https://gist.github.com/kuenishi/370df96974051b2dc6159366a8f62d7d) for working code. Maybe I could add null-checking code for all other methods than `destroy()`, but don't want to mess up current code …

Add destroy method to NcclCommunicator

---

cupy/core/core.pyx
cupy/linalg/solve.py
cupy/statistics/meanvar.py
tests/cupy_tests/statics_tests/test_meanvar.py

Currently `cupy.linalg.inv` computes the matrix inverse by calling `solve` with an identity matrix. This can be accomplished more quickly by instead using LU factorization and calls to CUDA's `getrf` and `getrs` functions.
I use the following code to test speed:
```
np.random.seed(0)
samples = np.random.random(size=(2000, 2000)).astype(np.float64)
%timeit cp.linalg.inv(cp.array(samples))
```
Current `master` produces:
`874 ms ± 11.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`
With this PR, the output is:
`224 ms ± 1.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)`
Finally, in comparing the output of the original function to the output of the modified function, `np.allclose(inv_LU, inv_QR)` returns `True`.
This PR includes the …

improve matrix inverse speed using LU decomposition

---

docs/source/index.rst
docs/source/upgrade.rst

This PR adds upgrade guide for CuPy v2 and v4.
This fixes #878.
Remove v4 part when backporting.

add upgrade guide for v2 & v4

---

docker/python2/Dockerfile
docker/python3/Dockerfile

This PR changes the base Docker image from CUDA 7.5 to 8.0 (as done in Chainer https://github.com/chainer/chainer/pull/3902), and use CuPy wheel for installation.

update to CUDA 8.0 and use CuPy wheels in Dockerfiles

---

cupy/core/core.pyx
tests/cupy_tests/indexing_tests/test_indexing.py

In numpy, [`ndarray.diagonal(x, offset, axis1, axis2)`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.diagonal.html) accepts negative axis for both axis1 and axis2. The smallest negative axis we can specify is `-x.ndim` (i.e., the range of axis1 and axis2 is `-x.ndim <= axis < x.ndim` ).
However, in cupy, the same method cannot accept `axis2=-x.ndim` (i.e., the range of axis2 is `-x.ndim < axis < x.ndim` ).
This inconsistency between numpy and cupy does not seem to be intended.
This PR allows `axis2` to be `-x.ndim` .
```python
import cupy
x_np = np.arange(16).reshape(4, 4)
y_np21 = x_np.diagonal(axis1=-2, axis2=-1)
print('y_np21 =', y_np21)
y_np12 = x_np.diagonal(axis1=-1, axis2=-2)
print('y_np12 =', y_np12)
np.testing.assert_array_equal(y_np21, …
```

Fix ndarray.diagonal to accept appropriate argument of axis2

---

cupy/sparse/coo.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_coo.py

NumPy does not call `sum_duplicates` in `eliminate_zeros`. I removed this call.
related to #834

Fix eliminate zeros

---

docs/source/reference/index.rst

Tree in the left pane has a redundant hierarchy and difficult to access.
https://docs-cupy.chainer.org/en/stable/reference/index.html#module-cupy

remove unnecessary heading from reference

---

docs/source/install.rst
install/build.py

* Support CUDA 9.1
* Add wheel instructions for `cupy-cuda91`
* Remove pretty-formatting of CUDA version, because CUDA 9.1 (`libcudart.so.9.1`) returns `9010` instead of `9100`

Support CUDA 9.1

---

cupy/linalg/norms.py
tests/cupy_tests/linalg_tests/test_norms.py

[backport] Fix return type of linalg.norm for complex input

---

cupy_setup_build.py

Exception message was not printed correctly during Windows build failure.

fix exception handling fail on Windows with Python 3.x

---

cupy/core/reduction.pxi

The j-stride of the loop should be `block_size / block_stride` instead of `block_size`,  where `block_stride` is the length of a block for the direction of i-axis.
Currently this error hasn't caused bug, because the current blocking strategy is to minimize `block_stride` and avoid the loop over j-axis. So if the loop is still required, `block_stride` has been always 1.
But it causes bug if the blocking strategy is changed. Furthermore, it is very confusing for those who read the code. I believe the error is very harmful for maintainability.

fix potential error at the stride for loop over the j-axis in RedutionKernel

---

cupyx/__init__.py
cupyx/rsqrt.py
docs/source/reference/ext.rst
tests/cupyx_tests/test_rsqrt.py

This PR implements `cupy.rsqrt` as discussed in https://github.com/chainer/chainer/issues/4092.

Add `cupyx.rsqrt`

---

docs/source/upgrade.rst

For change introduced in https://github.com/cupy/cupy/pull/991.
The same sentence as in Chainer upgrade guide.
https://github.com/chainer/chainer/blob/v4.0.0b4/docs/source/upgrade.rst#update-of-docker-images

add Docker update information to upgrade guide

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

We want to use following code.
```
@cuda.fuse(input_num=None)
def hoge(x, y, z):
z[...] = x + y
return z
```
This feature is requested in chainer/chainer#4162 .

Implement __setitem__ in fusion function

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

`tmpvars` is a set of variables that are defined in a given function. `mem.var_list[0:len(in_vars)]` is `in_vars`. We need to skip all these variables.
fix #1019

Fix temporary variables which are used when input_num is given

---

cupy/cusparse.py
cupy/sparse/csc.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

When a sparse matrix has duplicated entries, matrix multiplication does not work correctly.
merge #833 first

Fix matrix multiplication when matrixes have duplicated entries

---

cupy/cuda/__init__.py

When cusolver has a bug and cupy fails to import cusolver, the error is ignored and reports wrong error. It is better to check CUDA version.

Use CUDA version to decide if it import cusolver or not

---

cupy/core/core.pyx
docs/source/reference/ufunc.rst

`cupy.scatter_add` is deprecated. #894
This PR fixes to use `cupyx.scatter_add`.

Fix scatter_add docs

---

docs/source/contribution.rst
docs/source/install.rst

We should encourage pip. Corresponding to https://github.com/chainer/chainer/pull/4366.

Prefer pip in documentation

---

cupy/cuda/nvrtc.pyx

According to the [API reference of NVRTC](http://docs.nvidia.com/cuda/nvrtc/index.html#group__compilation_1gc622d6ffb6fff71e209407da19612c1a), sizes returned by `nvrtcGetPTXSize` and `nvrtcGetProgramLogSize` includes trailing NULL.
As a result, when the error occur, garbage appears at the end.

remove trailing NULL from values returned from NVRTC

---

cupy/manipulation/basic.py
tests/cupy_tests/manipulation_tests/test_basic.py

Fix cupy.copyto ignore where argument when src is scalar

---

cupy/manipulation/basic.py
tests/cupy_tests/manipulation_tests/test_basic.py

[backport] Fix cupy.copyto ignore where argument when src is scalar

---

cupy/cuda/cudnn.pyx

cuDNN v7 adds following new status values:
```
CUDNN_STATUS_RUNTIME_PREREQUISITE_MISSING = 11,
CUDNN_STATUS_RUNTIME_IN_PROGRESS          = 12,
CUDNN_STATUS_RUNTIME_FP_OVERFLOW          = 13,
```
However they haven't added in the dictionary.
As `cudnnGetErrorString` returns the string version of the status (e.g., `CUDNN_STATUS_SUCCESS`), current error message is redundant. I think we don't have to manage the dict.

remove cudnn STATUS dict

---

docs/source/reference/ndarray.rst

This PR fixes to use `:func:` instead of `:meth:`.

Fix broken link to numpy.sum

---

docs/source/license.rst

I add SciPy license to the document.
SciPy license was already added to LICENSE file (#196), but it was not reflected in the document.

Add SciPy license to document

---

tests/cupy_tests/test_cudnn.py

Fix test failure introduced in #715.

skip cuDNN tests when cuDNN is unavailable

---

cupy/testing/__init__.py
cupy/testing/helper.py
docs/source/reference/testing.rst
tests/cupy_tests/testing_tests/test_helper.py

The original implementation of shaped_random always generates real number even if `dtype` indicates complex number.

Fix shaped_random for complex number

---

appveyor.yml
appveyor/install-cuda.ps1
appveyor/install.ps1
appveyor/run_with_env.cmd

This PR adds AppVeyor test for CuPy.
Limitations (I'd like to solve these in separate PR):
* Currently only Python 3.6.x is tested.
As for Python 2.7, I spent some time to let NVCC use Visual C++ 9.0 (which seems required as Python 2.7 is built with VC++ 9.0) on AppVeyor, but so far failing.  Currently I don't have a local environment to build CuPy on Windows + Python 2.7, so I'll try this problem again once I can try building CuPy locally.
* Currently it only checks if the build succeeds.
As CUDA installer does not install CUDA Driver (`nvcuda.dll`) when GPU is not available, we cannot even import the CuPy module.
I'm still finding a solution to this issue.

add AppVeyor configuration

---

docs/source/tutorial/basic.rst

Chainer introduced `backends` subpackage. chainer/chainer#3974
Due to this change, `chainer.cuda` moved to `chainer.backends.cuda`.
I fix broken links to Chainer's `to_cpu` and `to_gpu`.

Update documentation for `chainer.backends.cuda`

---

cupy/cuda/cupy_cuda.h
cupy/cuda/driver.pxd
cupy/cuda/driver.pyx

This PR exposes low-level CUDA functions for manually modifying the CUDA context. I found it useful when using `cupy` with the `multiprocessing` module, as it will create superfluous CUDA contexts that need to be removed manually.
One design issue is that only `devicePrimaryCtxGetState` is a Python function, since it returns a tuple, while the other functions are defined with `cpdef`. Do you have any opinion on whether this function should also be exposed to the Cython side with `cpdef`?

Expose context management API in driver

---

cupy/core/core.pyx
tests/cupy_tests/manipulation_tests/test_transpose.py

Embarrasingly, my cupy.moveaxis behavior is different from numpy if destination is not ascending order.
I fixed it and added tests.

Fix moveaxis bug

---

cupy/core/core.pyx
cupy/padding/pad.py
tests/cupy_tests/padding_tests/test_pad.py

Currently, `cupy.pad` only accepts `mode='constant'` and I'd like to use it with `mode='reflect'`.
Mostly, I copied some functions from `numpy.pad` and should I write the notice for it?
Or the declaration in `LICENSE` file is enough?

Add 'edge' and 'reflect' mode to cupy.pad

---

docker/python2/Dockerfile
docker/python3/Dockerfile

I found that Docker build for Python 2.x is failing with `MemoryError` on Docker Hub.
https://hub.docker.com/r/cupy/cupy/builds/bkjms5j4pjhdw4vwynzjf7v/
It seems it hits the memory limit while downloading wheels.
I confirmed that `--no-cache-dir` reduces the memory usage and succeed to build.
It also improves the footprint of the image size.

use --no-cache-dir in Dockerfile

---

cupy/testing/helper.py

"with all dtypes" -> "with unsigned dtypes"
In addition, I make documents of `for_*_dtypes` uniform.

Fix document of for_unsigned_dtypes

---

tests/cupy_tests/linalg_tests/test_einsum.py

Tests will fail in some environments (e.g., Windows) that does not support `complex256`.
`testing.for_all_dtypes` does not emit `complex256` test case, so this condition is not needed.

remove platform-dependent dtype

---

cupy/cuda/__init__.py
cupy/cuda/pinned_memory.pyx
cupy/indexing/generate.py
cupy/math/rounding.py
cupy/math/sumprod.py
cupy/prof/time_range.py
cupy/random/distributions.py
cupy/random/generator.py
cupy/sparse/base.py
cupy/sparse/coo.py
cupy/sparse/csc.py
cupy/sparse/csr.py
cupy/sparse/linalg/solve.py
cupyx/scatter.py
docs/source/reference/cuda.rst
docs/source/reference/fft.rst
docs/source/reference/sorting.rst

I fix wrong references using nitpicky mode of Sphinx.
Enable nitpicky mode is suggested (#657), but it is a bit difficult to fix all warnings.
Therefore, I first write PR about fixing easy errors.

Fix wrong references of document

---

cupy/linalg/product.py

`out` is not available in CuPy nor NumPy.
See https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.tensordot.html

remove invalid argument description in cupy.tensordot

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_complex_ops.py

This PR fixes the issue #799 that in-place modification of `real` and `imag` does not work.
~~TODO: add test.~~ (done)

Fix a.real and a.imag to return view

---

cupy/cuda/cublas.pyx
cupy/cuda/cudnn.pyx
cupy/cuda/cusolver.pyx
cupy/cuda/cusparse.pyx

Some cuSPARSE/cuSOLVER/cuDNN/cuBLAS calls were not using stream.
This PR fixes #1086.

Use streams when calling libraries

---

cupy/core/carray.pxi
cupy/core/include/cupy/atomics.cuh
cupy/sparse/compressed.py
cupy/sparse/coo.py
cupy/sparse/util.py
setup.py

This PR aims to support double precision `atomicAdd` on Maxwell or older GPUs. This is related to chainer/chainer#4397.

Support double precision atomicAdd on Maxwell or older GPUs

---

cupy/core/core.pyx
cupy/core/internal.pyx
tests/cupy_tests/manipulation_tests/test_join.py

Fix cupy.concatenate to support arrays with >= 2**31 elements

---

cupy/core/core.pyx
cupy/core/internal.pyx
tests/cupy_tests/manipulation_tests/test_join.py

[backport] Fix cupy.concatenate to support arrays with >= 2**31 elements

---

cupy/cuda/compiler.py
tests/cupy_tests/cuda_tests/test_compiler.py

Fixes #1048.
See also: http://docs.nvidia.com/cuda/nvrtc/index.html#group__options

limit arch to the maximum value allowed in each NVRTC version

---

cupy/__init__.py
cupy/core/carray.pxi
cupy/cuda/__init__.py
cupyx/__init__.py
cupyx/runtime.py
tests/cupy_tests/test_init.py
tests/cupyx_tests/test_runtime.py

* `cupy.show_config` is a counterpart for `numpy.show_config` that prints configuration information to stdout.
Note that `cupy.show_config` prints both compile-time and runtime info, whereas `numpy.show_config` only prints compile-time info.
* `cupyx.get_runtime_info` is a hidden API to be used in Chainer (see PR https://github.com/chainer/chainer/pull/4298)

Implement cupy.show_config and cupyx.get_runtime_info

---

tests/cupy_tests/testing_tests/test_helper.py

I use `six.assertRaisesRegex` instead of `numpy.testing.assert_raises_regex`. `numpy.testing.assert_raises_regex` depends on nose. (Note that it's fixed in the master branch.)
https://github.com/numpy/numpy/blob/v1.14.0/numpy/testing/nose_tools/utils.py#L1194-L1223

Remove nose dependency

---

docs/source/install.rst

As many users are reporting installation failures, I reorganized the Installation Guide.
Major changes compared to the current one is to recommend use of wheels as the first choice.

rewrite installation guide

---

cupyx/__init__.py
cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/interpolation.py
docs/source/reference/index.rst
docs/source/reference/ndimage.rst
setup.cfg
setup.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

I implement multi-dimensional image processing as `cupyx.scipy.ndimage`. This is a subset of `scipy.ndimage` interface. Some options for parameters are not supported and it has two differential features.
- Support additional mode, `opencv`. If it is given, the function performs like the behavior of OpenCV's functions.
- Change default order from 3 to 1. If `order` option is not given, it outputs a warning. It may change in the future, but it is not decided. Therefore I think `FutureWarning` is not necessary.

Implement multi-dimensional image processing

---

cupy/__init__.py

This PR exposes the following dtypes to improve interoperability with NumPy.
(I found this issue during porting code from NumPy to CuPy)
```py
from numpy import complexfloating
from numpy import generic
from numpy import bool8  # NOQA
from numpy import intp  # NOQA
from numpy import uintp  # NOQA
from numpy import double  # NOQA
from numpy import int  # NOQA
from numpy import bool  # NOQA
from numpy import float # NOQA
from numpy import complex # NOQA
```
Fixes #1043.

expose all supported dtypes from numpy

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h
cupy/cudnn.pyx

This PR aims to use v7 APIs of cuDNN in order to get appropriate convolution algorithms when TensorCore is available.  This is a split from #890.

Use cuDNN v7 APIs to get conv algos for TensorCore

---

cupyx/runtime.py

Functions like `cupy.cuda.runtime.runtimeGetVersion()` could cause an error and `cupy.show_config()` does not handle it.
Previously:
```
>>> cupy.show_config()
File "/data2/work/w/repos/cupy/cupy/__init__.py", line 691, in show_config
sys.stdout.write(str(cupyx.get_runtime_info()))
File "/data2/work/w/repos/cupy/cupyx/runtime.py", line 63, in get_runtime_info
return _RuntimeInfo()
File "/data2/work/w/repos/cupy/cupyx/runtime.py", line 33, in __init__
self.cuda_runtime_version = cupy.cuda.runtime.runtimeGetVersion()
File "cupy/cuda/runtime.pyx", line 150, in cupy.cuda.runtime.runtimeGetVersion
cpdef int runtimeGetVersion() except *:
File "cupy/cuda/runtime.pyx", line 153, in cupy.cuda.runtime.runtimeGetVersion …
```

 Handle errors in cupy.show_config()

---

cupy/cuda/runtime.pyx

`Error` is already declared in `runtime.pxd`: https://github.com/cupy/cupy/blob/v4.0.0rc1/cupy/cuda/runtime.pxd#L15, to share `Error` declaration with  `profile.pyx`.
This fixes the warning message during installation.
```
warning: cupy/cuda/runtime.pyx:33:4: 'Error' redeclared
```

fix duplicate delcaration of cudaError_t

---

cupy/indexing/generate.py

This PR enables flake8 in `cupy/indexing/generate.py`. It has been disabled accidentally.

Enable flake8 in cupy/indexing/generate.py

---

cupy/cuda/memory_hook.pyx
cupy/cuda/memory_hooks/debug_print.py

I fix wrong references of `MemoryHook`'s document. It has referred to `cupy.cuda.memory.SingleDeviceMemoryPool` and `cupy.cuda.memory.PooledMemory`, but they are hidden.
This PR relates to #1078.

Fix document of MemoryHook

---

cupy/linalg/solve.py
tests/cupy_tests/linalg_tests/test_solve.py

I'm using CuPy 4.0.0rc1 with CUDA 9.1 on CentOS 7.4.
`cupy.linalg.inv()` breaks its argument just like #842.
I pasted a code to reproduce the problem at the bottom.
My PR has two problems:
1. The PR is time- and space-consuming because it always copies the given matrix. It might be better to introduce `overwrite_a` as in `scipy.linalg.inv()`.
2. Test is not extensive. I noticed that the problem does not reproduce for some matrices (e.g. lower-triangular matrix in row-major format).  The test should cover such a special/corner cases.
A code to reproduce the problem is as follows:
```
import scipy as sp
import scipy.linalg
ndim = 10
#init_x = np.tril(np.random.random((ndim, ndim)), -1)
init_x = np.triu(np.random.random((ndim, ndim)), +1)
init_x += …
```

fix cupy.linalg.inv() breaks its argument

---

cupyx/runtime.py
tests/cupyx_tests/test_runtime.py

[backport] fix to capture CuDNNError in cupyx.runtime

---

cupy/cuda/compiler.py
tests/cupy_tests/cuda_tests/test_compiler.py

The maximum value should not be a platform-specific CC.

do not use platform-specific CC

---

cupy/random/permutations.py
docs/source/reference/random.rst
tests/cupy_tests/random_tests/test_permutations.py

Fix incompatibility between cupy.random.permutation and numpy.random.permutation .

---

tests/cupy_tests/core_tests/test_fusion.py

Difference of outputs from `cupy.power` and `numpy.power` are larger than we expected with complex number in Windows.
I adjusted tolerance to avoid test failures.

Separate tests for cupy.power against complex dtype

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

(This PR consists of two parts: bug fix and comment improvements. Please review commit-by-commit.)
Under the following circumstances, an exception is raised during freeing chunk.
As a result, it will leak memory as the chunk being freed does not go back to arena of the memory pool.
Here is a code to reproduce the issue:
```py
import cupy
def malloc(x):
return cupy.zeros(x, dtype=cupy.int8)
def make_garbages():
garbages = []
for i in range(1024):  # 1024 = compaction_threshold * 2
garbages.append(malloc(512 * (i + 1)))  # 512 = alloc_unit
return garbages
garbages = make_garbages()
del garbages
garbages = make_garbages()
m1 = malloc(512*2048)
del m1
m2 = malloc(512*1024)  #  split
m3 = malloc(1024)  # trigger compaction
print("-- exception --")
del m3
print("-- end --")
```
You will see …

Fix memory leak (mempool tries to find out-of-bounds bin when freeing chunk)

---

cupy/linalg/einsum.py
tests/cupy_tests/linalg_tests/test_einsum.py

[backport] Fix regex in einsum to match empty input subscript

---

cupy/core/elementwise.pxi

On Windows, int scalars must be 32-bit when it fits it.

Fix scalar casting rule to support Windows

---

tests/cupy_tests/core_tests/test_fusion.py

[backport] Separate tests for cupy.power against complex dtype

---

tests/example_tests/test_finance.py

[backport] Fix example test to pass on Windows

---

cupy/testing/__init__.py
cupy/testing/helper.py
tests/cupy_tests/core_tests/test_elementwise.py
tests/cupy_tests/math_tests/test_arithmetic.py
tests/cupy_tests/math_tests/test_misc.py

[backport] skip int8.max test on Windows due to NumPy bug

---

.coveragerc

This PR fixes the bug which the coverage of `cupyx` has not been measured.

Fix .coveragerc

---

.gitignore

pyd files are generated while building Windows DLL (Python modules).

Fix gitignore to exclude pyd files

---

cupy/creation/matrix.py
tests/cupy_tests/creation_tests/test_matrix.py

By using the latest GitHub master, `cupy.diag()` fails when a list or a tuple is given.
It reproduces as follows:
```
$ python
...
>>> cupy.diag((1,2,3))
File ".../cupy/cupy/creation/matrix.py", line 28, in diag
if v.ndim == 1:
AttributeError: 'tuple' object has no attribute 'ndim'
```

fix cupy.diag() fails for array_likes other than CuPy arrays

---

cupy/cuda/cufft.pyx
tests/cupy_tests/fft_tests/test_fft.py

This PR adds a workaround about `CUFFT_ALLOC_FAILED` (#1063). Even after it is merged, the reported error at #1063 is not resolved because memory compaction has not been introduced (#536).

Free pooled memory when cufftMakePlan1d cannot allocate memory

---

cupy/linalg/norms.py
tests/cupy_tests/linalg_tests/test_norms.py

In NumPy 1.14, np.linalg.norm has been changed to preserve dtype of input array.
However, as fix made in NumPy 1.14 was incomplete, there are some cases (e.g., when arbitrary order is specified) that dtype is not preserved.
The issue is recognized by the team and the additional fix is ongoing.
* https://github.com/numpy/numpy/issues/10364
* https://github.com/numpy/numpy/pull/10368
This PR makes CuPy behavior consistent with NumPy 1.14.1 (assuming the above PR got merged and released).
We need to discuss if we should separate tests for `<1.14`, `==1.14`, '>1.14'.
(Maybe we can ignore `==1.14` ... but in that case, can we say that we support NumPy 1.14?)

Fix to preserve dtype of input array in cupy.linalg.norm

---

cupy/core/reduction.pxi

Fix a compilation error like following found by @toslunar. The cause is that there are no implicit conversions from `float16` to `complex<float>` and from `float16` to `complex<double>`.
```
>>> cupy.sum(cupy.arange(3).astype(cupy.float16), dtype=cupy.complex64)
File "/home/user/local/miniconda3/envs/chainer2/lib/python2.7/site-packages/cupy/core/fusion.py", line 833, in __call__
return self._cupy_op(*args, **kwargs)
File "/home/user/local/miniconda3/envs/chainer2/lib/python2.7/site-packages/cupy/math/sumprod.py", line 25, in sum
return a.sum(axis, dtype, out, keepdims)
File "cupy/core/core.pyx", line 1139, in cupy.core.core.ndarray.sum
File "cupy/core/core.pyx", line 1147, in cupy.core.core.ndarray.sum
File …
```

Fix conversion from float16 to complex

---

tests/cupy_tests/core_tests/test_carray.py

On Windows, reduction does not promote to int64.
```py
>>> import numpy as np
>>> x = np.ones(2**31, dtype='b').sum()
>>> x
-2147483648
>>> x.dtype
dtype('int32')
```
CuPy behaves the same way.

Fix 32-bit boundary test to support Windows

---

tests/cupy_tests/core_tests/test_carray.py

[backport] Fix 32-bit boundary test to support Windows

---

cupy/creation/basic.py
tests/cupy_tests/creation_tests/test_basic.py

This PR fixes #1203. The default `dtype` of `cupy.full` should be determined by `fill_value`.

Fix default dtype of full

---

cupy/cuda/thrust.pyx

Thrust may raise C++ exceptions.
We should translate it, otherwise python process will abort when exception is thrown.
```
File "test.py", line 11, in test
cupy.unique(arr, return_inverse=True)
File "/home/kenichi/Development/cupy/cupy/manipulation/add_remove.py", line 65, in unique
perm = ar.argsort()
File "cupy/core/core.pyx", line 844, in cupy.core.core.ndarray.argsort
thrust.argsort(self.dtype, idx_array.data.ptr, data.data.ptr, 0,
File "cupy/cuda/thrust.pyx", line 100, in cupy.cuda.thrust.argsort
cpdef argsort(dtype, size_t idx_start, size_t data_start, size_t keys_start,
RuntimeError: radix_sort: failed to get memory buffer: out of memory
```

catch C++ exceptions from Thrust

---

cupy/linalg/norms.py
tests/cupy_tests/linalg_tests/test_norms.py

Fix for NumPy 1.14 on Windows.
In NumPy 1.14, `matrix_rank` has been rewritten to use `count_nonzero` (which results in `int64`) instead of `sum` reduction (which results in `int32` on Windows).

Fix linalg.matrix_rank casting for Windows

---

cupy/cuda/memory.pyx

CuPy sometimes raises `OutOfMemoryError` even if there are sufficient large freeable chunks.
A code to reproduce the problem is at the bottom.
`SingleDeviceMemoryPool._malloc()` tries to `cudaFree()` unused freeable chunks using `free_all_blocks()` and `gc.collect()` in some cases.  But because there are some local variables referencing the freeable chunks, they can't be reclaimed and remains until `_malloc()` ends (unfortunately, by `OutOfMemoryError`).
This PR fixes the problem by clearing such local variables.
The following code reproduces the problem:
```
import cupy
free, total = cupy.cuda.runtime.memGetInfo()
assert free > total*0.97
blob_30pct_1 = cupy.empty(int(0.3*free), dtype=cupy.uint8)
blob_30pct_2 = cupy.empty(int(0.3*free), dtype=cupy.uint8)
del blob_30pct_2
blob_60pct_1 = …
```

fix OutOfMemoryError raised even when there are sufficient large freeable chunks

---

cupy/cuda/memory.pyx

[backport] fix OutOfMemoryError raised even when there are sufficient large freeable chunks

---

cupy/core/core.pyx
setup.cfg
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

- complex to bool checks if each element is non-zero
- complex to int and complex to float uses real part
```
>>> numpy.array([0+1j]).astype('?')
array([ True], dtype=bool)
>>> numpy.array([0+1j]).astype('i')
__main__:1: ComplexWarning: Casting complex values to real discards the imaginary part
array([0], dtype=int32)
>>> numpy.array([0+1j]).astype('f')
array([ 0.], dtype=float32)
```
fix #1276

Fix astype for complex dtypes

---

cupy/creation/matrix.py
tests/cupy_tests/creation_tests/test_matrix.py

[backport] fix cupy.diag() fails for array_likes other than CuPy arrays

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h

This PR aims to improve performance of batch normalization on GPU.
cuDNN batch normalization may not be so fast sometime specifically when batch size and/or channel size is small and image size is big. The **CUDNN_BATCHNORM_SPATIAL_PERSISTENT** mode that is supported by cuDNN 7.0 or later can improve the performance for that cases. This PR is related to this mode and allows you to use this mode for batch normalization layers in your models.
Please take a look at [here](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnBatchNormMode_t) for details about **CUDNN_BATCHNORM_SPATIAL_PERSISTENT**.

Improve performance of batch normalization

---

cupy_setup_build.py
install/build.py

This PR enables bundling DLLs into wheels for Windows.
```
python setup.py bdist_wheel \
--cupy-wheel-lib "C:\Program Files\NVIDIA Corporation\NvToolsExt\bin\x64\nvToolsExt64_1.dll" \
--cupy-wheel-lib "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\cudnn64_7.dll"
```

Support bundling dependent DLLs for Windows wheel support

---

cupy/core/include/cupy/complex.cuh
cupy/math/rounding.py
cupy/math/ufunc.py
tests/cupy_tests/math_tests/test_rounding.py

`rint` is applied to both real and imag.
related to #1281

Support rounding for complex types

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_complex_ops.py

[backport] Fix `real`, `imag` of non-contiguous complex arrays

---

docs/source/install.rst

[backport] Add NumPy 1.14 to supported versions

---

cupy/core/core.pyx
docs/source/_templates/autosummary/class.rst

Some `cpdef` methods in cython `cdef` class seems to become `wrapper_descriptor`:
```py
>>> type(cupy.ElementwiseKernel.__call__)  # cdef class
<class 'wrapper_descriptor'>
>>> type(cupy.ReductionKernel.__call__)  # class
<class 'cython_function_or_method'>
```
Sphinx cannot decide if `wrapper_descriptor` is a method or an attribute, and mis-recognize it as an attribute, as attributes have higher priorotiy than methods.
https://github.com/sphinx-doc/sphinx/blob/v1.7.4/sphinx/ext/autodoc/__init__.py#L1325-L1327
This PR changes the template to force render known methods as method even if it is recognized as attributes.
This fixes #458 (`ElementwiseKernel.__call__` is not documented), and also adds docs for some important methods like `cupy.ndarray.__getitem__`.
See …

Force displaying known methods which are mis-recognized as attributes by Sphinx

---

setup.py

Similar to https://github.com/chainer/chainer/pull/4846, [imp.load_source](https://docs.python.org/3/library/imp.html), the undocumented function in Python3, is advised to be excised from setup.py

Remove deprecated imp.load_source in setup.py

---

setup.cfg

Include license file to wheel distribution.
`license.rst` will be installed under `.../site-packages/cupy-5.0.0b1.dist-info/LICENSE.txt`.
Note: currently wheel does not support adding multiple license files.
https://wheel.readthedocs.io/en/stable/#including-the-license-in-the-generated-wheel-file
Related to #1330

Add license file to wheel

---

cupy/testing/helper.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

We introduced `cupyx.scipy` namespace and have been adding functions. This PR adds `scipy_name` to simplify the testing of those functions.

Add scipy_name to testing helper functions

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

Improved fusion notation by allowing direct reduction.  This PR resolves #141.
```
@cupy.fuse()
def sample2(x, y):
return cupy.sum(x + y, axis=0) * 2
for xp in (numpy, cupy):
a = xp.array([[3, 1, 4, 1, 5], [9, 2, 6, 5, 3]], 'f')
b = xp.array([[2, 7, 1, 8, 2], [8, 1, 8, 2, 8]], 'f')
print(sample2(a, b))
```
```
[ 44.  22.  38.  32.  36.]
[ 44.  22.  38.  32.  36.]
```

Allow more natural fusion notation

---

cupy/core/fusion.py

Fix #1353.
```
>>> import numpy, cupy
>>> type(numpy.sum)
<class 'function'>
>>> type(cupy.sum)
<class 'function'>
```

Fix type of reduction

---

cupy/core/core.pxd

[backport] Support weak reference to CuPy array

---

README.md
docs/source/install.rst

Blocked by https://github.com/chainer/chainer-test/pull/431 and https://github.com/cupy/cupy-release-tools/pull/13

Update requirements for v5.0.0b2 / v4.2 release

---

cupy/linalg/norms.py
tests/cupy_tests/linalg_tests/test_norms.py

[backport] Fix to preserve dtype of input array in cupy.linalg.norm

---

cupy/linalg/__init__.py
cupy/linalg/product.py
tests/cupy_tests/linalg_tests/test_product.py

cc: @asi1024 and @kmaehashi, thank you for all the help put in so far. I am really sorry that I have had to redo this a few times.
To prep for this PR, I deleted my CuPy fork, re-forked CuPy, and applied the patch from the v2 PR (#1371) as a single commit. This PR closes #1358.

implemented matrix power with tests

---

cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/cuda/pinned_memory.pyx
tests/cupy_tests/core_tests/test_internal.py

This PR can reduce usage of pinned_memory when user copies arrays of multiple sizes.

[HIGH] Introduce clp2 to improve pinned_memory

---

cupy/core/core.pyx
cupy/testing/helper.py

[backport]  Support 'f' and 'c' in order

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_core.py

NumPy still supports longer order names (although it emits DeprecationWarning).
Fixes the issue introduced in #1385.

Fix to accept longer order names

---

tests/cupy_tests/linalg_tests/test_einsum.py

The PR #1334 was partial:
- The memory bug in old `np.einsum` is caused by wrong pointer increment.  Return value can be wrong whether or not einsum crashes.
- `@testing.for_all_dtypes_combination(full=False)` rarely contains `{'dtype_a': <class 'numpy.bool_'>, 'dtype_b': <class 'numpy.bool_'>, 'dtype_c': <class 'numpy.bool_'>}`.

Fix requirements of numpy in `test_einsum.py`

---

cupy/core/core.pyx
cupy/logic/type_test.py
tests/cupy_tests/creation_tests/test_from_data.py

Improve host to device memory copy

---

cupy/cudnn.pyx

This PR aims to fix the issue about inappropriate cuDNN convolution math type setting.
I observed a failure when running sort of imagenet training with fp16 enabled resnet50 network on Volta GPUs with TensorCore. The failure occurred when I set `config.autotune = True`. The cause was that cuDNN convolution math type was not set correctly. With `config.autotune = True`, cuDNN find APIs are called to decide which algo/implementation are the best in terms of performance for the given convolution. Sometimes, it returns an algo that is not TensorCore ready even when a GPU is Volta generation. In that case, cuDNN convolution math type has to be set back to `CUDNN_DEFAULT_MATH` but it is not done in current master branch. This PR will fix that issue.

Fix issue of cuDNN convolution math_type setting

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

This was inconsistent with `numpy` and so with functions in `cupy.random`.

Make the method `cupy.random.RandomState.interval` private

---

cupy/core/dlpack.pyx

Thank you for CuPy!
The DLManagedTensor interface has a "deleter" function that
is used to signal the creator of the DLManagedTensor that
the consumer does not need the memory anymore.
This tiny patch calls the deleter when the DLPackMemory
created by fromDlpack is destroyed.
This fixes #1443, the memory leak when consuming DLPacks created by PyTorch.
This is my first PR to CuPy. I did run the test_dlpack tests.

Fix fromDlpack memory management

---

cupy/core/include/cupy/carray.cuh
cupy/math/misc.py

This PR is related to #1094 and #1117 .
`numpy.fmax` complies with std c `fmax` function. But, `min` behaves same as `fmin` in CUDA. It is a little strange.
HIP doesn't have such behavior. So, this PR fix it.

Use fmin and fmax for HIP environment

---

cupy/cusparse.py
cupy/sparse/base.py
cupy/sparse/compressed.py
cupy/sparse/construct.py
cupy/sparse/coo.py
cupy/sparse/csc.py
cupy/sparse/csr.py
cupy/sparse/dia.py
cupy/sparse/linalg/solve.py
cupy/testing/helper.py

I converted `cupy.sparse` in docstrings. All links are now broken.
related to #1079

Convert cupy.sparse to cupyx.scipy.sparse in docstrings

---

cupy/__init__.py
tests/cupy_tests/core_tests/test_fusion.py

```
>>> import numpy, cupy
>>> @cupy.fuse()
... def f(x):
...     xp = cupy.get_array_module(x)
...     print(xp)
...
>>> f(numpy.array([1]))
<module 'numpy' from xxxxxxxxxx>
>>> f(cupy.array([1]))
<module 'cupy.core.fusion' from xxxxxxxxxx>
```

Allow `cupy.get_array_module` take fusion parameters

---

cupy/cuda/memory.pyx

I found memory error with Python3.7.
```
tests/cupy_tests/linalg_tests/test_einsum.py::TestEinSumError::test_invalid_diagonal1 Traceback (most recent call last):
File "cupy/cuda/memory.pyx", line 521, in cupy.cuda.memory.PooledMemory.free
pool = pool()
TypeError: 'NoneType' object is not callable
Exception ignored in: 'cupy.cuda.memory.PooledMemory.__dealloc__'
File "cupy/cuda/memory.pyx", line 521, in cupy.cuda.memory.PooledMemory.free
pool = pool()
TypeError: 'NoneType' object is not callable
```
This PR fixes it.

Avoid memory error

---

cupy/core/reduction.pxi

This PR suppresses warning in Python3.7.
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working```

Avoid collections.sequence

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

Fix #1461. This PR uses [cython.no_gc](https://github.com/cython/cython/blob/master/docs/src/userguide/extension_types.rst#controlling-cyclic-garbage-collection-in-cpython).
rel #1457

Use cython.no_gc to avoid memory leak

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

[backport] Use cython.no_gc to avoid memory leak

---

cupy/core/core.pyx
cupy/math/sumprod.py
tests/cupy_tests/manipulation_tests/test_split.py
tests/cupy_tests/math_tests/test_sumprod.py

This PR make the following functions support 0-sized input arrays.
- `cupy.cumsum`, `cupy.cumprod` (fix #1455)
- `cupy.split`, `cupy.array_split` (fix #1458)

Fix errors on 0-sized inputs

---

cupy/cudnn.pyx

This PR makes some cuDNN RNN related functions support FP16 and FP64 data types. This change is needed to make `chainer.functions.n_step_rnn` support these float data types following https://github.com/chainer/chainer/issues/4582 .

Support FP16 and FP64 in cuDNN RNN related functions

---

docs/source/upgrade.rst

Blocked by #1451.
to-be-backported for v4 part.

Add upgrade guide for cupyx namespaces

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_distributions.py

for now
```
>>> import numpy
>>> numpy.random.dirichlet([1,1,1], (100,3)).shape
(100, 3, 3)
>>> cupy.random.dirichlet([1,1,1], (100,3)).shape
(100, 3)
```
I fixed this.

fix cupy.random.dirichlet to behave same as numpy.random.dirichlet

---

cupy/core/core.pxd
cupy/core/core.pyx
tests/cupy_tests/math_tests/test_sumprod.py

`cumsum` and `cumprod` are already implemented.
But, `ndarray` does not have them. I will add them by this PR.

Add cumsum and cumprod to ndarray

---

cupy/core/_scalar.pxd
cupy/core/_scalar.pyx
cupy/core/reduction.pxi
cupy_setup_build.py

I got following error on CentOS6.
```
cupy/core/_scalar.cpp:964: error: member '__pyx_t_float_complex __pyx_t_4cupy_4core_7_scalar_Scalar::complex64_' with constructor not allowed in union
cupy/core/_scalar.cpp:965: error: member '__pyx_t_double_complex __pyx_t_4cupy_4core_7_scalar_Scalar::complex128_' with constructor not allowed in union
```

Avoid compile error in old GCC (CentOS6)

---

cupy/core/internal.pyx
cupy/linalg/product.py
cupy/util.pyx

We can replace `from cupy.util import collections_abc` with `from six.moves import collections_abc` once https://github.com/benjaminp/six/pull/241 got merged.

Use collections.abc to avoid DeprecationWarning in Python 3.7

---

cupy/core/internal.pyx
cupy/linalg/product.py
cupy/util.pyx

[backport] Use collections.abc to avoid DeprecationWarning in Python 3.7

---

cupy/core/core.pyx
cupy/core/dlpack.pyx
cupy/core/elementwise.pxi
cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
tests/cupy_tests/creation_tests/test_from_data.py
tests/cupy_tests/cuda_tests/test_memory.py
tests/cupy_tests/cuda_tests/test_pinned_memory.py

This PR reduce GPU device object. In most cases it is less expensive to keep the GPU device id.
No compatible point.
- `ndarray.device` will not be `None`. So far it is `None` when the array size is 0.

Reduce GPU device object

---

docs/source/tutorial/basic.rst

Proposal: add a hint to the agnostic code tutorial that `cupy.asarray` and `cupy.asnumpy` can be used for explicit conversions from generic arrays.
Calling out to code that requires a NumPy array and that fails when given a CuPy array is, I think, a common operation, e.g. when plotting. I think it would be helpful to beginners to mention that `cupy.asarray` and `cupy.asnumpy` are agnostic functions, and to provide a best practice example. These functions are only used in their intended directions in the tutorial, at least to me it was not obvious that they are actually agnostic.
I put in an example that throws `ValueError: object __array__ method not producing an array` to have this example turn up in a page for someone who runs into this issue.

Update agnostic code tutorial

---

cupy/core/core.pxd
cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py

This implements a special CUDA array interface attribute, analogous to the [`__array_interface__`](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.interface.html#__array_interface__) attribute on NumPy arrays.  This attribute is specifically for advertising CUDA device-compatible pointers (actual device allocations, or managed memory) and associated metadata.
This allows CuPy arrays to be used with Numba-compiled CUDA functions when combined with numba/numba#2860.

__cuda_array_interface__ implementation

---

cupy/core/core.pyx
tests/cupy_tests/sorting_tests/test_search.py

numpy supports `nonzero` for complex types.
```
>>> np.array([[1, 0], [2j, 3]]).nonzero()
(array([0, 1, 1]), array([0, 0, 1]))
```
In cupy, the kernel has `!= 0`, which results in the compile error below on complex inputs.
```
E           CompileException: /tmp/tmpq4wq7klq/kern.cu(15): error: no operator "!=" matches these operands
E                       operand types are: T != int
```
Merge #1487 first.

Support `nonzero` for complex types 

---

cupy/core/core.pyx
cupy/manipulation/rearrange.py
cupy/statistics/histogram.py
tests/cupy_tests/statics_tests/test_histogram.py

* Some exception types has been changed from `ValueError` to `numpy.AxisError` (which inherits from `ValueError`).
* `np.histogram` has been changed to decide dtype for bin edges based on input. (https://github.com/numpy/numpy/pull/10324)

Fix unit test errors in NumPy 1.15

---

cupy/core/core.pyx

NumPy dtype order
```
>>> numpy.equal.types
['??->?',
'bb->?',
'BB->?',
'hh->?',
'HH->?',
'ii->?',
'II->?',
'll->?',
'LL->?',
'qq->?',
'QQ->?',
'ee->?',
'ff->?',
'dd->?',
'gg->?',
'FF->?',
'DD->?',
'GG->?',
'OO->?',
'MM->?',
'mm->?',
'OO->O']
```

Fix create_comparison

---

cupy/random/_kernels.py
cupy/random/generator.py

[The test code](https://github.com/okuta/cupy-bench)
before
```
% python test_random.py
beta_cupy     , 32768, 2.584322, 0.115615
binomial_cupy , 32768, 0.494043, 0.117940
beta_numpy    , 32768, 8.867222, 8.865142
binomial_numpy, 32768, 2.167342, 2.165002
```
after
```
% python test_random.py
beta_cupy     , 32768, 0.190274, 0.114515
binomial_cupy , 32768, 0.129215, 0.115728
beta_numpy    , 32768, 7.926788, 7.924813
binomial_numpy, 32768, 1.830270, 1.828578
```

Use xorshift128 to reduce global memory access

---

docs/source/upgrade.rst

[backport] Add upgrade guide for cupyx namespaces

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

This PR reduces 20-30% memory allocation time. [Benchmark code](https://github.com/okuta/cupy-bench)
Please merge #1540 first.
before
```
% python alloc_empty.py
alloc, 2.559044, 2.557237
alloc_and_free, 3.869997, 3.868559
% python alloc.py
dummy_call, 0.000104, 0.000099
mem_0B, 0.000735, 0.000728
mem_1K, 0.001575, 0.001568
mem_1M, 0.001610, 0.001602
```
after
```
% python alloc_empty.py
alloc, 2.061816, 2.060394
alloc_and_free, 3.069911, 3.068501
% python alloc.py
dummy_call, 0.000107, 0.000102
mem_0B, 0.000647, 0.000641
mem_1K, 0.001154, 0.001147
mem_1M, 0.001180, 0.001174
```

Improve memory pool performance

---

cupyx/scipy/special/__init__.py
cupyx/scipy/special/erf.py
docs/source/reference/special.rst
tests/cupyx_tests/scipy_tests/special_tests/test_erf.py

`erfinv` and `erfcinv` are not included because different behavior of SciPy and CUDA. They will be implemented later.

Add erf, erfc, and erfcx to cupyx

---

cupy/testing/helper.py
cupyx/scipy/sparse/compressed.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

This PR supports old and new SciPy. Fix #680 .
- Accept sparse matrix in `numpy_cupy_allclose` and `numpy_cupy_array_equal`.
- Relax slicing restrictions
- Fix test to use new style test functions

Support SciPy1.0+

---

cupyx/scipy/special/bessel.py
cupyx/scipy/special/erf.py
tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
tests/cupyx_tests/scipy_tests/special_tests/test_erf.py

It seems that `scipy.special` converts `float16` to `float32`.
```python
>>> scipy.special.j0(numpy.ones((2,), dtype=numpy.float16))
array([0.7651977, 0.7651977], dtype=float32)
```

Fix result dtypes of special functions

---

cupy/core/reduction.pxi

This PR is a collection of partial commits from https://github.com/cupy/cupy/pull/1520.
Since we noticed that https://github.com/cupy/cupy/pull/1520 introduces backward compatibility, I cherry-picked patches only in python layer.
Changes:
* out_clp2_size ~~=> out_block_size~~ => block_stride
* clp2_count => reduce_block_size
* get_trans_args => get_permuted_args
* laxis => reduce_axis
* raxis => out_axis
* out_block_ num = (out_indexer.size + out_block_size - 1) // out_block_size

Improve readability of reduction kernel (only python)

---

cupyx/scipy/special/digamma.py
cupyx/scipy/special/gamma.py
cupyx/scipy/special/gammaln.py
cupyx/scipy/special/zeta.py

Resolve the problem like following:
```python
>>> cupyx.scipy.special.gamma(1)
File "/home/user/work/chainer/cupy/cupyx/scipy/special/gamma.py", line 41, in gamma
```

Improve usability of special functions

---

cupy/core/elementwise.pxi
cupy/core/fusion.py
cupy/core/reduction.pxi
cupy/random/generator.py

Merge #1552 and chainer/chainer#5258 first.
ElementwiseKernel should cause CUDA compilation error when trying to mutate `in_params` in the `operation`.

Make ElementwiseKernel emit immutable in_params

---

cupy/cuda/cupy_cuda.h
cupy/cuda/runtime.pyx

Fix #1574
Thrust uses `cudaGetLastError`. This PR resets it.

Reset cuda runtime error

---

cupy/core/include/cupy/carray.cuh

`/' and `%` are very slow on GPU.
The new version uses bit operation when the divisor is a power of 2.

Use bit operation when the divisor is a power of 2 on GPU

---

cupy/core/core.pyx
cupy/core/elementwise.pxi
cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/cuda/cublas.pxd
cupy/cuda/cublas.pyx
cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/curand.pyx
cupy/cuda/cusolver.pxd
cupy/cuda/cusolver.pyx
cupy/cuda/cusparse.pxd
cupy/cuda/cusparse.pyx
cupy/cuda/device.pxd
cupy/cuda/device.pyx
cupy/cuda/driver.pxd
cupy/cuda/driver.pyx
cupy/cuda/function.pyx
cupy/cuda/nvrtc.pxd
cupy/cuda/nvrtc.pyx
cupy/cuda/nvtx.pyx
cupy/cuda/profiler.pxd
cupy/cuda/profiler.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx
cupy/cudnn.pyx

CuPy uses a lot of `except *`, but there is a better way.
http://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#error-return-values
- Removing `void`. The PR uses `cpdef function(...)` instead of `cpdef void function(...)`.
- Using `except? 0` instead of `except *` when return type is `size_t` and `float`.
- Mostly, using `except? -1` instead of `except *` when return type is `int`, `bint`.

Improve exception handling performance in Cython

---

cupy/core/core.pyx

Fallback to synchronous transfer if pinned memory could not be allocated

---

cupy/core/core.pyx

[backport] Fallback to synchronous transfer if pinned memory could not be allocated

---

.travis.yml
docs/source/_comparison_generator.py

CuPy version of https://github.com/chainer/chainer/pull/5317.

Fix invalid escape sequence warnings in Python 3.6

---

.travis.yml
cupy/logic/comparison.py

[backport] Fix invalid escape sequence warnings in Python 3.6

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_distributions.py

#1624.
- Check `scale >= 0`
- Fix the distribution about #1644
- Fix `test_distributions.py` for the cases numpy outputs Python `float`.

Fix random.exponential

---

cupy/linalg/norms.py

[backport] Fix typo in docstring for cupy.linalg.slogdet

---

cupy/core/include/cupy/carray.cuh

I found a bug in nextafter and fixed it.
The bug happens if x>0 and y<0.
in 3788136df8f499e6b2c8643e3d4478c59e4193a6 (master)
```shell
$ python nextafter.py 
numpy 2.998
cupy 3.002
```
in f1f00b593d94e2d5081efe57ef93c729cde2eb10 (fix-float16-nextafter)
```shell
$ python nextafter.py 
numpy 2.998
cupy 2.998
```
This is nextafter.py.
```
import cupy
import numpy
a = numpy.asarray(3.0, dtype='float16')
b = numpy.asarray(-1.0, dtype='float16')
print("numpy", numpy.nextafter(a, b))
cpa = cupy.array(a)
cpb = cupy.array(b)
print("cupy", cupy.nextafter(cpa, cpb))
```

Fix float16 nextafter

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_iter.py

`TypeError` should be raised as soon as `__iter__` is called.  Before this PR,
```
=============== FAILURES ===============
______ TestIterInvalid.test_iter _______
cupy/testing/helper.py:587: in test_func
impl(self, *args, **kw)
cupy/testing/helper.py:564: in test_func
accept_error=accept_error)
cupy/testing/helper.py:50: in _check_cupy_numpy_error
self.fail('Only numpy raises error\n\n' + numpy_tb)
E   AssertionError: Only numpy raises error
E
E   Traceback (most recent call last):
E     File "/home/kataoka/cupy/cupy/testing/helper.py", line 555, in test_func
E       impl(self, *args, **kw)
E     File "/home/kataoka/cupy/test_tmp.py", line 32, in test_iter
E       iter(x)
E   TypeError: iteration over a 0-d array
--------- Captured stdout call ---------
dtype is <class 'numpy.float64'> …
```

Fix `ndarray.__iter__`

---

cupy/random/_kernels.py

This PR fixes the nvrtc error:
```
link error: Linking globals named '_Z3minll': symbol multiply defined!
```
See the results of the daily tests on Jenkins.

Fix cupy.random.hypergeometric

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

[backport] Support `astype` in fused functions

---

cupy/core/carray.pxi
cupy/core/core.pyx
cupy/core/include/cupy/atomics.cuh
tests/cupy_tests/core_tests/test_ndarray_scatter.py

This pull request adds float16 support for `scatter_add` by implementing float16 version of `atomicAdd()` (`atomicCAS` with 32bit memory alignment) and works with CUDA 9.0 and later.
[In CUDA 10, 16bit __half floating point version of `atomicAdd()` is introduced](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomicadd), and maybe its faster than this implementation, but this works on more devices for now.

Add float16 support for scatter_add

---

setup.cfg

Ignore scipy<1.0 is warned by using deprecated feature of numpy>=1.15 

---

setup.cfg

[backport] Ignore scipy<1.0 is warned by using deprecated feature of numpy>=1.15 

---

cupy/random/generator.py

[backport] Use "x mod 1" to generate [0, 1)-uniform random

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_scatter.py

This PR add support for FP64 in `scatter_add`.

Support float64 in scatter_add

---

docs/source/install.rst
docs/source/upgrade.rst

We decided to drop support for CUDA 7.0 / 7.5, as it is outdated and most users are using CUDA 8.0 or later.
(Recommendation as of today is using CUDA 9.x for maximum performance.)
This also means we're dropping support for cuDNN v4, which is only available for CUDA 7.5 or prior.
Also note that cuRAND 7.5 and prior cannot be run on Volta GPU. (https://github.com/chainer/chainer/pull/3898#issuecomment-345204832)

Drop support for CUDA 7.0 / 7.5

---

cupy/math/floating.py
tests/cupy_tests/math_tests/test_floating.py

and the reason why zero is skipped in the tests.
Close #1686.

Explain that -ftz=true affects nextafter

---

docs/source/install.rst
docs/source/upgrade.rst

[backport] Drop support for CUDA 7.0 / 7.5

---

docs/source/install.rst

[backport] Add Python 3.7 support to installation docs

---

docs/source/_comparison_generator.py

- Fix `scipy.linalg` table
- Fix caption
- Exclude `numpy.linalg` reexports
- Add `scipy.sparse.linalg` table
- Use ~`:func:`~ `:obj:` and `:meth:`

Improve `_comparison_generator`

---

tests/cupyx_tests/__init__.py

[backport] Workaround for test failure when Python 3.4 + SciPy 0.x + NumPy 0.15

---

setup.cfg

In NumPy 1.15, `np.matrix` has been deprecated. https://github.com/numpy/numpy/pull/10142
However, `scipy.sparse` is still using it (and seems to continue using it for a while).
Note: SciPy 1.2 will set their own warning filter to ignore this warning. https://github.com/scipy/scipy/pull/8887

Fix PendingDeprecationWarning when running test against NumPy 1.15

---

setup.cfg

[backport] Fix PendingDeprecationWarning when running test against NumPy 1.15

---

cupy/testing/condition.py
cupy/testing/helper.py
cupy/testing/parameterized.py
tests/cupy_tests/testing_tests/test_condition.py
tests/cupy_tests/testing_tests/test_parameterized.py

Support `self.skipTest` in unittest as done in Chainer.
https://github.com/chainer/chainer/pull/4685
CuPy specific fixes (difference from above PR): `for_dtypes` loops inside one test case with different parameters. In this case we can't just raise the exception, as it will skip the all parameters.

Support skipping tests decorated by condition or parametize

---

docs/source/_comparison_generator.py

This is to indicate functions borrowed from NumPy as alias in comparison table.
This intends to describe the cause of dead link; the dead link without *alias* means things we forgot to add to documentation.

Indicate alias in comparison table

---

cupy/core/core.pyx

Fix unclear English in `ndarray.nbytes` documentation.

Fix English in ndarray.nbytes documentation

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

Fixed the following error.
```
>>> @cupy.fuse()
... def f(x, y):
...     return x + y
...
>>> x = cupy.arange(10).astype('e')
>>> y = cupy.arange(10).astype('F')
>>> f(x, y)
File "/home/imanishi/cupy/cupy/cuda/compiler.py", line 241, in compile
nvrtc.compileProgram(self.ptr, options)
File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
cpdef compileProgram(size_t prog, options):
File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
check_status(status)
File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
raise NVRTCError(status)
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)
During handling of the above exception, another exception occurred: …
```

Fix error in typecast from fp16 to complex dtype in `cupy.fuse`

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

[backport] Fix error in typecast from fp16 to complex dtype in `cupy.fuse`

---

cupy/core/reduction.pxi
tests/cupy_tests/core_tests/test_carray.py

Fix #1766.
* `_J_offset` can be up to `2^9` and `_out_ind.size.size()` (size_t) can be up to `2^64` (capped at max GPU memory).  Thus `_j_offset` should be typed as  `long long`.
* `gridDim.x` (unsigned int) can be up to `2^31` and `_block_stride` (int) can be up to `2^9`. Thus `_i_base` and `_i` should be typed as `long long`.

Fix invalid memory access during reduction whose output is large to exceed 32-bit

---

cupy/core/_kernel.pyx
cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py

[backport] Fix incorrect cast in element-wise op for float array and complex scalar

---

cupy/core/reduction.pxi
tests/cupy_tests/core_tests/test_carray.py

[backport] Fix invalid memory access during reduction whose output is large to exceed 32-bit

---

docs/source/reference/random.rst

[backport] Add note about `cupy.random.{get_set}_state`

---

cupy/core/core.pxd
cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_conversion.py

The `numpy.ndarray.item` method converts an array to a Python scalar (`int`, `float`, or `complex`).
I believe it's reasonable for `cupy.ndarray.item` to return a Python scalar, which is on CPU, too.

Add `ndarray.item` method

---

cupy/__init__.py
cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

This PR supports mainly the following features.
1. Raise an error when trying to broadcast out_params
```
>>> @cupy.fuse()
... def f(x, y):
...     x += y
...
>>> x = cupy.arange(4)
>>> y = cupy.arange(12).reshape(3, 4)
>>> f(x, y)
......
File "cupy/core/_kernel.pyx", line 763, in cupy.core._kernel.ufunc.__call__
File "/home/imanishi/cupy/cupy/core/fusion.py", line 578, in call_ufunc
raise ValueError('non-broadcastable output operand')
ValueError: non-broadcastable output operand
```
2. Scalar type variable
```
>>> import numpy
>>> @cupy.fuse()
>>> def f(x, y):
...     z = x
...     x += y
...     return x, z
...
>>> x1 = cupy.array([1, 1])
>>> x2 = 1
>>> x3 = numpy.int64(1)
>>> y = cupy.array([2, 3])
>>> f(x1, y) …
```

Support ndim checking in Fusion

---

cupy/core/core.pyx
cupy/core/include/cupy/complex/arithmetic.h
cupy/logic/ops.py
tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py

This adds numpy-style lexicographic ordering for complex numbers. This means, first the real parts are compared (if nan, I'm not sure what's supposed to happen, in this case I return the first number) and if they are equal, the imaginary parts are used.
This enables `>, >=, <=, >, min(), max()` to be used on complex arrays. At least one side-effect is that `svd()` now works with complex.

Support comparison operators for complex numbers

---

cupy/core/core.pyx
cupy/creation/from_data.py
tests/cupy_tests/creation_tests/test_from_data.py

This PR aims to improve an interoperability between CuPy and Numba. With this PR, you can convert a numba array to a cupy array w/o D2H/H2D by cupy.asarray() as below.
x = numpy.arange(10)    # type: numpy.ndarray
x_numba = numba.cuda.to_device(x)    # type: numba.cuda.cudadrv.devicearray.DeviceNDArray
x_cupy = cupy.asarray(x_numba)    # type: cupy.core.core.ndarray
Note that still D2D is performed at array conversion.
(*) this is related to #1720.

Support array conversion from numba to cupy w/o memcpy

---

tests/cupy_tests/random_tests/test_distributions.py

`numpy.random.binomial` requires `n` to be able to cast to long.
https://github.com/numpy/numpy/blob/v1.15.0/numpy/random/mtrand/mtrand.pyx#L3786
This PR depends on #1757.

Fix test failure of binomial distribution in Windows

---

MANIFEST.in
cupy/core/carray.pxi
cupy/core/include/cupy/_cuda/README.md
cupy/core/include/cupy/_cuda/cuda-10.0/cuda_fp16.h
cupy/core/include/cupy/_cuda/cuda-10.0/cuda_fp16.hpp
cupy/core/include/cupy/_cuda/cuda-9.2/cuda_fp16.h
cupy/core/include/cupy/_cuda/cuda-9.2/cuda_fp16.hpp
setup.py

Closes #1807.
This will make CuPy run without CUDA headers (i.e., you can use `runtime` Docker container to run CuPy) in CUDA v9.2 or later.

Bundle CUDA fp16 headers

---

cupy/core/fusion.py

This PR supports ideep mdarrays for chainer/chainer#5169.

Allow `cupy.fuse` taking any parameters when fails to fuse

---

cupy/core/core.pyx
cupy/logic/ops.py

This PR follows #1636 to change an argument name of `core.create_comparison` to currently comprehensive one.

Change argument name of core.create_comparison

---

cupy/cuda/compiler.py
docs/source/reference/environment.rst

This makes use of `cuda-gdb` against CuPy kernels easier by:
- Introducing `CUPY_CUDA_COMPILE_WITH_DEBUG` environment variable which enables embedding of debug information to cubin.
- Using the same filename for both compilation-time temporary source file and cached source file, so that users can easily see the code in `cuda-gdb` session (i.e., `list` command) by using `CUPY_CACHE_SAVE_CUDA_SOURCE=1`, `CUPY_CUDA_COMPILE_WITH_DEBUG=1` and `directory ~/.cupy/kernel_cache` in cuda-gdb.
This feature is becoming important as `RawKernel` is introduced.

Better support cuda-gdb

---

cupyx/scipy/sparse/__init__.py
cupyx/scipy/sparse/construct.py
cupyx/scipy/sparse/sputils.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py

This PR adds a CuPy implementation of `scipy.sparse.diags`. The implementation is identical to SciPy's aside from replacing some NumPy calls with their CuPy equivalents.
The new file `sputils.py` has only the subset of the functions that were used in the `diags` implementation. These are not part of the public API, so I have not added tests for these, but they are tested indirectly via the diags tests.

add cupyx.scipy.sparse.diags

---

cupy/core/core.pyx

This PR aligns the error messages of broadcast failures towards numpy, printing the shapes of interest. Although a quite common error to encounter,  the previous error message contained little information. This change should make debugging easier when encountered.
Please close this ticket if it has been discussed before, maybe in terms of performance.

Verbose broadcast failure message

---

docs/source/reference/sparse.rst

This PR follows #1840 to add `cupyx.scipy.sparse.diags` to the reference.

Add diags to documentation

---

cupy/core/fusion.py
cupy/math/rounding.py

Related to issue #1834 (PR: #1835).
https://docs-cupy.chainer.org/en/latest/reference/generated/cupy.around.html
https://docs-cupy.chainer.org/en/latest/reference/generated/cupy.round_.html

Fix bad hyperlink in `cupy.around` documentation

---

cupy/random/generator.py
docs/source/reference/difference.rst
tests/cupy_tests/random_tests/test_generator.py

[backport] Support Numpy arrays as seeds in RandomState

---

cupy/math/sumprod.py
tests/cupy_tests/math_tests/test_sumprod.py

This is a minimal PR adding a call to `asarray` so `cumsum` and `cumprod` work on numpy.ndarray, tuple and list inputs (as supported in NumPy).
Omit commit a6eed90 if it is desired to also do the conversion for `cupy.sum` and `cupy.prod`
I wasn't sure in that case because it could potentially cause backwards compatibility issues:
The current behavior of `sum` and `prod` on numpy.ndarray inputs (e.g. ``cupy.sum(numpy.arange(16))``) returns a scalar rather than a 0-dimensional cupy array.  This is because the `numpy.ndarray.sum` method when the input is a numpy array.  I wasn't sure whether or not this was intended?

cumsum, cumprod: support array-like input

---

cupy/core/fusion.py
cupy/manipulation/kind.py
tests/cupy_tests/core_tests/test_fusion.py

This PR is to support NumPy 1.16
#1881

Use item instead of asscalar to support NumPy 1.16

---

cupy/core/fusion.py
cupy/manipulation/kind.py
tests/cupy_tests/core_tests/test_fusion.py

[backport] Use item instead of asscalar to support NumPy 1.16

---

cupy/core/flags.pyx
tests/cupy_tests/core_tests/test_flags.py

This adds the properties `forc` and `fnc` to the ndarray's `flags`.  These behave the same as in NumPy.
`forc` is True if the array is either Fortran or C contiguous
`fnc` is True if the array is Fortran contiguous, but not C contiguous

Add `fnc` and `forc` to `core.flags.Flags`

---

tests/cupy_tests/random_tests/test_generator.py

Fix regression (Windows test failure) introduced in #1689.
```_______________________ TestRandomState.test_array_seed _______________________
self = <cupy_tests.random_tests.test_generator.TestRandomState testMethod=test_array_seed>
def test_array_seed(self):
>       self.check_seed(numpy.random.randint(0, 2**32, size=40))
tests\cupy_tests\random_tests\test_generator.py:222: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   ???
E   ValueError: high is out of bounds for int32
mtrand.pyx:991: ValueError
```

Fix `randint` high value in test for Windows

---

tests/cupy_tests/random_tests/test_generator.py

[backport] Fix `randint` high value in test for Windows

---

cupy/core/_kernel.pyx
cupy/core/fusion.pyx
tests/cupy_tests/core_tests/test_fusion.py

Moved the declaration of `_thread_local` to `_kernel.pyx`.

Refactor cyclic imports

---

cupy/core/reduction.pxi
cupy/manipulation/rearrange.py
tests/cupy_tests/manipulation_tests/test_rearrange.py

For ease of review, the body of `numpy.roll` function is reproduced exactly in the first commit here.
The minimal changes needed for `cupy` are in the second commit.

Allow multi-axis `roll` as in numpy 1.12+

---

cupyx/scipy/sparse/base.py
cupyx/scipy/sparse/compressed.py
cupyx/scipy/sparse/coo.py
cupyx/scipy/sparse/data.py
cupyx/scipy/sparse/dia.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

A `conj` method is defined for the sparse matrix classes in current master, but results in infinite recursion when used.
Here is a minimal example to reproduce the bug (run on the current master branch):
```Python
import cupy
cupy.cupyx.scipy.sparse.eye(5).conj()
```
which results in an error ending in:
```
File "/media/Data1/cupy/cupyx/scipy/sparse/base.py", line 258, in conj
return self.tocsr().conj()
RecursionError: maximum recursion depth exceeded
```
The `conj` method of the `cupyx.scipy.sparse.spmatrix` classes for COO, CSR, CSC and DIA is implemented in this PR.
The docstrings and implementation closely follow those for the corresponding methods in `scipy.sparse`.

fix RecursionError bug in conj method of sparse matrix classes

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

Allow setting external allocators to CuPy via raw pointers. See the docs for its interface. https://github.com/cupy/cupy/pull/1904/files#diff-0cb5dfa3212da5a58c698548f2df2f68R1179 .

CuPy external memory pool with memory pool and function pointers

---

cupy/core/core.pxd
cupy/core/core.pyx
cupy/manipulation/shape.py
tests/cupy_tests/manipulation_tests/test_shape.py

This PR implements a simple means to support the `order` kwarg in ndarray's `reshape` method.
namely, the trick used here is that:
```Python
x.reshape(newshape, order='F')
```
is equivalent to:
```Python
x.transpose().reshape(newshape[::-1]).transpose()
```
Various reshape test cases were duplicated for Fortran order to verify that this is indeed the case.
This transpose-based implementation probably has slight overhead vs. a lower-level implementation, but is considerably simpler and seems to have fairly small overhead. This is probably because transpose is fast as it returns a view rather than a copy.

Add the `order` kwarg to `cupy.reshape` and the underlying `ndarray` method

---

cupy/cuda/memory.pyx

The `size` attribute of the `ExternalAllocatorMemory` was never set in the constructor. This PR fixes it.

Set size attribute of externally allocated memory

---

cupy/core/core.pyx

[backport] Fix `ndim` not using `cdef`

---

.flake8.cython

We do not enforce either, so let's ignore them.
* Line break occurred before a binary operator (W503)
* Line break occurred after a binary operator (W504)
https://lintlyci.github.io/Flake8Rules/rules/W503.html
https://lintlyci.github.io/Flake8Rules/rules/W504.html

Ignore W503 and W504

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

Renamed `External{Allocator,AllocatorMemory}` to `CFunction{Allocator,AllocatorMemory}` as the latter name better describes the classes.

Rename External* to CFunction*

---

cupy/core/_routines_manipulation.pyx
cupy/core/core.pyx
cupy/core/internal.pxd
cupy/core/internal.pyx

* Removed the untyped variant, as it seems the typed one is sufficient.
* Removed `init` argument - it's never used.

Clean up `internal.pyx` (`prod`)

---

cupy/core/core.pyx
cupy/core/internal.pxd
cupy/core/internal.pyx

Backport of #1951 
Had to make some manual changes as https://github.com/cupy/cupy/pull/1620 wasn't backported.

[backport] Clean up `internal.pyx` (`prod`)

---

cupy/fft/fft.py
tests/cupy_tests/fft_tests/test_fft.py

Plan1D requires C contiguous data, but `_exec_fft` did not always ensure this. Specifically if the array was F-contiguous and the last axis was transformed, no copy was made, leading to an incorrect output.
closes #1934
@leofang, can you run your test cases using this small patch and verify that this fixes it for you?

ensure the input to the CUFFT Plan1D class is C contiguous

---

cupy/cuda/driver.pxd
cupy/cuda/driver.pyx
cupy/cuda/function.pxd
cupy/cuda/function.pyx
cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
cupy/cuda/pinned_memory.pxd
cupy/cuda/pinned_memory.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx

Fixes #1913
The added benefit is that Cython now checks negative size for malloc:
```
>>> a = cupy.cuda.memory.alloc(-1)
File "cupy/cuda/memory.pyx", line 506, in cupy.cuda.memory.alloc
cpdef MemoryPointer alloc(size):
File "cupy/cuda/memory.pyx", line 518, in cupy.cuda.memory.alloc
return _current_allocator(size)
File "cupy/cuda/memory.pyx", line 1068, in cupy.cuda.memory.MemoryPool.malloc
cpdef MemoryPointer malloc(self, size_t size):
OverflowError: can't convert negative value to size_t
```

Fix int types

---

cupy/core/fusion.pyx
tests/cupy_tests/core_tests/test_fusion.py

```
>>>
>>> @cupy.fuse()
... def f(x, y):
...     if y is None:
...         x[:] = -x
...     else:
...         x += y
...
>>> x = cupy.array([1, 2, 3])
>>> x
array([1, 2, 3])
>>> f(x, 1)
>>> x
array([2, 3, 4])
>>> f(x, None)
>>> x
array([-2, -3, -4])
```

Allow passing `None` as parameters of `Fusion.__call__`

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py

In SciPy 1.12.0, `scipy.sparse.random` can generate integer sparse matrix.

Fix test to support SciPy 1.12

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

This fixes the following error:
```py
>>> cupy.random.randint(3, 10, size=0)
File "/home/kenichi/Development/cupy/cupy/random/sample.py", line 112, in randint
return rs.randint(low, high, size, dtype)
File "/home/kenichi/Development/cupy/cupy/random/generator.py", line 1030, in randint
x = self._interval(diff, size).astype(dtype, copy=False)
File "/home/kenichi/Development/cupy/cupy/random/generator.py", line 607, in _interval
return ret.reshape(size)
AttributeError: 'NoneType' object has no attribute 'reshape'
```

Fix `cupy.random.randint` fail with size zero

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

[backport] Fix `cupy.random.randint` fail with size zero

---

cupy/core/core.pxd
cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_get.py

This PR is takeover version of #1955.
- Reduce function call
- Fix flake8 error
- Add tests

Add `out` argument to `ndarray.get` for asynchronous device-to-host copy

---

cupy/core/core.pxd
cupy/core/core.pyx

In `cupy.core.ndarray.get`, it internally creates a page-able buffer as destination
which causes asynchronous copy from device to host has lower bandwidth and
overlapping of GPU kernel execution and data transfer is impossible.
In order to solve this issue, add new argument as destination to `get` API.
User must allocate a pinned buffer as destination first to get speedup.
Otherwise, CuPy will go back to original behavior.
Regarding issues are #1937 and #1938

Fix performance of async D2H copy

---

cupy/cuda/memory.pyx

This fixing is for Python 2.
Please check chainer/chainer#5621 and [forum(ja)](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chainer-jp/7HVJiVHYgtU/n2PGkYI6FQAJ)

Call free_all_blocks to free CUDA memory

---

cupy/logic/type_test.py
tests/cupy_tests/logic_tests/test_type_test.py

[backport] Support Python scalars in `iscomplexobj`

---

cupy/cudnn.pyx

It seems that PR #1659 introduced a memory leak, and this PR fixes the problem.
When I ran a program that repeatedly train a network that contains batch normalization, memory consumption increased continuously. The problem happens with the following combinations of Chainer and CuPy. (I’m using python 3.5.2, cuda 8.0 and cudnn 5.1)
* Chainer
* v5.0.0
* v5.1.0
* revisions between v5.1.0 and https://github.com/chainer/chainer/commit/511f3cb5c3888c00df70f85b1d65fcf54e689d6f.
* CuPy
* revisions between https://github.com/cupy/cupy/commit/769c4a5ec4e846a1a4e9e503481572d5a5c3c23e and  v5.1.0.
* v5.1.0
* v5.2.0
The commit https://github.com/cupy/cupy/commit/769c4a5ec4e846a1a4e9e503481572d5a5c3c23e is a backport of PR #1659 and it changes `Descriptor` from `class` to `cdef class` while keeping …

define __dealloc__ instead of __del__ for cdef-classes to fix memory leak

---

tests/cupy_tests/testing_tests/test_array.py

The bug in the test is effective with `numpy>=1.16.1`.

Fix test of `assert_array_list_equal`

---

cupy/cuda/cupy_nccl.h
cupy/cuda/nccl.pyx
cupyx/runtime.py
install/build.py

`ncclGetVersion` function, `NCCL_VERSION` macro and `NCCL_VERSION_CODE` macro has been introduced in NCCL v2.3.4.
Use them to report runtime version in `cupy.show_config()` and also avoid redeclaration warning:
```
/tmp/tmpfdjuddmz/a.cpp:5:0: warning: "NCCL_VERSION" redefined
^
In file included from /tmp/tmpfdjuddmz/a.cpp:2:0:
/home/kenichi/.nccl/active/cuda/include/nccl.h:19:0: note: this is the location of the previous definition
#define NCCL_VERSION(X,Y,Z) ((X) * 1000 + (Y) * 100 + (Z))
^

Use version interface in NCCL 2.3.4

---

cupy/core/fusion.pyx

This PR also fixes a bug of cast mentioned in #1983, but this bug will not be reproduced until `cupy.copyto` is introduced in this repository.

Enhance error messages of elementwise operation in fusion mode

---

cupy/testing/helper.py
tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py

`accept_error` feature catches errors in test codes.
https://github.com/cupy/cupy/blob/7ea8df6127b7a2bf1d8c0b77f3a3050217fd926f/tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py#L160-L168
is called by
https://github.com/cupy/cupy/blob/7ea8df6127b7a2bf1d8c0b77f3a3050217fd926f/tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py#L213-L215
, which should fail with `TypeError: ... got an unexpected keyword argument 'no_complex'`.

Do not "accept error" if bad kwarg is passed to test itself

---

cupy/cudnn.pyx

[backport] Define `__dealloc__` instead of `__del__` for cdef-classes to fix memory leak

---

cupy/core/reduction.pxi
tests/cupy_tests/core_tests/test_reduction.py

Reduction on a outer axis of a large tensor has been small, due to bad memory access pattern. This PR aim to mitigate the issue by allocating up to 32 contiguous items to `_block_stride`. By doing this, coalesced memory access is achieved.
Increasing `_block_stride` can hurt parallelism, so performance degradation can occur depending on workload. I think the speed-up will outweigh the possible degradation, but more benchmarks are welcomed.
The following is the benchmark I conducted.
```python
import cupy
x = cupy.random.normal(0.0, 1.0, (16, 512, 8, 8), dtype=cupy.float32)
y = cupy.random.normal(0.0, 1.0, (16, 512, 8, 8), dtype=cupy.float32)
kern = cupy.ReductionKernel(
'T x, T y', 'T z',
'x * y', 'a + b', 'z = a', '0', 'sample_dot')
for i in range(10):
z = cupy.sum(x, axis=1)
for i in …
```

improve performance of reduction on outer axis

---

cupy/cudnn.pyx

`cudnnDeriveBNTensorDescriptor` returns FP32 when `xDesc` is FP16, so cuDNN assumes FP32 `gamma`, `beta`, etc. in FP16 BN. `x` and `gamma` do not necessarily have the same dtype, so we have to compare `gamma.dtype` with `dtype_param` before type conversion.
This change is especially important for `batch_normalization_backward` because we need FP32 `ggamma` for FP32 `gamma`.

Support cuDNN FP16 batch normalization

---

cupy/random/_kernels.py
cupy/random/generator.py

`rk_seed` dtype unexpectedly promotes to float64.
Closes #2032.

Fix random generator seed type

---

cupy/core/_kernel.pyx
cupy/core/core.pyx

This PR relates #1650 .
Please test with NumPy >= 1.16
```
NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1 python -c "import numpy, cupy; print(numpy.power(cupy.arange(10), 2))"
```

Fix __array_function__ bug

---

cupy/linalg/solve.py

The `ipiv` parameter of `sgetrf`/`dgetrf` function is declared to be a pointer to int array, but the current implementation allocates a buffer ndarray with `'f'` or `'d'` dtype.
It is safe on all platforms supported by CUDA, because `sizeof(int) <= sizeof(float)` on those platforms. But allocated buffer is larger than necessary in the `dgetrf` case on those platforms, since `sizeof(double)` is larger than `sizeof(int)`.
I'm not sure which of `numpy.intc` or `numpy.int32` is more appropriate for the purpose.

Fix incorrect `dtype` for `ipiv` buffer in `cupy.linalg.inv`

---

cupy/core/core.pyx

`import numpy` is executed every time in `a_cpu.ctypes.get_as_parameter()`

Avoid `import numpy`

---

cupy/cuda/runtime.pyx

[backport] Remove duplicate declaration of `cudaMalloc`

---

cupy/testing/attr.py

Closes #1917
Note: chainer has the same issue.

Avoid using pytest attributes during import

---

cupyx/scipy/__init__.py

It says that the function returns `cupy` module, but in fact it returns `cupyx.scipy` module.

fix cupyx.scipy.get_array_module's docstring

---

cupy/cuda/cufft.pyx
cupy/fft/fft.py
cupyx/scipy/fftpack/fft.py
tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py

This is an accompanying PR with #1942 to address the performance issue discussed in #1669. In this PR I changed the signatures for the following functions:
* `cupyx.scipy.fftpack.fft`
* `cupyx.scipy.fftpack.ifft`
so that they accept a `plan` argument (defaulted to `None`). Another change is made to `cupyx.scipy.fftpack.get_fft_plan`, introduced #1942, so that it can return either a cuFFT `Plan1d` or `PlanNd` --- this is a design choice that I'd like to have feedbacks from @grlee77 and perhaps @asi1024. Thanks.

Add `plan` argument to 1D FFT functions in `cupyx.scipy.fftpack`

---

cupy_setup_build.py

This PR fixes issues introduced in #2014.
* RPATH needs to be calculated for each file, not module.
* RPATH to `library_dirs` should not be set if `--cupy-no-rpath` is given.
This fix is needed to build wheels for release.

Fix RPATH not set correctly

---

cupy/testing/attr.py

[backport] Avoid using pytest attributes during import

---

cupyx/scipy/sparse/compressed.py
cupyx/scipy/sparse/coo.py
cupyx/scipy/sparse/dia.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

It is currently possible to pass non-integers as the elements of the `shape` input to the sparse matrix creation routines.  When this is done, the `__init__` method should make sure these get converted to proper Python `int`.  This conversion to `int` is already done if the first argument is a shape, but was missing when `shape` was instead supplied via the keyword argument.
A remaining difference is that the existing `util.isshape` function still allows a shape such as `(3.0, 4.0)` to be converted to `(3, 4)` while SciPy would raise the following error:
`TypeError: 'float' object cannot be interpreted as an integer`

ensure that sparse matrix shapes are always a tuple of int

---

cupyx/scipy/linalg/__init__.py
cupyx/scipy/linalg/decomp_lu.py
docs/source/reference/linalg.rst
tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py

This PR adds `lu_factor` and `lu_solve` to `cupyx.scipy.linalg` that correspond to `scipy.linalg.lu_factor` and `scipy.linalg.lu_solve`.
I want those functions to port https://github.com/locuslab/qpth/ from PyTorch to Chainer/CuPy.

Add `lu_factor` and `lu_solve` to `cupyx.scipy.linalg`

---

cupyx/scipy/sparse/compressed.py
cupyx/scipy/sparse/coo.py
cupyx/scipy/sparse/dia.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

[backport] Ensure that sparse matrix shapes are always a tuple of `int`

---

cupy/cudnn.pyx

This PR follows #2060 to make it keep backward compatibility.

Keep backward compatibility on cupy.cudnn.batch_normalization_forward_training

---

tests/cupy_tests/linalg_tests/test_decomposition.py

Generating a positive (semi-)definite matrix by `A = X.dot(X.T)` may give `A` too small eigenvalues by chance.  This fix reduces the chance to pick such unstable inputs.
Close #2083.

Test linalg.cholesky with more stable inputs

---

cupy/cudnn.pyx

`get_rnn_lin_layer_matrix_params` declares `w_data_ptr` but never use it.

Remove unused variable

---

cupy/core/core.pyx

Current docstring of ndarray does not cover `strides` argument which is supported in #1611.

Add strides to docstring of ndarray

---

cupy/cudnn.pyx

[backport] Fix fp16 issue in batch normalization + Keep backward compatibility on cupy.cudnn.batch_normalization_forward_training

---

cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

Follow-up of #2103.
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/34/TEST=CHAINERX_chainer-py3,sakura11=sakura11/console
```
20:33:56 Traceback (most recent call last):
20:33:56   File "cupy/cuda/memory.pyx", line 597, in cupy.cuda.memory.PooledMemory.free
20:33:56   File "cupy/cuda/memory.pyx", line 969, in cupy.cuda.memory.SingleDeviceMemoryPool.free
20:33:56   File "cupy/cuda/memory.pyx", line 791, in cupy.cuda.memory.LockAndNoGc.__enter__
20:33:56 AttributeError: 'NoneType' object has no attribute 'isenabled'
20:33:56 Exception ignored in: 'cupy.cuda.memory.PooledMemory.__dealloc__'
```

Check if gc module is still available

---

cupy/cuda/cupy_cusolver.h
cupy/cuda/cusolver.pxd
cupy/cuda/cusolver.pyx
cupy/cuda/device.pxd
cupy/cuda/device.pyx
tests/cupy_tests/cuda_tests/test_device.py

Avoid sharing handles between threads

---

cupy/core/carray.pxi
cupy/core/core.pyx
cupy/core/include/cupy/_cuda/cuda-10.1/cuda_fp16.h
cupy/core/include/cupy/_cuda/cuda-10.1/cuda_fp16.hpp
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cuda.h
cupy/cuda/cupy_cudnn.h
cupy/cuda/device.pyx
cupy/cuda/memory.pyx
cupy/cuda/pinned_memory.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx
cupy_setup_build.py
docs/source/install.rst

Closes #2002 and #2069
Please note that:
* Error numbers of CUDA Runtime API has been renumbered in CUDA 10.1.
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
* Although it is not documented in the reference, I confirmed that NVRTC from CUDA 10.0 accepts `compute_75` PTX compilation.
https://docs.nvidia.com/cuda/archive/10.0/nvrtc/index.html#group__options
* cuDNN 7.5 changed `CUDNN_BN_MIN_EPSILON` to `0.0`.
https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_750.html
Blocked by https://github.com/chainer/chainer-test/pull/506

Support CUDA 10.1 + cuDNN 7.5 + Turing

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py

Solves #2128.
According to what I understand from the `cupy.cuda.MemoryPointer` [documentation](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.cuda.MemoryPointer.html), the `mem.ptr` attribute pointer points to the base of the memory buffer, whereas `ptr` points to the _place within the buffer_, which I understand as base+slice offset.
Feel free to correct me if my understanding is wrong and the fix is not correct for all situations (e.g., we may need to point to some other attribute from `self.data.mem`). In my tests, also for the example I provided in #2128, this suffices to fix the issue.

Fix `__cuda_array_interface__` data pointer for sliced arrays

---

cupy/cuda/cupy_cuda.h
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx

Add wrappers for `cudaHostRegister` and `cudaHostUnregister` in CUDA Runtime API. It can *pin* (page-lock) a memory which is allocated by methods other than `cudaHostAlloc`.

Add `hostRegister` and `hostUnregister`

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py

[backport] Fix `__cuda_array_interface__` data pointer for sliced arrays

---

cupy_setup_build.py

Fixes #2070. Though basic CUDA 10.1 support is added by #2117, compile error with GCC 7 or 8  has persisted on Ubuntu 18.04, Arch and Gentoo .
The error is at `basic_string.tcc`. [GCC's C++11 ABI change to support non-CoW string](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) is likely related. As I noted on #2070, Anaconda had updated GCC. I think removing this workaround won't be problematic on Chainer v6 or later.

fix compile error on CUDA 10.1 and GCC 7 or 8

---

cupy_setup_build.py

[backport] fix compile error on CUDA 10.1 and GCC 7 or 8

---

examples/kmeans/kmeans.py

Close #2143.
This PR makes the k-means example's custom kernels simpler. Additionally, it makes the algorithm computing the centroids completely parallel.

Make k-means example's custom kernels simpler

---

cupy/sorting/search.py
tests/cupy_tests/sorting_tests/test_search.py

This is an attempt to solve issue #2164.

Complex support for cp.where()

---

cupy/cudnn.pyx

This PR may fix: https://ci.preferred.jp/chainer.py37.gpu/5842/
```py
try:
_create_tensor_descriptor(x_desc, x, format=d_layout)
_create_tensor_descriptor(gy_desc, gy, format=d_layout)
_create_filter_descriptor(filter_desc, gW, w_layout)
_create_convolution_descriptor(
conv_desc, pad, stride, dilation, groups, x.dtype,
cudnn.CUDNN_CROSS_CORRELATION, use_tensor_core)
if deterministic:
algo = cudnn.CUDNN_CONVOLUTION_BWD_FILTER_ALGO_1
workspace_size = cudnn.getConvolutionBackwardFilterWorkspaceSize(
handle, x_desc, gy_desc, conv_desc, filter_desc, algo)
math_type = cudnn.CUDNN_DEFAULT_MATH
```
In deterministic mode, `conv_desc` might be created with `use_tensor_core` is `True` whereas the algorithm does not Tensor Core.
This PR fixes this bug by disabling `use_tensor_core` in deterministic …

Avoid using Tensor Core with cuDNN deterministic mode in convolution backward

---

cupy/core/carray.pxi
cupy/core/core.pxd
cupy/core/core.pyx
cupy/cuda/function.pyx

Reverts cupy/cupy#719
This caused test errors in ChainerCV.
https://ci.preferred.jp/chainer.py3.cv.gpu/6895/

Revert "Improve kernel launch performance"

---

cupy/linalg/__init__.py
cupy/linalg/solve.py
tests/cupy_tests/linalg_tests/test_solve.py

Adds ```cupy.linalg.lstsq```
This solves a least squares problem using SVD similar to ```numpy.linalg.lstsq```.
This only returns the least-squares solution, while `numpy.linalg.lstsq` returns the residuals, rank, and singular values in addition to the least-squares solution.
If it's necessary to have 100% return syntax match to `numpy.linalg.lstsq`, I can modify this pr to include residuals, rank, and singular values.
Closes https://github.com/cupy/cupy/issues/1273
---
Edit 04-28-2019 22:54 EDT.
I have a [benchmark](https://jekel.me/2019/Compare-lstsq-performance-in-Python/) comparing the performance of this ```cupy.linalg.lstsq``` vs ```numpy.linalg.lstsq```, where CuPy was about six times faster on an AMD FX-8350 with NVIDIA Titan Xp for 6,000,000 data points. I'd be curious if this …

add linalg.lstsq

---

tests/cupy_tests/manipulation_tests/test_rearrange.py

Ignore invalid axis type test in NumPy 1.12.x or earlier

---

tests/cupy_tests/manipulation_tests/test_rearrange.py

[backport] Ignore invalid axis type test in NumPy 1.12.x or earlier

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_split.py

Fix #2206.
The incorrect result appears when `sections` does not divide the input length. I also fixed all the tests for `split.py` to check the divided inputs rather than the re-concatenated one so that the split points are also checked.

Fix `array_split` with non-equally dividing sections

---

.gitignore
cupy_setup_build.py

Rel. https://github.com/chainer/chainer/issues/7240
This fix is required to allow manually building ChainerX with cuDNN shared with wheel-distributed CuPy.
* Shared libraries are copied to `<cupy>/.data/lib` (previously `<cupy>/_libs`)
* Include fils are copied to `<cupy>/.data/include`

Add setup option to copy include files in wheel

---

cupy/core/core.pyx

This PR aims to fix an unexpected GPU#0 memory usage during CPU from/to GPU array copy even if the array is *not* on the GPU#0.
It reproduces on CuPy 6.0.0rc1/CUDA 9.0/V100×4 with the code below.
I've notice the problem though the [Chainer's ImageNet example](https://github.com/chainer/chainer/tree/master/examples/imagenet).
When I run the training program with `--gpu 1 2` to use GPU#1 and GPU#2, it consumes (~400 MiB) on GPU#0 after the first call to [`LogReport`](https://docs.chainer.org/en/latest/reference/generated/chainer.training.extensions.LogReport.html) extension (which internally calls `cupy.ndarray.get()` via `cupy.ndarray.__float__()`).
The code to reproduce the problem (on `cupy.ndarray.set()`) is as follows:
```
import os
import cupy
import numpy
print(f'CuPy: …
```

Set current device in `cupy.ndarray.get()`/`set()`

---

docs/source/overview.rst
docs/source/reference/index.rst
docs/source/reference/routines.rst

The PR stops using `.. module:: cupy` except for `index.rst`, in order to fix
```
WARNING: duplicate object description of cupy, other instance in index, use :noindex: for one of them
WARNING: duplicate object description of cupy, other instance in overview, use :noindex: for one of them
WARNING: duplicate object description of cupy, other instance in reference/index, use :noindex: for one of them
```

Fix: duplicate object description of cupy

---

docs/source/overview.rst
docs/source/reference/index.rst
docs/source/reference/routines.rst

[backport] Fix: duplicate object description of cupy

---

cupy/linalg/product.py
tests/cupy_tests/linalg_tests/test_product.py

[backport] Avoid division by zero in tensordot, allowing 0-length arrays

---

cupy/core/_kernel.pyx

`hasattr` is slow because it raises error when `key` is missing. An error object creation needs string operation. It is very high cost in Python.
This PR avoids it in typical cases.

Fix _preprocess_args to avoid calling hasattr

---

cupy/cudnn.pyx
tests/cupy_tests/test_cudnn.py

This PR helps developers identify a cause of convolution algorithm selection related cudnn error.
When auto tuning is enabled, cudnnFindConvolution* API is called to find optimal cudnn algorithm for each convolution layer at first attempt, but sometimes no algorithm returned by the API is available. This error case is not currently checked, so I added that check.

Raise error when no available algorithm found by cudnnFindConvolution*

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py

Fixes #2259. Added a test to ensure the compliance with `__cuda_array_interface__` standard.

Make `__cuda_array_interface__()['strides']` be `tuple`

---

cupy/core/core.pyx
cupy/util.pyx
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

[backport] Allow copying in the format `cupy_array[:] = numpy_array`

---

cupy/core/_kernel.pyx

This error is never occur. `is_const` is always `True` for `self.params[:self.nin]`.

Remove unused code

---

cupy/cudnn.pyx

Related to https://github.com/chainer/chainer/issues/7545.
When `rnn_backward_data` takes a sequence whose length is one,
it raises `CUDNN_STATUS_BAD_PARAMS`.
As pointed out by @kmaehashi, strides of `ys` and `dys` are different from each other.
Based on his comment, I put `copy` before `_internal_ascontiguousarray`.

Avoid CUDNN_STATUS_BAD_PARAMS

---

tests/cupy_tests/test_cudnn.py

Fixes error introduced in #2234.

Fix test failure when cuDNN is unavailable

---

docs/source/reference/interoperability.rst

This PR adds a section on interoperability with mpi4py.
We recently added support for `__cuda_array_interface__` in the master branch of [mpi4py](https://bitbucket.org/mpi4py/mpi4py) so that GPU arrays from CuPy or Numba can work seamlessly with a CUDA-aware MPI as long as they have `__cuda_array_interface__`. I think it's worth documenting and advertising (for example, I saw mpi4py is used in [Chainer](https://github.com/chainer/chainer)'s codebase, and the Chainer users are highly overlapped with CuPy's). More examples are available in mpi4py's `demo` folder:
https://bitbucket.org/mpi4py/mpi4py/src/master/demo/cuda-aware-mpi/

Document interoperability with mpi4py

---

cupy/io/npz.py
tests/cupy_tests/io_tests/test_npz.py

Support `allow_pickle` in `cupy.load` and `cupy.save`

---

cupy/cudnn.pyx

This PR adds support of NHWC tensor layout in batch normalization related routines in CuPy.
This is related to https://github.com/chainer/chainer/pull/7375.

Add NHWC layout support to batch normalization

---

cupyx/scipy/linalg/decomp_lu.py
tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py

Since `cusolverDn<t>getrf` supports non-square matrices as input, it would be nice to support it in cupy as well.
Note that `lu_solve` does require square matrices as input, so this PR only modifies `lu_factor`.
Yet, it can be useful to compute LU factorization of rectangle matrices.
Link to cuSOLVER documentation: https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-getrf

[Enhancement] support non-square matrices in lu_factor

---

cupy/core/core.pxd
cupy/core/core.pyx
cupy/math/sumprod.py

`cupy.{nansum/nanprod}` and `cupy.ndarray.{nansum/nanprod}` were supported in #2252. However, `numpy.ndarray` does not have `nansum` and `nanprod` as attributes, so they should be removed.

Remove `cupy.ndarray.{nansum/nanprod}`

---

docs/source/install.rst

Blocked by: https://github.com/chainer/chainer-test/pull/510
* Support Ubuntu 18.04
* Drop Ubuntu 14.04
* Add notes for Windows (closes #2177 and #2178)

Update installation guide

---

cupy/cuda/__init__.py
cupy/cuda/cupy_cutensor.h
cupy/cuda/cutensor.pyx
cupy/cutensor.py
cupy_setup_build.py
examples/cutensor/contraction.py
examples/cutensor/elementwise_binary.py
examples/cutensor/elementwise_trinary.py
install/build.py

This PR proposes to make cuTENSOR, a high-performance CUDA library for tensor operations, available on CuPy. Please see [this link](https://developer.nvidia.com/gtc/2019/video/S9593) for details about cuTENSOR.
All cuTENSOR's C APIs are exposed in `cupy/cuda/cutensor.pyx`. In addition, a bit abstracted APIs such as **contraction**, **elemetwise_trinary** and **elementwise_binary** are exposed in `cupy/cutensor.py`, so that python developers can utilize cuTENSOR in rather pythonic way. Please see examples in `examples/cutensor/` on how to use these APIs.
In order to build CuPy with cuTENSOR enabled, you first need to download cuTENSOR from [here](https://developer.nvidia.com/cutensor-product-page) and tell a path where cuTENSOR is installed by an environment variable `CUTENSOR_PATH` when …

Support cuTENSOR

---

cupy/__init__.py
tests/cupy_tests/core_tests/test_array_function.py
tests/cupy_tests/core_tests/test_core.py

With the introduction of `__array_function__` it has become impossible to use NumPy's implementation directly by aliasing such functions. To fix this behavior, a new `_implementation` attribute was added, ensuring libraries built on top of NumPy can fallback to its implementation.
This PR makes use of this new attribute to ensure functions like `cupy.can_cast` will fallback to `numpy.can_cast`. The tests added here will work for both NumPy < 1.17 (internally using the previous behavior of simply calling `numpy.can_cast` directly), and for NumPy >= 1.17 (internally calling `numpy.can_cast._implementation`). Tests won't work if `NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1` for NumPy 1.16.x, that doesn't have the `_implementation` attribute that allows these functions to work.

Add wrappers for can_cast, common_type and result_type functions

---

tests/cupy_tests/core_tests/test_core.py
tests/cupy_tests/test_type_routines.py

Enhanced tests for `can_cast`, `common_type` and `result_type` (implemented in #2249 as wrappers to NumPy functions).

Enhanced tests for type routines

---

cupy/linalg/decomposition.py

Documentation of `compute_uv` argument was wrong.

Fix for `linalg.svd` documentation

---

cupy/creation/matrix.py

The `row` and `col` variables were mixed up in `tri`'s kernel so I corrected their names. The logic hasn't changed.

Fix variable names in `tri` kernel

---

cupy/core/core.pyx

Make `cupy.tensordot` use Tensor Core also in case of compute-capability > 70

---

cupy/core/core.pyx

[backport] Make `cupy.tensordot` use Tensor Core also in case of compute-capability > 70

---

cupy/io/npz.py
tests/cupy_tests/io_tests/test_npz.py

[backport] Support `allow_pickle` in `cupy.load` and `cupy.save`

---

docs/source/tutorial/basic.rst

`np.allclose(x_gpu, [1, 2, 3])` now returns `True` without any errors by `__array_function__` support.
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/227/TEST=cupy-doc,label=mn1-p100/console

Fix doctest failure related to `__array_function__` support

---

docs/source/tutorial/basic.rst

[backport] Fix doctest failure related to `__array_function__` support

---

cupyx/fallback_mode/fallback.py
tests/cupyx_tests/fallback_mode_tests/test_fallback.py

This PR is related to #2066 
This will add wrapper around `numpy.vectorize` object.
It shows following behaviour:
```python
>>> from cupyx.fallback_mode import numpy
>>> vabs = numpy.vectorize(abs)
>>> vabs
<cupyx.fallback_mode.fallback.vectorize object at 0x7f0a2ba61ba8>
>>> isinstance(vabs, numpy.vectorize)
True
>>> a = numpy.array([-1, 2, -3])
>>> type(a)
<class 'cupyx.fallback_mode.fallback.ndarray'>
>>> res = vabs(a)
>>> res
array([1, 2, 3])
>>> type(res)
<class 'cupyx.fallback_mode.fallback.ndarray'>
>>> vabs.pyfunc is abs
True
>>> vabs.__doc__
'Return the absolute value of the argument.'
>>> 
```

Add wrapper for `numpy.vectorize` in `fallback_mode`

---

tests/cupy_tests/linalg_tests/test_decomposition.py

- Compare each `u[:, j]` up to a multiplication of `sign` with `abs(sign) == 1`, rather than comparing each `abs(u[i, j])`
- Do not compare vectors for `full_matrices=True` unless `abs(shape[-2] - shape[-1]) <= 1` (see below)
- Test complex inputs
- Test int inputs
- Follow `numpy.testing.assert_allclose(actual, desired)`
```python
import numpy
import cupy
numpy.random.seed(0)
numpy.set_printoptions(linewidth=100)
x = numpy.random.randn(8, 4)
print('u (numpy)')
print(numpy.linalg.svd(x)[0])
print('u (cupy)')
print(cupy.linalg.svd(cupy.array(x))[0])
x = numpy.random.randn(4, 8)
print('vh (numpy)')
print(numpy.linalg.svd(x)[2])
print('vh (cupy)')
print(cupy.linalg.svd(cupy.array(x))[2])
```
```
u (numpy)
[[-0.44713126 -0.61696779  0.21043358 -0.28435409  0.12524547  0.45223261 -0.12257623 …
```

Fix tests of linalg.svd

---

cupy/cuda/cupy_nccl.h
cupy/cuda/nccl.pyx
docs/source/reference/cuda.rst
tests/cupy_tests/cuda_tests/test_nccl.py

The main purpose of PR is to add a factory function to `NcclCommunicator` so that it is possible to create a group of NCCL communicators for multiple devices in a single process:
```python
from cupy.cuda import nccl
comms = nccl.NcclCommunicator.initAll([0, 2, 3])
```
Since Python/Cython does not support overloading multiple constructors, in order to preserve backward compatibility creating a factory function seems to be a necessary design decision to me. Please let me know if you have any better alternatives, thanks! 
In addition, this PR also wraps several other NCCL APIs (mainly to serve the above need). With this PR, **now CuPy supports the full NCCL APIs!** See below for a complete and finalized list for the changes:
**=== FINAL UPDATE ===**
- added `initAll()`, `groupStart()` and …

Provide full coverage for NCCL APIs in CuPy

---

cupy/__init__.py
docs/source/install.rst
docs/source/upgrade.rst

* Emit warnings for Python 2 users
* Drop support for Python 2.7 and Python 3.4 as well as it is already EOLed

Drop support for Python 2.7 and 3.4

---

tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py

Part of #2370.
NumPy's in-place elementwise operation has become to raise `numpy.core._exceptions.UFuncTypeError` instead of `TypeError` from NumPy 1.17. Currently, `cupy.testing.numpy_cupy_allclose` asserts whenever `isinstance(cupy_error, type(numpy_error))` is `False` even if we give any `accept_error` argument, so we cannot fix easily these tests.

Skip some ndarray-elementwise-op tests as temporary fix

---

tests/cupy_tests/random_tests/test_distributions.py

Fixes part of #2370
`a=0` [has been forbidden](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.power.html) in `numpy.random.power`, but it seems it only became an error in NumPy 1.17.

Remove `random.power` test with forbidden value

---

tests/cupy_tests/fft_tests/test_fft.py

This PR addresses the NumPy 1.17 test errors in the fft module (see #2361)
Hopefully this will be fixed by 1.17.1, so I chose to just skip a couple of the tests via
`@testing.requires('numpy!=1.17.0')`
closes #2361

skip some fft tests on NumPy 1.17.0 due to a NumPy bug

---

tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py

[backport] Skip some ndarray-elementwise-op tests as temporary fix

---

tests/cupy_tests/fft_tests/test_fft.py

[backport] Skip some FFT tests on NumPy 1.17.0 due to a NumPy bug

---

cupy/core/core.pyx
cupy/testing/helper.py
tests/cupy_tests/sorting_tests/test_search.py

Part of #2370. 
According to [NumPy 1.17.0 release notes](https://github.com/numpy/numpy/releases/tag/v1.17.0), calling nonzero on 0d arrays is deprecated. I fixed the following three test failures.
- `tests.cupy_tests.sorting_tests.test_search.TestNonzero`
- Made `cupy.nonzero` raise DeprecationWarning when `ndim` is `0`.
- `tests.cupy_tests.testing_tests.test_helper.TestIgnoreOfNegativeValueDifferenceOnCpuAndGpu`, `tests.cupy_tests.linalg_tests.test_einsum.TestEinSumUnaryOperation`
- The functions wrapped by `numpy_cupy_allclose` calls `numpy.nonzero` internally. The messages in `DeprecationWarning` suggested "Use `atleast_1d(cond).nonzero()` if the old behavior was intended.", but I didn't so because I found better implementation.

Avoid calling `numpy.nonzero` on 0-dim arrays

---

cupy/core/core.pyx
cupy/testing/helper.py
tests/cupy_tests/sorting_tests/test_search.py

Reverts cupy/cupy#2374
The original PR has a bug, and #2385 fixes it.

Revert "Raise `DeprecationWarning` on 0-dim arrays in `numpy.nonzero` to match NumPy 1.17 behavior"

---

cupy/core/core.pyx
tests/cupy_tests/sorting_tests/test_search.py

Raise `DeprecationWarning` on 0-dim arrays in `numpy.nonzero` to match NumPy 1.17 behavior

---

tests/cupy_tests/random_tests/test_generator.py

Each test added in #1300 theoretically fails with probability 0.1158125 %.  It seems OK to increase the numbers of retries because wrong implementation rarely passes K-S test with 2000 samples by chance.
Fix #2373.

Increase numbers of retries for K-S tests

---

cupy/cuda/cufft.pxd
cupy/cuda/cufft.pyx
cupy/fft/fft.py
cupyx/scipy/fftpack/fft.py
docs/source/reference/fft.rst
tests/cupy_tests/fft_tests/test_fft.py
tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py

Resolves #2356, resolves #2357. This PR enables the following (perhaps more pythonic) usage:
```python
import cupy
from cupyx.scipy.fftpack import get_fft_plan
x = cupy.arange(10)
fftplan = get_fft_plan(x)
with fftplan:
y = cupy.fft.fft(x)
```
Note that the context manager pattern will work for functions in both `cupy.fft` and `cupyx.scipy.fftpack`.
Furthermore, this PR makes it easy to work with the new module `cupyx.scipy.fft` (to be added in #2355 following upstream changes):
```python
import cupy
import cupyx.scipy.fft as cu_fft
import scipy.fft
from cupyx.scipy.fftpack import get_fft_plan
x = cupy.arange(10)
fftplan = get_fft_plan(x)
with scipy.fft.set_backend(cu_fft), fftplan:
scipy.fft.fft(x)  # Calls into cupyx, use fftplan, and returns a cupy array
```
While the `plan` argument …

Allow cuFFT plans to be used as a context manager; Set stream before executing cuFFT plans

---

cupy/core/fusion.pyx
cupy/core/include/cupy/complex/complex.h
docs/source/tutorial/kernel.rst

For docs, I replaced all `cupy.~` by `cp.~` in `kernel.rst` when it is used in code example, as `basics.rst` does so.

Small fix of `fusion.pyx` and docs

---

tests/cupy_tests/sorting_tests/test_search.py

Fixes a part of #2370
The corresponding v7 fix is: #2394

[v6] Skip `nonzero` test for 0d arrays in NumPy 1.17

---

cupy/testing/helper.py
tests/cupy_tests/testing_tests/test_helper.py

Another solution for #2377.
Related to #2376, #2379.
Currently, `accept_error` requires the type of `cupy_error` to be a sub-type that of `numpy_error`. This behavior is inconvenient for us when the target NumPy's function raises an error of NumPy's private exception class.
This PR relaxes this check condition of `accept_error`.

Change check condition of `accept_error`

---

cupyx/scipy/sparse/base.py
cupyx/scipy/sparse/csr.py
cupyx/scipy/sparse/dia.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

This PR implements the `diagonal` method for the DIA sparse matrix type.
The ``k`` argument (introduced in SciPy 1.0) was also added to the base `spmatrix` class.

implement diagonal method for cupyx.scipy.sparse.dia_matrix

---

cupy/__init__.py
cupy/core/__init__.py
cupy/core/raw.pxd
cupy/core/raw.pyx
docs/source/reference/kernel.rst
docs/source/tutorial/kernel.rst
tests/cupy_tests/core_tests/test_raw.py

- This PR aims to provide a public API for compiling large CUDA codes or loading CUDA modules. 
- This PR is favored over an earlier attempt #1889 for reasons discussed below. 
- Closes #1657. Closes #1889. 
- ~~This PR is built upon, and thus **blocked by**, #2369.~~
(This also serves as a refreshment of what's discussed/done early on...)
- As initially discussed in #1657, it'd be nice if an API can be exposed so that legacy CUDA codebase can be "imported" in CuPy;
- It seems that `cupy.cuda.function.Module()` was intended to be used as private API;
- It was suggested that `RawKernel.compile(long_code)` can be used as a public API, which was implemented in #1889;
- However, `RawKernel.compile()` returns a `Module` instance, not `RawKernel`, which could be misleading/confusing;
- With the …

Add `cupy.RawModule()`

---

.pfnci/config.pbtxt
.pfnci/docker/devel/Dockerfile
.pfnci/wheel_nightly.sh

This PR adds a config of pfnCI that makes wheel package of master branch. The wheel packages are uploaded to GCS and they can be used in Chainer families CI.

Make wheel of master for CI

---

cupy/__init__.py
tests/cupy_tests/test_type_routines.py

Fixed to use `numpy.find_common_type`

Avoid creating empty numpy ndarray in `common_type`

---

cupy/cuda/cufft.pyx
tests/cupy_tests/fft_tests/test_fft.py

Closes #2433, thanks to @elliottslaughter for reporting it. This bug appears in a multithreading setup and was an oversight of #2362. Now `cupy.cuda.cufft.get_current_plan()` works very much like this one: https://github.com/cupy/cupy/blob/a7d9fe0c6ff792b83bbe05f6029ae0a827512983/cupy/cudnn.pyx#L48-L51

Fixed `cupy.cuda.cufft.get_current_plan()` 

---

tests/cupy_tests/fft_tests/test_fft.py

Related: #2363, https://github.com/numpy/numpy/issues/14176

Add NumPy 1.17.1 to skip list of 0-length `ifft` test

---

tests/cupy_tests/fft_tests/test_fft.py

It seems this test passes even with NumPy 1.17.0.

Remove unnecessary skip in 0-length `ifft` test

---

tests/cupy_tests/fft_tests/test_fft.py

[backport] Add NumPy 1.17.1 to skip list of 0-length `ifft` test

---

cupy/cudnn.pyx

Rel https://github.com/chainer/chainer/pull/5808 and #2261.
cuDNN requires the strides as '(8, 8, 4)' for a tensor with the shape as '(1, 1, 2)' where the tensor is C contiguous and its shape starts with ones. On the other hand, CuPy, as well as NumPy, allows the strides as '(4, 4, 4)' even if a ndarray is C contiguous in such a case.
The latter strides makes cuDNN RNN functions fail with `CUDNN_STATUS_BAD_PARAMS`.
This PR fixes the problem with normalizing the supplied ndarray so that it has the strides cuDNN expects as done in #2261.

Normalize hidden layer strides in cuDNN RNN

---

docker/python2/Dockerfile

[backport] Fix NumPy version in Dockerfile

---

tests/cupy_tests/core_tests/test_dlpack.py

Closes #2444 
In some cases, the default memory pool might not be empty after `free_all_blocks` is called. This is happening because the gc has yet to collect some dead objects and free their references so the pool chunks can be actually freed.
This solves the issue in Jenkins by creating a new pool only for this test.

Fixed `TestDLTensorMemory.test_delete`

---

tests/cupy_tests/core_tests/test_raw.py

Fixes #2466 
Tests that require an exception to be thrown failed because newer pytest versions changed the `str` representation of the returned exception object.

Fix pytest 5.x version errors

---

cupy/core/raw.pyx

Fixes:
```
$ flake8 --config=.flake8.cython
./cupy/core/raw.pyx:192:14: W605 invalid escape sequence '\*'
./cupy/core/raw.pyx:200:51: W605 invalid escape sequence '\*'
```

Fix invalid escape sequence

---

tests/cupy_tests/cuda_tests/test_texture.py

It seems pytest does not handle global states outside of unittest classes properly. When testing `test_texture.py` from my earlier PR #2432 locally, I kept observing a cleanup error after all tests passed (!):
```shell
leofang@macbook:~/cupy$ python -m pytest tests/cupy_tests/cuda_tests/
========================================================================= test session starts =========================================================================
platform linux -- Python 3.6.5, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: /home/leofang/cupy, inifile: setup.cfg
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 450 items …
```

Remove global state from tests

---

cupy/linalg/solve.py
tests/cupy_tests/linalg_tests/test_solve.py

Closes #1903. Closes #2071. Closes #2464. 
Since this feature has been requested for multiple times, and it's not hard to fix (all needed Cython wrappers are already in place thanks to @rezoo's original commit), let us fix it once and for all.

Support complex dtypes in `cupy.linalg.inv()`

---

cupy/core/raw.pyx
cupy/cuda/cufft.pxd
cupy/cuda/cufft.pyx
cupy/cuda/driver.pxd
cupy/cuda/driver.pyx
cupy/cuda/memory.pyx
cupy/cuda/nccl.pyx
cupy/cuda/nvrtc.pxd
cupy/cuda/nvrtc.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx
cupy/cuda/stream.pxd
cupy/cuda/stream.pyx
cupy/cuda/texture.pxd
cupy/cuda/texture.pyx
docs/source/contribution.rst

Followup of #1952. Fixes #1913 further. 
This PR is encouraged in https://github.com/cupy/cupy/issues/1913#issuecomment-529298038. The main change is that most of the types in `cupy.cuda.driver` (such as `Function` and `Stream`) are pointers, and thus should be represented by `intptr_t`, see https://github.com/cupy/cupy/issues/1913#issuecomment-529262513. Once it's fixed, the changes should propagate outward to other modules.
***Challenges***: 
1. ~~In `cupy.cuda.memory` it seems streams are used in the memory mappings. I'm trying to figure out which `size_t` is meant to present a stream pointer there...~~
2. It's likely this PR would still not be enough to clear up everything. I expect an incremental approach is more appropriate.
If Jenkins can be kicked off to test the current PR, it'd …

Add appropriate pointer types in Cython to the contribute guide

---

cupy/core/_routines_statistics.pyx
tests/cupy_tests/statics_tests/test_meanvar.py

The variance for a complex-valued array is just the sum of the variances of the real and imaginary parts.
This PR only implements the `out=None` case, but that is probably by far the most common use case.

add complex dtype support to `cupy.std` and `cupy.var`

---

cupy/linalg/norms.py

This PR updates the docstring of `cupy.linalg.norm` to remove an outdated disclaimer about lack of complex support.
A few minor performance enhancements to the common `ord= 2` case were also made. There is no change in behaviour and the commits are pretty self-explanatory.

`cupy.linalg.norm`: update docstring and improve performance for ord=2 cases

---

cupy/cusparse.py
tests/cupy_tests/test_cusparse.py

Fixes #2005
Fixes #2365
Fix `coosort` by having `gthr` write to separated buffer instead of reading and writing to `x.data`

Bug: Fix `coosort`

---

cupy/cuda/__init__.py
cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

Closes #2481 
Adds a function to retrieve the current memory allocator.
Currently trying to figure out tests.

Added `cupy.cuda.memory.get_allocator` interface

---

cupy/core/_routines_statistics.pyx

Rel #2411.
Speed up `cupy.var` for complex inputs by defining custom kernel for complex value.

Performance improvement for `cupy.var` complex inputs

---

cupy/__init__.py

Closes #2476
```
$ python -W error
File "/home/ecastill/em-cupy/cupy/__init__.py", line 12, in <module>
from cupy import core  # NOQA
File "/home/ecastill/em-cupy/cupy/core/__init__.py", line 1, in <module>
from cupy.core import core  # NOQA
File "cupy/core/core.pyx", line 1, in init cupy.core.core
File "/home/ecastill/em-cupy/cupy/cuda/__init__.py", line 4, in <module>
from cupy.cuda import compiler  # NOQA
File "/home/ecastill/em-cupy/cupy/cuda/compiler.py", line 12, in <module>
from cupy.cuda import function
File "cupy/cuda/memory.pxd", line 12, in init cupy.cuda.function
File "cupy/cuda/memory.pyx", line 1, in init cupy.cuda.memory
File "fastrlock/_lock.pxi", line 4, in init fastrlock.rlock …
```

Ignore warning caused by fastrlock

---

tests/cupy_tests/cuda_tests/test_memory.py

* `TestAllocator` wrongly disables the memory pool in `tearDown`.
* Renamed `TestAllocatorDefault` to `TestAllocatorDisabled` as it intends to test behavior when memory pool is disabled.

Fix memory pool disabled during tests

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_tiling.py

Fix `cupy.repeat` error message about `repeats` argument type

---

cupy/padding/pad.py
tests/cupy_tests/padding_tests/test_pad.py

Enhancements to `cupy.pad` as discussed in #2367.
The only mode from `numpy.pad` that is omitted here is `median` due to the absence of `cupy.median`.
Aside from supporting a wider range of boundary modes, performance for the existing modes is 2-3 times faster on my machine. This is due to the performance-related refactorings done for NumPy 1.17 in PRs like numpy/numpy#11358 and numpy/numpy#11954. 
So far all padding tests pass locally when I tried them with NumPy 1.17 / Python 3.7.
**TODO?**
-  [x] include ~proposed~ bug fix for integer overflow from numpy/numpy#14209 
closes #2367

replace `cupy.pad` with a heavily refactored version from NumPy 1.17

---

cupy/testing/helper.py
tests/cupy_tests/testing_tests/test_helper.py

Fix `@testing.numpy_cupy_` decorators for skips

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/filters.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py

This PR aims to support two filters, `convolve` and `correlate`, from scipy.ndimage.fiters.
This is related to https://github.com/cupy/cupy/issues/2099.
This PR supports almost all parameters available in `convolve` and `correlate` of scipy.ndimage.filters.  You can use any `mode` of 'reflect', 'constant', 'nearest', 'minnor' and 'wrap' and you can also change the values of `cval` and `origin` from default.
As discussed in https://github.com/cupy/cupy/issues/2099, I intented to utilize the Chainer convolution implementation that executes `tensordot` after `im2col`. However, it was found that `im2col` becomes performance limiter for use-case of ndimage `convolve` and `correlate`, so I wrote a "direct convolution" code that does not require `im2col` using ElementWiseKernel.

Support `scipy.ndimage` compatible `convolve` and `correlate`

---

tests/cupy_tests/linalg_tests/test_product.py

NumPy causes `TypeError`:
```
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

Skip bool-bool inputs in `cupy.cross` test

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_tiling.py

[backport] Fix `cupy.repeat` error message about `repeats` argument type

---

cupy/manipulation/join.py
tests/cupy_tests/manipulation_tests/test_join.py

Solves #2486 . Allow axis=None in `concatenate` in which case arrays are flattened before use to be compatible with NumPy.

allow axis=None in concatenate

---

cupy/padding/pad.py
tests/cupy_tests/padding_tests/test_pad.py

cupy functions won't accept numpy arrays because it could lead to hidden device synchronization.

Avoid implicit cast inputs to cupy.ndarray in `cupy.pad`

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
tests/cupy_tests/creation_tests/test_from_data.py

Closes #2462. 
This PR is a parallel effort of the upstream PR numba/numba#4609. Although this PR is ready, it is marked as WIP and please do not review or merge until that one is approved. I will ensure any changes there to be reflected here as well. 
In the proposed v2 protocol, the `strides` field is made mandatory, and `strides=None` can be used to indicate C contiguity. 
This PR explicitly disables masked arrays (so does Numba), which was added to the v1 protocol (numba/numba#4199). When #2225 is resolved, the checks and guards implemented here should be lifted. 
To be discussed with CuPy core devs:
- ~~Do we want to enforce a strict compliance with the protocol, say, in a future release? For example,  we can check `__cuda_array_interface__['version'] == 2`. NumPy does that for …

Update `__cuda_array_interface__` to protocol version 3

---

cupy/testing/helper.py

Current shuffle-test sometimes causes stochastic test failure because the dtypes combination whose `result_type` is `bool` is rarely chosen. This PR prevents passing such tests.

Enhance shuffle-test of `testing.for_dtypes_combination`

---

cupy/cuda/cupy_cutensor.h
cupy/cuda/cutensor.pyx
cupy/cutensor.py
examples/cutensor/reduction.py

This PR aims to support new APIs for tensor reduction added in cuTENSOR 0.2.
cuTENSOR C APIs for tensor reduction are exposed in `cupy/cuda/cutensor.pyx`. In addition, a bit abstracted API **reduction()** is also exposed in `cupy/cutensor.py` so that python developers can use it easily. An example is in `cupy/example/cutensor`.
Please note that you need to set an environment variable `CUTENSOR_PATH` when you build CuPy with cuTENSOR enabled.
$ cd (to where cupy is installed)
$ CUTENSOR_PATH=/path/to/cutensor python setup.py install

Support cuTENSOR 0.2

---

cupy/linalg/decomposition.py
tests/cupy_tests/linalg_tests/test_decomposition.py

Adds support for complex dtypes in `cupy.linalg.cholesky`. C.f. https://github.com/cupy/cupy/pull/2468.

Cholesky decomposition to support complex values

---

cupy/core/_routines_math.pyx
cupy/core/_routines_statistics.pyx
cupy/cuda/cub.pyx
cupy/linalg/norms.py

This PR enables much faster 1D norms by ensuring calls to `max`, `min` and `sum` use 
```Python
axis=None, keepdims=False
```
to allow use of CUB for the reductions.
For large arrays, this can give an order of magnitude speed improvement.
For reference, the logic used here is chosen to enable the CUB code path based on:
https://github.com/cupy/cupy/blob/c9c7c4eedcca54e6f53b5dcfc205d4ad94a2b595/cupy/core/_routines_math.pyx#L76-L79
**edit**: in more recent commits below I have reverted the changes to `norm` itself and instead changed the CUB reduction code instead

enable fast CUB-based reductions in more cases (example cupy.linalg.norm)

---

cupy/cuda/cupy_cuda.h
cupy/cuda/device.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx
tests/cupy_tests/cuda_tests/test_device.py

From the issue #2440. 
This PR adds two features:
- Get a new Device by PCI Bus ID
- Get the PCI Bus ID from a Device
I'm not sure what tests I should add, I have:
- Check the returned PCI bus ID matches a specific format
- Ensure a device created with the PCI bus ID of another Device is the same device

Handle PCI bus ID

---

cupyx/__init__.py

Some initialization processes are triggered when importing `cupy.fallback_mode`, but these processes are not needed if fallback mode is not used.

Fixed not to import `cupyx.fallback_mode` default when importing `cupyx`

---

tests/cupy_tests/indexing_tests/test_indexing.py
tests/cupy_tests/manipulation_tests/test_rearrange.py

In these error cases:
* NumPy 1.14.6 or earlier emits `ValueError` instead of `numpy.core._internal.AxisError`.
* NumPy 1.15 or later emits `numpy.core._internal.AxisError`
```py
xp.arange(27).reshape((3,3,3)).diagonal(0,1,3)
```

Fix for NumPy 1.14.x compatibility

---

tests/cupy_tests/core_tests/test_ndarray_ufunc.py

It seems that NumPy 1.12.x or earlier does not handle overlapped arrays correctly. NumPy 1.13 works fine.
```py
import numpy as xp
a1 = xp.arange(1000000, dtype=xp.int64).reshape((1000,1000))
b1 = xp.transpose(a1)
a1 += b1
a2 = xp.arange(1000000, dtype=xp.int64).reshape(1000,1000)
b2 = xp.transpose(a2).copy()
a2 += b2
xp.all(a1 == b1)  # False
```

Workaround bug in NumPy 1.12.x or earlier

---

cupy/core/include/cupy/complex.cuh
cupy/core/include/cupy/complex/arithmetic.h
cupy/core/include/cupy/complex/complex.h

`ReductionKernel`, `ElementwiseKernel` and `RawKernel` couldn't use `real(number)` or `img(number)` to retrieve the real and imaginary parts of complex numbers

Allow to use `real` and `imag` on cuda kernels

---

cupy/core/include/cupy/complex/complex.h
cupy/core/include/cupy/complex/complex_inl.h
cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu
cupy/cuda/cupy_cub.h
install/build.py

This PR supersedes #2508 (was at commit 34d6ed9). Now complex-number reductions are supported ***natively*** in CUB. 
Closes #2508. Addresses #2519. 
Specifically, to achieve this we need two changes:
1. Add `__host__` qualifier to basic `thrust::complex` operations: Note that this also complies with the latest Thrust, but more importantly we need this for 2 below. (Without this change the program would crash silently, not even throwing a segfault!)
2. Add two specializations of `NumericalTraits`: see the comment in `cupy/cuda/cupy_cub.cu`.
I see a much better improvement over the previous version #2508. Statistics follow below.
cc: @grlee77 @toslunar @anaruse

Fix bug in CUB + **Native support** of complex numbers in CUB 

---

cupy/cuda/__init__.py
cupy/cuda/cupy_cusparse.h
cupy/cuda/cusparse.pyx
cupy/cuda/device.pyx
cupy/linalg/decomposition.py
cupy/linalg/eigenvalue.py
cupy/linalg/norms.py
cupy/linalg/solve.py
cupyx/linalg/sparse/solve.py
cupyx/scipy/linalg/decomp_lu.py
cupyx/scipy/sparse/linalg/solve.py
tests/cupy_tests/cuda_tests/test_cusolver.py
tests/cupy_tests/linalg_tests/test_decomposition.py
tests/cupy_tests/linalg_tests/test_eigenvalue.py
tests/cupy_tests/linalg_tests/test_norms.py
tests/cupy_tests/linalg_tests/test_product.py
tests/cupy_tests/linalg_tests/test_solve.py
tests/cupy_tests/random_tests/test_distributions.py
tests/cupy_tests/random_tests/test_generator.py
tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

This PR removes some checks that were supporting CUDA Toolkit versions older than 8.0.  [It seems that older Toolkit versions are no longer supported](https://docs-cupy.chainer.org/en/stable/install.html#requirements).
Aside from the checks, the only other change is the second commit which enables a commented-out `cusparse.getStream` method also requires CUDA Toolkit >=8.0.

checks for whether cuSOLVER is enabled aren't needed anymore

---

cupy/cuda/cupy_cusparse.h
cupy/cuda/cusparse.pxd
cupy/cuda/cusparse.pyx

The PR adds wrappers to cuSPARSE routines for preconditioners except routines deprecated in CUDA 10.1.
https://docs.nvidia.com/cuda/cusparse/index.html#preconditioners-reference

Add cuSPARSE routines for preconditioners

---

cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu
cupy/cuda/cupy_cub.h

This now works (can be verified by nvvp):
```python
dtype = cp.complex128
shape = (200, 1000, 1000)
x = cp.random.random(shape).astype(dtype) \
+1j*cp.random.random(shape).astype(dtype)
stream = cp.cuda.Stream()
with stream:
y = x.sum()  # runs on "stream" instead of the default stream
```

Support stream in CUB

---

docs/source/reference/cuda.rst

Fix #1956.
CuPy wraps CUDA runtime API. But it is not documented yet.

Add CUDA API runtime API list

---

.pfnci/config.pbtxt

This change is required for this CI script update: https://github.com/chainer/chainercv/pull/935.

Include `.git` in ChainerCV compatibility CI

---

install/build.py

See this commit for the same fix at another line https://github.com/cupy/cupy/commit/c3f11da8405440a563b86f828b689cc0a49b73bd

Use `!=` instead of `is not`  for literal

---

cupy/cuda/cupy_cufft.h

Complex numbers are defined in `cupy_cuComplex.h`, which gets included in `cupy_cuda.h`. We should just take advantage of the existing ones.

Remove redundant definitions in `cupy_cufft.h`

---

cupy/core/_routines_math.pyx
cupy/core/_routines_statistics.pyx
cupy/core/include/cupy/complex/complex.h
cupy/cuda/cub.pxd
cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu
cupy/cuda/cupy_cub.h

Part of #2519.
This PR does three things:
1. Refactor `cupy/cuda/cub.pyx` and `cupy/cuda/cupy_cub.*` to eliminate a lot of redundant lines for making the No.2 change below much easier;
2. Support `sum(axis=...)`, `min(axis=...)`, and `max(axis=...)` using CUB's **device segmented reduce** API. Because this API can only reduce over contiguous segments, any reduction with non-contiguous axes (e.g., `axis=(0, 2)` for `ndim=3`) is still deferred to the old reduction kernel. 
3. Enforce the alignments for Thrust's complex types to ensure performance
(I tried making a device-device copy to transpose the array at commit 31304f4 for non-contiguous cases, but the performance was just killed by copy. I can post an `nvvp` screenshot if anyone is interested.)
~~Note that for complex numbers with an …

Refactor CUB to support an explicit `axis` argument; Fix alignments for Thrust's complex types

---

cupy/linalg/decomposition.py
tests/cupy_tests/linalg_tests/test_decomposition.py

Part of #2371.  LAPACK does not have to be called for 0-sized arrays.
The test cases are from #2372.

Support 0-sized arrays for `linalg.qr`

---

examples/stream/map_reduce.py

Closes #1695. Closes #2524.
In #1695 it was reported by @mrocklin that no concurrency was seen in the demo even with multiple streams. In #2524 it was found by @emcastillo that it was simply because the workload was too small. Increasing the workload helps observe stream overlap, see below.
Before this PR:
With this PR:
Tested on P100.

Show better performance improvement in `examples/stream/map_reduce.py`

---

cupy/core/include/cupy/_cuda/cuda-10.1/cuda_fp16.hpp

Ref #2569. Pull in changes in Update 2.
Although this change is not described in the CUDA release note, Update 2 is `binary compatible with CUDA 10.1` (https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#title-u2-new-features) so it should run with 10.1 / 10.1 Update 1.

Import CUDA headers from CUDA 10.1 Update 2 (10.1.243)

---

cupy/linalg/decomposition.py
tests/cupy_tests/linalg_tests/test_decomposition.py

[backport] Support 0-sized arrays for `linalg.qr`

---

.pfnci/config.pbtxt
.pfnci/docker/devel/Dockerfile
.pfnci/wheel_nightly.sh

* Copy configuration from master branch.
* Activate `cupy.py2.cv.gpu`, `cupy.py2.cv.examples` configurations (copy configuration from the default config) and enable `include_dot_git` for https://github.com/chainer/chainercv/pull/935 .
See also: https://github.com/chainer/chainer/pull/8352

[v6] Add missing FlexCI configurations

---

docs/source/install_rocm.rst
docs/source/reference/environment.rst

Closes #661. As per requested in https://github.com/cupy/cupy/issues/661#issuecomment-524750781. 
All of the env variables are searched via `grep --include=\*.{pyx,pxd,pxi,py} -R './' -e 'CUPY_'`. Except for `CUB_PATH` and `CUB_DISABLED` (to be discussed with CuPy core devs, see https://github.com/cupy/cupy/pull/2562#issuecomment-548390938), I hope I am not missing anything.

Document more environment variables

---

cupy/core/core.pxd
cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_conversion.py

Makes a simple implementation of `tobytes` for CuPy arrays, which converts the data back into a NumPy array and let's NumPy do the heavy lifting.

Implement `tobytes` for CuPy arrays

---

cupy/core/_routines_statistics.pyx
cupy/cuda/cub.pxd
cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu
cupy/cuda/cupy_cub.h

This PR is made easy based on the refactoring in #2562. Part of #2519.
Notes:
1. Currently an explicit `axis` argument is not supported. In fact, I am a bit reluctant to add CUB support for it because of two reasons:
- According to the NumPy behavior `axis` can only be an integer, not a tuple (see #2595), meaning that only the special case `axis=-1` (searching over the last axis) can be benefited by `device_segmented_reduce` added in #2562, which doesn't seem worth the time...
- On the technical side, the output of `device_segmented_reduce` would be an array of key-value pairs. I am not sure what's the best way to retrieve the keys (i.e. the wanted array indices). Seems like I need one extra kernel launch to loop data over and copy keys to another device array? Any comment or suggestion …

Add CUB support for `argmax()` and `argmin()`

---

cupy/sorting/search.py
tests/cupy_tests/sorting_tests/test_search.py

Backport of #2175
Closes #2613

[backport] Support complex dtypes in `cupy.where`

---

cupy/core/carray.pxi
cupy/core/core.pxd
cupy/core/include/cupy/cuComplex_bridge.h
cupy/core/raw.pxd
cupy/core/raw.pyx
docs/source/tutorial/kernel.rst
tests/cupy_tests/core_tests/test_raw.py

Closes #1866. Closes #2111.
Previously the support of complex numbers in `cupy.RawKernel` (and thus `cupy.RawModule`) was poorly documented, see https://github.com/cupy/cupy/pull/1866#issuecomment-457791608 and #2111 for example. This PR aims to solve this problem once and for all. This PR supersedes #1866.
The support of the APIs from `cuComplex.h` is enabled by prepending a set of C macros that replace those APIs by their Thrust counterparts. Thus, users can just copy and paste their `cuComplex`-based codes to `cupy.RawKernel` or `cupy.RawModule`, and make them work without any modification. Note that the complex mathematical functions are supported without any additional macros.
For backward compatibility, the newly added option `enable_cuComplex` is set to `False` by default.
attn: …

Support cuComplex.h in `cupy.RawKernel` and `cupy.RawModule`

---

cupy/cudnn.pyx

Fix chainer/chainer#6644 and some other cuDNN issues.  Revert an ad-hoc fix.  `_make_tensor_descriptor_array` could be fixed similarly, but not in this PR.
Drawback:
- Normalized stride is incorrect if an input array has 1-length axes and other contiguity is used.
Alternative fixes:
- Use `_ascontiguousarray_normalized_strides` (in #2261) everywhere
- It will create more `ndarray` objects.
- It is overhead if (4-dim) tensor discriptor is used.  It is too unmaintainable to keep `core._internal_ascontiguousarray` for the safe cases.
- It depends that the internal `_reshape` preserves normalized strides. https://github.com/cupy/cupy/blob/b9db374f4d0ccee358a998d7b283248f77cef351/cupy/cudnn.pyx#L1673-L1674
- Make contiguous array and its cuDNN descriptor simultaneously.
- Not easy to fix the …

Normalize strides of cuDNN descriptors

---

cupy/math/special.py
tests/cupy_tests/math_tests/test_special.py

Closes #2645 
`sinpi` is a cuda only function that does not have an equivalent in thrust for complex numbers.
Note that the original numpy implementation uses the product of pi instead of an optimized sin.
Question:
Should we split the routines using a dispatcher, as the ufuncs doesnt seem to support overloading functions, one for complex and one for non-complex numbers?

Add support of complex dtypes for `sinc`

---

cupy/__init__.py
cupy/creation/from_data.py
cupy/io/__init__.py
cupy/io/rawfile.py
tests/cupy_tests/creation_tests/test_from_data.py
tests/cupy_tests/io_tests/test_rawfile.py

For now this does the simple thing of calling `numpy.fromfile` and converting the result to a CuPy array, which is returned. In the future this could be replaced by something more optimal (like https://github.com/cupy/cupy/issues/2576 ;).

Add fromfile

---

setup.py

This PR provides rich information for [PyPI](https://pypi.org/project/cupy/).

Add software description to setup.py

---

cupy/core/include/cupy/complex/complex.h

Avoid using `__align__` in ROCm

---

cupy/core/_routines_manipulation.pyx
cupy/testing/__init__.py
cupy/testing/helper.py
tests/cupy_tests/manipulation_tests/test_shape.py

[backport] Do not allow `reshape` on empty arrays

---

cupy/core/_kernel.pyx

Cache `ElementwiseKernel` kernel globally instead of per instance

---

cupy/cudnn.pyx

This PR adds support for new batch normalization interface introduced in cuDNN 7.4.1.
https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_741.html
`cupy.cudnn.batch_normalization_forward_training_ex()` returns an extra value "reserve space" that can be passed to the backward API for faster computation.
See also: https://github.com/chainer/chainer/pull/7620

Add cuDNN new batch normalization

---

cupy/cuda/cupy_cusparse.h

Remove stubs for APIs dropped in CUDA 10.1 Update 2

---

cupy/core/_kernel.pyx

[backport] Cache `ElementwiseKernel` kernel globally instead of per instance

---

tests/cupy_tests/creation_tests/test_from_data.py

Followup of #2491. Resolves #2521. 
cf. https://github.com/cupy/cupy/pull/2534#issuecomment-539341617.

Add backward compatibility test for `__cuda_array_interface__`

---

cupy/linalg/norms.py
tests/cupy_tests/linalg_tests/test_norms.py

Use `cupy.where(dev_info, ...)` to avoid sync.
Fix #2650.

Fix `det` and `slogdet` on singular inputs

---

cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

Closes #2625 
Allows set_allocator to behave as a context manager and a regular function as the same time.

Add `using_allocator` context manager

---

cupy/lib/__init__.py

This PR fixes AttributeError of `stride_tricks`. The following code works with NumPy, but not with CuPy.
```
import numpy
numpy.lib.stride_tricks.as_strided
import cupy
cupy.lib.stride_tricks.as_strided
```
```
AttributeError: module 'cupy.lib' has no attribute 'stride_tricks'
```

Fix `AttributeError` of `stride_tricks`

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_sample.py

Currently randint will fail when handed tuple with a value `(0,)`
>cupy.random.randint(10, None, size=(0,))
> AttributeError: 'NoneType' object has no attribute 'reshape'
This PR resolves the error by handing back any empty cupy array if the ret value is `None`

handle tuple with value 0 and return empty array

---

cupy/cuda/memory.pyx

This PR removes `std::map` for simple implementation.
And, this PR improves speed.

Remove std::map for simple implementation

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
tests/cupy_tests/creation_tests/test_from_data.py

Backport of #2491 and #2536
Only consuming side is being backported.

[backport] Update `__cuda_array_interface__` to protocol version 2

---

cupy/cuda/memory.pyx

`getattr(_thread_local, 'allocator', _current_allocator)` is slow because it creates error object.

Avoid threading.local() object overhead

---

cupy/lib/stride_tricks.py

The warning in the document of `as_strided` has not been correctly shown.
https://docs-cupy.chainer.org/en/v7.0.0rc1/reference/generated/cupy.lib.stride_tricks.as_strided.html

Fix document format of `as_strided`

---

cupy/random/generator.py

https://github.com/cupy/cupy/pull/2706#discussion_r350521248
It looks obvious this assertion holds, and this condition does not affect the behavior of the following code.

Remove insignificant assertion

---

cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

set_allocator should throw an error when used inside `using_allocator` context manager

Make `set_allocator` and `get_allocator` symmetric

---

cupy/core/internal.pyx

`vector.vector[Py_ssize_t]` allocation is slow.

Remove memory allocation in set_contiguous_strides

---

cupy/__init__.py
cupy/core/_routines_manipulation.pyx
cupy/core/core.pyx
cupy/cusparse.py
cupy/linalg/decomposition.py
cupy/linalg/norms.py
cupy/linalg/solve.py
cupy/statistics/correlation.py
cupy/statistics/meanvar.py
cupyx/linalg/solve.py
cupyx/linalg/sparse/solve.py
cupyx/scipy/linalg/solve_triangular.py
cupyx/scipy/sparse/base.py
cupyx/scipy/sparse/linalg/solve.py

I have replaced `numpy.find_common_type` with use of `numpy.promote_types` where possible.
A couple basic benchmarks showing relative timings (for NumPy 1.17.3):
e.g.
```
%timeit np.find_common_type([np.int, 'f'], [])
6.4 µs ± 23.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
%timeit np.result_type(*(np.int, 'f'))
657 ns ± 1.19 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
%timeit np.promote_types(np.int, 'f')
148 ns ± 0.644 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
This is also true for long lists of types
```
import functools
types = [np.int, 'f'] * 100
%timeit np.find_common_type(types, [])
84.8 µs ± 232 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit …
```

Avoid use of slow numpy.find_common_type

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Avoid two tests that segfault within SciPy when it is version 1.3.* (or 1.4.0rc1). See scipy/scipy#11125.
Hopefully this will be fixed prior to the final 1.4.0 release.

Skip tests that segfault when using SciPy 1.3.x

---

cupy/core/_kernel.pyx
cupy/core/_routines_manipulation.pxd
cupy/core/_routines_manipulation.pyx

This PR avoids allocation of `list` and `tuple`.

Improve broadcast

---

cupy/__init__.py

`cupy.cupyx` may be too confusing to users who just did `pip install cupy`.
Ref: #2654.

Remove `cupy.cupyx`

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

[backport] Skip tests that segfault when using SciPy 1.3.x

---

cupy/core/core.pxd
cupy/core/core.pyx

`ndarray` only accepts `tuple` like object. `_ndarray_init` accepts `vector`. We will be able to pass `vector` without cast.

Add _ndarray_init to reduce ndarray creation cost

---

cupy/cuda/memory.pyx

The memory allocation is core part in CuPy. So, I want to speed up it.

Avoid __init__ function call overhead in memory allocation

---

cupy/core/core.pyx

`reduced_view` is a CuPy original function. `dtype` argument is not used.
- Deprecated `dtype` argument
- Add fast path with `_c_contiguous` input

Improve ndattay.reduced_view

---

cupy/internal.py
cupy/linalg/einsum.py
cupy/linalg/product.py
cupy/linalg/solve.py
cupy/testing/helper.py

Close #2661. Removed `cupy.internal.prod()` by redirecting to `cupy.core.internal.prod()`. 
Not sure if my `grep` caught all of the target `prod()` calls, so I need to rely on CI tests for this.

Remove `cupy/internal.py`

---

cupy/core/_scalar.pxd
cupy/core/_scalar.pyx
cupy/core/reduction.pxi

I would have defined `@staticmethod cdef CScalar.from_int32()`, but `cdef` class cannot have a static method.

Avoid tricky initialization of block stride

---

cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu
cupy/cuda/cupy_cub.h
cupyx/scipy/sparse/csr.py

I was curious whether CUB would also improve the performance of sparse matrix multiplication. It seems that for < ~ 1,000,000 non-zero entries it is faster. At sizes larger than that, it is basically tied with cuSPARSE. A bit disappointing that the >3 fold gains at smaller sizes don't hold up for the larger problems of interest, although would be curious if this is also true for higher-end NVIDIA cards. (I tested with a GTX 1080 Ti)
The main limitation is that CUB only has this one sparse matrix function so it is limited to CSR only. Aside from performance, I think the other feature it has over cuSPARSE is that it can be used for additional dtypes such as `int` that are not supported by cuSPARSE. This can be done with the undocumented `device_spmv` function here, but the end-user …

CUB-based CSR sparse matrix vector multiply

---

cupy/fft/fft.py
cupyx/scipy/fft/__init__.py
cupyx/scipy/fft/fft.py
docs/source/reference/fftpack.rst
docs/source/reference/scipy.rst
docs/source/reference/scipy_fft.rst
setup.py
tests/cupy_tests/fft_tests/test_fft.py
tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py

SciPy version 1.4 will have a new submodule [`scipy.fft`] with an interface very similar to `numpy.fft`. This adds a subset of that interface to `cupyx.scipy` and also adds [`uarray`]-based backend support allowing cupy FFTs to be called through the `scipy.fft` interface e.g.
```python
import cupy
import cupyx.scipy.fft as cu_fft
import scipy.fft
x = cupy.arange(10)
scipy.fft.fft(x)  # ValueError: object __array__ method not producing an array
with scipy.fft.set_backend(cu_fft):
scipy.fft.fft(x)  # Calls into cupyx, returning a cupy array
```
Tests are currently failing but at least some of the failures seem to be bugs in `cupy.fft`. I need to investigate further.
[`scipy.fft`]: https://scipy.github.io/devdocs/fft.html
[`uarray`]: …

Add scipy.fft to cupyx

---

cupy/__init__.py
cupy/core/core.pyx
cupy/sorting/search.py
cupy/statistics/histogram.py
tests/cupy_tests/sorting_tests/test_search.py

Implements `searchsorted`
As in NumPy the function assumes that the `a` array is monotonic increasing and doesn't explicitly check it.
The implemented kernel adds a `check` option to detect wether the array is increasing or decreasing by comparing two values. This is to allow an efficient implementation of `digitize`.

Add `searchsorted`

---

cupy/core/reduction.pxi

This PR adds `_get_reduction_args` to remove duplicated code.
~Please merge #2689 before this PR.~

Improve reduction core

---

cupy/testing/helper.py

Delay import of pkg_resources
On my Windows workstation, `import cupy` takes 3.5 s, about 3 s of which are spent in `import pkg_resources`.
Importing `pkg_resources` is known to be excruciatingly slow. See https://github.com/pypa/setuptools/issues/510

Fix slow import of cupy

---

cupy/fft/fft.py
tests/cupy_tests/fft_tests/test_fft.py

From #2355, this PR backports the fixes in `cupy/fft/fft.py`.
The n-dim FFT implementation `_fftn` should correctly handle
- `axes=None` regardless of whether `shape` is specified, and
- unsorted `axes`

[v6] Fix axes handling in `_fftn`

---

cupy/cuda/cupy_cuda.h
cupy/cuda/cupy_hip.h
cupy/cuda/driver.pxd
cupy/cuda/driver.pyx

Part of #2768. It's currently unused in the codebase, and it's marked deprecated for quite some time, so let us remove it to suppress some deprecate warnings.

Remove unused `cuParamSetTexRef()`

---

cupy/cuda/cupy_thrust.cu
cupy/cuda/thrust.pyx
tests/cupy_tests/sorting_tests/test_sort.py

Support `sort()`/`msort()`, `lexsort()` and `argsort()` on `complex64` and `complex128` arrays. I am making the build time of the `cupy.cuda.thrust` module even longer! 🤣
Supporting complex numbers in the `thrust` module  is trickier than in the `cub` module, because it can only depend on `cuComplex.h`. I couldn't get the complex headers from either CuPy or Thrust to work. The former compiles but segfaults at import time (likely due to the namespace collision), and the latter gives me "no matching `thrust::complex<T>::real` found" error even after I added specializations of `operator<()` and `real()` (a77d1bf contains leftovers of failed attempts). Perhaps enabling CUB's `sort` support would circumvent this problem, but it should be a separate PR. 
NumPy has a special rule for sorting …

Support sorting complex arrays

---

cupy/core/reduction.pxi

I just want to make `reduction.pxi` a bit more organized and consistent.
This PR only includes renames and reorder of private functions/class.
* `_get_simple_reduction_kernel()` -> `_create_reduction_function()`
* `class simple_reduction_function` -> `class _SimpleReductionKernel`
* `_get_simple_reduction_function()` -> `_SimpleReductionKernel_get_cached_function()`
* `_get_reduction_kernel()` -> `_ReductionKernel_get_cached_function()`
Any comments are welcome (as usual).

Rename and reorder private functions in `reduction.pxi`

---

cupy/core/_kernel.pyx

`numpy.can_cast` is called many times.
The new routine uses ` numpy.min_scalar_type` instead of `numpy.can_cast`.
I added benchmark result.

Avoid `numpy.can_cast` call to improve guess routine 

---

cupy/core/raw.pyx

Part of #2779. 
This PR is simply to demonstrate that it is very easy to support PTX in `cupy.RawModule`. It's basically a one-line change. 
While I do not have any opinion in whether to support this or not, I did have this possibility in mind when adding `cupy.RawModule` in #2389, and recently I heard there exists people writing PTX directly instead of in CUDA C/C++, despite it is a quite unusual and inefficient approach IMHO. 
I'll let the core devs make the decision for the PTX support.

Support loading PTX in `cupy.RawModule`

---

cupy/core/raw.pyx
docs/source/tutorial/kernel.rst
tests/cupy_tests/core_tests/test_raw.py
tests/cupy_tests/cuda_tests/test_texture.py

Current API can't handle a code with a comment ending with `.cubin` at the end.

Separate code and path arguments in `RawModule`

---

cupy/core/_kernel.pyx

`numpy.can_cast` is very slow. rel #2673.

Avoid `can_cast` calling to reduce overhead

---

tests/cupy_tests/linalg_tests/test_product.py

The issue is found in #2569.
The PR fixes:
- `a ** 2` is less accurate than `a * a`;
- condition number of `[[1, 4, 9], [16, 25, 36], [49, 64, 81]]` is somewhat large.

Use more stable input to test `linalg.matrix_power`

---

tests/cupy_tests/linalg_tests/test_product.py

[backport] Use more stable input to test `linalg.matrix_power`

---

cupyx/__init__.py
cupyx/time.py
tests/cupyx_tests/test_time.py

I want to officially support some helpers to measure CPU/GPU execution times.
CuPy organization has [cupy-benchmark](https://github.com/cupy/cupy-benchmark) currently, but it is for the maintainers to show users the performance results. I want to support this feature for also external contributors and users.

Add helpers to measure execution times

---

cupy/core/reduction.pxi

Currently `_get_reduction_args()` includes calculation of kernel block parameters.
Its role is too bloated.
Context: I had difficulty resolving merge conflict of #2731 with master.

Refactor reduction code

---

cupyx/scipy/ndimage/filters.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py

This PR makes the allowed settings for origin match SciPy's behavior.
The actual origin validation code in current scipy master is
```Python
(origin < -(lenw // 2)) or (origin > (lenw - 1) // 2)
```
I just made the minimal needed change here, but can change to match the style above exactly if you prefer that
This fix corresponds to the following PR merged for SciPy 1.2: scipy/scipy#8817. It seems older versions might segfault for some invalid `origin` settings.

fix range used in cupyx.scipy.ndimage filter origin check

---

cupy/cuda/compiler.py
cupy/cuda/pinned_memory.pyx
cupy/cuda/stream.pyx
cupy/cusparse.py
cupy/cutensor.py
cupy/random/generator.py
cupy/util.pyx

Closes #2806, #2658, and #2777 
In some python interpreters (mostly installed with pyenv)
The following one-liner causes an exception in object destruction during interpreter shutdown.
`python -c 'import cupy; stream = cupy.cuda.Stream()'`
When finishing program execution, python does not guarantee the order in which objects are destroyed.
Calls inside a __del__ method calling other objects or modules are not guaranteed to be correctly executed as those objects can be already deleted.
[PEP442](https://docs.python.org/3/whatsnew/3.4.html#whatsnew-pep-442) should address this, but we have seen this problem persists.
This solution is obtained from [Numba/llvmlite](https://github.com/numba/llvmlite/blob/9ddb1a52b259daa418cd33f62cfe8f4992c7a2d3/llvmlite/binding/common.py#L27-L41) code.

Detect interpreter shutdown for proper `__del__` behavior

---

cupy/cuda/compiler.py
cupy/cuda/pinned_memory.pyx
cupy/cuda/stream.pyx
cupy/cusparse.py
cupy/random/generator.py
cupy/util.pyx

[backport] Detect interpreter shutdown for proper `__del__` behavior

---

cupy/__init__.py
cupy/core/__init__.py
cupy/core/_kernel.pxd
cupy/core/_kernel.pyx
cupy/core/_reduction.pxd
cupy/core/_reduction.pyx
cupy/core/_routines_logic.pyx
cupy/core/_routines_manipulation.pxd
cupy/core/_routines_manipulation.pyx
cupy/core/_routines_math.pyx
cupy/core/_routines_statistics.pyx
cupy/core/core.pyx
cupy/core/fusion.pyx
cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/manipulation/rearrange.py
cupy_setup_build.py
tests/cupy_tests/core_tests/fusion_tests/test_function.py
tests/cupy_tests/core_tests/test_reduction.py

Removes `include 'reduction.pxi'` as it's confusing, because often you lose where functions are actually defined.
`_kernel.pyx` uses `_broadcast_core()`. Importing `_routines_manipulation.pyx` from `_kernel.pyx` causes cyclic dependencies. ~I refactored `_broadcast_core()` and `class broadcast` as `_broadcast.pyx`.~
I only moved `_broadcast_core` to `internal.pyx`.

Separate reduction code from `_kernel.pyx`

---

cupy/linalg/decomposition.py
cupy/linalg/norms.py
tests/cupy_tests/linalg_tests/test_norms.py

`linalg.det` using `getrfBatched` is originally implemented in chainer/chainer#613.
For the input `random.randn(256, 256, 256)`,
- v6: 0.85 sec
- v7 (after #2437 and #2660): 1.2 sec
- this PR: 0.022 sec

Use getrfBatched in `linalg.slogdet`

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_split.py

Close #2163.
`cupy.split` and `cupy.array_split` raise some error when they take indices that have an index exceeds the target axis' dimension. This PR fix it to make them return empty arrays for such sections as NumPy does.

Fix split and array_split with indices overrun

---

cupy/core/raw.pyx

[backport] Fix docs of options argument in RawKernel and RawModule

---

cupy/creation/from_data.py

[backport] Fix the docstring format of `cupy.asarray`

---

cupy/core/include/cupy/complex.cuh
cupy/core/include/cupy/complex/arithmetic.h
cupy/core/include/cupy/complex/catrig.h
cupy/core/include/cupy/complex/catrigf.h
cupy/core/include/cupy/complex/ccosh.h
cupy/core/include/cupy/complex/ccoshf.h
cupy/core/include/cupy/complex/cexp.h
cupy/core/include/cupy/complex/cexpf.h
cupy/core/include/cupy/complex/clog.h
cupy/core/include/cupy/complex/clogf.h
cupy/core/include/cupy/complex/complex.h
cupy/core/include/cupy/complex/complex_inl.h
cupy/core/include/cupy/complex/cpow.h
cupy/core/include/cupy/complex/cproj.h
cupy/core/include/cupy/complex/csinh.h
cupy/core/include/cupy/complex/csinhf.h
cupy/core/include/cupy/complex/csqrt.h
cupy/core/include/cupy/complex/csqrtf.h
cupy/core/include/cupy/complex/ctanh.h
cupy/core/include/cupy/complex/ctanhf.h
cupy/core/include/cupy/complex/math_private.h

Closes #2629. Changes (see the discussion starting https://github.com/cupy/cupy/issues/2629#issuecomment-558448086):
1. Add a `__host__` qualifier to all functions
2. Sync a few function implementations with the upstream counterparts
3. Adjust some style and format
4. Fix a bug: https://github.com/cupy/cupy/pull/2741#discussion_r353360865

Update thrust::complex headers with a bug fix

---

cupy/core/_kernel.pxd
cupy/core/_kernel.pyx
cupy/core/_routines_math.pyx
cupy/core/reduction.pxi
tests/cupy_tests/math_tests/test_arithmetic.py
tests/cupy_tests/statics_tests/test_meanvar.py

[backport] Fix `true_divide` with dtype argument
