cupy/cupy

docs/source/tutorial/gpu.rst

There is no such convenient function.

No such methods

---

setup.py

CuPy is not depend on protobuf.

Remove dependency to protobuf

---

docs/source/tutorial/gpu.rst

`cuda.init` is a function in chainer.

Remove description about init

---

docs/source/tutorial/gpu.rst

I fixed GPU tutorial to pass the test.

Fix gpu tutorial to pass the test

---

.pep8
.travis.yml
README.md
cupy/core/carray.cuh
cupy/core/core.pyx
cupy/core/fusion.py
cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h
cupy/cuda/cupy_nccl.h
cupy/cuda/nccl.pxd
cupy/cuda/nccl.pyx
cupy/cudnn.py
cupy/linalg/__init__.py
cupy/linalg/decomposition.py
cupy/testing/helper.py
cupy_setup_build.py
docs/source/conf.py
docs/source/cupy-reference/linalg.rst
docs/source/install.rst
install/build.py
tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
tests/cupy_tests/core_tests/test_ndarray_indexing.py
tests/cupy_tests/linalg_tests/test_decomposition.py
tests/cupy_tests/manipulation_tests/test_rearrange.py

Merge v1.24

---

README.md
cupy_bibtex.txt

Remove Chainer reference

---

cupy/core/core.pyx
cupy/cuda/memory.pyx
tests/cupy_tests/core_tests/test_ndarray_indexing.py

Retarget of this PR: https://github.com/pfnet/chainer/pull/2726
Fixes https://github.com/pfnet/chainer/issues/2722

Avoid adding non-zero offset to zero-pointer

---

cupy/core/carray.cuh
cupy/core/carray.pxi
cupy/core/core.pyx
cupy/testing/__init__.py
cupy/testing/attr.py
tests/cupy_tests/core_tests/test_carray.py
tests/cupy_tests/core_tests/test_ndarray_reduction.py
tests/cupy_tests/creation_tests/test_basic.py
tests/cupy_tests/math_tests/test_sumprod.py

Please see also https://github.com/pfnet/chainer/pull/1894 and https://github.com/pfnet/chainer/pull/2263

Support 64bit address

---

README.md
cupy/cuda/compiler.py
docs/source/install.rst
setup.py

This PR remove filelock.
Advantage
- speed up (lock free)
- Improve stability on cluster file system

Remove filelock

---

tests/cupy_tests/core_tests/test_fusion.py

Retarget from https://github.com/pfnet/chainer/pull/2725.
Fixes https://github.com/pfnet/chainer/issues/2720.

Stabilize fusion test

---

cupy/core/carray.cuh

This PR replaces https://github.com/cupy/cupy/pull/51/.

Stop overloading pointer types and non-pointer types

---

cupy/core/carray.cuh

Fix constness in `carray.cuh`. https://stackoverflow.com/a/856839

Fix constness in carray.cuh

---

cupy/core/carray.cuh

Remove some unnecessary static functions in carray.cuh

Remove some unnecessary static functions in carray.cuh

---

docs/source/install.rst

relate to https://github.com/pfnet/chainer/pull/2729

Update installation guide

---

tests/cupy_tests/manipulation_tests/test_basic.py

Remove unused import

---

cupy/__init__.py
cupy/core/core.pyx
cupy/cuda/common.pxd
cupy/cuda/cupy_common.h
cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx
cupy/sorting/sort.py
cupy_setup_build.py
docs/source/reference/sorting.rst
install/build.py
setup.py
tests/cupy_tests/sorting_tests/test_sort.py

This PR implements cupy.sort, resending the changes of https://github.com/pfnet/chainer/pull/2539 and https://github.com/pfnet/chainer/pull/2581 for chainer v1.

Implement cupy.sort.

---

install/build.py

Update minimum CUDA and cuDNN version

---

cupy/core/core.pyx
cupy/sorting/sort.py

Small fixing about sort function

---

cupy/core/core.pyx
cupy/core/internal.pyx

Currently, setup.py outputs some warnings. This PR reduce that warnings.

Reduce setup warnings

---

install/build.py

Minimum CUDA version was changed.

Fix minimum CUDA version in an error message

---

cupy_setup_build.py

Modules which causes an error on install need to be skipped.

Skip modules to install which cannot pass their tests

---

docs/source/conf.py
docs/source/tutorial/basic.rst
docs/source/tutorial/kernel.rst

- Use `cp` and `np`.
- Use `doctest` instead of `testcode`.

Fix doctest

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

Gumbel-max trick uses `argmax(u + g)` where u is log(p) and g is a sample from Gumbel distribution.

Fix choice

---

docs/source/tutorial/basic.rst

Add missing line break after doctest.

Fix missing doc line break

---

cupy/cuda/cupy_cusparse.h
cupy/cuda/cusparse.pxd
cupy/cuda/cusparse.pyx
cupy_setup_build.py

I added cusparse stub code.
related to #36

Add cuSPARSE APIs

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

Make random.get_random_state() thread-safe

---

tests/cupy_tests/random_tests/test_generator.py

This test sometimes fails. I fixed its condition.

Fix test condition for choice method

---

examples/kmeans/kmeans.py

Use c argument instead of color.

Fix color argument

---

docs/source/tutorial/basic.rst

[backport] Fix missing doc line break

---

examples/kmeans/kmeans.py

[backport] Fix color argument

---

cupy/cuda/memory.pyx
cupy/cuda/pinned_memory.pyx

[backport] Memory pool is thread unsafe

---

cupy_setup_build.py
install/build.py

[backport] Fix nvcc not found

---

cupy/core/core.pyx
cupy/linalg/decomposition.py

`copy` argument in `astype` is keyword argument.
related to #111

Use keyword argument

---

tests/cupy_tests/random_tests/test_generator.py

V1 stabilize choice

---

docs/source/overview.rst

[backport] Add to doc about advanced indexing support

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

This PR is backport to v1.
This PR was reviewed by #78

[backport] Make random.get_random_state() thread-safe

---

cupy/random/__init__.py
cupy/random/sample.py
tests/cupy_tests/random_tests/test_sample.py

I implemented `cupy.random.multinomial`. Please merge #84 first.

Implement multinomial

---

cupy_setup_build.py

Fix error message in setup script

Fix error message in setup script

---

cupy_setup_build.py

[backport] fix-error-in-setup

---

docs/source/reference/difference.rst

Remove description about exponential of boolean array

---

docs/source/tutorial/basic.rst

[backport] Fix document

---

cupy/manipulation/dims.py
tests/cupy_tests/manipulation_tests/test_dims.py

~Supports `numpy.ndarray` in `atleast_<n>d`.~
Also done some refactoring.

Refactor atleast_nd

---

cupy/cudnn.py

This PR is related to dilated convolution and for enabling you to use cuDNN v6's implementation of dilated convolution. This is related to https://github.com/chainer/chainer/pull/2858

cuDNN v6 dilated convolution

---

cupy/__init__.py
cupy/math/sumprod.py
docs/source/reference/math.rst
tests/cupy_tests/math_tests/test_sumprod.py

I implemented `cumprod` function based on `cumsum` function.
In addition, I also fixed typos in the docstring of cumsum function (cumlative -> cumulative).

Implement cumprod function

---

docs/source/overview.rst

[backport] Use HTTPS for chainer.org

---

cupy/core/carray.cuh
cupy/core/core.pyx

Please merge #160 before this PR.

Use ndim in _concatenate_kernel

---

cupy/linalg/__init__.py
cupy/linalg/norms.py
docs/source/reference/linalg.rst
tests/cupy_tests/linalg_tests/test_norms.py

I implemented `matrix_rank` based on NumPy's implementation.

Implement matrix_rank

---

docs/source/conf.py

This PR is a port from https://github.com/chainer/chainer/pull/2758 ~(currently not merged yet)~.

Link to GitHub source page (CuPy)

---

README.md

Fix https://github.com/cupy/cupy/issues

Add Development section on README.md

---

cupy/cuda/cupy_cusolver.h
cupy/cuda/cusolver.pxd
cupy/cuda/cusolver.pyx
cupy/linalg/__init__.py
cupy/linalg/norms.py
docs/source/reference/linalg.rst
tests/cupy_tests/linalg_tests/test_norms.py

I implemented slogdet which calculates sign and log of determinant.

Implement slogdet

---

docs/source/conf.py

[backport] Link to GitHub source page (CuPy) 

---

.travis.yml

This PR is a backport of #100.

[backport] Fix travis

---

tests/cupy_tests/random_tests/test_generator.py

This PR is the backport of #175.

[backport] Fix expected histogram in RandomState.interval test

---

cupy/cuda/memory.pyx

This PR is a backport of https://github.com/cupy/cupy/pull/170

[backport] Fix multi thread  bug in memory pool

---

cupy/cuda/memory.pyx

Reverts cupy/cupy#170
Please see discussion in #170.

Revert "Fix multi thread  bug in memory pool"

---

cupy/cuda/memory.pyx

Reverts cupy/cupy#181
Please see discussion in #170.

Revert "[backport] Fix multi thread  bug in memory pool"

---

cupy/__init__.py
cupy/creation/ranges.py
cupy/indexing/generate.py
tests/cupy_tests/creation_tests/test_ranges.py
tests/cupy_tests/indexing_tests/test_generate.py

I implemented cupy.mgrid and cupy.ogrid functions.
Along with that, I changed the behavior of cupy.arange in case of step=None
and implemented cupy.indices.

Implement mgrid and ogrid

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

Retarget of this PR: https://github.com/pfnet/chainer/pull/2548
Fixes https://github.com/pfnet/chainer/issues/2547

Fuse decorator without paren

---

README.md
cupy_setup_build.py
setup.py

The URL of CuPy documents was changed.

Fix document URL

---

README.md

[backport] Improve readability of README.md

---

cupy/core/elementwise.pxi

Clean up `core._preprocess_args` function for (slightly) performance

Clean up core._preprocess_args

---

README.md
cupy_setup_build.py
setup.py

[backport] Fix document URL

---

cupy/testing/array.py
tests/cupy_tests/testing_tests/test_array.py

[backport] Check type in assert_array_list_equal

---

cupy/testing/__init__.py
cupy/testing/condition.py

- Use direct import for IDE
- Skip environment variable check.

Improve test

---

cupy/testing/__init__.py

[backport] Improve test

---

cupy/cuda/cupy_cusolver.h
cupy/cuda/cusolver.pxd
cupy/cuda/cusolver.pyx
cupy/linalg/__init__.py
cupy/linalg/eigenvalue.py
cupy_setup_build.py
docs/source/reference/linalg.rst
tests/cupy_tests/linalg_tests/test_eigenvalue.py

I implemented eigh and eigvals API.
It is copied from https://github.com/pfnet/chainer/pull/2429

Implement eigen value calculator for symmetric matricies

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

Fixes #209 
- Also changed error message to match that of `cure.core.ufunc`

Fix out argument in fusion ufunc

---

cupy/testing/__init__.py

Remove redundant import

---

cupy_setup_build.py
install/build.py

Fixes #197.
I'm not sure if this is the correct way, but it works.

Handle "no supported host compiler" error of nvcc

---

tests/cupy_tests/random_tests/test_generator.py

[backport] Fix test condition for choice method

---

cupy_setup_build.py
install/build.py

[backport] Handle "no supported host compiler" error of nvcc

---

docker/python2/Dockerfile
docker/python3/Dockerfile
setup.py

Update to v1.0.1

---

tests/cupy_tests/linalg_tests/test_decomposition.py

[backport] Add retry to unit tests of decomposition functions

---

tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
tests/cupy_tests/core_tests/test_ndarray_scatter.py

[backport] Fix Numpy VisibleDeprecationWarning in indexing tests

---

cupy/math/sumprod.py

[backport] Add docstring of cumsum function and add it to the reference

---

tests/cupy_tests/creation_tests/test_from_data.py

[backport] Put the value of copy option of cupy.array appropriately to ndarray.astype

---

cupy/core/core.pyx

[backport] Avoid synchronize in array function

---

cupy/cuda/memory.pyx

[backport] Change allocation_unit_size from 256 to 512

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

[backport] Fix out argument in fusion ufunc

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py

[backport] Fix deepcopy with multiple devices

---

docs/source/tutorial/basic.rst

Fix spelling in tutorial

---

cupy/testing/random.py

This PR is refactoring of `cupy.testing.random` (See https://github.com/cupy/cupy/pull/82), preparing for porting this module to chainer.
In chainer, I'm thinking of calling `cupy.testing.random.do_setup` and `cupy.testing.random.do_teardown` like this:
```
def do_setup(deterministic=True):
if cuda.available:
cuda.cupy.testing.random.do_setup(deterministic)
else:
_numpy_do_setup(deterministic)
def do_teardown():
if cuda.available:
cuda.cupy.testing.random.do_teardown()
else:
_numpy_do_teardown()
:
:
```

Refactor deterministic test

---

docs/source/tutorial/basic.rst

[backport] Fix spelling in tutorial

---

cupy/manipulation/basic.py
tests/cupy_tests/manipulation_tests/test_basic.py

Fixes https://github.com/chainer/chainer/issues/2911

Fix multi-device copyto

---

cupy/manipulation/basic.py
tests/cupy_tests/manipulation_tests/test_basic.py

[backport] Fix multi-device copyto

---

cupy/testing/__init__.py
cupy/testing/condition.py
cupy/testing/helper.py
cupy/testing/random.py
tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/linalg_tests/test_decomposition.py
tests/cupy_tests/random_tests/test_generator.py
tests/cupy_tests/random_tests/test_sample.py

[backport] Deterministic test

---

.pep8
.travis.yml

Fix travis test to enable style check for normal Python code

---

examples/gemm/sgemm.py

I fixed gemm example to use absolute path.

Use absolute path in gemm example

---

examples/gemm/sgemm.py

The code broke after https://github.com/cupy/cupy/pull/108

Make grid size to integer for GEMM example

---

.coveragerc

[backport] Add include option for covreage

---

cupy/core/core.pyx
cupy/core/elementwise.pxi
cupy/core/reduction.pxi
cupy/cuda/device.pyx
cupy/cuda/memory.pyx
cupy/cuda/pinned_memory.pyx

Remove `six` in Cython code for performance up.

Remove six in Cython code

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h
cupy/cudnn.py

This PR removes old cuDNN support (v2 and v3).
Please merge chainer/chainer#2920 before this PR.

Remove old cuDNN support

---

cupy/cuda/cupy_cuda.h
cupy/cuda/nvtx.pyx

I implemented RangeStart and RangeEnd that shows range in nvvp.
See https://github.com/chainer/chainer/pull/2496

Implemented RangeStart and RangeEnd

---

cupy/sparse/base.py

Fix toarray in spmatrix

---

cupy_setup_build.py

link_args is required to use cusolver.

Fix link args for cusolver

---

cupy/cusparse.py
cupy/sparse/__init__.py
cupy/sparse/coo.py
tests/cupy_tests/sparse_tests/test_coo.py

I implemented COO matrix.
Please merge #226 first.
related to #36

COO matrix

---

cupy/cusparse.py
cupy/sparse/__init__.py
cupy/sparse/coo.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_coo.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented csr2coo method.
Merge #234 first
related to #36

Conversion method from compressed matrix (csr, csc) to coordinate format (coo)

---

.gitignore

I fixed gitignore to ignore generated document.

Ignore generated reference

---

.gitignore

[backport] Ignore generated reference

---

cupy/__init__.py
cupy/linalg/product.py
docs/source/reference/linalg.rst
tests/cupy_tests/linalg_tests/test_product.py

I implemented cupy.kron which calculates kronecker product.

Implement kron

---

cupy/linalg/__init__.py
cupy/linalg/norms.py
docs/source/reference/linalg.rst
tests/cupy_tests/linalg_tests/test_norms.py

I implemented `det` which calculates determinant.
It uses `slogdet`. Merge #95 first.

Determinant

---

cupy_setup_build.py

This PR is a backport of #292 .

[backport] Fix link args for cusolver

---

docs/source/reference/difference.rst

Fix #144 causing doc-test failure on jenkins.

Fix difference of reduction functions

---

cupy/sparse/compressed.py
cupy/sparse/csc.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented copy method and copy initializer of csr and csc matrix.

CSR and CSC copy

---

cupy/cusparse.py
cupy/sparse/compressed.py
cupy/sparse/csc.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented add and sub methods.
Merge #236 first

__add__, __radd__, __sub__ and __rsub__ for CSR and CSC

---

.gitignore

Add tags file to .gitignore

---

.gitignore

[backport] Add tags file to .gitignore

---

docs/source/reference/difference.rst

[backport] Fix difference of reduction functions

---

docs/source/conf.py

Fix https://github.com/cupy/cupy/issues/331.

Fix GitHub link

---

docs/source/conf.py

[backport] Fix GitHub link

---

README.md
docs/source/install.rst

Fix document about numpy version

---

cupy/cuda/compiler.py
docs/source/reference/environment.rst

Dump CUDA source on compilation error

---

cupy/core/core.pyx
cupy/manipulation/join.py
cupy/manipulation/rearrange.py
cupy/math/sumprod.py
cupy/statistics/histogram.py
tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_unary_op.py
tests/cupy_tests/manipulation_tests/test_dims.py
tests/cupy_tests/manipulation_tests/test_join.py
tests/cupy_tests/manipulation_tests/test_rearrange.py
tests/cupy_tests/math_tests/test_sumprod.py
tests/cupy_tests/statics_tests/test_histogram.py

Reverts cupy/cupy#281
Workaround for https://github.com/cupy/cupy/issues/342

Revert "Support NumPy 1.13"

---

docker/python2/Dockerfile
docker/python3/Dockerfile
setup.py

Update to v1.0.2

---

cupy/cusparse.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented __mul__ operator for CSR matrix.
merge #238 first
related to #36

__mul__ method for CSR

---

cupy/cusparse.py
cupy/sparse/base.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented rmul method for sparse matrixes.
Merge #239 first.
related to #36

__rmul__ for sparse matrixes

---

cupy/cuda/cublas.pyx
cupy/cuda/cudnn.pyx
cupy/cuda/curand.pyx
cupy/cuda/cusolver.pyx
cupy/cuda/driver.pyx
cupy/cuda/nvtx.pyx
cupy/cuda/profiler.pyx
cupy/cuda/runtime.pyx

`cdef extern` receives additional configuration.

Simplify nogil

---

cupy/sparse/base.py

I found many mistakes in spmatrix. These implementations are not used from other sub-classes yet.

Fix default behavior of methods in spmatrix

---

cupy/core/core.pyx

Remove unsupported `strides` argument from docstring

Remove unsupported strides argument from docstring

---

cupy/cuda/cupy_thrust.cu

This PR fixes double declaration problem.

Remove tuple_less

---

cupy/sparse/csr.py

I fixed csr_matrix to raise an error on methods which are not implemented. Because spmatrix uses `to_csr` method, it causes infinite loop without this patch.

Made dummy implementation to prevent infinite loop

---

cupy/sparse/base.py

I updated docstrings of some methods in spmatrix.

Fix docstring of spmatrix

---

setup.cfg

Ref: https://github.com/chainer/chainer/pull/3077

Configure flake8 to ignore the .git directory

---

cupy/cuda/cublas.pxd
cupy/cuda/cublas.pyx
cupy/cuda/cupy_cuda.h
cupy/linalg/__init__.py
cupy/linalg/decomposition.py
cupy/linalg/norms.py
cupy/linalg/solve.py
cupy/linalg/util.py
docs/source/reference/linalg.rst
tests/cupy_tests/linalg_tests/test_solve.py

This PR implements ``cupy.linalg.solve`` to cupy.

Implements a solver of a linear matrix equation

---

cupy/sparse/csc.py
tests/cupy_tests/sparse_tests/test_csc.py

I wrote test for `csc_matrix.dot`.
related to #36

Write test for csc_matrix.dot

---

cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_csr.py

`dot` method is already supported. I added tests for the method.
related to #36

csr_matrix.dot method

---

cupy/sparse/__init__.py
cupy/sparse/construct.py
tests/cupy_tests/sparse_tests/test_construct.py

I implemented `identity` and `eye` to create identity matrix.
related to #36

Implement identity

---

setup.cfg

[backport] Configure flake8 to ignore the .git directory

---

cupy/core/core.pyx

[backport] Remove unsupported strides argument from docstring

---

docs/source/conf.py

[backport] Hide source link for alien objects

---

cupy/sparse/compressed.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented __getitem__ method for single element.
related to #36

Implement csr_matrix.__getitem__ for single element

---

cupy/sparse/base.py
cupy/sparse/util.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented `__pow__` method. It uses `identity`.
check #358 first
related to #36

Implement __pow__

---

cupy/linalg/__init__.py
cupy/linalg/solve.py
docs/source/reference/linalg.rst
tests/cupy_tests/linalg_tests/test_solve.py

Merge after #207.
This PR implements ``cupy.linalg.tensorsolve`` to cupy.

Implements cupy.linalg.tensorsolve

---

cupy/sparse/__init__.py
cupy/sparse/dia.py
tests/cupy_tests/sparse_tests/test_dia.py

I implemented dia_matrix, that is diagonal format. dia_matrix is required for some creation methods such as `eye` and `diags`.
related to #36

Implement dia_matrix

---

cupy/sparse/dia.py
tests/cupy_tests/sparse_tests/test_dia.py

I implemented nnz for dia_matrix.
Merge #313 first.
relate to #36

nnz for dia_matrix

---

cupy/cuda/compiler.py

In `cupy/cuda/compiler.py`
* Remove unnecessary condition, replacing with `assert`.
* Make `preprocess` private by prefixing with `_`.
(No need to backport)

Remove unnecessary condition

---

cupy/sparse/coo.py
cupy/sparse/util.py
tests/cupy_tests/sparse_tests/test_coo.py

It supports initializer with shape for coo_matrix.
merge #328 first
related to #36

Coo shape init

---

cupy/core/__init__.py
cupy/core/core.pyx
cupy/manipulation/join.py
cupy/manipulation/rearrange.py
cupy/math/sumprod.py
cupy/statistics/histogram.py
docs/source/install.rst
tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_unary_op.py
tests/cupy_tests/manipulation_tests/test_dims.py
tests/cupy_tests/manipulation_tests/test_join.py
tests/cupy_tests/manipulation_tests/test_rearrange.py
tests/cupy_tests/math_tests/test_sumprod.py
tests/cupy_tests/statics_tests/test_histogram.py

This PR includes #281, #336 and #344,
This PR fixes #342.

Support NumPy 1.13 again

---

.github/CONTRIBUTING.md

We already have the contribution guide.

Add link ot our contribution guide

---

cupy/core/reduction.pxi

Add semicolons to the reduction kernel template

Add semicolons to the reduction kernel template

---

tests/cupy_tests/manipulation_tests/test_dims.py

[Backport] Fix typo

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h
cupy/cudnn.py
install/build.py

This PR is for supporting cuDNN7.
There are some API addition and changes in cuDNN7 from cuDNN6. This PR enables you to use new or modified APIs of cuDNN7.

cuDNN7 support

---

cupy/__init__.py
cupy/core/core.pyx
cupy/sorting/sort.py
docs/source/reference/sorting.rst
tests/cupy_tests/sorting_tests/test_sort.py

Merge #229 first.
This PR implements `cupy.partition` to fix #162 .

Implement cupy.partition

---

tests/cupy_tests/sparse_tests/test_coo.py

I wrote test for operators of `coo_matrix`. It uses implementation in its base class `spmatrix`.
relate to #36

Write test for operators

---

examples/gemm/sgemm.py
examples/gmm/gmm.py
examples/kmeans/kmeans.py
tests/example_tests/example_test.py
tests/example_tests/test_gemm.py
tests/example_tests/test_gmm.py
tests/example_tests/test_kmeans.py

I made example test in cupy repository instead of chainer-test. This PR includes some small fixes in the examples.
Check discussion on https://github.com/chainer/chainer-test/pull/276

Example test

---

cupy/core/core.pyx
cupy/manipulation/join.py
cupy/manipulation/rearrange.py
cupy/math/sumprod.py
cupy/statistics/histogram.py
docs/source/install.rst
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_unary_op.py
tests/cupy_tests/manipulation_tests/test_dims.py
tests/cupy_tests/manipulation_tests/test_join.py
tests/cupy_tests/manipulation_tests/test_rearrange.py
tests/cupy_tests/math_tests/test_sumprod.py
tests/cupy_tests/statics_tests/test_histogram.py

[backport] Support NumPy 1.13

---

cupy/sparse/base.py
tests/cupy_tests/sparse_tests/test_coo.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py
tests/cupy_tests/sparse_tests/test_dia.py

I fixed docstring of property `A` and wrote its test.

Write docstring of A property and its test

---

cupy/binary/packing.py
cupy/random/distributions.py
examples/kmeans/kmeans.py

`cupy.ElementwiseKernel` creates instance at each call.
This code caches the object.

Fix usage about ElementwiseKernel

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

Fix view when the itemsize of the dtype changes

---

cupy/cuda/cupy_cusparse.h
cupy/cuda/cusparse.pxd
cupy/cuda/cusparse.pyx
cupy/cusparse.py
cupy/sparse/compressed.py
cupy/sparse/csc.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented dense2csr and dense2csc conversion.
related to #36

Dense2compress

---

cupy/testing/helper.py
install/build.py

We need to use two backslashes in str literals..

Use double backslash in str literal

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

[backport] fix view when the itemsize of the dtype changes

---

tests/cupy_tests/testing_tests/test_array.py

`random_integer` is deprecated. I replaced it with `randint`.

Use randint instead of random_integer that is deprecated

---

cupy/linalg/einsum.py

I updated docstring of `einsum`.

Update docstring of einsum

---

cupy/testing/helper.py
install/build.py

[backport] Use double backslash in str literal

---

cupy/core/reduction.pxi

[backport] Add semicolons to the reduction kernel template

---

cupy/testing/__init__.py
cupy/testing/helper.py
tests/cupy_tests/cuda_tests/test_memory.py

I copied `assert_warns` from Chainer and use it to suppress deprecation warning.

Assert warns

---

tests/example_tests/test_gmm.py
tests/example_tests/test_kmeans.py

We need to use `six.assertRegex`

Use six.assertRegex

---

docs/source/conf.py

See: https://github.com/chainer/chainer/pull/3080

Remove "Edit on GitHub" link

---

cupy/testing/__init__.py
cupy/testing/helper.py
tests/cupy_tests/cuda_tests/test_memory.py

[backport] Assert warns

---

cupy/core/core.pyx
tests/cupy_tests/indexing_tests/test_indexing.py

Fix diagonal

---

cupy/sparse/construct.py
tests/cupy_tests/sparse_tests/test_construct.py

I updated eye function to support all arguments using `spdiags`.
merge #388 first

Improve eye

---

tests/cupy_tests/sparse_tests/test_coo.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

Add test for asfptype

---

cupy/core/core.pyx
tests/cupy_tests/indexing_tests/test_indexing.py

[backport] Fix diagonal

---

cupy/testing/random.py
tests/cupy_tests/random_tests/test_generator.py

Some tests are failed by dtype problem on Windows

Fix test for generator

---

tests/example_tests/example_test.py

This patch shows error messages which example program shows on example tests.

Show error message when an error occurs on example test

---

cupy/core/core.pyx

[backport] Fix matmul document

---

examples/cg/cg.py

Conjugate Gradient

---

cupy/sparse/util.py
tests/cupy_tests/sparse_tests/test_csr.py

I improved unit test for `__pow__` to cover all error cases, and found a bug.

Improved pow test

---

cupy/sparse/csc.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_coo.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py
tests/cupy_tests/sparse_tests/test_dia.py

I implemented copy argument of array conversion methods. I also wrote unit tests for this option.

Implemented copy option of array conversion methods and wrote tests

---

cupy/core/elementwise.pxi
cupy/core/reduction.pxi

[backport] Clear doctest warnings

---

tests/cupy_tests/sparse_tests/test_dia.py

Fix dia test

---

cupy/linalg/__init__.py
cupy/linalg/solve.py
docs/source/reference/linalg.rst
tests/cupy_tests/linalg_tests/test_solve.py

This PR implements `cupy.linalg.inv`.

Implement cupy.linalg.inv

---

docs/source/contribution.rst
docs/source/developers.rst
docs/source/index.rst
docs/source/overview.rst
docs/source/reference/index.rst
docs/source/tutorial/index.rst

* Added group captions
* Brought "Overview", "Tutorial" and "Reference" to top, which are the most important for users
* Removed "CuPy" prefix
* fixed #385 ?
**old**
**new**
TODO: Port to Chainer

doc: Sort out navigation menu

---

docs/source/contribution.rst
docs/source/developers.rst
docs/source/index.rst
docs/source/overview.rst
docs/source/reference/index.rst
docs/source/tutorial/index.rst

[backport] doc: Sort out navigation menu

---

docs/source/tutorial/basic.rst

Fix a grammatical error in tutorial

Fix a grammatical error in tutorial

---

docs/source/conf.py
docs/source/reference/index.rst
docs/source/reference/sparse.rst

I made a reference page of cupy.sparse.
relate to #36

cupy.sparse reference

---

cupy_setup_build.py
setup.py

We need to use Cython before making sdist. I customized `sdist` command to call `cythonize`. `Command.sub_commands` are called before its `run` method.

Made a cutomized version of sdist command to use cython

---

cupy/core/core.pyx

This PR reduces kernel call and improves `tensordot_core` speed.

Improve tensordot_core

---

docs/source/tutorial/basic.rst

[backport] Fix a grammatical error in tutorial

---

tests/cupy_tests/math_tests/test_arithmetic.py

[backport] Fix tolerance

---

cupy/math/sumprod.py
tests/cupy_tests/math_tests/test_sumprod.py

Please merge #390 before this PR.
This PR fixes `test_cumprod_huge_array`.

Fix cumsum

---

cupy/testing/random.py
tests/cupy_tests/random_tests/test_generator.py

[backport] Fix test for generator 

---

cupy/manipulation/rearrange.py

This PR improves performance of fliplr and flipud.

Simplify flip function

---

cupy/sparse/base.py

I wrote docstring of `issparse`.

Write docstring of issparse

---

cupy/random/generator.py
cupy/random/sample.py
tests/cupy_tests/random_tests/test_generator.py

I made a naive implementation of choice with `replace=False` and without `p`.

Choice replace false

---

cupy/cuda/__init__.py

Reverts cupy/cupy#483
It looks like this PR is causing import error.

Revert "import memory_hooks"

---

tests/cupy_tests/math_tests/test_misc.py

Numpy.clip at dtype 'bool' is different from ubuntu and Windows.

Numpy clip dtype

---

cupy/testing/__init__.py
cupy/testing/helper.py
tests/cupy_tests/io_tests/test_base_n.py
tests/cupy_tests/logic_tests/test_type_test.py

Related: #355 
Tests for NumPy functions.

Tests for NumPy alias functions

---

cupy/random/__init__.py
cupy/sparse/coo.py
cupy/sparse/csc.py
cupy/sparse/csr.py
cupy/sparse/dia.py

Clear doctest warnings

---

cupy/core/core.pyx
cupy/sorting/search.py
tests/cupy_tests/sorting_tests/test_search.py

Fix bug of nonzero

---

cupy/cuda/__init__.py
setup.py

Reopen #483. We need this to merge #442.

import memory_hooks

---

cupy/core/core.pyx
cupy/sorting/search.py
tests/cupy_tests/sorting_tests/test_search.py

[backport] Fix bug of nonzero

---

cupy/core/reduction.pxi
cupy/logic/truth.py
tests/cupy_tests/logic_tests/test_truth.py
tests/cupy_tests/sorting_tests/test_search.py

[backport] Fix simple reduction

---

cupy/cuda/__init__.py
setup.py

This PR is a backport of #502.

[backport] import memory_hooks

---

tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
tests/cupy_tests/linalg_tests/test_eigenvalue.py

Remove print() in tests

---

cupy/cuda/pinned_memory.pxd
cupy/cuda/pinned_memory.pyx

Resolve dealloc problem and multi thread problem in PinnedMemory

---

cupy/cuda/memory.pyx

backport of https://github.com/cupy/cupy/pull/480

[backport] Fix multi thread problem in PooledMemory

---

cupy/cuda/pinned_memory.pxd
cupy/cuda/pinned_memory.pyx

backport of https://github.com/cupy/cupy/pull/481

[backport] Resolve dealloc problem and multi thread problem in PinnedMemory

---

cupy/logic/truth.py

Add documents of cupy.all and cupy.any function

---

tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
tests/cupy_tests/linalg_tests/test_eigenvalue.py

[backport] Remove print() in tests

---

cupy/core/fusion.py

Some document of function are blank. Please see [this](https://docs-cupy.chainer.org/en/v2/reference/generated/cupy.copy.html)
This PR fixes this problem.

Fix document about fusion functions

---

cupy/core/elementwise.pxi

[backport] Avoid duplicate loop index

---

cupy/cuda/device.pyx
cupy/cudnn.py

This PR adds a method to check if Tensor-Core is available.

Tensor-Core support (cuDNN)

---

cupy/logic/truth.py

[backport] Add documents of cupy.all and cupy.any function

---

cupy/core/fusion.py

[backport] Fix document about fusion functions

---

docs/Makefile

[backport] Treat sphinx warnings as errors

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx

This PR adds some memorable things.

Refactoring cupy/cuda/cudnn

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

Please merge #475 before this PR.
This PR improves malloc performance.

Use vector to improve free memory searching in malloc

---

cupy/core/core.pyx
cupy/core/elementwise.pxi
cupy/cuda/memory.pyx

I fixed docstrings to suppress warnings.

Fix document to suppress warning errors

---

cupy_setup_build.py
docs/source/contribution.rst
docs/source/install.rst
docs/source/reference/environment.rst
install/build.py

[backport] Support NVCC environment variable

---

cupy/core/core.pyx
cupy/core/elementwise.pxi
cupy/cuda/memory.pyx

[backport] Fix document to suppress warning errors

---

cupy/cuda/nvrtc.pyx

[backport] Show NVRTC error code

---

docs/requirements.txt

Fix docs requirement

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

We need to use `RandomState` in `choice` method.

Use RandomState in choice

---

tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

This PR is just to add some test cases (and TODOs that are failing for now).
Some cases are related to #503.

Add test cases for adv-indexing zero-dim and zero-sized arrays

---

cupy/core/core.pyx
tests/cupy_tests/manipulation_tests/test_dims.py

Fix broadcast

---

cupy/random/generator.py

* Reduce the iterations by resampling only unfinished elements.
* Avoid unnecessary allocation of the return array when the sampling is finished in only one iteration.
Performance measurement of `cupy.random.randint` for some `high`s:
```
[before this PR]
0x1                :    50.884 us   +/-  0.926 us
0x2                :   329.517 us   +/- 23.467 us
0x3                :  1660.352 us   +/-199.703 us
0x4                :   331.984 us   +/- 10.940 us
0x0f               :   988.530 us   +/-234.087 us
0x10               :   332.519 us   +/-  9.331 us
0x11               :  2931.345 us   +/-363.038 us
0x0ffffff          :   335.284 us   +/- 12.876 us
0x1000000          :   332.018 us   +/-  8.070 us
0x1000001          :  3182.727 us   +/-396.831 us
[this PR]
0x1                :    50.621 us …
```

Optimize RandomState.interval

---

docs/source/install.rst

[backport] Fix wrong urls in document

---

cupy/__init__.py
tests/cupy_tests/test_numpy_interop.py

Fix get_array_module to be aware of spmatrix

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

[backport] Use RandomState in choice

---

cupy/random/distributions.py

Fix random.normal double memory consumption

---

cupy/random/distributions.py

[backport] Fix random.normal double memory consumption

---

cupy/core/elementwise.pxi
cupy/core/reduction.pxi
cupy/cuda/compiler.py
tests/cupy_tests/core_tests/test_elementwise.py
tests/cupy_tests/core_tests/test_reduction.py
tests/cupy_tests/cuda_tests/test_compiler.py

Check kernel name when a kernel is made

---

cupy/core/elementwise.pxi
cupy/core/reduction.pxi
cupy/cuda/compiler.py
tests/cupy_tests/core_tests/test_elementwise.py
tests/cupy_tests/core_tests/test_reduction.py
tests/cupy_tests/cuda_tests/test_compiler.py

[backport] Check kernel name when a kernel is made

---

cupy/random/generator.py

[backport] Optimize RandomState.interval

---

cupy/__init__.py
tests/cupy_tests/test_numpy_interop.py

[backport] Fix get_array_module to be aware of spmatrix

---

tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

[backport] Add test cases for adv-indexing zero-dim and zero-sized arrays

---

cupy/cusparse.py
tests/cupy_tests/test_cusparse.py

I wrote a unit test for csrgemm.

Test csrgemm

---

cupy/cusparse.py
tests/cupy_tests/test_cusparse.py

[backport] Fix csrmm2 to support transa

---

cupy/manipulation/dims.py
tests/cupy_tests/manipulation_tests/test_dims.py

Fixed #544 
Please merge #543 first.

Fix broadcast_arrays return type

---

cupy/cusparse.py
tests/cupy_tests/test_cusparse.py

[backport] Fix csrmv

---

cupy_setup_build.py

[backport] Avoid Cython 0.27.0

---

tests/cupy_tests/random_tests/test_sample.py

[backport] Use mock.patch instead of directly replacing function with Mock

---

cupy/__init__.py
cupy/math/window.py
docs/source/reference/math.rst
tests/cupy_tests/math_tests/test_window.py

This PR adds `cupy.blackman`, `cupy.hamming` and `cupy.hanning`, each of which is compatible with numpy's.

Add window functions

---

cupy/core/core.pyx
tests/cupy_tests/manipulation_tests/test_dims.py

[backport] Fix broadcast

---

docs/requirements.txt

[backport] Fix docs requirement

---

cupy/testing/helper.py

Fix helper doc

---

cupy/sparse/__init__.py
cupy/sparse/construct.py
tests/cupy_tests/sparse_tests/test_construct.py

I implemented `cupy.sparse.random`. 
Review #556 first.

Sparse random

---

cupy/core/elementwise.pxi
tests/cupy_tests/core_tests/test_elementwise.py

Fix OverflowError passing large integer to elementwise operation

---

docs/source/install.rst

[backport] Fix supported CUDA and cuDNN version

---

docs/source/install.rst

Related: https://github.com/cupy/cupy/issues/599

Put warning about conda in install guide

---

docs/source/install.rst

[backport]Put warning about conda in install guide

---

docker/python2/Dockerfile
docker/python3/Dockerfile
setup.py

Update setup.py and Docker files to v3.0.0a1.

Update to v3.0.0a1

---

cupy/sparse/csc.py

csc matrix is transposed version of csr matrix. So, we can optimize csc_matrix.__mul__ with transa argument.

Optimize csc mul

---

README.md

[backport] fix link for developers

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx

[backport] Refactoring cupy/cuda/cudnn

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

I implemented `RandomState.tomaxint`.

Implement tomaxint

---

cupy/testing/helper.py

It does not give any useful information.

Remove unrelated seealso from numpy_cupy_raises

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

[backport] Support uint32 sampling in random.RandomState.interval

---

cupy/__init__.py
cupy/core/core.pyx
cupy/sorting/sort.py
tests/cupy_tests/sorting_tests/test_sort.py

[backport] Implement cupy.argpartition

---

cupy/__init__.py
cupy/math/window.py
docs/source/reference/math.rst
tests/cupy_tests/math_tests/test_window.py

[backport]Add window functions

---

cupy/core/elementwise.pxi
tests/cupy_tests/core_tests/test_elementwise.py

[backport] Fix OverflowError passing large integer to elementwise operation

---

cupy/sparse/csc.py

[backport] Optimize csc mul

---

docs/source/install.rst

I added notice about environment variables used in installation.
See #521

Write note about environment variables

---

docs/source/install.rst

[backport] Write note about environment variables

---

cupy/testing/random.py

Setup random of Python library in testing/random

---

cupy/testing/random.py

[backport] Setup random of Python library in testing/random

---

cupy/testing/attr.py
setup.py
tests/example_tests/test_gemm.py
tests/example_tests/test_gmm.py
tests/example_tests/test_kmeans.py

This is CuPy's counterpart of https://github.com/chainer/chainer/pull/3324
Needs https://github.com/chainer/chainer-test/pull/338

Move to PyTest

---

docs/source/reference/linalg.rst

Fix reference page of linalg

---

cupy/core/core.pyx
cupy/cuda/function.pyx
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

[backport] Fix indexing 0-dim array with boolean mask

---

docs/source/reference/linalg.rst

[backport] Fix reference page of linalg

---

cupy/testing/attr.py
setup.py
tests/example_tests/test_gemm.py
tests/example_tests/test_gmm.py
tests/example_tests/test_kmeans.py

Backport for pull request #623 from niboshi/pytest-cupy

[backport] Move to PyTest

---

cupy/cuda/cudnn.pyx

Current find API interface is a little bit strange.

Fix find API interface

---

cupy/cuda/cudnn.pyx

This PR relates to #624.
Current implementation returns extra data.

Fix find API to improve behavior

---

docs/source/tutorial/basic.rst

[backport] fix document typo and broken heading

---

docs/source/conf.py

[backport] add missing chainer interreference

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h
cupy/cudnn.py

[backport] Use v6 RNN API with cuDNN7

---

setup.py
tests/cupy_tests/test_init.py
tests/install_tests/test_build.py

CuPy version of https://github.com/chainer/chainer/pull/3623

remove nose dependency in tests

---

docs/source/license.rst

[backport]fix typo in license page

---

setup.py
tests/cupy_tests/test_init.py
tests/install_tests/test_build.py

[backport]remove nose dependency in tests

---

cupy/testing/attr.py

Port of Chainer fix in https://github.com/chainer/chainer/pull/3624.

Fix decorators to allow users to filter test cases by number of GPUs

---

cupy/testing/helper.py

[backport] Remove unrelated seealso from numpy_cupy_raises

---

cupy/core/core.pyx

fix IndexError error message

---

cupy/core/core.pyx

Backport of https://github.com/cupy/cupy/pull/681

[backport] fix IndexError error message

---

cupy/testing/attr.py

[backport] Fix decorators to allow users to filter test cases by number of GPUs

---

cupy/__init__.py
cupy/indexing/generate.py
tests/cupy_tests/indexing_tests/test_generate.py

This PR implements `cupy.unravel_index`.

unravel_index

---

cupy/cuda/cupy_cuda.h
cupy/cuda/driver.pxd
cupy/cuda/driver.pyx
cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

[backport] Fix multi-threaded application fail when memory pool is enabled

---

cupy/indexing/generate.py
cupy/indexing/insert.py

This PR fixes some coding and documentation styles.

Fix some styles

---

cupy/indexing/generate.py
cupy/indexing/insert.py

[backport] Fix some styles

---

cupy/random/sample.py
tests/cupy_tests/random_tests/test_sample.py

[backport] Support dtype argument in random.randint

---

tests/cupy_tests/core_tests/test_fusion.py

[backport]Fix test about bool and complex

---

cupy/manipulation/dims.py
cupy/manipulation/join.py
cupy/testing/helper.py
setup.cfg
tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
tests/cupy_tests/io_tests/test_base_n.py
tests/cupy_tests/manipulation_tests/test_dims.py
tests/cupy_tests/math_tests/test_arithmetic.py

I added configuration for pytest-warnings to check DeprecationWarnings

Use pytest-warnings to check deprecated warnings

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

Fix https://github.com/cupy/cupy/issues/705

Fix adv indexing to not alter indices

---

tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/sorting_tests/test_search.py

[backport] Fix where tests

---

cupy/manipulation/dims.py
cupy/manipulation/join.py
setup.cfg
tests/cupy_tests/core_tests/test_fusion.py
tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
tests/cupy_tests/manipulation_tests/test_dims.py
tests/cupy_tests/math_tests/test_arithmetic.py

[WIP] Use pytest-warnings to check deprecated warnings

---

cupy/__init__.py
cupy/statistics/order.py
tests/cupy_tests/statics_tests/test_order.py

Implemented percentile for CuPy. 
See https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.percentile.html

Implement percentile

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

[backport] Fix adv indexing to not alter indices

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

[backport] Fix RandomState.seed to only accept integer types

---

cupy/core/core.pyx
cupy/statistics/meanvar.py
tests/cupy_tests/statics_tests/test_meanvar.py

[backport] pass ddof from var/std to _var/_std

---

cupy/cuda/cupy_cusparse.h
cupy/cuda/cusparse.pyx
cupy/cusparse.py
cupy/sparse/coo.py
cupy/sparse/csr.py
tests/cupy_tests/sparse_tests/test_coo.py
tests/cupy_tests/sparse_tests/test_csr.py

I implemented `csr_matrix.eliminate_zeros` using `csr2csr_compress`.

Implement csr_matrix.eliminate_zeros

---

cupy/random/__init__.py
cupy/random/generator.py
docs/source/reference/random.rst
tests/cupy_tests/random_tests/test_generator.py

Resolves #387.
Implements a feature requested.

Add random.set_random_state

---

cupy/linalg/__init__.py
cupy/linalg/solve.py
docs/source/reference/linalg.rst
tests/cupy_tests/linalg_tests/test_solve.py

This is a re-submission of #462 (I closed this PR by mistake).
This PR implements `cupy.linalg.tensorinv`.

Implement cupy.linalg.tensorinv

---

README.md

[backport] Fix the broken link to the forum

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h
cupy/cudnn.py

[backport] Grouped convolution

---

docs/source/contribution.rst

[backport]update testing guide of contirbution guide

---

docs/source/install.rst

This PR fixes ~~#638 and~~ #761.

improve dependency description of docs

---

docs/source/install.rst

[backport] improve dependency description of docs

---

docs/source/reference/environment.rst

[backport] fix typo in environment variable reference

---

cupy/core/core.pyx
cupy/indexing/generate.py
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

Make order=None work like default order

---

cupy/random/distributions.py
cupy/random/generator.py
cupy/random/sample.py
tests/cupy_tests/random_tests/test_generator.py

Fixes #738 
I had to refactor unit test, so that reproducibility of generators is checked every time generating method is called.

Fix: RandomState.choice reproducibility

---

tests/cupy_tests/sorting_tests/test_search.py

This adds test case for xhttps://github.com/chainer/chainer/issues/1099.

add test for argmin/argmax tie

---

tests/cupy_tests/sorting_tests/test_search.py

[backport] add test for argmin/argmax tie

---

cupy/cuda/compiler.py

[backport] fix to correctly display filename of CUDA dump

---

cupy/testing/helper.py

Add missing documentation for argument.

Add docs for missing argument

---

cupy/testing/helper.py

[backport] Add docs for missing argument

---

cupy/cudnn.pyx

This PR is to fix a but related to grouped convolution. Please apply this before testing https://github.com/chainer/chainer/pull/3494.

Bug fix about grouped convolution

---

cupy/manipulation/join.py
tests/cupy_tests/manipulation_tests/test_join.py

[backport]Fix stack function bug

---

.gitignore

CuPy counterpart for https://github.com/chainer/chainer/pull/3600

add pytest cache directory to gitignore

---

tests/cupy_tests/manipulation_tests/test_join.py

Refs https://github.com/cupy/cupy/pull/749

fix test to pass with numpy 1.9

---

cupy/core/elementwise.pxi

[backport] fix ElementwiseKernel.__call__ docs

---

cupy/core/elementwise.pxi
cupy/core/reduction.pxi
cupy_setup_build.py

[backport] Expose signatures to Reference

---

cupy/core/core.pyx
cupy/core/elementwise.pxi
cupy/core/fusion.py

This PR reduces Python function call.

Add default casting option to ufunc

---

cupy/testing/helper.py
tests/cupy_tests/testing_tests/test_helper.py

[backport] Allow derived errors to pass equality tests

---

cupy/core/core.pyx
cupy/core/elementwise.pxi
cupy/core/fusion.py

[backport] Add default casting option to ufunc

---

cupy/core/core.pyx
tests/cupy_tests/math_tests/test_matmul.py

Fix matmul to raise ValueError on invalid shapes

---

cupy/testing/helper.py

[backport] fix wrong comment in test helper

---

tests/cupy_tests/math_tests/test_matmul.py

[backport] Fix matmul test for old NumPy

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

Cast CUPY_SEED environment variable to uint64

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

[backport] Cast CUPY_SEED environment variable to uint64

---

cupy/testing/random.py
tests/cupy_tests/random_tests/test_generator.py

[backport]Remove dtype option which is introduced in v1.11

---

cupy/random/distributions.py
cupy/random/generator.py
cupy/random/sample.py
tests/cupy_tests/random_tests/test_generator.py

[backport] Fix: RandomState.choice reproducibility

---

cupy/testing/parameterized.py

Copying `testing/parameterized.py` from Chainer
https://github.com/chainer/chainer/blob/06595e8863b558e4ba9a29fdb44f2ccf678c87ea/chainer/testing/parameterized.py

Import testing/parameterized.py from Chainer

---

cupy/testing/parameterized.py

[backport] Import testing/parameterized.py from Chainer

---

examples/finance/monte_carlo_multigpu.py
tests/example_tests/test_finance.py

Merge #473 and #493 first.
This PR add an example that computes the price of call options using Monte-Carlo simulation and multiple GPUs.

Add an example of option pricing with multiple GPUs

---

cupy/core/core.pyx
tests/cupy_tests/manipulation_tests/test_tiling.py

[backport]Fix repeat behave differently with numpy

---

cupy/cuda/driver.pyx
tests/cupy_tests/cuda_tests/test_driver.py

[backport] fix ctxGetCurrent not returning context ptr

---

cupy/linalg/decomposition.py
tests/cupy_tests/linalg_tests/test_decomposition.py

[backport] Make a copy when SVD is calculated

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

[backport] Make order=None work like default order

---

cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_driver.py
tests/cupy_tests/cuda_tests/test_memory.py

[backport] Fix memory pool to correctly detect that memory pool is not established

---

tests/cupy_tests/manipulation_tests/test_join.py

[backport] Remove unnecessary try catch

---

cupy/sparse/coo.py
tests/cupy_tests/sparse_tests/test_coo.py

[backport] Implement coo initializer for scipy sparse matrix

---

cupy/manipulation/dims.py
tests/cupy_tests/manipulation_tests/test_dims.py

This patch supports scalar values in atleast_nd.

Support scalar values in atleast_nd

---

cupy/sparse/__init__.py
cupy/sparse/construct.py
tests/cupy_tests/sparse_tests/test_construct.py

I implemented `rand` using `random`.

Implement rand

---

cupy/sparse/csc.py
tests/cupy_tests/sparse_tests/test_csc.py

I implemented `csc_matrix.eliminate_zeros`.

Implement eliminate_zeros for csc matrix

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_complex_ops.py

Implement conversion to complex scalar

---

cupy/linalg/norms.py
tests/cupy_tests/linalg_tests/test_norms.py

Fix return type of linalg.norm for complex input

---

cupy/core/core.pxd
cupy/core/core.pyx
cupy/math/misc.py
tests/cupy_tests/math_tests/test_misc.py

[backport] Support None as an argument for clip method

---

README.md

[backport] Add reference

---

cupy/core/include/cupy/carray.cuh

[backport] fix downcast of size in CArray and CIndexer

---

cupy/core/fusion.py

[backport] Fix out argument in fusion

---

cupy_setup_build.py

[backport] Change nvcc compiler options for CUDA9

---

cupy/__init__.py

@kmaehashi please let me know what else needs to be done. (1st PR into cupy, still getting familiar with codebase.)
Addresses #905.

Import numpy complex dtypes into cupy namespace.

---

cupy/__init__.py
cupy/logic/type_test.py
docs/source/reference/logic.rst
tests/cupy_tests/logic_tests/test_type_test.py

Add logic type tests

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

`stream_ptr` interface is only used by internal function.

Simplify free_all_blocks interface

---

cupy/random/sample.py

[backport] Improve the document of rand/randn with examples

---

MANIFEST.in
cupy_setup_build.py

[backport] exclude Cython files from sdist

---

cupy/core/include/cupy/carray.cuh
tests/cupy_tests/core_tests/test_carray.py

[backport] fix array iteration index overflow

---

cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cuda.h
cupy/cuda/cupy_cudnn.h
cupy/cuda/cupy_nccl.h
cupy/cuda/driver.pyx
cupy/cuda/nccl.pyx

These values are useful for diagnosis or user support.

Embed build-time version of CUDA/cuDNN

---

cupy/cuda/nvtx.pyx

I am assuming this is a typo, please correct me if wrong

nestead -> nested

---

cupy/cuda/nvtx.pyx

[backport] nestead -> nested

---

cupy/core/core.pyx
cupy/core/elementwise.pxi
tests/cupy_tests/math_tests/test_arithmetic.py

[backport]Fix scalar broadcast

---

cupy/linalg/decomposition.py
cupy/linalg/solve.py
examples/cg/cg.py
examples/gmm/gmm.py

According to PEP 257, always use """triple double quotes""" around docstrings.

Prefer double quoted docstring to single quoted docstring

---

docs/source/reference/difference.rst
docs/source/tutorial/kernel.rst

Refs https://github.com/chainer/chainer/pull/4350

Prefer data type objects over character codes

---

docs/source/reference/difference.rst
docs/source/tutorial/kernel.rst

[backport] Prefer data type objects over character codes

---

cupy/cuda/memory_hooks/line_profile.py
cupy/testing/attr.py

[backport] Simplify chained comparisions

---

cupy/linalg/decomposition.py
cupy/linalg/solve.py
examples/cg/cg.py
examples/gmm/gmm.py

[backport] Prefer double quoted docstring to single quoted docstring

---

cupy/cuda/function.pyx
cupy/cuda/memory.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx
tests/cupy_tests/cuda_tests/test_memory.py

Fix multithread bug with CUDA driver API

---

cupy/core/include/cupy/carray.cuh

CuPy will use `__half_raw` and `half` in CUDA9 mainly.
But, if we use `half` directly, compiler outputs lots of errors. Thus, I use `float16` class.

Simplify fp16 code in carray.cuh

---

cupy/cuda/function.pyx
cupy/cuda/memory.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx
tests/cupy_tests/cuda_tests/test_memory.py

[backport] Fix multithread bug with CUDA driver API

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

Fix overflow in indices when indexing

---

cupy/cuda/cufft.pyx

I add `with nogil` in `cufft.pyx`.
fix #945

Use nogil in FFT

---

cupy/core/core.pyx

Use default stream in _scatter_op

---

tests/cupy_tests/core_tests/test_carray.py
tests/cupy_tests/core_tests/test_core.py
tests/cupy_tests/creation_tests/test_basic.py
tests/cupy_tests/math_tests/test_sumprod.py

The slow test is failed when we use multi process.
I use `free_all_blocks` to fix that issue.

Fix slow test

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

[backport] Fix overflow in indices when indexing

---

cupy/core/core.pyx
tests/cupy_tests/indexing_tests/test_indexing.py

[backport] Fix ndarray.diagonal to accept appropriate argument of axis2

---

cupy/core/core.pyx
cupy/core/internal.pyx
tests/cupy_tests/manipulation_tests/test_join.py

Improve concatenate and other functions

---

codecov.yml

See also https://github.com/chainer/chainer/pull/4402

add Codecov.io configuration

---

codecov.yml

[backport] add Codecov.io configuration

---

cupy/random/permutations.py

Permutation is already implemented at #603

Remove outdated TODO

---

cupy/linalg/solve.py
tests/cupy_tests/linalg_tests/test_solve.py

`solve` supports higher order ndarrays.

Support multi dimensional arrays in solve

---

docs/source/overview.rst

Complex dtypes are already supported.

Add complex dtypes on the overview

---

cupy/__init__.py

Import error message imporovements from https://github.com/cupy/cupy/pull/954

improve error message when import failed

---

cupy/cuda/cudnn.pyx

Fix for https://github.com/chainer/chainer/issues/1960

expose CUDNN_BN_MIN_EPSILON from cudnn.h

---

cupy/__init__.py

[backport] improve error message when import failed

---

docs/source/reference/difference.rst

Feedback from https://github.com/cupy/cupy/issues/409 and https://github.com/cupy/cupy/issues/923.

document more on CuPy/NumPy difference

---

cupy/cudnn.pyx
tests/cupy_tests/test_cudnn.py

This PR provides efficient cuDNN convolution interface.
~Please merge #512 before this PR.~

Implement cuDNN convolution interface

---

docs/source/contribution.rst
docs/source/install.rst

[backport] Prefer pip in documentation

---

cupy/cuda/nvrtc.pyx

[backport] remove trailing NULL from values returned from NVRTC

---

docs/source/reference/difference.rst

[backport] document more on CuPy/NumPy difference

---

README.md
docs/source/conf.py
docs/source/contribution.rst

PR https://github.com/chainer/chainer/pull/4317 may be helpful to review this PR.

Add URL to the directory in the documentation

---

examples/gmm/README.md
examples/gmm/gmm.py
examples/kmeans/README.md
examples/kmeans/kmeans.py
tests/example_tests/test_gmm.py
tests/example_tests/test_kmeans.py

Refs https://github.com/chainer/chainer/pull/3043

Avoid to import matplotlib to set its backend Agg in code like chainer

---

examples/gmm/README.md
examples/gmm/gmm.py
examples/kmeans/README.md
examples/kmeans/kmeans.py
tests/example_tests/test_gmm.py
tests/example_tests/test_kmeans.py

[backport] Avoid to import matplotlib to set its backend Agg in code like chainer

---

docs/source/tutorial/basic.rst

[backport] Update documentation for `chainer.backends.cuda`

---

docker/python2/Dockerfile
docker/python3/Dockerfile

[backport] use --no-cache-dir in Dockerfile

---

cupy/creation/matrix.py
tests/cupy_tests/creation_tests/test_matrix.py

[backport] fix diagflat fail if argument is not cupy.ndarray

---

cupy/core/core.pyx
tests/cupy_tests/manipulation_tests/test_transpose.py

[backport] Fix moveaxis bug

---

cupy/__init__.py
cupy/statistics/histogram.py
tests/cupy_tests/statics_tests/test_histogram.py

This PR implements histogram method. It only supports int and ndarray as `bins` argument.
I took over #298

Implement histogram

---

cupy/statistics/histogram.py

I just implemented the minimum function of histogram calculation for GPU.
I'd also like to determine the interface and write tests if required.

[WIP] Implement histogram calculation

---

cupy/testing/helper.py

[backport] Fix document of for_unsigned_dtypes

---

cupy_setup_build.py

Currently we are embedding CUDA_PATH (`/usr/local/cuda`), which is the CUDA installation path of the environment that builds wheel, to `DT_RPATH` of CuPy shared libraries.
(In addition, in Python 3.x, the same value is also appended to `DT_RUNPATH`).
This is inappropriate because `/usr/local/cuda` may point to the different version of CUDA in users’ environment. 
As `DT_RPATH` cannot be overridden by users using Python 2, so we should avoid embedding it to wheels.
I added `--cupy-no-rpath` option to the installer.
This option is intended to be used by cupy-release-tools.

Avoid embedding CUDA_PATH to RPATH in wheels

---

cupy_setup_build.py

[backport] Avoid embedding CUDA_PATH to RPATH in wheels

---

tests/cupy_tests/linalg_tests/test_einsum.py

[backport] remove platform-dependent dtype

---

cupy/linalg/product.py

[backport] remove invalid argument description in cupy.tensordot

---

cupy/cuda/cusolver.pxd

[backport] fix duplicate declaration of EigMode in cuSPARSE

---

cupy/cuda/pinned_memory.pyx
cupy/indexing/generate.py
cupy/math/rounding.py
cupy/math/sumprod.py
cupy/prof/time_range.py
cupy/random/distributions.py
cupy/random/generator.py
cupy/sparse/base.py
cupy/sparse/coo.py
cupy/sparse/csc.py
cupy/sparse/csr.py
cupy/sparse/linalg/solve.py
cupyx/scatter.py
docs/source/reference/cuda.rst
docs/source/reference/fft.rst
docs/source/reference/sorting.rst

[backport] Fix wrong references of document

---

cupy/cuda/compiler.py
tests/cupy_tests/cuda_tests/test_compiler.py

[backport] limit arch to the maximum value allowed in each NVRTC version

---

cupy/__init__.py
cupy/core/carray.pxi
cupy/cuda/__init__.py
cupyx/__init__.py
cupyx/runtime.py
tests/cupy_tests/test_init.py
tests/cupyx_tests/test_runtime.py

[backport] Implement cupy.show_config and cupyx.get_runtime_info

---

cupy/core/carray.pxi
cupy/core/include/cupy/atomics.cuh
cupy/sparse/compressed.py
cupy/sparse/coo.py
cupy/sparse/util.py
setup.py

[backport] Support double precision atomicAdd on Maxwell or older GPUs

---

tests/cupy_tests/testing_tests/test_helper.py

[backport] Remove nose dependency

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_complex_ops.py

[backport] Fix a.real and a.imag to return view

---

docs/source/install.rst

[backport] rewrite installation guide

---

cupyx/scipy/ndimage/interpolation.py

Fix document of ndimage

---

cupy/__init__.py

[backport] expose all supported dtypes from numpy

---

cupy/indexing/generate.py

[backport] Enable flake8 in cupy/indexing/generate.py

---

cupy/indexing/generate.py

Args of `r_` and `c_` have been broken. I eliminate the document of Args since it seems unnecessary.

Fix document of r_ and c_

---

cupyx/runtime.py
tests/cupyx_tests/test_runtime.py

Ref https://github.com/cupy/cupy/pull/1132#issuecomment-380709436

fix to capture CuDNNError in cupyx.runtime

---

cupy/cuda/runtime.pyx

[backport] fix duplicate delcaration of cudaError_t

---

cupy/cuda/cupy_cusolver.h
cupy/cuda/cusolver.pyx

use cusolverSpSetStream for cuSolverSP library calls

---

cupy/indexing/generate.py

[backport] Fix document of r_ and c_

---

cupy/cuda/cublas.pyx
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cusolver.h
cupy/cuda/cusolver.pyx
cupy/cuda/cusparse.pyx

[backport] Use streams when calling libraries

---

cupy/linalg/solve.py
tests/cupy_tests/linalg_tests/test_solve.py

[backport] fix cupy.linalg.inv() breaks its argument

---

cupy/cuda/memory_hook.pyx
cupy/cuda/memory_hooks/debug_print.py

[backport] Fix document of MemoryHook

---

cupy/cuda/compiler.py
tests/cupy_tests/cuda_tests/test_compiler.py

[backport] do not use platform-specific CC

---

cupy/core/core.pyx
cupy/creation/ranges.py
cupy/indexing/generate.py
cupy/sparse/construct.py
docs/source/reference/creation.rst
docs/source/reference/indexing.rst
docs/source/reference/logic.rst
docs/source/reference/math.rst
docs/source/reference/random.rst
docs/source/reference/sparse.rst
docs/source/reference/statistics.rst

Some functions are not documented. I add them to the document.

Fix missing documents

---

cupy/__init__.py

Add constants

---

cupy/cuda/memory.pxd
cupy/cuda/memory.pyx

[backport] Fix memory leak (mempool tries to find out-of-bounds bin when freeing chunk)

---

cupy/core/elementwise.pxi

[backport] Fix scalar casting rule to support Windows

---

tests/cupy_tests/math_tests/test_arithmetic.py

[backport] Fix real and imag test for bool to pass on Windows

---

cupy/__init__.py
cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

Support complex constants and functions in fuse

---

cupy/__init__.py
cupy/statistics/meanvar.py
docs/source/reference/statistics.rst
tests/cupy_tests/statics_tests/test_meanvar.py

This PR implements `cupy.average`.

Add cupy.average

---

cupy/__init__.py
cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

[backport] Support complex constants and functions in fuse

---

.gitignore

[backport] Fix gitignore to exclude pyd files

---

.travis.yml

See https://github.com/chainer/chainer/pull/4731 for context.

Fix hacking version

---

cupy/__init__.py

[backport] Add constants

---

cupy_setup_build.py
install/build.py

Separate NVTX module for better Windows support

---

cupy/__init__.py
cupy/creation/matrix.py
docs/source/reference/creation.rst
tests/cupy_tests/creation_tests/test_matrix.py

This PR implements cupy.tri, cupy.tril, and cupy.triu.

 Implement triangular array creation routines

---

cupy/cuda/cufft.pyx
tests/cupy_tests/fft_tests/test_fft.py

[backport] Free pooled memory when cufftMakePlan1d cannot allocate memory

---

cupy/cuda/cufft.pyx

[backport] Fix naming of cufft.pyx

---

cupy/core/reduction.pxi

[backport] Fix conversion from float16 to complex

---

cupy_setup_build.py
install/build.py

[backport] Separate NVTX module for better Windows support

---

cupy/creation/basic.py
tests/cupy_tests/creation_tests/test_basic.py

[backport] Fix default dtype of full

---

.coveragerc

[backport] Fix .coveragerc

---

cupy/core/core.pyx
cupy/core/fusion.py
tests/cupy_tests/math_tests/test_sumprod.py

[backport] Fix dtype option of sum and prod

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

~Close #1278.~
See also #1288.

Fix view of zerodim ndarray

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_complex_ops.py

Fix real and imag for zero-dim arrays

---

cupy/core/include/cupy/complex.cuh
tests/cupy_tests/math_tests/test_explog.py

Support expm1, log1p, log2 for complex type

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_complex_ops.py

[backport] Fix real and imag for zero-dim arrays

---

cupy/core/include/cupy/complex.cuh
tests/cupy_tests/math_tests/test_explog.py

[backport] Support expm1, log1p, log2 for complex type

---

cupy/cuda/thrust.pyx

[backport] catch C++ exceptions from Thrust

---

README.md

Fix #1182 and #200.
Sentences are copied from the installation guide.

Update README to encourage use of wheels

---

cupy/math/misc.py
tests/cupy_tests/math_tests/test_misc.py

I fixed misc functions to support complex types.
related to #1281

Fix unary functions in misc for complex

---

cupy/core/include/cupy/complex.cuh
cupy/math/misc.py
tests/cupy_tests/math_tests/test_misc.py

Fix binary functions in misc to support complex types

---

README.md

[backport] Update README to encourage use of wheels

---

cupy/math/misc.py
tests/cupy_tests/math_tests/test_misc.py

[backport] Fix unary functions in misc for complex

---

cupy/core/core.pyx
setup.cfg
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

[backport] Fix astype for complex dtypes

---

docs/source/reference/sparse.rst

Fix for question raised in https://github.com/cupy/cupy/issues/36#issuecomment-384151501

Improve sparse docs to show conversion from/to SciPy

---

cupy/core/include/cupy/complex.cuh
cupy/math/misc.py
tests/cupy_tests/math_tests/test_misc.py

[backport] Fix binary functions in misc to support complex types

---

cupy/core/include/cupy/complex.cuh
cupy/math/rounding.py
cupy/math/ufunc.py
tests/cupy_tests/math_tests/test_rounding.py

[backport] Support rounding for complex types

---

cupy/core/core.pyx
docs/source/_templates/autosummary/class.rst

[backport] Force displaying known methods which are mis-recognized as attributes by Sphinx

---

docs/source/reference/difference.rst

Expand reference on differences in zero-dimensional arrays

---

cupy_setup_build.py
install/build.py

Use define macro in setup.py

---

cupy/core/elementwise.pxi

`ElementwiseKernel ` calls some pure Python functions.
This PR reduces it.

Reduce Python function call in ElementwiseKernel

---

docs/source/reference/difference.rst

[backport] Expand reference on differences in zero-dimensional arrays

---

setup.py

[backport] Remove deprecated imp.load_source in setup.py

---

cupy/creation/matrix.py
tests/cupy_tests/creation_tests/test_matrix.py

Remove memory copy in diag function

---

cupy/creation/matrix.py
tests/cupy_tests/creation_tests/test_matrix.py

[backport] Remove memory copy in diag function

---

setup.cfg

[backport] Add license file to wheel

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

[backport] Fix view of zerodim ndarray

---

cupy/core/_dtype.pxd
cupy/core/_dtype.pyx
cupy/core/core.pyx
cupy/core/elementwise.pxi
cupy/core/reduction.pxi
cupy_setup_build.py

Improve ndarray initializing performance

---

cupy/core/core.pxd

Support weak reference to CuPy array

---

cupy/core/elementwise.pxi
cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

Fix type of return value of fused function

---

tests/cupy_tests/sparse_tests/test_coo.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py

I fixed ufuncs for sparse complex arrays.
merge #1277 first

Sparse complex ufunc

---

README.md
docs/source/install.rst

[backport] Update requirements for v5.0.0b2 / v4.2 release

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

It allows fused function which calls another fused function inside.
This PR resolves #1093.

Support composition of fused functions

---

cupy/cudnn.pyx

We can use best-fit-with-coalescing algorithm memory allocator. #168

Reduce GPU memory usage in (de)convotion

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h
cupy/cudnn.pyx

[backport] Use cuDNN v7 APIs to get conv algos for TensorCore

---

cupy/core/_dtype.pxd
cupy/core/_dtype.pyx
cupy/core/core.pyx
cupy/core/elementwise.pxi
cupy/core/reduction.pxi
cupy_setup_build.py

[backport] Improve ndarray initializing performance

---

cupy/core/core.pyx
cupy/testing/helper.py

NumPy supports small character.

 Support 'f' and 'c' in order

---

cupy/cudnn.pyx

[backport] Reduce GPU memory usage in (de)convotion

---

cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/cuda/pinned_memory.pyx
tests/cupy_tests/core_tests/test_internal.py

[backport] Round-up pooled memory allocation size with clp2

---

MANIFEST.in

[backport] Bundle license file to sdist

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_core.py

[backport] Fix to accept longer order names

---

tests/cupy_tests/core_tests/test_core.py

Refactor `TestOrder` and add test for `order=''`.

Refactor `TestOrder`

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

Add compilation methods in Fusion class

---

cupy/random/__init__.py
cupy/random/_kernels.py
cupy/random/distributions.py
cupy/random/generator.py
docs/source/reference/random.rst
tests/cupy_tests/random_tests/test_distributions.py
tests/cupy_tests/random_tests/test_generator.py

split from #1177.
I implemented binomial distribution.

Binomial distribution

---

cupy_setup_build.py
install/build.py

[backport] Support bundling dependent DLLs for Windows wheel support

---

cupy/creation/basic.py

Remove overhead in creation/basic.py

---

tests/cupy_tests/core_tests/test_core.py

[backport] Refactor `TestOrder`

---

cupy/creation/basic.py

[backport] Remove overhead in creation/basic.py

---

cupy/core/elementwise.pxi
cupy/core/reduction.pxi
tests/cupy_tests/core_tests/test_ndarray_ufunc.py

[backport] Improve reduce_dims for speed up

---

cupy/core/elementwise.pxi

[backport] Fix documentation of the `option` arg of ElementwiseKernel

---

cupy/cuda/function.pyx

[backport] Fix Module and LinkState not freed

---

cupy/statistics/correlation.py
tests/cupy_tests/statics_tests/test_correlation.py

Check if degrees of freedom <= 0.

 Fix cupy.cov for degrees of freedom <= 0

---

cupyx/scipy/sparse/__init__.py
cupyx/scipy/sparse/linalg/__init__.py
docs/source/reference/sparse.rst
setup.py

Introduce SciPy namespace

---

cupy/random/__init__.py
cupy/random/_kernels.py
cupy/random/distributions.py
cupy/random/generator.py
docs/source/reference/random.rst
tests/cupy_tests/random_tests/test_distributions.py
tests/cupy_tests/random_tests/test_generator.py

Beta Distribution

---

cupy/core/reduction.pxi

Use internal.clp2 in reduction

---

cupy/cuda/memory.pyx

[backport] Avoid memory error

---

cupy/core/reduction.pxi

[backport] Avoid collections.sequence

---

cupy/core/core.pyx
tests/cupy_tests/manipulation_tests/test_split.py

Support negative indices in array_split

---

cupy/core/core.pyx
tests/cupy_tests/manipulation_tests/test_split.py

[backport] Support negative indices in array_split

---

cupy/core/core.pyx
cupy/core/dlpack.pyx
cupy/core/internal.pyx
cupy/core/reduction.pxi
cupy/cuda/cublas.pyx
cupy/cuda/cudnn.pyx
cupy/cuda/cufft.pyx
cupy/cuda/curand.pyx
cupy/cuda/cusolver.pyx
cupy/cuda/cusparse.pyx
cupy/cuda/driver.pyx
cupy/cuda/function.pyx
cupy/cuda/nccl.pyx
cupy/cuda/nvrtc.pyx
cupy/cuda/runtime.pyx
cupy/cuda/thrust.pyx
cupy/cudnn.pyx
cupy/linalg/einsum.py
cupy/logic/comparison.py
cupy/random/generator.py
cupy/testing/array.py
cupy/testing/helper.py
tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
tests/cupy_tests/math_tests/test_arithmetic.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

This fix is for latest version of `autopep8`.

Fix styles for latest autopep8

---

cupy/__init__.py
cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

[backport] Add `divmod` function to `cupy` namespace

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

[backport] Allow more natural fusion notation

---

cupy/core/core.pyx
cupy/math/sumprod.py
tests/cupy_tests/manipulation_tests/test_split.py
tests/cupy_tests/math_tests/test_sumprod.py

[backport] Fix errors on 0-sized inputs

---

tests/cupy_tests/test_cusparse.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_base.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

I fixed test for sparse matrixes.
merge #1451 first

Fix sparse test

---

cupy/core/_scalar.pxd
cupy/core/_scalar.pyx
cupy/core/core.pyx
cupy/core/elementwise.pxi
cupy/core/halffloat.h
cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/cuda/function.pyx
cupy_setup_build.py
tests/cupy_tests/core_tests/test_internal.py
tests/cupy_tests/core_tests/test_userkernel.py

[backport] Speed up ElementwiseKernel launch

---

cupy/cuda/memory.pyx

[backport] Improve memory allocation performance

---

cupy/core/elementwise.pxi
cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

[backport] Fix type of return value of fused function

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

[backport] Support composition of fused functions

---

cupy/core/fusion.py
tests/cupy_tests/core_tests/test_fusion.py

[backport] Add compilation methods in Fusion class

---

cupy/core/fusion.py

[backport] Fix type of reduction

---

cupy/core/_scalar.pxd
cupy/core/_scalar.pyx
cupy/core/elementwise.pxi
cupy/core/reduction.pxi

 Use CScalar in elementwise and reduction

---

cupy/core/_scalar.pxd
cupy/core/_scalar.pyx
cupy/core/elementwise.pxi
cupy/core/reduction.pxi

[backport]  Use CScalar in elementwise and reduction

---

cupy/core/_scalar.pxd
cupy/core/_scalar.pyx
cupy/core/reduction.pxi
cupy_setup_build.py

[backport] Avoid compile error in old GCC (CentOS6)

---

cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx

Fix #707
I use custom allocator to avoid memory error in thrust

Fix thrust memory allocation problem

---

.flake8.cython
.travis.yml
cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
cupy/linalg/einsum.py
docs/source/contribution.rst

We don't want to use `hacking`. Please check chainer/chainer#4610.

Avoid hacking: Use the same test settings as Chainer

---

cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx

[backport] Fix thrust memory allocation problem

---

.flake8.cython
.travis.yml
cupy/__init__.py
cupy/core/core.pyx
cupy/cuda/cublas.pyx
cupy/cuda/cudnn.pyx
cupy/cuda/cufft.pyx
cupy/cuda/curand.pyx
cupy/cuda/cusolver.pyx
cupy/cuda/cusparse.pyx
cupy/cuda/function.pyx
cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
cupy/cuda/nccl.pyx
cupy/cuda/nvrtc.pyx
cupy/cuda/runtime.pyx
cupy/cuda/thrust.pyx
cupy/cudnn.pyx
docs/source/contribution.rst

[backport] Avoid hacking: Use the same test settings as Chainer

---

cupy/core/core.pyx
cupy/manipulation/rearrange.py

[backport] Fix unit test errors in NumPy 1.15

---

cupy/core/core.pxd
cupy/core/core.pyx

I fixed minor point to improve cythonize.

Add cdef and cpdef for better cythonize `core.pyx`

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

Fix indexing behavior when input is zero-sized array

---

cupy/__init__.py
cupy/logic/comparison.py
docs/source/reference/logic.rst
tests/cupy_tests/logic_tests/test_comparison.py

This PR implements cupy.allclose.

Implement `cupy.allclose`

---

cupy/core/elementwise.pxi
tests/cupy_tests/core_tests/test_elementwise.py

[backport] Raise error when trying to broadcast out_params in ElementwiseKernel

---

cupy/core/core.pyx

Improve view method performance

---

cupy/core/core.pyx

Add document to sqrt

---

cupy/__init__.py
cupy/core/fusion.py
cupy/math/misc.py
docs/source/reference/math.rst
tests/cupy_tests/math_tests/test_misc.py

Add nan_to_num

---

cupyx/scipy/special/bessel.py

Fix docstring of modified bessel function.

Fix docstring of modified bessel function

---

cupy/core/fusion.py

Fix cupy not working in thread other than one imported cupy

---

docs/source/install.rst

I confirmed that cupy works with cuDNN v7.2.

Support cuDNN v7.2

---

cupy/core/fusion.py

[backport] Fix cupy not working in thread other than one imported cupy

---

tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
tests/cupyx_tests/scipy_tests/special_tests/test_digamma.py
tests/cupyx_tests/scipy_tests/special_tests/test_gamma.py
tests/cupyx_tests/scipy_tests/special_tests/test_gammaln.py
tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py
tests/cupyx_tests/scipy_tests/special_tests/test_zeta.py
tests/cupyx_tests/scipy_tests/test_get_array_module.py

Test fails without these `import` because `scipy` does not import `scipy.special` automatically.

Import scipy.special to use it in test

---

cupy/core/fusion.py

[hotfix] [backport] Fix cupy not working in thread other than one imported cupy

---

tests/cupy_tests/core_tests/test_fusion.py

Add test for thread use case of fusion

---

cupy/sparse/compressed.py
cupy/testing/helper.py
tests/cupy_tests/sparse_tests/test_construct.py
tests/cupy_tests/sparse_tests/test_coo.py
tests/cupy_tests/sparse_tests/test_csc.py
tests/cupy_tests/sparse_tests/test_csr.py
tests/cupy_tests/sparse_tests/test_dia.py

[Backport] Support SciPy1.0+

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h

cuDNN v7.2 introduced new APIs for RNN which support unpacked arrays.

Add new APIs for RNN

---

cupy/cuda/cupy_cuda.h
cupy/cuda/runtime.pyx

[backport] Reset cuda runtime error

---

cupy/core/core.pyx
cupy/core/elementwise.pxi
cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/cuda/cublas.pxd
cupy/cuda/cublas.pyx
cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/curand.pyx
cupy/cuda/cusolver.pxd
cupy/cuda/cusolver.pyx
cupy/cuda/cusparse.pxd
cupy/cuda/cusparse.pyx
cupy/cuda/device.pxd
cupy/cuda/device.pyx
cupy/cuda/driver.pxd
cupy/cuda/driver.pyx
cupy/cuda/function.pyx
cupy/cuda/nvrtc.pxd
cupy/cuda/nvrtc.pyx
cupy/cuda/nvtx.pyx
cupy/cuda/profiler.pxd
cupy/cuda/profiler.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx
cupy/cudnn.pyx

[backport] Improve exception handling performance in Cython

---

tests/cupy_tests/core_tests/test_fusion.py

[hotfix] [backport] Add test for thread use case of fusion

---

.flake8.cython
docs/source/_comparison_generator.py
setup.cfg

This PR fixes very minor issues.

Fix around style checking

---

tests/cupy_tests/random_tests/test_generator.py

- Test reproducibility for non-zero seeds
- Make `generate`, `generate_many` return different values on `repeat` and `retry`.

Test reproducibility for any seed

---

cupy/random/generator.py

- Avoid generating `inf`
- Fix  #1644

Fix laplace

---

cupy/random/__init__.py
cupy/random/distributions.py
cupy/random/generator.py
docs/source/reference/random.rst
tests/cupy_tests/random_tests/test_distributions.py
tests/cupy_tests/random_tests/test_generator.py

There is error in `cp.random.standard_exponential`. I fixed.

add `cupy.random.exponential`

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cuda/cupy_cudnn.h
cupy/cudnn.pyx

[backport] Improve cudnn.pyx to up speed

---

cupy/core/core.pxd
cupy/core/dlpack.pyx
cupy/cuda/__init__.py
cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

This PR intends to support external memory pointer that is not owned by CuPy.

General support for external memory pointer

---

cupy/core/_kernel.pyx
cupy/core/core.pxd
cupy/core/core.pyx
cupy/core/dlpack.pyx
cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/linalg/einsum.py
tests/cupy_tests/core_tests/test_ndarray.py

Added `strides` option to align with `numpy.ndarray`.

Add `strides` option in `cupy.ndarray`

---

cupy/linalg/norms.py

fixed issue #1653

---

cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

Update ndimage to support SciPy 1.0+

---

cupy/random/_kernels.py

Make them ordered as in the original file.
~Merge #1680 first.~ (DONE)

Sort distribution kernels

---

cupy/random/_kernels.py

[backport] Add licenses of distribution kernels from numpy

---

tests/cupy_tests/math_tests/test_floating.py

Tentatively skip failing `test_nextafter_combination`

---

tests/cupy_tests/random_tests/test_generator.py

Add more K-S tests

---

tests/cupy_tests/random_tests/test_sample.py

[backport] Fix TestRandintDtype was slow

---

cupy/core/include/cupy/carray.cuh

[backport] Fix float16 nextafter

---

cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

[backport] Update ndimage to support SciPy 1.0+

---

.travis.yml
appveyor.yml
docs/source/contribution.rst
setup.py

[backport] Reorganize setup requirements

---

cupy/random/generator.py

Use "x mod 1" to generate [0, 1)-uniform random

---

.gitignore

[backport] Add header file generated by Cython to gitignore

---

tests/cupy_tests/random_tests/test_distributions.py

[backport] Minor fixes to cupy.random tests

---

cupy/linalg/einsum_opt.py

It seems there are many updates to `einsumfunc.py` in numpy.  This PR updates the corresponding file in cupy.

Update einsum optimization routine

---

cupy/core/reduction.pxi

[backport] Improve reduction code

---

cupy/core/core.pyx
tests/cupy_tests/logic_tests/test_comparison.py

Add workaround for numpy issue 12142

---

docs/source/install.rst

Add support for NumPy 1.15 in docs

---

docs/source/install.rst

[backport] Add support for NumPy 1.15 in docs

---

cupy/math/floating.py

[backport] Explain that -ftz=true affects nextafter

---

cupy/core/core.pyx
tests/cupy_tests/logic_tests/test_comparison.py

[backport] Add workaround for numpy issue 12142

---

cupy/random/generator.py

[backport] Fix test for python 3.7

---

docs/source/_comparison_generator.py

[backport] Improve `_comparison_generator`

---

cupy/cudnn.pyx

We want to provide simple cuDNN interface

Add cuDNN pooling interface

---

cupy/cudnn.pyx

We want to provide simple cuDNN interface

Add cuDNN softmax interface

---

cupy/core/core.pyx
cupy/core/include/cupy/atomics.cuh
tests/cupy_tests/core_tests/test_ndarray_scatter.py

[backport] Add float16 support for scatter_add

---

tests/cupy_tests/core_tests/test_userkernel.py

Also fixed (maybe) wrong test case value.

Fix userspace kernel test failure in Windows

---

tests/cupy_tests/core_tests/test_userkernel.py

[backport] Fix userspace kernel test failure in Windows

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_scatter.py

[backport] Support float64 in scatter_add

---

cupy/cudnn.pyx

[backport] Add cuDNN softmax interface

---

cupy/cudnn.pyx

[backport] Add cuDNN pooling interface

---

cupy/testing/condition.py
cupy/testing/helper.py
cupy/testing/parameterized.py
tests/cupy_tests/testing_tests/test_condition.py
tests/cupy_tests/testing_tests/test_parameterized.py

[backport] Support skipping tests decorated by condition or parametize

---

cupy/core/core.pyx
cupy/cuda/cupy_cuda.h
cupy/cuda/cupy_cudnn.h
cupy/cudnn.pyx
cupy_setup_build.py
cupyx/scipy/sparse/csr.py
install/build.py
tests/cupy_tests/test_cudnn.py

[backport] Drop support for CUDA 7.0 / 7.5 and cuDNN v4

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cudnn.pyx

We want to provide simple cuDNN interface.

Implement cuDNN batch normalization interface

---

cupy/cuda/__init__.py
cupy/cuda/cupy_cusparse.h

[backport] Assume CUDA v8 in cuSPARSE/cuSOLVER check

---

docs/source/reference/environment.rst

[backport] Fix description of CUDA_PATH environment variable

---

cupy/cuda/cudnn.pxd
cupy/cuda/cudnn.pyx
cupy/cudnn.pyx

[backport] Implement cuDNN batch normalization interface

---

docs/source/_comparison_generator.py

[backport] Indicate alias in comparison table

---

cupy/cudnn.pyx
tests/cupy_tests/test_cudnn.py

[backport] Fix DropoutStates interface to avoid using cuDNN handle

---

docs/source/reference/ext.rst

[backport] Enable intersphinx to cupyx module

---

cupy/core/core.pyx
cupy/core/include/cupy/complex/arithmetic.h
cupy/logic/ops.py
tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py

[backport] Support comparison operators for complex numbers

---

cupy/cudnn.pyx

I extracted high-level API from Chainer. It provides high-level API for cudnn's RNN.

RNN high level API

---

docs/source/install.rst
tests/cupy_tests/test_cudnn.py

cuDNN v7.3 supports dilated convolution for 2D in deterministic method.

Update for cuDNN v7.3 and v7.4

---

CodeOfConduct.md

Add code of conduct

---

cupy/cudnn.pyx

[backport] RNN high level API

---

cupy/cudnn.pyx

I renamed a function.
related to #1659

Rename `_make_rnn_workspace` function

---

cupy/cudnn.pyx

[backport] Rename `_make_rnn_workspace` function

---

cupy/cudnn.pyx

for refactoring
merge #1838 first

Make a helper function to get the number of layers in RNN

---

docs/source/install.rst
tests/cupy_tests/test_cudnn.py

[backport] Update for cuDNN v7.3 and v7.4

---

docs/source/install.rst

[backport] Support CUDA 10.0

---

cupy/core/fusion.py
cupy/logic/truth.py
cupy/math/sumprod.py
cupy/statistics/order.py
tests/cupy_tests/core_tests/test_fusion.py

Fix bad source hyperlinks

---

cupy/core/include/cupy/atomics.cuh

[backport]  Remove unnecessary intermediate data in FP16 atomicAdd

---

CodeOfConduct.md

[backport] Add code of conduct

---

tests/cupy_tests/random_tests/test_distributions.py

[backport] Fix test failure of binomial distribution in Windows

---

docs/source/install.rst

[backport] Update docs for newly supported libraries

---

tests/cupy_tests/core_tests/test_ndarray_reduction.py

This PR follows #1636 to add tests for `min` and `max` for complex numbers.

Add tests for complex min and max
