cupy/cupy

- docs/source/reference/interoperability.rst
> Document Numba CUDA array conversion

- cupy/cudnn.pyx
> Fix backward of batch normalization

- cupy/cudnn.pyx
> [backport] Fix backward of batch normalization

- cupy/cuda/cupy_nccl.h
> Support for documenting NCCL interfaces

- cupy/cudnn.pyx
There are duplicated and redundant code to create arrays. I refactored array creation method in RNN API.
merge #1839 first
> Refactor array creation for RNN API

- cupy/cudnn.pyx
> [backport] Check if cx is None

- cupyx/scipy/sparse/__init__.py
- cupyx/scipy/sparse/construct.py
- cupyx/scipy/sparse/sputils.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
> [backport] add cupyx.scipy.sparse.diags

- MANIFEST.in
- cupy/core/carray.pxi
- cupy/core/include/cupy/_cuda/README.md
- cupy/core/include/cupy/_cuda/cuda-10.0/cuda_fp16.h
- cupy/core/include/cupy/_cuda/cuda-10.0/cuda_fp16.hpp
- cupy/core/include/cupy/_cuda/cuda-9.2/cuda_fp16.h
- cupy/core/include/cupy/_cuda/cuda-9.2/cuda_fp16.hpp
- setup.py
> [backport] Bundle CUDA fp16 headers

- cupy/core/core.pyx
> [backport] Verbose broadcast failure message

- cupy/random/generator.py
- docs/source/reference/difference.rst
- tests/cupy_tests/random_tests/test_generator.py
Fixes https://github.com/cupy/cupy/issues/1675
> Support Numpy arrays as seeds in RandomState

- cupy/cuda/cupy_nccl.h
> [backport] Support for documenting NCCL interfaces

- cupy/core/fusion.py
- cupy/creation/from_data.py
- cupy/logic/truth.py
- cupy/math/arithmetic.py
- cupy/math/misc.py
- cupy/math/rounding.py
- cupy/math/sumprod.py
- cupy/sorting/search.py
- cupy/statistics/order.py
`_ufunc_wrapper` and `_reduction_wrapper` cause some problems (e.g. generate bad hyperlinks in documents), so made not allowed to use them.
> Avoid using _ufunc_wrapper and _reduction_wrapper

- cupy/cuda/cudnn.pxd
- cupy/cuda/cudnn.pyx
- cupy/cuda/cupy_cudnn.h
- cupy/cudnn.pyx
This PR aims to support new APIs added in cuDNN v7.4.1 for fast batch normalization. Please refer to a pointer below about new APIs.
https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_741.html#rel_741
> Support New APIs in cudnn v7.4.1

- cupy/__init__.py
- cupy/lib/stride_tricks.py
- docs/source/reference/indexing.rst
- docs/source/reference/lib.rst
- docs/source/reference/routines.rst
- setup.py
- tests/cupy_tests/lib_tests/test_strided_tricks.py
> Add `as_strided`

- cupy/__init__.py
- cupy/lib/stride_tricks.py
- docs/source/reference/lib.rst
- docs/source/reference/routines.rst
- setup.py
- tests/cupy_tests/lib_tests/test_strided_tricks.py
According to #755, I tried to add `as_strided` that works similar to `np.lib.stride_tricks.as_strided`.
It's my first contribution to cupy. Any suggestion is welcome.
> Added as_strided

- cupy/cuda/cudnn.pxd
- cupy/cuda/cudnn.pyx
- cupy/cuda/cupy_cudnn.h
> [backport] Support New APIs in cudnn v7.4.1

- cupy/core/core.pyx
- cupy/creation/basic.py
- tests/cupy_tests/creation_tests/test_basic.py
> Add `order` argument to` empty_like`,` zeros_like`, etc.

- cupy/core/core.pyx
Close #1322 
Please see discussion ~numpy/numpy#11129~ numpy/numpy#12028.
> Implement __array_function__ interface

- cupyx/scipy/sparse/base.py
- cupyx/scipy/sparse/compressed.py
- cupyx/scipy/sparse/coo.py
- cupyx/scipy/sparse/data.py
- cupyx/scipy/sparse/dia.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
> [backport] fix RecursionError bug in conj method of sparse matrix classes

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
- tests/cupy_tests/core_tests/test_ndarray_unary_op.py
- tests/cupy_tests/math_tests/test_misc.py
> Support NumPy 1.16

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
- tests/cupy_tests/core_tests/test_ndarray_unary_op.py
- tests/cupy_tests/math_tests/test_misc.py
> [backport] Support NumPy 1.16

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray.py
> Fix ndarray initialization bug

- cupy/core/_kernel.pyx
- cupy/core/fusion.py
> [backport] Fix ufunc performance degradation

- cupy/core/__init__.py
- cupy/core/_errors.py
- cupy/core/_kernel.pyx
- cupy/core/_routines_manipulation.pxd
- cupy/core/_routines_manipulation.pyx
- cupy/core/_ufuncs.py
- cupy/core/core.pxd
- cupy/core/core.pyx
- cupy/core/fusion.pyx
- cupy/core/internal.pxd
- cupy/core/internal.pyx
- cupy/core/reduction.pxi
- cupy/cudnn.pyx
- cupy/manipulation/join.py
- cupy/manipulation/rearrange.py
- cupy/math/sumprod.py
- cupy_setup_build.py
- tests/cupy_tests/core_tests/test_core.py
- tests/cupy_tests/core_tests/test_ndarray.py
- tests/cupy_tests/manipulation_tests/test_dims.py
- tests/cupy_tests/manipulation_tests/test_join.py
- tests/cupy_tests/manipulation_tests/test_transpose.py
- tests/cupy_tests/math_tests/test_sumprod.py
- tests/cupy_tests/sorting_tests/test_sort.py
An attempt to slim down `core.pyx`.
> Refactor manipulation routines from `core.pyx`

- .flake8.cython
> [backport] Ignore W503 and W504

- cupy/fft/fft.py
- tests/cupy_tests/fft_tests/test_fft.py
> [backport] ensure the input to the CUFFT Plan1D class is C contiguous

- README.md
> [backport] Add cupy-cuda100 to README

- tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
> [backport] Fix test to support SciPy 1.12

- README.md
> [backport] Fix README image to use URL

- cupy/cuda/memory.pyx
> [backport] Call free_all_blocks to free CUDA memory

- docs/source/install.rst
> [backport] Document NumPy 1.16 support

- examples/stream/cupy_memcpy.py
Based on suggestion by @jeng1220 at #1970. It also fixes #1692. Now the script performs a simple benchmark.
The output of `nvprof --print-gpu-trace python examples/stream/cupy_memcpy.py` is as follows. (GTX 1080 Mobile, Gentoo Linux) 
```
==3756== NVPROF is profiling process 3756, command: python cupy_memcpy.py
Synchronous Device to Host / Host to Device (ms)
2.3998401165008545
Asynchronous Device to Host / Host to Device (ms)
0.8518080115318298
==3756== Profiling application: python cupy_memcpy.py
==3756== Profiling result:
Start  Duration            Grid Size      Block Size     Regs*    SSMem*    DSMem*      Size  Throughput  SrcMemType  DstMemType           Device   Context    Stream  Name …
```
> Improve memcpy example

- cupy/__init__.py
- cupy/core/_routines_indexing.pxd
- cupy/core/_routines_indexing.pyx
- cupy/core/core.pxd
- cupy/core/core.pyx
- cupy/indexing/insert.py
- docs/source/reference/indexing.rst
- tests/cupy_tests/indexing_tests/test_insert.py
Solves #1690. Reference pages and tests are also added.
> Implement `cupy.put` and `cupy.place`

- tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
- tests/cupy_tests/testing_tests/test_helper.py
It seems NumPy changed assertion messages in the update 1.16.0 -> 1.16.1!
> Fix test with NumPy 1.16.1

- tests/cupy_tests/testing_tests/test_array.py
> [backport] Fix test of `assert_array_list_equal`

- tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
- tests/cupy_tests/testing_tests/test_helper.py
> [backport] Fix test with NumPy 1.16.1

- cupy/cuda/cupy_nccl.h
- cupy/cuda/nccl.pyx
- cupyx/runtime.py
- install/build.py
> [backport] Use version interface in NCCL 2.3.4

- cupy/cuda/cupy_nccl.h
> Fix NCCL version assignment for NCCL < 2.3.4

- cupy/cuda/cupy_nccl.h
> [backport] Fix NCCL version assignment for NCCL < 2.3.4

- cupy/core/core.pyx
- cupy/cuda/thrust.pyx
Fix #1932 except following method.
```
cpdef ndarray _reshape(ndarray self, vector.vector[Py_ssize_t] shape)
cpdef ndarray _transpose(ndarray self, vector.vector[Py_ssize_t] axes)
```
> Fix vector handling

- cupy/core/core.pyx
- cupy/cuda/thrust.pyx
> [backport] Fix vector handling

- cupy_setup_build.py
> Eliminate RUNPATH to use correct cuDNN

- cupy/core/_kernel.pyx
- cupy/core/fusion.pyx
`hasattr(_thread_local, 'history')` is slow.
> Improve _is_fusing performance

- cupy/core/_kernel.pyx
This PR reduces ufunc kernel launch time.
> Improve kind score operation

- cupy_setup_build.py
This PR is to avoid multiple define. `s.setdefault('extra_link_args', [])` returns same array.
> Fix eliminate-runpath

- cupy/cuda/runtime.pyx
> remove duplicate declaration of cudaMalloc

- cupy/core/_kernel.pyx
- cupy/util.pyx
Following code is inefficient in Cython.
``` python
if key in dict:
return dict[key]
```
> Improve dictionary operation

- cupy/core/_kernel.pyx
> Improve get_ufunc_kernel

- cupy/core/_kernel.pyx
- cupy/core/reduction.pxi
> Reduce get_device_id call

- cupy/core/_kernel.pyx
- cupy/util.pyx
> [backport] Improve dictionary operation

- cupy/random/_kernels.py
- cupy/random/generator.py
> [backport] Fix random generator seed type

- cupy/core/fusion.pyx
- docs/source/reference/kernel.rst
- docs/source/tutorial/kernel.rst
Merge after PR #1594 and #1713 are merged.
> Add documentation of `cupy.fuse`

- cupy/cuda/__init__.py
- cupy/cuda/cupy_nccl.h
- cupy/cuda/nccl.pyx
- tests/cupy_tests/cuda_tests/test_nccl.py
Add updates at https://github.com/NVIDIA/nccl/pull/172 . When built with old libraries it throws Exceptions.
> Add NCCL 2.4 functions

- cupy/cuda/__init__.py
- cupy/cuda/cupy_nccl.h
- cupy/cuda/nccl.pyx
- tests/cupy_tests/cuda_tests/test_nccl.py
> [backport] Add NCCL 2.4 functions

- cupy/core/fusion.pyx
> Remove experimental warning of `cupy.fuse`

- cupy/core/core.pyx
> [backport] Avoid `import numpy`

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_array_function.py
This PR solves https://github.com/cupy/cupy/issues/2011
> Fix usage array function for CuPy modules

- cupyx/scipy/fftpack/fft.py
> Make `plan` argument in 2D/3D FFT functions experimental

- docker/python2/Dockerfile
- docker/python3/Dockerfile
Bump version in Dockerfiles to v5.3.0.
> Bump version in Dockerfiles to v5.3.0

- cupy/core/_dtype.pyx
This PR reduces ndarray initialization time.
> Do exact type comparison instead of `isinstance` for `numpy.dtype`

- cupy/cudnn.pyx
This PR aims to fix a fp16 related issue of batch normalization layer, resulting in NaN.
This is related to https://github.com/chainer/chainer/pull/6323
> Fix fp16 issue in batch normalization

- .travis.yml
- docs/Makefile
CuPy counterpart for https://github.com/chainer/chainer/pull/4037 and https://github.com/chainer/chainer/pull/6417
Merge chainer/chainer-test#500 first.
> Do not fail by warnings when building docs

- .travis.yml
- docs/Makefile
> [backport] Do not fail by warnings when building docs

- cupy_setup_build.py
> Use deep copy in setting up RPATH

- docs/source/reference/interoperability.rst
Add docs for ``__array_function__`` feature.
> Document ``__array_function__``

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray.py
> Check array contiguity in `copy`

- docs/source/install.rst
> [backport] Add NCCL v2.4 support to docs

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray.py
> [backport] Check array contiguity in `copy`

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_indexing.py
> [backport] Fix assigning from complex to float 

- cupy/cudnn.pyx
I implemented some helper functions for cuDNN's extended RNN APIs introduced in cuDNN v7.2.
This PR includes refactoring code to reduce change.
> New RNN API introduced in v7.2

- cupy/cudnn.pyx
> [backport] Remove unused variable

- cupy/core/_kernel.pyx
- cupy/core/core.pxd
- cupy/core/core.pyx
- cupy/core/reduction.pxi
- cupy/creation/from_data.py
- tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
- tests/cupy_tests/creation_tests/test_from_data.py
ElementwiseKernel and ReductionKernel accept `__cuda_array_interface__` array by this PR.
> More support `__cuda_array_interface__`

- cupy/cuda/memory.pyx
Deleted some redundant declaration and fixed the assertion error by adding gc manipulations. See #2074 for details.
This my first contribution to the project, any suggestions are welcome.
> Fix assertion error in _Chunk.split

- cupy/cuda/memory.pyx
This PR is backport of #2074. Fix #2103
> [backport] Fix assertion error in _Chunk.split

- cupy/core/core.pyx
> [backport] Add strides to docstring of ndarray

- cupy/core/dlpack.pyx
> Support dltensor with strides of NULL

- cupy/core/dlpack.pyx
> [backport] Support dltensor with strides of NULL

- cupy/cuda/device.pyx
> Reorganize import in device.pyx

- cupy/cuda/cupy_cusolver.h
- cupy/cuda/cusolver.pxd
- cupy/cuda/cusolver.pyx
- cupy/cuda/device.pxd
- cupy/cuda/device.pyx
This PR is backport of #2053 and #2121.
> [backport] Avoid sharing handles between threads

- tests/cupy_tests/math_tests/test_sumprod.py
- tests/cupy_tests/math_tests/test_trigonometric.py
> Fix testing condition of `diff` and `unwrap`

- tests/cupy_tests/math_tests/test_sumprod.py
- tests/cupy_tests/math_tests/test_trigonometric.py
> [backport] Fix testing condition of `diff` and `unwrap`

- cupy/cuda/memory.pxd
- cupy/cuda/memory.pyx
- docs/source/reference/environment.rst
- docs/source/reference/memory.rst
- tests/cupy_tests/cuda_tests/test_memory.py
> Implement limit to memory pool

- cupy/testing/array.py
- cupy/testing/helper.py
Add `strides_check` option. Separated from #2081.
> Add `strides_check` option in array testing functions

- cupy/cuda/stream.pyx
> [backport] Avoid unnecessary weak pointer for null stream

- tests/cupy_tests/testing_tests/test_array.py
Add a missing test for `assert_array_equal(strides_check=True)` introduced in #2150.
> Add a test for `assert_array_equal(strides_check=True)`

- cupy/core/_kernel.pyx
> Emit kernel names with type names

- examples/kmeans/kmeans.py
Follows #2145.
This PR makes the k-means sample code cleaner in terms of educational purpose.
> Make k-means sample code cleaner for educational purpose

- cupy/cudnn.pyx
> [backport] Avoid using Tensor Core with cuDNN deterministic mode in convolution backward

- cupy/core/core.pyx
- cupy/cudnn.pyx
> [backport] Fix usage check of TensorCore

- tests/cupy_tests/test_cudnn.py
Fix issue introduced in #1885.
> Fix test failure when cudnn is unavailable

- docs/source/upgrade.rst
> [backport] Add upgrade guide for v6

- cupy/core/core.pyx
- cupy/cudnn.pyx
Reverts cupy/cupy#2168
https://github.com/cupy/cupy/pull/2168#issuecomment-493295582
> Revert "Fix usage check of TensorCore"

- cupy/core/core.pyx
- cupy/cudnn.pyx
Reverts cupy/cupy#2172
https://github.com/cupy/cupy/pull/2168#issuecomment-493295582
> Revert "[backport] Fix usage check of TensorCore"

- README.md
> [backport] Add cupy-cuda101 to README

- cupy/core/_routines_math.pyx
Fixes https://github.com/cupy/cupy/issues/2189.
I'll add tests if required. Verified locally.
> Fix `power` for large integrals

- cupy/core/_routines_manipulation.pyx
- tests/cupy_tests/manipulation_tests/test_split.py
> [backport] Fix `array_split` with non-equally dividing sections

- cupy/random/sample.py
- cupy/statistics/histogram.py
CUDA provides `unsigned long long` version `atomicAdd`.
> Improve atomicAdd in histgram and sample

- cupy/random/sample.py
- cupy/statistics/histogram.py
> [backport] Improve atomicAdd in histgram and sample

- cupy/cuda/memory.pyx
Fixes #2241
* Show the total memory successfully allocated so far, and explicitly state what it is.
* Put commas
* Wording improvement
```
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 200000000000 bytes (total 200000004096 bytes)
```
```
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 200,000,000,000 bytes (allocated so far: 4,096 bytes).
```
> Improve out-of-memory error message

- .gitignore
- cupy_setup_build.py
> [backport] Add setup option to copy include files in wheel

- cupyx/runtime.py
Adding API to retrieve installation info, such as include/library directory paths.
Needed for https://github.com/chainer/chainer/pull/7442
> Add API to retrieve installation info

- cupy/random/generator.py
- cupy/random/permutations.py
- tests/cupy_tests/random_tests/test_permutations.py
> Make `RandomState.permutation` compatible with `random.permutation`

- cupy/random/generator.py
- cupy/random/permutations.py
- tests/cupy_tests/random_tests/test_permutations.py
> [Backport] Make `RandomState.permutation` compatible with `random.permutation`

- cupy/core/core.pyx
> Coding style fix

- cupy/core/_routines_indexing.pyx
This PR reduces kernel launch count and memory consumption in typical cases.
`reduced_idx` is calculated without temporary arrays.
> Simplify _prepare_multiple_array_indexing

- cupy/core/internal.pxd
- cupy/core/internal.pyx
> Add `constant` modification to `vector_equal`

- cupy/core/internal.pxd
- cupy/core/internal.pyx
> [backport] Add `constant` modification to `vector_equal`

- cupy/core/_routines_indexing.pyx
> [backport] Simplify _prepare_multiple_array_indexing

- cupy/core/_kernel.pyx
> [backport] Fix _preprocess_args to avoid calling hasattr

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray.py
- tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
> [backport] Make `__cuda_array_interface__()['strides']` be `tuple`

- cupy/core/_kernel.pyx
> [backport] Remove unused code

- cupy/cudnn.pyx
> [backport] Avoid CUDNN_STATUS_BAD_PARAMS

- docs/source/reference/interoperability.rst
> [backport] Document interoperability with mpi4py

- cupy_setup_build.py
Like ChainerX: https://github.com/chainer/chainer/blob/c8e47f7e8463c84cedb6ac12ccbad582d6321ce5/chainerx_cc/CMakeLists.txt#L168-L170
> Make nvcc code generation target configure by env var

- install/build.py
> Remove warning about nvcc absence

- install/build.py
> [backport] Remove warning about nvcc absence

- docs/source/install.rst
> [backport] Update installation guide

- tests/cupy_tests/core_tests/test_core.py
- tests/cupy_tests/test_type_routines.py
> [backport] Enhanced tests for type routines

- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump version in Dockerfile to v6.2.0

- cupy/linalg/decomposition.py
> [backport] Fix for `linalg.svd` documentation

- cupy/linalg/decomposition.py
> Fix markup in `linalg.svd` docs

- cupy/linalg/__init__.py
- cupy/linalg/solve.py
- tests/cupy_tests/linalg_tests/test_solve.py
This PR aims to support batched matrix inverse using cublasXgetrfBatched and cublasXgetriBatched. Re: data type, float32, float64, complex64 and complex128 will be supported.
> Support batched matrix inverse

- cupy/linalg/decomposition.py
> [backport] Fix markup in `linalg.svd` docs

- cupy/core/_routines_math.pyx
- cupy/core/core.pyx
- cupy/core/fusion.pyx
- cupy/cudnn.pyx
> [backport] Fix unused imports and import orders

- cupy/cuda/cupy_nccl.h
- cupy/cuda/nccl.pyx
This PR adds a wrapper for ncclBroadcast which replaced ncclBcast in NCCL 2.2.
> Add NCCL broadcast

- docs/source/reference/dtype.rst
- docs/source/reference/linalg.rst
- docs/source/reference/routines.rst
> [backport] Add new functions to API reference

- cupy/cuda/compiler.py
- cupy/cuda/cublas.pyx
- cupy/cuda/cudnn.pyx
- cupy/cuda/cufft.pyx
- cupy/cuda/curand.pyx
- cupy/cuda/cusolver.pyx
- cupy/cuda/cusparse.pyx
- cupy/cuda/cutensor.pyx
- cupy/cuda/driver.pyx
- cupy/cuda/memory.pyx
- cupy/cuda/nccl.pyx
- cupy/cuda/nvrtc.pyx
- cupy/cuda/runtime.pyx
- tests/cupy_tests/cuda_tests/test_compiler.py
- tests/cupy_tests/cuda_tests/test_cublas.py
- tests/cupy_tests/cuda_tests/test_cudnn.py
- tests/cupy_tests/cuda_tests/test_cufft.py
- tests/cupy_tests/cuda_tests/test_curand.py
- tests/cupy_tests/cuda_tests/test_cusolver.py
- tests/cupy_tests/cuda_tests/test_cusparse.py
- tests/cupy_tests/cuda_tests/test_cutensor.py
- tests/cupy_tests/cuda_tests/test_driver.py
- tests/cupy_tests/cuda_tests/test_memory.py
- tests/cupy_tests/cuda_tests/test_nccl.py
- tests/cupy_tests/cuda_tests/test_nvrtc.py
- tests/cupy_tests/cuda_tests/test_runtime.pyx
> Make exceptions picklable

- tests/cupy_tests/test_type_routines.py
> Check return type in `test_type_routines.py`

- cupy/__init__.py
- cupy/core/_routines_statistics.pxd
- cupy/core/_routines_statistics.pyx
- cupy/statistics/meanvar.py
- docs/source/reference/statistics.rst
- tests/cupy_tests/statics_tests/test_meanvar.py
This PR partially resolves #2295.
I have `float16` deviation problem for `cupy.nanvar` and `cupy.nanstd` same as in #2319.
> Add `cupy.nanvar` and `cupy.nanstd`

- tests/cupy_tests/random_tests/test_distributions.py
> [backport] Remove `random.power` test with forbidden value

- cupy/testing/helper.py
> Avoid using `numpy.nonzero` in `_make_decorator`

- cupy/testing/helper.py
> [backport] Avoid using `numpy.nonzero` in `_make_decorator`

- tests/cupy_tests/random_tests/test_generator.py
> [backport] Increase numbers of retries for K-S tests

- docs/source/install.rst
Part of https://github.com/chainer/chainer/issues/7741
> Add 1.17 to supported NumPy versions

- cupy/core/_routines_statistics.pyx
Code simplification using `isnan` defined here:
https://github.com/cupy/cupy/blob/7d18da1918ebe4febd7eaa5896895b957e6a2ba6/cupy/core/include/cupy/complex.cuh#L25-L27.
> Some simplifications using `isnan`

- cupy/cuda/cupy_cusolver.h
- cupy/cuda/cusolver.pxd
- cupy/cuda/cusolver.pyx
This PR wraps more cuSolver APIs mainly for dense linear solver.
> Add more cuSolver APIs for dense linear solver

- cupyx/scipy/sparse/base.py
- cupyx/scipy/sparse/csr.py
- cupyx/scipy/sparse/dia.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
> [backport] implement diagonal method for cupyx.scipy.sparse.dia_matrix

- docs/source/install.rst
> [backport] Add 1.17 to supported NumPy versions

- .pfnci/config.pbtxt
> Drop Python 2 PFN CI configuration

- .travis.yml
> Drop Python 2 Travis CI configuration

- docker/python2/Dockerfile
CuPy counterpart of https://github.com/chainer/chainer/pull/8027
> Fix NumPy version in Dockerfile

- tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
Reverts cupy/cupy#2376
~Merge #2377 #2396 first.~
> Revert "Skip some ndarray-elementwise-op tests as temporary fix"

- cupy/core/core.pyx
- cupy/creation/basic.py
- tests/cupy_tests/creation_tests/test_basic.py
> [backport] Support for shape argument in *_like functions

- cupy/cudnn.pyx
> [backport] Normalize hidden layer strides in cuDNN RNN

- cupy/__init__.py
- cupy/misc/__init__.py
- cupy/misc/memory_ranges.py
- setup.py
- tests/cupy_tests/misc_tests/test_memory_ranges.py
> Add `may_share_memory`

- docs/source/install.rst
- docs/source/reference/environment.rst
Document new build-time environment variable introduced in #2210
> Document CUTENSOR_PATH

- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
> Fix data race in advanced indexing test

- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
> [backport] Fix data race in advanced indexing test

- cupy/core/_routines_math.pxd
- cupy/core/_routines_math.pyx
- cupy/core/_routines_statistics.pxd
- cupy/core/_routines_statistics.pyx
- cupy/core/core.pxd
- cupy/core/core.pyx
- cupy/math/sumprod.py
- cupy/sorting/search.py
> Remove unncecessary `ndarray` private methods

- docs/source/contribution.rst
> [backport] Add appropriate pointer types in Cython to the contribute guide

- cupy/core/_kernel.pyx
- cupy/core/_memory_range.pxd
- cupy/core/_memory_range.pyx
- cupy/misc/memory_ranges.py
- cupy_setup_build.py
- tests/cupy_tests/core_tests/test_ndarray_ufunc.py
> Copy inputs in ufunc if they share the same memory with outputs

- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump Docker version to v6.4.0

- cupy/__init__.py
> [backport] Ignore warning caused by fastrlock

- cupy/cusparse.py
- tests/cupy_tests/test_cusparse.py
> [backport] Bug: Fix `coosort`

- tests/install_tests/test_build.py
> Fix error in `test_build.py`

- cupy/core/_routines_sorting.pyx
- cupy/cuda/cupy_thrust.cu
- cupy/cusparse.py
- cupy_setup_build.py
- docs/source/reference/interoperability.rst
- examples/finance/black_scholes.py
- examples/finance/monte_carlo.py
- tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
> Fix some typo

- cupy/core/_routines_sorting.pyx
- cupy/cuda/cupy_thrust.cu
- cupy_setup_build.py
- docs/source/reference/interoperability.rst
- examples/finance/black_scholes.py
- examples/finance/monte_carlo.py
- tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
> [backport] Fix some typo

- tests/cupy_tests/cuda_tests/test_memory.py
> [backport] Fix memory pool disabled during tests

- cupyx/__init__.py
- cupyx/fallback_mode/__init__.py
Depends on #2540.
This feature is still under development and may change the behavior in future versions.
> Support `cupyx.fallback_mode` as an experimental feature

- cupy/cuda/cupy_cusolver.h
- cupy/cuda/cusolver.pxd
- cupy/cuda/cusolver.pyx
The purpose of this PR is to make more cuSolverSP APIs available in CuPy.
> Expand coverage of cuSolverSP APIs

- tests/cupy_tests/indexing_tests/test_indexing.py
- tests/cupy_tests/manipulation_tests/test_rearrange.py
> [backport] Fix for NumPy 1.14.x compatibility

- cupy/linalg/decomposition.py
- tests/cupy_tests/linalg_tests/test_decomposition.py
Close #2193. cf. #2468 & #2509.
> Support complex numbers in `cupy.linalg.qr()`

- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump Docker version to v6.5.0

- MANIFEST.in
Make sure the tests are included in `sdist`s.
> Package the tests

- cupy/cuda/compiler.py
- cupy/cuda/cublas.pyx
- cupy/cuda/cudnn.pyx
- cupy/cuda/cufft.pyx
- cupy/cuda/curand.pyx
- cupy/cuda/cusolver.pyx
- cupy/cuda/cusparse.pyx
- cupy/cuda/driver.pyx
- cupy/cuda/memory.pyx
- cupy/cuda/nccl.pyx
- cupy/cuda/nvrtc.pyx
- cupy/cuda/runtime.pyx
- tests/cupy_tests/cuda_tests/test_compiler.py
- tests/cupy_tests/cuda_tests/test_cublas.py
- tests/cupy_tests/cuda_tests/test_cudnn.py
- tests/cupy_tests/cuda_tests/test_cufft.py
- tests/cupy_tests/cuda_tests/test_curand.py
- tests/cupy_tests/cuda_tests/test_cusolver.py
- tests/cupy_tests/cuda_tests/test_cusparse.py
- tests/cupy_tests/cuda_tests/test_driver.py
- tests/cupy_tests/cuda_tests/test_memory.py
- tests/cupy_tests/cuda_tests/test_nccl.py
- tests/cupy_tests/cuda_tests/test_nvrtc.py
- tests/cupy_tests/cuda_tests/test_runtime.pyx
> [backport] Make exceptions picklable

- cupy/cuda/cusparse.pyx
> Remove cuSPARSE APIs dropped in CUDA 10.1 Update 2

- setup.py
> [backport] Fix url to use the home page address

- cupy/core/include/cupy/_cuda/cuda-10.1/cuda_fp16.hpp
> [backport] Import CUDA headers from CUDA 10.1 Update 2 (10.1.243)

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray.py
> Fix `__cuda_array_interface__` data pointer for 0-size arrays

- CODE_OF_CONDUCT.md
> [backport] Update CODE_OF_CONDUCT.md

- docs/source/reference/environment.rst
> [backport] Document more environment variables

- cupy/cuda/cupy_cuda.h
- cupy/cuda/cupy_hip.h
Ref #2560, #2531
Test: https://ci.preferred.jp/cupy.py3.amd/41455/
> Fix ROCm build error

- .pfnci/config.pbtxt
- .pfnci/script.sh
> Add CI configuration for ROCm

- setup.py
* `pytest`: duplicate requirement
* `nose`: no longer needed
* `pytest-timeout`: unnecessary constraints
> Fix invaild requirements

- setup.py
> [backport] Fix invaild requirements

- cupy/cuda/compiler.py
* Decode error messages from hipcc
* Warn users if the environment variable is not set at runtime
> Improve ROCm error handling

- cupy/core/_routines_math.pyx
- cupy/core/_routines_statistics.pyx
- cupy/core/include/cupy/complex.cuh
- cupy/core/include/cupy/complex/arithmetic.h
- cupy/cuda/cub.pxd
- cupy/cuda/cub.pyx
- cupy/cuda/cupy_cub.cu
***UPDATE:*** closes #2634.
cc: @grlee77 @anaruse @kmaehashi
> Fix bugs in CUB

- examples/stream/map_reduce.py
> [backport] Show better performance improvement in `examples/stream/map_reduce.py`

- cupy/core/_routines_manipulation.pyx
- cupy/testing/__init__.py
- cupy/testing/helper.py
- tests/cupy_tests/manipulation_tests/test_shape.py
> Do not allow `reshape` on empty arrays

- cupy/linalg/solve.py
- tests/cupy_tests/linalg_tests/test_solve.py
Closes #2581
Thanks to @YoujinShin
> Fix `pinv` for complex datatypes

- setup.py
> [backport] Add software description to setup.py

- cupy/cuda/cupy_thrust.cu
- cupy_setup_build.py
- docs/source/install_rocm.rst
- install/build.py
> Support thrust with ROCm

- cupy/core/internal.pyx
This PR removes temporary memory.
> Reduce memory allocation in improve get_reduced_dims

- cupy/random/generator.py
- tests/cupy_tests/random_tests/test_sample.py
> [backport] handle tuple with value 0 and return empty array

- .pfnci/config.pbtxt
- .pfnci/hint.pbtxt
- .pfnci/py27and35.Dockerfile
- .pfnci/py37.Dockerfile
- .pfnci/run.sh
- .pfnci/script.sh
As a first step, employ the same test variation as Chainer.
> Add FlexCI configurations

- cupy/lib/__init__.py
> [backport] Fix `AttributeError` of `stride_tricks`

- cupy/lib/stride_tricks.py
> [backport] Fix document format of `as_strided`

- cupy/core/_routines_math.pyx
- cupy/core/_routines_statistics.pyx
- cupy/cuda/cub.pyx
Fix https://github.com/cupy/cupy/pull/2636#issuecomment-553589774.
> Support CUB reduction for F-contiguous arrays

- cupy/random/generator.py
> [backport] Remove insignificant assertion

- .pfnci/config.pbtxt
- .pfnci/hint.pbtxt
- .pfnci/py27and35.Dockerfile
- .pfnci/py37.Dockerfile
- .pfnci/run.sh
- .pfnci/script.sh
> [backport] Add FlexCI configurations

- cupy/creation/matrix.py
- cupy/random/generator.py
- cupyx/scipy/ndimage/filters.py
This PR avoids recreate ElementwiseKernel object.
> Cache ElementwiseKernel object

- cupy/__init__.py
> [backport] Remove `cupy.cupyx`

- .pfnci/py27and35.Dockerfile
> [backport] Fix broken version specification in FlexCI dockerfiles

- MANIFEST.in
> [backport] Package tests in sdist

- cupy/core/_dtype.pyx
This PR is same concept as #2684
> Avoid module level lookup in _dtype

- cupy/core/_kernel.pyx
This PR adds fast path for reduction.
> Improve _reduce_dims

- cupy/core/_kernel.pyx
> Implement `ParameterInfo.__str__`

- cupy/__init__.py
- cupy/_environment.py
- cupy/cuda/__init__.py
> [backport] Support Python 3.8 on Windows

- docker/python2/Dockerfile
- docker/python3/Dockerfile
Previous https://github.com/cupy/cupy/pull/2571
> Bump Docker version to v6.6.0

- .pfnci/py27and35.Dockerfile
- .pfnci/py37.Dockerfile
> Test cuTENSOR v1.0.0

- cupy/testing/helper.py
> [backport] Fix slow import of cupy

- cupy/cuda/memory_hook.pyx
- cupy/cuda/runtime.pyx
- cupy/cuda/stream.pyx
> Avoid using PyThread API

- cupy/core/_routines_indexing.pyx
- cupy/core/core.pyx
- cupy/indexing/generate.py
- cupy/indexing/insert.py
- cupy/manipulation/add_remove.py
- cupy/random/generator.py
- cupy/sorting/search.py
- cupy/statistics/histogram.py
- cupy/statistics/meanvar.py
- cupy/statistics/order.py
> Document device synchronization

- docs/source/reference/scipy_fft.rst
resolves an overlooked comment from the review of #2355
> fix typo in scipy.fft docs

- .pfnci/config.pbtxt
**DO NOT BACKPORT THIS PR TO V7**
> Drop ChainerCV's test in master branch.

- cupyx/scipy/ndimage/filters.py
- tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
> [backport] fix range used in cupyx.scipy.ndimage filter origin check

- .pfnci/py27and35.Dockerfile
- .pfnci/py37.Dockerfile
> [backport] Test cuTENSOR v1.0.0

- cupy/cuda/cub.pyx
This PR adds `nogil` flag to CUB C interface.
> Add nogil to CUB

- tests/cupy_tests/core_tests/test_reduction.py
> Add f-contiguous reduction tests

- cupy/core/include/cupy/complex.cuh
- cupy/core/include/cupy/complex/arithmetic.h
- cupy/core/include/cupy/complex/catrig.h
- cupy/core/include/cupy/complex/catrigf.h
- cupy/core/include/cupy/complex/ccosh.h
- cupy/core/include/cupy/complex/ccoshf.h
- cupy/core/include/cupy/complex/cexp.h
- cupy/core/include/cupy/complex/cexpf.h
- cupy/core/include/cupy/complex/clog.h
- cupy/core/include/cupy/complex/clogf.h
- cupy/core/include/cupy/complex/complex.h
- cupy/core/include/cupy/complex/complex_inl.h
- cupy/core/include/cupy/complex/cpow.h
- cupy/core/include/cupy/complex/cproj.h
- cupy/core/include/cupy/complex/csinh.h
- cupy/core/include/cupy/complex/csinhf.h
- cupy/core/include/cupy/complex/csqrt.h
- cupy/core/include/cupy/complex/csqrtf.h
- cupy/core/include/cupy/complex/ctanh.h
- cupy/core/include/cupy/complex/ctanhf.h
- cupy/core/include/cupy/complex/math_private.h
> [backport] Update thrust::complex headers with a bug fix

- cupy/core/include/cupy/complex/cpow.h
> [backport] Fix compilation error causes when thrust is enabled

- cupy/testing/helper.py
- tests/cupy_tests/creation_tests/test_basic.py
- tests/cupy_tests/math_tests/test_rounding.py
- tests/cupy_tests/sorting_tests/test_search.py
> [backport] Fix decorator usage in tests 

- cupy/core/_kernel.pxd
- cupy/core/_kernel.pyx
- cupy/core/_routines_math.pyx
- cupy/core/reduction.pxi
- tests/cupy_tests/math_tests/test_arithmetic.py
- tests/cupy_tests/statics_tests/test_meanvar.py
> [backport] Fix `true_divide` with dtype argument

- cupy/random/generator.py
- tests/cupy_tests/random_tests/test_generator.py
> [backport] Support 64 bit extent `randint`

- cupy/random/generator.py
- tests/cupy_tests/random_tests/test_generator.py
- tests/cupy_tests/random_tests/test_sample.py
> [backport] Improve compatibility of `random.randint`

- docs/source/reference/scipy_fft.rst
> [backport] fix typo in scipy.fft docs

- tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
> [backport] Test `ifloordiv` with numpy 1.18

- cupy/core/core.pyx
- cupy/cuda/memory.pyx
- tests/cupy_tests/creation_tests/test_from_data.py
> [backport] Avoid looking up null pointers' attributes

- cupy/testing/helper.py
- tests/cupy_tests/manipulation_tests/test_shape.py
- tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
> [backport] Refactor array testing decorators

- cupy/core/_routines_statistics.pyx
Addresses [this comment](https://github.com/cupy/cupy/pull/2860#pullrequestreview-336084886)
> Add missing blank lines

- cupy/testing/helper.py
- tests/cupy_tests/random_tests/test_permutations.py
- tests/cupy_tests/sorting_tests/test_sort.py
- tests/cupy_tests/testing_tests/test_helper.py
> Fix `testing.shaped_random` for shape `()`

- cupy/core/core.pyx
- cupy/core/syncdetect.py
- cupy/cuda/device.pyx
- cupyx/__init__.py
- docs/source/reference/prof.rst
- tests/cupy_tests/core_tests/test_syncdetect.py
> Detect synchronization

- cupy/core/_routines_statistics.pyx
- cupy/core/core.pyx
- cupy/sorting/search.py
- tests/cupy_tests/sorting_tests/test_search.py
> Fix `argmin`/`argmax` `dtype` argument

- cupy/testing/helper.py
- tests/cupy_tests/random_tests/test_permutations.py
- tests/cupy_tests/sorting_tests/test_sort.py
- tests/cupy_tests/testing_tests/test_helper.py
> [backport] Fix `testing.shaped_random` for shape `()`

- cupy/core/_routines_statistics.pyx
- cupy/core/core.pyx
- cupy/sorting/search.py
- tests/cupy_tests/sorting_tests/test_search.py
> [backport] Fix `argmin`/`argmax` `dtype` argument

- cupy/cuda/memory.pxd
- cupy/cuda/memory.pyx
Converts private free functions to instance (or class) methods of relevant classes.
> Readability fix in `memory.pyx`

- cupyx/scipy/ndimage/filters.py
> Fix complex type checks in `_correlate_or_convolve`

- cupyx/time.py
There might be a room to discuss its name.
#2896
> Make `cupyx.time.repeat` experimental

- cupy/core/_kernel.pyx
- tests/cupy_tests/core_tests/test_userkernel.py
> Fix logic to check explicit `size` argument in `ElementwiseKernel`

- .mergify.yml
> [backport] Add Mergify configuration file

- tests/cupy_tests/core_tests/test_userkernel.py
Add tests for https://github.com/cupy/cupy/issues/2908#issuecomment-571973282
> Add tests for size argument with no input

- cupy/core/_kernel.pyx
Using local and global dictionary for fast lookup.
> Improve caching in `ElementwiseKernel`

- cupy/linalg/util.py
- cupyx/_ufunc_config.py
> Sets the default value for `thread_local.linalg` if not defined

- cupy/linalg/util.py
- cupyx/_ufunc_config.py
> [backport] Sets the default value for `thread_local.linalg` if not defined

- cupy/core/core.pxd
- cupy/core/core.pyx
- cupy/core/raw.pxd
- cupy/core/raw.pyx
- cupy/cuda/compiler.py
- cupy/cuda/cupy_cuda.h
- cupy/cuda/driver.pxd
- cupy/cuda/driver.pyx
- cupy/cuda/function.pyx
- tests/cupy_tests/core_tests/test_raw.py
Support `cooperative_groups` in `RawKernel`.
> Support grid synchronization in `RawKernel` and `RawModule`

- docs/source/reference/cuda.rst
> Document `get_allocator` function

- docs/source/install.rst
> [backport] Update cuTENSOR version in docs

- cupy/fft/fft.py
- tests/cupy_tests/fft_tests/test_fft.py
This PR is to avoid test failure on Pascal GPUs with CUDA 10.1U2 or 10.2.
There is an accuracy issue in cuFFT of CUDA 10.1U2 and 10.2 when Pascal or older generation GPU is used. With this PR, some FFT related tests that might hit the issue will be skipped. In addition, a warning will be shown when results of FFT, specifically `irfftn`, could be incorrect due the issue.
This is related to https://github.com/cupy/cupy/issues/2569.
> Skip some tests for irfftn

- cupy/core/_routines_indexing.pyx
- cupy/core/core.pyx
- cupy/indexing/generate.py
- cupy/indexing/insert.py
- cupy/manipulation/add_remove.py
- cupy/random/generator.py
- cupy/sorting/search.py
- cupy/statistics/histogram.py
- cupy/statistics/meanvar.py
- cupy/statistics/order.py
> [backport] Document device synchronization

- docs/source/reference/cuda.rst
> [backport] Document `get_allocator` function

- cupy/fft/fft.py
- tests/cupy_tests/fft_tests/test_fft.py
> [backport] Show warning for cuFFT bug in irfftn

- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump Docker version to v6.7.0

- cupy/core/_kernel.pxd
- cupy/core/_kernel.pyx
- cupy/core/_routines_math.pyx
- tests/cupy_tests/math_tests/test_arithmetic.py
> Disallow boolean subtraction

- cupy/core/syncdetect.py
> Make `cupyx.allow_synchronize` experimental

- cupy/cuda/cub.pyx
Fixes https://github.com/cupy/cupy/issues/2971
> Fix import of `_get_axis`

- cupy/core/__init__.py
- cupy/core/_routines_manipulation.pxd
- cupy/core/_routines_manipulation.pyx
- cupy/manipulation/dims.py
- tests/cupy_tests/manipulation_tests/test_dims.py
Follow numpy/numpy#14051.
Part of #2991.
> Allow multiple axes in `expand_dims`

- cupy/__init__.py
- cupy/core/_kernel.pyx
- cupy/core/core.pyx
- cupy/testing/helper.py
- cupy/testing/random.py
- cupy_setup_build.py
- examples/gemm/sgemm.py
> Remove `__future__` imports

- cupy/cuda/cub.pyx
> [backport] Add nogil to CUB

- cupy/cuda/cub.pyx
> Rename `_op` variable in cub.pyx

- cupy/cuda/nvrtc.pyx
> [backport] Fix empty vector access

- cupy/linalg/eigenvalue.py
> [backport] Fix typo in note

- cupy/cuda/nvrtc.pyx
Fixes #3020 as the `vector::data` return value is undefined for empty vectors
> Check size before accesing empty vectors data ptr

- cupy/testing/helper.py
- cupy/testing/parameterized.py
> Make `testing.parameterize` pdb-friendly

- examples/kmeans/kmeans.py
`numpy.random.choice` is the biggest bottleneck in this example.
With this fix, "GPU" time reduced to about a half in my environment.
> Use `cupy.random` in kmeans example

- cupy/__init__.py
- cupy/core/__init__.py
- cupy/core/_routines_math.pyx
- cupy/core/core.pxd
- cupy/core/core.pyx
- cupy/math/arithmetic.py
- tests/cupy_tests/core_tests/test_ndarray_complex_ops.py
- tests/cupy_tests/math_tests/test_arithmetic.py
- tests/cupy_tests/test_init.py
> Add `cupy.conjugate` and make `cupy.conj` its alias

- cupy/core/_routines_math.pyx
- tests/cupy_tests/math_tests/test_arithmetic.py
- tests/cupy_tests/testing_tests/test_helper.py
> Fix imag for 0-size array

- tests/conftest.py
Similarly to https://github.com/chainer/chainer/pull/8348
`CUPY_CI` is being introduced.
> Print installed packages in pytest

- cupy/core/_routines_math.pyx
- tests/cupy_tests/math_tests/test_arithmetic.py
- tests/cupy_tests/testing_tests/test_helper.py
> [backport] Fix imag for 0-size array

- docs/source/install.rst
> Add NumPy 1.18 to installation guide

- cupy/cuda/_environment.py
- cupy/cuda/compiler.py
> [backport] Fix nvcc command lookup

- cupy/core/core.pyx
- cupy/core/include/cupy/_cuda/cuda-10.2/cuda_fp16.h
- cupy/core/include/cupy/_cuda/cuda-10.2/cuda_fp16.hpp
I was working to build `cupy` for `linux-ppc64le` with cudatoolkit `10.2` and got these kind of errors with multiple tests when running certain tests -
```python
______________________________ TestNdarrayDeepCopy_param_2.test_deepcopy ______________________________
self = <cupy.testing.parameterized.TestNdarrayDeepCopy_param_2 testMethod=test_deepcopy>
def test_deepcopy(self):
arr = core.ndarray(self.shape)
>       arr2 = copy.deepcopy(arr)
core_tests/test_ndarray.py:140:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../../conda3/envs/cupy_py36/lib/python3.6/copy.py:161: in deepcopy
y = copier(memo)
cupy/core/core.pyx:1084: in cupy.core.core.ndarray.__deepcopy__
???
cupy/core/core.pyx:1085: in …
```
> Add CUDA 10.2 support

- cupy/__init__.py
- setup.py
> Do not let Python 2 users build CuPy v7+

- setup.py
> [backport] Fix an issue that cuComplex_bridge.h is not installed

- setup.py
> [backport] Do not let Python 2 users build CuPy v7+

- .pfnci/script.sh
- Update v6 to v7
- Output error message in get_base_branch()
- Remove 'run' in get_base_branch() as it should not be skipped
> Some fixes to `.pfnci/script.sh`

- cupy/core/_kernel.pyx
- cupy/core/_routines_math.pyx
- tests/cupy_tests/core_tests/test_ndarray_unary_op.py
- tests/cupy_tests/math_tests/test_arithmetic.py
> Disallow boolean `negative`

- .travis.yml
- appveyor.yml
> Set CUPY_CI environment variable in Travis CI and AppVeyor

- .travis.yml
- appveyor.yml
> [backport] Set CUPY_CI environment variable in Travis CI and AppVeyor

- docker/python3/Dockerfile
> Bump version in Dockerfile to v7.2.0

- README.md
- docs/source/install.rst
> [backport] Add cupy-cuda102

- cupy/cuda/compiler.py
- install/build.py
> Remove custom tempdir context manager

- cupy/cuda/__init__.py
- cupy/cuda/memory.pyx
- docs/source/reference/cuda.rst
- tests/cupy_tests/cuda_tests/test_memory.py
> Import `using_allocator` in `cupy.cuda`

- .pfnci/script.sh
> [backport] Some fixes to `.pfnci/script.sh`

- cupy/cuda/memory.pyx
- tests/cupy_tests/cuda_tests/test_memory.py
Fix #3008 .
This PR the memory pool to properly decrement its total bytes when free memory blocks are released back.
> Properly decrement total bytes in memory pool

- cupy/cuda/__init__.py
- cupy/cuda/memory.pyx
- docs/source/reference/cuda.rst
- tests/cupy_tests/cuda_tests/test_memory.py
> [backport] Import `using_allocator` in `cupy.cuda`

- cupy/cuda/cudnn.pxd
- cupy/cuda/cudnn.pyx
Modified `size_t` with `intptr_t` for cuDNN as a part of #2716
> Use `intptr_t` for cuDNN handles

- examples/gmm/gmm.py
> [backport] Fix GMM example for matplotlib 3

- tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
These two tests cannot pass in my environment due to small numerical errors.
> Fix atol of fft tests

- tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
> [backport] Fix atol of fft tests

- cupy/random/generator.py
> [backport] Use Python scalar as random seed

- cupy/cuda/memory.pyx
- tests/cupy_tests/cuda_tests/test_memory.py
> [backport] Properly decrement total bytes in memory pool

- tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
- tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_base.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
> Rewrite tests not to use `numpy_cupy_raises` cupyx.* tests

- cupy/__init__.py
- cupy/indexing/generate.py
- docs/source/reference/indexing.rst
- tests/cupy_tests/indexing_tests/test_generate.py
This PR adds `cupy.ravel_multi_index`
> add ravel_multi_index

- cupy/random/_kernels.py
> [backport] Add copyright notice for Random Kit

- cupy/__init__.py
- cupy/manipulation/kind.py
- docs/source/reference/manipulation.rst
- tests/cupy_tests/manipulation_tests/test_kind.py
I have added the implmentation and some tests and also added the documentation. Please review and suggest changes if any.
> Feature - implementation of np.require in Cupy

- cupy/__init__.py
- cupy/indexing/indexing.py
- docs/source/reference/indexing.rst
- tests/cupy_tests/indexing_tests/test_indexing.py
This PR is for the feature request Issue #2223
> Add `extract`

- cupy/random/generator.py
> use `time.process_time` instead of `time.clock`

- cupy/linalg/decomposition.py
- tests/cupy_tests/linalg_tests/test_decomposition.py
> add support for 0 sized matrices in svd

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
> [backport] Fix condition to use slice copy in ndarray.__setitem__

- cupy/cuda/cub.pyx
Closes https://github.com/cupy/cupy/issues/3092
Closes https://github.com/cupy/cupy/issues/3110
cc @leofang
> Readd `ndarray` type to `y`

- docs/source/reference/ndimage.rst
> [backport] Document `convolve` and `correlate`

- cupyx/scipy/sparse/dia.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
Fixes https://github.com/cupy/cupy/issues/3158
> Allow `dia_matrix` creation from SciPy equivalent

- cupy/cuda/stream.pyx
Continuation of #2809 
Closes #3173
> Fix `Event.__del__` behavior on shutdown`

- cupy/cuda/stream.pyx
> [backport] Fix `Event.__del__` behavior on shutdown`

- cupy/core/_routines_sorting.pyx
- tests/cupy_tests/sorting_tests/test_sort.py
> Remove some xfails in sorting tests

- cupy/__init__.py
- cupy/indexing/indexing.py
- docs/source/reference/indexing.rst
- tests/cupy_tests/indexing_tests/test_indexing.py
This PR implements the function cupy.select
> Add `cupy.select`

- tests/cupy_tests/core_tests/test_reduction.py
> [backport] Add the missing initialization value in the reduction test

- docs/source/install.rst
Close #3006. 
@jakirkham, two quick questions for you: Do you know who manages [the `cupy` package in the `rapidsai` channel](https://anaconda.org/rapidsai/cupy), and whether `cupy` from `conda-forge` is compatible with other GPU packages from `rapidsai`? Thanks.
> Update installation guide for conda-forge

- cupyx/scipy/ndimage/__init__.py
- cupyx/scipy/ndimage/measurements.py
- tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
> Add cupyx.scipy.ndimage.label

- cupy/core/_kernel.pxd
- cupy/core/_kernel.pyx
- cupy/core/_reduction.pyx
Please merge #2696 before this PR.
> Reduce list and tuple creation in _kernel and reduction

- docs/source/install.rst
> [backport] Update installation guide for conda-forge

- cupy/cuda/cupy_hip.h
Please merge #3203 before this PR.
> HIP blas wich complex

- docs/source/reference/difference.rst
Made a few small spelling fixes in `difference.rst`.
> Small typo/spelling fixes

- tests/cupy_tests/creation_tests/test_basic.py
- tests/cupy_tests/creation_tests/test_matrix.py
- tests/cupy_tests/creation_tests/test_ranges.py
- tests/cupy_tests/linalg_tests/test_decomposition.py
- tests/cupy_tests/linalg_tests/test_einsum.py
- tests/cupy_tests/linalg_tests/test_norms.py
- tests/cupy_tests/linalg_tests/test_product.py
- tests/cupy_tests/linalg_tests/test_solve.py
- tests/cupy_tests/math_tests/test_matmul.py
- tests/cupy_tests/math_tests/test_misc.py
- tests/cupy_tests/math_tests/test_rounding.py
- tests/cupy_tests/math_tests/test_sumprod.py
- tests/cupy_tests/padding_tests/test_pad.py
- tests/cupy_tests/sorting_tests/test_sort.py
- tests/cupy_tests/statics_tests/test_correlation.py
- tests/cupy_tests/statics_tests/test_histogram.py
- tests/cupy_tests/statics_tests/test_order.py
> Rewrite tests not use `numpy_cupy_raises`

- docs/source/reference/difference.rst
> [backport] Small typo/spelling fixes

- cupy/cuda/cupy_cusolver.h
- cupy/cuda/cusolver.pyx
- cupy/cusolver.py
- tests/cupy_tests/test_cusolver.py
Rework of #2337 on #3192
- The second commit is optional.
- The third commit can be done in a separate PR.
> Support cusolverDn<t>gesvdjBatched

- cupy/linalg/norms.py
This PR reduces memory consumption.
> Improve `norm`

- cupy/core/_kernel.pxd
- cupy/core/_kernel.pyx
- cupy/core/_reduction.pxd
- cupy/core/_reduction.pyx
- cupy/core/_scalar.pxd
- cupy/core/_scalar.pyx
- cupy/cuda/function.pxd
- cupy/cuda/function.pyx
This reverts commit 3d858104736e93aabc0a215c3d1d1add242095a0.
We do it to investigate the source of the execution time increase
> Revert "Merge elementwise"

- docker/python3/Dockerfile
> Bump version in Dockerfile to v7.4.0

- cupy/fft/fft.py
- cupyx/scipy/fft/fft.py
- cupyx/scipy/fftpack/fft.py
- tests/cupy_tests/fft_tests/test_fft.py
- tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
- tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py
Address #3263. Follow up of #3102.
> Enable getting R2C/C2R FFT plans from `get_fft_plan()`

- cupyx/scipy/sparse/data.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
> Add mean for sparse matrices

- cupy/core/_routines_indexing.pyx
- tests/cupy_tests/indexing_tests/test_insert.py
> [backport] Fix `put` when using scalars

- cupy/cuda/cupy_thrust.cu
- cupy/cuda/thrust.pyx
- tests/cupy_tests/sorting_tests/test_sort.py
> [backport] Support sorting complex arrays

- README.md
Apparently CuPy is an Nvidia product, so we should make things a bit clear.
😅
> Add PFN to the README

- cupy/cuda/nvrtc.pyx
> [backport] Fix byte buffer handling to support PyPy

- README.md
> [backport] Add PFN to the README

- cupy/indexing/iterate.py
- tests/cupy_tests/indexing_tests/test_iterate.py
Follows #3250 .
This PR implements `flatiter.__len__()` special method.
https://github.com/takagi/cupy/compare/flatiter-base...flatiter-len
> Implement `flatiter.__len__()` special method.

- cupy/linalg/solve.py
> [backport] Assign a workpace to `ormqr` functions in `_solve`

- cupy/core/_routines_sorting.pyx
- tests/cupy_tests/sorting_tests/test_sort.py
> [backport] Remove some xfails in sorting tests

- cupy/core/_reduction.pyx
> Fix wrong parameter names in kernel launch optimizers

- cupy/cuda/cupy_cusparse.h
- cupy/cuda/cusparse.pxd
- cupy/cuda/cusparse.pyx
- cupy/cusparse.py
- cupyx/scipy/sparse/coo.py
- tests/cupy_tests/test_cusparse.py
This is a kind of re-PR of https://github.com/cupy/cupy/pull/3129 that fixes a build issue on Windows with CUDA 10.1/10.2.
> Support cuSparse generic API

- cupy/core/_optimize_config.pyx
- cupy/core/_reduction.pyx
- tests/cupyx_tests/test_optimize.py
Tests for #2731.
These tests will be skipped in our CI currently.
> Add tests for optimizer for kernel launch parameters

- cupy/core/_optimize_config.pxd
- cupy/core/_optimize_config.pyx
- cupy/core/_reduction.pyx
- tests/cupyx_tests/test_optimize.py
> Support OptimizeContext serialization

- docker/python3/Dockerfile
> Bump Dockerfile to 8.0.0b3

- docker/python3/Dockerfile
> Bump Dockerfile to v7.5.0

- cupy/__init__.py
- cupy/misc/__init__.py
- cupy/misc/who.py
- docs/source/reference/index.rst
- docs/source/reference/misc.rst
- tests/cupy_tests/misc_tests/test_who.py
Take over #3224
Added test and minor fixes in the code.
> Add `cupy.who`

- cupy/cuda/compiler.py
- tests/cupy_tests/cuda_tests/test_compiler.py
> [backport] Get arch per device and support CUDA 9.2+ 

- cupy/core/_dtype.pyx
- cupy/core/_routines_statistics.pyx
> [backport] Fix `_count_non_nan` datatype for windows

- cupy/linalg/decomposition.py
This PR follows https://github.com/cupy/cupy/pull/3347#pullrequestreview-414350737 to remove unnecessary comparison in `cupy.linalg.svd` .
> Remove unnecessary comparison in `cupy.linalg.svd`

- tests/cupyx_tests/fallback_mode_tests/test_notifications.py
> Add `__init__.py` to allow importing test packages

- cupyx/optimizing/_optimize.py
Address https://github.com/cupy/cupy/pull/3244#discussion_r435475481.
> Support `ignore_error` in kernel optimization

- setup.py
> [backport] Fix sphinx version for travis

- cupy/_environment.py
Address https://github.com/cupy/cupy/pull/3145#discussion_r436237306.
> Fix initial values in `cupy._environment`

- cupy/cuda/stream.pyx
- tests/cupy_tests/cuda_tests/test_stream.py
> [backport] Properly reset current stream in case null stream is destroyed

- setup.py
> [backport] Use `find_packages` in `setup.py`

- docs/source/reference/creation.rst
> [backport] Document `cupy.fromfile`

- cupy/core/_routines_math.pyx
- tests/cupy_tests/math_tests/test_arithmetic.py
```py
>>> import numpy, cupy
>>> numpy.power(0j, 0j)
(1+0j)
>>> cupy.power(0j, 0j)
array(nan+nanj)
```
> Fix `cupy.power(0j, 0j)`

- cupy/testing/parameterized.py
> Fix `TypeError` in parameterize test catching `CUDADriverError`

- cupy/core/_cub_reduction.pxd
- cupy/core/_cub_reduction.pyx
- cupy/core/_reduction.pxd
- cupy/core/_reduction.pyx
- cupy_setup_build.py
Follows #3244.
Moved the implementations to `_cub_reduction.pyx`
> Refactor CUB-backed `_SimpleReductionKernel`

- cupy/core/core.pyx
> Fix docstring of `tofile()`

- setup.py
> [backport] Add optuna and remove theano for doctest requirement

- cupy/core/core.pyx
Reduces unnecessary indentation by early returns.
> Fix array() for readability

- cupy/cuda/nvrtc.pyx
As per the discussion in #3225 
Can be closed if not necessary
> Align vector access with #3020 #3022

- setup.py
- tests/cupy_tests/core_tests/fusion_tests/test_function.py
- tests/cupy_tests/cuda_tests/test_compiler.py
- tests/cupy_tests/cuda_tests/test_profile.py
- tests/cupy_tests/prof_tests/test_range.py
- tests/cupy_tests/random_tests/test_sample.py
- tests/cupy_tests/test_init.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
- tests/cupyx_tests/test_optimize.py
- tests/cupyx_tests/test_runtime.py
- tests/cupyx_tests/test_time.py
> Use `unittest.mock`

- docker/python3/Dockerfile
> Bump version in Dockerfile to 8.0.0b4

- docker/python3/Dockerfile
> Bump version in Dockerfile to 7.6.0

- cupy/core/_cub_reduction.pyx
- cupy/core/_reduction.pyx
- cupy/cuda/function.pyx
Close #2522. 
Related: #2449, #2518, https://github.com/cupy/cupy/pull/2731#issuecomment-633414262.
> [MNT] Add short comments for the internals

- tests/cupy_tests/core_tests/fusion_tests/test_reduction.py
Fix Jenkins timeout.
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/1420/
> Fix to set `testing.slow` correctly

- cupy/cuda/cupy_thrust.cu
- cupy/cuda/cupy_thrust.h
- cupy/cuda/thrust.pyx
- cupy/sorting/sort.py
- tests/cupy_tests/sorting_tests/test_sort.py
> [backport] Code fix + bug fix for `cupy.cuda.thrust`

- cupy/indexing/iterate.py
- tests/cupy_tests/indexing_tests/test_iterate.py
This PR implements `flatiter.__iter__()` special method.
> Implement `flatiter.__iter__()`

- cupy/core/core.pyx
- cupy/core/internal.pyx
- cupy/creation/basic.py
- cupy/indexing/generate.py
- cupyx/scipy/sparse/csc.py
- cupyx/scipy/sparse/csr.py
- tests/cupy_tests/core_tests/test_ndarray.py
- tests/cupy_tests/creation_tests/test_basic.py
- tests/cupy_tests/indexing_tests/test_generate.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Fixed to follow the NumPy 1.19 specification.
> Fix to raise` ValueError` for invalid `order`

- README.md
Add link to our Twitter account: https://twitter.com/CuPy_Team
> Add link to twitter account

- cupy/core/_routines_indexing.pyx
This PR is a small improvement.
> Improve _prepare_mask_indexing_single

- cupy/core/_routines_indexing.pyx
- cupy/core/_routines_math.pyx
This PR reduces CUDA kernel launch count.
> Improve scan operation

- cupy/statistics/order.py
- tests/cupy_tests/statics_tests/test_order.py
> Fix `cupy.percentile` type assignment in `asarray`

- cupyx/scipy/fft/__init__.py
- cupyx/scipy/fft/_helper.py
- docs/source/reference/scipy_fft.rst
- tests/cupyx_tests/scipy_tests/fft_tests/test_helper.py
Ready for #3560.
cc: @grlee77 and @leofang
> Add `cupyx.scipy.fft.next_fast_len`

- cupy/lib/polynomial.pyx
- tests/cupy_tests/lib_tests/test_polynomial.py
This PR implements lazy evaluation for poly1d coefficients
> Reduce device synchronization in `poly1d` instantiation

- cupy/core/_kernel.pyx
- cupy/core/core.pyx
- Fix `_init_fast`
- Fix `_reduced_view_core`
> Fix small performance issue

- cupy/core/_routines_indexing.pyx
- cupy/core/carray.pxi
- cupy/cuda/cupy_nccl.h
> [backport] Suppress compile warnings

- setup.py
> [backport] Update style checker version for Python 3.7

- docs/source/reference/environment.rst
https://github.com/cupy/cupy/pull/3592#issuecomment-657331813
> Update documentation of `CUPY_ACCELERATORS`

- docs/source/reference/ndimage.rst
Hi @takagi, following #1915 , this is a new PR
> add piece of sample code for image resizing

- cupy/core/core.pyx
- tests/cupy_tests/creation_tests/test_from_data.py
> Fix array creation for ndarray list of arrays of different dtypes

- cupy/cuda/cufft.pyx
- cupy/fft/fft.py
- tests/cupy_tests/fft_tests/test_fft.py
> Support 0-size ndarray and fix possible error in __del__ at fft

- cupy/math/misc.py
- tests/cupy_tests/math_tests/test_misc.py
- tests/cupy_tests/statics_tests/test_correlation.py
Follow-up of https://github.com/cupy/cupy/pull/3560#issuecomment-656301909. Tests passed locally.
> Reuse FFT plan for convolve/correlate

- cupy/core/_kernel.pyx
- cupy/core/_reduction.pxd
- cupy/core/_reduction.pyx
- cupy/core/raw.pxd
- cupy/core/raw.pyx
> Add `__name__` to custom kernels

- tests/cupy_tests/testing_tests/test_helper.py
> [backport] Fix negative value test in test_helper

- README.md
> [backport] Add link to twitter account

- cupyx/scipy/sparse/compressed.py
- cupyx/scipy/sparse/coo.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
Follow up of https://github.com/cupy/cupy/pull/3620#issuecomment-659935352. 
~~TODO: I wanna make sure only coo is impacted.~~
> Add a warning for `sum_duplicates`

- .github/CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- README.md
- cupy/__init__.py
- cupy/core/core.pyx
- cupy_setup_build.py
- setup.py
> [backport] Update url and email

- cupyx/scipy/sparse/coo.py
> [backport] Change sorting order of COO sparse matrix for cuSPARSE

- cupyx/scipy/sparse/coo.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
Backport of #3624
Blocked by #3623
> [backport] Add a warning for `sum_duplicates`

- cupyx/scipy/sparse/csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
This PR is to support `csr_matrix.multiply`.
See https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.multiply.html
> Support CSR matrix multiply

- cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.h
- cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.hpp
Headers imported in #3405 was CUDA version 11.0.1 (RC).
Update to the latest ones.
> Update CUDA 11.0 FP16 header to production release version (11.0.2)

- cupy/random/generator.py
- docs/source/reference/environment.rst
- tests/cupy_tests/random_tests/test_generator.py
> Remove CHAINER_SEED

- README.md
- cupy/cuda/compiler.py
- cupy_setup_build.py
- docs/source/install.rst
- docs/source/upgrade.rst
- install/build.py
- tests/cupy_tests/cuda_tests/test_compiler.py
> Drop support for CUDA 8.0 and 9.1

- cupy/__init__.py
> [backport] MAINT: Use builtins directly

- cupy/cuda/cupy_cusparse.h
- cupy/cuda/cusparse.pxd
- cupy/cuda/cusparse.pyx
- cupy/cusparse.py
- tests/cupy_tests/test_cusparse.py
> [backport] Support cusparse<t>csrgeam2 and cusparse<t>csrgemm2

- cupy/core/core.pyx
- tests/cupy_tests/creation_tests/test_from_data.py
> [backport] Fix array creation for ndarray list of arrays of different dtypes

- cupyx/scipy/sparse/data.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Merge #3638 first.
This PR fixes the return shapes of sparse argmin/argmax.
> Fix sparse argmin/argmax return shape

- docs/source/conf.py
- docs/source/contribution.rst
- docs/source/install.rst
- docs/source/install_rocm.rst
- docs/source/tutorial/basic.rst
- docs/source/upgrade.rst
> Remove Chainer related docs

- docker/python3/Dockerfile
> Bump Dockerfile version to v8.0.0b5

- cupy/cusolver.py
- cupy/cusparse.py
(this is not a release blocker as this is "should not happen" route)
> Fix broken message format

- cupy/cusparse.py
> [backport] Fix broken message format

- cupy/cuda/cupy_cusparse.h
- cupy/cuda/cusparse.pxd
- cupy/cuda/cusparse.pyx
- cupy/cusparse.py
- tests/cupy_tests/test_cusparse.py
> [backport] Support cuSparse generic API

- tests/cupy_tests/core_tests/test_raw.py
This PR is a code-fix of a test to use `mock.patch` to `cupy.cuda.compiler.*` instead of mutation of `os.environ`.
> Avoid mutation of `os.environ`

- docker/python3/Dockerfile
- docs/source/upgrade.rst
> Bump version in Docker images

- cupy/creation/basic.py
- cupy/creation/from_data.py
- cupy/creation/matrix.py
- cupy/creation/ranges.py
> [backport] Correct format of docstrings in creation routines

- cupyx/scipy/sparse/csr.py
> [backport] Fix sparse matrix related test failures on CUDA11

- cupy/testing/parameterized.py
- tests/cupy_tests/fft_tests/test_fft.py
Close #3757. See https://github.com/cupy/cupy/issues/3757#issuecomment-673184478 for the trigger condition. 
cc: @kmaehashi @pentschev @anaruse @maxpkatz
> Fix CUDA 11 multi-GPU FFT bug

- tests/cupy_tests/test_cudnn.py
> Temporary fixes for cudnn v8

- tests/cupy_tests/core_tests/fusion_tests/test_kernel_cache.py
- tests/cupy_tests/core_tests/fusion_tests/test_optimization.py
- tests/cupy_tests/core_tests/test_raw.py
> More on using `unittest.mock`

- tests/cupy_tests/test_cudnn.py
> [backport] Temporary fixes for cudnn v8

- cupy/cudnn.pyx
- tests/cupy_tests/test_cudnn.py
> [backport] Improve cudnn performance when using deterministic mode

- cupy/cusparse.py
> [backport] Fix error message broken

- cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.h
- cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.hpp
> [backport] Update CUDA 11.0 FP16 header to production release version (11.0.2)

- docs/source/install.rst
> [v7] Update requirements for CuPy v7.8.0

- docs/source/install.rst
> [v7] Install doc: source devtoolset needed in CentOS

- setup.py
* Add Python 3.8
* Remove macOS
> Update classifiers in `setup.py`

- docker/python3/Dockerfile
Previous: https://github.com/cupy/cupy/pull/3693
> Bump Dockerfile version to v7.8.0

- cupyx/scipy/linalg/solve_triangular.py
https://docs.cupy.dev/en/stable/reference/generated/cupyx.scipy.linalg.solve_triangular.html
> Fix a broken document

- cupy/polynomial/polyutils.py
- docs/source/reference/polynomials.rst
- tests/cupy_tests/polynomial_tests/test_polyutils.py
This PR implements `cupy.polynomial.polyutils.trimcoef`
> Add `trimcoef`

- docker/python3/Dockerfile
> Install scipy and optuna to Docker image

- cupy/fft/fft.py
- cupyx/scipy/fft/fft.py
- cupyx/scipy/fftpack/fft.py
- tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
> Copy input by default for C2R transform

- docs/source/install.rst
Blocked by https://github.com/chainer/chainer-test/pull/599
> Support Optuna v2 (install docs)

- cupy/core/_optimize_config.pxd
- cupy/core/_optimize_config.pyx
- cupyx/optimizing/_optimize.py
- tests/cupyx_tests/test_optimize.py
> Add `path` and `readonly` options to `cupyx.optimizing.optimize`

- cupy/_environment.py
- cupy_setup_build.py
Depends on #3880.
Add option to add files needed for library preloading.
> Add option to include wheel metadata

- docker/python3/Dockerfile
> Bump Dockerfile version to v8.0.0rc1

- .pfnci/script.sh
This fix FlexCI failing for v8 branch.
> Add v8 to list of known branch in FlexCI script

- .pfnci/script.sh
> [backport] Add v8 to list of known branch in FlexCI script

- cupy/statistics/histogram.py
- tests/cupy_tests/statics_tests/test_histogram.py
> Support list bins with histogram

- cupy/cusparse.py
> [backport] Fix `csr2csc` for zero-size matrix

- cupyx/scipy/sparse/_index.py
- cupyx/scipy/sparse/compressed.py
> [backport] Refactor CSR sparse matrix row fancy indexing

- cupy/random/_generator.py
Discovered during review of #3282
> Fix wrong curand enum names

- cupyx/scipy/sparse/_index.py
- cupyx/scipy/sparse/compressed.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
Fix `_minor_slice` and enhance test coverage.
> Fix `_compressed_sparse_matrix._minor_slice` for step > 1 case

- tests/cupyx_tests/fallback_mode_tests/test_notifications.py
> Fix side effects in some tests

- cupyx/scipy/sparse/_index.py
- cupyx/scipy/sparse/compressed.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
> [backport] Fix `_compressed_sparse_matrix._minor_slice` for step > 1 case

- tests/cupyx_tests/fallback_mode_tests/test_notifications.py
> [backport] Fix side effects in some tests

- tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
> [backport] Fix some test to check compatibility with scipy's behavior

- cupyx/scipy/sparse/csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
> [backport] Fix `csr_matrix._get_intXslice` for step < 0 case

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
> [backport] Handle transfer to cupy view

- cupyx/scipy/sparse/csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
> [backport] Support sparse pointwise division by vectors or matrices

- cupyx/scipy/sparse/csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
> [backport] Support sparse pointwise maximum and minimum

- cupyx/time.py
Rel #3420.
This PR hides private names in `cupyx.time` submodule.
> Hide private names in `cupyx.time`

- tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
> Refactor sparse indexing tests

- cupy/testing/__init__.py
- cupy/testing/helper.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
> [backport] Add `cupy.testing.shaped_sparse_random`

- tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
> [backport] Refactor sparse indexing tests

- cupy/core/__init__.py
- cupy/core/core.pyx
- cupy/cutensor.pyx
- cupy_backends/cuda/libs/cutensor.pxd
- tests/cupy_tests/test_cutensor.py
> [backport] Add cuTENSOR 1.2 support

- cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.hpp
> [backport] Update FP16 header to CUDA 11.0 Update 1 (11.0.3)

- cupyx/time.py
> [backport] Hide private names in `cupyx.time`

- cupyx/scipy/sparse/_index.py
- cupyx/scipy/sparse/compressed.py
- cupyx/scipy/sparse/csc.py
- cupyx/scipy/sparse/csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
> Fix `sparse.__getitem__` not to return view of input

- cupyx/scipy/sparse/_index.py
- cupyx/scipy/sparse/compressed.py
- cupyx/scipy/sparse/csc.py
- cupyx/scipy/sparse/csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
> [backport] Fix `sparse.__getitem__` not to return view of input

- cupyx/scipy/ndimage/filters.py
- cupyx/scipy/signal/signaltools.py
- docs/source/reference/ndimage.rst
- docs/source/reference/scipy.rst
- docs/source/reference/scipy_linalg.rst
- docs/source/reference/signal.rst
- docs/source/reference/special.rst
This PR brings the `cupyx.scipy.ndimage` documentation up to date with current master.
**edit**: I have added additional updates to the `cupyx.scipy` API docs as well
> DOC: update cupyx.scipy API documentation

- cupyx/scipy/ndimage/filters.py
- cupyx/scipy/signal/signaltools.py
- docs/source/reference/ndimage.rst
- docs/source/reference/scipy.rst
- docs/source/reference/scipy_linalg.rst
- docs/source/reference/signal.rst
- docs/source/reference/special.rst
> [backport] DOC: update cupyx.scipy API documentation

- cupyx/scipy/sparse/compressed.py
- cupyx/scipy/sparse/csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Closes https://github.com/cupy/cupy/issues/3831.
> Add sparse pointwise equality & inequality functions

- cupy/cusparse.py
Rel #3420.
This PR hides private names in `cupy.cusparse` submodule.
> Hide private names in `cupy.cusparse`

- cupyx/scipy/sparse/_index.py
- cupyx/scipy/sparse/compressed.py
> [backport] Improve cupyx.scipy.sparse int x int indexing

- cupyx/scipy/sparse/compressed.py
- cupyx/scipy/sparse/csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
> [backport] Add sparse pointwise equality & inequality functions

- cupyx/scipy/linalg/__init__.py
- cupyx/scipy/linalg/decomp_lu.py
- docs/source/reference/scipy_linalg.rst
- tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
Closes https://github.com/cupy/cupy/issues/3483
~~This PR also adds complex dtype support to `cupyx.scipy.linalg.lu_factor` and `cupyx.scipy.linalg.lu_solve`~~
> Add `cupyx.scipy.linalg.lu`

- cupy/cusparse.py
> [backport] Hide private names in `cupy.cusparse`

- cupy/cuda/cufft.pyx
- cupy/fft/_cache.pyx
- cupy/fft/config.py
- cupy/fft/fft.py
- cupy_setup_build.py
- cupyx/scipy/fftpack/_fft.py
- docs/source/reference/fft.rst
- tests/cupy_tests/fft_tests/test_cache.py
> [backport] Add a cuFFT plan cache

- cupy/cuda/compiler.py
> [backport] Avoid using CUlinkState unless absolutely necessary

- codecov.yml
> [backport] Disable github checks annotations of Codecov

- cupy/cudnn.pyx
Rel #3420.
This PR hides private names in `cupy.cudnn` submodule.
> Hide private names in `cupy.cudnn`

- cupyx/tools/install_library.py
> [backport] Bump cuDNN version to v8.0.3

- cupy/cuda/memory.pyx
> [backport] Fix managed memory leak

- tests/cupy_tests/test_ndim.py
> [backport] Fix `cupy.ndim` test style

- cupy_backends/cuda/libs/cutensor.pyx
> Use `__dealloc__` instead of `__del__` for cdef class

- cupyx/scipy/ndimage/morphology.py
https://github.com/cupy/cupy/issues/4021#issuecomment-700597849
> Fix typo in `_binary_erosion`

- cupy/cudnn.pyx
> [backport] Hide private names in `cupy.cudnn`

- cupyx/scipy/sparse/linalg/__init__.py
- cupyx/scipy/sparse/linalg/_norm.py
- docs/source/reference/sparse.rst
- tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
> [backport] Add `sparse.linalg.norm`

- docker/python3/Dockerfile
> [v8] Bump Docker version to v8.0.0

- cupy_setup_build.py
> [backport] Add `CUDA_VERSION` define for Cython compilation

- cupy/core/core.pyx
- tests/cupy_tests/math_tests/test_matmul.py
> [backport] Add a kernel for integer GEMM

- cupyx/tools/install_library.py
- tests/cupyx_tests/tools_tests/test_install_library.py
> [backport] Bump cuDNN to v8.0.4

- cupy/core/_cub_reduction.pyx
- cupy/core/_reduction.pyx
- cupy/core/internal.pyx
- cupy/cuda/cub.pxd
- cupy/cuda/cub.pyx
- cupy/cutensor.pyx
- tests/cupy_tests/core_tests/test_ndarray_reduction.py
- tests/cupy_tests/math_tests/test_sumprod.py
> [backport] Fix potential segfault when reduction axis is empty

- README.md
- docs/source/index.rst
- setup.py
> [backport] Update README and docs for unified tagline

- cupy/core/include/cupy/complex/complex.h
- cupy/core/include/cupy/complex/complex_inl.h
- cupy/core/include/cupy/type_dispatcher.cuh
- cupy/cuda/__init__.py
- cupy/cuda/common.pxd
- cupy/cuda/common.pyx
- cupy/cuda/cupy_thrust.cu
- cupy/cuda/device.pyx
- cupy/cuda/memory.pyx
- cupy/cuda/stream.pyx
- cupy_backends/cuda/api/runtime.pyx
- tests/cupy_tests/core_tests/test_array_function.py
- tests/cupy_tests/cuda_tests/test_compiler.py
- tests/cupy_tests/cuda_tests/test_driver.py
- tests/cupy_tests/cuda_tests/test_memory.py
- tests/cupy_tests/cuda_tests/test_stream.py
- tests/cupy_tests/test_init.py
> [backport] ROCm: Fix bugs and test suites to make ROCm/HIP happy - Part 2

- cupy/testing/__init__.py
- cupy/testing/helper.py
- tests/cupy_tests/testing_tests/test_helper.py
Original implementation by @beam2d in https://github.com/chainer/chainer/pull/8077
> Add `generate_matrix` to `cupy.testing`

- cupy_backends/cuda/libs/cusolver.pxd
I think they are not strictly needed but just added them for completeness
> Add `*svdjBatched` prototypes

- cupy/cusolver.py
> [backport] Hide private names in `cupy.cusolver`

- cupyx/scipy/sparse/base.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Closes https://github.com/cupy/cupy/issues/4072
> Add @ operator support to cupyx.scipy.sparse

- cupy/cuda/device.pyx
- cupy/cuda/memory.pyx
- tests/cupy_tests/cuda_tests/test_device.py
> Workaround cudaPointerGetAttributes error in CUDA 10.2+

- cupy/_math/sumprod.py
- cupy/_util.pyx
- cupy/core/_fusion_trace.pyx
- cupy/core/_routines_math.pyx
- cupy/core/internal.pxd
- cupy/core/internal.pyx
- cupy/linalg/product.py
- cupy/manipulation/rearrange.py
- cupyx/scipy/ndimage/_filters_core.py
- cupyx/scipy/ndimage/filters.py
- cupyx/scipy/ndimage/fourier.py
> [backport] Move `_normalize_axis_index` to `cupy/core/internal.pyx`

- cupy/testing/helper.py
- tests/cupy_tests/core_tests/test_ndarray_reduction.py
Added an option and made code-fix.
> Add `order` option in `cupy.testing.shaped_random`

- cupy/cutensor.pyx
> [backport] Add work-around for issue in cutensorReduction of cuTENSOR 1.2.1

- cupy_backends/cuda/api/runtime.pxd
- cupy_backends/cuda/api/runtime.pyx
- cupy_backends/cuda/cupy_cuda.h
- cupy_backends/cuda/cupy_cuda_common.h
- cupy_backends/cuda/cupy_hip.h
- cupy_backends/cuda/cupy_hip_common.h
> [backport] Add `cudaGetDeviceProperties`

- cupyx/_runtime.py
> [backport] Show numpy and scipy versions in `show_config`

- cupy/__init__.py
- cupy/manipulation/add_remove.py
- docs/source/reference/manipulation.rst
- tests/cupy_tests/manipulation_tests/test_add_remove.py
I wanted to run codes using these functions.
Closes #2101
> Implement `cupy.append` and `cupy.resize`

- cupy/fft/_cache.pyx
- docs/source/reference/fft.rst
- docs/source/reference/plan_cache.rst
> [backport] Improve the plan cache documentation

- cupy/core/_routines_linalg.pyx
Closes https://github.com/cupy/cupy/pull/4111.
> Add compute capability checking for cublasGemmEx()

- cupy/__init__.py
- cupy/_statistics/meanvar.py
- cupy/core/_routines_statistics.pyx
- docs/source/reference/statistics.rst
- tests/cupy_tests/statistics_tests/test_meanvar.py
Closes https://github.com/cupy/cupy/issues/4025 and https://github.com/cupy/cupy/issues/3433.
This PR adds `cupy.nanmedian`.
> Add cupy.nanmedian

- cupy/core/_cub_reduction.pyx
- tests/cupy_tests/sorting_tests/test_search.py
> [backport] Fix `argmax`/`argmin` in CUB block reduction for F-order arrays with ndim > 1

- .pfnci/script.sh
> ROCm gpg url changed

- cupy_backends/cuda/api/runtime.pxd
- cupy_backends/cuda/api/runtime.pyx
- cupy_setup_build.py
- cupyx/_runtime.py
> [backport] ROCm: Fix `getDeviceProperties` for HIP

- docs/source/install_rocm.rst
> [backport] Simplify ROCm install guide

- cupy/core/include/cupy/type_dispatcher.cuh
Close #4121. Thanks @JamesWhalley for reporting the failure on Windows!
> Fix 64-bit int types in `type_dispatcher.cuh`

- cupy/core/include/cupy/type_dispatcher.cuh
> [backport] Fix 64-bit int types in `type_dispatcher.cuh`

- cupyx/scipy/ndimage/_filters_core.py
- cupyx/scipy/ndimage/_interp_kernels.py
- cupyx/scipy/ndimage/_util.py
- cupyx/scipy/ndimage/filters.py
- cupyx/scipy/ndimage/interpolation.py
- tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
- tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
> [backport] handle np.nan and np.inf constant values properly in ndimage functions

- cupy/cutensor.pyx
> [backport] Hide private names in `cupy.cutensor`

- .pfnci/script.sh
- cupy_setup_build.py
> [backport] ROCm: Build on latest ROCm  

- cupy/core/raw.pxd
- cupy/core/raw.pyx
- tests/cupy_tests/core_tests/test_raw.py
> [backport] Support pickling `cupy.RawKernel`

- cupyx/scipy/ndimage/interpolation.py
> [backport] fix mode='opencv' case in cupyx.scipy.ndimage.affine_transform

- cupy_backends/cuda/stream.pyx
> [backport] Fix to use current stream properly with CUDA-related libraries

- cupy_backends/cuda/api/runtime.pyx
> [backport] Fix device properties for cuda 9.2

- tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
> [backport] Code fix on tests for `cupyx.scipy.ndiamge` stats functions

- cupy/testing/helper.py
- tests/cupy_tests/indexing_tests/test_indexing.py
- tests/cupy_tests/indexing_tests/test_iterate.py
- tests/cupy_tests/linalg_tests/test_einsum.py
- tests/cupy_tests/math_tests/test_matmul.py
- tests/cupy_tests/math_tests/test_sumprod.py
- tests/cupy_tests/testing_tests/test_helper.py
> [backport] Make parameterized dtype test skip by `pytest.skip`

- tests/cupyx_tests/fallback_mode_tests/test_notifications.py
> [backport] Fix tests that have side effects

- cupy/core/_routines_indexing.pyx
- cupy/core/core.pyx
- tests/cupy_tests/sorting_tests/test_search.py
> Fix `nonzero` for 0d inputs

- cupy/core/core.pyx
- cupy/core/include/cupy/_cuda/cuda-11.1/cuda_fp16.h
- cupy/core/include/cupy/_cuda/cuda-11.1/cuda_fp16.hpp
- cupy/cuda/compiler.py
- cupyx/tools/install_library.py
- docs/source/install.rst
Merge after https://github.com/chainer/chainer-test/pull/611
> Add support for CUDA 11.1

- cupy/core/_routines_linalg.pyx
> [backport] Add compute capability checking for cublasGemmEx()

- cupy/core/core.pyx
- cupy/core/include/cupy/_cuda/cuda-11.1/cuda_fp16.h
- cupy/core/include/cupy/_cuda/cuda-11.1/cuda_fp16.hpp
- cupy/cuda/compiler.py
- cupyx/tools/install_library.py
- docs/source/install.rst
> [backport] Add support for CUDA 11.1

- docker/python3/Dockerfile
> Bump Docker version to v9.0.0a1

- docker/python3/Dockerfile
> Bump Docker version to v8.1.0

- .travis.yml
Part of https://github.com/cupy/cupy/issues/2993#issuecomment-676164894.
> Use Python 3.6 in Travis CI

- README.md
- docs/source/install.rst
> [backport] Add cupy-cuda111 to README

- cupy/_logic/comparison.py
- tests/cupy_tests/logic_tests/test_comparison.py
Fixes #4201 
Relates to https://github.com/numpy/numpy/pull/16128, https://github.com/numpy/numpy/issues/9229
> Add equal_nan toggle for NaN values in array_equal

- cupyx/scipy/ndimage/measurements.py
- tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
> [backport] fix broadcasting behavior in ndimage.measurements functions

- cupy/testing/__init__.py
- cupy/testing/helper.py
- tests/cupy_tests/core_tests/fusion_tests/test_routines.py
- tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
- tests/cupy_tests/math_tests/test_arithmetic.py
- tests/cupy_tests/math_tests/test_explog.py
> Remove `cupy.testing.NumpyError`

- cupyx/scipy/sparse/linalg/_eigen.py
This PR fixes an issue in `cupyx.scipy.sparse.linalg.eigsh` with CUDA 9.2.
https://github.com/cupy/cupy/pull/4229#issuecomment-722241735
> Fix an issue in `cupyx.scipy.sparse.linalg.eigsh` with CUDA 9.2

- cupy/_math/misc.py
This PR reverts the workaround introduced in #3587, and utilizes the new cuFFT plan cache for further speed-up. Both CPU and GPU times are reduced. The test script used below is from https://github.com/cupy/cupy/pull/3560#issue-445154962.
Before this PR:
```
convolve            :    CPU:  307.700 us   +/- 5.083 (min:  302.990 / max:  363.945) us     GPU-0:  313.297 us   +/- 5.175 (min:  308.160 / max:  369.920) us
convolve            :    CPU:  362.793 us   +/- 8.644 (min:  355.626 / max:  506.037) us     GPU-0:  485.262 us   +/-33.614 (min:  461.600 / max:  602.496) us
convolve            :    CPU:  360.504 us   +/- 4.178 (min:  355.401 / max:  396.366) us     GPU-0:  464.572 us   +/- 2.826 (min:  461.248 / max:  493.024) us
convolve            :    CPU:  364.846 us   +/- 5.211 (min: …
```
> Improve convolve/correlate

- cupyx/scipy/sparse/linalg/__init__.py
- cupyx/scipy/sparse/linalg/_iterative.py
- docs/source/reference/sparse.rst
- tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
This PR adds `cupyx.scipy.sparse.linalg.cg`.
> Add cupyx.scipy.sparse.linalg.cg

- cupy/_util.pyx
- cupy_setup_build.py
- cupyx/_runtime.py
> [backport] Record Cython build version

- docs/source/reference/environment.rst
> Add description of env vars for parallel build and auto cc detection

- cupy/testing/helper.py
- tests/cupy_tests/testing_tests/test_helper.py
> [backport] Refactor `AssertFunctionIsCalled`

- cupy/_indexing/insert.py
- docs/source/reference/binary.rst
- docs/source/reference/indexing.rst
- docs/source/reference/logic.rst
- docs/source/reference/manipulation.rst
- docs/source/reference/misc.rst
- docs/source/reference/ndimage.rst
> [backport] DOC: add missing functions to the API reference

- .github/workflows/pretest.yml
Behaves as the same as https://github.com/cupy/cupy/blob/master/.travis.yml.
https://github.com/asi1024/cupy/runs/1384140459?check_suite_focus=true
> Use GitHub Actions

- docs/source/reference/ndimage.rst
documentation follow-up to #4145
> add spline_filter functions to ndimage docs

- cupy_setup_build.py
> [backport] Add parallel build feature

- cupy/fft/_callback.pyx
refs:
- https://jenkins.preferred.jp/job/chainer/job/daily_master_cupy-shuffled/ID=18,label=mn1-p100/383/console
- `environment.sh:        export NVCC="${NVCC} --compiler-bindir gcc-6"`
cc: @emcastillo
> Fix possible redefinition of "-ccbin" in `cupy.fft._callback`

- .github/workflows/pretest.yml
> [backport] Use GitHub Actions

- cupy/random/_generator.py
- tests/cupy_tests/random_tests/test_generator.py
- tests/cupy_tests/random_tests/test_sample.py
Closes https://github.com/cupy/cupy/issues/4120
> Improve cupy.random.randint

- cupyx/tools/install_library.py
> [backport] Bump cuDNN to v8.0.5

- cupy/random/__init__.py
- tests/cupy_tests/random_tests/test_init.py
> Fix `cupy.random.bytes` not working

- tests/cupy_tests/core_tests/test_ndarray_reduction.py
- tests/cupy_tests/sorting_tests/test_search.py
Close #4254. See the discussion there.
cc: @toslunar
> Skip some failing tests for fp16 + CUDA 9.0

- tests/cupy_tests/core_tests/test_ndarray_reduction.py
- tests/cupy_tests/sorting_tests/test_search.py
> [backport] Skip some failing tests for fp16 + CUDA 9.0

- .pfnci/script.sh
- cupy/_environment.py
- cupy/_statistics/histogram.py
- cupy/core/_cub_reduction.pyx
- cupy/core/_routines_math.pyx
- cupy/core/_routines_statistics.pyx
- cupy/cuda/__init__.py
- cupy/cuda/cub.pyx
- cupy/cuda/cupy_cub.cu
- cupy/cuda/cupy_cub.h
- cupy_setup_build.py
- docs/source/install_rocm.rst
- install/build.py
- tests/cupy_tests/core_tests/test_cub_reduction.py
- tests/cupy_tests/core_tests/test_ndarray_reduction.py
- tests/cupy_tests/core_tests/test_raw.py
> [backport] ROCm: Support hipCUB/rocPRIM

- cupy/_environment.py
> [backport] Defer import in `cupy/_environment.py`

- .pfnci/script.sh
- cupy_setup_build.py
> [backport] Add import test for ROCm

- README.md
- docs/source/install.rst
> [backport] cupy-cuda111 package now on PyPI

- docker/python3/Dockerfile
> Bump Docker version to v9.0.0a2

- docker/python3/Dockerfile
> Bump Docker version to v8.2.0

- README.md
> [backport] Update links to forums in README

- cupy_setup_build.py
- docs/source/reference/environment.rst
> Fix parallel build

- cupy_setup_build.py
> [backport] Fix parallel build

- tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
- tests/cupyx_tests/scipy_tests/ndimage_tests/test_fourier.py
- tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
- tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
- tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py
> Refactor ndimage_tests

- cupy/fft/config.py
> [backport] Fix cufft callback manager error in Windows

- cupy_setup_build.py
> [backport] Reset extra_compile_args for each module

- docs/requirements.txt
- docs/source/_comparison_generator.py
> [backport] add scipy.fft module to the API comparison table

- cupyx/scipy/sparse/base.py
- cupyx/scipy/sparse/csr.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
This PR adds `cupyx.scipy.sparse.csr_matrix.diagonal` and `cupyx.scipy.sparse.csr_matrix.setdiag`
This is useful when using Jacobi preconditioner, etc.
> Add `cupyx.scipy.sparse.csr_matrix.diagonal` and `cupyx.scipy.sparse.csr_matrix.setdiag`

- cupy/linalg/_solve.py
- tests/cupy_tests/linalg_tests/test_solve.py
> [backport] Fix `rcond` arg of `linalg.lstsq`

- cupy/cuda/compiler.py
> [backport] Inherit environment variable and detect cl.exe automatically

- tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
This PR refactors `TestLinearOperator` to check compatibility the behavior of `cupyx.scipy` and `scipy`.
> Refactor `TestLinearOperator`

- cupy/linalg/_solve.py
- tests/cupy_tests/linalg_tests/test_solve.py
> Fix `linalg.lstsq` for complex types

- tests/cupy_tests/linalg_tests/test_solve.py
> [backport] Refactor test of `linalg.lstsq`

- cupy/linalg/_solve.py
- tests/cupy_tests/linalg_tests/test_solve.py
> [backport] Fix `linalg.lstsq` for complex types

- cupy/core/_routines_math.pyx
This improves `scan_core` ([link](https://github.com/cupy/cupy/blob/e08848f7ed738636ecc3d377fda5f3d69f8a14f9/cupy/core/_routines_math.pyx#L501)) if dtype is promoted.
The current implementation copies the input array before calling a scan kernel when dtype is promoted, but this copying is not necessary when the CuPy bult-in scan kernel is used. This PR eliminates this array copy (when possible) and improves the performance. Below are measured results of `cumsum` on V100.
size | dtype | NumPy | CuPy (current) | CuPy (this PR)
-----|-------|-------|-----|-----
1,000,000 | int8 | 3.401 ms | 0.130 ms | 0.100 ms
1,000,000 | int32 | 2.856 ms | 0.132 ms | 0.095 ms
1,000,000 | uint32 | 3.163 ms | 0.135 ms | 0.095 ms
10,000,000 | int8 | 39.967 ms | 0.816 ms | 0.636 ms
10,000,000 | int32 | 40.706 …
> Improve `scan_core` in cupy/core/_routines_math.pyx

- cupyx/scipy/sparse/__init__.py
- cupyx/scipy/sparse/extract.py
- docs/source/reference/sparse.rst
- tests/cupyx_tests/scipy_tests/sparse_tests/test_extract.py
This PR adds `tril`, `triu` and `find` to `cupyx.scipy.sparse`.
> Add `tril`, `triu` and `find` to `cupyx.scipy.sparse`

- cupy/_sorting/search.py
Close #3841. 
Lesson learned from #4366: Unlike on NVIDIA GPUs, on AMD GPUs there cannot be any diverging threads in a warp. Early return causes such a thread divergence (even though unlike in common pitfalls where a barrier follows later we don't have any explicit barrier in `searchsorted`). I couldn't find a better way to guard this, so in this PR I use a bool to indicate if a thread is done. This bool is only used for running on HIP, and the old behavior is preserved on CUDA (although I start wondering if early return is also illegal in CUDA or not...) There might already be a standard way to deal with early return developed in OpenCL, so if experienced people can comment on this I would appreciate a lot 🙏
All `searchsorted` tests passed. (`pytest …
> Fix `cupy.searchsorted` on HIP

- cupy/_util.pyx
- cupy/core/core.pyx
- cupy/cuda/stream.pyx
- docs/source/reference/environment.rst
- tests/cupy_tests/core_tests/test_ndarray.py
- tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
- tests/cupy_tests/creation_tests/test_from_data.py
> [backport] Update CUDA Array Interface to v3 - Part 1

- cupyx/scipy/sparse/linalg/_eigen.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
This PR adds support for `LinearOperator` to `cupyx.scipy.sparse.linalg.eigsh` and `cupyx.scipy.sparse.linalg.svds` to improve compatibility with SciPy.
> Add support for `LinearOperator` to `eigsh` and `svds` in `cupyx.scipy.sparse.linalg`

- cupyx/scipy/linalg/solve_triangular.py
- tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
> Support complex types in `solve_triangular`

- setup.py
Fix `pytest-cov` (chainer/chainer-test#603) and `coverage` (chainer/chainer-test#546).
> Update `[jenkins]` requirement

- cupy_setup_build.py
> [backport] Add support for cuTENSOR 1.2.2

- cupyx/scipy/linalg/solve_triangular.py
- tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
> [backport] Support complex types in `solve_triangular`

- setup.py
> [backport] Update `[jenkins]` requirement

- cupy/random/_distributions.py
- cupy/random/_generator.py
- cupy/random/_permutations.py
- cupy/random/_sample.py
> [backport] Fix docs of `cupy.random` functions/methods

- tests/cupy_tests/core_tests/test_raw.py
This is to fix Windows test failure
> Fix raw kernel test

- cupy/cusolver.py
> fix dev info allocation

- docker/python3/Dockerfile
> Bump Dockerfile version to v8.3.0

- docker/python3/Dockerfile
> Bump Dockerfile version to v9.0.0b1

- cupy/cuda/compiler.py
> Use `--device-c` for RDC compile

- cupy/cusolver.py
> [backport] Fix dev info allocation

- setup.cfg
> [backport] Test FutureWarning

- cupy/fft/_callback.pyx
Fix #4506. ~~Work in progress.~~
> Fix potential race when compiling cuFFT callbacks

- cupyx/scipy/sparse/construct.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
> Fix sparse format of `kron`

- cupyx/scipy/sparse/construct.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py
> [backport] Fix sparse format of `kron`

- cupy/core/_routines_linalg.pyx
> [backport] Fix integer GEMM

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray.py
> Fix `__format__`

- cupy/_math/sumprod.py
- tests/cupy_tests/math_tests/test_sumprod.py
Fix #4520.
Please comment on #4522, too
> Fix `axis` of `cupy.gradient`

- cupy/random/cupy_distributions.cu
Windows does not define `ssize_t`.
Verified that the module builds and the tests work.
> Fix windows build of random module

- cupy/lib/_polynomial.pyx
Ready for https://github.com/cupy/cupy/pull/4262.
> Fix return type of `polynomial.__eq__`

- cupy/lib/_polynomial.pyx
> [backport] Fix return type of `polynomial.__eq__`

- cupy/core/core.pyx
- cupy/core/dlpack.pxd
- cupy/core/dlpack.pyx
- cupy/core/include/cupy/README.md
- cupy/core/include/cupy/dlpack/README.md
- cupy/core/include/cupy/dlpack/dlpack.h
- cupy_setup_build.py
- docs/source/reference/interoperability.rst
- tests/cupy_tests/core_tests/test_dlpack.py
> [backport] Import DLPack header file & Fix multiple issues

- cupy/lib/_polynomial.pyx
> Fix return type of `polynomial.__eq__` to `numpy.bool_`

- cupy/_math/floating.py
- cupy/core/_fusion_kernel.pyx
- cupy_backends/hip/cupy_hip.h
- tests/cupy_tests/core_tests/fusion_tests/test_example.py
Merge after #4485 
changes are those of commit https://github.com/cupy/cupy/commit/21fc6c83805d9d62ef721f080d93b9ead29025a1
> Fix fusion tests for HIP

- docker/python3/Dockerfile
> Bump Dockerfile version to v9.0.0b2

- docker/python3/Dockerfile
> Bump Dockerfile version to v8.4.0

- install/build.py
> [backport] Fix warning message on cuDNN version

- cupy/lib/_polynomial.pyx
- cupy/lib/_routines_poly.py
- tests/cupy_tests/lib_tests/test_polynomial.py
https://github.com/numpy/numpy/pull/17577
> Fix `poly1d` return types for NumPy 1.20

- cupy/_statistics/histogram.py
- cupy/core/core.pyx
- tests/cupy_tests/indexing_tests/test_insert.py
- tests/cupy_tests/testing_tests/test_helper.py
- tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
> [backport] Stop using deprecated type aliases

- cupy/core/internal.pyx
- cupy/random/_generator.py
- tests/cupy_tests/core_tests/test_internal.py
- tests/cupy_tests/core_tests/test_ndarray.py
- tests/cupy_tests/creation_tests/test_basic.py
- tests/cupy_tests/random_tests/test_generator.py
> Deprecate passing shape=None to mean shape=()

- cupy/_creation/ranges.py
- tests/cupy_tests/creation_tests/test_ranges.py
> Update spec of `linspace` to NumPy 1.20

- cupyx/scipy/linalg/decomp_lu.py
- tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
Close #4259.
It looks that `cupyx.scipy.linalg.lu_factor` returns the same result to `scipy.linalg.lu_factor`. I remove the note on the document and add a test given a singular matrix.
> Update doctest of `cupyx.scipy.linalg.lu_factor`

- cupy_backends/cuda/api/runtime.pyx
> [backport] Fix device property default name

- docs/source/install.rst
> Update installation guide for cuTENSOR on Conda-Forge

- cupyx/jit/_compile.py
- tests/cupy_tests/functional_tests/test_vectorize.py
~Blocked by https://github.com/cupy/cupy/pull/4347.~
> Support explicit typecast in CuPy JIT

- .github/workflows/pretest.yml
- docs/requirements.txt
- setup.py
- Remove docs/doctest from setup.py as they're not used.
- Updated to use the latest Sphinx in RTD and Jenkins. (docs/requirements.txt is used setup RTD environment and run doctest in Jenkins)
> Update documentation requirements

- cupy/random/_distributions.py
- cupy/random/_generator.py
- tests/cupy_tests/random_tests/test_distributions.py
> [backport] Make `normal` and `lognormal` support array args

- .github/workflows/pretest.yml
- docs/requirements.txt
- setup.py
> [backport] Update documentation requirements

- .pfnci/config.pbtxt
- .pfnci/trim_cupy_kernel_cache.py
- .pfnci/windows/_error_handler.ps1
- .pfnci/windows/_flexci.ps1
- .pfnci/windows/run.bat
- .pfnci/windows/test.ps1
- setup.cfg
The first attempt to run CI on Windows.
> Add FlexCI for Windows

- cupy_setup_build.py
- docs/source/contribution.rst
- install/build.py
> [backport] Remove broken support for macOS

- cupyx/jit/_compile.py
- tests/cupy_tests/functional_tests/test_vectorize.py
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/2972/TEST=cupy-py36,label=mn1-p100/testReport/junit/tests.cupy_tests.functional_tests.test_vectorize/TestVectorizeExprs/test_vectorize_typecast/
> Fix typecast from complex to bool in JIT

- cupy/__init__.py
- setup.py
> Bump fastrlock requirement

- docs/source/install.rst
> [backport] Update installation guide for cuTENSOR on Conda-Forge

- cupyx/jit/_compile.py
- cupyx/jit/_typerules.py
- tests/cupy_tests/functional_tests/test_vectorize.py
> Support if-statement in CuPy JIT

- cupy_backends/cuda/cupy_cusparse.h
> Fix cuSPARSE module build failure with CUDA 10.1 on Windows

- .pfnci/config.pbtxt
- .pfnci/trim_cupy_kernel_cache.py
- .pfnci/windows/_error_handler.ps1
- .pfnci/windows/_flexci.ps1
- .pfnci/windows/run.bat
- .pfnci/windows/test.ps1
- setup.cfg
- tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
> [backport] Add FlexCI for Windows

- cupy/core/dlpack.pyx
- cupy/core/include/cupy/dlpack/README.md
- cupy/core/include/cupy/dlpack/dlpack.h
> [backport] Fix DLPack header version

- cupyx/tools/install_library.py
Close #4601. Please check the installation test on the Windows CI before merging. It should pass now.
> Support cuTENSOR download tool on Windows
