cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

Currently ``map_coordinates`` with ``order=1`` assumes ``coords`` is a 2d array, but this restriction is not present in SciPy itself. This PR fixes the code to handle ``coords`` with >2 dimensions.

fix cupyx.scipy.ndimage.map_coordinates for cases with coords > 2d

---

cupy/logic/comparison.py

Currently it synchronizes the device and returns a `bool`, but I think it can just return a 0-dim array.

Avoid device synchronization in `cupy.allclose`

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_split.py

Follows #2814 .
`cupy.split` and `cupy.array_split` raise an error when they take unordered indices as `[4, 2]`. NumPy does not require indices ordered and, in such case, it return an empty array for a going-back index. I'm not sure it is meaningful, but it actually does. This PR fix the functions to follow NumPy's behavior.
```Python
>>> import numpy as np
>>> np.split(np.array([0, 1, 2, 3, 4]), [4, 2])
[array([0, 1, 2, 3]), array([], dtype=int64), array([2, 3, 4])]
>>> cp.split(cp.array([0, 1, 2, 3, 4]), [4, 2])
File "cupy/core/core.pyx", line 1341, in cupy.core.core.ndarray.__repr__
return repr(self.get())
File "cupy/core/core.pyx", line 1432, in cupy.core.core.ndarray.get
a_cpu = …
```

Fix split and array_split with unordered indices supplied

---

cupy/core/_reduction.pyx

`_reduce_dims()` (and `ndarray.reduced_view()`) can only squash C-contiguous dimensions.
This PR sorts the axes so that they can be squashed even if they're F-contiguous.
Benchmark code using [cupy-perf](https://github.com/niboshi/cupy-perf/):
```py
import cupy
import cupy_perf
class Perf1(cupy_perf.PerfCases):
def setUp(self):
shape = (100,) * 3
self.a = cupy.empty(shape, 'float32')
self.b = cupy.empty(shape, 'float32').T
@cupy_perf.attr(n=100)
def perf_ccont(self):
self.a.sum(axis=(1, 2))
@cupy_perf.attr(n=100)
def perf_fcont(self):
self.b.sum(axis=(0, 1))
cupy_perf.run(__name__)
```
Result:
```
ccont               :    22.412 us   +/- 2.332 (min:   20.623) us    896.698 us   +/- 5.373 (min:  875.040) us
fcont               :    26.003 us   +/-17.168 (min:   17.974) us   2862.353 us …
```

Allow squashing f-contiguous axes for faster reduction

---

cupy/core/include/cupy/complex/cpow.h

Build fails during cythonizing.
`cupy/core/include/cupy/complex/cpow.h(22): error: identifier "y" is undefined`

Fix compilation error causes when thrust is enabled

---

cupy/core/_reduction.pyx
cupy/core/_routines_math.pyx
cupy/core/_routines_statistics.pyx
cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/cuda/cub.pyx
tests/cupy_tests/core_tests/test_ndarray_reduction.py
tests/cupy_tests/math_tests/test_sumprod.py

closes #2720
The bug is fixed by the lines computing `out_shape` within `device_reduce`.
In order to avoid multiple calls to `_get_axis`, I moved the `_get_axis` call outside of `_preprocess_array` and call it directly in `_routines_math.pyx` and `_routines_statistics.pyx` instead. The duplicate logic could potentially be refactored into a common function
`_get_axes` will have already sorted the axes in ascending order and checked their range (It also separates out the axes to be reduced from those needed in determining the shape for keepdims).
This allows greatly simplifying the code in `_cub_device_segmented_reduce_axis_compatible` and removes the need for `_cub_device_reduce_axis_compatible` altogether.
Although not strictly part of the bug fix, I implemented a performance improvement …

keepdims should always preserve all dimensions in CUB-based reductions

---

cupy/core/raw.pyx
docs/source/tutorial/kernel.rst
tests/cupy_tests/core_tests/test_raw.py
tests/cupy_tests/cuda_tests/test_texture.py

Backport of #2784
Was not cleanly cherry-picked

[backport] Separate code and path arguments in `RawModule`

---

cupy/core/_routines_math.pyx
cupy/core/_routines_statistics.pyx
cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/core/reduction.pxi
cupy/cuda/cub.pyx
tests/cupy_tests/core_tests/test_ndarray_reduction.py
tests/cupy_tests/math_tests/test_sumprod.py

[backport] keepdims should always preserve all dimensions in CUB-based reductions

---

cupy/random/generator.py
tests/cupy_tests/random_tests/test_generator.py

Fix #2816.
Compared to #2823, this PR keeps using 32-bit RNG.

Support 64 bit extent `randint`

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_split.py

[backport] Fix split and array_split with indices overrun

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_split.py

[backport] Fix split and array_split with unordered indices supplied

---

cupy/core/core.pyx
cupy/cuda/memory.pyx
tests/cupy_tests/creation_tests/test_from_data.py

Follow-up of #2611. Close #2789.
This PR fixes the consumer side (while #2611 fixed the producer side) for handling zero-size arrays. 
cc: @jakirkham

Avoid looking up null pointers' attributes

---

.travis.yml

Python 3.4 is no longer supported.

Reomve Python 3.4 matrix from Travis CI

---

cupy/__init__.py
cupy/sorting/search.py
cupy/statistics/histogram.py
tests/cupy_tests/statics_tests/test_histogram.py

Adds `digitize` using `searchsorted`
As `digitize` supports increasing and decreasing arrays, I tuned the `searchsorted` kernel to do the monotonicity check and support both sorting directions. However, a specific kernel only for digitize can be made or the arrays could be simply reversed as in the numpy implementation.

Add `digitize`

---

.travis.yml

[backport] Remove Python 3.4 matrix from Travis CI

---

cupy/testing/helper.py
tests/cupy_tests/manipulation_tests/test_shape.py
tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py

Depends on #2820 
Refactor the common code to call cupy and cupy test implementation (`_call_func_numpy_cupy()`).

Refactor array testing decorators

---

cupy/core/core.pxd
cupy/core/core.pyx
cupy/statistics/order.py

Remove `dtype` argument from `min`/`max`

---

cupy/core/_kernel.pyx

`items()` is not guaranteed to be in any order (at least before Python 3.7).
This value is used as a cache key, so it should be sorted.

Sort type map in `_kernel.pyx`

---

cupy/core/_routines_statistics.pyx

as mentioned in #2725, this PR enables a CUB code path for mean computation

Add CUB reduction support to `mean`

---

cupy/testing/helper.py
tests/cupy_tests/testing_tests/test_helper.py

[backport] Fix `@testing.numpy_cupy_` decorators for skips

---

tests/cupy_tests/testing_tests/test_helper.py

Error message was changed in 1.18.
I think error message can be simply ignored.

Fix `test_helper.py` for NumPy 1.18

---

cupy/cuda/cupy_cuda_common.h
cupy/cuda/memory.pyx
cupy/cuda/runtime.pxd

Cherry-pick from #2644. This PR fixes the error when peer access is enabled by some external libraries (cuFFT in the case of #2644). The `CUDARuntimeError` should be silently ignored in this case.

Ignore error when peer access is already enabled 

---

cupyx/scipy/sparse/compressed.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

This is a follow up to #2712 that updates CSR and CSC sparse matrix slicing tests for 1.4.0. The prior PR just skipped the existing tests on 1.3.x to avoid segfaults. 
In SciPy 1.4.0, the behavior for this tests case is changed from raising an `IndexError` to instead return an empty slice. [For reference see this comment at at SciPy](https://github.com/scipy/scipy/pull/11127#issuecomment-560936956) (and the implementation in scipy/scipy#11166). The new behavior is consistent with slicing of NumPy arrays/matrices. 
The PR corresponding to this behavior is being backported to the 1.4.0 branch for inclusion prior to the upcoming 1.4.0 release (see scipy/scipy#11161). For the moment I have just verified that the new test cases pass vs. current SciPy master.

update slicing of CSR and CSC matrices for compatibility with SciPy 1.4.0

---

cupy/cuda/memory.pyx

`cudaFree` (but not `cudaMalloc`) causes device synchronization.

Declare device synchronization at `runtime.free()`

---

tests/cupy_tests/testing_tests/test_helper.py

[backport] Fix `test_helper.py` for NumPy 1.18

---

cupyx/scipy/ndimage/filters.py

This is a more minimal change than the one proposed in #2842. It just skips some logic checks and a multiply+add when a coefficient is zero.
As in the other issues
```Python
import cupy
from cupyx.scipy.ndimage import convolve
from cupyx.time import repeat
d = cupy.cuda.Device()
x = cupy.random.randn(256, 256, 256);
w = cupy.random.randn(5, 5, 5)  # dense case
perf = repeat(convolve, (x, w), n=50, n_warmup=10)
print(perf)
```
dense:
```
convolve            :   161.843 us   +/-73.898 (min:  112.840 / max:  485.355) us  199239.168 us   +/-620.967 (min:197391.357 / max:200185.852) us
```
sparse:
```
convolve            :   166.174 us   +/-72.078 (min:  112.363 / max:  615.620) us  74903.974 us   +/-88.711 (min:74803.200 / max:75203.583) us
```
vs. dense or sparse on master
```
convolve …
```

skip zero valued coefficients in cupyx.scipy.ndimage.convolve

---

cupyx/scipy/ndimage/filters.py

[backport] Fix complex type checks in `_correlate_or_convolve`

---

cupy/testing/helper.py

This fix makes `pytest --pdb` inspect the traceback of the actual error raised in the test, instead of the traceback of `self.fail()`.
If both cupy and numpy raised errors, `--pdb` stops at the cupy error.

Make test helper decorators pdb-friendly

---

cupy/core/_kernel.pyx
cupy/core/_reduction.pyx
cupy/core/_scalar.pxd
cupy/core/_scalar.pyx

Cleans up `_scalar.pyx/pxd`.
* Previously, `convert_scalar()` returned different types of objects depending on a flag. This is confusing because the return type is obscure.
* Unifies `CScalar`'s various creation functions into static methods `CScalar.from_xxx()`.

Clean up `_scalar.pyx`

---

tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py

Solves a [rare flaky test](https://jenkins.preferred.jp/job/chainer/job/cupy_pr/829/TEST=cupy-py35,label=mn1-p100/testReport/junit/tests.cupyx_tests.scipy_tests.linalg_tests.test_solve_triangular/TestSolveTriangular_param_7_%7Bcheck_finite=True,%20lower=True,%20overwrite_b=True,%20trans=%27N%27,%20unit_diagonal=False%7D/test_solve/)
Thanks to @toslunar for finding the reason.

Avoid 0s in the diagonal of `TestSolveTriangular` inputs

---

tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py

[backport] Avoid 0s in the diagonal of `TestSolveTriangular` inputs

---

cupy/cuda/cub.pyx

...I guess we forgot it back in #2725, @grlee77? 
It'd be really nice if all these CUB bug fixes could be avoided by having CIs catching them in the first place...

Fix `cupy.cuda.cub.device_segmented_reduce()` not being used

---

.mergify.yml

Adding mergify configuration.
It's also necessary to configure the organization following the instruction: https://doc.mergify.io/getting-started.html
Should `continuous-integration/appveyor/pr` also be included?

Add Mergify configuration file

---

cupy/cuda/cub.pyx

[backport] Fix `cupy.cuda.cub.device_segmented_reduce()` not being used

---

cupy/core/_kernel.pyx
tests/cupy_tests/core_tests/test_userkernel.py

Orthogonal to #2731
Right now the `ElementwiseKernel` class launches all kernels with the same block size which is not easily tunable.
This PR replaces the hardcoded value with a kwarg for the `__call__` method.

Allow `ElementwiseKernel` to set the block_size

---

cupy/core/_kernel.pyx

Adds expected and actual numbers.
```
TypeError: Wrong number of arguments for 'cupy_add'. It must be either 2 or 3 (with outputs), but given 4.
```

Improve error message for wrong number of arguments in elementwise kernels

---

cupy/core/_kernel.pxd
cupy/core/_kernel.pyx
cupy/core/_reduction.pxd
cupy/core/_reduction.pyx

Separated from #2920.
Introduced `_ArgInfo` to hold argument metadata, and `_TypeMap` to abstract C type mapping.

Enhance type and argument manipulation in elementwise and reduction kernels

---

docs/source/install.rst

Follow-up #2709.  To be backported to v7 (but not to v6).

Update cuTENSOR version in docs

---

cupy/manipulation/basic.py

Part of #2159.
`cupy.copyto` currently uses synchronous DtoD copy in one of its branches, eventually using the default CUDA stream. This PR fixes it to use asynchronous DtoD copy with the current CUDA stream that CuPy manages.

Use asynchronous copy in `cupy.copyto`

---

cupy/cuda/__init__.py
cupy/linalg/einsum.py

This PR is to use cuTensor for `einsum` when cuTensor is available.
This is related to https://github.com/cupy/cupy/issues/2904

Use cuTensor for einsum

---

cupy/core/_routines_manipulation.pyx

This PR silences two such warnings: `warning: comparison between signed and unsigned integer expressions [-Wsign-compare]`.

silence sign comparison warnings

---

cupy/core/_routines_statistics.pyx

This bug fix was split out from PR #2903 for easier review. For integer dtypes it is not possible to perform in-place division by a float.

Avoid invalid in-place division in CUB-based mean

---

cupy/core/_kernel.pyx

`__hash__` and `__eq__`, required to be suitable as a cache key, were missing in `ParameterInfo`.
You can check the behavior by the following code.
```py
import cupy
a = cupy.core._kernel.ParameterInfo('raw T x', False)
b = cupy.core._kernel.ParameterInfo('raw T x', False)
print(hash(a))
print(hash(b))
print(a == b)
```
After the fix:
```
2788533504290071466
2788533504290071466
True
```

Fix `ParameterInfo` as a cache key

---

cupy/core/_kernel.pyx

[backport] Fix `ParameterInfo` as a cache key

---

cupy/cuda/memory.pyx

It might be useful for debugging to include the pointer value etc.
```
>>> a = cupy.array([1, 2, 3], 'float32')
>>> a.data
<MemoryPointer 0x7f9be0800000 device=0 mem=<cupy.cuda.memory.PooledMemory object at 0x7f9cde8edb30>>
```

`MemoryPointer.__repr__`

---

cupy/creation/ranges.py
tests/cupy_tests/creation_tests/test_ranges.py

`numpy.linspace(start, stop, num=1, endpoint=False, retstep=True)[1]` returns `stop - start` from 1.18.

Fix `linspace(..., num=1, endpoint=False, retstep=True)`

---

cupy/creation/ranges.py
tests/cupy_tests/creation_tests/test_ranges.py

[backport] Fix `linspace(..., num=1, endpoint=False, retstep=True)`

---

cupyx/scipy/sparse/compressed.py
cupyx/scipy/sparse/csc.py
cupyx/scipy/sparse/csr.py
cupyx/scipy/sparse/data.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

This adds min, max, argmin, and argmax functionality to cupy sparse csr and csc matrix formats. Format differences from scipy are to improve computational performance by eliminating duplicate summation and coo matrix construction time.

Added min, max, argmin, argmax to sparse csr and csc matrices

---

cupy/fft/fft.py
tests/cupy_tests/fft_tests/test_fft.py

* Place operators after new lines
* `raise unittest.SkipTest()` instead of `pytest.skip()`

A nit-picking code fix

---

cupy/linalg/einsum.py

This PR is to improve performance of einsum when no contraction is necessary w/o using cuTensor.
This is related to https://github.com/cupy/cupy/issues/2904 and https://github.com/cupy/cupy/pull/2928#discussion_r364643809.

Improve performance of element-wise `einsum` where no contraction is necessary

---

cupy/__init__.py
cupy/core/_routines_statistics.pxd
cupy/core/_routines_statistics.pyx
cupy/core/core.pxd
cupy/core/core.pyx
cupy/statistics/order.py
tests/cupy_tests/core_tests/test_ndarray_reduction.py
tests/cupy_tests/statics_tests/test_order.py

This PR adds `ptp` (peak-to-peak). 
I have included a `dtype` argument to make it consistent with CuPy's min & max (which `ptp` calls internally), but this argument is not present in the NumPy API. If preferred it can be removed (I wasn't sure what the reasoning for its inclusion was).
Also, unlike `amin` or `amax`, `ptp` as implemented here does not currently support Fusion. I haven't looked at the Fusion code implementation, so am not sure how easy it might be to support? The current implementation calls both `_amin` and `_amax` ufuncs rather than implementing its own separate reduction kernel, so there was not a single kernel to point to as done in the `amin` function I looked at as a reference.
Finally, should we also check explicitly for `bool` dtype and raise a TypeError in that …

Add `ptp` ndarray method and function

---

cupy/cuda/cub.pyx

This PR is to address some potential failures in `tests/cupy_tests/sorting_tests/test_search.py` when CUB is enabled.

Fix an issue using non-existing attribute in cub.pyx

---

cupy/cuda/cub.pyx

[backport] Fix an issue using non-existing attribute in cub.pyx

---

cupy/core/core.pyx

[backport] Use `size_t nbytes` in `__cuda_array_interface__`

---

cupy/cuda/nvrtc.pyx

Closes #3016
In some linux distributions accessing &(array[0]) can trigger an assertion in libstdc++
thanks to @coderforlife for providing details on this and how to fix it.

Fix empty vector access

---

cupy/cuda/cub.pxd
cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu
cupy/cuda/cupy_cub.h
cupy/math/sumprod.py

In the demo below, CUB gets about a 4x speed-up on a P100:
```python
>>> import cupyx
>>> 
>>> a = cp.random.random(1000000)
>>>
>>> cp.cuda.cub_enabled  =False
>>> print(cupyx.time.repeat(cp.cumprod, (a, )))
cumprod             :   428.775 us   +/-57.870 (min:  396.988 / max:  976.234) us    471.108 us   +/-45.524 (min:  449.888 / max:  992.736) us
>>> cp.cuda.cub_enabled = True
>>> print(cupyx.time.repeat(cp.cumprod, (a, )))
cumprod             :   103.053 us   +/-19.460 (min:   84.242 / max:  229.079) us    132.358 us   +/-17.695 (min:  113.888 / max:  250.048) us
>>>
>>> cp.cuda.cub_enabled = False
>>> print(cupyx.time.repeat(cp.cumsum, (a, )))
cumsum              :   428.253 us   +/-55.802 (min:  398.817 / max:  978.976) us    470.163 us   +/-43.695 (min: …
```

Support CUB prefix sum & product

---

cupyx/scipy/fftpack/fft.py
tests/cupy_tests/fft_tests/test_fft.py
tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py

Cherry-pick from #2998:
> 2. Fix a bug in cupyx.scipy.fftpack.get_fft_plan() following #2752 (1c6174d, should be backported)
> 3. Fix missing axes arguments in TestRfft2 (4ef81b1, should be backported)

[backport] Fix `get_fft_plan()` and some FFT tests

---

cupy/cuda/cusolver.pxd
cupy/cuda/cusolver.pyx

A part of #2716
Other types should be fixed, too (like `stream` and `devInfo`), but this PR only fixes handles.

Use `intptr_t` for cuSOLVER  handles

---

cupy/cuda/_environment.py
cupy/cuda/compiler.py

Takes over #3023
In some environment, `nvcc` is not necessarilly looked up by`PATH`.

Fix nvcc command lookup

---

setup.py

This PR is to address some failures in `tests/cupy_tests/core_test/test_raw.py` due to `cuComplex_bridge.h` not being installed.

Fix an issue that cuComplex_bridge.h is not installed

---

examples/gmm/gmm.py

On the GMM (Gaussian Mixture Model) example, fix the following.
- Use `scipy.stats` to compute bivariate normal.  `matplotlab.mlab.bivariate_normal` is deprecated since matplotlib 2.2 and is removed since 3.0
- Surpress the warning message:
> 'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.
```
% python gmm.py --output-image=tmp.png
Running CPU...
train_accuracy : 92.143100
test_accuracy : 92.000000
CPU :  1.087882 sec
Running GPU...
train_accuracy : 92.030900
test_accuracy : 92.000000
GPU :  0.651976 sec
% imgcat tmp.png
```

Fix GMM example for matplotlib 3

---

docs/source/install.rst

[backport] Add NumPy 1.18 to installation guide

---

tests/example_tests/test_gmm.py

This amends #2996 for test environments without `scipy` (but with `matplotlib`).

Require `scipy` in `test_gmm`

---

cupy/core/_routines_statistics.pyx
tests/cupy_tests/statics_tests/test_meanvar.py

The first commit here fixes a bug in CUB-based mean that was introduced in #2860. When the input had an integer dtype, the in-place addition with a float would fail with a `TypeError`.
The second two commits fix both the CUB code path and the non-CUB one to return the requested dtype. In current master, mean would fail when dtype was not a floating (or complex) type as there is not case for that defined in the `_mean_core` ufunc. NumPy does allow such cases. The newly added tests verify consistent behavior. They pass when I tried it locally for both `CUB_DISABLED=0` and `CUB_DISABLED=1`.

Fix handling of dtypes in cupy.mean

---

tests/example_tests/test_gmm.py

[backport] Require `scipy` in `test_gmm`

---

cupyx/scipy/special/__init__.py
cupyx/scipy/special/convex_analysis.py
tests/cupyx_tests/scipy_tests/special_tests/test_convex_analysis.py

This PR adds five simple ufuncs to `cupyx.scipy.special`. In SciPy, these are defined in [_convex_analysis.pxd](https://github.com/scipy/scipy/blob/76da841e41090c77f682afd77a951da455abed91/scipy/special/_convex_analysis.pxd). I followed some existing examples in the cupyx.scipy.special folder on how to handle NaN's and added an equivalent handling for INF values here.
`entr` and `rel_entr` are used to implement `scipy.stats.entropy` if there is interest in adding that in a follow-up PR.
Most of the test cases added here correspond to [ones defined in the SciPy test suite](https://github.com/scipy/scipy/blob/76da841e41090c77f682afd77a951da455abed91/scipy/special/tests/test_basic.py#L3314-L3399).

Add convex analysis ufuncs to `cupyx.scipy.special`

---

tests/conftest.py

[backport] Print installed packages in pytest

---

cupy/cuda/cupy_hip.h
cupy/cuda/cupy_hip_common.h
cupy_setup_build.py

* Functions added in `cupy_cuda.h` and `cupy_cuda_common.h`  was missing in its HIP counterpart
* Do not use CUDA-specific libraries (cudnn, etc) in HIP build (regression in https://github.com/cupy/cupy/pull/2730)

Fix ROCm build errors

---

tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py

CI is failing after upgrading numpy for python 3.5
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/996/testReport/
The reason is #2922 and Pascal is being used in Jenkins.

Skip `irfft` tests for compute capability != 7

---

cupy/core/_routines_indexing.pyx
cupy/core/_routines_math.pxd
cupy/core/_routines_math.pyx
cupy/math/sumprod.py
tests/cupy_tests/math_tests/test_sumprod.py

Solves #2905 
Uses the fast scan available in _math_routines and adds new kernels for batched cumsum/cumprod
Matrix size : (550, 100, 72, 50)
Previous to this PR:
```
cumsum   axis=None  :   228.304 us   +/-23.550 (min:  217.939 / max:  358.161) us  80835.688 us   +/-37.779 (min:80798.241 / max:81046.272) us
cumsum   axis=0     :   241.658 us   +/-11.215 (min:  234.609 / max:  315.020) us  84766.405 us   +/- 9.216 (min:84760.162 / max:84825.439) us
cumsum   axis=1     :   261.572 us   +/- 8.596 (min:  255.286 / max:  308.073) us  85690.466 us   +/- 6.717 (min:85684.509 / max:85727.554) us
cumsum   axis=2     :   261.069 us   +/- 6.102 (min:  255.105 / max:  292.426) us  85336.803 us   +/-49.660 (min:85323.997 / max:85682.014) us
cumsum   axis=3     :   258.408 us   +/-48.437 (min: …
```

Improve performance of `cumsum` and `cumprod`

---

cupy/creation/ranges.py
tests/cupy_tests/creation_tests/test_ranges.py

This supports array-like inputs and an `axis` argument in linspace as implemented in NumPy 1.16+.
closes #2446 
~I have marked this as WIP due to what is currently relatively slow performance for the array-like code path.~ (**edit:** slow for small `num`. For large enough `num`, cupy should always be faster)
A basic translation of the code from numpy 1.17 ends up being pretty slow for small arrays. It can be faster to just run `numpy.linspace` and transfer the result to the GPU in the case of array-like `start` and/or `stop` (as currently done in #2399).
For now, I check if both start & stop are scalars and run the current implementation as a fast path. This preserves performance for this common case, but results in some code duplication.

support array-like start/stop and add axis argument to linspace

---

tests/cupy_tests/core_tests/test_raw.py

Closes #3029 
I was totally unable to make the test skip with either `unittest.skipUnless` or `pytest.mark.skipif` decorators ...

Added a compute capability check for testing grid sync

---

cupy/core/raw.pyx
docs/source/tutorial/kernel.rst
tests/cupy_tests/core_tests/test_raw.py

Close #1703.
This PR adds a public API to `cupy.RawModule`. This enables, for example, the usage of constant memory in `RawKernel`s, which makes it easier for PyCUDA and general CUDA users to migrate to CuPy, part of an ongoing effort tracked in #2450. See also the discussion in #1703.
Note that a Cython wrapper for the CUDA driver API `cuModuleGetGlobal()` already exists, so with this PR all `cuModuleGet*()` functions are exposed to end users via `cupy.RawModule`.

Add `get_global()` to `cupy.RawModule`

---

cupy/core/_routines_manipulation.pxd
cupy/core/_routines_manipulation.pyx
cupy/manipulation/join.py
tests/cupy_tests/manipulation_tests/test_join.py

Numpy supports `out` for both `stack` and `concatenate`.
This PR matches the behavior
https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html
https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

Added `out` parameter to `cupy.concatenate` and `cupy.stack`

---

cupy/cuda/cublas.pxd
cupy/cuda/cublas.pyx
cupy/cuda/cusparse.pxd
cupy/cuda/cusparse.pyx

Modified `size_t` with `intptr_t` for cuSPARSE and cuBLAS as a part of #2716

Use `intptr_t` instead of `size_t` for cuSPARSE and cuBLAS handles

---

cupy/core/__init__.py
cupy/core/_errors.py
cupy/core/_reduction.pyx
cupy/core/_routines_indexing.pyx
cupy/core/_routines_manipulation.pyx
cupy/core/_routines_sorting.pyx
cupy/core/core.pyx
cupy/core/fusion.pyx
cupy/cuda/cub.pyx
cupy/indexing/indexing.py
cupy/manipulation/join.py
cupy/manipulation/rearrange.py
cupy/testing/helper.py
cupy/util.pyx
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/manipulation_tests/test_dims.py
tests/cupy_tests/manipulation_tests/test_join.py
tests/cupy_tests/manipulation_tests/test_transpose.py
tests/cupy_tests/math_tests/test_sumprod.py
tests/cupy_tests/sorting_tests/test_sort.py
tests/cupy_tests/testing_tests/test_helper.py

`numpy.AxisError` was introduced from NumPy 1.13.0.
We decided to drop NumPy<1.15 support from CuPy v8. (#2938)

Remove `IndexOrValueError`

---

cupy/cuda/cupy_cub.cu

Fix `cub_reduction` for `CUPY_CUB_MIN` and float16 arrays

---

cupy/padding/pad.py
tests/cupy_tests/padding_tests/test_pad.py

Now that #2461 was merged, use of `numpy.linspace` within `cupy.pad` can be avoided

cupy.pad: update to use cupy.linspace instead of numpy.linspace internally

---

cupy/cuda/__init__.py
cupy/cuda/memory.pyx

Follow up https://github.com/cupy/cupy/pull/3087#pullrequestreview-360104578
I feel this version (introducing `memory._set_thread_local_allocator()`) is better than `for` loop trick, but not 100% confident.

Minor fix to `using_allocator`

---

cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu

This PR (hopefully) fixes a (yet another) CUB bug, introduced in #2600. We didn't notice that `__half2float` is accessible on host only starting CUDA 9.2 😞 Appveyor was able to catch it, though, see https://github.com/cupy/cupy/pull/2584#issuecomment-587303111. 
cc: @y1r @emcastillo @niboshi

Fix compiler bug when building `cupy.cuda.cub` with CUDA < 9.2 

---

cupy/random/_kernels.py

Fixes #3063
Ref. https://github.com/cupy/cupy/pull/1177#issuecomment-390850953, #1356
Copied the copyright notice from https://github.com/numpy/numpy/blob/v1.15.0/numpy/random/mtrand/randomkit.c

Add copyright notice for Random Kit

---

cupy/__init__.py
cupy/core/_routines_indexing.pxd
cupy/core/_routines_indexing.pyx
cupy/core/core.pxd
cupy/core/core.pyx
cupy/indexing/indexing.py
docs/source/reference/indexing.rst
tests/cupy_tests/indexing_tests/test_indexing.py

I tried to mimic numpy as much as possible. I observed that `PyArray_Compress` in numpy internally calls `nonzero` and `take`. So, I tried to do it in the same way instead of making a separate kernel. I would be happy to receive suggestions on how to implement the kernel for `compress`, if it is required to do so.

Add `compress`

---

cupy/core/internal.pyx
tests/cupy_tests/manipulation_tests/test_shape.py

Fix `reshape` to raise `ValueError` for order 'K'

---

cupyx/fallback_mode/fallback.py
tests/cupyx_tests/fallback_mode_tests/test_fallback.py

**EDIT:**
I've fixed the bug associated with `ndarray.__init__`.
**ORIGINAL:**
This PR is related to #2066 
This PR will support use of `numpy.MaskedArray`, `numpy.chararray`, `numpy.recarray`, `numpy.matrix`. Also, there will be some performance improvement when an `ndarray` is fallbacked consecutively.
And structure of `fallback.ndarray` is changed so that, it doesn't need to explicitly check for in-place updates. In-place changes to an `ndarray` will be confirmed before dispatching it for function execution (both `cupy` and `numpy`) including functions such as `__repr__`.
TO-DO:
* ~~Fix `ndarray` creation using `cupy.ndarray.__init__`, currently all attributes are returned as `NoneType`.~~
Recent changes caused this issue. Currently working to figure it out.

Add `ndarray` variants AND inplace support in `fallback_mode`

---

cupy/__init__.py
cupy/binary/elementwise.py
cupy/core/core.pyx
tests/cupy_tests/test_init.py

Added alias for `invert`. Modified docstring of `invert` to include `bitwise_not` as a note.

Add `bitwise_not` as alias to `invert`

---

tests/cupy_tests/manipulation_tests/test_dims.py
tests/cupy_tests/manipulation_tests/test_join.py
tests/cupy_tests/manipulation_tests/test_rearrange.py
tests/cupy_tests/manipulation_tests/test_shape.py
tests/cupy_tests/manipulation_tests/test_tiling.py
tests/cupy_tests/manipulation_tests/test_transpose.py

Rewrite manipulation tests not to use `numpy_cupy_raises`

---

cupy/indexing/insert.py
tests/cupy_tests/indexing_tests/test_insert.py

Fix #2970 .
`cupy.fill_diagonal()` is currently implemented with `cupy.ndarray.ravel()` as opposed to NumPy that implements `numpy.fill_diagonal()` with `numpy.ndarray.flat`, that keeps off properly filling the value in the main diagonal of an array.
This PR fixes the problem with providing the counterpart of `numpy.flatiter` to touch an array by means of the flatten index space with 1D basic slicing.

Fix `fill_diagonal`

---

cupy/random/generator.py

[backport] use `time.process_time` instead of `time.clock`

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
tests/cupy_tests/core_tests/test_ndarray_indexing.py

Fix #3013 .
This PR fixes the condition to use CUPY_EXPERIMENTAL_SLICE_COPY feature in `ndarray.__setitem__` to check if the supplied `slices` is a slice object.

Fix condition to use slice copy in ndarray.__setitem__

---

cupy/linalg/norms.py
tests/cupy_tests/linalg_tests/test_norms.py

add support for `ord` = 2, -2, and 'nuc' in `cupy.linalg.norm`

---

cupy/core/_routines_math.pyx
cupy/cuda/cub.pxd
cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu
cupy/cuda/cupy_cub.h

Both full and segmented reductions are supported.
TODO:

Support CUB `prod`

---

cupy/indexing/insert.py

Follows #3011 .
This PR reimplement `fill_diagonal` using `ElementwiseKernel` with manual indexing its `raw` argument specifier brings.
At first I thought that I had to make some modification on `ElementwiseKernel` to provide an indexer for each raw argument, but I've found that just `CArray::operator[](ptrdiff_t i)` performs the necessary index computation here so I don't need to touch `ElementwiseKernel`.

Use elementwise kernel in `cupy.fill_diagonal`

---

cupy/statistics/histogram.py
tests/cupy_tests/statics_tests/test_histogram.py

**Description**
This PR updates the `histogram` function to support the `range`, `weights` and `density` kwargs.
It should be easiest to review the 3 commits sequentially as each of them deals with a separate kwarg.
**Details**
The helpers `_get_outer_edges`, `_get_bin_edges` and `_ravel_and_check_weights` are closely based on their NumPy implementations (except that they do not automatically convert array-likes to `ndarray`).
NumPy itself has a fast code path for uniform bins that loops over blocks of ~65k elements using `bincount` and then a second path for non-uniform bins that uses `searchsorted`. I have not made any changes related to those here, but left the current implementation based on `ElementwiseKernel`.
**One question on API:**
In NumPy there is also a `normed` argument, but …

Histogram update: support range, weights and density

---

cupyx/scipy/sparse/coo.py

Current error message is outdated.
The type and the message in this PR is aligned with numpy.

Fix error type and message in `coo_matrix`

---

cupy/cuda/__init__.py
cupy/cuda/stream.pyx
docs/source/reference/cuda.rst
tests/cupy_tests/cuda_tests/test_stream.py

Related to #3126 and https://github.com/pytorch/pytorch/pull/33860
This allows using external streams in CuPy by creating a `ExternalStream` object from a given `cudaStream_t` pointer.
The main use-case for this is to allow interface cupy with other frameworks such as numba or PyTorch. In PyTorch the streams are managed in a pool so although we can trick and reassign the`.ptr` attribute of a CuPy stream to use a Torch managed stream, the RAII interface can delete this stream thus making this approach not safe.
The approach is similar to `cupy.cuda.BaseMemory` and `cupy.cuda.Memory`
TODO: add more tests
cc @leofang

Add `cupy.cuda.ExternalStream`

---

cupy/indexing/insert.py
tests/cupy_tests/indexing_tests/test_insert.py

This is a manual backport of both #3011 and #3139 since #3011 couldn't be easily backported but #3139 was pretty easy.

[backport] Fix `fill_diagonal`

---

.pfnci/py27and35.Dockerfile
.pfnci/wheel_nightly.sh

Remove python2.7 builds from pfnCI.
File names and config file keys should be changed too, but it requires changes to CI configuration.
Kept them now for compatibility
Thanks to @toslunar and @Hakuyume for finding it.

Remove python 2.7 builds

---

docs/source/reference/ndimage.rst

These were missing from the API docs previously. So this just makes sure they are included.
cc @beckernick @awthomp

Document `convolve` and `correlate`

---

cupy/indexing/insert.py

This PR removes an unused argument in `fill_diagonal`.

Remove unused argument in `fill_diagonal`

---

cupy/indexing/insert.py

[backport] Remove unused argument in `fill_diagonal`

---

cupy/cuda/cupy_cub.cu

Follow-up of #3067, in which I made yet another CUB bug 😞 Fortunately the tests in #2598 were able to catch it...
For reduction operations we need a start point, and for `prod` it's 1. On the device, `static_cast<__half>(1)` gives 1 in half precision as expected, but on the host it gives 0 (mdfk!) A correct behavior on host is important for CUB, because it doesn't directly launch a device kernel.
The reason is, quite annoyingly, that a conversion constructor is only available for device functions:
https://github.com/cupy/cupy/blob/106943a0006d27a2c4c164c4799bafcba1428160/cupy/core/include/cupy/_cuda/cuda-10.0/cuda_fp16.hpp#L184
and I have no idea where the zero comes from for host functions...Likely it just returns an uninitialized value?
The current workaround here is quite brute-force: …

Fix CUB-based `cupy.prod` for half precision

---

cupy/cusparse.py
tests/cupy_tests/test_cusparse.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

Fixes https://github.com/cupy/cupy/issues/3061

Allow `MatDescriptor` to be pickle-able

---

cupy/core/_memory_range.pyx

Follow-up of #2949.
```bash
building 'cupy.core._memory_range' extension
gcc -pthread -B /home/leofang/miniconda3/envs/cupy_dev/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FORCE_INLINES=1 -I/usr/local/cuda/include -I/home/leofang/cupy/install/../cupy/core/include -I/home/leofang/sources/cub-1.8.0 -I/home/leofang/miniconda3/envs/cupy_dev/include/python3.7m -c cupy/core/_memory_range.cpp -o build/temp.linux-x86_64-3.7/cupy/core/_memory_range.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cupy/core/_memory_range.cpp: In function ‘std::pair<long int, long int> __pyx_f_4cupy_4core_13_memory_range__get_bound(__pyx_obj_4cupy_4core_4core_ndarray*)’:
cupy/core/_memory_range.cpp:2334:33: …
```

silence sign comparison warning (cont'd) 

---

cupy/cuda/texture.pyx

Suppress this warning: 
```bash
building 'cupy.cuda.texture' extension
gcc -pthread -B /home/leofang/miniconda3/envs/cupy_dev/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FORCE_INLINES=1 -I/usr/local/cuda/include -I/home/leofang/cupy/install/../cupy/core/include -I/home/leofang/sources/cub-1.8.0 -I/home/leofang/miniconda3/envs/cupy_dev/include/python3.7m -c cupy/cuda/texture.cpp -o build/temp.linux-x86_64-3.7/cupy/cuda/texture.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cupy/cuda/texture.cpp: In function ‘int __pyx_pf_4cupy_4cuda_7texture_16TextureReference___init__(__pyx_obj_4cupy_4cuda_7texture_TextureReference*, intptr_t, __pyx_obj_4cupy_4cuda_7texture_ResourceDescriptor*, …
```

avoid enum comparison (-Wenum-compare)

---

cupy/cuda/cupy_cuda_common.h
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx

Close #2768.
This PR does what I suggested in https://github.com/cupy/cupy/issues/2768#issuecomment-596320247:
> As far as I can tell, these attributes are never used in the codebase. How about just removing them entirely so as to suppress the deprecation warning? We're gonna remove them when they are removed from CUDA anyway.

Remove unused, deprecated fields from `cudaPointerAttributes`

---

cupyx/scipy/ndimage/filters.py

This PR improves performance of `convolve` and `correlate` in `cupyx.scipy.ndimage.filter.py`.
I was investing why the performance of `convolve` and `correlate` was slower than expected, and it seems one of the causes is that raw array access via `CArray` is slow.. The issue will be addressed with this PR.
Performance (convolution, fp32)
[sec]  | scipy convolve | cupyx convolve (current) | cupyx convolve (this PR)
-----  | ---------------- | --------------------------- | ---------------------------
x.shape = (4000, 4000), w.shape = (3,3) | 0.225978 | 0.002195 | 0.000670
x.shape = (4000, 4000), w.shape = (5,5) | 0.390014 | 0.005525 | 0.001229
x.shape = (4000, 4000), w.shape = (7,7) | 0.761595 | 0.011325 | 0.002043
x.shape = (300, 300, 300), w.shape = (3, 3, 3) | 0.702484 | 0.028360 | …

Improve ndimage convolve/correlate

---

cupy/cuda/cupy_cusparse.h
cupy/cuda/cusparse.pxd
cupy/cuda/cusparse.pyx
cupy/cusparse.py
tests/cupy_tests/test_cusparse.py

This PR is to support some cuSparse functions, `cusparse<t>csrgeam2` and `cusparse<t>csrgemm2`, mainly for next CUDA release.
Currently, `cusparse<t>csrgeam` and `cusparse<t>csrgemm` are used in `csrgeam` and `csrgemm` in cupy/cusparse.py as backend implementation for sparse matrix addition and multiplication respectively. As you might know, those were deprecated in CUDA 10.1 and will be removed and unavailable in next CUDA release. `cusparse<t>csrgeam2` and `cusparse<t>csrgemm2` remain available in next CUDA release, so you can use these as alternatives.

Support cusparse<t>csrgeam2 and cusparse<t>csrgemm2

---

tests/cupy_tests/core_tests/test_reduction.py

I noticed this reduction test is passed by luck -- the initial accumulation value is not initialized at all, so in the generated kernel we get this line:
```C
...
_i_base += (ptrdiff_t)gridDim.x * _block_stride) {
_type_reduce _s = _type_reduce();     // <--- implicitly zero initialized
ptrdiff_t _i =
...
```
It's fine here only because we are testing `sum`; for `prod`, say, this would be totally wrong. Better be explicit and avoid surprise I think.
With this change, the line of concern becomes
```C
_type_reduce _s = _type_reduce(0);     // <--- the identity '0' enters here
```

Add the missing initialization value in the reduction test

---

cupyx/scipy/special/erf.py
tests/cupyx_tests/scipy_tests/special_tests/test_erf.py

Closes #3151. 
I tested with CUDA 10.0, and it seems the `erfinv` and `erfinvc` from CUDA Math API can already provide the desired behavior, but I'm not sure about other CUDA versions.
I suspect this behavior is different from older SciPy. Maybe we can check that by running CIs first.

Fix `erfinv` & `erfcinv` in `cupyx.scipy.special`

---

cupy/__init__.py
cupy/logic/comparison.py
tests/cupy_tests/logic_tests/test_comparison.py

Add `array_equal`

---

cupy/random/distributions.py
cupy/random/generator.py

Multivariate normal doesn't seem to work... not sure if it's an issue with svd in cuda, or in how the svd is applied in python. Regardless, this PR uses cholesky decomposition, and seems quite fast. Using cholesky also fixes the issue for all versions of cuda where cholesky is working... which is all of them that I have tried.
Removes experimental label.

Fix `cupy.random.multivariate_normal`

---

docs/source/reference/cuda.rst

[backport] Include `UnownedMemory` in the API docs

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py

Initial PR for `__bytes__` for `cupy.ndarray`
Resolves #3007

`__bytes__` for `cupy.ndarray`

---

cupy/core/raw.pxd
cupy/core/raw.pyx
tests/cupy_tests/core_tests/test_raw.py

Close #3193. Close #3200. 
For motivation see the initial PR #3200. This is an alternative attempt (didn't want to force push there).
After offline discussion with @emcastillo, I am convinced to try and utilize the internal per-device cache (`cupy.util.memoize`), so we don't have to do the cache by ourselves in this module. This should greatly simplifies the code.
This PR has the same expected behavior as the previous one: The same `RawKernel`/`RawModule` instance would be usable on any device. Recompiling (and caching) is done internally when necessary.
No backward compatibility is broken in either PR: Note that if the context is not switched, for `RawKernel`, the actual compilation happens at first launch, whereas for `RawModule`, the compilation happens when creating the instance. Both …

Make `RawKernel` and `RawModule` aware of CUDA context (alt)

---

cupy/cuda/cupy_cusolver.h
cupy/cuda/cusolver.pxd
cupy/cuda/cusolver.pyx
cupy/cusolver.py
tests/cupy_tests/test_cusolver.py

This PR makes following two types of cuSolver SVD implementations available in CuPy.
* `gesvdj` ... https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-gesvdj
* `gesvda` ... https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-gesvda
`gesvdj` uses Jacobi method and can give better performance compared with standard [gesvd](https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-gesvd) using QR factorization when matrix size is not large.
`gesvda` is approximate SVD solver and better in performance when a tall skinny matrix.
This is related to  https://github.com/cupy/cupy/issues/3174

Support cusolverDn<t>gesvdj and cusolverDn<t>gesvdaStridedBatched

---

cupy/core/carray.pxi
cupy/core/include/cupy/_cuda/cuda-10.2/cuda_fp16.h
cupy/core/include/cupy/_cuda/cuda-10.2/cuda_fp16.hpp

Attempts to backport ( https://github.com/cupy/cupy/commit/d654524fa1c5aae4df39090d148f5eadce4ebb2c ) from PR ( https://github.com/cupy/cupy/pull/2910 ). Though this doesn't apply cleanly. So have tried to fix it up accordingly. Please check that I've done this correctly.
cc @ksangeek @rlratzel @leofang

Add CUDA 10.2 support

---

cupy/cuda/nvrtc.pyx

This PR solves conda-forge/cupy-feedstock#43 (#3221).
I tested on following environment.
```
Python 3.6.9 (1608da62bfc7, Dec 23 2019, 10:50:04)
[PyPy 7.3.0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
```

Fix byte buffer handling to support PyPy

---

cupy/cuda/cupy_hip.h

I added complex support with BLAS on HIP environment.
Please test this feature by `pytest -m "not slow" tests/cupy_tests/linalg_tests/test_einsum.py`.

Support einsum with complex

---

cupy/core/_kernel.pyx

The change removes the following warning by cython(==0.29.16).
```
[ 1/16] Cythonizing cupy/core/_kernel.pyx
warning: cupy/core/_kernel.pyx:114:4: Unreachable code
```

Remove unreachable code

---

cupy/core/core.pyx

In the implementation of `ndarray.__array_function__`, this change
- removes the antipattern "`getattr` after `if hasattr`", and
- merges the `except AttributeError` logic.

Refactor `__array_function__`

---

cupy/__init__.py
cupy/core/core.pyx
cupy/indexing/__init__.py
cupy/indexing/iterate.py
docs/source/reference/indexing.rst
tests/cupy_tests/indexing_tests/test_iterate.py

Follows #3139 .
I will post several PRs to implement `cupy.flatiter`. It will have similar interface to `cupy.ndarray` as `numpy.flatiter` does to `numpy.ndarray`. For the first, this PR implements its subscript operators so that we can replace `cupy.fill_diagonal`’s implementation using it.
I suppose that `cupy.flatiter` would not provide its iteration interface, as for-loop or the `next` method,  in contrast to `numpy.fatiter` because iteration is essentially serial concept and does not suit to GPU’s pararell computation model.

Implement `cupy.flatiter`

---

cupy/math/sumprod.py
tests/cupy_tests/math_tests/test_sumprod.py

Currently calling `cupy.diff` with an out-of-range axis results in an `IndexError` when trying to access an invalid list element. NumPy explicitly checks the axis and raises an `AxisError` in this case. This PR makes the error types consistent.

make diff return AxisError for an invalid axis

---

tests/cupy_tests/math_tests/test_matmul.py

Fix overfow in `matmul` test

---

cupy/fft/fft.py
tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py

closes #3033
closes #3079
A concrete example of the issue is given in #3033. This PR fixes that use case, adding a corresponding test case over both C and Fortran ordered views.
Please also backport this fix to the ~~7.x and 6.x branches.~~ 7.x branch.

Fix: n-dimensional FFTs must preserve array contiguity when copying a view

---

cupy/indexing/insert.py

Follows #3165 , originated from #2970 .
`cupy.fill_diagonal` is currently implemented with its own elementwise kernel object. This PR fixes it to implement by means of `cupy.flatiter` that is introduced at #3165 as `numpy.fill_diagonal` does.
https://github.com/takagi/cupy/compare/flatiter...takagi:fix-fill-diagonal

Fix `cupy.fill_diagonal` to implement with `cupy.flatiter`

---

cupy/fft/fft.py
tests/cupyx_tests/scipy_tests/fftpack_tests/test_fftpack.py

[backport] Fix: n-dimensional FFTs must preserve array contiguity when copying a view

---

cupy/cuda/function.pxd
cupy/cuda/function.pyx

This PR resolves performance degradation in `function.pyx`.
note: https://github.com/cupy/cupy/pull/2920#pullrequestreview-382636309
- `v8.0.01b`
```
time_raw             - case 10                            :    CPU:    6.197 us   +/- 0.341 (min:    5.882 / max:    6.814) us     GPU:    9.843 us   +/- 1.630 (min:    8.704 / max:   13.056) us
time_raw             - case 100                           :    CPU:    5.816 us   +/- 0.195 (min:    5.621 / max:    6.114) us     GPU:    8.787 us   +/- 0.831 (min:    8.064 / max:   10.400) us
time_raw             - case 1000                          :    CPU:    6.399 us   +/- 0.194 (min:    6.213 / max:    6.682) us     GPU:   10.067 us   +/- 0.403 (min:    9.664 / max:   10.688) us
time_raw             - case 10000                         : …
```

Remove unnecessary `Arg` instantiation in `cuda/function.pyx`

---

cupy/core/_reduction.pyx
tests/cupy_tests/core_tests/test_reduction.py

Closes #3258
When calling `_reduce_dims`, the out_args tuple was empty, so dimensions were never reduced.
`_get_out_args` is the function that initializes the actual arrays if the `out` parameter is an empty list, and it wasn't called until later.
This PR calls `_get_out_args` before and then retrieves its `ndarray` objects, so that dimensions can be effectively reduced. Then it recreated the output as the dimensionality might have changed.
Another way to solve this could be to make `_reduce_dims` allow a list of `Arg` objects as the parameter and modify it accordingly.
`ElementwiseKernel` should be check to verify if this problem also happens there.

Fix `_reduce_dims` call in reduction

---

cupy/core/_routines_indexing.pyx
tests/cupy_tests/indexing_tests/test_indexing.py

[backport] Use larger type to represent index range in `cupy.take`

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/filters.py
cupyx/scipy/ndimage/morphology.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py

This PR is to make following four functions in scipy.ndimage available in CuPy.
* [minimum_filter](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.minimum_filter.html)
* [maximum_filter](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.maximum_filter.html)
* [grey_closing](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.grey_closing.html)
* [grey_opening](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.grey_opening.html)
I think this is relatively easy PR since the core routines required for the functions above are already implemented by https://github.com/cupy/cupy/pull/3216.

Add four functions in scipy.ndimage

---

cupy/cuda/function.pxd
cupy/cuda/function.pyx

note: https://github.com/cupy/cupy/pull/2920#pullrequestreview-382636309
- `master`
```
time_abs             - case        100                    :    CPU:   18.968 us   +/- 0.256 (min:   18.684 / max:   19.358) us     GPU:   23.123 us   +/- 1.272 (min:   21.888 / max:   25.504) us
time_abs             - case        200                    :    CPU:   18.604 us   +/- 0.182 (min:   18.349 / max:   18.823) us     GPU:   22.074 us   +/- 0.479 (min:   21.504 / max:   22.816) us
time_abs             - case        300                    :    CPU:   18.727 us   +/- 0.174 (min:   18.502 / max:   19.000) us     GPU:   22.259 us   +/- 0.787 (min:   21.760 / max:   23.808) us
time_abs             - case        400                    :    CPU:   18.834 us   +/- 0.270 (min:   18.566 / max:   19.258) us …
```

Reduce arg creation cost in `Arg.from_obj`

---

cupy/fft/fft.py
tests/cupy_tests/fft_tests/test_fft.py

Close #3240. This makes the behavior compatible with NumPy.

Raise `IndexError` for R2C/C2R FFT with `axes=()`

---

docs/requirements.txt

Rel #3250 and https://github.com/chainer/chainer-test/issues/571 .
This PR changes the requirements file to specify sphinx 2.x to use on Read the Docs.

Use sphinx 2.x on Read the Docs

---

tests/cupy_tests/math_tests/test_matmul.py

[backport] Fix overfow in `matmul` test

---

cupy/__init__.py
cupy/core/_routines_statistics.pxd
cupy/core/_routines_statistics.pyx
cupy/statistics/meanvar.py
tests/cupy_tests/statics_tests/test_meanvar.py

For the issue #2305
The implementation still lacks the functionality to calculate median for `float16`, `bool` and `complex` dtypes.
- `float16` and `bool` because of `thrust.sort`.
- `complex` because of `cupy.partition`.

Add `cupy.median`

---

tests/cupy_tests/linalg_tests/test_eigenvalue.py

- `testing.numpy_cupy_allclose` supports tuples.
- `xp.argsort` is available.

Simplify `TestEigenvalue`

---

cupy/__init__.py
cupy/math/window.py
docs/source/reference/math.rst
tests/cupy_tests/math_tests/test_window.py

The following PR adds the function equivalent of numpy.kaiser. Most of the functionality required was already added by the ufunc i0, and hence this is a small PR.
The bencmark is as follows,
```
size = 10000
numpy
kaiser              :    CPU: 1032.667 us   +/-93.976 (min:  880.462 / max: 1274.299) us
cupy
kaiser              :    CPU:  257.534 us   +/-11.794 (min:  250.239 / max:  335.450) us     GPU:  261.903 us   +/-12.010 (min:  254.656 / max:  340.000) us
```
```
size = 100000
numpy
kaiser              :    CPU: 8782.974 us   +/-2339.073 (min: 7171.441 / max:15070.544) us
cupy
kaiser              :    CPU:  279.742 us   +/-45.929 (min:  245.857 / max:  520.667) us     GPU:  306.540 us   +/-43.233 (min:  242.912 / max:  533.888) us
```
```
size = 1000000
numpy
kaiser              : …
```

Implementation of `cupy.kaiser`

---

cupy/core/_routines_sorting.pyx
cupy/cuda/common.pxd
cupy/cuda/cupy_common.h
cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx
tests/cupy_tests/sorting_tests/test_sort.py

All kinds of sort functions work with all dtypes now!
~~Ongoing, **DO NOT MERGE!**~~
- ~~msort~~
- ~~lexsort~~
- ~~remove redundant tests~~
- ~~clean up~~
- ~~test for performance regression~~ LGTM

Support all dtypes in every sorting function in `cupy.cuda.thrust`

---

cupy/_sorting/sort.py
cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx
tests/cupy_tests/sorting_tests/test_sort.py

Close #3232, in which two different bugs were reported. Follow-up of #2745 & #3286.  
This PR does two things:
1. code fix: most pointers passed from Cython are of type `intptr_t` (#2455). Shouldn't have to cast them to `size_t`.
2. bug fix: #3232 has two bugs reported:
- `cupy::thrust::_lexsort()` assumes a C-contiguous input but we didn't check it
- lack of NaN handling for real numbers 
Context for the 2nd bug: In #2745 (#3286) when sorting complex (half precision) numbers was supported, NaN handling was added, but I forgot to extend it to single and double precisions 😅 Now this is done in a unified fashion, similar to how it's handled in `cupy/cuda/cupy_cub.cu`. (Perhaps I will do more refactoring later to reduce code repetition.) The master branch fails most of the added tests (for …

Code fix + bug fix for `cupy.cuda.thrust`

---

cupy/padding/pad.py

This should mostly resolve the zero-padding performance issue reported in #3277.
The change to `_as_pairs` reduces argument handling time for the `constant_values`, `end_values` and  `stat_length` kwargs when a scalar is provided.

improve efficiency of cupy.pad for some simple cases

---

cupy/core/_kernel.pyx

Before
```
time_abs             - case        100                    :    CPU:   11.408 us   +/- 0.413 (min:   11.019 / max:   12.159) us     GPU:   15.149 us   +/- 1.590 (min:   13.888 / max:   19.616) us
time_abs             - case        200                    :    CPU:   11.355 us   +/- 0.401 (min:   10.908 / max:   12.262) us     GPU:   14.707 us   +/- 0.768 (min:   13.984 / max:   16.864) us
time_abs             - case       5000                    :    CPU:   11.993 us   +/- 1.310 (min:   10.898 / max:   15.197) us     GPU:  506.054 us   +/- 1.694 (min:  504.576 / max:  510.688) us
time_abs             - case      10000                    :    CPU:   54.580 us   +/-121.037 (min:   11.170 / max:  417.547) us     GPU: 2028.294 us   +/-128.319 (min: 1982.528 / max: 2413.120) us …
```

Improve `ElementwiseKernel` cpu time

---

cupy/cuda/cupy_cuda.h
cupy/cuda/cupy_cuda_common.h
cupy/cuda/cupy_hip_common.h
cupy/cuda/function.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx
cupy/cuda/texture.pxd
cupy/cuda/texture.pyx
docs/source/reference/cuda.rst
docs/source/tutorial/kernel.rst
tests/cupy_tests/cuda_tests/test_texture.py

Takeover from #3197. **Main credit goes to @Fokatu**. Close #2624. 
This is a follow-up of #2432. The surface object API is supported. Although I don't think there're many users who need this capability (compared to texture memory), @Fokatu has shown it's simple to support this in CuPy with little maintenance burden, so I think it's still worth adding. 
With this support, CuPy is now a full (and far better!) replacement for PyCUDA.

Support surface memory in `RawKernel`

---

cupy/core/_routines_sorting.pyx
cupy/core/_routines_statistics.pyx
tests/cupy_tests/statics_tests/test_meanvar.py

~As in NumPy, bool gets converted to double~
~float16 inputs are temporarily converted to float32 for compatibility with `partition`~
~For complex dtypes, `sort` is used because `partition` lacks complex support.~
#3286 removed the need for the above workarounds.
**edit**: 
I updated this PR with enhancements for axis support as well. Let me know if you would prefer to keep that in a separate PR instead.
- Support for axis as a sequence of ints has been added
- when `axis` is out of range, `numpy.AxisError` is now returned instead of `IndexError`.

ENH: support additional dtypes and axis sequences in cupy.median

---

cupyx/scipy/ndimage/_interp_kernels.py
cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

This PR improves the performance and reduces memory usage for the `cupyx.scipy.ndimage.interpolation` module. There should be no change in behavior from the prior implementation.
Memory overhead in various functions like `affine_transform` is greatly reduced by not explicitly generating dense n-dimensional coordinate arrays.
closes #2607
also resolves some issues with performance that were previously reported in: #1168, #2345, #2844
Will post the benchmarks in a follow-up comment, but performance is greatly improved on all cases I tested.
The main downside to this PR is that such template-based code generation is a bit harder to read than the previous implementations, but I tried to add some comments describing what is going on.

rewrite cupyx.scipy.ndimage.interpolation using ElementwiseKernel

---

cupy/core/_carray.pxd
cupy/core/_carray.pyx
cupy/core/_kernel.pxd
cupy/core/_kernel.pyx
cupy/core/_reduction.pyx
cupy/core/_routines_indexing.pyx
cupy/core/_routines_manipulation.pxd
cupy/core/_routines_manipulation.pyx
cupy/core/core.pxd
cupy/core/core.pyx
cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/cudnn.pyx

Declare `shape_t` and `strides_t` as aliases of `vector.vector[Py_ssize_t]` for the readability.

Alias of shape type

---

cupy/cuda/runtime.pyx

Close #3320.
If we need a test for this, we'll need to run it as a subprocess, because somewhere else in the test suite we'll establish contexts for all devices, and this bug won't show up (which is why we didn't see it until now). Let me know if a test is desired.
I think the overhead of extra runtime API calls like `getDevice()` and `getDeviceCount()` are very low, so performance impact, if any, can only come from the usage of a Python list. I could try to do some quick benchmarks if desired, but I think this bug definitely needs to be fixed one way or another.

Ensure runtime context on a per-device basis

---

cupy/__init__.py
cupy/math/window.py
docs/source/reference/math.rst
tests/cupy_tests/math_tests/test_window.py

This PR adds the function cupy.bartlett.
| size(M) |  numpy |  This PR | 
| ----------- | ----------- | ----------- |
| 10 | 0.03 | 0.04 | 
| 100 | 0.01 | 0.04 | 
1000 | 0.02 | 0.04 | 
10000 | 0.08 | 0.04 | 
100000 | 0.97 | 0.04 | 
1000000 | 8.09 | 0.15 | 
10000000 | 109.34 | 1.19 |
Benchmarks for cupy.bartlett
Additionally, while I was implementing the following PR, I saw the implementations of the blackman, hamming and hanning and think that they can be improved significantly using Elementwise kernels. Should I create a new PR for this or implement them in this PR ?

Add cupy.bartlett

---

cupy/math/window.py

This PR adds performance improvements to the following methods
- cupy.blackman
- cupy.hamming
- cupy.hanning
by incorporating Elementwise kernels.
The benchmarks are as follows
for cupy.blackman
size |  numpy |  This PR |  existing |
----- | ------ | ------ | ------ |
10 | 0.03 | 0.03 | 0.39 | 
100 | 0.02 | 0.03 | 0.39 | 
1000 | 0.05 | 0.03 | 0.39 | 
10000 | 0.35 | 0.03 | 0.39 | 
100000 | 4.12 | 0.05 | 0.50 | 
1000000 | 35.42 | 0.16 | 3.25 | 
10000000 | 403.96 | 1.33 | 22.36 | 
for cupy.hamming
size |  numpy |  This PR |  existing |
----- | ------ | ------ | ------ |
10 | 0.04 | 0.04 | 0.44 | 
100 | 0.03 | 0.07 | 0.43 | 
1000 | 0.05 | 0.03 | 0.24 | 
10000 | 0.41 | 0.04 | 0.24 | 
100000 | 3.36 | 0.04 | 0.36 | 
1000000 | 28.83 | 0.15 | 1.66 | 
10000000 | 327.42 | 1.18 | 11.22 | 
for …

Enhancement: Performance Improvements to blackman, hanning and hamming methods

---

cupy/core/_routines_indexing.pyx
tests/cupy_tests/indexing_tests/test_insert.py

Closes #3325
When using scalars calling put,
`ndarray` is called, but `ndarray` takes the shape as parameter  instead of the actual data,
creating incorrect arrays.

Fix `put` when using scalars

---

cupy/core/core.pyx
cupy/math/rounding.py
tests/cupy_tests/core_tests/test_ndarray_math.py

Take over #2330
Closes #2276
--
`cupy.around` is incompatible with `numpy.around` such as `cupy.around(2.5) == numpy.around(2.5)` gives `False` (tested on CuPy 7.0.0b1 vs. NumPy 1.16.4).
This PR fixes the problem, and also solves #2276.
We may need additional fix and/or discussion because there still be incompatible case(s) even with this PR:
* `cupy.around(2**63, -1)` differs from NumPy, the latter does *not* round the last digit,
* corner cases like `cupy.array(255, cupy.uint8).round(-1)` are not exhaustively tested.

`cupy.around` behaves differently from NumPy for EVEN_NUMBER+0.5

---

docs/requirements.txt

[backport] Remove upper restrictions for numpy and scipy in doc build

---

cupy_setup_build.py
docs/source/reference/environment.rst

Support multiple architectures in `CUPY_NVCC_GENERATE_CODE`

---

cupyx/scipy/fft/fft.py

It seems that the current code in `cupyx/scipy/fft/fft.py` that checks for SciPy >= 1.5.0 will always evaluate to False. 
It seems `from _scipy_fft._lib._pep440 import Version` will always fail because the `Version` function lives in  `scipy._lib._pep440`. Also, should we really be importing anything from a private `_lib` folder? (We could use an alternative like `numpy.lib.NumpyVersion` or distutils `LooseVersion` instead)
@peterbell10, can you verify if this fix looks correct to you?

Fix scipy version check in cupyx.scipy.fft

---

cupy/cuda/cupy_cutensor.h
cupy/cuda/cutensor.pyx
cupyx/runtime.py

Cub has no way to retrieve the version number and it is not written in any header that we can parse  :( so it shows `Enabled` instead ...

Show versions of cub and cutensor on `cupy.show_config`

---

cupy/cuda/cupy_cutensor.h
cupy/cuda/cutensor.pyx
cupyx/runtime.py

[backport] Show versions of cub and cutensor on `cupy.show_config`

---

cupy/linalg/decomposition.py
tests/cupy_tests/linalg_tests/test_decomposition.py

Fix `linalg.svd` for 0-sized matrices

---

cupy/indexing/iterate.py
docs/source/conf.py
tests/cupy_tests/indexing_tests/test_iterate.py

This PR implements `flatiter.base` proeprty that is a reference to the array that is iterated over.

Implement `flatiter.base` property

---

cupy/linalg/solve.py

Close #3323
`ormqr` functions were using the same workspace as `geqrf` which is different and causes a memory corruption.

Assign a workpace to `ormqr` functions in `_solve`

---

cupy/indexing/iterate.py
tests/cupy_tests/indexing_tests/test_iterate.py

Follows #3251 .
This PR implements `flatiter.__next__()` special method.
https://github.com/takagi/cupy/compare/flatiter-len...flatiter-next
Note that `flatiter.__next__()` returns an instance of `cupy.ndarray`, as opposed to NumPy's counterpart that returns an element of the iterator's base array, to keep off device synchronization.

Implement `flatiter.__next__()` special method

---

cupy/linalg/decomposition.py

Fix #3327 .
This PR reimplements #2277 to reduce the memory usage of `cupy.linalg.svd` with following CuPy style guideline and having less changes.
Note that the implementation of `cupy.linalg.svd` expects its input `M x N` is C-order and actually computes svd of its Fortran-order transpose `N x M` by means of cuSolver.

Reduce memory usage of `cupy.linalg.svd`

---

cupy/linalg/decomposition.py
tests/cupy_tests/linalg_tests/test_decomposition.py

[backport] Fix `linalg.svd` for 0-sized matrices

---

cupy/core/raw.pxd
cupy/core/raw.pyx

Address #3326 and https://github.com/cupy/cupy/pull/3201#issuecomment-628331367. 
It help reduce the kernel launch overhead, but my dev env is under stress test so I need to find another idle system and do benchmarks 😅

Use local cache in `cupy.RawKernel`

---

cupy/cuda/function.pyx
docs/source/tutorial/kernel.rst
tests/cupy_tests/core_tests/test_raw.py

Fix for Python complex scalar inputs.

Support primitive complex scalar in `RawKernel`

---

cupy/cuda/cufft.pyx

Follow-up of #2644. I overlooked an undocumented CUDA behavior that for `cudaMemcpyAsync`/`cudaMemcpyPeerAsync`, the `stream` argument should reside on the **source** device (see, e.g., [here](https://stackoverflow.com/a/22792494/2344149); I also confirmed it with someone from NVIDIA). If this condition is not met, then CUDA would neglect the input `stream` and instead use its internal stream to do the job (can be checked on nvvp). 
If we don't want to rely on CUDA doing the job for us and prefer to be explicit, it means: 
- for the `'scatter'` operation: all streams should be on the same device as is the source
- for the `'gather'` operation: each device needs one stream. 
This PR addresses this distinction.

Fix the internal streams in multi-GPU Plan1d 

---

cupy_setup_build.py

When building v7 with cuda 8 in windows:
```
fatal error C1128: number of 
sections exceeded object file format limit: compile with /bigobj
```
This just adds bigobj to all the builds in windows for v7, the only drawback for this option seems to be that older linkers can't consume the generated objects.
https://stackoverflow.com/questions/15110580/penalty-of-the-msvs-compiler-flag-bigobj

Fix windows

---

cupyx/time.py
tests/cupyx_tests/test_time.py

Fix `time.repeat` to accumulate duration after GPU synchronization

---

cupy/core/_dtype.pyx
cupy/core/_routines_statistics.pyx

Closes #2780 
dtype `l` is `int32` in windows and `int64` in linux causing `_count_non_nan` to return different types. 
This value is then passed as parameter to _nanvar_core which explicitly declares it as `int64 _count` in its args list.
Fix it by using the datatype `q` which is int64 in both, windows and linux.
The test suite detects this error when running in windows.
I think we should change several of the `l`s in the code base to `q`s to avoid different behaviors

Fix `_count_non_nan` datatype for windows

---

cupy/cuda/compiler.py
tests/cupy_tests/cuda_tests/test_compiler.py

I noticed the max compute capability used in the NVRTC support is slightly outdated, so I updated the values according to https://en.wikipedia.org/wiki/CUDA#GPUs_supported; I wasn't able to find a single table listing all these from CUDA's documentation, so it'd be worth double checking. 
Also, the global cache `_nvrtc_max_compute_capability` is replaced by a per-device cache to deal with heterogeneous environments (see https://github.com/cupy/cupy/issues/3292#issuecomment-616267757).

Get arch per device and support CUDA 9.2+ 

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/measurements.py
docs/source/reference/ndimage.rst
tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

This PR adds the following routines for cupyx.scipy.ndimage
- sum
- mean
- variance
Currently this method uses Elementwise Kernels,I tried to use Reduction Kernel but couldnt get it to work, if possible can someone recommend a way to use Reduction Kernels.
This PR is still a work in progress.
Todo list

Add cupyx.scipy.ndimage sum, mean,standard deviation and variance

---

tests/cupy_tests/creation_tests/test_from_data.py

Follow-up of #3009. See https://github.com/cupy/cupy/pull/3009#issuecomment-579967759. By "large size" we mean the input array has more than INT_MAX bytes in total. Without the patch from #3009 the added test would fail.

Add a test to cover accepting large-size arrays via __cuda_array_interface__

---

cupy/cutensor.py

Fix cuTENSOR routines to raise `ValueError` for invalid arguments

---

setup.py

Travis started installing sphinx 3.1.0,
set it to 3.0.4 while we look for the issue 
https://travis-ci.org/github/cupy/cupy/builds/696302151

Fix sphinx version for travis

---

cupyx/scipy/ndimage/measurements.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

Follows https://github.com/cupy/cupy/pull/3259#discussion_r431205268.
NumPy's `ndarray.sum()` and `ndarray.mean()` use different intermediate dtypes for summation and return a little different results for float16 inputs.
```Python
a = (np.arange(100) / 2).astype(np.float16)
>>> print(a.sum() / a.size)
24.76
>>> print(a.mean())
24.75
```
Because of this, `cupyx.scipy.ndimage` stats functions introduced in #3259 return slightly different results for float16 inputs compared with their SciPy counterparts. This PR fixes the functions to follow SciPy's way to compute such values.

Fix intermediate dtypes for float16 inputs in `cupyx.scipy.ndimage` stats functions

---

cupy/core/_routines_sorting.pyx
cupy/cuda/common.pxd
cupy/cuda/cupy_common.h
cupy/cuda/cupy_thrust.cu
cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx
tests/cupy_tests/sorting_tests/test_sort.py

[backport] Support all dtypes in every sorting function in `cupy.cuda.thrust`

---

cupy/cuda/stream.pyx
tests/cupy_tests/cuda_tests/test_stream.py

Rel. #3316.
When a CuPy stream object set to the current stream is about to be destroyed, the current stream is automatically replaced with `Stream.null`. However, it does not work when the stream is a user-defined null stream, causing the error reported in #3316.
This PR fixes the problem to properly reset the current stream even if a user-defined null stream is used.

Properly reset current stream in case null stream is destroyed

---

cupyx/scipy/ndimage/measurements.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

Follows #3259.
This PR fixes `cupyx.scipy.ndimage` stats functions to support `cupy.bool_`.

Support boolean in `cupyx.scipy.ndimage` stats functions

---

cupy/cuda/cupy_cusparse.h
cupy/cuda/cusparse.pyx
cupy/cusparse.py
cupyx/scipy/sparse/coo.py
cupyx/scipy/sparse/csc.py
cupyx/scipy/sparse/csr.py
tests/cupy_tests/test_cusparse.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py

**Main credit goes to @smarkesini (from his #2790).**
Close #2790. Close #2664.
I don't know why this simple but great change was buried unnoticed 😢 Explained by @smarkesini in https://github.com/cupy/cupy/issues/2365#issuecomment-532133094: 
> I suspect this issue has something to do with '_has_canonical_format' not being set even after calling coosort. There are several places where to set this flag, and I am not sure if the following is the best place, anyway I was focusing on csr and modified the last 3 lines in cupyx/scipy/sparse/coo.py 'tocsr' function as described below and got better performance for my problem (SpMV with a csr matrix ), >100x speedup on the first iteration.
**UPDATE:** While performance improvement was the original concern in this PR, note that this is also a …

Speed up CSR SpMV by orders of magnitude

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py

Related: #589, #734.
Fix the type of the error and error message.
```py
>>> numpy.asarray(cupy.array([1, 2, 3]))
File "/home/imanishi/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
return array(a, dtype, copy=False, order=order)
ValueError: object __array__ method not producing an array
```

Raise `TypeError` in `cupy.ndarray.__array__`

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_join.py

Closes #3283
Concatenate creates an array of pointers, but the device here is not verified so it can fail
with hard to understand errors.
TODO: Add test

Assert that all the pointers are in the same device in `concatenate`

---

cupy/testing/__init__.py
cupy/testing/helper.py
tests/cupy_tests/manipulation_tests/test_shape.py
tests/cupy_tests/polynomial_tests/test_polynomial.py
tests/cupy_tests/polynomial_tests/test_polyutils.py

The behavior of `cupy.testing.empty` is so different from `xp.empty` that I feel confusing. So I want to deprecate this feature and encourage to use `xp.zeros((0,))` instead.

Deprecate `testing.empty`

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

This tests against the CUB SpMV support added in #2698. Style in line with the existing tests and #2598. Not sure why I didn't add this in #2598...
@grlee77 Could you take a look?

Test CUB SpMV

---

cupy/indexing/iterate.py
tests/cupy_tests/indexing_tests/test_iterate.py

Follows #3165.
This PR implements `flatiter.copy()` that returns a copy of the iterator as a 1-D array.

Implement `flatiter.copy()`

---

cupy/linalg/norms.py

[backport] Fix typos in cupy.linalg.det docstring

---

setup.py

(note: currently this configuration is not used by CIs)
Theano is not needed in CuPy (maybe it was inherited from Chainer).

Add optuna and remove theano for doctest requirement

---

tests/cupy_tests/core_tests/test_raw.py

These tests are not guaranteed to work when the compute capability of Device(0) exceeds that of Device(1).

Remove wrong tests in `test_raw.py`

---

cupyx/scipy/sparse/dia.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

In newer scipy released today (1.5.0)
The `dia_matrix.diagonal` method does not raise `ValueError` for invalid values anymore.
Now an empty array is returned instead.
https://github.com/scipy/scipy/blob/v1.5.0/scipy/sparse/dia.py#L323-L324

Fix `scipy.dia_matrix.diagonal` for `scipy==1.5.0`

---

cupy/testing/parameterized.py

[backport] Fix `TypeError` in parameterize test catching `CUDADriverError`

---

cupy/core/core.pxd
cupy/core/core.pyx
cupy/cuda/cupy_cusolver.h
cupy/cuda/cusolver.pxd
cupy/cuda/cusolver.pyx
cupy/cusolver.py
cupy/linalg/decomposition.py
cupy/linalg/util.py
cupyx/linalg/solve.py
tests/cupy_tests/linalg_tests/test_decomposition.py
tests/cupyx_tests/linalg_tests/test_solve.py

This PR adds Cython wrappers for cusolverDn<t>potrfBatched and cusolverDn<t>potrsBatched.
I've implemented batched version of `cupy.linalg.cholesky` using `potrfBatched`. Added test cases that cover input arrays of shape `(..., N, N)`. So now the functionality is the same as in NumPy.
Using `potrsBatched` I've implemented batched version of `cupyx.linalg.invh`, but it does not work yet because cusolver does not yet support `nrhs != 1` for this routine (see remarks in cusolver's documentation). But I think the code is correct and once the issue is solved in cusolver it will be available for use here.

Added wrappers for `cusolverDn<t>potrfBatched` and `cusolverDn<t>potrsBatched`

---

cupy/cuda/cupy_thrust.h
cupy/cuda/thrust.pyx
cupy_setup_build.py
cupyx/runtime.py
install/build.py

Companion PR of 03f4964 from #2584. Starting CUB & Thrust 1.9.9 they are version-locked with each other (in theory, explained below), so this could help detect/debug if there's any incompatibility issue.
* Thrust and CUB have a circular dependency. However, if we use CUB alone, there's a good chance it's decoupled from Thrust, unless iterators are used (see https://github.com/NVlabs/cub/issues/182#issuecomment-631272979). I tested with CuPy that the latest CUB 1.9.10 works with an old Thrust from CUDA 10.0, so I don't think there's any concern here, and this is just for richer config output.

Detect and show Thrust build version

---

cupy/core/core.pyx

[backport] Fix docstring of `tofile()`

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_join.py

[backport] Assert that all the pointers are in the same device in `concatenate`

---

docker/python3/Dockerfile

Related to #2993.
We need to use NumPy<1.18 as the base image contains Python 3.5, but pip is too old to recognize `python_requires` tag, so it tries to install the latest NumPy and build fails.

Update setuptools and pip in docker image

---

cupyx/__init__.py
cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/signaltools.py
docs/source/reference/scipy.rst
docs/source/reference/signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

This PR blocks #3371.
It is an implementation of `scipy.signal.choose_conv_method ` (supporting only 1D inputs currently). One difference from SciPy's behaviour is that it always chooses direct convolution for signed/unsigned integers

Add `choose_conv_method`

---

cupy/cuda/cutensor.pyx

This PR adds new compute types added in cuTENSOR 1.1 mainly to enable users to test NVIDIA A100 TensorCore performance with cuTENSOR.

Support cuTENSOR 1.1

---

cupyx/scipy/sparse/data.py

Use absolute import

---

cupy/testing/__init__.py
cupy/testing/helper.py
tests/cupy_tests/core_tests/test_ndarray_reduction.py
tests/cupy_tests/math_tests/test_sumprod.py
tests/cupy_tests/sorting_tests/test_search.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Follow up of #2598 and #3428. See https://github.com/cupy/cupy/pull/3428#issuecomment-647053948.
cc: @emcastillo

Add mock tests to ensure `cupy.cuda.cub` is used

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/filters.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py

This implements the rank-based filters (median, rank, and percentile filters).
These all use the same logic (in `_rank_filter`) and utilize the same underlying CUDA kernel as the other ndimage filters
just with some adjustments that the `_generate_nd_kernel()` function already allowed for. The biggest piece of CUDA code is the sorting function required for these filters. It chooses either selection or shell sort to be used to establish the rankings. CUB or similar sorts are not used since the sort is done per-kernel instead of with dynamic parallelism (there is 1 small sort to be done for every pixel in an image, should not parallelize within a single sort but instead parallelize across the sorts).
The cutoff of 225 (15x15), for which selection sort is used below and shell sort is used …

ndimage rank-based filters

---

tests/cupy_tests/indexing_tests/test_iterate.py

As suggested at https://github.com/cupy/cupy/pull/3508#pullrequestreview-439666718, this PR fixes some of `flatiter` tests to check NumPy compatibility too.

Check NumPy compatibility in `flatiter` tests

---

cupy/core/_routines_indexing.pyx
cupy/indexing/generate.py
tests/cupy_tests/indexing_tests/test_generate.py
tests/cupy_tests/indexing_tests/test_indexing.py
tests/cupy_tests/indexing_tests/test_insert.py

Fixed to follow the NumPy 1.19 specification.

Fix to raise `ValueError` for invalid clipmode

---

cupy/cuda/cudnn.pyx
cupy/cuda/function.pyx
cupy/cudnn.pyx

Similar to #3020, but I don't know if the input vectors can be empty.
The remaining ones are not of type `std::vector`.
```
% git grep '&.*\[0]'
cupy/cuda/cufft.pyx:        cdef int* shape_ptr = &shape_arr[0]
cupy/cuda/cufft.pyx:            inembed_ptr = &inembed_arr[0]
cupy/cuda/cufft.pyx:            onembed_ptr = &onembed_arr[0]
cupyx/scipy/sparse/compressed.py:        'if (ind == minor) atomicAdd(&answer[0], d);',
cupyx/scipy/sparse/compressed.py:          atomicAdd(&answer_real[0], real);
cupyx/scipy/sparse/compressed.py:          atomicAdd(&answer_imag[0], imag);
```

Use `.data()` for `std::vector`

---

cupy/linalg/einsum.py
tests/cupy_tests/linalg_tests/test_einsum.py

Fixed to follow the NumPy 1.19 specification.

Fix to raise `TypeError` for invalid subscripts in `einsum`

---

cupyx/time.py
tests/cupyx_tests/test_time.py

Closes #3484 
Check with
```python
import cupy
import cupyx
import time
size = 10 ** 8
def single_device():
with cupy.cuda.Device(0):
arr_0 = cupy.ones(size)
arr_1 = cupy.ones(size)
arr_0 * arr_1
def multi_device():
streams = []
with cupy.cuda.Device(0):
arr_0_0 = cupy.ones(size // 2)
arr_0_1 = cupy.ones(size // 2)
with cupy.cuda.Device(1):
arr_1_0 = cupy.ones(size // 2)
arr_1_1 = cupy.ones(size // 2)
with cupy.cuda.Device(0):
arr_0_0 * arr_0_1
with cupy.cuda.Device(1):
arr_1_0 * arr_1_1
print(cupyx.time.repeat(single_device, n_repeat=10))
print(cupyx.time.repeat(multi_device, n_repeat=10, devices=[0,1]))
```

Add multi-gpu support to time

---

cupy/cuda/cupy_cusparse.h
cupy/cusparse.py

Close #3407 
This PR uses `CUSPARSE_VERSION` instead of `CUDA_VERSION` for the various version checks related to cuSparse.
I've confirmed that this works fine with CUDA 10.0, 10.1, 10.2 and 11.0, but all on Linux.
It would be great if you could check to see if it works on Windows as well when you have time.

Use `CUSPARSE_VERSION` instead of `CUDA_VERSION`

---

cupy/core/raw.pyx
cupy_setup_build.py
tests/cupy_tests/core_tests/test_raw.py

Fix https://github.com/cupy/cupy/pull/3486#issuecomment-653145880. There, the CI error occurred because `RawModule` compiles at initialization, not when `get_function()` is called, so in a Read the Docs environment where nvcc is not available, the build fails. Now it's fixed by ~~checking if the build environment has CUDA or not~~ (**UPDATE**) deferring the compilation to when something needs to be fetched.
~~In fact, making this `no_cuda` flag (and potentially a few other ones) available could help some other Cython modules to conditionally compile.~~
cc: @cjnolet

Avoid early compilation when initializing a RawModule instance

---

cupy/core/core.pxd
cupy/core/core.pyx
cupy/core/raw.pxd
cupy/core/raw.pyx
cupy/cuda/compiler.py
cupy/cuda/function.pyx

This PR pertains to #3482. Currently, no output from the nvcc compiler is displayed to stdout. 
The intent of this implementation is to add a `verbose` flag to `RawModule` and `RawKernel` to be able to print nvcc output.
Initial push only modifies `cupy/cuda/compiler.py`.
@leofang I think the parent function is `compile_with_cache` (in `cupy/cuda/compiler.py`). But I haven't quite figured out exactly which functions that call it should be modified to accept the new flag.
```python
def compile_with_cache(
source, options=(), arch=None, cache_dir=None, extra_source=None,
backend='nvrtc', *, enable_cooperative_groups=False,
name_expressions=None, verbose=False):
```
The actual print is performed here.
```python
def _run_nvcc(cmd, cwd, verbose):
try:
stdout = subprocess.check_output(cmd, …
```

Added functionality to print nvcc and nvrtc output

---

cupy/linalg/decomposition.py
cupy/linalg/norms.py
tests/cupy_tests/linalg_tests/test_norms.py

Related to #3522, I added support for `cupy.linalg.slogdet` to handle complex numbers.
This PR also includes a bug fix on `cupy.linalg.decomposition._lu_factor` that incorrectly handled complex ndarrays with cuSolver.

Support batched slogdet with complex numbers

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/filters.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py

This adds implementations for 11 linear filters to `cupyx.scipy.ndimage.filters`. The following are nearly identical to scipy's code, just using the cupy's `convolve`/`convolve1d`/`correlate`/`correlate1d` as appropriate:
- `uniform_filter1d`
- `gaussian_filter1d`
- `generic_laplace`
- `laplace`
- `gaussian_laplace`
- `generic_gradient_magnitude`
- `gaussian_gradient_magnitude`
The following use an additional function making it easier to add any separable linear filters, but otherwise perform very closely to the original scipy's functions:
- `uniform_filter`
- `gaussian_filter`
- `prewitt`
- `sobel`
The function for handle separable filters also now handles the min/max filters when separable (in fact, the code was taken from there to make it work for any set of 1D filters to create an ND …

ndimage common linear filters

---

setup.py

Part of chainer/chainer-test#586.

Add missing `cupy_cub.cu` in package data

---

tests/cupy_tests/linalg_tests/test_norms.py

Fixes to check that the dtypes of return values of `cupy.linalg.slogdet`are equal to those of `numpy.linalg.slogdet`.

Fix `slogdet` tests to check dtypes of return values

---

cupy_setup_build.py

This PR fixes a build issue with CUDA 11.0 GA. "compute_30" is not supported in CUDA 11.
This is related to https://github.com/cupy/cupy/issues/3575

Remove compute_30 when CUDA11

---

setup.py

The following message is output In Python 3.7.
```
% ~/env/chainer/check.sh
/home/okuta/env/chainer37/.direnv/python-3.7.6/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
/home/okuta/env/chainer37/.direnv/python-3.7.6/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
/home/okuta/env/chainer37/.direnv/python-3.7.6/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
```
This PR updates style checker version.

Update style checker version for Python 3.7

---

cupy/cutensor.py
examples/cutensor/contraction.py
examples/cutensor/elementwise_binary.py
examples/cutensor/elementwise_trinary.py
examples/cutensor/reduction.py
tests/cupy_tests/test_cutensor.py

This PR avoids creating `numpy.ndarray` for each operation.
TODO:

Reduce `numpy.ndarray` creation in cuTENSOR operation preparation

---

cupy/sparse/__init__.py
cupyx/scipy/sparse/__init__.py
cupyx/scipy/sparse/construct.py
docs/source/reference/sparse.rst
tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py

The implementation and test cases are largely borrowed from SciPy, with minor tweaks. 
I actually implemented a correct `ElementwiseKernel` to construct the arrays `row`, `col`, and `data` at once (see 7135ec9) instead of following SciPy, but in my local tests I found it's slower, so I abandoned it. I guess it's because the memory access pattern isn't optimal. 
Moreover, the real bottleneck in this function is the three `coo_matrix()` calls. Together they took about 90% of time, so how the rest is implemented really doesn't matter much. I am not sure if this is a defect or something expected, will look into it, but it shouldn't be a blocker.

Add `cupyx.scipy.sparse.kron()`

---

cupyx/scipy/sparse/compressed.py
cupyx/scipy/sparse/coo.py
cupyx/scipy/sparse/csc.py
cupyx/scipy/sparse/csr.py
tests/cupy_tests/test_cusparse.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

This PR brings the current implementation to full compliance with SciPy, but I don't know what's the best way to measure performance impacts...I measured SpMV and do not see slowdown with this PR. Not sure what else I should look into, but I think for compatibility this PR is good to go.
Notes:
1. The property code is largely borrowed from SciPy so that it's easier to maintain and stay compliant.
2. The two `has_*` properties are mainly for compressed matrices (i.e. CSC/CSR); for COO, it doesn't have `has_sorted_indices`, and its `has_canonical_format` is set during creation or when `sum_duplicate()` is called. 
Importantly, COO does not validate this property when it is accessed. 
3. The internal flags `_has_*` are not directly accessed anywhere in the codebase; they are maintained by …

Implement `has_sorted_indices`, `has_canonical_format`, `sort(ed)_indices()` for sparse matrices

---

cupy/cutensor.py

Modified not to use `Descriptor` in `cupy/cutensor.py` [while refactoring cutensor.py](https://github.com/cupy/cupy/pull/2772/files#diff-142bdbde8a244a83c4d0c894c1f1d185L107-L110)

Remove unused descriptor definition

---

cupy/statistics/histogram.py
tests/cupy_tests/statics_tests/test_histogram.py

Resolve conflict of https://github.com/cupy/cupy/pull/3582 and https://github.com/cupy/cupy/pull/3473.

Use `numpy_cupy_array_equal` instead of `numpy_cupy_array_list_equal`

---

tests/cupy_tests/testing_tests/test_helper.py

Taking over #2884 with making appropriate changes.
`raises` was wrapping a function decorated with `for_unsigned_dtypes` and
`for_signed_dtypes`. In this scheme, if an error was raised in any of
the combinations of dtypes, the test would pass, which would be unintended.

Fix negative value test in test_helper

---

cupyx/scipy/sparse/data.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Close #3506.
This PR fixes sparse min/max to support `axis=None`.

Support `axis=None` in sparse min/max

---

cupyx/scipy/sparse/coo.py

This PR fixes cuSPARSE related test failures when matrix format is COO and CUDA version is 10.2 or later.

Change sorting order of COO sparse matrix for suSPARSE

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/special_tests/test_erf.py

[v7] Skip csc and erf tests for `scipy>1.2`

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Rel #3515. Merge #3536 first.
This PR adds missing tests for sparse max with `axis=None`.

Add tests for sparse max with `axis=None`

---

cupy/core/_cub_reduction.pxd
cupy/core/_cub_reduction.pyx
cupy/core/include/cupy/complex/complex.h
cupy/core/include/cupy/complex/complex_inl.h
tests/cupy_tests/core_tests/test_cub_reduction.py
tests/cupy_tests/core_tests/test_raw.py

1. Remove all of the type constraints: I remember I set the limitations due to some errors when running the full test suite, but I could no longer reproduce it (with the latest master). @grlee77's [new `norm` kernels](https://github.com/cupy/cupy/issues/2516#issuecomment-538043247) might also need the support for complex numbers.
2. Add a possible exception to the optimizer: during the optuna optimization `CUDADriverError` could be raised due to out of resource. This was first observed in https://github.com/cupy/cupy/pull/3244#issuecomment-641479088, and I thought by constraining the search range it'd be remedied, but today I encountered it a few more times for different tasks, so apparently this is necessary. 
After adding this, I see that the error is gracefully handled:
```bash
[I …
```

Small fixes for CUB block reduction kernels

---

cupy/core/_routines_math.pyx
cupy/cutensor.py

Use cuTENSOR in `cupy.sum`

---

docs/source/install.rst
docs/source/install_rocm.rst

Fix #3648. This PR backports the doc change from #2584 so that the users know a deep clone is needed.
Thanks to @Nicholas-Mitchell for bringing this up!

[backport] Update Installation Guide

---

cupy/fft/fft.py

This is a minor change to reduce the number of elementwise division kernels called in `fftfreq` and `rfftfreq`.
For `fftfreq` with n=16,  it reduces execution time from ~75 us to ~60 us.
For `fftfreq` with n = 10,000,000 it reduces execution time from ~1.4 ms to 1.0 ms.

improve efficiency of cupy.fft.fftfreq and rfftfreq

---

cupy/__init__.py

Avoid warnings with latest `numpy` of the form:
```
E   DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. Use `complex` by itself, which is identical in behavior, to silence this warning. If you specifically wanted the numpy scalar type, use `np.complex_` here.
```

MAINT: Use builtins directly

---

cupyx/scipy/ndimage/measurements.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

Follows #3259. Merge #3419 first.
This PR fixes the case `cupyx.scipy.ndimage.sum` takes a zero-dimensional input.

Fix `cupyx.scipy.ndimage.sum` taking zero-dimensional input

---

cupy/core/__init__.py

We already exposed the set methods to `cupy.core`. Might as well expose the get methods.

[MNT] Expose accelerator internal API to one level up

---

cupy/cuda/__init__.py
cupyx/runtime.py

After creating `cuda_backends` some imports where not changed and `cupy.show_config` wasn't able to detect cudnn, cutensor and other libraries

Fix missing imports and `cupy.show_config`

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_filters_generic.py
cupyx/scipy/ndimage/_interp_kernels.py
cupyx/scipy/ndimage/_util.py
cupyx/scipy/ndimage/filters.py
cupyx/scipy/ndimage/interpolation.py
cupyx/scipy/ndimage/morphology.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py

This is the final PR to close #2099 and close #3111.
Additionally, the filter code was split into multiple files as it was getting too unwieldy for a single file.
Some notes:
- The `generic_filter()` function cannot exactly match in Cupy and Scipy. Scipy's accepts any Python function with a single `ndarray` parameter and single scalar return value or a wrapped C function with a specific signature. The Cupy version accepts any *fuseable* Python function with the same restrictions (`ndarray` param, scalar return), a `RawKernel` with almost the same C signature (just missing return value) as with Scipy. It also accepts `ReductionKernel` with 1 input and 1 output.
- Support for new fuseable functions is hackish, the `RawKernel` and `ReductionKernel` are significantly more 'legit'
- The …

Ndimage generic filters

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Merge #3639 first.
This PR parameterizes the tests of sparse min/max/argmin/argmax. As argmin/argmax currently do not work with `axis=None`, I make the corresponding tests skip here and will post another PR to fix it.

Parameterize sparse min/max/argmin/argmax tests

---

cupyx/scipy/sparse/data.py

Close #3535. Extracted from #3583. Merge #3656 first.
Currently, sparse min/max/argmin/argmax have `sum_duplicate` parameter that, when `sum_duplicate=False` is supplied, indicates to skip combining duplicate elements prior to the operation. However, the implementation of `sum_duplicate` method immediately returns if a sparse matrix is already canonically formatted so we don't need to specify `sum_duplicate=False` explicitly. This PR removes the parameter.

Remove `sum_duplicate` parameter in sparse min/max/argmin/argmax

---

cupy_backends/cuda/api/runtime.pxd
cupy_backends/cuda/api/runtime.pyx
cupy_backends/cuda/cupy_cuda.h
cupy_backends/cuda/cupy_cuda_common.h

This PR adds support for the `cudaIpc` calls in the API
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html
A simple example of how to use them:
```python
import multiprocessing as mp
import cupy
def child(handler, shape, dtype):
import cupy
data_ptr = cupy.cuda.runtime.ipcOpenMemHandle(handler)
buff = {"data": (int(data_ptr), False), "shape": shape, "typestr": dtype}
class capsule(object):
pass
cap = capsule()
cap.__cuda_array_interface__ = buff
a = cupy.asanyarray(cap)
print(a)
if __name__ == "__main__":
mp.set_start_method("spawn")
a = cupy.arange(10)
handler = cupy.cuda.runtime.ipcGetMemHandle(a.data.ptr)
p = mp.Process(target=child, args=(handler, a.shape, str(a.dtype)))
p.start()
p.join()
```
The example is based in one from …

Expose cuda IPC runtime calls

---

cupyx/scipy/sparse/csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

This PR is to partially support `csr_matrix` division. With this PR, you can divide a sparse matrix in CSR format by a scalar number.
Division by dense or sparse matrix is not supported by this PR. This is partially because the SciPy implementation returns a `numpy.matrix` object as output in such cases, which is not supported by CuPy (AFAIK).

Support CSR matrix division

---

cupyx/scipy/sparse/csr.py

This PR fixes some CSR matrix related test failures on CUDA11.
Although `csrmvEx` is not available in CUDA11, it is sometimes used in sparse matrix vector computation.

Fix sparse matrix related test failures on CUDA11

---

cupy/cuda/cudnn.py
cupy/cuda/profiler.py
cupy/cuda/runtime.py
tests/cupyx_tests/test_runtime.py

Supersedes #3685 
This fixes the issue that `import cupy.cuda.{runtime,profiler,cudnn}` is not working after cupy_backends refactoring.
discussion: https://github.com/cupy/cupy/pull/3681#issuecomment-665093779
(although the code freeze period is already over, we will include this fix to v8b5 as this will break user code)

Fix broken imports for `cupy.cuda.*`

---

cupy_setup_build.py

Fix the issue that rpath generation was expecting that all modules that use shared library are under `cupy.*`.
This is needed for `cuda_backends`.

Fix rpath for wheel build

---

cupy/creation/basic.py
tests/cupy_tests/creation_tests/test_basic.py

closes #3632
`empty` and `zeros` already supported this, but for some reason these two functions did not

support order argument in cupy.ones, cupy.full and cupy.eye

---

cupyx/scipy/sparse/data.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

~~Close #3535.~~
~~Currently, sparse min/max/argmin/argmax have `sum_duplicates` and `nonzero` parameters. However, the SciPy counterparts do not have them and always conduct as `sum_duplicates=True` and `nonzero=False`. This PR removes the parameters from the methods to make compliance with SciPy.~~
Merge #3676 first.
Currently, sparse min/max have `nonzero` parameter that indicates that the operations should take care of explicitly stored elements only in a sparse matrix. However, the parameter is now proposed in https://github.com/scipy/scipy/pull/11899 and is not merged to the SciPy master nor released in its stable release. This PR makes it a keyword-only parameter and marks as experimental for future possible changes.

Mark `nonzero` parameters experimental in sparse min/max

---

cupy/__init__.py
tests/cupy_tests/creation_tests/test_from_data.py

If the object given to `asnumpy` supports `__cuda_array_interface__`, then coerce it to a CuPy `ndarray` and use `.get(...)` to transfer it back to host (as would be done with a CuPy `ndarray`).

Handle `__cuda_array_interface__` in `asnumpy`

---

cupy/cutensor.pyx
cupy_backends/cuda/libs/cutensor.pxd
cupy_backends/cuda/libs/cutensor.pyx
cupy_setup_build.py

This PR adds `cupy_backends/cuda/libs/cutensor.pxd` and cythonizes `cupy.cutensor`.
Further performance improvement will be worked in another PR: #3700

Add `cupy_backends/cuda/libs/cutensor.pxd`

---

cupy/__init__.py
cupy/linalg/__init__.py

Rel #3420.
This PR removes unnecessary imports of `cupy.linalg` as well as making `cupy/linalg/__init__.py` follow NumPy's reference.

Remove unnecessary imports of `cupy.linalg`

---

cupyx/__init__.py
cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/bsplines.py
cupyx/scipy/signal/signaltools.py
tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

I have implemented most of `scipy.signal.signaltools`. This is the first batch that should be the most straightforward since it is just utilizing the ndimage functions which includes:
* `wiener`
* `order_filter`
* `med_filt`
* `med_filt2d`
* `sepfir2d` (which is actually in bsplines.py)
Next batch will be some of the utility functions and functions like `hilbert`. After that will be `convolve` and friends (but those are dependent on #3614). After that, there will be `lfilter` and `sosfilt` and friends. By then I may have the splines completed as well.
Currently there are no formal tests for these but those are coming shortly.

Adding scipy.signal functions that are simple wrappers of ndimage functions

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/fourier.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_fourier.py

This adds the `fourier_shift` function from ndimage. These functions take a Fourier-domain image and apply the complex exponentials that would be needed to give a (circular) shift in the spatial domain. (i.e. based on the [Fourier shift theorem](https://www.dsprelated.com/freebooks/sasp/Shift_Theorem.html)).
It seems like we might already have a utility like `_reshape_nd` here somewhere else, but I'm not sure. If desired we could move it to `cupy.core.internal`.
`_get_output_fourier_complex` was copied from SciPy
The SciPy implementation is in C and could be emulated via an `ElementwiseKernel`. This separable implementation only has to take the complex exponential of a 1d array along each axis rather than at every n-d element, though, so I think it might be faster.

add cupyx.scipy.ndimage.fourier_shift, fourier_gaussian, fourier_uniform

---

cupy/core/core.pyx

Close #3672. Use CUB device reduction to accelerate it. If not available, fall back to the original kernel.
Before: 
```
vdot                :    CPU:   17.272 us   +/- 0.938 (min:   16.300 / max:   39.416) us     GPU-0:  640.646 us   +/-18.809 (min:  630.496 / max:  774.144) us
```
After:
```
vdot                :    CPU:   57.839 us   +/- 6.615 (min:   55.680 / max:  216.692) us     GPU-0:   80.302 us   +/-18.042 (min:   75.776 / max:  232.096) us
```
For some reason CPU overhead is unexpectedly increased...Not sure what I overlooked 😞

Speed up `cupy.vdot`

---

cupy/cuda/cub.pyx

Close #3738.
There are two errors in this function:
1. #3562 mistakenly assumed that it's safe to call `_preprocess_array()` right away, but that function assumes `reduce_axis` and `out_axis` being legitimate. 
2. If an exception is raised (in this case, `_preprocess_array()` raised an unexpected `AssertionError`), we should propagate it.
cc: @grlee77

Fix `can_use_device_segmented_reduce()` for incompatible axes

---

cupy/math/misc.py
cupyx/scipy/signal/signaltools.py

Fixes CI failures.
`cupyx.signal` was removed in the refactor https://github.com/cupy/cupy/pull/3645. I can't fix the import path in `cupy.math.misc` due to circular imports, so moved some implementations from `cupyx.scipy.signal` to `cupy.math.misc`.

Fix circular imports

---

cupyx/scipy/signal/bsplines.py
tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py

test_bsplines.py has been failing randomly due to a bug in scipy where out-of-bounds memory is being read under certain circumstance.
A bug report has been submitted to scipy: https://github.com/scipy/scipy/issues/12691https://github.com/scipy/scipy/issues/12691
See https://github.com/cupy/cupy/pull/3645#issuecomment-671149939 for some other details.

Adding a workaround for even-length inputs to scipy.signal.sepfir2d

---

tests/cupy_tests/cuda_tests/test_nccl.py

Ref #3567.
Also removed `cuda.nccl.get_version() >= 2000` constraints as we no longer support NCCL 1.x.

Fix test to run without NCCL

---

tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py

Fix #3737.
This PR relaxes relative tolerance. https://github.com/cupy/cupy/issues/3737#issuecomment-671760130

Relax tolerance in `TestArrayElementwiseOp::test_doubly_broadcasted_pow`

---

tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py

[backport] Relax tolerance in `TestArrayElementwiseOp::test_doubly_broadcasted_pow`

---

cupy/cusparse.py
tests/cupy_tests/test_cusparse.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

Backports PR ( https://github.com/cupy/cupy/pull/3157 ) to CuPy 7.

[backport] Allow `MatDescriptor` to be pickle-able

---

cupy/fft/fft.py
cupyx/scipy/fft/fft.py
cupyx/scipy/fftpack/fft.py
tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py

Since CUDA 10.1, some of the behavior has changed with cuFFT to align it more closely to that of fftw, modifying the input in `cufftExecC2R`. Due to that, we prevent testing asserting that input wasn't indeed modified and document that as a warning to the user.
See https://github.com/cupy/cupy/issues/3736 for discussion.

Skip FFT input checks for some CUDA >= 10.1 cases

---

cupy/manipulation/rearrange.py
tests/cupy_tests/manipulation_tests/test_rearrange.py

This PR updates axis handling in `cupy.flip` to be consistent with NumPy 1.15+

add multi-axis support to cupy.flip

---

tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/creation_tests/test_basic.py
tests/cupy_tests/indexing_tests/test_generate.py
tests/cupy_tests/indexing_tests/test_insert.py
tests/cupy_tests/linalg_tests/test_einsum.py
tests/cupy_tests/logic_tests/test_type_test.py
tests/cupy_tests/manipulation_tests/test_dims.py

Skip some tests that fail due to recent exception type changes in NumPy 1.19, as discussed in https://github.com/cupy/cupy/issues/3406#issuecomment-673715890 .

[v7] Skip tests failing due to exception type changes in NumPy 1.19

---

cupy/fft/fft.py
cupyx/scipy/fft/fft.py
cupyx/scipy/fftpack/fft.py
tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py

[backport] Skip FFT input checks for some CUDA >= 10.1 cases

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

[v7] Avoid testing exception type match on NumPy 1.19+

---

cupy/creation/basic.py
tests/cupy_tests/creation_tests/test_basic.py

[backport] support order argument in cupy.ones, cupy.full and cupy.eye

---

cupy/core/carray.pxi
cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.h
cupy/core/include/cupy/_cuda/cuda-11.0/cuda_fp16.hpp
cupy/cuda/compiler.py
cupy/cuda/cupy_cuda_common.h
cupy/cuda/cupy_cudnn.h
cupy/cuda/cupy_cusparse.h
cupy/cuda/cusparse.pxd
cupy/cuda/cusparse.pyx
cupy/cuda/runtime.pxd
cupy/cuda/runtime.pyx
cupy/cudnn.pyx
cupy/cusparse.py
cupy_setup_build.py
cupyx/scipy/sparse/csc.py
cupyx/scipy/sparse/csr.py
install/build.py
tests/cupy_tests/cuda_tests/test_compiler.py
tests/cupy_tests/test_cudnn.py
tests/cupy_tests/test_cusparse.py

Backport of #3405 + #3578 + #3183 (those all are needed to build on CUDA 11.0 so cannot be separated)

[backport] Support CUDA 11.0

---

docs/source/contribution.rst
docs/source/index.rst
docs/source/install.rst
docs/source/reference/environment.rst
docs/source/reference/index.rst

* Clean up the installation guide
* #3671 (Support cuDNN 7.6 and 8.0)
* #3630 (Support NumPy 1.19)
* #3643 (Drop support for NumPy 1.15 or earlier)
* #3631 (Drop support for SciPy 1.2 or earlier)
* #3521 (Declare baseline NumPy/SciPy version)
* #3530 (Add docs to build cub module in Ubuntu 16.04 and RHEL 6/7)
* Fix NVCC environment variable missing from the runtime table
* Move developer tips (editable mode & ccache) to contributor guide

Update docs for v8

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

Skip test if scipy>=1.5.0, see https://github.com/cupy/cupy/issues/3469 for the fix in v8.

[v7] Skip TestDiaMatrixScipyComparison failing with scipy>=1.5.0

---

cupy/statistics/correlation.py

This PR avoids the import error that occurred on my environment when `cupy.correlate()` used.
I'm not sure why, but I could not call a routine `cupyx.scipy.signal.choose_conv_method()` within a file `cupy/statistics/correlate.py`, so instead I used `cupy.math.misc._choose_conv_method()`. 
```
$ python -c "import cupy; cupy.show_config()"
CuPy Version          : 8.0.0b5
CUDA Root             : /usr/local/cuda-11.0.2
CUDA Build Version    : 11000
CUDA Driver Version   : 11000
CUDA Runtime Version  : 11000
cuBLAS Version        : 11100
cuFFT Version         : 10200
cuRAND Version        : 10201
cuSOLVER Version      : (10, 5, 0)
cuSPARSE Version      : 11100
NVRTC Version         : (11, 0)
Thrust Version        : 100909
CUB Build Version     : 100909
cuDNN Build Version   : None
cuDNN …
```

Fix cupy.correlate

---

cupyx/scipy/sparse/_index.py

Speed up `_csr_row_slice` implemented in #3657.
(cc: @cjnolet)
- Current master
```
- name = major_slice_with_step, major = slice(1, 2000, 2), minor = slice(1, 500, 1), format = csr, density = 0.5, dtype = float32, n_rows = 15000, n_cols = 15000
cupy.sparse         :    CPU: 8381.574 us   +/-273.936 (min: 8333.696 / max:11354.615) us     GPU-0: 8443.801 us   +/-270.144 (min: 8396.800 / max:11375.616) us
- name = major_slice_with_step, major = slice(1, 2000, 2), minor = slice(1, 500, 1), format = csr, density = 0.5, dtype = float32, n_rows = 15000, n_cols = 15000
cupy.sparse         :    CPU: 8353.152 us   +/- 8.223 (min: 8333.645 / max: 8372.479) us     GPU-0: 8415.525 us   +/- 8.251 (min: 8395.776 / max: 8434.688) us
- name = major_slice_with_step, major = slice(1, 3000, 2), minor = …
```

Improve 2D sparse row slicing

---

cupyx/scipy/sparse/data.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Close #3474.
~~This PR fixes sparse `min` and `max` to take a negative `axis`. I'll parameterize its test in another PR.~~
Merge #3656 first. This PR fixes sparse min/max/argmin/argmax to take a negative `axis`.

Support negative `axis` in sparse min/max/argmin/argmax

---

cupyx/scipy/ndimage/filters.py

This PR improves the performance of `median_filter` and `rank_filter`.
The current implementation sorts it in ascending order after loading the data to registers and then retrieves the median, but you don't need to sort it completely if you just want to get the median. So, this PR uses a kind of incomplete sort to reduce the amount of comparisons. As you can seen below, for filter sizes of 15x15 or smaller, the performance improvement is about 2x.
* time-mf.py:
```
import cupy
import cupyx
import cupyx.scipy
import cupyx.scipy.ndimage
w, h = 1920, 1080 
print('w, h = {}, {}'.format(w, h))
a = cupy.random.rand(w, h, dtype=cupy.float32)
for size in 3, 5, 7, 9, 11, 13, 15:
name = 'median_filter(' + str(size) + 'x' + str(size) + ')'
perf = cupyx.time.repeat(cupyx.scipy.ndimage.median_filter, …
```

Improve median_filter, rank_filter and percentile_filter

---

cupy/__init__.py
cupy/_environment.py
cupy/cuda/cudnn.py
cupyx/tools/install_library.py
tests/cupyx_tests/tools_tests/test_install_library.py

This implements #3724.
* Download the latest supported cuDNN by:
```
python -m cupyx.tools.install_library --library cudnn --cuda 11.0
```
Libraries are extracted to `~/.cupy/cuda_lib/11.0/cudnn/8.0.2/` (actual shared libraries are placed like `~/.cupy/cuda_lib/11.0/cudnn/8.0.2/lib64/libcudnn.so.8.0.2`)
* Warn when importing cuDNN if the package is installed via wheels (`cupy/_wheel.json` exists) and library could not be loaded.
This preloading is only performed in wheel packages (from PyPI).
TODO:

Implement library preloading for wheels

---

cupy/core/__init__.py
cupy/core/core.pxd
cupy/core/core.pyx
docs/source/reference/environment.rst
tests/cupy_tests/math_tests/test_matmul.py

This PR allows users to use TF32 for single precision matrix multiply computation on A100 GPU.
You can enable use of TF32 by setting a environment variable `CUPY_TF32=1`. 
This is related to https://github.com/cupy/cupy/issues/3602.

Support TF32

---

cupy/__init__.py
cupy/_sorting/__init__.py

Rel #3420.
This PR removes unnecessary imports from `cupy._sorting` submodule.

Remove unnecessary imports in `cupy._sorting`

---

cupy/__init__.py
cupy/sparse/__init__.py
cupyx/linalg/sparse/solve.py
cupyx/scipy/sparse/construct.py
examples/stream/cusparse.py
tests/cupy_tests/test_numpy_interop.py
tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py

Close #3773.
This PR raises a deprecation warning for `cupy.sparse` package as discussed in #3773.

Deprecate `cupy.sparse` package

---

tests/cupy_tests/test_cudnn.py

Follow-up #3731.
The test fails to run in environment without cuDNN.

Fix test to run without cuDNN

---

cupyx/scipy/linalg/special_matrices.py
cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/measurements.py

Resolve https://github.com/cupy/cupy/issues/3821.
Current CuPy's codebase does not have any circular imports, but it occurs if we try importing `cupyx.scipy.***` from `cupy/***/***.py`.

Resolve circular imports between `cupy` and `cupyx.scipy`

---

cupyx/scipy/sparse/_index.py
cupyx/scipy/sparse/compressed.py
cupyx/scipy/sparse/csr.py

Split `_get_csr_submatrix` into `_get_csr_submatrix_major_axis` and `_get_csr_submatrix_minor_axis`, and reduced redundant operations in `getrow`, `getcol` and `_get_submatrix` methods.
- Current master
```
- name = major_slice_minor_all, major = slice(1, 500, None), minor = slice(None, None, None), format = csr, density = 0.5, dtype = float32, n_rows = 15000, n_cols = 15000
cupy.sparse         :    CPU:  898.847 us   +/-22.038 (min:  884.982 / max: 1584.682) us     GPU-0:  936.310 us   +/-21.587 (min:  923.648 / max: 1607.680) us
- name = major_slice_minor_all, major = slice(1, 500, None), minor = slice(None, None, None), format = csc, density = 0.5, dtype = float32, n_rows = 15000, n_cols = 15000
cupy.sparse         :    CPU:17697.888 us   +/-10.398 (min:17671.201 / max:17723.284) us …
```

Improve CSR matrix `getrow`, `getcol` and some slicing

---

cupy/core/raw.pyx
tests/cupy_tests/core_tests/test_raw.py

Closes #3554 
Takes over #1889 (thanks @leofang!)
Tried to add tests, but it is hard to assert wether the compiler is called or not using mock due to cython issues and memorization issues.

Add a `compile` method for `RawKernel` and `RawModule`

---

cupy/statistics/histogram.py
tests/cupy_tests/statics_tests/test_histogram.py

In my environment, histogram test is failed with float16.
I use GeForce GTX Titan X (sm_52). 
```
% pytest tests/cupy_tests/statics_tests/test_histogram.py -s
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.7.6, pytest-4.1.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/okuta/env/chainer37/cupy, inifile: setup.cfg
collected 88 items
tests/cupy_tests/statics_tests/test_histogram.py .....................................................................................dtype is <class 'numpy.float16'>
F..
=================================================================================================== FAILURES …
```

Fix float16 ndarray input in histogram with CUB

---

cupy/sparse/__init__.py
cupy/sparse/linalg/__init__.py

Fix `cupy.sparse.*` deprecation

---

cupy/cuda/__init__.py
cupy/cuda/memory.pxd
cupy/cuda/memory.pyx
docs/source/reference/cuda.rst
tests/cupy_tests/cuda_tests/test_memory.py

This allows cupy to perform memory allocation from a given python interface.
I.e. if the pytorch allocator is exposed in python, it can be used through this new `PythonFunctionAllocator` class.
The difference with `CFunctionAllocator` is that the later uses function pointers that are not easily callable from python and limiting the interoperability with other tools.

Add `PythonFunctionAllocator`

---

docs/source/upgrade.rst

Closes #3516
This guide is generated from no-compat labelled PRs: https://github.com/cupy/cupy/issues?q=label%3Ano-compat
Note that no-compat changes between v8 pre-releases (alpha/beta/rc) are excluded from this guide.

Add upgrade guide for v8

---

MANIFEST.in
cupy/core/include/cupy/README.md
setup.py

During the verification process, I found that CUB source tree is not bundled in CuPy wheels.

Fix cub not bundled in wheels

---

cupy/_environment.py
cupy_setup_build.py

After `cupy_backends` separation cuDNN bundled in wheels are not loaded on Windows.
The following description only applies for Windows. (Linux behavior is different).
Currently we are copying two DLLs in wheels:
- `nvToolsExt64_1.dll` (used from `cupy.cuda.nvtx`)
- `cudnn64_7.dll` (used from `cupy_backends.cuda.libs.cudnn`)
In wheels, DLLs are placed under `cupy/cuda/` directory. This is because DLLs are looked up from the same directory as the Python extension module requiring that DLL. This assumption was OK until `cupy_backends` separation.
This PR changes the path to place shared library to `cupy/.data/lib` (which is the same as Linux), and add that directory to `PATH` (for Python 3.7 or earlier) or DLL lookup directory `os.add_dll_directory` (for Python 3.8+).
TODO: I'm now testing …

[WIP] Fix wheel not loading bundled cuDNN on Windows

---

cupy/cuda/cudnn.py
cupyx/runtime.py
tests/cupyx_tests/test_runtime.py

In #3732, `cupyx/runtime.py` was fixed to use `cupy.cuda.cudnn` but this was incorrect.
`cupyx/runtime.py` is automatically imported when doing `import cupy`, so preloading warnings for cuDNN will be displayed just by doing `import cupy` if cudnn is unavailable.

Fix not to use cupy.cuda.* from cupy codebase

---

cupyx/scipy/sparse/_index.py
cupyx/scipy/sparse/compressed.py

- Current master
```
- name = major_slice_with_step, major = slice(1, 2000, 2), minor = slice(1, 500, 1), format = csr, density = 0.5, dtype = float32, n_rows = 15000, n_cols = 15000
cupy.sparse         :    CPU: 2618.350 us   +/-37.772 (min: 2603.562 / max: 3321.213) us     GPU-0: 2682.434 us   +/-35.877 (min: 2667.520 / max: 3347.456) us
- name = major_slice_with_step, major = slice(1, 2000, 2), minor = slice(1, 500, 1), format = csr, density = 0.5, dtype = float32, n_rows = 15000, n_cols = 15000
cupy.sparse         :    CPU: 2615.678 us   +/- 4.734 (min: 2602.753 / max: 2630.037) us     GPU-0: 2680.169 us   +/- 4.704 (min: 2667.520 / max: 2696.192) us
- name = major_slice_with_step, major = slice(1, 3000, 2), minor = slice(1, 5000, 1), format = csr, density = 0.5, dtype = float32, …
```

Use `_csr_row_index` for CSR matrix major-axis slicing with step

---

tests/cupy_tests/core_tests/test_carray.py

I locally confirmed this test pass on Windows.

Fix 32-bit boundary test to run on Windows

---

cupyx/scipy/sparse/_index.py
cupyx/scipy/sparse/compressed.py

[backport] Use `_csr_row_index` for CSR matrix major-axis slicing with step

---

tests/cupy_tests/cuda_tests/test_cudnn.py

[backport] Fix test fail when cudnn is unavailable

---

tests/cupy_tests/core_tests/test_carray.py

[backport] Fix 32-bit boundary test to run on Windows

---

cupy/cuda/function.pyx
tests/cupy_tests/core_tests/test_raw.py

This PR fixs an issue when a kernel is launched by cuLaunchCooperativeKernel().
When launching a kernel with [cuLaunchCooperativeKernel()](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__EXEC.html#group__CUDA__EXEC_1g06d753134145c4584c0c62525c1894cb), the kernel grid size must not exceed the limit determined by [cuOcupancyMaxActiveBlocksPerMultiprocessor()](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__OCCUPANCY.html#group__CUDA__OCCUPANCY_1gcc6e1094d05cba2cee17fe33ddd04a98). It looks the current implementation requires the user to select a grid size that meets this limit, but I don't think it's realistic to ask the user to do this, as this limit varies with kernel register usage, number of SMs of GPUs used, etc. Please see …

Fix cooperative kernel launch

---

cupy/core/core.pyx

Closes https://github.com/cupy/cupy/issues/3532
This PR improves the accuracy of `cupy.around` for complex arguments a little.
```
print(cp.around(0.1234567,decimals=4))
print(np.around(0.1234567,decimals=4))
print(cp.around(0.1234567+0.1234567j,decimals=4))
print(np.around(0.1234567+0.1234567j,decimals=4))
```
Output (current implementation):
```
0.1235
0.1235
(0.12350000000000001+0.12350000000000001j)
(0.1235+0.1235j)
```
Output (this PR):
```
0.1235
0.1235
(0.1235+0.1235j)
(0.1235+0.1235j)
```

Improve accuracy of cupy.around

---

cupyx/scipy/__init__.py

Rel #3420.
This PR hides private names in `cupyx/scipy/__init__.py`.

Hide private names in `cupyx/scipy/__init__.py`

---

cupyx/scipy/sparse/csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Follows-up #3680.
Some dtypes were not compatible with SciPy.  Moreover, some of the result values were wrong due to unsafe casting.
```
>>> (sparse.csr_matrix(cupy.array(1+2j))/cupy.array(3+4j)).todense()  # ok
array([[0.44+0.08j]])
>>> (sparse.csr_matrix(cupy.array(1+2j, 'F'))/cupy.array(3+4j)).todense()  # not ok
/path/to/cupy/_creation/from_data.py:41: ComplexWarning: Casting complex values to real discards the imaginary part
return core.array(obj, dtype, copy, order, subok, ndmin)
array([[0.12+0.24j]], dtype=complex64)
```

Fix dtype in CSR matrix division

---

cupyx/scipy/sparse/csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

[backport] Fix dtype in CSR matrix division

---

docs/source/reference/sorting.rst

Follow-up of #2726. Close #1274.

Add `cupy.searchsorted` to doc

---

cupy/cuda/cufft.pyx
cupy/fft/fft.py
tests/cupy_tests/cuda_tests/test_cufft.py

Follow-up of #2644. Close #1429, close #2742, and address https://github.com/cupy/cupy/issues/2742#issuecomment-608951598.
This PR supports `Plan1d.fft(a, b, direction)` with `a` and `b` being NumPy arrays. The main purpose is to transform a massive dataset that single GPUs cannot hold (which to me is one of the biggest motivations to do multi-GPU FFTs). 
No real code is added in this PR, only tests --- all of the work was done in #2644, but the NumPy support at both low- and high- levels were commented out in 3e2b7d0 and 705fe1a, respectively, and this PR restores the former so that advanced users can allocate and use `Plan1d` if needed. **This PR does not affect any high-level APIs** such as `cupy.fft.fft()`.
I also made a few variables cdef'd, but this is just a very minor code fix.

Proposal: Support transforming NumPy arrays with multi-GPU `Plan1d`

---

docs/source/reference/sorting.rst

[backport] Add `cupy.searchsorted` to doc

---

cupyx/scipy/__init__.py

[backport] Hide private names in `cupyx/scipy/__init__.py`

---

cupy_backends/cuda/cupy_cuda.h
cupy_backends/cuda/cupy_hip.h
cupy_backends/cuda/cupy_hip_common.h
cupy_setup_build.py
install/build.py

rocTX seems to be NVTX's counterpart on ROCm. `tests/cupy_tests/prof_tests/test_range.py` and `tests/cupy_tests/cuda_tests/test_nvtx.py` passed locally.

ROCm: Support rocTX

---

cupyx/scipy/sparse/csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py

Fix `csr_matrix._get_intXslice` for step < 0 case

---

cupy/cusolver.py
cupy/linalg/solve.py
tests/cupy_tests/test_cusolver.py

This PR changes the solver used in `cupy.linalg.solver` to an LU decomposition based solver, so-called **gesv**.
As you know, `numpy.linalg.solve` uses **gesv** as its solver, while `cupy.linalg.solve` uses a QR decomposition based solver. There must have been some reason for this, but I think it is better to use **gesv** or equivalent solver in `cupy.linalg.solve` as well if you want to be compatible with numpy. In fact, **gesv** is a combination of **getrf** and **getrs**, and cuSOLVER supports them. This PR uses them to implement a **gesv**-equivalent routine, `cupy.cusolver.gesv`, and calls it from `cupy.linalg.solve`.

Use LU-decomposition based solver in cupy.linalg.solver

---

cupy/__init__.py
cupy/math/sumprod.py
docs/source/reference/math.rst
tests/cupy_tests/math_tests/test_sumprod.py

closes #1270
This PR ports the gradient function from `cupyimg` to here. It is based closely on the NumPy implementation.
This had previously been started, but abandoned in #3233. The test cases added here are more comprehensive and run for all dtypes for various spacing, `axis` and `edge_order` combinations.
In https://github.com/cupy/cupy/pull/3233#issuecomment-605736667, @asi1024 suggested possibly using an `Elementwise` kernel, but at least for the uniform spacing case, I don't think it is likely to be beneficial. At least, I tried timing the current `cupy.diff` vs. using `Elementwise` convolution via `cupy.correlate(data, [-1, 1])` and this tended to be slower unless a difference of order >=4 was used.

ENH: add cupy.gradient

---

cupy/_version.py

This release fixes the packaging error of the source distribution published on PyPI.
* `RuntimeError: Missing file: cupy/cuda/cub.cpp`
* `RuntimeError: Missing file: cupy/cuda/cutensor.cpp`

[v7] Post release 1 for v7.8.0

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/morphology.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py

This PR adds `binary_erosion`, `binary_dilation`, `binary_opening`, `binary_closing`, `binary_hit_or_miss`, `binary_propagation`, `binary_fill_holes`, `generate_binary_structure` and `iterate_structure`.
The only new kernel is the one corresponding to binary erosion. I was able to mostly reuse the existing utility `_filters_core._generate_nd_kernel`, but did have to add a couple of arguments to get it to work for this case. @coderforlife, please take a look if you have a chance.
All other binary morphological operations are built on top of `binary_erosion`. Some of the specific data arrays used in the tests were borrowed from SciPy's test suite.
The only feature in SciPy that is not implemented here is the case where `iterations > 1` and `brute_force=False`. SciPy uses a different …

add all binary morphology functions to cupyx.scipy.ndimage

---

cupy_backends/cuda/cupy_hip.h
cupy_backends/cuda/libs/cupy_cusolver.h
cupy_backends/cuda/libs/cusolver.pxd
cupy_backends/cuda/libs/cusolver.pyx

Follow up of #3950. For some reason I didn't catch the bug that when calling `cupy.show_info()` `CUSOLVERError` was raised (perhaps my local build was dirty):
```python
>>> cp.show_config()
File "cupy_backends/cuda/libs/cusolver.pyx", line 722, in cupy_backends.cuda.libs.cusolver.check_status
raise CUSOLVERError(status)
cupy_backends.cuda.libs.cusolver.CUSOLVERError: rocblas_status_not_implemented
Exception ignored in: 'cupy_backends.cuda.libs.cusolver.getProperty'
File "cupy_backends/cuda/libs/cusolver.pyx", line 722, in cupy_backends.cuda.libs.cusolver.check_status
raise CUSOLVERError(status)
cupy_backends.cuda.libs.cusolver.CUSOLVERError: rocblas_status_not_implemented
Traceback (most recent …
```

ROCm: fix rocBLAS and rocSOLVER version displays

---

cupyx/scipy/sparse/_index.py
cupyx/scipy/sparse/compressed.py

Blocked by #3975 
- `master`
```
- name = major_slice, major = 30, minor = 30, format = csr, density = 0.5, dtype = float32, n_rows = 15000, n_cols = 15000
cupy.sparse         :    CPU:  347.650 us   +/-62.985 (min:  338.049 / max: 3612.037) us     GPU-0:  353.839 us   +/-63.345 (min:  344.064 / max: 3636.224) us
```
- this PR
```
- name = major_slice, major = 30, minor = 30, format = csr, density = 0.5, dtype = float32, n_rows = 15000, n_cols = 15000
cupy.sparse         :    CPU:  109.048 us   +/-39.150 (min:  105.948 / max: 3626.384) us     GPU-0:  114.418 us   +/-39.267 (min:  110.592 / max: 3641.344) us
```

Improve cupyx.scipy.sparse int x int indexing

---

cupy/_statistics/histogram.py
tests/cupy_tests/statistics_tests/test_histogram.py

`cub.device_histogram` assumes following dtype combination.
-  same float dptye `x` and `bin_edge` 
- `x` is `integer` dtype, `binedge` is `double` dtype

Add different dtype input test in histogram

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/morphology.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py

This PR adds the four remaining greyscale morphology functions: `morphological_gradient`, `morphological_laplace`, `white_tophat`, `black_tophat`. In combination with gh-3907, this completes CuPy's coverage of `scipy.ndimage.morphology` module with the exception of `distance_transform_*`.
The implementations here are simple as they just rely on the existing `grey_erosion` and `grey_dilation` functions.

Add remaining greyscale morphology operations to `cupyx.scipy.ndimage`

---

cupyx/scipy/linalg/decomp_lu.py
tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py

This PR adds support for complex dtypes to `cupyx.scipy.linalg.lu_factor` and `cupyx.scipy.linalg.lu_solve`.
This is related to https://github.com/cupy/cupy/pull/3995.

Add complex dtype support to cupyx.scipy.linalg.lu_factor/solve

---

cupyx/scipy/sparse/_index.py
cupyx/scipy/sparse/compressed.py
cupyx/scipy/sparse/csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py

[backport] Add compressed sparse `__setitem__`

---

cupyx/scipy/linalg/decomp_lu.py

This PR fixes docs of `cupyx.scipy.linalg.lu_factor` as now it support complex dtypes. This is related to https://github.com/cupy/cupy/pull/4002.

Fix docs of cupyx.scipy.linalg.lu_factor

---

cupy/cuda/compiler.py

I noticed `ls.add_ptr_data()` took about 20% of time in `_compile_with_cache_cuda()`, but it's actually not needed unless we are doing separate compilation and need to link with other input files/data. Otherwise, we can just pass the generated PTX to `cuModuleLoad()` which should work just fine.

Avoid using CUlinkState unless absolutely necessary

---

codecov.yml

Codecov annotations are bit cluttering when reviewing so we decided to disable it.
Confirmed the config is valid using `curl --data-binary @codecov.yml https://codecov.io/validate`.

Disable github checks annotations of Codecov

---

cupy/fft/_cache.pyx
docs/source/reference/fft.rst
docs/source/reference/plan_cache.rst

Follow up of #3730. This PR moves `cupy.fft._cache.PlanCache` from the auto summary to a separate page, as it is meant to be a private class (for now). But, this change introduces a warning in Sphinx, which I am not quite sure how to fix, although it's certainly harmless (and intended):
```
...
pickling environment... done
checking consistency... /home/leofang/dev/cupy_rocm3.5.0/docs/source/reference/generated/cupy.fft._cache.PlanCache.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
...
```
In addition, I also fixed a few hyperlink issues in the docstrings.

Improve the plan cache documentation

---

cupy/cuda/memory.pyx

Looks like the managed memory is not freed even after `free_all_blocks()` is called, see https://stackoverflow.com/q/63998616/2344149. I checked this PR is in effect by monitoring `top` and `nvidia-smi`.

Fix managed memory leak

---

tests/cupy_tests/test_ndim.py

Follow-up of #3060. Changed `assert` to `return` (https://github.com/cupy/cupy/pull/3060#discussion_r476174676).

Fix `cupy.ndim` test style

---

cupy/cuda/cufft.pyx

Follow up of #3102. Close #4009. Thanks to @plamenivanov257 for reporting.

Fix typos in `cupy.cuda.cufft`

---

cupy_backends/cuda/libs/cutensor.pyx

[backport] Use `__dealloc__` instead of `__del__` for cdef class

---

cupy/__init__.py

Rel #3420.
This PR hides private names in `cupy/__init__.py`.

Hide private names in `cupy/__init__.py`

---

cupy/__init__.py

[backport] Hide private names in `cupy/__init__.py`

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Results of `<=` and `>=` had wrong dtype (scipy/scipy#8833)

Require SciPy 1.2 for sparse comparison

---

cupy/_statistics/order.py
cupy/core/_routines_math.pyx
cupy/core/_routines_statistics.pyx
cupy/cutensor.pyx
tests/cupy_tests/core_tests/test_ndarray_reduction.py
tests/cupy_tests/statistics_tests/test_order.py

Use cuTENSOR in `cupy.prod`, `cupy.max`, `cupy.min`, `cupy.ptp` and `cupy.mean`

---

cupy/_statistics/order.py
cupy/core/_routines_math.pyx
cupy/core/_routines_statistics.pyx
cupy/cutensor.pyx
tests/cupy_tests/core_tests/test_ndarray_reduction.py
tests/cupy_tests/statics_tests/test_order.py

[backport] Use cuTENSOR in `cupy.prod`, `cupy.max`, `cupy.min`, `cupy.ptp` and `cupy.mean`

---

README.md
docs/source/index.rst
setup.py

* Use the unified tagline "A NumPy-compatible array library accelerated by CUDA" everywhere
* Add link to Gitter chat room
* Cleanup README

Update README and docs for unified tagline

---

cupy/__init__.py
cupy/core/_routines_manipulation.pxd
cupy/core/_routines_manipulation.pyx
cupy/lib/shape_base.py
cupy/manipulation/transpose.py
docs/source/reference/functional.rst
tests/cupy_tests/lib_tests/test_shape_base.py
tests/cupy_tests/manipulation_tests/test_transpose.py

This PR implements `apply_along_axis` which is a utility to repeatedly apply a 1d function along a given axis, looping over all other axes.
This function is slightly simplified from [NumPy's](https://github.com/numpy/numpy/blob/c6853c7c27bb8352ab498848439d4fee9eb79a33/numpy/lib/shape_base.py#L268) because it doesn't support a separate `matrix` class and doesn't try to preserve array subclasses like `numpy.ma.core.MaskedArray` via `__array_wrap__` (neither masked arrays or `__array_wrap__` are currently implemented by CuPy)

Add `apply_along_axis`

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

[backport] Require SciPy 1.2 for sparse comparison

---

cupy/core/core.pyx
tests/cupy_tests/math_tests/test_matmul.py

Fixes #3941
We rely only on cublas for the matrix multiplication and we cast the inputs to float and then back to integral types again. This causes precision issues.
This also has an speedup of 45% for a matrix product with `dtype=numpy.int32` and`shape=(5000, 5000)`

Add a kernel for integer GEMM

---

cupy/core/_cub_reduction.pyx
cupy/core/_reduction.pyx
cupy/core/internal.pyx
cupy/cuda/cub.pxd
cupy/cuda/cub.pyx
cupy/cutensor.pyx
tests/cupy_tests/core_tests/test_ndarray_reduction.py
tests/cupy_tests/math_tests/test_sumprod.py

closes #4023
~TODO: The test cases here no longer segfault, but many of the Fortran-contiguous cases do not pass. This seems to be a separate bug somewhere in reductions on F-ordered arrays when CUB is disabled.~
After a clean rebuild, the only difference is that sometimes unaccelerated or cuTENSOR reductions reductions return a result with different contiguity. The actual values seem to be fine and the tests here all pass for me now.

Fix potential segfault when reduction axis is empty

---

cupyx/scipy/sparse/compressed.py
cupyx/scipy/sparse/coo.py
cupyx/scipy/sparse/csc.py
cupyx/scipy/sparse/csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Closes https://github.com/cupy/cupy/issues/3289
This PR adds some missing sparse matrix constructors below to improve compatibility to SciPy.
- csr/csc matrix construction from a tuple of data, row and col vectors
- coo matrix construction from dense matrix

Add missing sparse matrix constructors

---

.pfnci/script.sh
cupy/_environment.py
cupy/_statistics/histogram.py
cupy/core/_cub_reduction.pyx
cupy/core/_routines_math.pyx
cupy/core/_routines_statistics.pyx
cupy/cuda/__init__.py
cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu
cupy/cuda/cupy_cub.h
cupy_setup_build.py
docs/source/install_rocm.rst
install/build.py
tests/cupy_tests/core_tests/test_cub_reduction.py
tests/cupy_tests/core_tests/test_ndarray_reduction.py
tests/cupy_tests/core_tests/test_raw.py

Close #3893. Blocked by #3835. ~~Currently this compiles and some tests passed. Still work in progress...~~
TODO:
***UPDATE***:
This PR adds the support of CUB device routines (i.e. the `cupy.cuda.cub` module) and block reduction kernels (i.e. the `cupy.core._cub_reduction` module) for AMD GPUs. hipCUB is used, which under the hood is backed by rocPRIM on AMD GPUs. The existing CUDA call paths are not touched.
To support CUB block reduction, I also added `get_rocm_path()` and `get_hipcc_path()` to `cupy._environment`, which are the parallel helpers to CUDA.
Note that CuPy's CUB bundle cannot be used in ROCm.
Below is a benchmark script for performance comparison. Some routines are suboptimal, and some even have bugs (likely due to low-precision floating point arithmetics). But the bugs …

ROCm: Support hipCUB/rocPRIM

---

cupyx/_runtime.py

Currently `cupy.show_config` only shows cuda related info.
In order to easily lookup for errors in CI and locally, printing numpy and scipy versions as well can be helpful.
Blocked by #3858 and #3877

Show numpy and scipy versions in `show_config`

---

cupy/cuda/device.pyx
cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_device.py

[backport] Workaround cudaPointerGetAttributes error in CUDA 10.2+

---

cupy/cutensor.pyx

Closes https://github.com/cupy/cupy/issues/4045.
The reason for the failure of cutensorReduction was due to a problem of cuTENSOR 1.2.1 in the handling of old compute types. If you use the new compute types added in version 1.2, this problem will not occur. This PR uses new compute types for cutensorReduction with version 1.2 and above.

Add work-around for issue in cutensorReduction of cuTENSOR 1.2.1

---

cupy/core/_routines_statistics.pyx
tests/cupy_tests/statistics_tests/test_order.py

Closes https://github.com/cupy/cupy/issues/3518.
https://github.com/cupy/cupy/blob/890e40cfd29c2ea37d52fbbef3d2e7d7ceb105d7/cupy/core/include/cupy/complex.cuh#L62-L77
According to the source code above, function `min` (and `max`) for complex dtypes returns numerical argument when one argument is `NaN`. So you should be able to support complex dtypes simply by adding `'F->F'` and `'D->D'` to the following `nanmin` (and `nanmax`) as @leofang suggested in https://github.com/cupy/cupy/issues/3518.
https://github.com/cupy/cupy/blob/890e40cfd29c2ea37d52fbbef3d2e7d7ceb105d7/cupy/core/_routines_statistics.pyx#L283-L289

Add complex dtype support in cupy.nanmin and cupy.nanmax

---

cupy/core/_reduction.pxd
cupy/core/_reduction.pyx
cupy/core/_routines_statistics.pyx
tests/cupy_tests/core_tests/test_ndarray_reduction.py

Depends on #4091.
Fix #4061.
Fix not to sort reduce axis of the input when `_J` is used.

Fix `argmax` and `argmin` for F-order inputs

---

cupy/testing/helper.py
tests/cupy_tests/core_tests/test_ndarray_reduction.py

[backport] Add `order` option in `cupy.testing.shaped_random`

---

cupy/core/_reduction.pxd
cupy/core/_reduction.pyx
cupy/core/_routines_statistics.pyx
tests/cupy_tests/core_tests/test_ndarray_reduction.py

[backport] Fix `argmax` and `argmin` for F-order inputs

---

cupy/core/_cub_reduction.pyx
cupy/core/_reduction.pyx
tests/cupy_tests/core_tests/test_ndarray_reduction.py
tests/cupy_tests/math_tests/test_sumprod.py

[backport] Fix CUB block reduction for F-order arrays with ndim > 2

---

cupy_backends/cuda/api/runtime.pxd
cupy_backends/cuda/api/runtime.pyx
cupyx/_runtime.py

Close #4107. Follow-up of #3858, so **this PR needs to be backported**.
Output without any error:
```
$ python -c "import cupy; cupy.show_config()"
OS                           : Linux-5.4.0-42-generic-x86_64-with-debian-buster-sid
CuPy Version                 : 8.0.0rc1
NumPy Version                : 1.19.1
SciPy Version                : 1.5.2
CUDA Root                    : /opt/rocm
CUDA Build Version           : 0
CUDA Driver Version          : 313700
CUDA Runtime Version         : 3137
cuBLAS Version               : 22200
cuFFT Version                : 10003839
cuRAND Version               : 201001
cuSOLVER Version             : (3, 5, 0)
cuSPARSE Version             : 0
NVRTC Version                : (9, 0)
Thrust Version               : 100902
CUB Build Version            : 201001 …
```

ROCm: Fix `getDeviceProperties` for HIP

---

cupy/core/_cub_reduction.pyx
tests/cupy_tests/sorting_tests/test_search.py

Fix #4061. ~~Blocked by #4062.~~ Parallel of #4084 to fix `argmax`/`argmin` when the CUB block reduction kernel is in use.

Fix `argmax`/`argmin` in CUB block reduction for F-order arrays with ndim > 1

---

cupy/core/raw.pxd
cupy/core/raw.pyx
tests/cupy_tests/core_tests/test_raw.py

Fix #4044. We need to ensure a `RawKernel` is recompiled after unpickling. `RawModule` does not have this problem, because when calling `get_function` the recompiling will be triggered if the compiled module is not found in CuPy's internal cache (`_util.memoize()`).
@jglaser @pentschev @jakirkham Is it possible for any of you to test this PR? I think this is the root cause for the failure, but just wanna be 100% sure. 🙂

Support pickling `cupy.RawKernel`

---

cupy/cuda/cufft.pyx

[backport] Fix typos in `cupy.cuda.cufft`

---

.pfnci/script.sh
cupy_setup_build.py

The symlinks `libhiprtc.so` and `libhip_hcc.so` are gone starting ROCm 3.7.0. We should just use the actual shared library that they point to. I tested locally that this is backward compatible with 3.5.0.
This PR also changes the Debian repo to the latest one so that the pfnCI can always target the latest ROCm release.

ROCm: Build on latest ROCm  

---

cupy/__init__.py
cupy/_math/sumprod.py
docs/source/reference/math.rst
tests/cupy_tests/math_tests/test_sumprod.py
tests/cupyx_tests/fallback_mode_tests/test_fallback.py

This PR adds `cupy.nancumsum` and `cupy.nancumprod`.
The implementation is simple: it replaces the `NaN` value with `0` or `1` before calling `cumsum` or `cumprod`.
This is related to https://github.com/cupy/cupy/issues/4025.

Add cupy.nancumsum and cupy.nancumprod

---

.pfnci/script.sh
cupy/cuda/cupy_nccl.h
cupy_setup_build.py
docs/source/install_rocm.rst
install/build.py

Close #3927. All tests in `tests/cupy_tests/cuda_tests/test_nccl.py` passed locally, but I only have 1 GPU, so we might need further tests to ensure it's working with multi-GPUs.
This works because RCCL uses exactly the same API names as in NCCL, so we don't even need a shim layer to wrap the names!

ROCm: Support RCCL

---

cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/morphology.py

This PR adds a parameter that skips the check for non-zero elements when possible in the binary erosion kernel. Surprisingly, this leads to a fairly large increase in performance (It does result in an ~50 microsecond increase in CPU time, but GPU time is reduced by a factor of 2-3 for large images).
A similar change could be made for the convolution filters and rank filters as well, but I did not measure any change in performance when I tried it for those, so I have left it out of this PR.
```Python
import cupy
import cupyx.scipy.ndimage as ndi
from cupyx.time import repeat
for shape in [(256, 256), (4096, 4096)]:
density = 0.7
connectivity = 2
xp = cupy
rstate = cupy.random.RandomState(5)
x = rstate.randn(*shape) > density
structure = ndi.generate_binary_structure(x.ndim, connectivity) …
```

improve performance of binary morphology for fully nonzero structuring elements

---

cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_interp_kernels.py
cupyx/scipy/ndimage/_util.py
cupyx/scipy/ndimage/filters.py
cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

SciPy's interpolation routines with mode='constant' allow the constant value to be `np.nan`, `np.inf` or `-np.inf`, but these currently cause compilation failure in CuPy. 
closes #4082
I will add test cases in a bit and look into whether we might want to have a similar change for ndimage filters, etc.

handle np.nan and np.inf constant values properly in ndimage functions

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/measurements.py
docs/source/reference/ndimage.rst
tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

This PR adds a series of related `cupyx.scipy.ndimage.measurement` functions: `maximum`, `maximum_position`, `minimum`, `minimum_position`, `median` and `extrema`.
All of these rely on a single `_select` helper function that is patterned after SciPy's, but deviates in some implementation details.  Specifically, SciPy's implementation relies on NumPy-specific behavior regarding indexing with duplicate indices that is a [documented difference from CuPy behavior](https://docs.cupy.dev/en/stable/reference/difference.html#duplicate-values-in-indices)
[Example SciPy code](https://github.com/scipy/scipy/blob/48a876262d95fafbc44e7cbc7baa1ffd685ad659/scipy/ndimage/measurements.py#L867):
```Python
mins[labels[::-1]] = input[::-1]
```
For NumPy arrays, assuming `input` has already been sorted in …

add several functions to cupyx.scipy.ndimage.measurements

---

cupy_setup_build.py

[backport] Add `compute_35` for CUDA 11.0+

---

cupy/cuda/__init__.py

It wasn't immediately obvious to me that I needed to start `nvprof` with profiling turned off in order only profile only the code inside the profiling context, so I added this note to the documentation to help Python users who may not be familiar with profiling compiled languages.

DOC: Add note about starting nvprof with profiling off

---

cupyx/scipy/ndimage/measurements.py

Following up #3979.
This PR fixes the docstrings of `cupyx.scipy.ndimage.{minimum,maximum}_position` to be rendered properly.

Fix docstrings of `cupyx.scipy.ndimage.{minimum,maximum}_position`

---

cupyx/scipy/ndimage/interpolation.py

Support for `mode='opencv'` in `cupyx.scipy.ndimage.affine_transform` seems to have been broken since CuPy 8.0 by the changes I introduced in gh-3166.
This PR [restores the code path from CuPy 7.8 for this case](https://github.com/cupy/cupy/blob/a08841a8e18d285652df0f7a2a25f5ae5bc1a897/cupyx/scipy/ndimage/interpolation.py#L237-L243).
closes #3601
This was not detected previously when testing locally because apparently `@testing.with_requires('opencv-python')` does not pick up the conda-forge `opencv` package, so this test case was always skipped on my system. If I comment out the `with_requires` statement, the following test completes locally after this change:
https://github.com/cupy/cupy/blob/a7766076f15cbe85036960b2faa930496c1c029b/tests/cupyx_tests/scipy_tests/ndimage_tests/test_interp …

fix mode='opencv' case in cupyx.scipy.ndimage.affine_transform

---

cupyx/scipy/ndimage/measurements.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

The `cupyx.scipy.ndimage.measurements` functions `sum`, `mean`, `variance` and `standard_deviation` currently do not broadcast the labels argument properly in all cases.
The call to `cupy.broadcast_arrays` just needs to precede any calls like `input[labels > 0]` or `input[labels == index]` as proposed here.
The test cases added here fail on master, but pass after the changes in this PR.

fix broadcasting behavior in ndimage.measurements functions

---

tests/cupy_tests/lib_tests/test_polynomial.py

In the CuPy combination tests, when using Numpy 1.19.2 and CUDA 9.2 polyfit fails when weights are set to other than `None`. Because of a e-16 difference in one result.
```
actual     = array([3.21811551e+00, 8.02329466e-01, 2.14338135e-16])
atol       = 0
desired    = array([3.21811551, 0.80232947, 0.        ])
```
https://jenkins.preferred.jp/job/chainer/job/chainer-test_pr/220/

Fix `polyfit` tests tolerance

---

cupy/_environment.py

This was my oversight in #4027. I didn't notice the file header says "This file must not depend on any other CuPy modules."

Defer import in `cupy/_environment.py`

---

tests/cupy_tests/polynomial_tests/test_polynomial.py

- It is not very good idea to assume `filterwarnings` in `[tool:pytest]` section contains `error::DeprecationWarning`.  See chainer/chainer#7824 for the previous discussion.
- It seems better to check results even if they are warned.  In fact, 46e5443be2c6de60a15c31f6b4e46866335a9a2a could have prevented the regression #4165.

Use `testing.assert_warns`

---

cupy/_sorting/search.py
cupy/core/_routines_indexing.pyx
tests/cupy_tests/sorting_tests/test_search.py

Fix #4166.
`argwhere` is added by #3135.

Fix `argwhere` for 0d inputs

---

cupy_backends/cuda/stream.pyx

Close #4136.
Currently, the current stream does not work with the following CUDA-related libraries as `enable_current_stream` flag is mistakenly updated as a local variable:
```
~/cupy$ git grep -i enable_current_stream
cupy_backends/cuda/libs/cublas.pyx:    """Set current stream when enable_current_stream is True
cupy_backends/cuda/libs/cublas.pyx:    if stream_module.enable_current_stream:
cupy_backends/cuda/libs/cudnn.pyx:    """Set current stream when enable_current_stream is True
cupy_backends/cuda/libs/cudnn.pyx:    if stream_module.enable_current_stream:
cupy_backends/cuda/libs/curand.pyx:    """Set current stream when enable_current_stream is True
cupy_backends/cuda/libs/curand.pyx:    if stream_module.enable_current_stream:
cupy_backends/cuda/libs/cusolver.pyx:    """Set current …
```

Fix to use current stream properly with CUDA-related libraries

---

cupy/_sorting/search.py
cupy/core/_routines_indexing.pyx
tests/cupy_tests/sorting_tests/test_search.py

[backport] Fix `argwhere` for 0d inputs

---

cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu
cupy/cuda/cupy_cub.h

This PR eliminates the need of allocating a temporary array for offsets, and instead uses iterator combos to generate the offset on the fly. Both CPU and GPU times are improved! Thanks to @allisonvacanti's kind suggestion (https://github.com/NVIDIA/cub/issues/143#issuecomment-713162542) 🙂
Script:
```python
from cupyx.time import repeat
cp.core._accelerator.set_routine_accelerators(['cub'])
cp.core._accelerator.set_reduction_accelerators([])
a = cp.random.random((512, 512, 512), dtype=cp.float32)
print(repeat(cp.min, (a, (2,)), n_repeat=500))
assert cp.allclose(cp.min(a, (2,)), np.min(cp.asnumpy(a), (2,)))
print(repeat(cp.min, (a, (1,2)), n_repeat=500))
assert cp.allclose(cp.min(a, (1,2,)), np.min(cp.asnumpy(a), (1,2,)))
print(repeat(cp.sum, (a, (2,)), …
```

Improve `cupy.cuda.cub.device_segmented_reduce()`

---

cupy/testing/helper.py
tests/cupy_tests/indexing_tests/test_indexing.py
tests/cupy_tests/indexing_tests/test_iterate.py
tests/cupy_tests/linalg_tests/test_einsum.py
tests/cupy_tests/math_tests/test_matmul.py
tests/cupy_tests/math_tests/test_sumprod.py
tests/cupy_tests/testing_tests/test_helper.py

This PR makes parameterized dtype test possible to skip a test for a specific dtype by `pytest.skip`. 
Once `unittest` was used as CuPy's unit test framework, and we could skip it by `raise unittest.SkipTest()`. It seems that, however, the code was not properly updated when we replaced `unittest` with `pytest` and we need to return a dummy array for that purpose.

Make parameterized dtype test skip by `pytest.skip`

---

tests/cupyx_tests/fallback_mode_tests/test_notifications.py

Rel #4138.
Currently, `NotificationTestBase` keeps the value of `_ufunc_config._config` and restores it on tearing down. However, the value of `_config` is an instance that is destructively changed and we need to have another object to properly restore its original contents.

Fix tests that have side effects

---

cupy/_util.pyx
cupy_setup_build.py
cupyx/_runtime.py

The runtime version might be useful for #4141. It'd be shown as `None` if Cython is not found at runtime.
```
$ python -c "import cupy; cupy.show_config()"
OS                           : Linux-5.4.0-42-generic-x86_64-with-debian-buster-sid
CuPy Version                 : 8.0.0rc1
NumPy Version                : 1.19.1
SciPy Version                : 1.5.2
Cython Build Version         : 0.29.21
Cython Runtime Version       : 0.29.21
CUDA Root                    : /usr/local/cuda-10.2
CUDA Build Version           : 10020
CUDA Driver Version          : 11000
CUDA Runtime Version         : 10020
cuBLAS Version               : 10202
cuFFT Version                : 10102
cuRAND Version               : 10102
cuSOLVER Version             : (10, 3, 0)
cuSPARSE Version             : 10301
NVRTC Version …
```

Record Cython build and runtime versions

---

cupy/testing/helper.py

Previous:
```py
if type_check:
for cupy_r, numpy_r in cupy_numpy_result_ndarrays:
>               assert cupy_r.dtype == numpy_r.dtype
E               AssertionError
```
This PR:
```py
if type_check:
for cupy_r, numpy_r in cupy_numpy_result_ndarrays:
if cupy_r.dtype != numpy_r.dtype:
>                           raise AssertionError(
'''ndarrays of different dtypes are returned.
cupy: {}
numpy: {}'''.format(cupy_r.dtype, numpy_r.dtype))
E   AssertionError: ndarrays of different dtypes are returned.
E   cupy: float64
E   numpy: float32
```

Enhance dtype error message in testing helpers

---

cupyx/_ufunc_config.py
tests/cupyx_tests/test_cupyx.py

Rel #4138.
Currently, `cupyx.seterr()` unintentionally set `None` to `_config.linalg` when `linalg` argument is not supplied. This PR fixes it to leave as it is in such a case.

Fix cupyx.seterr() when `linalg` not supplied

---

cupyx/_ufunc_config.py
tests/cupyx_tests/test_cupyx.py

[backport] Fix cupyx.seterr() when `linalg` not supplied

---

cupy/core/_routines_indexing.pyx
cupy/core/core.pyx
tests/cupy_tests/sorting_tests/test_search.py

[backport] Fix `nonzero` for 0d inputs

---

cupyx/scipy/sparse/linalg/__init__.py
cupyx/scipy/sparse/linalg/_eigen.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

This PR adds `cupyx.scipy.sparse.linalg.eigsh`.
`scipy.sparse.linalg.eigsh` provides many options because it uses ARPACK as its eigensolver library. It is difficult to provide all the feature of `scipy.sparse.linalg.eigsh` on CuPy, since there is no ARPACK equivalent GPU library (AFAIF). Therefore, this PR aims to make some of key features of `scipy.sparse.linalg.eigsh` available to users.
This is related to https://github.com/cupy/cupy/issues/3344.

Add cupyx.scipy.sparse.linalg.eigsh

---

cupyx/scipy/ndimage/morphology.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py

This PR fixes a one line bug fix in `binary_erosion`. The current code was causing the output to always be stored in a new array even when the user supplied an output array. Test cases using a user-provided array were added.

fix: respect user-supplied output array in all binary morphology functions

---

cupy/cuda/memory.pyx

Rel #4171.
This PR add a note about split free blocks in `free_all_blocks` reference.

Add a note in `free_all_blocks` reference

---

cupy/testing/__init__.py
cupy/testing/_bundle.py
cupy/testing/parameterized.py
tests/cupy_tests/testing_tests/test_parameterized.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py

#2633 copied almost all the features in `chainer.testing.parameterized`, but some of them are unused.  For further refactoring, this PR removes unused / rarely used features.

Remove unused features in `testing.parameterized`

---

cupy/linalg/_norms.py
tests/cupy_tests/linalg_tests/test_norms.py

Fix output dtype of `linalg.norm`

---

cupy/linalg/_norms.py
tests/cupy_tests/linalg_tests/test_norms.py

[backport] Fix output dtype of `linalg.norm`

---

cupy/__init__.py
cupy/_functional/vectorize.py
cupy/core/_kernel.pxd
cupy/core/_kernel.pyx
cupyx/jit/_compile.py
cupyx/jit/_interface.py
cupyx/jit/_typerules.py
cupyx/jit/_types.py
tests/cupy_tests/functional_tests/test_vectorize.py

First step of #3392.
This PR adds `cupy.vectorize`.
Currently, only primitive arithmetic operations are supported, but I'm planning to cover more features in the future.
Future works:
- `vectorize.__init__` options: (`otypes`, `excluded`, ... etc.)
- Compile-time constants
- python math library / cupy ufunc function calls.
- Control statements (for, while, ... etc.)

Add `cupy.vectorize`

---

cupy/testing/parameterized.py

chainer/chainer#3661 started editing exceptions of test failures because PyTest does not print str(self), while Nosetests does. However, it should have been utilized that PyTest shows repr of local variables.
Fixes #3915.
<details><summary>before</summary>
```
__________________________ TestA_param_0_{x=1}.test_a __________________________
self = <cupy.testing._bundle.TestA_param_0_{x=1} testMethod=test_a>, args = ()
kwargs = {}, s = <_io.StringIO object at 0x7fdb15dc5ee0>, k = 'x', v = 1
err_class = <class 'AssertionError'>
@functools.wraps(base_method)
def new_method(self, *args, **kwargs):
try:
>           return base_method(self, *args, **kwargs)
../cupy/testing/parameterized.py:83:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = …
```

Add repr of parameterized test and stop adding error message

---

cupy_setup_build.py

Use the `CUPY_NUM_BUILD_JOBS` to control the number of modules being built in parallel.
This PR enables the parallel compilation of thrust and cub, which are the modules that takes most of the time.
When building for all the compute archs, the master branch buiold time is 18 minutes, with this PR it becomes 9 minutes.
Moreover, if we limit to a single compute capability with something like `CUPY_NVCC_GENERATE_CODE=arch=compute_62,code=sm_62` , we get a build time of 3 minutes, which is enough for the majority of the users.
Currently, the default is 4 processes because as long as we ensure that there are two threads, cub and thrust will be built independently.
Cub and Thrust are a single .cu file that is built for all the compute archs, and this is what takes the majority of the compile …

Add parallel build feature

---

cupy_setup_build.py
install/build.py

When building CuPy, most of the time the users do not specify the CC of their devices and end up building all of it, this is especially true when they just do `pip install cupy`. This PR detects the CCs at setup time and tailors the build unless specified otherwise (useful when building wheels).
TODO:
- Add a define with the ccs CuPy was built, so we can prevent future errors. (User installing a new GPU in his prebuilt CuPy install).

Detect the CC of the device when building

---

cupy/testing/helper.py
tests/cupy_tests/testing_tests/test_helper.py

Fixed issues:
- assertion failure leaves the target unpatched
- `times_called` is also passed to `mock.patch`
(close #4232)

Refactor `AssertFunctionIsCalled`

---

tests/cupy_tests/core_tests/test_ndarray.py

- `bytes` of uninitialized arrays should not be tested.  Changed them to have size = 0.
- `ndarray.item` returns python scalar.  Test `()`-shaped arrays instead.

Fix tests of `__bytes__`

---

tests/cupy_tests/core_tests/test_ndarray.py

[backport] Fix tests of `__bytes__`

---

cupy/testing/helper.py
tests/cupy_tests/sorting_tests/test_sort.py

Blocked by https://github.com/cupy/cupy/pull/4252.
Fixes `testing.numpy_cupy_equal` decorator for the following situation.
```py
class TestX(unittest.TestCase):
@testing.numpy_cupy_equal()
def test_x(self, xp):
raise ValueError
```
The current master branch passes the above test, even if `numpy` and `cupy` raise errors of different types.

Fix `numpy_cupy_equal` for case that both numpy cupy raise errors

---

cupy/_misc/memory_ranges.py
cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/_spline_prefilter_core.py
cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

This adds the functions `spline_filter1d` and `spline_filter`. These are used for the prefiltering stage for all interpolation functions in `scipy.ndimage` when order >= 2. I will make a follow-up PR later with the actual spline interpolation support.
The `ElementwiseKernel` approach used for convolutions in `cupyx.scipy.ndimage.filters` is not applicable for these spline prefilters because they are infinite impulse response (IIR) filters. Instead, a `RawKernel` is used that follows the SciPy implementation closely. The implementation was originally only for batched operation along the last axis (commit c5ab0f5), but I later refactored it (8f6223b) to use strided operation instead as that ends up being faster.
For the strided operation, I borrowed the `row` function and some stride …

add spline_filter1d and spline_filter to cupyx.scipy.ndimage.interpolation

---

cupy/fft/_callback.pyx

Follow-up of #4141. Many thanks to @maxpkatz for suggesting [`nvprune`](https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#nvprune) 🙏
With this PR, the file size of each Python share library generated at runtime is greatly reduced from 159M to 55M on my system (CUDA 10.2 + sm75). This is made possible by using `nvprune` to slim the size of `libcufft_static.a` for the target arch. The slimmed static library is cached in the same directory as the Python modules for easy reuse.
`nvprune` is made as a soft requirement: According to @maxpkatz, `nvprune` will always be present iff `nvcc` is (which is a hard requirement for the callback support), so in most scenarios this would just work. In the extremest cases where `nvprune` is not found, we fall back to the old behavior (linking …

Reduce the file size of cuFFT callback modules

---

cupy/fft/_callback.pyx

Fix https://github.com/cupy/cupy/issues/4105#issuecomment-727633420. This reverts commit 30a620db38889692694745f5e738e86f080fe524. It seems when linking all callback objects, a C++ compiler must be used (ex: g++ instead of gcc) in order to resolve undefined symbols (ex: `__cxa_pure_virtual`).
cc: @llukas @mnicely @emcastillo

Fix undefined symbols in `cupy.fft._callback`

---

cupy/testing/helper.py
tests/cupy_tests/sorting_tests/test_sort.py

[backport] Fix `numpy_cupy_equal` for case that both numpy cupy raise errors

---

cupyx/jit/_compile.py
cupyx/jit/_typerules.py
tests/cupy_tests/functional_tests/test_vectorize.py

This PR supports compile-time constants in CuPy JIT. This enhancement simplifies generated code by evaluating some numerical expressions in transpile time and enables us to use Python objects of any type, even if it is a non-numerical object, in compile-time.

Support compile-time constants in CuPy JIT

---

cupy/fft/_fft.py

Use `.imag = 0` at hipFFT workaround

---

cupy/cuda/compiler.py
cupy/cuda/jitify.pyx

~~Blocked by my upstream PR NVIDIA/jitify#82~~, which allows reusing the already-constructed header map (in C++). Also, I eject all input code from this map to only keep headers. Together, this helps reduce the runtime for both the first shot compilation as well as a long-running program (such as running the test suite).

Improve Jitify performance

---

cupy/core/core.pyx
cupy/core/include/cupy/math_constants.h
cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_filters_generic.py
cupyx/scipy/ndimage/_interp_kernels.py
cupyx/scipy/special/_convex_analysis.py

Close #4268. Close #4270.
Two changes:
1. Add `cupy/math_constants.h` for both CUDA and HIP
2. Convert a `__global__` RawKernel to a `__device__` function in the ndimage generic filters.
This simple fix makes a handful of tests in `tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py` pass (ROCm 3.5.0 + Radeon VII). The failing ones are irrelevant of #4268 or #4270, and will be documented in a separate issue (#4272).

ROCm: Fix filters in `cupyx.scipy.ndimage`

---

cupyx/scipy/ndimage/_interp_kernels.py

Follow-up of #4271. With this small change all tests in `tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py` pass with ROCm 3.5.0 + Radeon VII.

ROCm: fix ndimage interpolation

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_unary_op.py

Close #4249.
This PR makes an empty array warn `DeprecationWarning` for its truth value as NumPy does.

`DeprecationWaring` on truth value on empty array

---

cupy/cuda/__init__.py
cupy/cuda/cupy_jitify.h
cupy/cuda/jitify.pyx
cupy_setup_build.py
cupyx/_runtime.py
install/build.py

Unfortunately Jitify does not have any identifiable name (branch, tag, etc), so we must use the commit here. Hopefully the submodule pinning is long lasting.
```
$ python -c "import cupy; cupy.show_config()"
OS                           : Linux-5.4.0-42-generic-x86_64-with-debian-buster-sid
CuPy Version                 : 9.0.0a1
NumPy Version                : 1.19.1
SciPy Version                : 1.5.2
Cython Build Version         : 0.29.21
Cython Runtime Version       : 0.29.21
CUDA Root                    : /usr/local/cuda-10.2
CUDA Build Version           : 10020
CUDA Driver Version          : 11000
CUDA Runtime Version         : 10020
cuBLAS Version               : 10202
cuFFT Version                : 10102
cuRAND Version               : 10102
cuSOLVER Version             : (10, 3, 0) …
```

Detect Jitify version

---

cupyx/scipy/sparse/coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py

This PR fixes issues when coo sparse matrix is created from dense matrix.
There are two issues in current implementation.
* The created coo matrix does not have an attribute `has_canonical_format`.
* The created coo matrix may have the wrong shape.
Sorry, both are my bugs.

Fix issues when coo sparse matrix is created from dense matrix

---

cupy_setup_build.py

Currently, extra_compile_args is reused between module builds (e.g. `'-fopenmp'` is added for every module built after `cusolver` module), because it manipulates on shallow copy of the original settings dict, which is returned from `build.get_compiler_setting()`.

Reset extra_compile_args for each module

---

cupy_setup_build.py
docs/source/reference/environment.rst

During the wheel build release process (which is a very high load situation where CuPy build for all CUDA versions are run simultaneously) I found that the parallel build cause build failures for some reason.
(1) https://jenkins.preferred.jp/job/chainer/job/other_cupy_release_builder/130/CUDA=9.0,PYTHON=3.7.0,label=mn1-p100/consoleFull
```
21:13:53 /usr/local/cuda/bin/nvcc -D_FORCE_INLINES=1 -DCUPY_CUB_VERSION_CODE=100800 -DCUPY_JITIFY_VERSION_CODE=60e9e72 -I/work/cupy/install/../cupy/core/include/cupy/cub -I/work/cupy/install/../cupy/core/include -I/usr/local/cuda/include -I/opt/pyenv/versions/3.7.0/include/python3.7m -c cupy/cuda/thrust.cpp -o build/temp.linux-x86_64-3.7/cupy/cuda/thrust.o -fopenmp --std=c++11
21:13:53 nvcc fatal   : Unknown option 'fopenmp'
```
-> This issue …

Tentatively hide CUPY_NUM_BUILD_JOBS option

---

cupy/testing/helper.py
tests/cupy_tests/testing_tests/test_helper.py

Closes #4220.
This PR makes `testing.numpy_cupy_allclose` allow tolerance per dtype.

`testing.numpy_cupy_allclose` with per-dtype tolerance

---

cupyx/scipy/sparse/linalg/_eigen.py

Follows up #4214.
This PR refactors `cupyx.scipy.sparse.linalg.eigsh`. The new one should implement exactly the same algorithm except that `u` is once allocated and overwritten.

Refactor `cupyx.scipy.sparse.linalg.eigsh`

---

cupy/testing/helper.py

The PR improves PyTest support.
- Fix `numpy_cupy_*` with `sp_name`, `scipy_name`.
- Raise `AssertionError`.
- Use `pytest.mark.skipif` instead of `unittest.skipIf`.

Fix `testing.helper` to work without `unittest`

---

cupy/linalg/_solve.py
cupyx/lapack.py
tests/cupy_tests/linalg_tests/test_solve.py
tests/cupyx_tests/test_lapack.py

This PR uses `cupyx.lapack.gesv` in `cupy.linalg.inv` and reduce code duplication.

Simplify `cupy.linalg.inv`

---

cupy/fft/_callback.pyx
cupy/fft/config.py
cupy_setup_build.py

Close #4352. This PR adds a few extra safes:
1. For Windows, we do not build the module `cupy.fft._callback` as it cannot be used on Windows anyway 
2. We defer the initialization of the module-level variables, so even if there's any error it won't happen at import time
3. We honor the `CXX` environment variable if `sysconfig` cannot find `CXX` (I don't understand how's that possible, but at least it's the root cause of the reported error).

Apply fixes to the FFT callback module

---

cupy/core/_cub_reduction.pxd
cupy/core/_cub_reduction.pyx
cupy/core/_fusion_op.py
cupy/core/_reduction.pyx
cupy/core/fusion.pyx

Close #3983. Follow-up of #3244. Currently this only supports 1 in + 1 out for efficiently accessing the global memory. N in + 1 out could be revisited in the future; IIUC `ReductionKernel` does not support multiple outputs.
New changes:
- `cupy.ReductionKernel` can be backed by CUB (from `cupy.core._cub_reduction`)
- Fusion (`@cupy.fuse`) with reduction can also use CUB now; this again assumes 1 in + 1 out, which holds IIUC
- No user code change is required other than the need of setting `CUPY_ACCELERATORS=cub`.
Taking the example code from the tutorial:
```python
from cupyx.time import repeat
l2norm_kernel = cp.ReductionKernel(
'T x',  # input params
'T y',  # output params
'x * x',  # map
'a + b',  # reduce
'y = sqrt(a)',  # post-reduction map
'0', …
```

Support CUB-backed `cupy.ReductionKernel` and `@cupy.fuse`

---

tests/cupy_tests/core_tests/fusion_tests/test_example.py
tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
tests/cupy_tests/core_tests/test_reduction.py
tests/cupy_tests/testing_tests/test_parameterized.py
tests/cupyx_tests/fallback_mode_tests/test_fallback.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py

This coding rule will be required in order to stop inheriting `unittest.TestCase`. https://docs.pytest.org/en/stable/reference.html#confval-python_classes
- This PR overlaps with 61fe60fd479a684ff01c3f699b5d40f125c38044 in #4307.
- This PR does not fix that `cupy_tests/testing_tests/test_condition.py::MockUnitTest::runTest` is collected.

Make names of test classes start with `Test`

---

tests/cupy_tests/core_tests/fusion_tests/test_example.py
tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
tests/cupy_tests/core_tests/test_reduction.py
tests/cupy_tests/testing_tests/test_parameterized.py
tests/cupyx_tests/fallback_mode_tests/test_fallback.py

[backport] Make names of test classes start with `Test`

---

cupy/__init__.py
cupy/_statistics/order.py
docs/source/reference/statistics.rst
tests/cupy_tests/statistics_tests/test_order.py

This is a simple PR to add `cupy.quantile` which is the same as `cupy.percentile` but with q in the range [0, 1] rather than [0, 100].
This just reuses the existing `cupy.percentile` implementation, so there is not much new to review. The test cases are also copies of the tests for percentile, but using floating point `q` in the range [0, 1].
`numpy.quantile` was introduced in NumPy 1.15 which I think CuPy now requires, so I didn't do any `with_requires` checks in the tests.
**One area to consider**
I added range checks on `q` as in NumPy, but these require device synchronization, so it may not be desirable. If we don't want this, I can just remove use of `_quantile_is_valid` and the two `*_out_of_range_q` tests.

add cupy.quantile

---

.mergify.yml

Configure Mergify to check GitHub Actions instead of Travis

---

.mergify.yml

[backport] Configure Mergify to check GitHub Actions instead of Travis

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

scipy/scipy#10341 added the `callback_type` arg.

Require SciPy >= 1.4 in `TestGmres`

---

cupy/cuda/stream.pyx
cupy_backends/cuda/api/runtime.pxd
cupy_backends/cuda/api/runtime.pyx
cupy_backends/cuda/hip/cupy_common.h
cupy_backends/cuda/hip/cupy_runtime.h
cupy_backends/cuda/stub/cupy_cuda_runtime.h
docs/source/reference/cuda.rst
tests/cupy_tests/cuda_tests/test_stream.py

According to the [CUDA Runtime API documentation](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1g74aa9f4b1c2f12d994bf13876a5a2498), `cudaStreamAddCallback` will be deprecated in favor of this new function, added since CUDA 10.0:
> This function is slated for eventual deprecation and removal. If you do not require the callback to execute in case of a device error, consider using `cudaLaunchHostFunc`. Additionally, this function is not supported with `cudaStreamBeginCapture` and `cudaStreamEndCapture`, unlike `cudaLaunchHostFunc`.
TODO:

Add `cudaLaunchHostFunc`

---

cupy/linalg/_solve.py
tests/cupy_tests/linalg_tests/test_solve.py

- The default is `rcond='warn'`, which fallbacks to `rcond=-1`.
- Negative `rcond` should be treated as the machine precision.
- NumPy's future default `rcond=None` is max(m, n) times machine precision.

Fix `rcond` arg of `linalg.lstsq`

---

cupy_setup_build.py

This PR adds support for cuTENSOR 1.2.2.
There is no API change from version 1.2.1, so there is no need to change any compute routines.
As of 1.2.2, the cuTENSOR's library files for CUDA 11.x are now common, and this PR just adds changes to accommodate it.

Add support for cuTENSOR 1.2.2

---

cupy/lib/_polynomial.pyx
tests/cupy_tests/lib_tests/test_polynomial.py

Do not "maintain" poly1d
The semantics of NumPy's poly1d (legacy polynomial class) is not maintained.
Therefore `__array_priority__` should be removed.

Fix `poly1d`

---

docs/source/reference/environment.rst

The `NUM_BUILD_JOBS` environment variable has a redundant `CUPY_` prepended to it in the docs.

 DOC: Incorrect environment variable description

---

cupy/cuda/compiler.py

* NVCC refers to several environment variables, so it should be inherited from the environment.
* On Windows, it's better to append path to the compiler to allow using nvcc backend without frustration.
See comments in the code for details.

Inherit environment variable and detect cl.exe automatically

---

cupyx/scipy/stats/__init__.py
cupyx/scipy/stats/distributions.py
docs/source/reference/scipy.rst
docs/source/reference/statistics.rst
docs/source/reference/stats.rst
tests/cupyx_tests/scipy_tests/stats_tests/test_distributions.py

This PR adds the `scipy.stats` function, `entropy`. This implementation relies on the already existing `cupyx.scipy.special.entr` and `cupyx.scipy.special.rel_entr` functions and so should be simple to review.
There is not currently a `cupyx.scipy.stats` module, so this PR has added it. However, I do not currently have plans to implement other functions within the `stats` module. This function is used within a scikit-image function we created a CUDA equivalent for in `cupyimg`. If there is not an interest in having stats functions within CuPy itself, we can just keep this implementation there.
shape | GPU time (ms) | CPU time (ms) | acceleration
------|---------------|---------------|-------------
(256,) | 0.045 +/- 0.002 | 0.019 +/- 0.001 | 0.420
(512, 512) | 0.117 +/- 0.002 | 5.334 +/- …

add cupyx.scipy.stats.entropy

---

cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

This PR is related to #4247, but deals only with the recently implemented `spline_filter` functions from #4145.
The first commit here removes the `allow_float32` keyword-only argument which is not present in scikit-image and has not yet appeared in a released CuPy version. ~It also changes the default `output=np.float64` to `output=None` which will autoselect a floating point precision for the output. This allows computations to run in single precision by default on float16, float32 or complex64 inputs. In other words, the functionality previously provided by `allow_float32=True` becomes the default.~ **update**: restored default output to float64 for SciPy consistency. internal dtype behaves as if allow_float32=True.
If this type of single precision dtype handling seems okay, I would …

revise dtype handling in cupyx.scipy.ndimage.spline_filter

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/measurements.py
docs/source/reference/ndimage.rst
tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

This PR adds three functions to `cupyx.scipy.ndimage.measurements`
- `center_of_mass`
- `labeled_comprehension`  (applies an arbitrary function over each labeled region)
- `histogram` (implemented via `labeled_comprehension`)
One difference in behavior was made to avoid the need for object arrays (in this case, an arrays where each element is an array). This is used for histogram which calls `labeled_comprehension` using `dtype=object` so that each element of the object array is the histogram over a particular label. For the CuPy implementation, a list of arrays is returned instead of an object array.
If the return value is a scalar in the scipy implementation, a 0-dimensional device array is returned instead here to avoid device->host transfers as much as possible.
I also suppressed all …

cupyx.ndimage.measurements: add center_of_mass, histogram, labeled_comprehension

---

cupyx/scipy/sparse/linalg/_iterative.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

This PR adds support for `LinearOperator` to `cupyx.scipy.sparse.linalg.cg` and `cupyx.scipy.sparse.linalg.gmres` to improve compatibility with SciPy.
Thanks to @venkywonka for adding `LinearOperator` (https://github.com/cupy/cupy/pull/4258)

Add support for `LinearOperator` to `cg` and `gmres` in `cupyx.scipy.sparse.linalg`.

---

.pfnci/script.sh
cupy_setup_build.py
install/build.py

Close #4415. Thanks to @ipe-zhangyz for reporting and helping debug the issue 🙏
**UPDATE**: This PR addresses the following things:
- Ensure pfnCI has a pure ROCm environment (by removing all CUDA related stuff)
- Print HIPCC path at build time, if found
- Ensure wherever NVCC is asked, HIPCC can also be used if `use_hip` is set
- Add a version check for HIP, though currently we only detect its version at build time but do not burn it into any module (we should revisit this in a later PR)
- Don't check compute capability on HIP
- Ensure Windows does not have ROCm support
- Remove the internal helper `_format_cuda_version()` as it's just a alias of `str()`

Disentangle HIP from CUDA in the build script

---

cupy/core/_scalar.pxd
cupy/core/_scalar.pyx
cupy/core/core.pyx
tests/cupy_tests/test_numpy_interop.py

Fix ndarray binary operations with non-CuPy arrays to return `NotImplemented`

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/fourier.py
docs/source/reference/ndimage.rst
tests/cupyx_tests/scipy_tests/ndimage_tests/test_fourier.py

This adds the `fourier_ellipsoid` filter, completing the `cupyx.scipy.ndimage.fourier` module. Unlike the other Fourier filters, this one is not separable and is not truly n-dimensional (as in SciPy itself, only 1d, 2d and 3d cases are implemented).

add cupyx.scipy.ndimage.fourier_ellipsoid

---

docs/source/reference/sparse.rst

Follows up #4356. This PR add `cupyx.scipy.sparse.linalg.spsolve_triangulare` to the reference.

Add `spsolve_triangular` to the reference

---

cupyx/scipy/ndimage/filters.py

Close #4272. 
Turns out this is a bug in the partial selection sort introduced in #3813, but for some reason *on CUDA this is not caught at all*, and led to erroneous results only on HIP. All tests in `tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py` passed on ROCm 3.5.0 + Radeon VII.
@anaruse I didn't realize it's from your #3813 until now 😅 Could you comment on
- whether this fix is the intended usage?
- why it works well on CUDA? 
cc: @grlee77

Fix out-of-bound access in ndimage rank filters

---

cupy/_sorting/search.py

[backport] Fix `cupy.searchsorted` on HIP

---

cupyx/scipy/ndimage/filters.py

[backport] Fix out-of-bound access in ndimage rank filters

---

docs/source/reference/statistics.rst

Backport of cefbd7e28d39dc44a1471761e18372271c556e45
https://github.com/cupy/cupy/pull/4370/files#r533052219

[backport] Fix comment in docs/source/reference/statistics.rst

---

cupy/random/__init__.py
tests/cupy_tests/random_tests/test_init.py

[backport] Fix `cupy.random.bytes` not working

---

cupy/core/core.pyx

We were passing 1, or 2 to the cuda stream synchronize and this is not yet supported in HIP

Fix `__cuda_array_interface__` for HIP

---

cupy/random/_distributions.py
cupy/random/_generator.py
cupy/random/_permutations.py
cupy/random/_sample.py

Now NumPy has the docs for Legacy Random Generation (https://numpy.org/doc/stable/reference/random/legacy.html).  This PR fixes the broken hack.

Fix docs of `cupy.random` functions/methods

---

cupy/core/_routines_math.pyx
tests/cupy_tests/math_tests/test_sumprod.py

Closes https://github.com/cupy/cupy/issues/4456.
This PR fixes the issue of input arrays being overwritten when `axis` is specified in `cumsum` and `cumprod`. This issue was caused by the code change in https://github.com/cupy/cupy/pull/4316 as @grlee77 and @leofang pointed out.

Fix overwritten issue in `cumsum` and `cumprod`

---

cupy/core/_routines_math.pyx

While I was looking through how scan operations worked I found a minor TODO that could be fixed. During my tests this provides an extremely minor speed boost.

Fixing minor TODO in scan.

---

cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_interp_kernels.py
cupyx/scipy/ndimage/_spline_prefilter_core.py
cupyx/scipy/ndimage/_util.py
cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

This PR adds support for additional boundary modes in all interpolation functions. It is based on the most recent bug fixes and enhancements in this area for SciPy 1.6.0 (~12 issues in SciPy were closed: see meta-issue scipy/scipy#12773).
The changes in this PR correspond to those from scipy/scipy#12767 and scipy/scipy#12776 and include:
- enables the previously disabled 'reflect' and 'wrap' modes ('reflect' behavior was fixed in SciPy 1.6. 'wrap' remains as before, but a new 'grid-wrap' mode is probably what most users will want)
- new modes: 'grid-wrap' and 'grid-constant' (also 'grid-mirror' as a synonym for 'reflect')
The easiest way to understand the various modes is probably via the new figures introduced to SciPy's ndimage tutorial. The main doc site doesn't show these yet, but …

ndimage: support all interpolation boundary modes

---

cupy/random/_distributions.py
tests/cupy_tests/random_tests/test_distributions.py

Currently `cupy.random.normal` does not work with array arguments for `scale` or `loc` unless `size` is also specified. This contradicts with the behavior of NumPy.
This PR broadcasts the scale and loc arguments to determine size.
The following examples now work without requiring the user to provide the size:
```Python
cupy.random.normal(cp.arange(8), 5)
cupy.random.normal(5, cp.arange(8))
cupy.random.normal(cp.arange(8)[:, cp.newaxis], cp.arange(8)[cp.newaxis, :])
```
Prior to this PR, all of the above would fail with: `ValueError: Out shape is mismatched`
There may be other distributions that also need a similar fix, but this is the one I encountered in an application.

cupy.random.normal: fix broadcasting of scale and loc arguments

---

cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_interp_kernels.py
cupyx/scipy/ndimage/_spline_prefilter_core.py
cupyx/scipy/ndimage/_util.py
cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

blocked by #4400 (This PR builds on that one. Only the final "ENH: implement grid_mode parameter for zoom" commit here is new)
This PR implements zooming in a manner consistent with scikit-image's `resize` and OpenCV's `cv2.resize`. See further explanation in the corresponding SciPy PR scipy/scipy#13095 (to be released in SciPy 1.6).
Basically the issue relates to whether coordinate (0, 0) is at the center or corner of a pixel. In the kernel, this translates into computing coordinates via: 
`c = zoom * (in_coord + 0.5) - 0.5` (for grid_mode=True)
vs.
`c = zoom * in_coord` (for grid_mode=False)

ndimage: add grid_mode option to zoom

---

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

This fixes the test variation to exclude unsupported dtypes. Errors were hidden by `accept_error=ValueError` option, but should be explicitly excluded.
I found this because the following code cause hard crash on Windows + SciPy 1.5.4.
```
import numpy, scipy.signal
scipy.signal.order_filter(numpy.ones(10, dtype=numpy.float16), numpy.ones(3, dtype=numpy.bool_), 0)
```
On Linux, this raises an exception.

Exclude unsupported dtypes for TestOrderFilter

---

cupyx/scipy/ndimage/_filters_generic.py

This updates the ndimage scipy generic filters to use the new `CArray` and `CIndexer` constructors instead of manipulating their memory which was quite hackish.

Update to use the new CArray and CIndexer constructors

---

cupy/_statistics/order.py
tests/cupy_tests/statistics_tests/test_order.py

Because the existing percentile_weightnening kernel reads past the end of the input array, the 100th quantile returned by `cupy.percentile` can (incorrectly) be a NaN if that extra read returns a NaN as described in #4451. This PR ensures that the kernel does not read past the end of the array by passing in the size of the array and ensuring that the index is at most `size - 1`.
While the fix is straightforward, the associated test is somewhat trickier. The unit test provided as part of this PR allocates a large array of NaNs, deletes that array, and then calls `cupy.percentile` in order to maximize the likelihood that arrays newly-allocated during the computation will have a NaN in device memory just past their end.
I'm currently leaving this PR as WIP because I would appreciate feedback …

Eliminate read past end of array in percentile_weightnening

---

tests/cupy_tests/core_tests/test_carray.py

There is a bug in HIP/Rocm in which grids with total size of 2**32 do not launch threads at all.
This can be reproduced with 
```python
size = 2**32
add_kernel = cp.RawKernel(r'''
extern "C" __global__
void my_add(char* y) {
unsigned long long block_dim = blockDim.x;
unsigned long long block_idx = blockIdx.x;
unsigned long long tid = block_dim * block_idx + threadIdx.x;
y[tid] = 24;
}
''', 'my_add')
y = cp.empty(size, dtype=cp.int8)
add_kernel((size//256,), (256,), (y,))  # grid, block and arguments
cp.cuda.stream.get_current_stream().synchronize()
print(y)
```
I also created a C reproducer to report this to AMD folks.
```c
#include <hip/hip_runtime.h>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
using namespace std;
__global__ void helloworld(char* out)
{ …
```

Skip large size test for hip

---

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

[backport] Exclude unsupported dtypes for TestOrderFilter

---

tests/cupyx_tests/scipy_tests/stats_tests/test_distributions.py

cherry-picked 426e6b471273a57deab5c5db9b070b683c3f36fe.

Fix TestEntropy: Requires scipy>=1.4.0 for `axis` parameter

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py

We agreed to disable this, as there are no compatible libraries anywhere
This change breaks some tests

Disable `__cuda_array_interface__` for HIP

---

cupy/cuda/compiler.py

[backport] Use `--device-c` for RDC compile

---

cupyx/scipy/ndimage/_interp_kernels.py
cupyx/scipy/ndimage/_spline_kernel_weights.py
cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

closes #1523
blocked by #4400 and #4401
This PR implements spline interpolation orders 2-5. Spline interpolation was substantially improved in SciPy 1.6, with all boundary modes now being handled correctly. Only the `mode='mirror'` cases can be compared tested against older SciPy.
**To decide**: How do we want to handle the order argument to these functions. Should we change the default back from None to 3 so that it matches SciPy? For now, I have left it as it was in CuPy 8.0.
I will post some benchmark results when I get a chance. This is still fast relative to SciPy, but the acceleration is worse than that seen for orders 0 and 1. I would like to see if there is a way to refactor this a bit to reduce register usage, as I suspect that is part of the reason for the performance …

ndimage: implement higher order spline interpolation

---

cupy/random/_distributions.py

Document `random.uniform` may return high

---

cupy/core/internal.pyx
cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_signaltools_core.py
cupyx/scipy/signal/signaltools.py
docs/source/reference/signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

This implements `cupyx.scipy.signal.oaconvolve` which uses the recently merged `cupyx.scipy.signal.fftconvolve` to do most of the work by breaking the larger data into smaller blocks to make the FFTs faster. Nearly all of the other logic comes from scipy with some simplifications.
A custom version of scipy's `special.lambertw` function is provided that only works for the situation needed to determine the block size (called `_optimal_oa_block_size`). This function is only called once per call to `oaconvolve` and takes a 1-2 microseconds in my tests, if necessary this can be moved to Cython which is 10x faster.

Implementing cupyx.scipy.signal.oaconvolve

---

cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_interp_kernels.py
cupyx/scipy/ndimage/_util.py
cupyx/scipy/ndimage/filters.py
cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

~blocked by #4402~
This PR enables interpolation (scipy/scipy#12812) and convolution/correlation of complex-valued data (scipy/scipy#12725). It is created starting from #4401, so most commits here are duplicate with that PR. The new ones start from 87872b7.
Work on this PR resulted in a bug fix PR to SciPy 1.6.0rc1 (scipy/scipy#13249) for constant boundary modes with `cval` != 0.

ndimage: complex dtype support in filters and interpolation

---

tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py

Follows #4444 up. This PR removes unnecessary `return` statements in the tests.

Remove unnecessary `return` statements

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_join.py

 Fix `cupy.concatenate` typecheck for out with different dtype

---

cupyx/scipy/signal/_signaltools_core.py
cupyx/scipy/signal/bsplines.py
cupyx/scipy/signal/signaltools.py
tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

This adds support for complex values in the following functions in the `cupyx.scipy.signal` package. These functions always had support in scipy but did not have support in cupy due to lack of support for complex values in the underlying `ndimage` functions that were being used.
* `cupyx.scipy.signal.convolve` (when method wasn't 'fft')
* `cupyx.scipy.signal.correlate` (when method wasn't 'fft')
* `cupyx.scipy.signal.convolve2d`
* `cupyx.scipy.signal.correlate2d`
* `cupyx.scipy.signal.wiener`
* `cupyx.scipy.signal.sepfir2d`
This code removes intentional error messages for complex data types and a few necessary complex conjugations.

Add complex support to `cupyx.scipy.signal` functions

---

cupy/core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_join.py

[backport]  Fix `cupy.concatenate` typecheck for out with different dtype

---

cupy/core/_routines_linalg.pyx
cupy/cusolver.py
cupy/linalg/_decomposition.py
cupy_backends/cuda/libs/cublas.pyx
cupy_backends/cuda/libs/cusolver.pyx
cupy_backends/hip/cupy_hipblas.h
cupy_backends/hip/cupy_rocsolver.h
tests/cupy_tests/linalg_tests/test_decomposition.py
tests/cupy_tests/test_cublas.py
tests/cupy_tests/test_cusolver.py
tests/cupyx_tests/test_lapack.py

Related to #4132. ~~Blocked by #4205~~. 
TODO:
**UPDATE**: `gels` was just recently added upstream (https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/164) and is not included in any official ROCm release yet

ROCm: Cover more new BLAS/SOLVER functions

---

cupy/core/_routines_indexing.pyx
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

Fix `cupy.take` from an empty array

---

cupy/core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py

Follow-up of #4198, #4458, #4482. **Merge after #4485.**
Close #4515. 
Fix two issues:
1. `hasattr` has side effect, so on HIP `hasattr(a, '__cuda_array_interface__')`  raises `RuntimeError`. This is fixed by simply raising `AttributeError` instead so that `hasattr(a, '__cuda_array_interface__') == False`, which also matches the original intension (#4482).
2. In `__array_ufunc__`, when on HIP instead of testing if the array has `__cuda_array_interface__ ` we test if the participating object is a `cupy.ndarray` since `__cuda_array_interface__` is disabled.

Fix bug on bad interaction between `__cuda_array_interface__` and `__array_ufunc__` on HIP

---

cupy/core/_routines_indexing.pyx
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

[backport] Fix `cupy.take` from an empty array

---

cupy/core/_routines_linalg.pyx

Follow-up of #3994. ~~Blocked by #4217.~~
This PR fixes two things:
1. For ROCm/HIP, there is a bunch of errors in `test_product.py` (see https://github.com/cupy/cupy/issues/4484#issuecomment-751204258) due to ~~the different handlings in out-of-bound access between CUDA and HIP. A check is added on HIP.~~ a strange behavior in HIP (likely the same cause as in #4504. Fixed by syncing the block only on HIP.
2. The kernel allocates shared memory statically, not dynamically, so there's no reason to pass `shared_mem` when launching the kernel.

Fix integer GEMM

---

cupy/__init__.py
docs/source/reference/math.rst
tests/cupy_tests/core_tests/fusion_tests/test_routines.py
tests/cupy_tests/math_tests/test_rounding.py

NumPy has a `round` function that is equivalent to `around`, but CuPy currently does not define this function.
When checking the proposed Array API Standard, I see that `round` rather than `around` is specified in the standard, so it would be good to support it here. See:
https://data-apis.github.io/array-api/latest/API_specification/elementwise_functions.html#round-x

Add cupy.round

---

cupyx/scipy/ndimage/_util.py
cupyx/scipy/ndimage/interpolation.py

These should no longer be needed now that SciPy 1.6.0 [has been released](https://github.com/scipy/scipy/releases/tag/v1.6.0)
[edit by @toslunar] Close #4467.

Remove experimental warnings from cupyx.scipy.ndimage

---

cupy/core/core.pyx
cupy/cuda/device.pyx
cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

Close #4317. Wrapping pointers using `ctypes.c_void_p()` is still accepted, but it's not required.
TODO:

Support passing pointers as integers in memory copy routines

---

cupy/core/_kernel.pxd
cupy/core/_kernel.pyx
cupy/core/_scalar.pyx
cupy/cuda/texture.pyx
docs/source/tutorial/kernel.rst
tests/cupy_tests/core_tests/test_userkernel.py

Close #2550.
This PR allows users to pass a `cupy.cuda.texture.TextureObject` to `cupy.ElementwiseKernel`. The texture coordinates can be computed from the loop indexing variable `i`, see the added tests (thanks to @the-lay for pointing out this possibility which I failed to see!). 
This PR has a particular potential benefit in that since a lot of ndimage kernels are written in `cupy.ElementwiseKernel`, if someone is willing to spend time on adding texture-utlized versions of them, it is possible to use the texture hardware to accelerate some of the computations (ex: [interpolation](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#texture-fetching)), which GPUs are known very good since this is one of GPUs' primary applications.
Notes: 
- Texture objects cannot be part of …

Support texture object in `cupy.ElementwiseKernel`

---

cupyx/scipy/ndimage/_interp_kernels.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

Fix rounding behavior for `cupyx.scipy.ndimage.interpolation` functions with order=0.
closes #4550
reference line from SciPy source: 
https://github.com/scipy/scipy/blob/255d49cd63d4341c4d95b28ee8272657bf5e8e42/scipy/ndimage/src/ni_interpolation.c#L479

ndimage: coordinate rounding fix for order=0 interpolation

---

cupy/core/dlpack.pyx
cupy/core/include/cupy/dlpack/README.md
cupy/core/include/cupy/dlpack/dlpack.h

Follow-up of #4517. @tqchen kindly fixed this issue in upstream right after I reported it, so given that we manually bundle the header we can just apply the same fix ourselves.
This PR should be backported (after #4535).

Fix DLPack header version

---

cupyx/scipy/ndimage/_interp_kernels.py
cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

This PR fixes a bug in `cupyx.scipy.ndimage.zoom` when the output has any dimension of size 1 and `grid_mode=True`. The purpose of the modified code section was just to prevent any potential divide by zero when calculating the zoom factors.
This PR is built on top of #4552, otherwise the order=0 test cases added here would fail.

Fix cupyx.scipy.ndimage.zoom for outputs of size 1

---

cupy/testing/helper.py

When using `testing.numpy_cupy_**` testing helpers, both NumPy and CuPy raise the same error type if the test script has a bug, for example, the wrong number of parameters.
This PR avoids passing such a wrong test unexpectedly.
Rel. https://github.com/cupy/cupy/pull/3702

Check if the accepted_error was not raised from test code

---

cupy/core/include/cupy/math_constants.h

Fix #4414.
This PR makes CuPy's own copy of `math_constants.h` a standalone header, so that users who are running CuPy without a full CUDA installation (ex: Conda-Forge or CUDA runtime docker) can still JIT compile codes. Unneeded constants are removed to avoid potential EULA violation 😞
cc: @grlee77

Remove dependency on CUDA's math_constants.h

---

cupy/core/core.pyx
tests/cupy_tests/creation_tests/test_from_data.py

Fix #4465.
This PR fixes `cupy.array` when it is supplied a nested list contains zero-dim ndarrays
```
a = cp.cos(1)
cp.array([[a], [a]])
```

Fix `cupy.array` from nested list of zero-dim ndarray

---

cupy/random/cupy_distributions.cu
cupy/random/cupy_distributions.cuh

`ssize_t` was in the .cu file instead of the .cuh

Fix windows build

---

cupy/core/core.pyx
tests/cupy_tests/creation_tests/test_from_data.py

[backport] Fix `cupy.array` from nested list of zero-dim ndarray

---

cupyx/scipy/ndimage/_interp_kernels.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

[backport] ndimage: coordinate rounding fix for order=0 interpolation

---

cupy/cuda/compiler.py
cupy_backends/cuda/cupy_nvrtc.h
cupy_backends/cuda/libs/nvrtc.pxd
cupy_backends/cuda/libs/nvrtc.pyx
cupy_backends/cupy_rtc.h
cupy_backends/hip/cupy_hiprtc.h
cupy_backends/stub/cupy_nvrtc.h
tests/cupy_tests/core_tests/test_raw.py

**UPDATE**: this PR only adds Cython wrappers for `nvrtcGetCUBIN`, and the migration strategy to this new API is to be discussed.
This PR changes the NVRTC default for CUDA 11.1+ from compiling PTX to compiling CUBIN, bypassing the driver JIT step when the module is loaded. This could potentially improve the overall performance (to be verified) in terms of both reducing overall time and enabling better code generation.
For CUDA 9.2 - 11.0, this PR does not do anything.
TODO:

CUDA 11.1: Wrap the new `nvrtcGetCUBIN` API

---

cupy/cuda/compiler.py
cupy_backends/cuda/libs/nvrtc.pyx

Starting CUDA 11.2, if the program name is an empty string, the first time NVRTC is invoked it would output the following log:
```
invalid filename
!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus, file: !1, producer: "lgenfe: EDG 6.0", isOptimized: true, runtimeVersion: 0, emissionKind: NoDebug, enums: !2)
!1 = !DIFile(filename: "", directory: "/home/leofang/dev/cupy_cuda112")
invalid filename
!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus, file: !1, producer: "lgenfe: EDG 6.0", isOptimized: true, runtimeVersion: 0, emissionKind: NoDebug, enums: !2)
!1 = !DIFile(filename: "", directory: "/home/leofang/dev/cupy_cuda112")
```
It's harmless but very annoying. This PR fixes it in 2 layers:
- In the Cython layer, if an empty name is detected, we pass NULL instead. This …

CUDA 11.2: Fix empty NVRTC program name

---

cupy/_environment.py
cupyx/tools/install_library.py
tests/cupyx_tests/tools_tests/test_install_library.py

I am working on making cuTENSOR available on Conda-Forge (conda-forge/staged-recipes#13576), and I realized the same convenience can also be brought to here. Currently machine-readable links are only available on Linux variants (thanks to @kkraus14's help 👍).

Add cuTENSOR to library download tool

---

cupy_backends/cuda/api/runtime.pyx

This bug shadowed another bug being investigated: https://github.com/conda-forge/cupy-feedstock/issues/98.

Fix device property default name

---

tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
tests/cupy_tests/logic_tests/test_type_test.py
tests/cupy_tests/math_tests/test_arithmetic.py

[backport] Avoid test discovery failure in NumPy 1.20

---

cupy/_statistics/histogram.py
cupy/core/core.pyx
cupyx/scipy/ndimage/measurements.py
tests/cupy_tests/indexing_tests/test_insert.py
tests/cupy_tests/testing_tests/test_helper.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py

`np.float`, `np.int`, `np.bool` are deprecated since NumPy 1.20.

Stop using deprecated type aliases

---

install/build.py

If CUDA's built-in CUB is used (on CUDA 11.0+), the current implementation will make the Jitify header test fail due to a mistaken path...

Fix Jitify version detection on CUDA 11.0+

---

cupy/core/internal.pyx
cupy/random/_generator.py
tests/cupy_tests/core_tests/test_internal.py
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/creation_tests/test_basic.py
tests/cupy_tests/random_tests/test_generator.py

[backport] Deprecate passing shape=None to mean shape=()

---

cupyx/scipy/fftpack/_fft.py
tests/cupy_tests/math_tests/test_arithmetic.py
tests/cupy_tests/statistics_tests/test_histogram.py

Follow-up #4605
I checked the occurrences with `git grep '\.\(float\|int\|bool\|complex\)\([^0-9a-z_]\|$\)'`

Stop using deprecated `numpy.complex`

---

tests/cupy_tests/lib_tests/test_polynomial.py

Backport: Fix `poly1d` return types for NumPy 1.20

---

cupyx/scipy/fftpack/_fft.py
tests/cupy_tests/math_tests/test_arithmetic.py
tests/cupy_tests/statics_tests/test_histogram.py

[backport] Stop using deprecated `numpy.complex`

---

cupy/core/_fusion_kernel.pyx
cupy/cuda/compiler.py

Use NVRTC for grid synchronization in `cupy.fuse`

---

cupy/random/_distributions.py
cupy/random/_generator.py
tests/cupy_tests/random_tests/test_distributions.py

- `cupy.random.RandomState.normal`
- `cupy.random.lognormal`
- `cupy.random.RandomState.lognormal`
were broken.
Fix #4613.

Make `normal` and `lognormal` support array args

---

tests/cupy_tests/creation_tests/test_ranges.py

Backport of https://github.com/cupy/cupy/pull/4604

[backport] Fix tests for incompatible behavior of NumPy 1.20 `linspace`

---

setup.py

- Update NumPy requirement. (Actually this had to be done when we decided to drop NumPy 1.16 or earlier in v9 releases)
- Add `all` extra specifier to install all optional dependencies
c.f. https://docs.cupy.dev/en/latest/install.html#python-dependencies

Update install requirements

---

cupy/core/_fusion_kernel.pyx
cupy/cuda/compiler.py

[backport] Use NVRTC for grid synchronization in `cupy.fuse`

---

cupy/cuda/compiler.py
cupy_backends/cuda/libs/nvrtc.pyx

[backport] CUDA 11.2: Fix empty NVRTC program name

---

cupy/cuda/stream.pyx
tests/cupy_tests/cuda_tests/test_stream.py

Follow-up of #4322.
PTDS does not work on HIP and leads to segfault when going out of scope (https://github.com/cupy/cupy/issues/4132#issuecomment-775734406). This PR disables it on HIP:
- Raise if `ptds=True` is set in the constructor
- Avoid creating the `cupy.cuda.Stream.ptds` singeleton
- Skip PTDS tests

ROCm: disable PTDS

---

cupy/_statistics/order.py
setup.py
tests/cupy_tests/statistics_tests/test_order.py

Improve the floating point accuracy of the linear interpolation formula used in `percentile_weightnening` kernel of `cupy.percentile`
Resolve #4607

Improve floating point accuracy in percentile

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

```py
>>> import scipy.sparse
>>> scipy.sparse.random(3, 4).tocsc().has_sorted_indices
1
>>> import cupyx.scipy.sparse
>>> cupyx.scipy.sparse.random(3, 4).tocsc().has_sorted_indices
True
```

Fix return type of `has_sorted_indices` of sparse array

---

cupy/core/_fusion_interface.py
cupy/core/_fusion_kernel.pyx
cupy/core/_fusion_op.py
cupy/core/_fusion_variable.pyx
cupy/core/fusion.pyx
cupyx/jit/_codeblock.py
cupyx/jit/_compile.py
cupyx/jit/_types.py

This PR fixes JIT code with `CodeBlock` object, which we implemented in CuPy fusion to generate human-readable CUDA code.

Use `CodeBlock` to generate human-readable code in JIT

---

tests/cupy_tests/linalg_tests/test_eigenvalue.py

Rel #4132 and #4484.
```
cupy_backends.cuda.libs.cusolver.CUSOLVERError: rocblas_status_not_implemented
```

Xfail tests for eigenvalue under HIP/ROCm

---

cupy/random/_generator.py
tests/cupy_tests/random_tests/test_distributions.py

Make `uniform`-based random distributions support array args

---

tests/cupy_tests/lib_tests/test_polynomial.py

Rel #4132.
Absense of `__cuda_array_interface__`.

Skip `TestPoly1dMathArithmetic` under HIP/ROCm

---

tests/cupy_tests/math_tests/test_misc.py

Rel #4132 and #4484.
The test fails when the shape of `b` is larger.

Xfail tests for `convolve` under HIP/ROCm

---

cupy/core/core.pyx
cupy/core/include/cupy/math_constants.h
cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_filters_generic.py
cupyx/scipy/ndimage/_interp_kernels.py
cupyx/scipy/special/_convex_analysis.py

[backport] ROCm: Fix filters in `cupyx.scipy.ndimage` - Part 1

---

tests/cupy_tests/test_cublas.py

Skip failing tests for `cupy.cublas` under HIP

---

cupy/_math/rational.py

Rel #4132 and #4484.
This PR fixes the order of definitions of `gcd` and `lcm` in the preamble as the HIP compiler requires.

Fix definition order in preamble

---

tests/cupy_tests/indexing_tests/test_generate.py

Rel #4132.
This test strangely fails. Sometimes an additional statement gets the fail away.

Xfail test for cupy._indexing.generate under HIP

---

cupy/random/_generator.py
tests/cupy_tests/random_tests/test_distributions.py

[backport] Make `uniform`-based random distributions support array args

---

cupyx/tools/install_library.py

Needed by https://github.com/cupy/cupy-release-tools/pull/66

Add cudnn and cutensor for CUDA 11.2 in `install_library`

---

cupy/core/include/cupy/math_constants.h

[backport] Remove dependency on CUDA's math_constants.h

---

cupy/core/core.pyx
cupy_backends/cuda/stream.pxd
cupy_backends/cuda/stream.pyx
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py
tests/cupy_tests/creation_tests/test_from_data.py

Follow up of #4357 and #4322. This PR should ***not*** be backported.
Now that we support PTDS (#4322), we should detect if it's in use before exporting (context: https://github.com/cupy/cupy/pull/4357#issuecomment-735852102). The test suite is updated accordingly. One of the main focus is to ensure the tests pass regardless of the value of the env var `CUPY_CUDA_PER_THREAD_DEFAULT_STREAM` (verified locally). 
This PR also adds an extra safe for HIP following #4651: On HIP, `CUPY_CUDA_PER_THREAD_DEFAULT_STREAM` should be ignored as PTDS is not supported.
cc: @pentschev

Update CUDA Array Interface to v3 - Part 2

---

.pfnci/windows/_flexci.ps1
.pfnci/windows/test.ps1

https://github.com/cupy/cupy/pull/4362#discussion_r572536881
This PR also fixes the issue that test script fails when all tests pass 😅

Fix Windows CI test script to avoid caching kernel when in pull-request test

---

install/build.py

Follows up https://github.com/cupy/cupy/pull/4636.
This PR removes the check for maximum cuDNN version in installation. The code is very aged. I guess it was included for some reason, but it doesn't seem to have much sense now.

Remove maximum cuDNN version check

---

cupy/cusolver.pyx
cupy_backends/cuda/libs/cusolver.pyx
cupy_backends/cupy_lapack.h
cupy_setup_build.py
tests/cupy_tests/linalg_tests/test_decomposition.py

Close #4684. Close #4687.
Fix 3 bugs:
- The workspace size is not large enough
- The pointer address should be computed differently based on `full_matrices`
- Force C++11 compilation to work with older gcc (like gcc 5)
Remove the skip on CUDA 10.0 to force the CI to test it out, as gesvd shouldn't be affected by the known cuSOLVER bug.

Fix random errors in batched SVD

---

tests/cupy_tests/test_cudnn.py

Blocking https://github.com/chainer/chainer-test/pull/633.
This PR fixes the tests for cuDNN 8.1. Note that this change is not tested with the current CI configurations as it requires cuDNN 8.1. I checked it works as much as possible on my machine. After this PR is merged, https://github.com/chainer/chainer-test/pull/633 should kick the CI again.

Fix tests for cuDNN 8.1

---

cupyx/tools/install_library.py

[backport] Add cudnn and cutensor for CUDA 11.2 in `install_library`

---

.pfnci/windows/_flexci.ps1
.pfnci/windows/test.ps1

[backport] Fix Windows CI test script to avoid caching kernel when in pull-request test

---

docker/python3/Dockerfile

Closes #4593.
We may bump to more recent one in v9, if the newer CUDA version is released before CuPy v9rc release.

Bump CUDA version for Docker images

---

docs/source/install_rocm.rst

[backport] Remove unneeded environment variable from ROCm install guide

---

MANIFEST.in
cupy_setup_build.py
pyproject.toml
readthedocs.yml
setup.py

This PR removes C++ sources from sdist and changes the CuPy installer to always run cythonize at user-side.
Cython will automatically (temporarily) be downloaded by setuptools via `setup_requires` configuration.
The primary motivation for this is to use compile-time constants in the code appropriately (closes #4597).
Besides that, cythonize at user-side  is also needed for #4395 which generates pyx during the installation.

Always run cythonize on sdist installation

---

cupy/cuda/cupy_thrust.cu
cupy_setup_build.py

The headers changed to have `constexpr`

Fix thrust compilation in MSVC 14 for CUDA 11.2

---

docs/source/install.rst
setup.py

Backport of #4711.
Manually made a backport as the content is different. Merge after ~#4711~ (merged).

[backport] Update Python / NumPy / SciPy requirements

---

cupy/cuda/cupy_thrust.cu
cupy_setup_build.py

Windows ate it, but linux doesn't.
also when declaring some functions as constexpr other stuff started to blow up.
I built it locally and confirmed that now cuda 11.2 can be built.

 Missing `constexpr` in `cupy_thrust.cu`

---

cupy_setup_build.py

When no rpath is needed, `-Wl,--disable-new-dtags,` is added to the command line, but the trailing comma is invalid.
This will be needed for ROCm packaging.

Fix invalid command line generated when rpath is empty

---

cupy/cuda/cupy_thrust.cu

In linux having all with `constexpr` works (otherwise, it fails)
In windows, if these are declared as `constexpr` compilation fails :D.
Will revisit after release.

Disable some `constexpr` only for windows

---

cupy/cuda/cupy_thrust.cu
cupy_setup_build.py

[backport]  Missing `constexpr` in `cupy_thrust.cu`

---

cupy_setup_build.py
docs/source/install.rst

[backport] Bump Cython version requirement for Python 3.9

---

cupy/_statistics/order.py
tests/cupy_tests/statics_tests/test_order.py

Bring changes from PR 4453 into v8 to eliminate read past end of array in percentile calculations

[backport] Eliminate read past end of array in percentile_weightnening

---

cupy/cusolver.py

This bug fix is cherry-picked from #4628.

[backport] Fix `_gesvdj_batched` info array size

---

README.md
docs/source/install.rst

[backport] Remove `cupy-cuda112` support from documentation

---

cupy/linalg/_decomposition.py
cupy/linalg/_solve.py
tests/cupy_tests/linalg_tests/test_solve.py

~~***Blocked by #4684*** as batched SVD is required but currently emitting random errors in the CI.~~
Close #3062.
- For supporting batched `pinv`: the original implementation already followed NumPy's, so really it's just adding `newaxis` here and there to broadcast. 
- This PR also fixes an incompatibility when the input array is of zero size

Support batched `pinv`

---

tests/cupyx_tests/linalg_tests/test_solve.py

Looks that rocSOLVER does not implement `potrs` yet.
https://rocsolver.readthedocs.io/en/latest/userguide_intro.html#brief-description-and-functionality

Xfail TestInvh under ROCm/HIP

---

README.md
docs/source/install.rst

Revert "[backport] Remove `cupy-cuda112` support from documentation"

---

tests/cupy_tests/math_tests/test_sumprod.py

`l`/`L` refers to `int32`/`uint32` on Windows, which leads to test failures.

Windows: Fix test condition for CUB device kernels

---

cupy/random/_generator.py
tests/cupy_tests/random_tests/test_generator.py

Currently, cupy's Dirichlet distribution does not support an integer argument a a shape. Only tuples are allowed; ints lead to a `TypeError`. This differs from the behavior of numpy and is not a necessary restriction. It also does not match the [documented parameters](https://docs.cupy.dev/en/stable/reference/generated/cupy.random.dirichlet.html).
The issue has been [detailed on Stack Overflow recently](https://stackoverflow.com/a/66405505/7802200). A workaround is for the user to provide the size as a tuple, but they shouldn't have to.
I address this by turning the provided argument into a list. (If it's already a list or tuple, this won't affect anything.) I provide a test case as well.
Note that cupy's multivariate normal distribution supports both integer and tuple arguments.

Support int argument for Dirichlet shape

---

tests/cupy_tests/lib_tests/test_polynomial.py

Rel #4132.
`cupy_backends.cuda.libs.cusolver.CUSOLVERError: rocblas_status_not_implemented`

Xfail tests in polynomial roots

---

tests/cupy_tests/random_tests/test_generator.py

Looks that MT19937 is not implemented yet in hipRAND, failing with the status code `HIPRAND_STATUS_NOT_IMPLEMENTED`.

Assert MT19937 not implemented in hipRAND

---

tests/cupy_tests/lib_tests/test_polynomial.py

Rel #4132, #4484, #4758.
Looks that polyfit returns negated value when deg == 0.

Xfail TestPolyfitCovMode when deg == 0 under ROCm/HIP

---

cupy/_functional/vectorize.py
cupyx/jit/__init__.py
cupyx/jit/_compile.py
cupyx/jit/_interface.py
cupyx/jit/_typerules.py
cupyx/jit/_types.py
tests/cupyx_tests/jit_tests/test_raw.py

Part of #4290.
This PR supports a raw kernel interface like as following.
```py
def f(x, y, z, n):
tid = jit.threadIdx.x + jit.blockIdx.x * jit.blockDim.x
ntid = jit.blockDim.x * jit.gridDim.x
for i in range(tid, n, ntid):
z[i] = x[i] + y[i]
n = numpy.uint32(1024)
x = cupy.arange(n)
y = cupy.arange(n)
z = cupy.empty((n,), dtype='l')
f[16, 16](x, y, z, n)
```

Add CuPy JIT Kernel definition

---

tests/cupy_tests/sorting_tests/test_sort.py

This PR removes an `xfail` mark as it is already fixed and leaves XPASS on pytest output.

Remove solved xfail mark for msort

---

tests/cupy_tests/manipulation_tests/test_dims.py

Xfail tests for manipulation dims under HIP/ROCm

---

tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py

```
FAILED tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py::TestSepFIR2d_param_0_{hcol=1, hrow=1, input=(256, 256)}::test_sepfir2d
FAILED tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py::TestSepFIR2d_param_1_{hcol=1, hrow=1, input=(4, 512)}::test_sepfir2d
FAILED tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py::TestSepFIR2d_param_2_{hcol=1, hrow=1, input=(512, 3)}::test_sepfir2d
FAILED tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py::TestSepFIR2d_param_3_{hcol=1, hrow=3, input=(256, 256)}::test_sepfir2d
FAILED tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py::TestSepFIR2d_param_4_{hcol=1, hrow=3, input=(4, 512)}::test_sepfir2d
FAILED tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py::TestSepFIR2d_param_5_{hcol=1, hrow=3, …
```

Windows: Fix `sepfir2d` tests

---

cupy/__init__.py

Deprecate `cupy.bool`, `cupy.int`, `cupy.float` and `cupy.complex`

---

tests/cupy_tests/math_tests/test_sumprod.py

Follow-up of #4776. It's currently not tested on the Windows CI yet, but will cause errors when we enable it.

Windows: Fix cuTENSOR tests

---

cupy/linalg/_solve.py
tests/cupy_tests/linalg_tests/test_solve.py

[v8] Fix `linalg.pinv` on empty matrices

---

examples/finance/monte_carlo.py

hipRTC fails with the conflicting typedef.
```
cupy.cuda.compiler.CompileException: /tmp/comgr-17edf0/input/CompileSource:5358:32: error: typedef redefinition with different types ('unsigned long long' vs '__uint64_t' (aka 'unsigned long'))
typedef unsigned long long uint64_t;
^
/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h:27:20: note: previous definition is here
typedef __uint64_t uint64_t;
^
```

Remove duplicated typedef in example when HIP

---

cupy/cuda/cupy_thrust.cu

https://github.com/cupy/cupy/commit/74c54b07a9d8a0f1c0130e6cfec989b3aa3ed867 from #4730 broke it, see https://github.com/cupy/cupy/issues/4132#issuecomment-791579731. All tests in `test_sort.py` pass now.

ROCm: Fix sorting bug

---

cupyx/jit/_typerules.py
tests/cupy_tests/functional_tests/test_vectorize.py

For `a = np.array([1, 2, 3, 4])`, on Linux `a.dtype == np.int64`, but on Windows `a.dtype == np.int32`.

Windows: fix vectorize tests

---

tests/cupy_tests/lib_tests/test_polynomial.py

Looks that `polyfit` returns negated value when `deg == 0`.

Xfail TestPolyfitParametersCombinations when deg == 0 under ROCm/HIP

---

cupy_setup_build.py
install/build.py
tests/install_tests/test_build.py

No cuDNN counterpart in ROCm/HIP.

Xfail cuDNN version check test under ROCm/HIP

---

tests/cupy_tests/statistics_tests/test_correlation.py

Assertion errors like below:
```
E       AssertionError:
E       Not equal to tolerance rtol=0.01, atol=0
E
E       Mismatched elements: 101 / 101 (100%)
E       Max absolute difference: 64847
E       Max relative difference: 42.19661458
E        x: array([1191,  651,  779,  562,  751,  745,  693,  862,  864,  936, 1027,
E               988,  962,  827,  937,  817,  832,  837,  814,  740,  794,  842,
E               771,  822,  895,  956,  943,  996,  946,  983,  890,  912,  824,...
E        y: array([2592, 1718, 1987, 1649, 1849, 1731, 1795, 1760, 1768, 1660, 1897,
E              1677, 1809, 1717, 1837, 1735, 1847, 1829, 1986, 1817, 1897, 1825,
E              1697, 1752, 1698, 1794, 1725, 1754, 1791, 1757, 1813, 1836, 1871,...
```

Xfail some tests for `cupyx.scipy.statistics.correlation` under ROCm/HIP

---

cupyx/scipy/sparse/sputils.py

[backport] Windows: fix sparse matrix indexing type

---

cupy/cuda/compiler.py
docs/source/install_rocm.rst

Close #4719. Both hiprtc and hipcc can pick up the right device, so no need to set `HCC_AMDGPU_TARGET` at runtime.

ROCm: remove the need to set `HCC_AMDGPU_TARGET` at runtime

---

.github/workflows/backport.yml

* Fix broken netrc configuration (Sorry it was my mistake in #4833...)
I confirmed in my fork that `git clone` to private repo working.
https://github.com/kmaehashi/cupy/runs/2057137229?check_suite_focus=true#step:5:4
* Improve the workflow to skip in forks.
example: https://github.com/kmaehashi/cupy/actions/runs/632585230
https://github.community/t/have-github-action-only-run-on-master-repo-and-not-on-forks/140840
* Change name from `pretest` to `backport`.

Fix automated backport workflow

---

.github/workflows/backport.yml

Use `pull_request_target` so that we can also use `labeled` trigger (when we notice the PR needs to be backported after merging the pull-request, we can just label it to trigger the workflow).
Note that `pull_request` does not work as this workflow requires the secret access.

Use pull_request_target trigger

---

cupy_setup_build.py

Fix #4750.
Currently, CuPy completes its build even if an essential module is failed to be built. This PR fixes the build process to complete only when we can successfully build all of the required modules. See #4750 for an exhaustive list of modules CuPy depends on mandatorily or optionally.

Complete build only when all of the essential modules are available

---

cupy/core/dlpack.pyx
cupy/core/include/cupy/dlpack/README.md
cupy/core/include/cupy/dlpack/dlpack.h
tests/cupy_tests/core_tests/test_dlpack.py

~~**DO NOT MERGE** until the upstream is tagged!~~ 
The new v0.4 has the following change:
- Support complex numbers
- Rename the struct `DLContext` to `DLDevice`
Prepare for Array API adoption (https://github.com/data-apis/array-api/pull/106).

Update DLPack support

---

cupy/random/_generator.py
tests/cupy_tests/random_tests/test_generator.py

Fix #4511
Current version
```python
>>> cupy.random.choice(0, size=(3, 0, 7))
ValueError: a must be greater than 0
>>> cupy.random.choice([], size=(3, 0, 7))
ValueError: a must be non-empty
```
After changes
```python
>>> cupy.random.choice(0, size=(3, 0, 7))
array([], shape=(3, 0, 7), dtype=int64)
>>> cupy.random.choice([], size=(3, 0, 7))
array([], shape=(3, 0, 7), dtype=float64)

Fixed choice function for 0 samples from 0 candidates

---

cupy_backends/cuda/stream.pyx

`get_current_stream_ptr` is one of the frequently called function (every kernel launch / malloc), so let's avoid the overhead.

Avoid evaluating PTDS environment variable everytime

---

cupy/linalg/_decomposition.py
cupy/linalg/_eigenvalue.py
cupy/linalg/_norms.py
cupy/linalg/_solve.py
cupy/linalg/_util.py
tests/cupy_tests/linalg_tests/test_solve.py

Backport of #4363
There were several conflicts so I expect this to need additional work.

[backport] Fix dtypes in `cupy.linalg`

---

cupy_backends/cuda/cupy_nvrtc.h
cupy_backends/cuda/libs/nvrtc.pxd
cupy_backends/cuda/libs/nvrtc.pyx
cupy_backends/hip/cupy_hiprtc.h
cupy_backends/stub/cupy_nvrtc.h

Add a wrapper for the new NVRTC API (added in CUDA 11.2) to query supported architectures:
```python
>>> cp.cuda.nvrtc.getSupportedArchs()
(35, 37, 50, 52, 53, 60, 61, 62, 69, 70, 72, 75, 80, 86)
```

Support `nvrtcGetSupportedArchs`

---

cupyx/scipy/sparse/compressed.py

Addressed issues:
1. For argmin/argmax, the precision of input floats does not matter since they can be compared just fine, so it doesn't make sense to always cast to `double` (`float64`).
2. However, the output int type is platform dependent (`int64` on Linux, `int32` on Windows), so we want to fix it properly to eliminate the Windows errors (see #4805).
The solution to fix both issues at once is to do template specializations using `RawModule`. This is both an improvement ***and*** a bug fix.
Close #4805.

Improve/fix csc/csr argmax/argmin 

---

tests/cupy_tests/core_tests/test_ndarray_indexing.py

Xfail tests for ndarray indexing under HIP

---

cupyx/scipy/sparse/coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py

The functions added here are direct copies of the SciPy methods, only switching out `np`->`cupy`.
`diagonal` worked okay prior to this PR via the base class `diagonal ` method which first converted to CSR. 
The `TestCooMatrixDiagonal` class here is modification of the existing `TestCsrMatrixDiagonal` class. The only methods that needed to be modified for the COO case were `_make_matrix` and `_test_setdiag`.

Add diagonal and setdiag methods for COO sparse matrices

---

tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

Including fairly larger errors.
```
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       Mismatched elements: 1 / 2 (50%)
E       Max absolute difference: 1608
E       Max relative difference: 64.32
E        x: array([1633,   33])
E        y: array([25, 33])
```

Xfail some conditions of ndimage measurements under ROCm/HIP

---

cupy/lib/_polynomial.pyx

Again, pure guess work here...
```
_______ TestPoly1dPow_param_3_{exp=4, shape=()}.test_poly1d_pow_scalar ________
cupy\testing\helper.py:825: in test_func
impl(self, *args, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <<cupy_tests.lib_tests.test_polynomial.TestPoly1dPow_param_3_{exp=4, shape=()} testMethod=test_poly1d_pow_scalar>  parameter: {'exp': 4, 'shape': ()}>
args = (), kw = {'dtype': <class 'numpy.int8'>}
cupy_result = (poly1d([1], dtype=int64),), cupy_error = None
numpy_result = (poly1d([1]),), numpy_error = None
cupy_numpy_result_ndarrays = [(array([1], dtype=int64), array([1]))]
cupy_r = array([1], dtype=int64), numpy_r = array([1])
@_wraps_partial_xp(impl, name, sp_name, scipy_name)
def test_func(self, *args, **kw):
( …
```

Windows: Fix `test_poly1d_pow_scalar`

---

cupy/cudnn.pyx
tests/cupy_tests/test_cudnn.py

Close #3872.
Another guess work. My theory is the workspace size is too stringent for the failing tests:
```
FAILED tests/cupy_tests/test_cudnn.py::TestConvolutionBackwardData_param_93_{auto_tune=True, bias=True, deterministic=True, dilate=2, dtype=float16, groups=2, max_workspace_size=4194304, ndim=3, tensor_core='always'}::test_call
FAILED tests/cupy_tests/test_cudnn.py::TestConvolutionBackwardData_param_94_{auto_tune=True, bias=True, deterministic=True, dilate=2, dtype=float16, groups=2, max_workspace_size=4194304, ndim=3, tensor_core='auto'}::test_call
FAILED tests/cupy_tests/test_cudnn.py::TestConvolutionBackwardData_param_95_{auto_tune=True, bias=True, deterministic=True, dilate=2, dtype=float16, groups=2, max_workspace_size=4194304, ndim=3, tensor_core='never'}::test_call
FAILED …
```

Windows: Skip failing cuDNN tests

---

tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py

Larger errors to say the matter of tolerance.
```
E       AssertionError: 
E       Not equal to tolerance rtol=1e-05, atol=1e-05
E       
E       Mismatched elements: 17 / 20 (85%)
E       Max absolute difference: 4.46357349
E       Max relative difference: 0.51304726
E        x: array([[4.375872, 5.488135, 5.448832, 4.236546, 4.236548],
E              [5.288949, 6.027634, 5.288949, 4.236548, 4.236548],
E              [4.375872, 4.37587 , 5.288949, 4.236546, 4.236548],
E              [5.288949, 5.288948, 5.288949, 4.236546, 4.236548]])
E        y: array([[5.488135, 6.458941, 7.151894, 6.027634, 5.448832],
E              [5.488135, 6.027634, 6.027634, 5.680446, 5.448832],
E              [4.375872, 5.680446, 7.781568, 8.326198, 8.700121],
E              [5.288949, …
```

Xfail some conditions of ndimage filter under ROCm/HIP

---

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

Including fairly larger errors.
```
E       AssertionError: 
E       Not equal to tolerance rtol=0.001, atol=0.001
E       
E       Mismatched elements: 784 / 784 (100%)
E       Max absolute difference: 1333.3907
E       Max relative difference: 8.11097
E        x: array([[[ 1.132499e+02,  8.041714e+01,  1.015153e+02,  6.432927e+01,
E                 1.203019e+02,  1.354613e+01,  2.911143e+01, -2.381061e+01,
E                 2.635724e+01, -3.767127e+01,  1.562032e+01,  6.885651e+01,...
E        y: array([[[  30.119678,   78.50118 ,  117.3106  ,  146.02594 ,
E                 160.77292 ,  161.73344 ,  150.97159 ,  165.33815 ,
E                 196.18398 ,  194.92374 ,  152.63922 ,  113.40126 ,...
```

Xfail some conditions of signal tests under ROCm/HIP

---

cupy/_manipulation/rearrange.py
tests/cupy_tests/manipulation_tests/test_rearrange.py

Another version of #4864. (cc: @awthomp)

Support `cupy.ndarray` type `shift` in `cupy.roll`

---

cupy/core/__init__.py
cupy/core/_fusion_trace.pyx
cupy/core/_gufuncs.py
cupy/core/_routines_linalg.pxd
cupy/core/_routines_linalg.pyx
cupy/core/core.pyx
cupy/core/internal.pxd
cupy/core/internal.pyx
cupy/linalg/_product.py
tests/cupy_tests/math_tests/test_matmul.py

This is a big nasty one.
Currently wip.
Adds a GUFunc class (all the axes and batching stuff has been copied straight from dask).
There are some heavy incompatibilities here with things such as `matmul` since all the batching is done in the relevant cublas routine, we should avoid doing repeated calls at any cost. So for some gufuncs we need to skip several of these steps.
Also, we need to find a way to blend this with the regular `UniversalFunction`, probably wrapping it and doing a straight call should be enough, but we will provide additional support for currently non-supported kwargs such as `where`.
This needs to be cythonized too.
Fixes:
#4549 
#2552

Support for Generalized Universal Functions

---

cupy/random/_generator_api.pyx
tests/cupy_tests/random_tests/test_generator_api.py

Fixes #4903
BTW I want to rework the tests and add a common baseclass for distributions in the old and new API as most of them are 100% identical, right now we are duplicating code where we shouldnt.

Add `out` arg verifier in new random interface.

---

cupy/cuda/cufft.pxd
cupy/cuda/cufft.pyx
cupy/cuda/cupy_cufft.h
cupy/fft/_cache.pyx
cupy/fft/_callback.pyx
tests/cupy_tests/fft_tests/test_callback.py

Close #4746.
This is an alternative of #4743 (proposal v2 mentioned there). The solution here is to avoid cimporting any CuPy modules so that we don't expose Cython-level APIs. The incurred overhead is OK ~~(which I will post later)~~: about +/- 5 us (yes, it can be faster in some cases, which I didn't expect), see https://github.com/cupy/cupy/pull/4853#issuecomment-794903196.
TODO:

Fix cuFFT callback compilations - v2

---

.pfnci/windows/_flexci.ps1
.pfnci/windows/test.ps1

This fix intends to prevent test insntace termination caused by watchdog process not responding.
I'm not 100% sure how priority improves the situation though.
Examples of instance termination (multiple Execution tab):
https://ci.preferred.jp/cupy.experimental.win.cuda100/70115/
https://ci.preferred.jp/cupy.experimental.win.cuda100/70105/
https://ci.preferred.jp/cupy.experimental.win.cuda100/70103/

Prioritize FlexCI daemon in Windows CI

---

.pfnci/windows/_flexci.ps1

FlexCI does not define `FLEXCI_BRANCH` when run as scheduled job.

Fix to work with scheduled FlexCI job

---

cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

Solve UnboundLocalError on copy_from_host_async

---

cupyx/tools/install_library.py

* Use `lib` instead of `lib64` (keep dir name in original archive)
~Depends on https://github.com/cupy/cupy/pull/4912~ merged
* Preserve license file
* A bit cleanup

Improve cuTENSOR installer

---

cupy/core/core.pyx
cupy/core/include/cupy/carray.cuh
tests/cupy_tests/core_tests/test_core.py

Close #4875.
As mentioned in the linked issue, NVRTC by default does not support many C++ features, including the offending `type_traits` header. Since it is best to not revert a feature we already supported (#3683), I choose to add a workaround patch, which in this case is still manageable though unfortunately against my earlier intention to avoid custom C++ `std` stubs (ex: #4264).
The added test ensures an error like the one reported in #4875 can be detected by the CI and prevents a regression from happening again.
cc: @takagi @coderforlife @grlee77

Fix C++ compilation error

---

cupy/random/_generator_api.pyx
cupy/random/cupy_distributions.cu
cupy/random/cupy_distributions.cuh
tests/cupy_tests/random_tests/test_generator_api.py

This is a example PR on how to add distributions to the new random API (#4557)
https://numpy.org/doc/stable/reference/random/generator.html#distributions
The process is to create a CUDA kernel from the code in `cupy/random/_distributions.py` that uses the corresponding cuRAND generator and call it from `_generator_api.pyx`
Tests are obtained from `tests/cupy_tests/random_tests/test_generator.py` and modified accordingly

Add `cupy.random.Generator.standard_normal`

---

docs/source/install.rst
docs/source/upgrade.rst

Closes #4850
Blocked by https://github.com/cupy/cupy-release-tools/pull/81, #4848, #4852

Document that cuDNN and NCCL are no longer included

---

docs/source/install.rst

* Say "tested" rather than "recommended" to make the meaning clear. Also add Windows
* v8 -> v9
* Cython is now always required for source build

Update install docs

---

cupy/core/_reduction.pyx
tests/cupy_tests/core_tests/test_reduction.py

Close #4405.
The compiler error was due to the absence of a guard that raises `ComplexWarning` and casts a complex array to real. Not sure if there is a better solution...But this patch seems to work fine.
I do not touch `ReductionKernel` as I am not sure if such an error-prone usage is even possible there.

Fix compilation error due to invalid complex-to-real casting in `_SimpleReductionKernel`

---

tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py

Fixes cupy-combination tests in chainer-test 
https://github.com/chainer/chainer-test/pull/644
Confirmed locally with cuda 11.0 and scipy 1.6.1
This does not happen with cuda 11.2

Change irfft tests tolerance

---

cupy/cuda/texture.pyx
tests/cupy_tests/cuda_tests/test_texture.py

Close #4865. This patch is verified using the stress test (https://github.com/cupy/cupy/issues/4865#issuecomment-804272731).
There are two separate bugs fixed in this PR:
1. The copy routine in `texture.pyx` does not respect the current stream, leading to surprises.
2. The tests in `test_texture.py` generate input data on the default stream, but run the copy routine on a separate stream without first establishing a proper stream order.
Both have to be fixed to make the stress test pass.
I also did a few cosmetic changes in `test_texture.py` that were not possible with older dependencies. Should be obvious ones.

Fix flaky `CUDAarray` tests

---

cupy/cusparse.py
cupy_backends/cuda/cupy_cusparse.h
cupy_backends/cuda/libs/cusparse.pxd
cupy_backends/cuda/libs/cusparse.pyx
cupy_backends/stub/cupy_cusparse.h
cupyx/scipy/sparse/csc.py
cupyx/scipy/sparse/csr.py
tests/cupy_tests/test_cusparse.py

This PR adds support for new cuSparse functions for matrix conversion, [cusparseDenseToSparse()](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-dense2sparse) and [cusparseSparseToDense()](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-sparse2dense), added in CUDA 11.2. The cuSparse function, [cusparseXdense2csr()](https://docs.nvidia.com/cuda/cusparse/index.html#dense2csr), used in CuPy currently have a problem with incorrect results for some matrix sizes. The new functions solve that problem.
This is related to https://github.com/cupy/cupy/issues/3223

Support cuSparse functions for matrix conversion added in CUDA 11.2

---

cupy/_functional/vectorize.py
cupy/core/include/cupy/carray.cuh
cupyx/jit/_compile.py
cupyx/jit/_interface.py

Enclosed the `CArray._indexing` declarations with `#ifdef CUPY_JIT_MODE`, because ROCm tries to find `thrust::get` before the expansion of template member functions whereas CUDA does not.

Declare `CArray._indexing()` only in CuPy JIT mode

---

.pfnci/script.sh

ROCm 4.1 is out but seems the build is failing. Tentatively pin to 4.0.1 until we support it.

Tentatively pin CI to ROCm 4.0.1

---

cupyx/scipy/sparse/csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

This is a temporary workaround until we figure out a proper solution, see https://github.com/cupy/cupy/issues/3822#issuecomment-782607637.
cc: @emcastillo

Disable CUB SpMV on CUDA 11.x

---

tests/cupy_tests/math_tests/test_sumprod.py

Follow-up of #4920. This is needed to enable the check `cupy.cuda.cutensor.available`. Not sure how I missed this...
ref: https://github.com/cupy/cupy/pull/4920#discussion_r597873769

Fix `cutensor` import in the test

---

tests/install_tests/__init__.py
tests/install_tests/test_build.py
tests/install_tests/test_utils.py

Currently install_tests expects that the current directory is at `cupy/` source root.
Due to this limitation we have to run tests separately, in two step (install_tests and other tests).
https://github.com/chainer/chainer-test/blob/master/test_cupy.sh#L28-L34

Make install_tests runnable without depending on current path

---

docs/source/install.rst

This is mainly to reflect that we start building Windows packages on Conda-Forge since v8.6.0 and v9.0.0rc1 (https://github.com/conda-forge/cupy-feedstock/pull/114), so this PR should be backported to v9.

Update installation guide for Conda-Forge

---

cupy_backends/cuda/libs/cusparselt.pxd
cupy_backends/cuda/libs/cusparselt.pyx
cupy_backends/cupy_cusparselt.h
cupy_backends/stub/cupy_cusparselt.h
cupy_setup_build.py
examples/cusparselt/matmul.py
install/build.py

This PR adds support for cuPARSELt (https://docs.nvidia.com/cuda/cusparselt/index.html).
cuSPARSELt can be downloaded from the following URL. https://developer.nvidia.com/cusparselt/downloads
cuSPARSELt can also be installed via conda as follows (thanks to @mnicely and @leofang !).
$ conda install -c conda-forge cusparselt
To enable cuSPARSELt, when you build CuPy from source, set the environment variables CFLAGS and LDFLAGS as follows.
$ export CUSPARSELT_PATH=/path/to/libcusparselt
$ CFLAGS="-I ${CUSPARSELT_PATH}/include" LDFLAGS="-L ${CUSPARSELT_PATH}/lib64" python setup.py install

Support cuSPARSELt

---

examples/cusparselt/matmul.py

Fix `examples/cusparselt/matmul.py` not to use internal function `_dtype.to_cuda_dtype`. (cc: @anaruse)
Related to #4883.

Fix cuSPARSELt example not to use internal function

---

cupyx/time.py
docs/source/reference/ext.rst
docs/source/reference/prof.rst

Address https://github.com/cupy/cupy/issues/4902#issuecomment-801662941. I think it's better to get this API documented sooner while we plan to expand on the tutorial. It is a very handy API that we keep referring users in the issue tracker to use, so I say we just get it on the docs to have something to refer to. As such, we should backport this PR to v9.

Document `cupyx.time.repeat`

---

README.md
docs/source/contribution.rst

The Anaconda badge is copied from https://anaconda.org/conda-forge/cupy/badges.
Close #3696.

Doc: Add links to Anaconda, Gitter, StackOverflow

---

cupy/cuda/compiler.py

I don't know if this would help fix any of the failing tests that we currently skip, but this is definitely something we want to do to align with the CUDA builds. See the discussion in https://github.com/ROCm-Developer-Tools/HIP/issues/2252, and the inline comments.

HIP: add `-ftz=true`

---

cupyx/scipy/fft/_fft.py
docs/source/reference/scipy_fft.rst
tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py

Added hfft2, ihfft2, hfftn, and ihfftn from SciPy. Let me know if a conclusive benchmark comparing the performance of `cupyx.scipy.fft.hfft2()`, `cupyx.scipy.fft.ihfft2()`, `cupyx.scipy.fft.hfftn()`, and `cupyx.scipy.fft.ihfftn()` with `scipy.fft.hfft2()`, `scipy.fft.ihfft2()`, `scipy.fft.hfftn()`, and  `scipy.fft.ihfftn()` is necessary

Add hfft2, ihfft2, hfftn, and ihfftn to cupyx.scipy.fft

---

cupyx/jit/_compile.py
tests/cupyx_tests/jit_tests/test_raw.py

Indicates on which line of the target Python function the compile error occurred.
If an error is raised while the compilation, the type of error is immediately converted to `_JitCompileError` class temporarily.
The attributes of `_JitCompileError` object include 1. the type and message of the original error and 2. On which line of the original python function the error is raised.
Just before exiting the top level of the compilation function, the error type is restored to the original error type, and "Where in the Python function the compilation error occurred" is shown as the error message.

CuPy JIT: Readable compile error messages

---

cupyx/jit/_compile.py
cupyx/jit/_interface.py

Marks `cupyx.jit.rawkernel` as experimental because its interface may change in the future.

Mark `cupyx.jit.rawkernel` as experimental

---

tests/cupy_tests/cuda_tests/test_stream.py

This seems to be why the copy multigpu error is happening in the CI https://github.com/cupy/cupy/issues/4673.
In these tests, ptds is left as the default stream for the rest of the CI execution, and when the array is copied back, `asarray` ignores the ptds set https://github.com/cupy/cupy/pull/5004, and just starts copying to host before the multidevice copy is over.
If we are right, https://github.com/cupy/cupy/pull/5040 will print 2 in the current stream being used once that test fails.
#5004 fixes the root cause of the error, but this PR is needed to set the CI environment correctly.

Fix `TestStream` cleanup

---

cupy/cuda/__init__.py
docs/source/reference/cuda.rst

I think it'd be good to expand the memory management documentation, but before that let's make them appear in the index first.

Document `CFunctionAllocator` and `ManagedMemory`

---

cupyx/_runtime.py

So that users can map CUDA device ID and nvidia-smi device when multiple cards having the same name are installed.

Add PCI Bus ID to show_config

---

cupy/fft/_cache.pyx

Close #5022.
This is a band-aid fix to avoid reusing cuFFT plans on CUDA 11.1 that introduces this regression:
> Plans with primes larger than 127 in FFT size decomposition or FFT size being a prime number bigger than 4093 do not perform calculations on second and subsequent cufftExecute* calls. Regression was introduced in cuFFT 11.1
https://docs.nvidia.com/cuda/archive/11.2.0/cuda-toolkit-release-notes/index.html#cufft-resolved-issues
Thanks @michaelmarty for reporting and @mnicely for pointing out the issue!

Disable cuFFT plan cache on CUDA 11.1

---

cupy/_core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py

Fix #4988.
This PR fixes `ndarray.copy` to use async memcpy so that it respects the current stream.
I'll try to supply an appropriate testing code.

Use async memcpy in `ndarray.copy`

---

cupyx/jit/_compile.py
examples/jit/reduction_simple.py
tests/cupy_tests/functional_tests/test_vectorize.py

Fix the iteration dtype generated from `range(start, stop, step)`.
Current master:
- `start`, `stop` and `step` must have the same integer dtype (raises `TypeError` otherwise).
This PR
- `start`, `stop` and `step` can be different integer dtype.
- iteration dtype is inferred from `stop`.

CuPy JIT: Fix range type

---

cupy/_core/_gufuncs.py

Currently if we throw `_GUFunc` to `cupyx.time.repeat` we get this error:
```
AttributeError: '_GUFunc' object has no attribute '__name__'
```
So this PR fixes it. Though, I am not sure if assigning the name of the wrapped function to the `_GUFunc` object is a good idea. Suggestions welcome!

Give gufunc a name

---

cupyx/jit/__init__.py
cupyx/jit/_compile.py

`inspect.getsource` does not work in Python REPL.
This PR support `cupyx.jit._getsource_func` to set a third-party alternative function of `inspect.getsource`.
Here is a example using `dill.source.getsource` as the `getsource` function.
```py
>>> from cupyx import jit
>>> import dill
>>>
>>> jit._getsource_func = dill.source.getsource
>>>
>>> @jit.rawkernel()
... def elementwise_copy(x, y, size):
...     tid = jit.blockIdx.x * jit.blockDim.x + jit.threadIdx.x
...     ntid = jit.gridDim.x * jit.blockDim.x
...     for i in range(tid, size, ntid):
...         y[i] = x[i]
...
/home/asi1024/cupy/cupyx/jit/_interface.py:149: FutureWarning: cupyx.jit.rawkernel is experimental. The interface can change in the future.
cupy._util.experimental('cupyx.jit.rawkernel')
>>> size = …
```

Support custom getsource option in CuPy JIT

---

cupy/_core/dlpack.pyx
cupy/_core/include/cupy/dlpack/README.md
cupy/_core/include/cupy/dlpack/dlpack.h

Follow-up of #4695. This PR contains two fixes:
1.  We need to set `lanes=1` for complex numbers to match the `bits` field (which was set correctly in #4695).
2. We need to reject `lanes>1` following what PyTorch has been doing; the reason our round-trip test passed for the No.1 bug is because we allowed any `lanes` but actually ignored it
related: pytorch/pytorch#55365, https://github.com/dmlc/dlpack/pull/66
cc: @emcastillo @rgommers

Fix DLPack lanes

---

tests/cupy_tests/manipulation_tests/test_basic.py

Reverts cupy/cupy#5040
Confirmed that the per thread default stream was accidentally set as the current stream, causing the test to expose a known bug:
```
----------------------------- Captured stdout call -----------------------------
12:57:49 current stream: <Stream 2>
12:57:49 current device: 0
```

Revert "Add debug print for flaky test"

---

cupy/_environment.py

See https://github.com/conda-forge/cupy-feedstock/pull/113#issuecomment-807010102. Without this patch, the dll loading errors at this line:
https://github.com/cupy/cupy/blob/30e004549b1862f3360b3b5922566bd6b9805bb2/cupy/_environment.py#L226
The reason is Anaconda/Conda-Forge put all dlls under the Conda env root (`$CONDA_PREFIX`), which is then assigned to `$CUDA_PATH`, so the expected dlls are just in the root dir. Also, on Windows there is no `$CONDA_PREFIX\bin` directory.

Fix Windows dll loading for Conda

---

cupy/random/_generator_api.pyx

By just copy-pasting the docstrings of random functions, the reference pointers were to the legacy API ...

Point to the correct numpy random docs

---

cupy/_environment.py

Closes #5080
Unlike cuDNN v8 for Linux, cuDNN v8 for Windows requires the library path to be in the PATH.
This does not affect wheels for CUDA 10.0 or earlier as they are pinned to cuDNN v7.
I confirmed that this PR now correctly preloads cuDNN v8 on Windows with Python 3.6/3.7/3.8/3.9.

Adjust PATH when preloading to load cuDNN v8 correctly on Windows

---

docs/source/install.rst

This is just a nitpick PR following #5107:
- Supporting Jitify is not possible due to hiprtc's limitation. Plus I doubt we need Jitify once hiprtc fixes its support for `-I`.
- Dynamical parallelism on ROCm is hardware-specific. There's a device attribute or property that we can query. (My recollection is gfx906 does not support it, but I could be wrong.)

Revise ROCm doc

---

cupyx/jit/_typerules.py

`cupy.add(int64, int64)` unexpectedly outputs `uint8` value in CuPy JIT `cuda` mode.
Reproducer:
```py
import numpy
import cupy
size = 256
def f(x, z):
tid = jit.threadIdx.x + jit.blockIdx.x * jit.blockDim.x
partial_sum = jit.shared_memory(numpy.int64, size)
partial_sum[jit.threadIdx.x] = x[tid]
jit.syncthreads()
s = jit.blockDim.x >> 1
while s > 0:
if jit.threadIdx.x < s:
partial_sum[jit.threadIdx.x] += partial_sum[jit.threadIdx.x + s]
jit.syncthreads()
s = s >> 1
if jit.threadIdx.x == 0:
z[jit.blockIdx.x] = partial_sum[0]
x = cupy.arange(32 * size)
z = cupy.arange(32)
f[32, size](x, z)
print(z)
```
master:
```py
[128 128 128 128 128 128 128 128 128 128 128 128 128 128 128 128 128 128
128 128 128 128 128 128 128 128 128 128 128 128 128 128]
```
This …

Bugfix for typing rule of CuPy JIT

---

tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py

Rel #4132.
This PR adjusts the testing tolerance for `hfftn` in the case of HIP/ROCm.

Adjust testing tolerance for `hfftn` for HIP/ROCm

---

cupy/cuda/stream.pyx

Docstrings mention `ctypes` although we no longer uses `ctypes`.

Fix docs in `stream.pyx`

---

tests/cupy_tests/cuda_tests/test_device.py
tests/cupy_tests/cuda_tests/test_driver.py
tests/cupy_tests/cuda_tests/test_memory.py
tests/cupy_tests/fft_tests/test_cache.py
tests/cupy_tests/fft_tests/test_fft.py
tests/cupy_tests/random_tests/test_generator.py
tests/cupy_tests/random_tests/test_generator_api.py

Several tests are not resetting the current device after launching a thread.
I hope this closes https://github.com/cupy/cupy/issues/5124...

Use current device in tests

---

cupyx/_scatter.py

`cupy.scatter_add` has been removed in CuPy v8 but docs were not updated.

Fix docs of scatter_add

---

tests/cupy_tests/core_tests/test_ndarray.py

Follows up #5004 under HIP environment, keeping Device 0's stream alive over the D2D copy as well as giving longer enough busy-wait.

Fix stream usage on D2D copy test under HIP

---

cupyx/scipy/sparse/linalg/_eigen.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Fix TypeError reported at #5000.  Because of inaccurate `eigsh`, the added tests fail at `numpy_cupy_allclose`.

Fix TypeError in `svds`

---

docs/source/install.rst

Close #5142.
This PR changes ROCm limitations to mention the Per-thread default stream as well as removing several links to GitHub issues that should be covered in the earlier paragraphs.

Mention PTDS in ROCm Limitation

---

.pfnci/script.sh

FlexCI base image no longer contains CUDA components other than `cuda-driver`.

Fix for updated FlexCI base image

---

cupy/cusolver.pyx
tests/cupy_tests/test_cusolver.py

Close #4666.
This PR fixes `spsolve` to accept non-contiguous RHS input.

Properly handle non-contiguous RHS in cupyx.scipy.sparse.linalg.spsolve

---

cupyx/jit/__init__.py
cupyx/jit/_builtin_funcs.py
cupyx/jit/_compile.py
examples/jit/reduction_atomic.py
tests/cupyx_tests/jit_tests/test_raw.py

Part of https://github.com/cupy/cupy/issues/4290.
Example:
```py
def reduction(x, y, size):
tid = jit.blockIdx.x * jit.blockDim.x + jit.threadIdx.x
ntid = jit.blockDim.x * jit.gridDim.x
value = cupy.float32(0)
for i in range(tid, size, ntid):
value += x[i]
smem = jit.shared_memory(cupy.float32, 1024)
smem[jit.threadIdx.x] = value
jit.syncthreads()
if jit.threadIdx.x == cupy.uint32(0):
value = cupy.float32(0)
for i in range(jit.blockDim.x):
value += smem[i]
jit.atomic_add(y, 0, value)
```
Generated CUDA code:
```cpp
extern "C" __global__ void reduction(CArray<float, 1, true, true> x, CArray<float, 1, true, true> y, unsigned int size) {
unsigned int tid;
unsigned int ntid;
float value;
unsigned int i;
__shared__ float _smem1[1024];
float* smem;
tid = ((blockIdx.x * …
```

Add `cupyx.jit.atomic_add`

---

tests/cupy_tests/random_tests/test_distributions.py

Rel #4132.
This PR xfails tests for some distributions of `cupy.random.Generator` that are not supported under HIP/ROCm.
```
RuntimeError: Generator API not supported in HIP, please use the legacy one.
```

Xfail tests for random distribution generator under HIP/ROCm

---

cupy/cuda/memory.pyx
cupy_backends/cuda/api/runtime.pxd
cupy_backends/cuda/api/runtime.pyx
cupy_backends/hip/cupy_hip_common.h
cupy_backends/hip/cupy_hip_runtime.h
cupy_backends/stub/cupy_cuda_common.h
cupy_backends/stub/cupy_cuda_runtime.h
docs/source/user_guide/memory.rst
tests/cupy_tests/cuda_tests/test_memory.py

- CUDA 11.2+: `get_limit()` and `set_limit()` 
- CUDA 11.3+: `used_bytes()`, `free_bytes()`, and `total_bytes()`

CUDA 11.2/11.3: Support `MemoryAsyncPool` statistics and limits

---

.pfnci/script.sh
cupy/cuda/cupy_thrust.cu
cupy_setup_build.py

This fixes the constexpr issue for building CuPy with ROCm 4.2.0, and also reverts https://github.com/cupy/cupy/pull/4961 to make it use the latest ROCm.

Fix thrust compilation for ROCm 4.2.0

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/measurements.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

closes #5111
This PR renames `sum` to `sum_labels`, but leaves the old function name available as well. This follows what was done upstream in SciPy 1.6.0. I was initially going to add a warning if the old name was used, but it doesn't look like SciPy has one, so I followed the same approach here.
I think this can be backported to 9.x as well since it is not really a new feature, but an API fix.

add sum_labels to cupyx.scipy.ndimage.measure

---

cupy_backends/cuda/cupy_cusparselt.h
cupy_backends/cuda/libs/cusparselt.pxd
cupy_backends/cuda/libs/cusparselt.pyx
cupy_backends/cupy_cusparselt.h
cupy_backends/stub/cupy_cusparselt.h
examples/cusparselt/matmul.py

Close https://github.com/cupy/cupy/issues/5136. Merge https://github.com/cupy/cupy/pull/5149 first. 
Note that it's CUDA 11.2+ only. Rel https://github.com/cupy/cupy/pull/5050.
I've locally confirmed that it successfully builds and cusparselt example runs.

Support cuSPARSELt v0.1.0

---

cupy/cuda/stream.pyx
cupy_backends/cuda/stream.pxd
cupy_backends/cuda/stream.pyx
docs/source/user_guide/basic.rst
tests/cupy_tests/cuda_tests/test_stream.py

Close #3980. Fix #5143. Fix #5145.
For the reason in https://github.com/cupy/cupy/issues/3980#issuecomment-831487066, we call `getDevice()` every time we need to look up the device.
***UPDATE:*** major changes:
- Stream references are kept when entering the `with stream` context to avoid dead references, but not when calling `stream.use()` (which still keeps only the stream weakref)
- The stream stack now also records the *current* stream so that if a stream is deleted it can fall back correctly.
TODO:

Per device stream

---

docs/source/install.rst

Blocked by https://github.com/cupy/cupy/pull/5158
When backporting v0.0.1 needs to be added.

Fix cusparseLt not covered in docs

---

cupy/cuda/memory.pyx

This PR proposes changing the default value of `MemoryAsyncPool`'s `pool_handles` argument from `"default"` to `"current"`.
Let me first explain the terminology as it's a bit confusing 😅 For CUDA's new Stream Ordered Memory Allocator:
- the "current" mempool refers to the async mempool set to current via `cudaDeviceSetMemPool()`
- the "default" mempool is the unique mempool instance per device that's used when `cudaMallocAsync()` is called without any prior call to `cudaDeviceSetMemPool()`
Currently, when creating a `MemoryAsyncPool` instance we use `"default"`, but I consider this as *a defect if not a bug*, even though we do allow users to provide custom mempool handles to `pool_handles`:
- If CuPy is used in conjunction with other libraries (say RMM) which set a mempool to current: I …

`MemoryAsyncPool`: Use the "current" mempool instead of the "default" one

---

cupyx/tools/install_library.py

~~We may need an option to switch cuTENSOR v1.3.0 and v1.2.2 to install if v1.3.0 support is not to be backported to v9 as v1.3.0 is not binary compatible with previous versions. https://github.com/cupy/cupy/issues/5165#issuecomment-831001486~~
Just not backporting this PR is enough to leave v9 supporting v1.2.2. No additional switch is needed and we can use v9 `install_library.py`.

cuTENSOR v1.3.0 for library installer

---

cupy/_core/_routines_linalg.pyx
tests/cupy_tests/math_tests/test_matmul.py

`_get_stride_for_strided_batched_gemm` assumed that the input `a` has the canonical strides at least in the batch dimensions (`a.shape[:-2]`), which was not true.
This PR computes stride for `<t>gemmStridedBatched` from `a.shape[-2:]` by assuming `a` is C-contiguous in the sense of NumPy>=1.10 (see https://numpy.org/doc/stable/reference/arrays.ndarray.html#index-3 for `NPY_RELAXED_STRIDES_CHECKING`).

Fix matmul for input with relaxed strides

---

.pfnci/windows/test.ps1
install/build.py

Depends on ~#4969~
See https://github.com/cupy/cupy/pull/4963#issuecomment-805927327

Avoid using `pip install -e` on Windows CI for performance

---

cupy/cuda/cupy_thrust.cu

constexpr does not work the same way in c++11 and 14 and mscv 15 has no full c++14 support
so we need hacks like this 😭😭

Fix windows constexpr

---

docs/source/install.rst

We observed failure in CUDA 11.3 fft cache tests, so let's skip supporting it in this month's release.
https://github.com/chainer/chainer-test/pull/658

Tentatively remove CUDA 11.3 from support list

---

cupy/random/_generator_api.pyx

Remove duplicated subtraction in `cupy.random.Generator.integers`

---

cupy/_core/internal.pyx
cupy/cuda/memory.pyx
cupy_backends/cuda/api/driver.pyx
cupy_backends/cuda/api/runtime.pxd
cupy_backends/cuda/api/runtime.pyx
cupy_backends/cuda/libs/cusparse.pyx

This eliminates the following warnings:
```
cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
```

Use cdef instead of cpdef where appropraite

---

.gitmodules

CUB repository is now at https://github.com/NVIDIA/cub

Fix cub repository url

---

setup.py

Cython 3.0a7 causes a build failure with the current codebase:
```
building 'cupy_backends.cuda.api.runtime' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D_FORCE_INLINES=1 -DCUPY_CUB_VERSION_CODE=-1 -DCUPY_JITIFY_VERSION_CODE=8f42e9a -I/home/maehashi/Development/release-20210527/cupy-10.0.0a1/install/../cupy/_core/include/cupy/cub -I/home/maehashi/Development/release-20210527/cupy-10.0.0a1/install/../cupy/_core/include -I/usr/local/cuda/include 
-I/opt/pyenv/versions/3.7.0/include/python3.7m -c cupy_backends/cuda/api/runtime.cpp -o build/temp.linux-x86_64-3.7/cupy_backends/cuda/api/runtime.o
cupy_backends/cuda/api/runtime.cpp: In function ‘PyObject* __pyx_f_7cpython_11contextvars_get_value(PyObject*, …
```

Exclude Cython 3 from setup_requires
