cupy/_environment.py, setup.py
=> Fix files not closed

cupyx/jit/_compile.py, tests/cupy_tests/functional_tests/test_vectorize.py
=> Support assignment of compile-time constants in CuPy JIT

cupy/_environment.py, setup.py
=> [backport] Fix files not closed

cupyx/tools/install_library.py, install/build.py
=> [backport] Bump cuDNN to v8.1.0

cupy/cuda/compiler.py
This PR partially reverts the change made in https://github.com/cupy/cupy/pull/4558, where `_get_arch` was simplified.
`_get_arch` was originally for the case that nvrtc supported only lower compute capability than nvcc, but at the same time, it also worked for the situation that the compute capability that the CUDA Toolkit version supported was lower than the GPU did.
The situation may have to be always an error as, for example, one should not expect to run Ampere on CUDA 10.x, but we keep working user's environment here. (Actually, we have to build CUDA 9.0 wheels on Tesla T4 (CC = 7.5))
=> Revert `_get_arch`

docs/source/conf.py
Also fix the issue that cupyx docs are not linked to GitHub.
Spin off from #4619 to fix build issues in https://github.com/chainer/chainer-test/pull/634
=> Support building docs against pip installed cupy

docs/source/conf.py
=> [backport] Support building docs against pip installed cupy

cupyx/jit/_compile.py, cupyx/jit/_types.py, tests/cupy_tests/functional_tests/test_vectorize.py
Part of #4290.
~Depends on #4672.~
=> Support while/for-statement in CuPy JIT

cupy_setup_build.py
Should fix : https://github.com/cupy/cupy-release-tools/pull/66
=> Use MSVC 14.0 with CUDA 11.2

tests/cupy_tests/test_cudnn.py
=> [backport] Fix tests for cuDNN 8.1

install/build.py
=> [backport] Remove maximum cuDNN version check

cupy/core/core.pyx, cupy/core/include/cupy/_cuda/cuda-11.2/cuda_fp16.h, cupy/core/include/cupy/_cuda/cuda-11.2/cuda_fp16.hpp, cupy/cuda/compiler.py
=> [backport] Support CUDA 11.2

cupy_setup_build.py
=> [backport] Use MSVC 14.0 with CUDA 11.2

README.md, docs/source/install.rst
=> [backport] Add CUDA 11.2 to docs

README.md, docs/source/install.rst
https://github.com/cupy/cupy/issues/4663#issuecomment-781807982
=> Document that only x86_64 wheels are provided

README.md, docs/source/install.rst
=> [backport] Document that only x86_64 wheels are provided

docs/source/install.rst
=> [backport] Update document for cuDNN 8.1

docs/source/install.rst
Closes #4478
Merge after https://github.com/chainer/chainer-test/pull/635
=> Add NCCL 2.8 to supported version

docs/source/install.rst
=> [backport] Add NCCL 2.8 to supported version

docs/source/install.rst, setup.py
=> Update Python / NumPy / SciPy requirements

MANIFEST.in, cupy_setup_build.py, pyproject.toml, readthedocs.yml, setup.py
=> [backport] Always run cythonize on sdist installation

.pfnci/windows/test.ps1
=> [backport] Publish results even if build failed in Windows CI

cupy/cuda/cupy_thrust.cu, cupy_setup_build.py
=> [backport] Fix thrust compilation in MSVC 14 for CUDA 11.2

cupy_backends/cuda/libs/cupy_cusparse.h
Fix cusparse versioning bug (manual backport of #4419)
=> [backport] Fix cuSPARSE module build failure with CUDA 10.1 on Windows

docs/source/install.rst
(Jenkins not needed, please merge after checking RTD build preview)
=> Fix dead link to issue

cupy_backends/cuda/api/runtime.pxd
=> Add missing attrs

docs/source/install.rst
=> [backport] Fix dead link to issue

cupy/cuda/cupy_thrust.cu
=> [backport] Disable some `constexpr` only for windows

pyproject.toml, setup.py
=> Remove `pyproject.toml`

tests/cupy_tests/fft_tests/test_callback.py
https://github.com/cupy/cupy/pull/4734#issuecomment-785392652
=> Skip callback tests for this release

pyproject.toml, setup.py
=> [backport] Remove `pyproject.toml`

setup.py
=> [backport] Fix Cython setup requirement out of sync

docker/python3/Dockerfile
Merge after uploading a wheel.
=> Update Docker image for v9.0.0b3 (use CUDA 11.2)

docker/python3/Dockerfile
Previous https://github.com/cupy/cupy/pull/4579
=> Bump Dockerfile version to v8.5.0

docker/rocm/Dockerfile, docker/rocm/README.md, docs/source/install_rocm.rst
Merge after uploading a wheel.
=> Add Docker image for ROCm and documentation

docker/python3/Dockerfile
=> Fix Docker image to use CUDA 11.1

tests/cupy_tests/random_tests/test_generator.py, tests/cupy_tests/random_tests/test_sample.py
Xfail some unstable chi-squared tests.
=> Xfail chi-squared test for some random functions under ROCm/HIP

.github/CODEOWNERS
=> [backport] Add CODEOWNERS

README.md, docs/source/install.rst
=> Revert "Remove `cupy-cuda112` support from documentation"

cupyx/scipy/sparse/compressed.py, cupyx/scipy/sparse/sputils.py
~~***DO NOT MERGE***~~ Another guess work...
=> Windows: fix sparse matrix indexing type

cupyx/tools/install_library.py
=> [backport] Bump cuDNN to v8.1.1 in library installer tool

tests/cupy_tests/math_tests/test_sumprod.py
=> [backport] Windows: Fix test condition for CUB device kernels

cupy_backends/cuda/api/runtime.pxd
=> Fix: avoid redeclaring attributes

.flake8.cython, cupy/__init__.py, cupy/core/_fusion_op.py, cupy/testing/parameterized.py, setup.py
=> [backport] Use newest versions of stylecheck packages

cupy/random/_generator.py, tests/cupy_tests/random_tests/test_generator.py
=> [backport] Support int argument for Dirichlet shape

cupy/core/_cub_reduction.pyx, tests/cupy_tests/core_tests/test_raw.py
~~DO NOT MERGE!~~ Close #4383.
I don't have access to any Windows+CUDA machine, so this is purely guess work.
=> Windows: Fix compiler error for CUB block reduction kernels

cupy/_statistics/histogram.py
=> [backport] Windows: Fix histogram test failures

cupy/core/_cub_reduction.pyx
=> [backport] Windows: Fix compiler error for CUB block reduction kernels

cupy/random/_generator.py, tests/cupy_tests/random_tests/test_generator.py
=> Unify linux/windows randint with NumPy

cupy/random/_generator.py, tests/cupy_tests/random_tests/test_generator.py
=> [backport] Unify linux/windows randint with NumPy

.pfnci/windows/test.ps1
=> [backport] Fix pytest opts for Windows CI

cupy/cuda/cupy_thrust.cu
=> [backport] ROCm: Fix sorting bug

tests/cupy_tests/lib_tests/test_polynomial.py
Rel #4132.
Tolerance in case HIP and `polymul`.
=> Adjust tolerance of `TestPolyArithmeticDiffTypes` under HIP/ROCm

.github/workflows/backport.yml
Blocked by https://github.com/cupy/backport/pull/20
=> Add GHAction for automatic backport

.github/workflows/backport.yml
Blocked by https://github.com/cupy/backport/pull/22
=> Use access token for automated backport

cupy/core/_fusion_op.py, cupy/cusparse.py, cupy/fft/_fft.py, cupy/lib/_routines_poly.py, cupy/testing/helper.py, cupyx/fallback_mode/fallback.py
=> [backport] Fix: code quality issues

cupyx/scipy/sparse/__init__.py, cupyx/scipy/sparse/base.py
I overlooked this during #4213 review :bow:
=> Fix redeclaration of sparse warning classes

cupy/cuda/stream.pyx
Fix parameters list in https://docs.cupy.dev/en/latest/reference/generated/cupy.cuda.Stream.html
=> Fix broken Stream docs

docs/source/reference/environment.rst
=> Reformat environment variables table

tests/cupy_tests/math_tests/test_sumprod.py
=> [backport] Windows: Fix cuTENSOR tests

cupy/cusolver.pyx, cupy_backends/cupy_lapack.h
Follow-up of https://github.com/cupy/cupy/pull/4690#discussion_r579984220. Overwrites the intermediate array to reduce memory footprint, which seems to also perform faster.
=> Improve batched SVD

tests/cupy_tests/cuda_tests/test_device.py
=> Xfail test on sparse handle under ROCm/HIP

tests/cupy_tests/core_tests/test_ndarray_conversion.py, tests/cupy_tests/core_tests/test_ndarray_unary_op.py
Tests fail on rocm-ci-report but I cannot reproduce them on my local.
=> Xfail some tests under ROCm/HIP

tests/install_tests/test_build.py
=> Fix to test checking HIP version

cupyx/scipy/sparse/compressed.py
Removed duplicated code and intrincated ifs
=> Clean-up sparse max/min argmax/argmin

docs/source/reference/environment.rst
=> [backport] Reformat environment variables table

.github/workflows/backport.yml, .github/workflows/pretest.yml
Use human readable name instead of full path.
=> Add names for workflows

.github/workflows/pretest.yml
=> [backport] Add names for workflows

cupy/core/include/cupy/_cuda/cuda-11.2/cuda_fp16.h
Seems the only diff is comment, but bump it anyway.
=> Bump headers to CUDA 11.2.2

cupy/core/_routines_math.pyx, cupy/core/_routines_statistics.pyx, cupy/cuda/__init__.py, cupy/cuda/cutensor.py
Prepare for #4873. ~~Blocked by #4919.~~
The change starts at 1d55ca52.
=> Add `cupy/cuda/cutensor.py`

cupy/linalg/_einsum.py
=> Fix cutensor import

cupyx/tools/install_library.py, tests/cupyx_tests/tools_tests/test_install_library.py
Depends on ~https://github.com/cupy/cupy/pull/4912~ (merged) and #4852
=> Add NCCL to library installer

cupy/core/include/cupy/carray.cuh, cupyx/jit/_compile.py, tests/cupyx_tests/jit_tests/test_raw.py
=> Support tuple indexing in CuPy JIT

cupyx/jit/__init__.py, cupyx/jit/_compile.py, cupyx/jit/_interface.py, cupyx/jit/_types.py, tests/cupyx_tests/jit_tests/test_raw.py
Depends on https://github.com/cupy/cupy/pull/4939.
=> Support `__syncthreads()` in CuPy JIT

tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
Including the case that CuPy returns 255 where SciPy returns zero.
```
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=1e-05
E       
E       Mismatched elements: 1 / 100 (1%)
E       Max absolute difference: 255
E       Max relative difference: 0.
E        x: array([[  7,   7,   5,   6,   6,   4,   5,   5,   2,   6],
E              [  5,   9,   6,   5,   9,   0,   1,   2,   9,   9],
E              [  3,   4,   6,   5,   4,   2,   3,   1,   8,   7],...
E        y: array([[7, 7, 5, 6, 6, 4, 5, 5, 2, 6],
E              [5, 9, 6, 5, 9, 0, 1, 2, 9, 9],
E              [3, 4, 6, 5, 4, 2, 3, 1, 8, 7],...
```
=> Xfail some conditions of ndimage interpolation tests under ROCm/HIP

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump Dockerfile version to v9.0.0rc1

docker/python3/Dockerfile
=> Bump Dockerfile version to v8.6.0

cupyx/jit/__init__.py, cupyx/jit/_compile.py, cupyx/jit/_interface.py, cupyx/jit/_types.py, tests/cupyx_tests/jit_tests/test_raw.py
=> Support shared memory in CuPy JIT

.pfnci/script.sh
Follow-up for #4973
https://github.com/cupy/cupy/pull/4980#issuecomment-808092315
=> Update list of known branches

cupy/cuda/cupy_thrust.cu
=> Use THRUST_OPTIONAL_CPP11_CONSTEXPR

cupyx/jit/_interface.py
=> CuPy JIT: Print kernel code

docs/source/overview.rst, docs/source/reference/difference.rst, docs/source/reference/routines.rst
Close #2750.
Close #3692.
Close #2085.
=> More documentation on the supported backends

tests/cupy_tests/manipulation_tests/test_basic.py
=> Add debug print for flaky test

docs/source/install.rst
Fix an oversight of mine. This needs to be backported.
=> Fix code block in installation guide

cupy/_core/_kernel.pxd, cupy/_core/_kernel.pyx, cupyx/jit/_compile.py, cupyx/jit/_typerules.py
Resolve https://github.com/cupy/cupy/issues/5018.
=> CuPy JIT: Use C++-like typing rule in 'cuda' mode

.github/workflows/backport.yml
Blocked by ~https://github.com/cupy/backport/pull/27~ merged
=> Use bot mode in automatic backport

tests/cupy_tests/cuda_tests/test_memory.py
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/3519/
=> Mark some memory tests as `testing.slow`

docs/source/reference/interoperability.rst
=> Improve the documentation on interoperability

cupy_backends/cuda/libs/cusparselt.pyx, cupy_backends/stub/cupy_cusparselt.h, cupyx/_runtime.py
=> [backport] Print cuSPARSELt version in `show_config`

examples/cusparselt/matmul.py
=> [backport] Fix cuSPARSELt example not to use internal function

cupyx/jit/_compile.py, cupyx/jit/_interface.py, docs/source/reference/kernel.rst, docs/source/tutorial/kernel.rst, examples/jit/elmentwise_op.py, examples/jit/reduction_simple.py
=> CuPy JIT documentation

cupy/cuda/memory.pyx, cupy_backends/cuda/stream.pyx
To prevent further error like #5004
=> Improve comments for memory and stream API usage

cupy/cuda/memory.pyx, tests/cupy_tests/cuda_tests/test_memory.py
=> Support PTDS in CuPy memory pool

cupy/_core/_kernel.pxd, cupy/_core/_kernel.pyx, cupy/lib/_routines_poly.py
=> Fix some internal `cpdef` functions to `cdef` in `_kernel.pyx`

docs/source/install.rst
@takagi could you fill these sections?
=> Add ROCm limitations to docs

cupy/cuda/device.pyx, tests/cupy_tests/cuda_tests/test_device.py
WIP. Fixes https://github.com/cupy/cupy/issues/5006.
=> Make cupy.cuda.Device context manager interface thread safe

cupy_backends/stub/cupy_cusparselt.h
Follows up #4883.
- Removed extra indent
- Untabify
=> Cosmetic change in cuSPARSELt stub header

cupy/_core/_routines_indexing.pyx, tests/cupyx_tests/test_scatter.py
https://ci.preferred.jp/cupy.experimental.win.cuda100/71661/
=> Fix integer `scatter_add` failure on Windows

cupy/random/_generator_api.pyx, cupy/random/cupy_distributions.cu, cupy/random/cupy_distributions.cuh, tests/cupy_tests/random_tests/test_distributions.py
We were not supporting arrays for lam parameter ...
~merge after #4907~
=> Fix poisson to support lam array

docs/requirements.txt
=> Use Sphinx 4

cupyx/_runtime.py
=> Add NVCC path and Python version to `show_config`

cupyx/tools/install_library.py
~Blocked by #5192 (cuTENSOR 1.3)~ merged
=> Add libraries for CUDA 11.3

cupyx/tools/install_library.py
=> [backport] Add libraries for CUDA 11.3

cupy/_core/syncdetect.py, docs/source/reference/prof.rst
=> Remove syncdetect APIs

docs/source/install.rst
Blocked by chainer/chainer-test#655 and https://github.com/cupy/cupy/pull/5192
=> cuTENSOR v1.3 on documentation

cupy/__init__.py, cupy/_environment.py
=> Add warnings for duplicate installation

cupy/cutensor.pyx, cupy/linalg/_einsum.py
closes https://github.com/cupy/cupy/issues/5204
=> Add check_availability for cuTensor routines

docs/source/reference/ndimage.rst
=> Add `cupyx.scipy.ndimage.sum_labels` to docs

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump Dockerfile version to v10.0.0a1

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump Dockerfile version to v9.1.0

cupy/_core/__init__.py, cupy/_core/_gufuncs.py, cupy/_core/_routines_linalg.pxd, cupy/_core/_routines_linalg.pyx, cupy/linalg/_product.py
Closes #5170 
https://cupy--5174.org.readthedocs.build/en/5174/reference/generated/cupy.matmul.html
=> Fix `matmul` docstring

docs/source/reference/fft.rst, docs/source/reference/scipy_fft.rst, docs/source/user_guide/fft.rst, docs/source/user_guide/index.rst, docs/source/user_guide/memory.rst
Close #5199. Part of https://github.com/cupy/cupy/issues/4902#issuecomment-813205619.
=> Add user guide for FFT

docs/source/user_guide/basic.rst, docs/source/user_guide/cuda_api.rst
Part of https://github.com/cupy/cupy/issues/4902#issuecomment-813205619.
=> Add user guide for streams & events

cupyx/scipy/sparse/base.py, cupyx/scipy/sparse/coo.py, cupyx/scipy/sparse/csc.py, cupyx/scipy/sparse/csr.py, cupyx/scipy/sparse/sputils.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
=> Add reshape method for COO, CSR and CSC matrices

docs/source/user_guide/cuda_api.rst, docs/source/user_guide/interoperability.rst
Follow-up of #5283, see https://github.com/cupy/cupy/pull/5283#issuecomment-851437165.
=> Document `ExternalStream`

cupy/_math/misc.py
=> Support `nan`, `posinf`, `neginf` in `cupy.nan_to_num`

docs/source/user_guide/cuda_api.rst, docs/source/user_guide/interoperability.rst
Backport of #5305 by @leofang.
=> [backport] Document `ExternalStream`

setup.py
=> Add upper restrictions to NumPy/SciPy versions

cupy/_core/include/cupy/carray.cuh, tests/cupy_tests/core_tests/test_carray.py
Fixes #5328 
Verified that test fails in master branch
=> Fix large arrays assignment

docs/source/user_guide/basic.rst
In this PR I propose several improvements to the 'Basics of cupy.ndarray' and 'Current Device' sections.
=> docs: user_guide/basic.rst: various improvements

cupy/_core/_gufuncs.py, tests/cupy_tests/core_tests/test_gufuncs.py
This mostly completes the support for GUFunc adding the same core characteristics than numpy
=> Adding GUFunc order, dtype and casting kwarg support

cupy/cusparse.py
=> Remove unnecessary print

cupy/_core/_gufuncs.py, tests/cupy_tests/core_tests/test_gufuncs.py
~Depends on #5260~
Adds tests for axes, type, signatures, and out features of gufuncs.
=> Increase test coverage for Generalized Universal Functions

docs/source/index.rst, setup.py
Follow-up #5254.
The package description appears in the PyPI page: https://pypi.org/project/cupy/
=> Update tag lines in package description and docs index

cupyx/__init__.py, cupyx/_gufunc.py, docs/source/reference/ufunc.rst
Make it a public API
Docs are generated in:
https://cupy--5408.org.readthedocs.build/en/5408/reference/generated/cupyx.GeneralizedUFunc.html
=> Expose `_GUFunc` through `cupyx`

.mergify.yml
Closes #5345
https://docs.mergify.io/actions/comment/#request-for-action
=> Notify conflict by mergify

cupy/_math/trigonometric.py, tests/cupy_tests/math_tests/test_trigonometric.py
=> Fix `numpy.unwrap` for NumPy 1.21

docs/source/upgrade.rst
This PR expects that https://github.com/cupy/cupy/pull/5251 and https://github.com/cupy/cupy/pull/5214 will be merged. -> done
=> Add upgrade guide for v10

tests/cupy_tests/math_tests/test_trigonometric.py
=> Fix `unwrap` tests for v9

cupy/_core/_routines_indexing.pyx, cupy/_core/_routines_math.pyx, cupy/_core/core.pyx, cupy/_core/include/cupy/hip_workaround.cuh, cupyx/jit/_builtin_funcs.py, tests/cupyx_tests/jit_tests/test_raw.py
=> Add HIP symbol redefinitions

cupy/_core/core.pyx, tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
Close #1288, close #5427, close #5431.
=> Fix compatibility issues of `ndarray.view`

tests/cupyx_tests/tools_tests/test_install_library.py
This fixes failues in slow test.
Follow-up: #5327
(It seems that I mistakenly closed #5404...)
=> Fix preloading slow tests

tests/cupy_tests/core_tests/test_dlpack.py
Manually backport part of #5306.
=> [v9] Add missing DLPack test for complex numbers

cupy/cudnn.pyx
This is harmless (so far) but it's better to avoid calling CUDA APIs on import.
=> Do not call cudnnGetVersion on import

cupy/_core/_kernel.pyx, tests/cupy_tests/core_tests/test_ndarray_ufunc.py
=> Fix `types` attribute of ufunc 

docs/source/user_guide/basic.rst
Various improvements and fixes to `basic.rst` but mainly to the "Device agnostic code" section.
=> docs: user_guide/basic.rst: impr. device agnostic section

setup.py
=> Update setup.py numpy/scipy pinning

cupy_setup_build.py
Closes #5476 
Thanks to @kmaehashi for the alternative solution
=> Import numpy before Cython

cupy/random/_generator_api.pyx, tests/cupy_tests/random_tests/common_distributions.py
Fixes #5466
Thanks to @toslunar 
Added tests cases with 2d large shapes that are verified to fail in master.
=> Fix random generator output not being raveled

cupyx/scipy/signal/signaltools.py, tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
This fixes the actual routine while
#5368 deals with the tests
Ref: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.medfilt.html
=> Fix signaltools `medfilt` for `scipy>=1.7.0`

cupy/linalg/_eigenvalue.py
=> Fix docs of eigh and eigvalsh

docs/source/user_guide/interoperability.rst
=> Use `from_dlpack` instead of fromDlpack

cupy/_core/_routines_manipulation.pyx, cupy/_core/internal.pyx, tests/cupy_tests/manipulation_tests/test_shape.py
Fix #5469 and some other issues.
=> Fix reshape

cupy/linalg/_solve.py, tests/cupy_tests/linalg_tests/test_solve.py
=> Fix `linalg.lstsq` for empty matrix 

cupy/_core/_routines_indexing.pyx, cupy/_core/_routines_math.pyx, cupy/_core/core.pyx, cupy/_core/include/cupy/hip_workaround.cuh
Backport of #5362 by @leofang. The JIT part is removed in this PR as it's only applicable to the master branch.
=> [backport] Add HIP symbol redefinitions

cupyx/tools/install_library.py
Please merge this after CUDA 11.4 support.
=> cuDNN v8.2.2

cupy_backends/cuda/libs/cusparse.pyx, cupyx/scipy/sparse/linalg/_solve.py
=> [v9] Add missing checks and `_setStream()`

cupy_setup_build.py
=> Add missing hipSPARSE include to builder

cupy/linalg/_product.py, tests/cupy_tests/linalg_tests/test_product.py
=> Make `matrix_power` support stacked matrices 

cupyx/tools/install_library.py, docs/source/install.rst
=> [backport] NCCL v2.10.3 for library installer and document

docs/source/reference/scipy_fft.rst, docs/source/user_guide/fft.rst
Related to https://github.com/scipy/scipy/issues/14266#issuecomment-880029174. We should present at least a self-contained snippet to make it more clear.
cc: @AnirudhDagar @peterbell10 @rgommers
=> Document `scipy.fft` backend usage

cupy_backends/cuda/api/runtime.pyx, cupy_backends/cuda/libs/cusparselt.pyx, cupy_backends/cuda/stream.pyx
Backport of #5522 by @kmaehashi
=> [backport] Hide modules from public APIs

cupy/cusolver.pyx, cupy/cusparse.py
Backport of #5492 by @kmaehashi
=> [backport] Fix availability tests in cuSOLVER and cuSPARSE

README.md, docs/source/install.rst
=> [backport] Support CUDA 11.4 on documents

.github/workflows/auto-cc.yml
The bot was not working for issues...
=> Fix auto notify bot for issues

cupyx/scipy/sparse/linalg/__init__.py, cupyx/scipy/sparse/linalg/_iterative.py, docs/source/reference/sparse.rst, tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
This PR add `cupyx.sparse.linalg.cgs` to sparse linear algebra.
=> Add cupyx.scipy.sparse.linalg.cgs

cupy/cusolver.pyx, cupy_backends/hip/cupy_rocsolver.h
- make `_gesvdj_batched` cpdef'd
- fix work space size on ROCm for gesvd
=> Code fix for {cu, roc}SOLVER

cupy/cuda/memory.pyx
This should reduce memory consumption when importing cupy
=> Fix CUDA API call on module initialization

cupyx/scipy/linalg/decomp_lu.py, tests/cupy_tests/core_tests/test_ndarray_unary_op.py, tests/cupy_tests/functional_tests/test_vectorize.py, tests/cupy_tests/indexing_tests/test_generate.py, tests/cupy_tests/random_tests/test_distributions.py, tests/cupyx_tests/test_scatter.py
- Remove `xfail` for some xpass'd tests
- Fix tests that are not supported on HIP
This PR should be backported.
=> Fix some tests for HIP

cupyx/scipy/linalg/decomp_lu.py, tests/cupy_tests/core_tests/test_ndarray_unary_op.py, tests/cupy_tests/functional_tests/test_vectorize.py, tests/cupy_tests/indexing_tests/test_generate.py, tests/cupy_tests/random_tests/test_distributions.py, tests/cupyx_tests/test_scatter.py
=> [backport] Fix some tests for HIP

.pfnci/linux/tests/_build_and_test.sh, .pfnci/linux/tests/_environment.sh, setup.py
`all` should list all dependencies.
Depends on #5576
=> Add Cython to `all` requirements

cupy_backends/cuda/libs/nccl.pyx
(patch authored by Greg Brockman)
=> Release the GIL for several NCCL ops

cupyx/scipy/sparse/linalg/__init__.py, cupyx/scipy/sparse/linalg/_solve.py, docs/source/reference/sparse.rst, tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
This PR add MINRES solver to sparse linear algebra.
=> Add cupyx.scipy.sparse.linalg.minres

cupyx/scipy/signal/_signaltools_core.py, cupyx/scipy/signal/signaltools.py, tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
=> Fix FFT convolve for shapes containing 1

docs/requirements.txt
=> Update sphinx to 4.1.2

.pfnci/linux/tests/_build_and_test.sh, tests/cupy_tests/math_tests/test_arithmetic.py
=> Fix cubic `for_all_dtypes_combination` tests

cupy/random/_generator_api.pyx
Fix docstrings of some Generator distributions.
=> Fix random docstring

cupyx/_runtime.py
```
CUDA Build Version           : 11040 (CUDA Python: 0+untagged.13.g427c597)
```
=> Show CUDA Python version

cupy_backends/cuda/libs/nccl.pxd
Close #5529.
This PR adds `ncclAvg` operation introduced in NCCL 2.10.
=> Add ncclAvg and ncclBfloat16 for NCCL

cupy/_manipulation/add_remove.py, tests/cupy_tests/manipulation_tests/test_add_remove.py
=> Fix `unique` for empty array

cupy/_core/_routines_linalg.pyx
Rel #5592.
This PR fixes CI failures relating hipblas found in #5630. I will make another PR to fix other lines relating to ROCm's new version definition.
=> Fix version check for new ROCm version definition

cupy/fft/_fft.py, tests/cupy_tests/core_tests/fusion_tests/fusion_utils.py, tests/cupy_tests/core_tests/test_raw.py, tests/cupy_tests/cuda_tests/test_compiler.py
=> [backport] Rest of version check fix for new ROCm version definition

tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
https://github.com/cupy/cupy/pull/5673#discussion_r698180409
=> Improve performance of `TestSplineFilter1dLargeArray`

tests/cupy_tests/linalg_tests/test_eigenvalue.py
The update is taken from #5555 with minor change (skip testing on HIP entirely).
=> [v9] Update `test_eigenvalue.py`

cupy/random/_generator_api.pyx
=> [backport] Fix random docstring

tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py, tests/cupy_tests/core_tests/test_ndarray_scatter.py, tests/cupy_tests/cuda_tests/test_texture.py, tests/cupy_tests/lib_tests/test_polynomial.py, tests/cupy_tests/linalg_tests/test_einsum.py, tests/cupy_tests/logic_tests/test_truth.py, tests/cupy_tests/math_tests/test_sumprod.py, tests/cupy_tests/random_tests/test_distributions.py, tests/cupy_tests/statistics_tests/test_histogram.py, tests/cupy_tests/statistics_tests/test_meanvar.py, tests/cupy_tests/test_cublas.py, tests/cupy_tests/test_cudnn.py, tests/cupy_tests/test_cusolver.py, tests/cupy_tests/test_cusparse.py, tests/cupy_tests/test_cutensor.py, tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py, tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_construct.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Backport of #5599 by @toslunar
=> [backport] Stop inheriting `unittest.TestCase` for performance

tests/cupyx_tests/fallback_mode_tests/test_notifications.py, tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
https://github.com/cupy/cupy/pull/5659/files#r691093294
=> Make test parameter names static

cupy/_core/internal.pyx, tests/cupy_tests/core_tests/test_ndarray_indexing.py
=> Fix exception for indexing with multiple ellipses 

cupy/cuda/stream.pyx
I felt that the current error message is a bit difficult to understand what is happening.
=> Improve stream mismatch error message

.github/workflows/docker.yml
=> Add workflow to test/build/push docker images on pull-request/release

cupy_backends/hip/cupy_hipblas.h, cupy_backends/hip/cupy_hipsparse.h, cupy_backends/hip/cupy_rocsolver.h
Fixes https://github.com/cupy/cupy/issues/5768
=> Include `stdexcept` in hip headers

cupy_backends/hip/cupy_hipblas.h, cupy_backends/hip/cupy_rocsolver.h
Backport of #5769 by @emcastillo
=> [backport] Include `stdexcept` in hip headers

README.md, docs/source/install.rst
=> Use custom index for pre-release wheels

.pfnci/linux/main-flexci.sh
* Improve FlexCI output.
* Show full log URL in a separate line to make copy-paste easier.
=> Improve FlexCI output

.pfnci/linux/tests/cuda114.Dockerfile, .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile, docs/source/install.rst, setup.py
=> Drop support for Python 3.6

tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
Follow-up #5791
I failed to test #5791 correctly... I confirmed this PR correctly skips on CUDA 10.2.
=> Fix test skip issue

docs/source/upgrade.rst
Backport of #5824 by @kmaehashi
=> [backport] Update upgrade guide

.pfnci/linux/tests/_environment.sh, .pfnci/linux/tests/rocm.sh
Backport of #5955 by @kmaehashi
=> [backport] CI: Do not run full combination test even for branch tests for ROCm

cupy/array_api/_array_object.py, cupy/array_api/_typing.py, tests/cupy_tests/array_api_tests/test_creation_functions.py
This PR includes
- patch from numpy/numpy#20129
- cherry-pick of patch from numpy/numpy#20071
=> Update the Array API module

cupy/random/__init__.py, cupy/random/_bit_generator.pyx, cupy/random/_generator_api.pyx, cupy/random/cupy_distributions.cu, cupy/random/cupy_distributions.cuh, docs/source/install.rst, install/cupy_builder/_modules.py, install/cupy_builder/cupy_setup_build.py, tests/cupy_tests/random_tests/test_distributions.py, tests/cupy_tests/random_tests/test_generator_api.py
=> Enable new random api in ROCm 4.3

docs/source/user_guide/interoperability.rst
Blocked by #5970 
Closes #5833
=> Add PyTorch with RawKernel example to docs

docs/source/user_guide/difference.rst
=> Mention `np.matrix` in the difference section

cupy/cuda/device.pyx
=> Fix comment in device switching

cupy/cuda/stream.pyx, cupy/cuda/texture.pyx
Fixes #5943 for streams.
Follow-up #5963, #5984.
=> Avoid using with context for streams

docs/source/user_guide/performance.rst
=> Cover a bit more of cuTENSOR in perf guide

.pfnci/linux/main-flexci.sh
Backport of #5814 by @kmaehashi
=> [backport] Improve handling of FlexCI test runs

.pfnci/linux/main-flexci.sh
Backport of #5867 by @kmaehashi
=> [backport] Upload cache even when test failed in FlexCI

cupy/cuda/compiler.py
Closes #5959.
I chose SHA1 based on the quick micro benchmark:
```py
>>> a = ('*' * 4096).encode()
>>> timeit('hashlib.md5(a).hexdigest()', globals=globals())
6.068204950541258
>>> timeit('hashlib.sha1(a).hexdigest()', globals=globals())
4.463794406503439
>>> timeit('hashlib.sha256(a).hexdigest()', globals=globals())
9.106148925609887
```
Under Python 3.6.8 on CentOS 8 stream with FIPS-compilant mode enabled:
```
>>> hashlib.md5(b"foo").hexdigest()
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
>>> hashlib.md5(b"foo", usedforsecurity=False).hexdigest()
'acbd18db4cc2f85cedef654fccc4a4d8'
>>> hashlib.sha1(b"foo").hexdigest()
'0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33'
>>> hashlib.sha1(b"foo", …
```
=> Use SHA1 hash for kernel cache key to support Linux in FIPS-compliant mode

README.md, docs/source/install.rst
=> [backport] Support CUDA 11.5 on documents

cupyx/tools/install_library.py
=> [backport] Support cuTENSOR 1.3.3

cupyx/tools/install_library.py
=> [backport] Support CUDA 11.5 for library installer

docs/source/upgrade.rst
=> Update upgrade guide for v10

cupyx/tools/install_library.py
Backport of #6007 by @kmaehashi
=> [backport] Fix cuTENSOR installation on Windows

cupy/cuda/compiler.py
Backport of #5779 by @leofang
Conflict manually resolved.
=> [backport] Fix: Allow generating cubins for the max known CC

docs/source/install.rst, setup.py
=> Add Python 3.10.0 to support list

cupy/__init__.py, cupy/_environment.py
=> Improve import error message

cupy/__init__.py, cupy/_environment.py, cupy/cuda/cudnn.py, cupy/cudnn.pyx, cupyx/_runtime.py
=> Lazy-preload cuDNN

cupyx/scipy/signal/_signaltools_core.py
=> Fix: Add missing output dtype check for direct correlate/convolve 

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump cupy version in Dockerfile to v10.0.0rc1

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump cupy version in Dockerfile to v9.6.0

docs/source/upgrade.rst
=> Add v11 to compatibility matrix

CITATION.bib, README.md
Add citation file to make it appear in the About section of the repo top page:
https://docs.github.com/ja/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
=> Add CITATION.bib and update README

setup.cfg
Workaround for https://github.com/pypa/setuptools/issues/2885
=> Workaround DeprecationWarning raised from pkg_resources

docs/source/install.rst
=> Remove LLVM_PATH note on document

cupy/array_api/__init__.py, cupy/array_api/_array_object.py, cupy/array_api/_creation_functions.py, cupy/array_api/_data_type_functions.py, cupy/array_api/_searching_functions.py, cupy/array_api/_set_functions.py, tests/cupy_tests/array_api_tests/test_array_object.py, tests/cupy_tests/array_api_tests/test_creation_functions.py
=> Apply upstream patch to `cupy.array_api` 

docs/source/upgrade.rst
=> [v10] Update labels of Docs column

.pfnci/flexci_notify.py, .pfnci/linux/main-flexci.sh
The current message was too verbose...
=> Fix CI result notification message format

.pfnci/linux/tests/array-api.Dockerfile, .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
=> Fix cuSPARSELt version in manually crafted Dockerfiles

docs/source/upgrade.rst
=> Add link to compatibility matrix

install/cupy_builder/cupy_setup_build.py
fixes #3885
- change ```from os import path``` to ```os.path```
=> delete from os import path

.pfnci/generate.py, .pfnci/linux/tests/cuda-example.Dockerfile, .pfnci/linux/tests/cuda-head.Dockerfile, .pfnci/linux/tests/cuda-slow.Dockerfile, .pfnci/linux/tests/cuda102.Dockerfile, .pfnci/linux/tests/cuda102.multi.Dockerfile, .pfnci/linux/tests/cuda110.Dockerfile, .pfnci/linux/tests/cuda110.multi.Dockerfile, .pfnci/linux/tests/cuda111.Dockerfile, .pfnci/linux/tests/cuda111.multi.Dockerfile, .pfnci/linux/tests/cuda112.Dockerfile, .pfnci/linux/tests/cuda112.multi.Dockerfile, .pfnci/linux/tests/cuda113.Dockerfile, .pfnci/linux/tests/cuda113.multi.Dockerfile, .pfnci/linux/tests/cuda114.Dockerfile, .pfnci/linux/tests/cuda114.multi.Dockerfile, .pfnci/linux/tests/rocm-4-0.Dockerfile, .pfnci/linux/tests/rocm-4-2.Dockerfile, .pfnci/linux/tests/rocm-4-3.Dockerfile
Fixes the issue that `cuda-head` test did not install pre-releases correctly (`=0a0` file was created...).
=> CI: Fix unquoted specifiers

cupy/linalg/_decomposition.py, tests/cupy_tests/linalg_tests/test_decomposition.py
=> Fix empty Cholesky

docs/source/upgrade.rst
* Mention baseline API update change
* Make list of API changes a bullet list, following v9 style
=> Update upgrade guide

cupy/_core/_gufuncs.py, cupy/_core/_routines_linalg.pyx, cupy/linalg/_product.py, tests/cupy_tests/math_tests/test_matmul.py
=> Make `matmul` support ufunc kwargs

cupy/_core/_routines_linalg.pyx, tests/cupy_tests/math_tests/test_matmul.py
=> Fix overlapping `out` in `matmul` and `(tensor)dot`

cupy/cuda/compiler.py, tests/cupy_tests/cuda_tests/test_compiler.py
=> Fix `compile_with_cache` returning None

cupyx/scipy/fft/__init__.py, cupyx/scipy/fft/_fft.py, cupyx/scipy/linalg/__init__.py, cupyx/scipy/linalg/special_matrices.py, cupyx/scipy/sparse/linalg/_norm.py
fixes #6070 
- ```__all__``` is not used. Then delete it.
=> Remove `__all__` from `cupyx/scipy/*`

cupyx/scipy/ndimage/_filters_core.py, cupyx/scipy/ndimage/_util.py, tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
=> Fix overloading ambiguity in ndimage filters

cupy/_core/_gufuncs.py, cupy/_core/_routines_linalg.pyx, cupy/linalg/_product.py, tests/cupy_tests/math_tests/test_matmul.py
=> [backport] Remove memory copy in matmul

docs/source/reference/math.rst, docs/source/reference/ufunc.rst
Fixes #6017 by updating the docs as discussed in the "issue conversations"
=> Add `cupy.positive` in API Reference

.gitignore, cupy/cublas.py, cupy_backends/cuda/libs/cublas.pxd, cupy_backends/cuda/libs/cublas.pyx, cupy_backends/hip/cupy_hipblas.h, cupy_backends/stub/cupy_cublas.h, tests/cupy_tests/test_cublas.py
Added BLAS 2 and 3 functions (SYRK and SBMV) for real and complex types
=> Cublas extension

cupyx/scipy/ndimage/measurements.py
Hi all,
I'm just suggesting to adapt a warning message. It took me a moment to understand it. I hope the updated version is more clear.
Best,
Robert
=> more clear warning message

cupyx/scipy/sparse/linalg/_eigen.py
=> Fix `eigsh` doc

cupy/__init__.py, cupy/_creation/matrix.py, docs/source/reference/creation.rst, tests/cupy_tests/creation_tests/test_matrix.py
Ref: #6078 
Hi team,
I have implemented `vander` API.
cc @kmaehashi 
Thanks!
=> Add `cupy.vander` API.

cupy/_core/core.pyx, tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
=> Support comparison with more objects

tests/cupy_tests/math_tests/test_misc.py, tests/cupy_tests/statistics_tests/test_correlation.py
=> Remove XFAIL for XPASS tests on ROCm

cupy/cuda/memory.pyx, cupy_backends/cuda/api/runtime.pyx, cupy_backends/cuda/libs/cublas.pyx, cupy_backends/cuda/libs/cudnn.pyx, cupy_backends/cuda/libs/curand.pyx, cupy_backends/cuda/libs/cusolver.pyx, cupy_backends/cuda/libs/cusparse.pyx
The checks where called unconditionally and caused version checks to blow up
Closes #6295
=> Fix stream capture in ROCm

.github/ISSUE_TEMPLATE/documentation.yml
Hi, Team!
The PR Fixes: https://github.com/cupy/cupy/issues/6293#issue-1094716054
cc: @kmaehashi @leofang @toslunar
=> Add doc issue template

cupy/__init__.py, cupy/_math/misc.py, docs/source/reference/math.rst, tests/cupy_tests/math_tests/test_misc.py, tests/cupy_tests/test_cusparse.py, tests/cupyx_tests/fallback_mode_tests/test_notifications.py
Hi, Team!
The PR **aims** to add `cupy.fabs` API. Follows https://github.com/cupy/cupy/issues/6078#issue-1051191869.
I will be happy to know and learn from your viewpoints. Thanks!
cc: @kmaehashi
=> Add `cupy.fabs` API.

cupy/__init__.py, cupy/_manipulation/join.py, docs/source/reference/manipulation.rst, tests/cupy_tests/manipulation_tests/test_join.py
As per title.
Ref: https://github.com/cupy/cupy/issues/6078
=> Add `cupy.row_stack` API.

.pfnci/config.pbtxt, .pfnci/config.tags.json
Migrate slow tests from Jenkins to FlexCI.
=> CI: Add `cuda-slow` test in FlexCI

cupyx/tools/install_library.py
=> Install lib directory on Windows in cuDNN installer

.pfnci/flexci_notify.py
Scheduled test has an empty sub description.
=> Avoid empty notification message for scheduled tests

cupyx/jit/__init__.py, cupyx/jit/_compile.py, docs/source/user_guide/kernel.rst
Backport of #6329 by @kmaehashi
=> [backport] Fix JIT to support notebook environment

tests/cupyx_tests/tools_tests/test_install_library.py
Parameterize to avoid timeout in slow tests.
=> Parameterize library installer tests

cupy/__init__.py, cupy/_logic/truth.py, docs/source/reference/logic.rst, tests/cupy_tests/logic_tests/test_truth.py
Hi, Team!!
The PR **aims** to add `cupy.union1d` API. It follows #6078.
I would love to get your feedback.
Thanks! :)
=> Add `cupy.union1d` API.

install/cupy_builder/_command.py, install/cupy_builder/_compiler.py, install/cupy_builder/cupy_setup_build.py, install/cupy_builder/install_build.py, install/cupy_builder/install_utils.py, install/mypy.ini
Adds mypy configuration at `installer/mypy.ini`.
=> Fix type annotations in installer

cupy/_core/core.pyx, cupy/typing/__init__.py, cupy/typing/_generic_alias.py, tests/cupy_tests/test_typing.py
=> Add `cupy.typing`

.github/workflows/pretest.yml
Reduces pre-review test time for 3 minutes.
=> CI: build docs in parallel

cupy/_math/misc.py, tests/cupy_tests/math_tests/test_misc.py
=> Fix `cupy.nan_to_num`

.github/workflows/pretest.yml, .gitignore, cupy/__init__.py, cupy/_core/__init__.py, cupy/_logic/comparison.py, cupy/_math/floating.py, cupy/array_api/_array_object.py, cupy/array_api/_constants.py, cupy/array_api/_creation_functions.py, cupy/array_api/_data_type_functions.py, cupy/array_api/_sorting_functions.py, cupy/array_api/_typing.py, cupy/array_api/linalg.py, cupy/cuda/compiler.py, cupy/fft/config.py, cupy/testing/_helper.py, cupy/testing/_loops.py, cupy/testing/_pytest_impl.py, cupy/typing/_generic_alias.py, cupyx/jit/_cuda_typerules.py, cupyx/scipy/fft/_fft.py, cupyx/scipy/fft/_helper.py, cupyx/scipy/sparse/base.py, cupyx/scipy/sparse/csc.py, cupyx/scipy/sparse/sputils.py, cupyx/tools/_hipsparse_stub_mapper.py, setup.cfg, setup.py
Introduces mypy 0.931 for static type checks.
=> First step of `mypy` introduction

.pfnci/coverage.rst, .pfnci/linux/tests/cuda114.Dockerfile, .pfnci/linux/tests/cuda114.multi.Dockerfile, .pfnci/matrix.yaml
Backport of #6448 by @kmaehashi
=> [backport] CI: fix NCCL 2.10 unit test not covered

cupy/__init__.py, cupy/_logic/truth.py, docs/source/reference/set.rst, tests/cupy_tests/logic_tests/test_truth.py
Hi,
The PR aims to add `cupy.intersect1d` API. It follows #6078
Looking forward to your viewpoints :)
Thanks!
=> Add `cupy.intersect1d` API.

cupy/_functional/vectorize.py
Fixing the copy paste bug mentioned in: "#6485"
=> Fix error message in `vectorize`

cupy/linalg/_einsum.py, tests/cupy_tests/linalg_tests/test_einsum.py
Follow numpy/numpy#16080 to resolve #6495.
=> Make einsum accept subscripts in numpy int

cupy/__init__.py, cupy/_math/misc.py, docs/source/reference/math.rst, tests/cupy_tests/math_tests/test_misc.py
Linked Issue: #6078 
I am somewhat skeptical about the tests I have written(specifically about the format).
=> Add `cupy.real_if_close` API

cupyx/scipy/linalg/__init__.py, cupyx/scipy/linalg/_special_matrices.py, cupyx/scipy/linalg/_uarray.py, tests/cupyx_tests/scipy_tests/linalg_tests/test_uarray.py
=> Minor fixes on uarray backend support

cupyx/scipy/sparse/_coo.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
Close https://github.com/cupy/cupy/issues/6494
=> Fix coo_matrix.diagonal

.pfnci/config.pbtxt, .pfnci/config.tags.json, .pfnci/matrix.yaml, .pfnci/windows/_flexci.ps1, .pfnci/windows/test.ps1
To be tested:
https://ci.preferred.jp/cupy.win.cuda110/
https://ci.preferred.jp/cupy.win.cuda111/
https://ci.preferred.jp/cupy.win.cuda112/
https://ci.preferred.jp/cupy.win.cuda113/
https://ci.preferred.jp/cupy.win.cuda114/
https://ci.preferred.jp/cupy.win.cuda115/
Testing:
https://ci.preferred.jp/cupy.win.cuda116/96388/
~edit: Seems we need to update scripts to use VS 2017+.~
=> Add FlexCI projects for Windows

docs/source/contribution.rst
=> Shortened the contributing guidelines.

README.md, docs/source/install.rst
=> [backport] Fix documents for CUDA 11.6

cupy/_core/_kernel.pxd, cupy/_core/_kernel.pyx, cupy/_core/_reduction.pyx, tests/cupy_tests/core_tests/test_ndarray_ufunc.py
=> Fix `out` args parser of ufunc

cupy/_core/core.pyx, tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
=> Fix `cupy.fill` to properly take zero-dim `cupy.ndarray`

cupy/array_api/_array_object.py, cupy/array_api/_constants.py, cupy/array_api/_creation_functions.py, cupy/array_api/_data_type_functions.py, cupy/array_api/_typing.py, cupy/array_api/linalg.py
=> mypy: array_api

tests/cupy_tests/array_api_tests/test_set_functions.py
https://ci.preferred.jp/cupy.linux.cuda110/96900/
=> Fix flaky test_inverse_indices_shape

.pfnci/coverage.rst
Due to pull-request merge order the matrix was not up-to-date.
=> [v10] CI: regenerate matrix

cupy/_core/_memory_range.pyx, tests/cupy_tests/misc_tests/test_memory_ranges.py
=> Fix `may_share_memory` algorithm

tests/cupy_tests/array_api_tests/test_set_functions.py
=> [backport] Fix flaky test_inverse_indices_shape

.pfnci/config.pbtxt, .pfnci/config.tags.json, .pfnci/coverage.rst, .pfnci/generate.py, .pfnci/linux/main-flexci.sh, .pfnci/linux/run.sh, .pfnci/linux/tests/actions/benchmark.sh, .pfnci/linux/tests/benchmark.Dockerfile, .pfnci/linux/tests/benchmark.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml
Adds a job that is triggered with `/test benchmark` and compares the current PR with the master branch.
Useful to detect performance regressions in doubtful PRs
=> Run cupy-benchmark on CI

README.md, docs/source/install.rst
=> Documentation update for ROCm 5.0

.pfnci/schema.yaml, cupy/_core/include/cupy/carray.cuh, cupyx/scipy/ndimage/_filters_core.py, cupyx/scipy/ndimage/_filters_generic.py, cupyx/scipy/sparse/csc.py, examples/custom_struct/complex_struct.py, tests/cupy_tests/core_tests/test_function.py, tests/cupy_tests/core_tests/test_ndarray.py, tests/cupy_tests/core_tests/test_raw.py, tests/cupy_tests/cuda_tests/test_memory.py, tests/cupy_tests/functional_tests/test_vectorize.py, tests/cupy_tests/linalg_tests/test_product.py, tests/cupyx_tests/fallback_mode_tests/test_fallback.py, tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
=> [backport] Fix for supporting ROCm 5.0

README.md, docs/source/install.rst
=> [backport] Documentation update for ROCm 5.0

README.md, docs/source/install.rst
=> Add `--pre` option to instructions installing pre-releases

cupy_backends/cuda/api/_runtime_enum.pxd
=> Add missing `cudaDevAttrMemoryPoolsSupported` to hip

cupyx/jit/_interface.py
See https://github.com/cupy/cupy/pull/6620#discussion_r845946400.
=> JIT: fix access to cached codes

cupy/lib/_routines_poly.py, tests/cupy_tests/lib_tests/test_polynomial.py
=> Fix int64 overflow in `cupy.polyval`

cupyx/scipy/sparse/_compressed.py
Fixes the wrong message and warning class (found in #6667)
=> Improve warning message in sparse

cupyx/jit/cg.py, tests/cupyx_tests/jit_tests/test_cooperative_groups.py
https://github.com/cupy/cupy/pull/6670#issuecomment-1106083778
=> JIT: Disable `memcpy_async` on CUDA 11.0

.github/workflows/flexci_dispatcher.py
Fix issue probably-meant-fstring found at https://codereview.doctor
=> Fix missing f prefix on f-strings fix

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump version in Dockerfile for v10.4.0

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump version in Dockerfile for v11.0.0b2

.github/workflows/pretest.yml, install/cupy_builder/_command.py, install/cupy_builder/_compiler.py, setup.py
v10 needs a separate fix: #6711
=> Bump pinned mypy version

.github/workflows/pretest.yml, install/cupy_builder/_command.py, install/cupy_builder/_compiler.py, setup.py
This is a cherry-pick of 5e7bfd8f3 (#6710).
Fixes pretest failure found in #6709.
=> [v10] Pin mypy version in setup.py

cupy/_functional/vectorize.py, cupyx/jit/_interface.py
https://github.com/cupy/cupy/pull/6668#discussion_r854845340
=> JIT: Use C++14

docs/source/conf.py, docs/source/reference/array_api.rst, docs/source/user_guide/difference.rst
=> [backport] Minor improvement on the array API  docs

cupy/__init__.py, cupy/_math/misc.py, cupy/lib/_polynomial.pyx, cupy/lib/_routines_poly.py, docs/source/reference/polynomials.rst, tests/cupy_tests/lib_tests/test_polynomial.py
Takeover of #3547. Close #3547.
=> Add `cupy.poly`

cupyx/scipy/sparse/_base.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
This PR recovers CI failures caused by a scipy==1.8.1 bugfix.
https://github.com/scipy/scipy/issues/15258
https://github.com/scipy/scipy/pull/16035
=> Follow scipy==1.8.1 sparse dot bugfix

cupy/fft/_cache.pyx
=> Fix memory leak in the FFT plan cache during multi-threading

tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Following up #6524. A test of LOBPCG may get wierd eigenvalues on ROCm 5.0.
=> Xfail a test of LOBPCG on ROCm 5.0+

.pfnci/linux/main-flexci.sh
=> Fix GPG key issue in FlexCI base image

cupyx/distributed/_nccl_comm.py, tests/cupyx_tests/distributed_tests/comm_runner.py, tests/cupyx_tests/distributed_tests/test_comm.py
=> Add sparse `reduce`

cupyx/distributed/_nccl_comm.py, tests/cupyx_tests/distributed_tests/comm_runner.py, tests/cupyx_tests/distributed_tests/test_comm.py
=> Add sparse `all_reduce` and minor fixes

cupy/lib/_routines_poly.py, tests/cupy_tests/lib_tests/test_polynomial.py
Enhance test coverage of type combinations
=> Fix polynomial tests

.pfnci/linux/main-flexci-prep.sh
Test: https://ci.preferred.jp/cupy.prep-linux/103428/
=> CI: Fix prep script to show build failure details

cupy_backends/cuda/libs/nvtx.pyx
Some users working with CuPy did not understand NVTX ranges, so I tried to improve the docs with a small example and a sentence about using Nsight Systems. Instead of complaining about the docs I thought I would spend a minute and contribute. 
I don't know if I got the formatting correct for the "Example:" code in the docstring.
=> Improved NVTX documentation

cupy/lib/_routines_poly.py, cupyx/scipy/special/__init__.py
- master
```
__pow__             :    CPU:17129.355 us   +/-742.564 (min:15711.574 / max:18453.500) us     GPU-0:17138.483 us   +/-742.922 (min:15719.424 / max:18463.743) us
```
- This PR
```
__pow__             :    CPU:  218.919 us   +/- 5.220 (min:  213.281 / max:  230.438) us     GPU-0:  227.021 us   +/- 4.782 (min:  221.184 / max:  236.544) us
```
- benchmark
```py
import cupy
x = testing.shaped_random((5,), xp=cupy, dtype='f', seed=0, scale=0.4)
x = cupy.poly1d(x)
n = 5000
perf = benchmark(cupy.poly1d.__pow__, (x, n), n_repeat=10)
print(perf)
```
=> Use fast convolution algorithm in `cupy.poly1d.__pow__`

.pfnci/linux/tests/array-api.Dockerfile
Backport of #6508 by @kmaehashi
=> [backport] Fix Dockerfile broken for array-api tests

cupyx/jit/_cuda_types.py
```
$ mypy cupy cupyx cupy_backends --enable-error-code attr-defined | grep cupyx/jit
```
=> Add type annotation in `_cuda_types.py`

cupyx/distributed/_nccl_comm.py, tests/cupyx_tests/distributed_tests/comm_runner.py, tests/cupyx_tests/distributed_tests/test_comm.py
=> Add sparse `gather` `scatter` `all_gather`

cupyx/scipy/special/__init__.py, cupyx/scipy/special/_stats_distributions.py, docs/source/reference/scipy_special.rst, tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
Hi,
The PR adds `cupyx.scipy.special.log_ndtr`. Thanks! :)
=> [special] Add `cupyx.scipy.special.log_ndtr`

cupyx/jit/_cuda_typerules.py, cupyx/jit/_internal_types.py
=> Add type annotation to JIT internal types

.pfnci/config.pbtxt, .pfnci/config.tags.json, .pfnci/coverage.rst, .pfnci/linux/tests/cuda117.Dockerfile, .pfnci/linux/tests/cuda117.multi.Dockerfile, .pfnci/linux/tests/cuda117.multi.sh, .pfnci/linux/tests/cuda117.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml, cupy/_core/include/cupy/_cuda/README.md, cupy/_core/include/cupy/_cuda/cuda-11/cuda_fp16.h, cupy/_core/include/cupy/_cuda/cuda-11/cuda_fp16.hpp, cupy/_environment.py, cupyx/tools/install_library.py, install/universal_pkg/setup.py
=> [backport] Support CUDA 11.7

.pfnci/coverage.rst, .pfnci/linux/main-flexci.sh, .pfnci/linux/tests/cuda-head.Dockerfile, .pfnci/linux/update-cuda-driver.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml
Backport of #6804 by @kmaehashi
=> [backport] Fix CI Docker image build failing in head test

.pfnci/linux/main-flexci.sh, .pfnci/linux/run.sh, .pfnci/linux/tests/cuda-rapids.Dockerfile, .pfnci/linux/tests/cuda-rapids.sh
=> Tiny clean up in CI script

cupy/_core/_routines_indexing.pyx, cupy/_core/_routines_manipulation.pyx, cupy/_core/core.pyx, cupy/_core/internal.pxd, cupy/_core/internal.pyx, cupyx/jit/_cuda_typerules.py, tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py, tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py, tests/cupy_tests/creation_tests/test_basic.py, tests/cupy_tests/functional_tests/test_vectorize.py
=> Fix for NumPy 1.23

.github/workflows/docker.yml
=> Fix docker workflow to push to latest image

cupy/__init__.py, cupy/_math/misc.py, docs/source/reference/math.rst, tests/cupy_tests/math_tests/test_misc.py
=> add `cupy.heaviside` api.

.pfnci/coverage.rst, .pfnci/linux/tests/rocm-5-1.Dockerfile, .pfnci/linux/tests/rocm-5-1.sh, .pfnci/linux/tests/rocm-5-2.Dockerfile, .pfnci/linux/tests/rocm-5-2.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml
=> CI: Add ROCm 5.1 and 5.2

cupy/cuda/device.pyx
Fixing confusing function name (#6865).
=> Fix function names

.pfnci/config.pbtxt, .pfnci/windows/_flexci.ps1
=> Add config for `cupy.win.cuda117`

cupy/_core/_routines_math.pyx
=> Fix real and imag in subclass

README.md, docs/source/install.rst
**MERGE THIS JUST BEFORE v11 RELEASE.**
Depends on #6888.
=> Update install instructions on README

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump version for Docker image v11.0.0

README.md, docs/source/install.rst
=> [v11] Update install instructions on README

docs/source/upgrade.rst, docs/source/user_guide/interoperability.rst
=> Expand breaking change & best practice on device management

cupy/_core/include/cupy/complex/complex.h
=> Suppress nvcc warning

cupy/array_api/_set_functions.py, cupy/array_api/linalg.py
Applied patches from upstream:
- numpy/numpy#21666
- numpy/numpy#21084
=> Update `cupy.array_api` (cont'd)

cupy/_core/_codeblock.py, cupyx/jit/_builtin_funcs.py, cupyx/jit/_compile.py, cupyx/jit/_cuda_typerules.py, cupyx/jit/_cuda_types.py, cupyx/jit/_internal_types.py
=> JIT: Add type annotation in _compile.py

cupyx/scipy/special/__init__.py, cupyx/scipy/special/_basic.py, docs/source/reference/scipy_special.rst, tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
Made a small change to add [``scipy.special.cosm1``](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.cosm1.html) to cupyx.
Would appreciate if you can take a look @leofang @emcastillo @kmaehashi 
#6324
=> Added ``scipy.special.cosm1`` to cupyx

.github/workflows/pretest-rocm-test.sh
https://github.com/cupy/cupy/pull/6992#discussion_r946335002
=> Revert comment fix

cupyx/jit/_interface.py, tests/cupyx_tests/jit_tests/test_raw.py
=> Fix JIT for scalar argument

cupy/random/_generator.py, tests/cupy_tests/random_tests/test_generator.py
See https://github.com/cupy/cupy/issues/1644
=> Make sure weibull distribution support ndarrays

cupy/_core/_kernel.pyx, cupy/_ufunc_method/__init__.py, cupy/_ufunc_method/outer.py, tests/cupy_tests/core_tests/test_ufunc_methods.py
Part of https://github.com/cupy/cupy/issues/6866.
https://cupy--7049.org.readthedocs.build/en/7049/reference/generated/cupy.ufunc.html
=> Add `ufunc.outer`

cupy/_core/_routines_indexing.pyx
Ready for `cupy.ufunc.at` support.
=> Cosmetic change in _routine_indexing.pyx

.github/workflows/docker.yml
To push #7089 to v12.0.0a2 tag, allow workflow to be manually triggered.
=> Support force-overwriting Docker image via workflow

cupy/random/_generator.py, tests/cupy_tests/random_tests/test_generator.py
=> Allow randint to support array bounds

cupyx/distributed/_store.py
=> Don't use `__del__` in `TCPStore`

docs/source/reference/ufunc.rst
Add recently-added ufuncs missing from the list.
=> Docs: Add missing functions

docs/source/reference/ufunc.rst
=> Docs: ufunc methods

cupy/_core/_kernel.pyx, tests/cupy_tests/core_tests/test_ufunc_methods.py
=> Add `ufunc.reduce` and `ufunc.accumulate`

cupy/_core/_scalar.pxd, cupy/_core/_scalar.pyx, cupy/_core/core.pyx, cupy/_core/fusion.pyx, tests/cupy_tests/core_tests/fusion_tests/test_misc.py
=> Fix compile error from `inf`/`nan` in cupy.fuse

cupy/_core/_kernel.pyx, cupy/_core/_routines_indexing.pxd, cupy/_core/_routines_indexing.pyx, cupy/_core/core.pxd, cupy/_core/core.pyx, docs/source/reference/ufunc.rst, tests/cupy_tests/core_tests/test_ufunc_methods.py
Close https://github.com/cupy/cupy/issues/7082.
=> Add `cupy.add.reduceat`

cupy/__init__.py, cupy/_core/core.pyx, docs/source/reference/dtype.rst, tests/cupy_tests/core_tests/test_core.py
=> Implement `cupy.min_scalar_type`

cupyx/scipy/sparse/_compressed.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
Follows https://github.com/scipy/scipy/pull/16657.
=> Fix indexing sparse matrix with empty index arguments

cupyx/tools/install_library.py
=> Support NCCL 2.15

cupyx/jit/_compile.py, tests/cupy_tests/functional_tests/test_vectorize.py
=> JIT: Fix compile error of minmax function

cupy/cusparse.py
=> Fix a typo

cupyx/profiler/_time.py
Closes #7165.
This PR also removes unnecessary event creation.
=> Improve benchmark documentation

cupy/_sorting/sort.py, tests/cupy_tests/sorting_tests/test_sort.py
https://github.com/cupy/cupy/pull/7159/commits/6050a35330271df638bd42fcb6dc2ad936668e39 found this bug.
=> Fix 1-dim lexsort

cupy/linalg/_einsum.py
=> Use list(kwargs) instead of list(kwargs.keys)

cupyx/scipy/interpolate/__init__.py, docs/source/reference/scipy_interpolate.rst
This is a minor change missing from https://github.com/cupy/cupy/pull/7086
=> Expose splder and splantider

cupyx/scipy/interpolate/__init__.py, cupyx/scipy/interpolate/_rbfinterp.py, docs/source/reference/scipy_interpolate.rst, tests/cupyx_tests/scipy_tests/interpolate_tests/test_rbfinterp.py
Add the RBFInterpolator, as per gh-7186.
=> Add `cupyx.scipy.interpolate.RBFInterpolator`

cupyx/scipy/interpolate/_rbfinterp.py
Follows up #7190, which causes CI failure in cupy.linux.cuda111 and cupy.linux.cuda111.multi
=> Remove scipy import

docs/source/install.rst
=> Fix v11 installation doc

docs/source/install.rst
=> Revert "Fix v11 installation doc"

cupyx/scipy/sparse/_util.py
https://ci.preferred.jp/cupy.linux.cuda11x-cuda-python/117857/
=> Fix interpreting Sparse init arguments

cupyx/scipy/interpolate/__init__.py, cupyx/scipy/interpolate/_bspline.py, cupyx/scipy/interpolate/_bspline2.py, docs/source/reference/scipy_interpolate.rst, tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py
gh-7186
Based off gh-7086, will rebase on master when that one is done.
<s>This is very WIP at the moment</s>.  This is ready for a first review.
=> add cupyx.scipy.interpolate.make_interp_spline

cupyx/jit/thrust.py, tests/cupyx_tests/jit_tests/test_thrust.py
Previous: https://github.com/cupy/cupy/pull/7139
=> JIT: Enhance thrust functions coverage

cupy/_core/core.pyx, cupy/_core/include/cupy/_cuda/README.md, cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.h, cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.hpp, cupy/_environment.py
Part of #7232. Add FP16 headers and dup package detection.
=> Extra fixes for CUDA 12.0

cupyx/scipy/interpolate/_bspline2.py, tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py, tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py
This is branched off gh-7195, will rebase after it is in. Relevant commits start from 64c80c417cc490f20e1c9e0bff22bb7552e200bf
=> Implement `make_interp_spline(..., bc_type="periodic")`

cupyx/scipy/interpolate/__init__.py, cupyx/scipy/interpolate/_cubic.py, docs/source/reference/scipy_interpolate.rst, tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py
=> Add CubicHermiteSpline to cupyx.scipy.interpolate

setup.cfg
https://github.com/cupy/cupy/pull/7262#issuecomment-1371737070
=> Filter SQLAlchemy's warning on which optuna depends in test

cupy/typing/_generic_alias.py, cupyx/scipy/interpolate/_bspline2.py, tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py, tests/cupyx_tests/scipy_tests/interpolate_tests/test_ppoly.py
=> Fix CI failures related to `cupyx.scipy.interpolate`

docs/source/user_guide/cuda_api.rst, docs/source/user_guide/interoperability.rst
I was asked for this several times so I guess it's time to document it :)
=> Doc: Add interop example using raw pointers

tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
=> [v11] Fix tests for NumPy 1.24 (c.f. #7286)

.pfnci/config.pbtxt, .pfnci/config.tags.json, .pfnci/coverage.rst, .pfnci/linux/tests/cuda120.Dockerfile, .pfnci/linux/tests/cuda120.multi.Dockerfile, .pfnci/linux/tests/cuda120.multi.sh, .pfnci/linux/tests/cuda120.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml, .pfnci/windows/_flexci.ps1, cupyx/tools/install_library.py, install/universal_pkg/setup.py, tests/cupyx_tests/linalg_tests/test_solve.py, tests/install_tests/test_build.py
cuda120 tests:
* https://ci.preferred.jp/cupy.linux.cuda120/120643/
* https://ci.preferred.jp/cupy.linux.cuda120.multi/120644/
* https://ci.preferred.jp/cupy.win.cuda120/120645/
=> Add CI for CUDA 12.0

README.md, docs/source/install.rst
=> Doc: Bump supported environments (CUDA 12 / cuDNN 8.7 / NCCL 2.16)

.pfnci/windows/_flexci.ps1, .pfnci/windows/test.ps1
https://ci.preferred.jp/cupy.win.cuda118/120849/
=> CI: Use NVTX1 in FlexCI image

install/universal_pkg/setup.py
Merge after ~https://github.com/cupy/cupy-release-tools/pull/322~ done
=> Add `cupy-cuda12x` to `cupy-wheel`

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump Dockerfile version to v11.5.0

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump Dockerfile version to v12.0.0b3

cupyx/scipy/interpolate/__init__.py, cupyx/scipy/interpolate/_bspline2.py, cupyx/scipy/interpolate/_cubic.py, docs/source/reference/scipy_interpolate.rst, tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py
=> Add Akima1DInterpolator to cupyx.scipy.interpolate

docs/source/user_guide/difference.rst
=> Doc: add docs for contiguity policy

cupyx/scipy/sparse/linalg/_eigen.py
=> Imporves stability of orthogonization step in ```cupyx.scipy.sparse.eigsh```

setup.cfg
Refs #7364. This is for backport.
=> Filter SQLAlchemy 2.0 warnings raised from Optuna v2

cupyx/scipy/interpolate/_rgi.py, tests/cupyx_tests/scipy_tests/interpolate_tests/test_rgi.py
=> Enable spline methods on RegularGridInterpolator

cupy/typing/_generic_alias.py
https://github.com/cupy/cupy/pull/7264#issuecomment-1411153663
=> Do not test NumPy version for private APIs

cupy/typing/_generic_alias.py
Backport of #7368 by @kmaehashi
Conflict resolved manually.
=> [backport] Do not test NumPy version for private APIs

.pfnci/config.tags.json, .pfnci/matrix.yaml
Follows-up https://github.com/cupy/cupy/pull/7299
=> Add CI for CUDA 12.0 on Windows

cupy/_core/_kernel.pyx, cupy/_core/_reduction.pxd, cupy/_core/_reduction.pyx, tests/cupy_tests/core_tests/test_reduction.py, tests/cupy_tests/core_tests/test_userkernel.py
=> Add `cached_code` to `ElementwiseKernel` and `ReductionKernel`

cupyx/scipy/interpolate/__init__.py, cupyx/scipy/interpolate/_interpolate.py, docs/source/reference/scipy_interpolate.rst, tests/cupyx_tests/scipy_tests/interpolate_tests/test_ppoly.py
=> Add BPoly to cupyx.scipy.interpolate module

tests/cupy_tests/sorting_tests/test_search.py
https://docs.cupy.dev/en/stable/user_guide/difference.html#cast-behavior-from-float-to-integer
=> Avoid casting nan value to integer type in `nanargmin/max` tests

tests/cupy_tests/core_tests/test_ndarray_unary_op.py, tests/cupy_tests/creation_tests/test_ranges.py, tests/cupy_tests/functional_tests/test_piecewise.py, tests/cupy_tests/indexing_tests/test_indexing.py, tests/cupy_tests/logic_tests/test_comparison.py, tests/cupy_tests/manipulation_tests/test_add_remove.py, tests/cupy_tests/polynomial_tests/test_polyutils.py, tests/cupy_tests/testing_tests/test_loops.py, tests/cupyx_tests/scipy_tests/special_tests/test_log_softmax.py, tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py
=> Avoid int8 overflow in some tests

tests/cupy_tests/functional_tests/test_vectorize.py
=> Fix int8 overflow in vectorize tests

tests/cupy_tests/core_tests/test_ndarray_unary_op.py, tests/cupy_tests/creation_tests/test_ranges.py, tests/cupy_tests/functional_tests/test_piecewise.py, tests/cupy_tests/indexing_tests/test_indexing.py, tests/cupy_tests/logic_tests/test_comparison.py, tests/cupy_tests/manipulation_tests/test_add_remove.py, tests/cupy_tests/polynomial_tests/test_polyutils.py, tests/cupy_tests/testing_tests/test_loops.py, tests/cupyx_tests/scipy_tests/special_tests/test_log_softmax.py
=> [backport] Avoid int8 overflow in some tests

tests/cupy_tests/math_tests/test_sumprod.py
=> Fix sumprod test to avoid uint overflow

cupy/_core/_dtype.pxd, cupy/_core/_dtype.pyx, cupy/_core/_fusion_trace.pyx, cupy/_core/_gufuncs.py, cupy/_core/_kernel.pyx, cupy/_core/_routines_manipulation.pyx, cupy/_core/fusion.pyx, cupyx/jit/_compile.py, tests/cupy_tests/manipulation_tests/test_join.py, tests/cupy_tests/math_tests/test_arithmetic.py
This is mainly from me trying to understand the machinery better.  I had larger changes, which continuously shrank again, thus i am not sure that `_raise_if_invalid_cast` is worthwhile (and I am very happy to drop it!  Or most of the rest for that matter.).
=> Small fixes and refactor of casting related things

tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
=> [backport] Fix ndarray.fill to raise ComplexWarning

docs/source/conf.py
=> Tentatively disable cuquantum intersphinx

docs/source/conf.py
=> Revert "Tentatively disable cuquantum intersphinx"

docs/source/conf.py
=> Revert "[backport] Tentatively disable cuquantum intersphinx"

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump Dockerfile version to v11.6.0

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump Dockerfile version to v12.0.0rc1

.github/workflows/backport.yml, .github/workflows/flexci.yml, .pfnci/coverage.rst, .pfnci/linux/tests/actions/benchmark.sh, .pfnci/matrix.yaml, .pre-commit-config.yaml, README.md, docs/source/conf.py, docs/source/contribution.rst, docs/source/user_guide/kernel.rst
Backport of #7448 by @kmaehashi
=> [backport] Update branch name from `master` to `main`

docs/source/_comparison_generator.py
Preview:
https://cupy--7433.org.readthedocs.build/en/7433/reference/comparison.html#interpolation
=> Add comparison table for `scipy.interpolate` module

docs/source/install.rst
~Merge after #7473~ (merged)
Ref #7441, #7378, #7471, #7386
=> Update list of supported libraries

.github/workflows/auto-cc.yml, .github/workflows/backport.yml, .github/workflows/docker.yml, .github/workflows/flexci.yml
Remove deprecation warnings.
c.f. https://github.com/cupy/cupy-release-tools/pull/339
=> Bump platform versions used in actions

install/cupy_builder/_compiler.py
I'll check how this changes the wheel size. Closes #4874.
main: https://github.com/kmaehashi/cupy-aarch64-wheel/actions/runs/4560418924
main with this PR: https://github.com/kmaehashi/cupy-aarch64-wheel/actions/runs/4560219377
=> Use `-Xfatbin=-compress-all`

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_iir_utils.py, cupyx/scipy/signal/_signaltools.py, tests/cupyx_tests/scipy_tests/signal_tests/test_iir_utils.py, tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
This PR derives a parallel implementation to compute recursive filters based on https://doi.org/10.1145/3173162.3173168
=> Add lfilter/IIR utilities to cupyx.scipy.signal

cupy/array_api/__init__.py, cupy/array_api/_indexing_functions.py, tests/cupy_tests/array_api_tests/test_indexing_functions.py
fix #7425 
Implementation is analogous to numpy: https://github.com/numpy/numpy/pull/23284
=> add array_api.take function

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_arraytools.py, cupyx/scipy/signal/_savitzky_golay.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_savitzky_golay.py
Add Savitzky-Golay filter from `scipy.signal.savgol_filter`. In fact, the code is the same, modulo minor adjustments to paper over limitations of `cupy.poly1d`.
=> ENH: cupyx/scipy/signal: add savgol_coeffs and savgol_filter

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_iir_utils.py, cupyx/scipy/signal/_signaltools.py, tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Depends on https://github.com/cupy/cupy/pull/7442
=> Add lfiltic and lfilter_zi to cupyx.scipy.signal

tests/cupyx_tests/scipy_tests/interpolate_tests/test_ppoly.py
=> Mark scipy required in a test

cupyx/scipy/special/__init__.py, cupyx/scipy/special/_zetac.py, docs/source/reference/scipy_special.rst, tests/cupyx_tests/scipy_tests/special_tests/test_zetac.py
This PR aims to add `scipy.special.zetac` to cupy . 
Linked Issue : #6324
=> Add `scipy.special.zetac` to cupyx

cupyx/scipy/signal/_splines.py
After benchmarking `symiirorder2` in its original version, several bottlenecks related to the starting conditions computation were found. This PR moves these computations into their own kernels and also tries (optimistically) to reduce the length of the linear search to be done when comparing against the `precision` argument, where it performs better when the cutoff is at the beginning of the array.
=> Improve symiirorder2 performance

.readthedocs.yaml
Ref https://github.com/pfnet/pytorch-pfn-extras/pull/680
=> Fix RTD build failure

.github/workflows/pretest.yml
Improve build speed even when the previous build cache is missing.
=> Reestore GitHub Actions cache with prefix match

cupy/_core/core.pyx, tests/cupy_tests/core_tests/test_ndarray_ufunc.py
=> Dispatch ufunc methods

install/universal_pkg/setup.py
=> Bump version to v13.0.0a1

.pre-commit-config.yaml, cupy/_indexing/indexing.py, cupy/_io/formatting.py, cupy/_manipulation/kind.py, cupy/_math/arithmetic.py, cupy/_math/misc.py, cupy/_statistics/histogram.py, cupy/cublas.py, cupy/random/_generator.py, cupyx/_pinned_array.py, cupyx/jit/cg.py, cupyx/profiler/_time.py, cupyx/scipy/linalg/_decomp_lu.py, cupyx/scipy/sparse/linalg/_lobpcg.py, cupyx/scipy/sparse/linalg/_solve.py, examples/gemm/sgemm.py, tests/cupy_tests/creation_tests/test_ranges.py, tests/cupy_tests/random_tests/test_permutations.py, tests/cupyx_tests/jit_tests/test_raw.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
This fixes the problem when applying static checkers in Python 3.10+.
=> Bump versions of static checkers

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_signaltools.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Depends on https://github.com/cupy/cupy/pull/7552
=> Add sosfiltfilt to cupyx.scipy.signal

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
=> Fix `hilbert` and `hilbert2` test condition

.github/workflows/pr-project.yml
=> Dump event payload for debugging

.github/workflows/pr-project.yml, .github/workflows/pr-updated.yml
Another follow-up for https://github.com/cupy/cupy/pull/7631
Let me self-merge.
cc/ @asi1024
=> Pass pull-request number via artifact

.github/workflows/pr-project.yml
Another follow-up for https://github.com/cupy/cupy/pull/7631
Things were more complicated than I expected... 
Let me self-merge.
cc/ @asi1024
=> Use GitHub App to update org-wide project

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_lti_conversion.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_ltisys.py
=> ENH: cupyx/scipy/signal: add abcd_normalize

.github/workflows/pr-updated.yml
Follow-up https://github.com/cupy/cupy/pull/7631
=> Do not trigger on closed pull-requests and fix to work with `issue_comment` trigger

cupyx/scipy/linalg/__init__.py, cupyx/scipy/linalg/_matfuncs.py, tests/cupyx_tests/scipy_tests/linalg_tests/test_matfuncs.py
This PR adds `scipy.linalg.khatri_rao` to cupy. The function and tests come from scipy.
=> Implement `scipy.linalg.khatri_rao`

cupy_backends/cuda/libs/cusparse.pxd, cupy_backends/cuda/libs/cusparse.pyx
=> Fix type/exception annotations in cuSPARSE binding

.pfnci/config.pbtxt, .pfnci/linux/tests/cuda-rapids.Dockerfile, cupyx/scipy/sparse/csgraph/_traversal.py, tests/cupyx_tests/scipy_tests/sparse_tests/csgraph_tests/test_traversal.py
Backport of #7693 by @jnke2016
=> [backport] Update pylibcugraph weakly connected components call

.pfnci/generate.py, .pfnci/schema.yaml
ref #7548
No CI trigger needed (Pre-review Tests should be sufficient).
=> Allow specifying Docker repository for CI images

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_peak_finding.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_peak_finding.py
=> Add find_peaks, peak_prominences, peak_widths to cupyx.scipy.signal

cupy/_environment.py
=> Improve detection for package installation source on Windows

cupy/_statistics/histogram.py, tests/cupy_tests/statistics_tests/test_histogram.py
=> Temporarily disable CUB histogram

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_signaltools.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
=> ENH: cupyx/scipy/signal: add correlation_lags

.github/workflows/pretest-rocm-test.sh, .github/workflows/pretest.yml
Backport of #7729 by @kmaehashi
=> [backport] CI: remove explicit Cython installation

cupy/cuda/__init__.py, cupy/cuda/compiler.py, tests/cupy_tests/cuda_tests/test_compiler.py
Close https://github.com/cupy/cupy/issues/5297.
=> Remove `cupy.cuda.compile_with_cache`

docs/source/install.rst
Backport of #7753 by @kmaehashi
=> [backport] Add CUDA 12.2 to list of supported CUDA

tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
=> Fix test_sum_duplicates_incompatibility for SciPy 1.11

README.md
Highlighted sections have stopped working due to the recent syntax change:
https://github.com/orgs/community/discussions/16925#discussioncomment-6506860
=> Fix Note highlight sections in README

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_bsplines.py, cupyx/scipy/signal/_iir_utils.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
=> Add 1D signal b-splines to cupyx.scipy.signal

cupyx/scipy/signal/_filter_design.py, cupyx/scipy/signal/_iir_filter_conversions.py, cupyx/scipy/signal/_polyutils.py
Close https://github.com/cupy/cupy/issues/7761.
#7766 had an invalid branch. Let me correctly open a pull request.
=> Note device sync on some cupyx.scipy.signal API documents

docs/source/install.rst
https://github.com/cupy/cupy/pull/7758#issuecomment-1665202197
=> Add notes for CUDA 12.2 on Windows support

docs/source/install.rst
I misunderstood the problem... the issue could not be workaround by installing full CTK.
Also updated #7776.
=> Fix CUDA 12.2 for Windows notes

docs/source/install.rst
Backport of #7781 by @kmaehashi
=> [backport] Fix CUDA 12.2 for Windows notes

.github/workflows/publish.yml
Minor fix to https://github.com/cupy/cupy/pull/7779. Let me self merge.
=> Fix publish workflow: improve deployment preview

.github/workflows/publish.yml
Minor fixes to https://github.com/cupy/cupy/pull/7779. Let me self-merge.
=> Add postcheck step to publish workflow

README.md, docs/source/install.rst
=> Add `-U` to pre-release installation command

docker/rocm/Dockerfile
=> [v12] Fix ROCm Dockerfile not working

.github/workflows/pretest.yml, cupyx/jit/_compile.py
`typing_tests` was skipped... cc/ @asi1024
=> Fix mypy not installed in pre-review test

cupy/_core/core.pyx, tests/cupy_tests/core_tests/test_dlpack.py
=> Make `stream` kwonly argument in `ndarray.__dlpack__`

.github/workflows/pretest.yml, cupy/cuda/__init__.py, cupy/cuda/device.pyx, cupyx/scipy/sparse/_compressed.py, cupyx/scipy/sparse/_coo.py, cupyx/scipy/sparse/_csc.py, cupyx/scipy/sparse/_csr.py, cupyx/scipy/sparse/_index.py, cupyx/scipy/sparse/linalg/_eigen.py, cupyx/scipy/sparse/linalg/_iterative.py, cupyx/scipy/sparse/linalg/_solve.py
This is a part of #7620. Lazy import cuSPARSE. Depends on ~#7843~ (merged & rebased).
=> Lazy import cuSPARSE

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_waveforms.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_waveforms.py
=> Port waveforms from cusignal to cupyx.scipy.signal

.pfnci/windows/_flexci.ps1, .pfnci/windows/test.ps1
https://github.com/cupy/cupy/pull/7851#issuecomment-1712702124
=> CI: Remove path length limitation on Windows CI image

.pfnci/windows/_error_handler.ps1, .pfnci/windows/test.ps1
Fix Windows CI failing even when all tests pass.
=> Fix Windows CI failures

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_spectral.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py
Depends on https://github.com/cupy/cupy/pull/7568
=> Add check_{NOLA, COLA} to cupyx.scipy.signal

.github/workflows/pretest.yml, cupy/fft/_cache.pyx, cupy/fft/_callback.pyx, cupy/fft/_fft.py, cupyx/_runtime.py, cupyx/scipy/fft/_fft.py, cupyx/scipy/fftpack/_fft.py
This is a part of #7620. Lazy import cuFFT. Depends on ~#7847~ (merged and rebased).
=> Lazy import cuFFT

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_bsplines.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py
=> Port gauss_spline from CuSignal

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_wavelets.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_wavelets.py
=> Port wavelets module from cusignal to cupyx.scipy.signal

.github/workflows/pretest.yml, cupy/cuda/__init__.py, cupy/fft/_cache.pyx, cupy/fft/_callback.pyx, cupy/fft/_fft.py, cupy/random/__init__.py, cupy/random/_bit_generator.pyx, cupy/random/_generator.py, cupyx/_runtime.py, cupyx/scipy/fft/_fft.py, cupyx/scipy/fftpack/_fft.py
This is a part of #7620. Lazy import cuRAND. Depends on #7849.
=> Lazy import cuRAND

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_spectral.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py
Depends on https://github.com/cupy/cupy/pull/7564
=> Port stft/istft from CuSignal to cupyx.scipy.signal

tests/cupy_tests/core_tests/test_ndarray_unary_op.py
Close https://github.com/cupy/cupy/issues/7884.
Part of https://github.com/cupy/cupy/issues/7616.
=> Skip test_pos_boolarray if numpy>=1.25

tests/cupy_tests/core_tests/test_ndarray_complex_ops.py, tests/cupy_tests/core_tests/test_ndarray_indexing.py, tests/cupy_tests/io_tests/test_formatting.py, tests/cupyx_tests/fallback_mode_tests/test_fallback.py
=> [backport] Remove conversions of array with ndim > 0 to a scalar

docs/source/install.rst
=> Fix CUDA 12.2 for Windows notice

.github/workflows/pretest.yml, cupy/_core/_routines_linalg.pyx, cupy/_core/core.pyx, cupy/cuda/__init__.py, cupy/cuda/device.pyx, cupy/linalg/_decomposition.py, cupy/linalg/_eigenvalue.py, cupy/linalg/_solve.py, cupyx/__init__.py, cupyx/linalg/_solve.py
This is a part of #7620. Lazy import cuBLAS.
=> Lazy import cuBLAS

docs/source/install.rst
Backport of #7922 by @kmaehashi
=> [backport] Fix CUDA 12.2 for Windows notice

tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
=> [backport] Skip some LOBPCG tests failing with SciPy 1.11

cupy/cuda/cupy_cub.cu
CUB utilities `cub::If` and `cub::Equals` are deprecated.
There's no need to backport this PR, as the v12 branch does not see the same CCCL headers across all CUDA versions.
=> MNT: Suppress CUB compilation warnings 

cupyx/distributed/_comm.py, cupyx/distributed/_store.py
Resolves #7863. Solution by @milesvant
=> Provide .stop() method for cupyx.distributed._Backend

.pfnci/windows/_flexci.ps1, .pfnci/windows/test.ps1
Backport of #7957 by @kmaehashi
=> [backport] Fix Windows test scripts

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_spectral.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py
Depends on https://github.com/cupy/cupy/pull/7838
=> Port vectorstrength, coherence and spectrogram from CuSignal to cupyx.scipy.signal

.gitmodules, .pfnci/windows/test.ps1, cupy/_core/include/cupy/cub/.gitattributes, cupy/_core/include/cupy/cub/LICENSE.TXT, cupy/_core/include/cupy/cub/cub
This removes CUB files that are unnecessary for CuPy's functionality. Ref #7920.
=> [v12] Remove unnecessary CUB files from CuPy distribution

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_ltisys.py, docs/source/reference/scipy_signal.rst, setup.cfg, tests/cupyx_tests/scipy_tests/signal_tests/test_ltisys.py
=> cupyx/scipy/signal: add place poles

.pfnci/config.pbtxt, .pfnci/windows/_flexci.ps1, .pfnci/windows/test.ps1, docs/source/install.rst, setup.py, tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py
Backport of #7947 by @kmaehashi
=> [backport] Support Python 3.12, add Windows CI

docs/requirements.txt, docs/source/install.rst, setup.py
Backport of #7992 by @kmaehashi
=> [backport] Bump supported NumPy & SciPy versions

cupyx/scipy/signal/__init__.py, cupyx/scipy/signal/_max_len_seq.py, docs/source/reference/scipy_signal.rst, tests/cupyx_tests/scipy_tests/signal_tests/test_max_len_seq.py
=> Add max_len_seq to cupyx.scipy.signal

docker/python3/Dockerfile, docker/rocm/Dockerfile
Previous: https://github.com/cupy/cupy/pull/7795
=> [v12] Bump version in Dockerfile to v12.3.0

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Bump version in Dockerfile to v13.0.0rc1

docs/source/upgrade.rst
Backport of #8021 by @kmaehashi
=> [backport] Add upgrade guide for v13

cupy/_core/_cub_reduction.pyx, cupy/_core/_fusion_kernel.pyx, cupy/_core/_fusion_op.py, cupy/_core/_kernel.pxd, cupy/_core/_reduction.pyx, cupy/_core/_routines_statistics.pyx, tests/cupy_tests/sorting_tests/test_search.py
Close https://github.com/cupy/cupy/issues/8014.
=> Fix argmax/argmin for large reduction axis

docs/source/user_guide/performance.rst
=> Add a note on accelerating CI/CD

cupyx/scipy/fft/_realtransforms.py, tests/cupyx_tests/scipy_tests/fft_tests/test_realtransforms.py
https://github.com/scipy/scipy/pull/18613.
=> Fix `cupyx.scipy.fft.{dst,dstn}` in type 2/3

tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py
=> Remove some `signal.vectorstrength` xfail tests

tests/cupyx_tests/scipy_tests/fft_tests/test_realtransforms.py, tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py, tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
https://ci.preferred.jp/cupy.linux.cuda121/152363/
=> Fix scipy>=1.12 filter condition

cupyx/signal/__init__.py, cupyx/signal/_acoustics/__init__.py, cupyx/signal/_acoustics/_cepstrum.py, tests/cupyx_tests/signal_tests/acoustics_tests/test_cepstrum.py
=> add `cupyx.signal.{complex_cepstrum,real_cepstrum,inverse_complex_cepstrum,minimum_phase}`

cupyx/scipy/special/_beta.py, cupyx/scipy/special/_stats_distributions.py, tests/cupyx_tests/scipy_tests/special_tests/test_beta.py, tests/cupyx_tests/scipy_tests/special_tests/test_ufunc_dispatch.py
https://github.com/scipy/scipy/pull/17697/files#diff-fd436f10742a9f7191568deddfd22044f07e286873ed08725071a55c5af50301R29-R35
=> Fix `cupyx.scipy.special.betainc` for invalid inputs

cupyx/signal/_radartools/_radartools.py, tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py
https://github.com/cupy/cupy/pull/8022, https://github.com/cupy/cupy/pull/8057
=> Refactor radartools tests

cupyx/signal/_radartools/_radartools.py, tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py
Blocked by https://github.com/cupy/cupy/pull/8071.
=> Refactor radartools

cupyx/signal/__init__.py, cupyx/signal/_convolution/__init__.py, cupyx/signal/_convolution/_convolve.py, tests/cupyx_tests/signal_tests/convolution_tests/test_convolve.py
Part of https://github.com/cupy/cupy/issues/8055.
=> Add `cupyx.signal.convolve1d2o`

cupyx/signal/__init__.py, cupyx/signal/_convolution/__init__.py, cupyx/signal/_convolution/_convolve.py, tests/cupyx_tests/signal_tests/convolution_tests/test_convolve.py
=> [backport] Add `cupyx.signal.convolve1d2o`

tests/cupyx_tests/scipy_tests/special_tests/test_beta.py, tests/cupyx_tests/scipy_tests/special_tests/test_ufunc_dispatch.py
=> [backport] Fix cupyx.scipy.special.betainc for invalid inputs

cupyx/signal/__init__.py, cupyx/signal/_filtering/__init__.py, cupyx/signal/_filtering/_filtering.py, docs/source/reference/ext.rst, tests/cupyx_tests/signal_tests/filtering_tests/test_filtering.py
=> Add `cupyx.signal.freq_shift`

README.md, docs/source/install.rst
- Add docs for `cupy-core` (https://github.com/conda-forge/cupy-feedstock/pull/241#issuecomment-1898976347)
- Minor update to reflect the recent change in conda-forge
=> Update conda installation guide

install/cupy_builder/_features.py
=> Do not search for static libs

cupyx/signal/__init__.py, cupyx/signal/_filtering/__init__.py, cupyx/signal/_filtering/_filtering.py, docs/source/reference/ext.rst, tests/cupyx_tests/signal_tests/filtering_tests/test_filtering.py
=> Add `cupyx.signal.channelize_poly`

cupyx/cutensor.pyx, tests/cupyx_tests/test_cutensor.py
Related issue: https://github.com/cupy/cupy/issues/8133
Related PR: https://github.com/cupy/cupy/pull/8136
=> add incontiguous support for cutensor functions

cupy/_core/_scalar.pyx, cupy/_core/core.pyx, tests/cupy_tests/random_tests/test_bit_generator.py, tests/cupy_tests/random_tests/test_generator.py
Close https://github.com/cupy/cupy/issues/8049.
=> Remove usages of `numpy.float_` and `numpy.complex_`

cupyx/scipy/spatial/distance.py
=> Fix pdist docstring in order to specify that the returned matrix is condensed

cupyx/_runtime.py
=> Allow `cupy.show_config()` without CUDA

cupyx/scipy/linalg/_matfuncs.py, tests/cupyx_tests/scipy_tests/linalg_tests/test_matfuncs.py
closes https://github.com/cupy/cupy/issues/8205
=> Fix `expm(complex matrix)`

cupy/cuda/jitify.pyx
=> Fix jitify warmup kernel

cupyx/scipy/interpolate/_interpolate.py, cupyx/scipy/signal/_iir_utils.py, cupyx/scipy/signal/_max_len_seq.py, cupyx/scipy/signal/_peak_finding.py, cupyx/scipy/signal/_spectral_impl.py, cupyx/scipy/signal/_splines.py, cupyx/scipy/signal/_waveforms.py
=> [backport] Fix: remove unnecessary include that causes deployment issue

README.md
This PR is add some information of CuPy training materials.
The following information has been added, which is useful for those new to CuPy.
- GTC Fall 2021 session (40min video): GPU Acceleration in Python using CuPy and Numba.
- ICASSP'21 Tutorial: GPU-Acceleration of Signal Processing Workflows using CuPy and cuSignal.
=> Add CuPy Training Materials information to README.md

.pfnci/linux/tests/cuda-build.sh, tests/import_tests/test_import.py
=> Add import test without CUDA Toolkit

cupyx/scipy/interpolate/_rbfinterp.py, tests/cupyx_tests/scipy_tests/interpolate_tests/test_rbfinterp.py
Depends on https://github.com/cupy/cupy/pull/7671
=> Add neighbors option to RbfInterpolator

cupyx/scipy/interpolate/__init__.py, cupyx/scipy/interpolate/_ndbspline.py, docs/source/reference/scipy_interpolate.rst, tests/cupyx_tests/scipy_tests/interpolate_tests/test_ndbspline.py
=> Add NdBSpline to cupyx.scipy.interpolate

cupy/random/cupy_distributions.cu, tests/cupy_tests/random_tests/test_generator_api.py
=> Fix overflow of index calculation in random generator API

cupy_backends/cuda/cupy_cutensor.h, cupy_backends/cuda/libs/cutensor.pxd, cupy_backends/cuda/libs/cutensor.pyx, cupy_backends/cuda/stream.pxd, cupy_backends/cuda/stream.pyx, cupy_backends/stub/cupy_cutensor.h, cupyx/cutensor.pyx, install/cupy_builder/_features.py, tests/cupyx_tests/test_cutensor.py
Add CutensorMg support and corresponding test unit.
=> Add CutensorMg support

cupy/linalg/_norms.py
This is a ~~cumpletely~~ completely unavoidable issue, but I've fixed it.
=> Fixed critical documentation issue

cupyx/scipy/signal/_spectral.py
See https://github.com/cupy/cupy/pull/7564#discussion_r1545755447
=> Replace license notice in cupyx.scipy.signal._spectral

cupyx/scipy/interpolate/__init__.py, cupyx/scipy/interpolate/_interpnd.py, cupyx/scipy/spatial/delaunay_2d/_kernels.py, cupyx/scipy/spatial/delaunay_2d/_tri.py, docs/source/reference/scipy_interpolate.rst, tests/cupyx_tests/scipy_tests/interpolate_tests/test_interpnd.py
=> Add CloughTocher2DInterpolator to cupyx.scipy.interpolate

docs/source/install.rst
=> Update document for CUDA 12.3 and 12.4

.pfnci/config.pbtxt, .pfnci/config.tags.json, .pfnci/coverage.rst, .pfnci/linux/tests/cuda123.Dockerfile, .pfnci/linux/tests/cuda123.multi.Dockerfile, .pfnci/linux/tests/cuda123.multi.sh, .pfnci/linux/tests/cuda123.sh, .pfnci/linux/tests/cuda124.Dockerfile, .pfnci/linux/tests/cuda124.multi.Dockerfile, .pfnci/linux/tests/cuda124.multi.sh, .pfnci/linux/tests/cuda124.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml, .pfnci/windows/_flexci.ps1, tests/cupy_tests/core_tests/fusion_tests/fusion_utils.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
Backport of #8265 by @kmaehashi
- https://ci.preferred.jp/cupy.linux.cuda123/159814/ success
- https://ci.preferred.jp/cupy.linux.cuda123.multi/159815/ success
- https://ci.preferred.jp/cupy.linux.cuda124/159816/ success
- https://ci.preferred.jp/cupy.linux.cuda124.multi/159817/ success
- https://ci.preferred.jp/cupy.win.cuda123/159818/ timeout -> retry once
- https://ci.preferred.jp/cupy.win.cuda124/159819/ timeout -> retry once
=> [backport] Add support for CUDA 12.3 & 12.4

cupyx/scipy/spatial/_delaunay.py, docs/source/reference/scipy_spatial.rst
=> Expose Delaunay in documentation

cupy/cuda/cupy_cub.cu
=> Fix CUB build error on win-64

docs/source/install.rst
In PR #8074  (cf ISSUE #6757 ), I found the installation guide-doc unchanged. Please update it accordingly.
=> Update the version of cusparselt in the installation guide

docs/source/install.rst
Should we make this at this moment?
=> Add NumPy 2.0 on document

docs/source/install.rst
https://github.com/cupy/cupy/pull/8368#pullrequestreview-2110262882
=> Update API baseline on document

cupyx/scipy/ndimage/_interp_kernels.py, cupyx/scipy/ndimage/_interpolation.py
=> Fix `map_cordinates` recompilation condition

.pfnci/config.pbtxt, .pfnci/config.tags.json, .pfnci/coverage.rst, .pfnci/linux/tests/cuda125.Dockerfile, .pfnci/linux/tests/cuda125.multi.Dockerfile, .pfnci/linux/tests/cuda125.multi.sh, .pfnci/linux/tests/cuda125.sh, .pfnci/linux/update-cuda-driver.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml, .pfnci/windows/_flexci.ps1
Backport of #8337 by @johnnynunez
https://ci.preferred.jp/cupy.linux.cuda125/164749/
https://ci.preferred.jp/cupy.linux.cuda125.multi/164750/
https://ci.preferred.jp/cupy.win.cuda125/164751/
=> [backport] Cuda 12.5 Tests

docs/source/install.rst
=> Add CUDA 12.5 to list of supported platform

.pfnci/generate.py, .pfnci/linux/tests/cuda112.Dockerfile, .pfnci/linux/tests/cuda112.multi.Dockerfile, .pfnci/linux/tests/setup/setup-yum-centos7-post.sh, .pfnci/linux/tests/setup/setup-yum-centos7-pre.sh
See https://github.com/cupy/cupy/pull/8429#issuecomment-2234234738.
=> Fix CUDA 11.2 CI failure on Linux

cupy/_environment.py
Closes: https://github.com/cupy/cupy/issues/8440
=> Address KeyErrors from importlib_metadata

tests/cupy_tests/core_tests/test_ndarray.py, tests/cupy_tests/core_tests/test_ndarray_indexing.py, tests/cupy_tests/core_tests/test_reduction.py, tests/cupy_tests/creation_tests/test_basic.py, tests/cupy_tests/indexing_tests/test_iterate.py, tests/cupy_tests/lib_tests/test_shape_base.py, tests/cupy_tests/logic_tests/test_content.py, tests/cupy_tests/manipulation_tests/test_basic.py, tests/cupy_tests/manipulation_tests/test_dims.py, tests/cupy_tests/manipulation_tests/test_join.py, tests/cupy_tests/manipulation_tests/test_kind.py, tests/cupy_tests/manipulation_tests/test_transpose.py, tests/cupy_tests/math_tests/test_arithmetic.py, tests/cupy_tests/math_tests/test_misc.py, tests/cupy_tests/math_tests/test_sumprod.py, tests/cupy_tests/padding_tests/test_pad.py, tests/cupy_tests/sorting_tests/test_sort.py, tests/cupy_tests/statistics_tests/test_meanvar.py, tests/cupy_tests/testing_tests/test_helper.py, tests/cupy_tests/testing_tests/test_loops.py
=> Resolve Ruff `NPY` errors

cupy/testing/_helper.py, setup.py, tests/cupy_tests/testing_tests/test_helper.py
=> Get rid of `pkg_resources`

cupy/_environment.py, cupy/cuda/compiler.py, cupyx/_runtime.py
=> Search header files from CTK wheel

cupy/_environment.py
My silly mistake... 🤦‍♂️
Follows-up #8489
=> Fix CUDA version condition to use headers from wheel

cupyx/scipy/linalg/_special_matrices.py, tests/cupyx_tests/scipy_tests/linalg_tests/test_uarray.py
Fix https://github.com/cupy/cupy/pull/8506
=> [v13] Fix deprecation backport

tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
=> Relax `test_firls` atol

.pfnci/config.pbtxt, .pfnci/config.tags.json, .pfnci/coverage.rst, .pfnci/linux/tests/cuda126.Dockerfile, .pfnci/linux/tests/cuda126.multi.Dockerfile, .pfnci/linux/tests/cuda126.multi.sh, .pfnci/linux/tests/cuda126.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml, .pfnci/windows/_flexci.ps1, cupy/_core/core.pyx, cupy/_core/include/cupy/_cuda/cuda-12.6/cuda_fp16.h, cupy/_core/include/cupy/_cuda/cuda-12.6/cuda_fp16.hpp, docs/source/install.rst
Part of #8482
https://ci.preferred.jp/cupy.linux.cuda126/168834/
https://ci.preferred.jp/cupy.linux.cuda126.multi/168721/
https://ci.preferred.jp/cupy.win.cuda126/168835/
=> Support CUDA 12.6

cupy/_core/core.pyx
Backport of #8518 by @kmaehashi
=> [backport] Fallback to system headers for future CUDA 12.x versions

docker/python3/Dockerfile, docker/rocm/Dockerfile
=> Remove unnecessary "install" package in Docker image

cupyx/scipy/special/_basic.py, cupyx/scipy/special/_digamma.py, cupyx/scipy/special/_gamma.py, cupyx/scipy/special/_loggamma.py, cupyx/scipy/special/_spherical_bessel.py, cupyx/scipy/special/_statistics.py, tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py, tests/cupyx_tests/scipy_tests/special_tests/test_digamma.py, tests/cupyx_tests/scipy_tests/special_tests/test_exprel.py, tests/cupyx_tests/scipy_tests/special_tests/test_gamma.py, tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py, tests/cupyx_tests/scipy_tests/special_tests/test_spherical_bessel.py, tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
=> Fix dtype rule of special functions for SciPy 1.14

cupyx/scipy/stats/_distributions.py, tests/cupyx_tests/scipy_tests/stats_tests/test_distributions.py
=> Fix dtype rule of `cupy.scipy.stats.entropy` for SciPy 1.14

tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py, tests/cupyx_tests/scipy_tests/special_tests/test_digamma.py, tests/cupyx_tests/scipy_tests/special_tests/test_exprel.py, tests/cupyx_tests/scipy_tests/special_tests/test_gamma.py, tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py, tests/cupyx_tests/scipy_tests/special_tests/test_spherical_bessel.py, tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
Backport of https://github.com/cupy/cupy/pull/8532.
=> [v13] Skip special tests for SciPy 1.14 dtype rule changes

.pfnci/config.pbtxt, .pfnci/linux/tests/actions/unittest.sh, .pfnci/windows/test.ps1
=> Revert CI timeout bump

tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
=> [v13] Missing backport for sparse_array.A removal

cupy_backends/hip/cupy_hip_runtime.h
=> Guard for ROCm 6.x

docs/source/user_guide/fft.rst
=> docs: update fft.rst

cupy_backends/cuda/api/_runtime_typedef.pxi, cupy_backends/cuda/api/runtime.pyx, cupy_backends/hip/cupy_hip_runtime.h
Follows up #8610 (#8335)
Tested the PR with both ROCm 5.7 & 6.2.
=> Fix `HIP_VERSION` unit

.github/workflows/self-hosted-ci.yml, .pfnci/coverage.rst, .pfnci/linux/tests/rocm-6-2.Dockerfile, .pfnci/linux/tests/rocm-6-2.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml
Ref https://github.com/cupy/cupy/issues/8606
=> Add CI for ROCm 6.2

.pfnci/linux/tests/rocm-6-2.Dockerfile
=> Renegerate rocm-6-2.Dockerfile

tests/cupyx_tests/scipy_tests/signal_tests/test_max_len_seq.py, tests/cupyx_tests/scipy_tests/signal_tests/test_resample.py, tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py, tests/cupyx_tests/scipy_tests/signal_tests/test_windows.py, tests/cupyx_tests/signal_tests/filtering_tests/test_filtering.py, tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py
Backport of #8634 by @EarlMilktea
=> [backport] Skip tests if `scipy` is not installed

tests/cupy_tests/indexing_tests/test_indexing.py
=> Use `with_requires` rather than `xfail`

docs/source/contribution.rst, setup.py
- Remove deprecated `stylecheck` deps.
- Update the contribution guide
MEMO: I'm intentionally not mentioning the details of the checks for future replacement/addition.
=> Update documentation to use `pre-commit`

docs/source/contribution.rst, setup.py
Backport of #8640 by @EarlMilktea
=> [backport] Update documentation to use `pre-commit`

.pre-commit-config.yaml, cupy/_core/_gufuncs.py, cupyx/scipy/signal/_iir_filter_conversions.py, cupyx/scipy/signal/_upfirdn.py, cupyx/scipy/sparse/linalg/_iterative.py, tests/cupy_tests/core_tests/fusion_tests/fusion_utils.py, tests/cupy_tests/linalg_tests/test_product.py, tests/cupy_tests/test_type_routines.py, tests/cupyx_tests/fallback_mode_tests/test_fallback.py
Backport of #8628 by @EarlMilktea
=> [backport] Update precommit

docs/source/contribution.rst
=> Add tips on Windows development in Contribution Guide

cupyx/jit/_cuda_types.py, tests/cupyx_tests/jit_tests/test_raw.py
Close https://github.com/cupy/cupy/issues/8696.
=> Fix undefined inf/nan constant in CuPy JIT

.pfnci/coverage.rst, .pfnci/linux/tests/cuda11x-cuda-python.Dockerfile, .pfnci/matrix.yaml, cupyx/_runtime.py
=> [backport] Bump CUDA version in cuda11x-cuda-python CI

tests/cupyx_tests/scipy_tests/signal_tests/test_peak_finding.py, tests/cupyx_tests/scipy_tests/special_tests/test_basic.py, tests/cupyx_tests/test_lapack.py
Backport of #8727 by @EarlMilktea
=> [backport] Fix some NumPy 2.x CI failures (cupyx)

cupy/_statistics/order.py, tests/cupy_tests/statistics_tests/test_order.py
=> Fix `cupy.percentile` for NumPy 2.x

cupy/_statistics/order.py
https://github.com/cupy/cupy/pull/8726#discussion_r1846086478
=> Enhance comments in percentile implementation

.github/ISSUE_TEMPLATE/bug.yml
* Mark installation method and environment information required
* Ask user to do "show_config(_full=True)" for better diagnosis
=> Update bug issue template

.github/workflows/pretest.yml, install/cupy_builder/_command.py
=> Resolve uncaught type warning

cupy/fft/_fft.py, cupy/lib/_routines_poly.py, cupyx/scipy/fft/_fft.py, cupyx/scipy/special/_gammaln.py, tests/cupy_tests/fft_tests/test_fft.py, tests/cupy_tests/lib_tests/test_polynomial.py, tests/cupy_tests/manipulation_tests/test_basic.py, tests/cupy_tests/math_tests/test_special.py, tests/cupyx_tests/scipy_tests/interpolate_tests/test_rbfinterp.py, tests/cupyx_tests/scipy_tests/special_tests/test_gammaln.py
Related to #8565 .
This PR partly fixes CI failures marked with `XXX`.
=> Fix some NumPy 2.x CI failures (cont.) 

cupy/_statistics/order.py, tests/cupy_tests/statistics_tests/test_order.py
Closes https://github.com/cupy/cupy/issues/8806. Convert axis to a tuple before iterating over it if it is int
=> Fix crashes of quantile and percentile

.pfnci/config.pbtxt, cupy/_core/_routines_math.pyx, cupy/_functional/vectorize.py, cupy/random/_distributions.py, cupy/random/_generator.py, cupyx/jit/_cuda_typerules.py, tests/cupy_tests/random_tests/test_generator.py, tests/cupyx_tests/scipy_tests/signal_tests/test_polyutils.py, tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py
Part of https://github.com/cupy/cupy/issues/8306 and https://github.com/cupy/cupy/issues/8514.
=> Add NumPy 2.x CI for Windows

.github/workflows/flexci.yml
=> Revert "Fix FlexCI trigger workflow"

cupy/_manipulation/add_remove.py, cupy/polynomial/polyutils.py, tests/cupy_tests/manipulation_tests/test_add_remove.py, tests/cupy_tests/statistics_tests/test_correlation.py
Temporary skip for failing tests.
=> Skip some tests incompatible with NumPy 2.2

.github/workflows/scripts/flexci_dispatcher.py
Follow-up #8832. FlexCI's pull_request event support should not be used in this case.
=> CI: Fix FlexCI compatibility

cupy/_statistics/correlation.py, tests/cupy_tests/statistics_tests/test_correlation.py
This PR incorporates https://github.com/numpy/numpy/pull/27661 .
=> Fix `cupy.cov`

.flake8.cython, .github/workflows/scripts/backport_reminder.py, .pre-commit-config.yaml, .ruff.toml, cupy/__init__.py, cupy/_core/__init__.py, cupy/linalg/_einsum_opt.py, cupy/random/__init__.py, cupyx/distributed/array/_linalg.py, cupyx/scipy/fft/_realtransforms.py, cupyx/scipy/ndimage/_measurements.py, cupyx/scipy/ndimage/_spline_kernel_weights.py, cupyx/scipy/sparse/_sputils.py, setup.cfg, tests/cupyx_tests/jit_tests/test_raw.py, tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py, tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py, tests/cupyx_tests/scipy_tests/signal_tests/test_upfirdn.py
Backport of #8671 by @EarlMilktea
=> [backport] Replace `flake8` with `ruff`

cupyx/signal/__init__.py, cupyx/signal/_radartools/__init__.py, cupyx/signal/_radartools/_beamformers.py, tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py
Part of https://github.com/cupy/cupy/issues/8055.
=> Add `cupyx.signal.mvdr`

tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
=> Fix test for csr_matrix.setdiag

cupy/cuda/cupy_cub.cu
In similar spirit as #8446, users should not specialize `cub::Min` and `cub::Max`. We recently changed their definition to be aliases to `cuda::minimum` and `cuda::maximum`, which will break cupy when it upgrades to CCCL 2.8. This PR provides a fix for that.
* Avoid specializing cub::Min/Max
* Use cuda::minimum/maximum when available
=> Use a custom Min/Max instead of specializing CUB

cupyx/scipy/sparse/_compressed.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
=> Raise ValueError upon attempts to create 3-dim sparse array

cupyx/scipy/fft/_fftlog.py, tests/cupyx_tests/scipy_tests/fft_tests/test_fftlog.py
https://github.com/scipy/scipy/pull/21668
=> Fix `fft.fht` following bug fix in SciPy 1.15

cupy/testing/__init__.py, cupy/testing/_helper.py, tests/cupy_tests/testing_tests/test_helper.py
Add a new testing function.
Rel https://github.com/cupy/cupy/issues/8893.
=> Add `testing.shaped_linspace`

.pre-commit-config.yaml
Backport of #8838 by @EarlMilktea
=> [backport] Update `pre-commit` hooks

.pfnci/linux/tests/cuda-rapids.Dockerfile, .pfnci/linux/tests/cuda-rapids.sh, cupyx/scipy/spatial/distance.py, docs/source/reference/scipy_spatial.rst, docs/source/reference/scipy_spatial_distance.rst, tests/cupyx_tests/scipy_tests/spatial_tests/test_distance.py
=> [backport] Updating pylibraft `pairwise_distance` to cuvs

cupyx/scipy/stats/_morestats.py, tests/cupyx_tests/scipy_tests/stats_tests/test_morestats.py
Follow up #8095
Details see https://github.com/scipy/scipy/pull/20021
=> Fix boxcox_llf for SciPy 1.13

.gitmodules, .pfnci/coverage.rst, .pfnci/linux/tests/cuda123.multi.sh, .pfnci/linux/tests/cuda123.sh, .pfnci/matrix.yaml, .pfnci/windows/_flexci.ps1
Update CCCL submodule to pickup commit: https://github.com/NVIDIA/cccl/commit/3a388b7b01512d48474b98389a3e776c8d8f817a
This fixes an issue seen previously with CUDA 12.3
=> Use NVIDIA CCCL 2.8 latest w/CUDA 12.3 fix

cupyx/scipy/stats/_morestats.py, tests/cupyx_tests/scipy_tests/stats_tests/test_morestats.py
=> Fix dtype rule of boxcox_llf for SciPy 1.15

install/cupy_builder/_compiler.py, install/cupy_builder/_features.py
Fixes minimum CUDA version check and improve comment regarding compute capability.
=> Fix minimum CUDA version check and update comments

cupyx/tools/install_library.py
Part of #8903. xref https://github.com/cupy/cupy/pull/8899#issuecomment-2621647610
=> Bump library installers for CUDA 12.8

.gitmodules, cupy/_core/core.pyx, cupy/_core/include/cupy/_cuda/cuda-12.8/cuda_fp16.h, cupy/_core/include/cupy/_cuda/cuda-12.8/cuda_fp16.hpp, cupy/cuda/compiler.py, cupy/cuda/cupy_cub.cu, cupy/cuda/jitify.pyx, cupy/fft/_callback.pyx, install/cupy_builder/_compiler.py, setup.cfg, tests/cupy_tests/core_tests/test_include.py, tests/cupy_tests/core_tests/test_raw.py, tests/cupy_tests/cuda_tests/test_compiler.py, tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py, tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_design.py, tests/cupyx_tests/scipy_tests/signal_tests/test_ltisys.py
=> [backport] Support CUDA 12.8 + Blackwell GPUs (sm_100, sm_120)

.gitmodules, .pfnci/coverage.rst, .pfnci/linux/tests/cuda123.multi.sh, .pfnci/linux/tests/cuda123.sh, .pfnci/matrix.yaml, .pfnci/windows/_flexci.ps1, cupy/_core/core.pyx, cupy/cuda/compiler.py
=> [backport] Use CCCL 2.8.x branch + Use `CUPY_CACHE_KEY` in hash keys

.pfnci/config.pbtxt, .pfnci/config.tags.json, .pfnci/coverage.rst, .pfnci/linux/tests/cuda128.Dockerfile, .pfnci/linux/tests/cuda128.multi.Dockerfile, .pfnci/linux/tests/cuda128.multi.sh, .pfnci/linux/tests/cuda128.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml, .pfnci/windows/_flexci.ps1
Backport of #8905 by @kmaehashi
Testing at: https://ci.preferred.jp/p/dashboard_by_commit_id?commit_id=20123faf3ab6e8804a2cef47c6069d87021efeb9
=> [backport] Add CI for CUDA 12.8

docs/source/install.rst
=> Update list of supported versions

docs/source/install.rst
Backport of #8986 by @kmaehashi
=> [backport] Update list of supported versions

cupyx/jit/_compile.py, tests/cupyx_tests/jit_tests/test_raw.py
Close https://github.com/cupy/cupy/issues/8979.
=> JIT: Support empty return

tests/cupy_tests/core_tests/fusion_tests/test_ufunc.py
Test only ~backport~ forward port of gh-9012
=> TST: Add test for fusion path with constant and scalar

cupy/_core/fusion.pyx, tests/cupy_tests/core_tests/fusion_tests/test_ufunc.py
=> [v13.4.1] BUG: Hot fix for numpy 2 support in some fusion paths

cupyx/scipy/stats/_stats_py.py, tests/cupyx_tests/scipy_tests/stats_tests/test_stats.py
=> Fix `cupyx.scipy.stats.zscore` for SciPy 1.15

.pfnci/windows/test.ps1
Backport of #9039 by @chainer-ci
=> [v13.4.1] CI: Pin setuptools version on Windows

cupy/_core/_fusion_variable.pyx, tests/cupy_tests/core_tests/fusion_tests/test_misc.py
Backport of #9043 by @chainer-ci
=> [v13.4.1] Fix compilation error of cupy.inf in fusion2

.pfnci/windows/test.ps1
https://github.com/cupy/cupy/pull/9038#issuecomment-2741941395
=> Revert "CI: Pin setuptools version on Windows"

tests/cupyx_tests/scipy_tests/signal_tests/test_bsplines.py, tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py
=> Mark xfails in some spline tests for SciPy 1.15

tests/cupyx_tests/scipy_tests/special_tests/test_basic.py, tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py
=> [v13] Skip some cupyx.scipy.special tests for SciPy 1.15

cupy/testing/_array.py, cupy/testing/_loops.py
Close https://github.com/cupy/cupy/issues/9071.
=> Update `cupy.testing` followiing numpy

.github/workflows/pretest.yml, cupy/cuda/cupy_thrust.h, install/cupy_builder/_features.py
=> Allow build on ROCm 6.4

docs/source/install.rst
https://github.com/cupy/cupy/issues/9101#issuecomment-2820080726
xref #8607
=> Update ROCm docs

pyproject.toml
=> [v13] Bump NumPy version restriction

.pfnci/config.pbtxt
=> [backport] Add NumPy 2.3 + windows CI

.pfnci/config.tags.json, .pfnci/matrix.yaml
=> Fix test trigger phrase for `cupy.win.cuda129` CI

cupyx/scipy/special/_basic.py, cupyx/scipy/special/_beta.py, cupyx/scipy/special/_erf.py, cupyx/scipy/special/_stats_distributions.py, cupyx/scipy/special/_xlogy.py, tests/cupyx_tests/scipy_tests/special_tests/test_basic.py, tests/cupyx_tests/scipy_tests/special_tests/test_beta.py, tests/cupyx_tests/scipy_tests/special_tests/test_erf.py, tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
=> Update cupyx.scipy.special functions for SciPy 1.16

tests/cupyx_tests/scipy_tests/linalg_tests/test_solve_triangular.py
=> [backport] Add test cases for batchwise `solve_triangular` (as xfail)

tests/cupyx_tests/scipy_tests/special_tests/test_basic.py, tests/cupyx_tests/scipy_tests/special_tests/test_erf.py, tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
=> [backport] Update cupyx.scipy.special functions for SciPy 1.16

tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
=> Relax tolerance of test_hilbert

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
Skip these tests until https://github.com/scipy/scipy/issues/22368 is resolved.
https://github.com/cupy/cupy/pull/8884
=> Skip some signal q dtype tests

cupyx/scipy/signal/_filter_design.py, tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py
https://github.com/scipy/scipy/pull/22982
=> Fix freqz for complex w

cupy/__init__.py
Close https://github.com/cupy/cupy/issues/9249.
=> Add `cupy.bool`, `cupy.long` and `cupy.ulong`

.pfnci/config.pbtxt
=> Support SciPy 1.16 on Windows

cupyx/scipy/sparse/linalg/_solve.py, tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
=> Fix lsmr type promotion rule for complex dtype 

.pfnci/config.pbtxt, .pfnci/config.tags.json, .pfnci/coverage.rst, .pfnci/linux/tests/cuda130.Dockerfile, .pfnci/linux/tests/cuda130.multi.Dockerfile, .pfnci/linux/tests/cuda130.multi.sh, .pfnci/linux/tests/cuda130.sh, .pfnci/matrix.yaml, .pfnci/schema.yaml, .pfnci/windows/_flexci.ps1, .pfnci/windows/test.ps1, cupy/_core/core.pyx, cupy/_core/include/cupy/_cuda/cuda-13.0/cuda_fp16.h, cupy/_core/include/cupy/_cuda/cuda-13.0/cuda_fp16.hpp, cupy/_environment.py, cupy/cuda/compiler.py, cupy_backends/cuda/api/_runtime_enum.pxd, cupy_backends/cuda/api/_runtime_extern.pxi, cupy_backends/cuda/api/_runtime_softlink.pxi, cupy_backends/cuda/api/_runtime_typedef.pxi, cupy_backends/cuda/api/runtime.pyx, cupy_backends/cuda/libs/_cnvrtc.pxi, cupy_backends/cuda/libs/cusparse.pyx, cupyx/tools/install_library.py, install/cupy_builder/_compiler.py, install/cupy_builder/install_build.py, tests/cupy_tests/cuda_tests/test_compiler.py, tests/cupy_tests/fft_tests/test_callback.py
Backport of #9289 by @emcastillo
cc/ @robertmaynard @leofang @agirault
=> [backport] Add CUDA 13 support

.github/workflows/flexci.yml
=> Fix syntax error in CI workflow

.github/workflows/flexci.yml, .github/workflows/self-hosted-ci.yml
Updates parameters for https://github.com/cupy/self-hosted-ci/commit/d080aab526eed522177a8dec1db6df91fafa6758
=> Fix handling of ROCm self-hosted CIs

cupy/_core/_cub_reduction.pyx
rocPRIM on ROCm 7.0 requires c++17. rocPRIM is included in cub headers, so this commit switches to c++17 when using hipCUB. This matches the nvcc behavior. This commit also does some minor cleanup.
This PR is structured so that there is no change for ROCm 6 usage.
=> feat(hipCUB) Use c++17 for hipCUB

cupy/_core/_routines_linalg.pyx, cupy/_core/include/cupy/carray.cuh, cupy/_core/raw.pyx, cupy/fft/_callback.pyx, cupy_backends/cuda/libs/_cnvrtc.pxi, cupy_backends/hip/cupy_hipblas.h, cupyx/scipy/interpolate/_bspline.py, cupyx/scipy/interpolate/_interpolate.py, cupyx/scipy/ndimage/_filters_core.py, cupyx/scipy/ndimage/_filters_generic.py, cupyx/scipy/ndimage/_pba_2d.py, cupyx/scipy/ndimage/_pba_3d.py, cupyx/scipy/signal/_bsplines.py, cupyx/scipy/signal/_fir_filter_design.py, cupyx/scipy/signal/_iir_utils.py, cupyx/scipy/signal/_peak_finding.py, cupyx/scipy/signal/_spectral_impl.py, cupyx/scipy/signal/_splines.py, cupyx/scipy/signal/_upfirdn.py, cupyx/scipy/signal/_waveforms.py, cupyx/scipy/signal/_wavelets.py, cupyx/scipy/sparse/_compressed.py, examples/custom_struct/complex_struct.py, examples/custom_struct/packed_matrix.py, tests/cupy_tests/core_tests/test_core.py, tests/cupy_tests/core_tests/test_function.py, tests/cupy_tests/functional_tests/test_vectorize.py
This PR enables ROCm 7.0. The build has been tested on self hosted CI using this PR: https://github.com/cupy/cupy/pull/9397
=> Enable rocm7
