cupy/cupy

cupy/cuda/memory.pyx

[backport] `MemoryAsyncPool`: Use the "current" mempool instead of the "default" one

---

cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

Currently MemoryAsync is holding a pointer to the stream, but this is unsafe because:
* In general it is prohibited to pass destoryed ptr to CUDA APIs (I sometimes experienced SegV).
* The stream ptr may be reused.  (e.g., `cudaStreamCreate(&x); cudaStreamDestroy(x); cudaStreamCreate(&y)  // x != y is not guaranteed`)
ref: #4592

Fix MemoryAsync to keep a weakref to stream

---

tests/cupy_tests/cuda_tests/test_memory.py

Follow-up of #5177. When debugging for https://github.com/chainer/chainer-test/pull/658#issuecomment-853133782 I realized my changes in the `TestAllocator` class was not legitimate, because it requires the ability of creating a new memory pool, which we currently do not support for `MemoryAsyncPool`:
https://github.com/cupy/cupy/blob/29eb596738a612bd77e2852f1cf6be99eb391ec0/cupy/cuda/memory.pyx#L1607-L1609
I will add the support in a separate PR,  after which we can re-enable this test.
cc: @kmaehashi

Temporarily remove the async pool test from `TestAllocator`

---

.pfnci/windows/test.ps1

I noticed that `atime` is not updated in Windows by default.
This PR changes the script trim only by the max size (the current cache size is 657 MB).

Fix Windows CI kernel cache

---

cupy/linalg/_einsum.py

This PR is to allow users to use cuTENSOR more with `cupy.einsum`.
To be more precise, we already have code in `cupy.einsum` to use cuTENSOR, but when we added that code, there was not that big performance difference compared to the einsum implementation using matmul. For this reason, we have restricted the cases where cuTENSOR is actually used, even when the environment variable `CUPY_ACCELERATORS` is set to "cutensor".
This PR removes that restriction so that `cupy.einsum` will use cuTENSOR when it is selected in the environment variable.
Although cuTENSOR is not always faster than current implementation, cuTENSOR 1.3 has improved performance considerably and has been shown to be faster in many cases, as shown below.
subscripts | x.shape | y.shape | time (asis) | time (cutensor) | …

Make cuTENSOR available in cupy.einsum

---

cupy/fft/_callback.pyx

Fix #5296. Thanks to @szsdk for reporting. 
We need to check if `nvprune` actually succeeds or not, as the static library does not contain device codes for certain CCs:
> Please note that the cuFFT library might not contain code for certain architectures as long as there is code for a lower architecture that is binary compatibile (e.g. SM37, SM52, SM61). 
> https://docs.nvidia.com/cuda/cufft/index.html#static-library
for example see https://github.com/cupy/cupy/issues/5296#issuecomment-851713662. 
To avoid the cost of rerunning `nvprune` for a CC known to not have any device code, we cache the CC after the first validation call. An alternative approach would be to not run `nvprune` at all (save us one long run) for a list of pre-compiled CCs, but there would be a maintenance burden on us …

Fix cuFFT callback for sm_61 etc

---

cupyx/jit/_builtin_funcs.py
cupyx/jit/_compile.py
cupyx/jit/_cuda_typerules.py
cupyx/jit/_cuda_types.py
tests/cupyx_tests/jit_tests/test_raw.py

Updated version of #5293.
- Built-in functions
- Array size functions
- Misc

Support `len`, `min`, `max`, `.ndim`, `.size` in jit

---

cupyx/jit/_compile.py
cupyx/jit/_cuda_types.py
tests/cupy_tests/functional_tests/test_vectorize.py

This PR supports nested tuple unpack in CuPy JIT.
Example:
```py
@cupyx.jit.rawkernel()
def f(x, y, z):
i = cupyx.jit.threadIdx.x
(x[i], y[i]), z[i] = (z[i], x[i]), y[i]
x = cupy.full((5), 10, dtype=cupy.int32)
y = cupy.full((5), 20, dtype=cupy.int32)
z = cupy.full((5), 30, dtype=cupy.int32)
f((1,), (5,), (x, y, z))
```
Generated kernel:
```cpp
extern "C" __global__ void f(CArray<int, 1, true, true> x, CArray<int, 1, true, true> y, CArray<int, 1, true, true> z) {
unsigned int i;
i = threadIdx.x;
{
thrust::tuple<thrust::tuple<int, int>, int> _temp0 = thrust::make_tuple(thrust::make_tuple(z[i], x[i]), y[i]);
{
thrust::tuple<int, int> _temp1 = thrust::get<0>(_temp0);
x[i] = thrust::get<0>(_temp1);
y[i] = thrust::get<1>(_temp1);
}
z[i] = thrust::get<1>(_temp0);
}
}
```
Related discussion: …

Support nested tuple unpack in CuPy JIT

---

cupy/cusolver.pyx

Found in discusson of #5204.
Functions that return per-device results should be memorized for each device.

Fix `check_availablity` for `cupy.cusolver`

---

cupyx/jit/__init__.py
cupyx/jit/_builtin_funcs.py
docs/source/reference/kernel.rst
tests/cupyx_tests/jit_tests/test_raw.py

This PR adds a convenience helper to make it easier to port existing Numba codes to CuPy JIT. The purpose of `jit.grid()` is to compute the absolute index of a thread in the grid. 
Note that `grid(n)` returns a tuple for n=2, 3. Calling `thrust::make_tuple()` would indeed incur a bit of overhead for such a simple operation, but to retain the Numba convention I am not sure if there's a better solution. Suggestions are more than welcome, as always!
The below snippet shows the generated CUDA code:
```python
def grid_1d():
x = jit.grid(1)
grid_1d[1, 1]()
print(grid_1d.cached_code)
def grid_2d():
x, y = jit.grid(2)
grid_2d[1, 1]()
print(grid_2d.cached_code)
def grid_3d():
x, y, z = jit.grid(3)
grid_3d[1, …
```

Support Numba-like `jit.grid()` syntax in CuPy JIT

---

.pfnci/config.pbtxt
.pfnci/script.sh
cupy_setup_build.py

Fix #5309 and #5314.
In ROCm 4.1 and later, we need to use the independent version of hipfft as well as rocfft. The hipFFT is assumed to be located in `/opt/rocm/hipfft`.
https://github.com/ROCmSoftwarePlatform/hipFFT

Use independent version of hipFFT for ROCm 4.1 and later

---

tests/cupy_tests/cuda_tests/test_memory.py

See https://github.com/chainer/chainer-test/pull/658.

Tentatively skip unstable `MemoryPoolAsync` tests

---

cupyx/jit/__init__.py
cupyx/jit/_builtin_funcs.py
cupyx/jit/_cuda_types.py
docs/source/reference/kernel.rst
tests/cupyx_tests/jit_tests/test_raw.py

Part of #5280.
Example:
```python
def f_shfl(a, b):
laneId = jit.threadIdx.x & 0x1f
if laneId == 0:
value = a
value = jit.shfl_sync(0xffffffff, value, 0)
b[laneId] = value
a = cp.int64(100)
b = cp.empty((32,), dtype=cp.int64)
f_shfl[1, 32](a, b)
print(b)
def f_shfl_up(a):
value = jit.shfl_up_sync(0xffffffff, a[jit.threadIdx.x], 5)
a[jit.threadIdx.x] = value
a = cp.arange(32, dtype=cp.int64)
f_shfl_up[1, 32](a)
print(a)
```
Output:
```
[100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
100 100 100 100 100 100 100 100 100 100 100 100 100 100]
[ 0  1  2  3  4  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
19 20 21 22 23 24 25 26]
```
TODO:

Support warp shuffle and sync functions in CuPy JIT

---

cupy/_environment.py
cupyx/tools/install_library.py

Currently some of features in cuDNN v8 is not working when installed via wheels.
```py
import ctypes
import cupy
import cupy.cuda.cudnn as libcudnn
import cupy.cudnn
x = cupy.arange(12, dtype=cupy.float32).reshape(3, 4)
cupy.cudnn.activation_forward(x, libcudnn.CUDNN_ACTIVATION_RELU)
cupy.cudnn.create_fused_ops_plan(0)  # CUDNN_FUSED_SCALE_BIAS_ACTIVATION_CONV_BNSTATS
```
The above example fails because `cudnn_cnn_train` depends on `cudnn_ops_infer`, `cudnn_ops_train`, and `cudnn_cnn_infer`, but `cudnn_ops_train` and `cudnn_cnn_infer` are not loaded and could not be discovered automatically by cuDNN.
This issue only occurs when chain-loading dependencies (i.e., loading a split module from another split module).
`libcudnn.so.8` has a `$ORIGIN` in RUNPATH, so `libcudnn.so.8` can find split …

Fix cuDNN preloading

---

cupy/cuda/texture.pxd
cupy/cuda/texture.pyx
tests/cupy_tests/cuda_tests/test_texture.py

Close #5341. For `copy_from` we can make a copy internally for handling non-contiguous inputs, but for `copy_to` we must require the input to be contiguous, otherwise it's not supported by `memcpy3DAsync`. 
The added tests fail on the current master.
cc: @the-lay

Ensure source array is C-contiguous before copying to `CUDAArray`

---

README.md

Backport of #5391 by @kmaehashi

[backport] Add `cupy-cuda113` and `cupy-rocm-4-2` to README and docs

---

cupyx/jit/_builtin_funcs.py

On HIP `atomicAdd` does not support half precision floating points.

JIT: Fix supported dtype of `atomic_add` on HIP

---

setup.cfg

`license_file` has been deprecated in setuptools v56.0.0.
`license_files` introduced in v42.0.0 needs to be used instead.
https://setuptools.readthedocs.io/en/latest/history.html#v42-0-0
https://setuptools.readthedocs.io/en/latest/history.html#v56-0-0

Fix `license_file` option in `setup.cfg`

---

cupy/_core/include/cupy/carray.cuh

Discussed with @emcastillo and this seems to be unused anywhere in the codebase.

Remove the data member `use_32bit_indexing` from `CArray`

---

cupy/_core/_routines_statistics.pyx
cupy/_statistics/meanvar.py
tests/cupy_tests/statistics_tests/test_meanvar.py

Close #5315.
This PR fixes `cupy.nanmedian`'s `axis` parameter to accept a sequence of axes other than a tuple. Also, it updates `axis` parameter's description in `cupy.nanmean`, `cupy.median` and `cupy.mean`.

Fix cupy.nanmedian's axis parameter to accept a sequence other than a tuple

---

tests/cupy_tests/core_tests/test_raw.py

This PR blocks #5407.
Currently, the following XFAIL is passing unexpectedly in Windows CI (cc: @leofang)
```
XPASS cupy_tests\core_tests\test_raw.py::TestRawJitify_param_0_{jitify=False}::test_jitify1 macro preprocessing in NVRTC is likely buggy
```

Remove xfail in windows jitify test

---

setup.cfg

pytest does not fail when XFAIL tests passes unexpectedly, unless strict mode is set.
Currently the following XFAIL is passing unexpectedly in Windows CI:
```
XPASS cupy_tests\core_tests\test_raw.py::TestRawJitify_param_0_{jitify=False}::test_jitify1 macro preprocessing in NVRTC is likely buggy
```
Retest and merge after https://github.com/cupy/cupy/pull/5409.

Enable strict xfail in pytest

---

cupy/testing/_helper.py
tests/cupy_tests/math_tests/test_misc.py

Follows up #5295.
This PR adds tests for `nan_to_num`'s `nan`, `posinf`, and `neginf` parameters.

Add tests for num_to_num's optional parameters

---

cupyx/jit/_builtin_funcs.py

[backport] JIT: Fix supported dtype of `atomic_add` on HIP

---

cupyx/jit/_builtin_funcs.py

[backport] JIT: Fix `__call__()` for built-in functions

---

cupy/lib/_shape_base.py

I assumed that usually, cupy reference in `seealso` section the numpy equivalent

Fix typo in `apply_along_axis`

---

cupyx/jit/_builtin_funcs.py
cupyx/jit/_cuda_types.py
tests/cupy_tests/functional_tests/test_vectorize.py

Fix to use `dtype.name` instead `dtype.char` and remove workaround from Windows behavior difference.
https://github.com/cupy/cupy/pull/5387#issuecomment-872319018

Use `dtype.name` instead `dtype.char`

---

cupy/_core/core.pyx
tests/cupy_tests/core_tests/test_dlpack.py

Follow-up: #5306
* Formatted string were broken :smile:
* Fix wrong tests. I noticed that stream consistency cannot be tested unless directly calling `__dlpack__` because the current stream in consumer (`cupy.from_dlpack`) and producer (`cupy.ndarray__dlpack__`) are always the same if both ends are CuPy.
Test failure detected in https://github.com/chainer/chainer-test/pull/673#issuecomment-874877502

Fix new DLPack protocol error messages and tests

---

cupyx/scipy/ndimage/interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

Follow-up of #5171. 
This PR fixes the CI errors since #5171 was merged (starting at commit https://github.com/kmaehashi/cupy-rocm-ci-report/commit/af1c43d68c774fd2d80f9454f93839773c816aa5) by skipping the texture tests, as we currently do not support texture memory on ROCm/HIP (https://github.com/cupy/cupy/issues/4132#issuecomment-764890763).

`texture_memory` option in `affine_transform` not supported by HIP

---

cupy/random/_generator_api.pyx
tests/cupy_tests/random_tests/test_generator_api.py

This was broken by returning invalid values due to use the wrong type in the output array
The statistical properties of the distribution were not currently tested, now they are

Fix random `integers`

---

cupyx/jit/__init__.py
cupyx/jit/_builtin_funcs.py
docs/source/reference/kernel.rst
tests/cupyx_tests/jit_tests/test_raw.py

Support Numba-like `jit.gridsize()` syntax in CuPy JIT

---

cupy/_core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

Fix #4354.
The result of `astype` from a ndarray whose dtype is boolean to another dtype is expected to be zero or one. However, its underlying representation is not necessarily zero or one (i.g. a view). And in such a case, `astype` returns a ndarray with values other than zero or one. This PR fixes `astype` from boolean ndarray to return the proper value.

Fix astype from boolean

---

tests/cupy_tests/core_tests/test_dlpack.py

Follow-up of #5449. On HIP the stream pointer cannot be 1.

Fix DLPack test for ROCm/HIP

---

docs/source/install.rst

[backport] Update install guide with new NumPy/SciPy versions

---

cupy/cuda/compiler.py

https://github.com/ROCm-Developer-Tools/HIP/issues/2182 is fixed since ROCm 4.2.0, so let's use it.

Try to use `-I` in hipRTC

---

cupy_backends/cuda/api/runtime.pyx
cupy_backends/hip/cupy_hip_runtime.h
cupy_backends/stub/cupy_cuda_runtime.h

I'm experimenting with peer access. It's handy if this is available in CuPy.

Add `cudaDeviceDisablePeerAccess` wrapper

---

.mergify.yml

Maybe `closed=false` condition is needed to avoid this: https://github.com/cupy/cupy/pull/5426#issuecomment-873896502
Just a wild guess.

Fix mergify to only comment when pull-request is open

---

.mergify.yml

With the change of #5439, mergify complains its configuration is invalid:
> Invalid condition 'closed=false'. Expected end of text, found '=' (at char 6), (line:1, col:7) @ pull_request_rules → item 1 → conditions → item 1
~~I can read that we have to use '-' prefix instead of '=' operator for negating a boolean condition:~~ 🤔 
https://docs.mergify.io/conditions/#grammar

Fix mergify condition

---

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

This reverts commit dad44ee7b7bbd410882ea0a9e6c48d5e6e6f6c99 in #5386.
The commit applied a part of
a012034c6c04331e1f7f3533cd3964d0ea05a25a in #5368
instead of reverting the part.

Fix "Revert test decorators order"

---

cupy/_core/core.pyx
cupy/_core/include/cupy/_cuda/cuda-11.4/cuda_fp16.h
cupy/_core/include/cupy/_cuda/cuda-11.4/cuda_fp16.hpp
cupy/cuda/compiler.py
cupy_setup_build.py
cupyx/tools/install_library.py

Blocked by https://github.com/chainer/chainer-test/pull/673.
Includes the following updates for CUDA 11.4:
- Compute capability support
- bundled FP16 header files
- library installer

Support CUDA 11.4 and support `compute_86`

---

.pfnci/linux/main-flexci.sh
.pfnci/linux/run.sh
.pfnci/linux/tests/_environment.sh

* Linux tests were not caching ccache/kernel binaries correctly.
* Fixes the branch tests to test full matrix, like as done in FlexCI Windows tests.

Fix FlexCI Linux tests

---

cupy/cusolver.pyx
cupy/cusparse.py

Part of #5401.
This PR also fixes the issue of cusolver availability test that checks HIP device compute capability against CUDA's pattern.

Fix availability tests in cuSOLVER and cuSPARSE

---

cupy/fft/_callback.pyx

Fix #5508.
It turns out that the prior patch #5304 is not robust enough. We must prune `libcufft_static.a` for all minor versions under the same major CC, which would fix the issue for sm_86 and is backward compatible with other CCs. In fact, this is a better patch that also help reduce the module sizes for all CC=XY with Y != 0.

prune cufft static lib by major cc ver

---

.github/workflows/auto-cc.yml

Automatically leave `cc/ someone` comment when specific label is set.
If we later need to support multiple labels, we can use `fromJSON` to define label-to-users mappings in JSON.
`peter-evans/*` is a third-party action, but I think it's quite stable as it's documented on GitHub's official website.
https://docs.github.com/en/actions/guides/commenting-on-an-issue-when-a-label-is-added

Add auto notify bot for `hip` label

---

.github/workflows/auto-cc.yml

https://github.com/peter-evans/create-or-update-comment
> Note: In public repositories this action does not work in pull_request workflows when triggered by forks. Any attempt will be met with the error, Resource not accessible by integration. This is due to token restrictions put in place by GitHub Actions. Private repositories can be configured to enable workflows from forks to run without restriction. See here for further explanation. Alternatively, use the pull_request_target event to comment on pull requests.

Use `pull_request_target` instead for auto notify bot

---

cupy/_core/_kernel.pyx
tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py

Addresses https://github.com/cupy/cupy/pull/5410#issuecomment-871166101.
For example, `xp.arange(3, dtype=xp.int8).view(bool) + 4.5` matches `'dd->d'` in `xp.add.types` and generates
```diff
typedef double in0_type;
typedef double in1_type;
typedef double out0_type;
extern "C" __global__ void cupy_add__bool_float_float64(const CArray<bool, 1, 1, 1> _raw_in0, const double in1, CArray<double, 1, 1, 1> _raw_out0, CIndexer<1> _ind) {
;
CUPY_FOR(i, _ind.size()) {
_ind.set(i);
-        const in0_type in0(_raw_in0[_ind.get()]);
+        const in0_type in0(_raw_in0[_ind.get()] ? 1 : 0);
out0_type &out0 = _raw_out0[_ind.get()];
out0 = in0 + in1;
}
;
}
```
, where the cast of `in0` (from `'?'` to `'d'`) is fixed to return 0/1 value.
This PR does not change casts in ufunc outputs.  A workaround for …

Fix casts from bool in ufunc inputs

---

cupy/__init__.py
cupy/_binary/__init__.py
cupy/_core/core.pyx
cupy/_creation/__init__.py
cupy/_indexing/__init__.py
cupy/_io/__init__.py
cupy/_logic/__init__.py
cupy/_manipulation/__init__.py
cupy/_math/__init__.py
cupy/_padding/__init__.py
cupy/_sorting/__init__.py
cupy/_statistics/__init__.py
cupy/cuda/cupy_thrust.cu
cupy/linalg/__init__.py
docs/source/overview.rst
docs/source/reference/ndarray.rst
docs/source/reference/random.rst
docs/source/reference/sparse.rst
docs/source/user_guide/basic.rst

Replaced the old Scipy links by the new NumPy doc links, in almost all the files that needed this modification, as per issue #3418

Replaced the links for NumPy docs as per issue #3418

---

.mergify.yml

We started using GitHub's native auto-merge, so let's turn off the Mergify.
Native auto-merge works well even with GitHub Actions (due to security restrictions Mergify can't do auto-merge if GitHub workflow files are updated in base branch after submitting the PR).

Disable Mergify's auto-merge

---

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

API baseline of CuPy v9's is SciPy 1.6 so we have to test against it.
This was my fault in backport: #5413.

[v9] Fix scipy requirement

---

cupy/cuda/compiler.py
tests/cupy_tests/core_tests/test_raw.py

This is needed to allow things like running code generated with cuda 11.3 and run it in an older driver although the driver is marked as  "supported" by [nvidia](https://docs.nvidia.com/cuda/nvrtc/index.html#versioning):
> the more recent NVRTC library1. However, the more recent NVRTC library may generate PTX with a version that is not accepted by the CUDA Driver API functions of an older CUDA driver, as explained in the CUDA Compatibility document. 
Some approaches to resolving this issue:
Install a more recent CUDA driver that is compatible with the CUDA toolkit containing the NVRTC library being used.
Compile directly to SASS instead of PTX with NVRTC (see CUDA Compatibility document).
If we compile CuPy with cuda 11.3 and run it with an old driver, we will get the invalid PTX errors. …

Compile with SASS for CUDA versions >= 11.1

---

cupy/cuda/compiler.py

Follow up of #5097. The ROCm CI is currently not functioning because of this 😂
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/4066/

Fix the RTC call path for HIP

---

cupy_backends/cuda/api/runtime.pxd
cupy_backends/cuda/api/runtime.pyx
cupy_backends/hip/cupy_hip_runtime.h

The enums `cudaMemoryType` and `hipMemoryType` have a nonzero offset...🤦🏻‍♂️ Also, the struct members are ~~misaligned~~ mismatched.

Access `cudaMemoryType` in the pointer attributes and fix for HIP

---

.pfnci/config.pbtxt

It seems that SASS fix (#5097) increased the compilation time.
Previously, running all unit tests without cache took:
* `CUPY_TEST_FULL_COMBINATION=1` 3h53m (https://ci.preferred.jp/cupy.linux.cuda114/75345/)
* `CUPY_TEST_FULL_COMBINATION=0` 2h8m (https://ci.preferred.jp/cupy.linux.cuda114/75362/)
Now it takes more than 4h (`CUPY_TEST_FULL_COMBINATION=1`):
https://ci.preferred.jp/cupy.linux.cuda114/75868/

Increase timeout for CUDA 11.4 tests

---

cupy_backends/cuda/api/runtime.pxd
cupy_backends/cuda/api/runtime.pyx
cupy_backends/hip/cupy_hip_runtime.h

[backport] Access `cudaMemoryType` in the pointer attributes and fix for HIP 

---

.pfnci/linux/tests/_build_and_test.sh
.pfnci/linux/tests/_environment.sh

I noticed that CUDA 11.4 tests does not have SciPy/Cython installed.

Update tests to install all requirements and add PATH

---

cupy/_core/internal.pyx

Example: `ValueError: operands could not be broadcast together with shapes (2,) (3,)`
- lower case "operands"
- `' '.join` instead of `', '.join` shapes

Fix broadcast error messages

---

docs/source/reference/environment.rst

In a recent mpi4py PR (https://github.com/mpi4py/mpi4py/pull/66) @dalcinl mentioned this native support. We should use it too.

Use Sphinx's `envvar` construct

---

cupy/_core/__init__.py
cupy/_core/_kernel.pyx
cupy/_core/_routines_math.pxd
cupy/_core/_routines_math.pyx
cupy/_core/_ufuncs.py
cupy/_core/core.pyx
cupy/_manipulation/basic.py
cupy/_math/arithmetic.py
cupy/testing/_helper.py
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
tests/cupy_tests/manipulation_tests/test_basic.py
tests/cupy_tests/math_tests/test_arithmetic.py

This PR fixes #5527 and simplifies `elementwise_copy` (e.g. reverts #5410 except for the test).
See also #5539.

Fix casts in ufunc outputs

---

cupy_backends/cuda/api/runtime.pyx

`type` member has been added in CUDA 10.0. Have to use `memoryType` for CUDA 9.2 (or earlier or HIP).
Follow-up: #5571

[v9] Fix broken build on CUDA 9.2

---

docker/rocm/Dockerfile

GPG expired so `apt` stopped working in already-released Docker containers.

Reload GPG key for Docker images

---

cupy/random/_generator_api.pyx
cupy/random/cupy_distributions.cu
cupy/random/cupy_distributions.cuh
tests/cupy_tests/random_tests/common_distributions.py

This PR will add the support for array input in beta distribution of Generator.
Before:
```python
>>> rng = cp.random.default_rng()
>>> a = cp.array([1, 2, 1])
>>> b = cp.array([2, 1, 2])
>>> rng.beta(a,b)
TypeError: only size-1 arrays can be converted to Python scalars
```
After this PR:
```python
>>> rng = cp.random.default_rng()
>>> a = cp.array([1, 2, 1])
>>> b = cp.array([2, 1, 1])
>>> rng.beta(a, b)
array([0.49999993, 0.5       , 0.49999997])
```

Add support for array input in beta distribution of Generator

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Follow-up of #5331. Looks like both CSC and CSR matrices do not work for the moment.

Mark `lsmr` tests xfail for CSR matrices on HIP

---

cupy/cusolver.pyx
cupy/linalg/_decomposition.py
cupy/linalg/_util.py
cupy_backends/cupy_lapack.h
cupy_backends/stub/cupy_cusolver.h
tests/cupy_tests/linalg_tests/test_decomposition.py

Close #4986.
To prepare for the upcoming NumPy 1.22 (https://github.com/numpy/numpy/pull/19151) and the Array API standard.
**UPDATE**: I made some educated guesses about zero-size input. But before NumPy 1.22 is out so that we can actually test all corner cases the validity remains to be seen. As a result, I require those tests to be run on NumPy 1.22+, and added an experimental warning if batching is in use.
TODO:

Support batched QR solver

---

.pfnci/linux/tests/_build_and_test.sh

The following test takes 5.5 min (in my environment) and times out, when `CUPY_TEST_FULL_COMBINATION=1` is set.
```
FAILED cupy_tests/math_tests/test_arithmetic.py::TestUfunc::test_casting_out_unsafe 
```
https://ci.preferred.jp/cupy.linux.cuda114/76501/

Increase test timeout

---

cupy/random/_generator_api.pyx
cupy/random/cupy_distributions.cu
cupy/random/cupy_distributions.cuh
tests/cupy_tests/random_tests/common_distributions.py
tests/cupy_tests/random_tests/test_generator.py
tests/cupy_tests/random_tests/test_generator_api.py

This PR adds log series distribution to Generator.
Following is the performance comparison on GTX1050.
size(nrows * ncols) | numpy (sec) | cupyx (sec)
---|---|---
10000 * 1 | 0.000 | 0.000
12000 * 1 | 0.000 | 0.000
15000 * 1 | 0.001 | 0.000
20000 * 1 | 0.001 | 0.000
10000 * 1000 | 0.381 | 0.044
12000 * 1000 | 0.468 | 0.056
15000 * 1000 | 0.622 | 0.058
20000 * 1000 | 0.795 | 0.095
10000 * 2000 | 0.788 | 0.081
12000 * 2000 | 0.949 | 0.093
15000 * 2000 | 1.194 | 0.123
20000 * 2000 | 1.643 | 0.155
10000 * 3000 | 1.231 | 0.116
12000 * 3000 | 1.507 | 0.140
15000 * 3000 | 2.034 | 0.174
20000 * 3000 | 3.184 | 0.231
<details>
<summary>script</summary>
```python
import cupyx
n_repeat = 2
n_warmup = 1
crng = cp.random.default_rng()
nrng = np.random.default_rng() …
```

Add Log Series distribution to Generator

---

cupy/cuda/compiler.py
docs/source/reference/environment.rst
tests/cupy_tests/core_tests/test_raw.py

Seems like SASS (CUBIN) increases compilation times in a non-negligible amount (specially when running the test-suite).
Adds `CUPY_COMPILE_WITH_PTX` env var to explicitly request the older behavior.

Allow to compile using PTX with an envvar

---

.pfnci/linux/tests/rocm-4-2.Dockerfile

ROCm 4.2 test stopped working as GPG key in Docker image expired.

Reload GPG key for ROCm 4.2 test

---

install/build.py

When no GPUs are available and ``CUPY_NVCC_GENERATE_CODE=current`` is set, invalid CC is printed (I got `--generate-code=arch=compute_211033746432543,code=sm_211033746432543`).

Fix compute capability check

---

.pfnci/linux/tests/cuda11x-cuda-python.sh

Branch name seems changed from `master` to `main` 😅

Fix branch name of cuda-python

---

cupy/cublas.py
cupy/linalg/_decomposition.py
cupy/linalg/_eigenvalue.py
cupy/linalg/_norms.py
cupy/linalg/_product.py
cupy/linalg/_solve.py
cupy/linalg/_util.py
cupyx/lapack.py
cupyx/linalg/_solve.py
cupyx/linalg/sparse/_solve.py
cupyx/scipy/linalg/decomp_lu.py
cupyx/scipy/sparse/csgraph/_traversal.py
cupyx/scipy/sparse/linalg/_solve.py

Fix bugs caused by the fact that `_assert_nd_squareness` does not assert the inputs are at least 2d.
```
>>> for xp in (numpy, cupy):
...  try: xp.linalg.cholesky(xp.ones(()))
...  except Exception: traceback.print_exc(limit=0)
...
numpy.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional
ValueError: max() arg is an empty sequence
>>> for xp in (numpy, cupy):
...  try: xp.linalg.eigh(xp.ones(()))
...  except Exception: traceback.print_exc(limit=0)
...
numpy.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional
ValueError: Array must be at least two-dimensional
```
`scipy.sparse.csgraph`, on the other hand, should not raise `LinAlgError`.
```
>>> scipy.sparse.csgraph.connected_components(numpy.ones((3, 2)))
ValueError: graph …
```

Fix squareness checks

---

docs/source/user_guide/interoperability.rst

__array_function__ is not an experimental feature anymore.
Changed `note that this is currently defined as an experimental feature of NumPy and you need to specify the environment variable (NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1) to enable it.`
to  `As of NumPy 1.17,  __array_function__ is enabled by default.`

`__array_function__` feature by default

---

.pfnci/linux/tests/rocm-4-3.Dockerfile

See https://github.com/cupy/cupy/issues/5592#issuecomment-901136342.
This PR adds a workaround for ROCm 4.3 CI.

Add a workaround for ROCm 4.3.0 for testing

---

cupy/random/_generator_api.pyx
tests/cupy_tests/random_tests/common_distributions.py
tests/cupy_tests/random_tests/test_generator.py
tests/cupy_tests/random_tests/test_generator_api.py

This PR adds Dirichlet distribution to Generator.
Following is the performance comparison on GTX1050.
(The comparison was done only for flattened shape as numpy does not support multi-dimension alpha as input)
size | numpy | cupy 
---|---|---
10000 | 0.001 | 0.001
12000 | 0.002 | 0.001
15000 | 0.002 | 0.001
25000 | 0.002 | 0.001
10000000 | 0.562 | 0.305
12000000 | 0.665 | 0.367
15000000 | 0.830 | 0.459
20000000 | 1.106 | 0.623
24000000 | 1.327 | 0.736
25000000 | 1.381 | 0.764
30000000 | 1.785 | 0.962
36000000 | 2.018 | 1.110
45000000 | 2.639 | 1.439
50000000 | 2.798 | 1.579
75000000 | 6.607 | 2.456
<details>
<summary>script</summary>
```python
import cupyx
n_repeat = 2
n_warmup = 1
crng = cp.random.default_rng()
nrng = np.random.default_rng()
def …
```

Add Dirichlet distribution to Generator

---

cupy/random/_generator_api.pyx
tests/cupy_tests/random_tests/common_distributions.py
tests/cupy_tests/random_tests/test_generator.py
tests/cupy_tests/random_tests/test_generator_api.py

This PR add F distribution to Generator.
Following is the performance comparison on GTX1050.
size(nrows * ncols) | numpy | cupy 
--- | --- | ---
10000 * 1 | 0.001 | 0.001
12000 * 1 | 0.001 | 0.001
15000 * 1 | 0.002 | 0.001
10000 * 1000 | 0.971 | 0.293
12000 * 1000 | 1.158 | 0.348
15000 * 1000 | 1.448 | 0.432
10000 * 2000 | 1.939 | 0.624
12000 * 2000 | 2.382 | 0.698
15000 * 2000 | 3.063 | 0.868
10000 * 3000 | 3.158 | 0.867
12000 * 3000 | 5.043 | 1.071
15000 * 3000 | 5.187 | 1.303
<details>
<summary>script</summary>
```python
import cupyx
n_repeat = 2
n_warmup = 1
crng = cp.random.default_rng()
nrng = np.random.default_rng()
def get_time(perf):
cpu_time = perf.cpu_times.mean()
gpu_time = perf.gpu_times.mean()
return max(cpu_time, gpu_time)
def run(dfn, …
```

Add F distribution to Generator

---

cupy/fft/_fft.py
tests/cupy_tests/core_tests/fusion_tests/fusion_utils.py
tests/cupy_tests/core_tests/test_raw.py
tests/cupy_tests/cuda_tests/test_compiler.py
tests/cupyx_tests/jit_tests/test_raw.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py

Succeeding #5657. Rel #5592, especially https://github.com/cupy/cupy/issues/5592#issuecomment-900813721.
This PR fixes version checks for the new ROCM version definition. I looked up all the lines to fix by:
```
$ find . -name '*.py' -or -name '*.pyx' | xargs grep 'runtimeGetVersion\|driverGetVersion\|get_build_version' -n`
```

Rest of version check fix for new ROCm version definition

---

tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py

Fix Typo in https://github.com/cupy/cupy/pull/2286#issuecomment-508328266 (`raise unittest.SkipTest()` is OK).  #5463 found this.
However, the fix keeps the test result (= pass), because `for_dtypes` does not propagate skips.
Notes:
- `unittest.skipTest` and `return` are equivalent inside `for_dtypes`, except for the debug message.
- `for_dtypes` catches `_skip_classes` because `numpy_cupy_*` propagates skips.  (This explanation is different than #1757.)
- Other loop helpers (e.g. `for_orders`) short-circuit skips, which may be error-prone.

Fix `skipTest` in `test_decomp_lu`

---

tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

Following up #5693.
This PR marks `TestSplineFilter1dLargeArray` slow as well as reducing its memory usage. Now it uses ~2GB of memory.

`TestSplineFilter1dLargeArray` marked slow and reduced memory usage

---

cupy/testing/_helper.py
tests/cupy_tests/manipulation_tests/test_basic.py

Methods of non-`unittest.TestCase` classes are supported since #4304.
An example of usage is in `tests/cupy_tests/manipulation_tests/test_basic.py`.

Make testing helpers support non-methods

---

.pfnci/windows/test.ps1

Default setuptools in Windows CI environment seems outdated (detected in CI of #5730: https://ci.preferred.jp/r/job/78702)

Update pip and setuptools in Windows CI

---

.github/workflows/backport.yml

Backport should be triggered only when the label added is `to-be-backported`.
This avoids backport to retrigger when labels other than `to-be-backported` is added to a already-closed PR with `to-be-backported` label, e.g., https://github.com/cupy/cupy/pull/5735#issuecomment-916625858

Fix backport trigger

---

cupy/_util.pyx
cupy/cuda/cufft.pxd
cupy/cuda/memory.pyx
cupy/fft/_callback.pyx
cupy_backends/cuda/api/_driver_extern.pxi
cupy_backends/cuda/api/_runtime_enum.pxd
cupy_backends/cuda/api/_runtime_typedef.pxi
cupy_backends/cuda/api/driver.pyx
cupy_backends/cuda/api/runtime.pyx
cupy_backends/cuda/libs/nvrtc.pyx
install/cupy_builder/cupy_setup_build.py

Preparing for #5723. See #5696.
This PR makes all of Cython's `compile_time_env` entries prefixed with `CUPY_` to keep off conflicts as CUDA Python's `CUDA_VERSION`.

Prefix Cython `compile_time_env` with `CUPY_`

---

cupyx/fallback_mode/fallback.py
tests/cupyx_tests/fallback_mode_tests/test_fallback.py

I was fixing a test code to support pytest-xdist but it seems the original TestDocs test is not working as expected.
context: https://github.com/cupy/cupy/pull/5659/files#r691093294

Fix docstring for fallback modules

---

.pfnci/linux/tests/cuda114.Dockerfile
cupyx/tools/install_library.py
docs/source/install.rst

Backport of #5734 by @takagi
Docker image rebuild: https://ci.preferred.jp/cupy.prep-linux/78968/
Trigger FlexCI after the rebuild complete.

[backport] Support NCCL 2.11.4

---

install/cupy_builder/__init__.py
install/cupy_builder/_preflight.py
setup.py

context: #5722, #5730, #5743
This also adds a message to take care of the source tarball is downloaded from GitHub.
Depends on ~#5743~ (merged)

Reorganize build scripts, part 3: simplify `setup.py`

---

install/cupy_builder/_context.py
install/cupy_builder/cupy_setup_build.py
setup.py
tests/install_tests/__init__.py
tests/install_tests/test_cupy_builder/test_context.py

context: #5722, #5730, #5743, #5745
Remove the global variable `cupy_setup_options`.
Recommends commit-by-commit review.

Reorganize build scripts, part 4: remove global `cupy_setup_options`

---

setup.py

Adding `maintainer` meta data to credit all contributors working on CuPy :smile:
This will be displayed under `Meta` section on PyPI. NumPy's example: https://pypi.org/project/numpy/

Add maintainers in `setup.py`

---

install/cupy_builder/cupy_setup_build.py

context: #5722, #5730, #5743, #5745, #5754
As Cython is now in `setup_requires`, version check is no longer necessary.
Depends on #5754

Reorganize build scripts, part 5: remove Cython version check

---

cupyx/optimizing/_optimize.py
tests/cupyx_tests/test_optimize.py

Previously `cupyx.optimize` context manager does not save a file when no optimization run within the scope.
I think it is better to save an empty result instead to make the behavior consistent.
This PR also fixes the issue that `cupyx.optimize` tests fail when CUB acceleartor is enabled.

Fix `cupyx.optimize` to save file when no optimization ran

---

cupy/_binary/packing.py
tests/cupy_tests/binary_tests/test_packing.py

This PR is about this issue: https://github.com/cupy/cupy/issues/5762

Adding 'bitorder' support to `cupy.unpackbits` 

---

cupyx/scipy/sparse/csr.py

There is a typo on line 334 which raises TypeError message
```
expected scalar, dense matrix/vector or csr matrixr
```
This corrects the typo to
```
expected scalar, dense matrix/vector or csr matrix
```

Fixed typo in error message in sparse.csr_matrix

---

.github/workflows/auto-cc.yml

Adding array-api notification to @asmeurer :tada:
https://github.com/cupy/cupy/pull/5698#issuecomment-915733273
The workflow is tested here: https://github.com/kmaehashi/sandbox/issues/12

Update auto-notify bot for array-api label

---

tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py

Automatically skip tests when hitting this condition:
https://github.com/cupy/cupy/blob/6071fc769486ce0209c6760215c3ecba64ba9e84/cupyx/scipy/fft/_fft.py#L508-L509
Jenkins uses P100, so it fails when testing with CUDA 10.2.

Skip tests for bug cases (FFT on CUDA 10.2 + Pascal)

---

cupy/cusparse.py

Test failure detected in https://github.com/cupy/cupy/pull/5770 (https://ci.preferred.jp/cupy.win.cuda102/79678/)
cuSPARSE Generic APIs are not available on Windows + CUDA 10.2.
> LIMITATION: The generic APIs are currently available for all platforms except Windows. Using these APIs in any other systems will result in compile-time or run-time failures. Their support will be extended in the next releases.
https://docs.nvidia.com/cuda/archive/10.2/cusparse/index.html#cusparse-generic-api-reference

Disable spmm on Windows CUDA 10.2

---

tests/cupy_tests/core_tests/test_ndarray.py

Follows-up #5749
```
NumPy 1.18
AttributeError: incompatible shape for a non-contiguous array
NumPy 1.19
AttributeError: Incompatible shape for in-place modification. Use `.reshape()` to make a copy with the desired shape.
```

Fix error message comparison

---

tests/cupy_tests/manipulation_tests/test_join.py

Preparing for #5759.
`@pytest.mark.parametrize` does not seem to work with methods of test classes deriving from `unittest.TestCase`. To use it, this PR fixes `TestJoin` to be pytest-based instead of unittest.

Use pytest in `TestJoin`

---

tests/cupy_tests/fft_tests/test_fft.py

Partially fix #5329.
Currently, `TestFftAllocate.test_fft_allocate` places a FFT plan to the plan cache in its `cupy.fft.fft` call. However, the cached plan (3GB+) is still being grabbed after returning from the test, which eventually causes OOM in another test that requires large memory. This PR fixes the test to clear the plan cache before it returns.

Clean up plan cache in a FFT slow test

---

.pfnci/linux/tests/_build_and_test.sh

It seems that recently CI hangs for some reason.
https://ci.preferred.jp/cupy.linux.cuda114/
https://ci.preferred.jp/cupy.linux.cuda11x-cuda-python/
(Some timeout after running ``6h00m`` hard limit)
I haven't identified the root cause yet, but I'd like to disable recently-introduced pytest-xdist to isolate the issue.

Tentatively disable pytest-xdist

---

docs/source/upgrade.rst

Closes #5766
Refs #5818 (keeping this issue open as this PR is not covering all changes in v10)
Auto-backport to v9 should fail, I'll take care of it.

Update upgrade guide

---

cupyx/_runtime.py

This makes it possible to verify CuPy installation without GPU (although CUDA/ROCm is still required.)
The output would look like this:
```py
>>> cupy.show_config()
OS                        : Linux-4.15.0-153-generic-x86_64-with-glibc2.27
Python Version            : 3.9.5
CuPy Version              : 10.0.0b3
CuPy Platform             : NVIDIA CUDA
NumPy Version             : 1.21.2
SciPy Version             : 1.7.1
Cython Build Version      : 3.0.0a9
Cython Runtime Version    : 3.0.0a9
CUDA Root                 : /usr/local/cuda-11.4.1
nvcc PATH                 : ccache nvcc
CUDA Build Version        : 11040
CUDA Driver Version       : 11040
CUDA Runtime Version      : CUDARuntimeError('cudaErrorNoDevice: no CUDA-capable device is detected')
cuBLAS Version            : (available)
cuFFT …
```

Make `show_config` runnable without GPU

---

cupy/_core/_routines_manipulation.pxd
cupy/_core/_routines_manipulation.pyx
cupy/_manipulation/join.py
tests/cupy_tests/manipulation_tests/test_join.py

Close #5700. Blocked by #5764.

Add `dtype` and `casting` arguments to `cupy.concatenate()`

---

.pfnci/generate.py
.pfnci/linux/tests/actions/_environment.sh
.pfnci/linux/tests/rocm-4-0.sh
.pfnci/linux/tests/rocm-4-2.sh
.pfnci/linux/tests/rocm-4-3.sh

Currently ROCm tests for branches in Jenkins is unstable.
This PR makes parameterization for branch tests sparse (i.e., reduce number of combinations to that of pull-request tests) to resolve this issue.
https://jenkins.preferred.jp/job/chainer/job/cupy_master/
https://jenkins.preferred.jp/job/chainer/job/cupy_stable/

CI: Do not run full combination test even for branch tests for ROCm

---

cupy/_core/core.pyx
cupy/_core/dlpack.pyx
cupy/_manipulation/basic.py
cupy/array_api/_array_object.py
cupy/array_api/_creation_functions.py
cupy/cuda/cufft.pyx
cupy/cuda/device.pyx
cupy/cuda/memory.pyx
cupy/fft/_cache.pyx
cupyx/profiler/_time.py

Fixes #5943
Do not use the context manager since mixing it with internal calls will mess the user set device.

Dont use `with device` in code base

---

docs/requirements.txt
docs/source/conf.py

Closes #5949 
* Added the dependency to `docs/requirements.txt`
* Added the extension in `docs/source/conf.py`
* Added configurations for Copybutton to:
* Ignore lines without input prompts if input prompts are present
* Copy multiline commands when lines end with `\`
Please find the screenshot attached below. On the right is the built HTML documentation with the `sphinx-copybutton` extension enabled.

Add `sphinx-copybutton`

---

cupy/_core/__init__.py
cupy/_core/_accelerator.pxd
cupy/_core/_accelerator.pyx
cupy/_core/_kernel.pxd
cupy/_core/_kernel.pyx
cupy/_core/_routines_math.pyx
cupy/_math/misc.py
cupy/cutensor.pyx

Closes #5776.
This PR also fixes the issue in `cupy.cutensor.elementwise_binary` that the wrong mode is used for `C` (the second argument).

Support using cuTENSOR in elementwise ufuncs

---

cupy/_core/core.pyx
cupy/_util.pyx

My mistake, I didn't double check that the format was aligned to other env vars.

Make `CUPY_DLPACK_EXPORT_VERSION` consistent

---

cupy/_core/_routines_manipulation.pyx
cupy/_core/internal.pyx

Close #4496.
Notes:
- `cupy_tests/manipulation_tests/test_dims.py::TestDims::test_expand_dims_repeated_axis` already checks `pytest.raises(ValueError)`, but (raised) `numpy.AxisError` is a subclass of (expected) `ValueError` (and `IndexError`).
- `ValueError('Duplicate axes given.')` in `cupy.linalg.norm` is OK.

Fix error type/message for duplicate value in axis

---

cupy/_core/core.pyx
tests/cupy_tests/manipulation_tests/test_shape.py

Always enforce the copy if the array is neither c- or f-contiguous.
Closes #5972

Fix `ravel` for strides 0

---

cupy/_core/include/cupy/carray.cuh

Use `index_t` to calculate the address difference.
NVRTC generate faster code when `_use_32bit_indexing` is `True`

Use index_t for faster address calculation

---

cupyx/tools/install_library.py

Follows-up #5996.
Detected by CI failure: https://ci.preferred.jp/cupy-release-tools.win/83625/
Confirmed `python install_library.py --library cutensor --cuda 11.4` runs on WIndows.

Fix cuTENSOR installation on Windows

---

cupy/cuda/compiler.py

On CUDA 11.4 + driver 470.57 + A6000, I am seeing the following error in `test_raw.py`: 
```
$ pytest tests/cupy_tests/core_tests/test_raw.py 
...
cupy/cuda/compiler.py:582: in _compile_with_cache_cuda
mod.load(cubin)
cupy/cuda/function.pyx:264: in cupy.cuda.function.Module.load
cpdef load(self, bytes cubin):
cupy/cuda/function.pyx:266: in cupy.cuda.function.Module.load
self.ptr = driver.moduleLoadData(cubin)
cupy_backends/cuda/api/driver.pyx:192: in cupy_backends.cuda.api.driver.moduleLoadData
check_status(status)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   raise CUDADriverError(status)
E   cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation …
```

Fix: Allow generating cubins for the max known CC

---

.github/workflows/pretest.yml

This reduces the build time from 3~4 minutes to ~1 minute.
First run: https://github.com/cupy/cupy/runs/4130095842 (3m9s)
Second run: https://github.com/cupy/cupy/runs/4130153202 (46s)

CI: Use `ccache` in Pre-review Test

---

cupy/cuda/compiler.py

Regression in #5988. Kernel cache was not used at all because hexdigest length changed from 32 (MD5) to 40 (SHA1).
This PR removes the magic number.
When writing a kernel cache file, CuPy prepends a checksum (hexdigest hash string) before the actual cubin data. However, the checksum length was hard-coded to 32, causing checksum validation to always fail.

Fix hash length for SHA1

---

.pfnci/config.pbtxt

Fix https://ci.preferred.jp/cupy.linux.cuda115/84064/

[v9] CI: Increase timeout for CUDA 11.4 / 11.5 tests

---

.pfnci/linux/tests/actions/_environment.sh

This was a regression in #5881.
When src directory is copied, compiler command line always include a random path, preventing ccache to reuse the cache.
This PR sets the source root as a ccache basedir to let ccache omit the dir from hash calculation.
https://ccache.dev/manual/4.4.2.html#_configuration_options
> base_dir (CCACHE_BASEDIR)
> ...
> ccache will rewrite absolute paths into paths relative to the current working directory, but only absolute paths that begin with base_dir. Cache results can then be shared for compilations in different directories even if the project uses absolute paths in the compiler command line.

CI: Fix ccache not working

---

.pfnci/config.pbtxt
.pfnci/flexci_test_tag.py
.pfnci/linux/main-flexci.sh

This PR adds a feature to run FlexCI tests selectively, based on the tags assigned to each FlexCI project.
For example:
* `/test mini` to run tests tagged with `mini`
* `/test example,rapids` to run tests tagged with `example` or `rapids`
`/test` runs all tests regardless of tags.
We may also need to discuss review criteria (e.g., what kind of PRs can be merged without "all" tests).

CI: allow running tests selectively

---

cupyx/_runtime.py

When cuDNN preload can be attempted (i.e., installed via wheel AND `import cupy.cuda.cudnn` is not performed yet), `show_config` should behave as follows:
* If `full` mode is requested, preload cuDNN immedeately and show the version. Output would be either the actual version, or None (if cuDNN is unavailable).
* If `full` mode is not requested, try to get cuDNN version without preloading. Output would be either the actual version, or 'not loaded' message.
This was a bug added by me in #5677

Fix cuDNN version not displayed in wheel installation

---

cupyx/distributed/_store.py

``setDaemon`` is deprecated and now emits a warning in Python 3.10.
https://ci.preferred.jp/cupy.linux.cuda114/85040/

Fix distributed test failure

---

cupyx/scipy/fft/__init__.py

`next_fast_len` should be a public API, but imported `__all__` shadows it from `cupyx.scipy.fft`.

Fix `__all__` in `cupyx.scipy.fft`

---

docs/source/_comparison_generator.py

~This hides several APIs that are unexpectedly exposed, by using `__all__`.~
~https://gist.github.com/kmaehashi/8e89e6cfd863a4bc0746b90c3467b795~
~Depends on #6071~
See discussion below.

Exclude `kernel_version` from comparison table

---

cupy/testing/_attr.py

Closes #5912.
Now tests can be run selectively using `pytest -m pytest -m "multi_gpu"` or `pytest -m pytest -m "not multi_gpu"`.

Fix `testing.multi_gpu` to add pytest marker

---

cupy/_core/dlpack.pyx

To ease diagnosing failure like this:
```py
cupy.from_dlpack(torch.arange(10))
```

Raise better message when importing CPU array via DLPack

---

cupy/_core/_carray.pxd
cupy/_core/_carray.pyx
cupy/_core/_kernel.pyx
cupy/_core/include/cupy/carray.cuh

Current CuPy elementwise generate 64bit division code.
1. For loop unrolling. 
2. For large indexing. (generate but not used. CUDA kernel register consumption increases.) 
For 1
benchmark code
```
import cupy
size = 1024
a = cupy.ones((size, size))
for i in range(10):
a * a
```
| | #register |  time[usec]
| - | - | - |
| before | 21 | 18 |
| after | 18 | 18 |
For 2
benchmark code
```
import cupy
size = 1024
b = cupy.broadcast_to(cupy.ones((size, 1)), (size, size))
for i in range(10):
b * b
```
| | #register |  time[usec]
| - | - | - |
| before | 28 | 25 |
| after | 24 | 25 |

Avoid 64bit division for reduce register consumption

---

.pfnci/linux/main-flexci-prep.sh
.pfnci/linux/main-flexci.sh
.pfnci/linux/run.sh

* Retry gsutil download as cache download may fail during other test uploading cache.
* Do `gcloud auth` outside of `run.sh` script to avoid configuring twice. (this is harmless but verbose)
* Improve message (show size of cache file, make docker push quiet).

Improve FlexCI test scripts

---

cupy/__init__.py
cupy/_math/sumprod.py
docs/source/reference/math.rst
tests/cupy_tests/math_tests/test_sumprod.py

Hi!
This PR adds a version of trapz as requested in https://github.com/cupy/cupy/issues/6078. This is my first contribution here, I hope it's the expected format/sufficiently tested and documented.
I've been using a version of this in [code for gravitational-wave astronomy](https://github.com/ColmTalbot/gwpopulation/blob/master/gwpopulation/cupy_utils.py#L49) for a while.

Add `cupy.trapz`

---

.pfnci/linux/tests/actions/unittest.sh

For some reason sometimes ROCm hangs here. To make it detectable set a timeout.

CI: Add timeout to show_config

---

cupy/cuda/compiler.py

`distutils` in Python 3.10 emits a warning. This PR replaces `distutils` use in CuPy codebase with `setuptools`.

Replace `distutils` with `setuptools` in Windows `cl.exe` detection

---

install/cupy_builder/cupy_setup_build.py

In many cases we may want to combine cupy with other frameworks (like pytorch or TensorRT).
when using pytorch and cupy together, since both of them compiled with cub/thrust, there would be a conflict with the static variable.  this may result cuda runtime error (when calling both cupy.argsort and torch.argsort in the same process) or stuck (it's hard to reproduce the stuck behavior here since this happens in my unittest).
this PR fixes this issue and cupy can work well with other frameworks.
the related issue may be #2409.
for detail you can see that https://github.com/NVIDIA/thrust/issues/1401#issuecomment-806403746

compile cub/thrust with no unique symbol

---

.pfnci/coverage.md
.pfnci/generate.py
.pfnci/linux/tests/cuda111.multi.Dockerfile
.pfnci/linux/tests/cuda112.multi.Dockerfile
.pfnci/matrix.yaml

Backport of #6037 by @kmaehashi
Also fixes the issue that Dockerfiles are not regenerated.

[backport] CI: add link to ROCm projects in CI coverage matrix

---

cupy/_core/_routines_indexing.pyx
cupy/_manipulation/basic.py
tests/cupy_tests/core_tests/test_ndarray_indexing.py
tests/cupy_tests/manipulation_tests/test_basic.py

Fix #5848.
[As a special case for backwards compatibility](https://github.com/numpy/numpy/blob/v1.21.4/numpy/core/src/multiarray/array_assign_array.c#L358), NumPy's broadcasting rule is more permissive in `copyto(dst, src, ...)` and `dst[indices] = src`.

Allow leading unit dimensions in copy source

---

cupy/_math/explog.py
tests/cupy_tests/math_tests/test_explog.py

Handles infinities of the same sign in `logaddexp` and `logaddexp2`

---

cupy/cublas.py
cupy/linalg/_solve.py
tests/cupy_tests/linalg_tests/test_solve.py

#6160
This PR fixes `linalg.solve` and `linalg.inv` for empty inputs.  As a consequence, `linalg.tensorsolve` and `linalg.tensorinv` are fixed, too.

Fix empty `solve`

---

.github/workflows/pretest.yml
.pfnci/linux/tests/actions/cleanup.sh

Further limit cache size to reduce upload/download/creation/extraction time.
* Default limit of ccache is 5GB but it was too large to keep CuPy build cache.
* Also adjust CuPy kernel cache size limit.

CI: Update limits to reduce cache size

---

cupy/_core/_routines_linalg.pyx
cupy/linalg/_product.py
tests/cupy_tests/math_tests/test_matmul.py

The current implementation incurs extra memory consumption and memory copy in matmul operation. This PR solves it.

Remove memory copy in matmul

---

cupy/__init__.py

Test with NumPy 1.22.0rc1 failed:
https://ci.preferred.jp/cupy.linux.cuda-head/87655/
This is because `np.MachAr` has been deprecated (https://github.com/numpy/numpy/pull/20201)

Deprecate MachAr (support NumPy 1.22)

---

tests/cupyx_tests/fallback_mode_tests/test_fallback.py

Test with pre-release failed:
https://ci.preferred.jp/cupy.linux.cuda-head/87777/

Support pre-release NumPy version in tests

---

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

Follow-up of #6046. Close #6057. 
Verified that the added tests would fail on CuPy v9.6 (as #6046 was not backported) but not on the `master` branch.

Add tests for `convolve2d`

---

docs/source/install.rst

I made some minor changes to the installation guide. The biggest change among them is the removal of the mention of pre-release versions on conda-forge. The reason is 2-fold:
- the download counts of pre-release packages are awfully low 
- I no longer have the bandwidth to maintain an extra `rc` branch in the feedstock

Update conda-forge installation guide

---

cupy/_core/core.pyx

I should have written the TODO comment more precisely in [this commit](https://github.com/cupy/cupy/pull/4198/commits/a829c8d0adce0c6b22504631eeb9cba8078b1493).
Fix #4118 on `__matmul__`.
```
>>> import dask.array as da
>>> cupy.ones((3, 4)) @ da.ones_like(cupy.empty((4, 2)))
dask.array<reshape, shape=(3, 2), dtype=float64, chunksize=(3, 2), chunktype=cupy.ndarray>
```

Fix #4675 on resolving TODO in #4198

---

cupy/linalg/_eigenvalue.py

Amends #6178.
The line is missed in fixing https://github.com/cupy/cupy/pull/6178#pullrequestreview-820522255

Eigenvalue solver 64bit API on CUDA 11.1

---

docs/source/conf.py

Unwrap functions wrapped by `contextmanager` to fix `[source]` deadlink, e.g.:
* https://docs.cupy.dev/en/v10.0.0rc1/reference/generated/cupy.cuda.using_allocator.html?highlight=[source]
* https://docs.cupy.dev/en/v10.0.0rc1/reference/generated/cupyx.optimizing.optimize.html?highlight=[source]
Add `[source]` link to objects defined in C-extensions, e.g.:
* https://docs.cupy.dev/en/v10.0.0rc1/reference/generated/cupy.cuda.Device.html

Docs: Update linkcode implementation

---

cupy/_creation/basic.py
tests/cupy_tests/creation_tests/test_basic.py

Fix edge case compatibility in `cupy.eye()`

---

docs/source/install.rst

A quick fix on a typo in the nvcc compiler flag and the `gcc` executable, as there is no `gcc-7` or similar in CentOS, unlike Ubuntu which all get symlinked. After installing the `devtoolset-7-gcc-c++` and activating those binaries, calling `gcc` will use the `gcc` at version 7 for compilation.

Docs: CentOS installation from source

---

cupy/linalg/_solve.py

Follow-up of #3942. Looks like the QR-based helper function `_solve()` is no longer used anywhere in the codebase.

Remove legacy `cp.linalg.solve()` implementation

---

cupy/linalg/_eigenvalue.py
tests/cupy_tests/linalg_tests/test_eigenvalue.py

Fix `linalg.eigh` and `linalg.eigvalsh` on empty inputs

---

cupy/_math/sumprod.py

Following up #6107. Minor fixes for the docstring of `cupy.trapz()`.

Fix `cupy.trapz` docstring

---

cupy/_statistics/order.py
tests/cupy_tests/statistics_tests/test_order.py

Partially fix #6198.
`percentile` and `quantile`'s `interpolation` parameter is renamed to `method` in NumPy 1.22, and some new interpolation methods are introduced as well. In this PR, I cover the change in the parameter name only to support NumPy 1.22, and will open another issue to implement the newly introduced methods.

Change a parameter name in `percentile` and `quantile` to support NumPy 1.22

---

cupy/_core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py

Fix #5715.
This PR implements comparisons to Python's built-in constants, `None` and `Ellipsis`. It returns a ndarray filled with `True` or `False` with the same shape as the ndarray as if the operation is performed elementwise.

Support comparison to `None` and `Ellipsis`

---

tests/cupy_tests/statistics_tests/test_order.py

Partial backport of #6228, containing test refactoring and DeprecationWarning skip only.

[backport] Change a parameter name in `percentile` and `quantile` to support NumPy 1.22

---

.pfnci/windows/test.ps1

`setuptools==60.*` and `numpy.distutils` from `numpy==1.21.*` conflicts on Windows, as setuptools now uses vendored distutils by default.
https://setuptools.pypa.io/en/latest/history.html#v60-0-0

Tentatively pin to `setuptools<60` in Windows CI

---

cupy/cusolver.pyx
cupy/linalg/_decomposition.py
tests/cupy_tests/linalg_tests/test_decomposition.py

Fix `cupy.linalg.qr` to align with NumPy 1.22

---

.github/workflows/pretest.yml

I noticed that we should update `actions/cache` key for every commit, otherwise cahce will never be updated...
https://github.com/cupy/cupy/runs/4648731921?check_suite_focus=true
> Post Load ccache
> Post job cleanup.
> Cache hit occurred on the primary key ccache, not saving cache.
This PR changes to use the commit hash as a primary key, and falls back to the base branch's commit hash for pull-requests.

Fix cache key for github actions

---

cupy/cuda/stream.pyx
tests/cupy_tests/cuda_tests/test_stream.py

Close #6243. Because `stream_ptr` is an int, `hash(stream_ptr)` is equal to `stream_ptr` and there is no point to do the former. This actually allows a very simple implementation as `__eq__` does not need to be modified at all.

Make streams hashable

---

cupy/cuda/stream.pyx

Follows-up: #6285
This fixes the following failure (https://github.com/cupy/cupy/issues/6243#issuecomment-994672793):
```py
>>> x = {cupy.cuda.Stream.null: 100, 0: 200}
File "cupy/cuda/stream.pyx", line 209, in cupy.cuda.stream._BaseStream.__eq__
return self.ptr == other.ptr
AttributeError: 'int' object has no attribute 'ptr'
```

Check isinstance before comparison in ``__eq__``

---

cupy/array_api/_array_object.py
tests/cupy_tests/array_api_tests/test_array_object.py

Stay in sync with NumPy here: https://github.com/numpy/numpy/commit/eb865fa4683bca9a9d7c840f8addd30e39b62f5b
Ports https://github.com/numpy/numpy/pull/20499 to `cupy.array_api`
CC @asmeurer

BUG: Fix the .T attribute in the `array_api` namespace

---

cupyx/scipy/fft/__init__.py
cupyx/scipy/fft/_fft.py
cupyx/scipy/fft/_realtransforms.py
docs/source/reference/scipy_fft.rst
tests/cupyx_tests/scipy_tests/fft_tests/test_realtransforms.py

This PR implements type II and III DCT and DST transforms. Since the corresponding real-to-real transforms are not implemented in cuFFT, the implementations here rely on manipulating the output of standard FFTs of equivalent length (see the references at the top of `_realtransforms.py` in this PR). This is a bit less efficient than if cuFFT supplied these transforms directly, but will still be fast relative to a CPU-based implementation. 
cc @IvanYashchuk for awareness

add discrete cosine and sine transforms to cupyx.scipy.fft

---

.pfnci/linux/main-flexci.sh

It seems CUDA Driver 510 cannot be reloaded without reboot?
```
[  238.136623] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  510.39.01  Fri Dec 31 11:03:22 UTC 2021
[  238.521491] NVRM: GPU 0000:00:04.0: RmInitAdapter failed! (0x63:0x55:2344)
[  238.522786] NVRM: GPU 0000:00:04.0: rm_init_adapter failed, device minor number 0
```

Tentatively pin to CUDA Driver 495

---

cupyx/scipy/special/__init__.py
cupyx/scipy/special/_xlogy.py
docs/source/reference/scipy_special.rst
tests/cupyx_tests/scipy_tests/special_tests/test_basic.py

This PR adds a couple of simple convenience functions to `cupyx.scipy.special`. This PR is built on top of #5687 to avoid conflicts with the changes to `__init__.py` made there. Only the last commit here is new.
cc @IvanYashchuk 
There is one deviation from SciPy in that the templated implementation here also has a single precision code path, while SciPy itself always promotes to double (see [here](https://github.com/scipy/scipy/blob/main/scipy/special/_xlogy.pxd) where `number_t` is a fused type made up of `double` and `complex<double>`). When testing locally the float32 code path was 4-5 times faster on large arrays.

add xlogy and xlog1py to cupyx.scipy.special

---

cupy/__init__.py
cupy/_indexing/generate.py
docs/source/reference/indexing.rst
tests/cupy_tests/indexing_tests/test_generate.py

Hi, Team!
The PR **aims** to add `cupy.tril_indices` and `cupy.tril_indices_from` API. It follows #6078.
Looking forward to your viewpoints :)
Thanks!
cc: @kmaehashi @takagi @leofang @asi1024  @toslunar

Add `tril_indices` and `tril_indices_from` API.

---

tests/cupy_tests/indexing_tests/test_generate.py

Follows up #6305.
This PR removes unused dtype parameterizing in `tril_indices` test.

Remove unused dtype parameterizing in `tril_indices` test

---

cupy/__init__.py
cupy/_io/formatting.py
docs/source/reference/io.rst
tests/cupy_tests/io_tests/test_formatting.py

Hello,
I recently came across the **CUPY** and found it interesting. I am excited and want to contribute to the cupy. 
I have implement the `cupy.format_float_positional` as requested in #6078,
looking for a review and further guidance.
Thank you.

added `cupy.format_float_positional`

---

cupy/__init__.py
cupy/_indexing/generate.py
docs/source/reference/indexing.rst
tests/cupy_tests/indexing_tests/test_generate.py

Hi,
The PR **aims** to add `cupy.triu_indices` and `cupy_indices_from` API's. It follows #6078.
Looking forward to your viewpoints.
Thanks!

Add `triu_indices` and `triu_indices_from` API.

---

cupyx/jit/_compile.py
tests/cupy_tests/functional_tests/test_vectorize.py

Fix https://github.com/cupy/cupy/issues/6223.
This PR fixes if-expr typing rule to infer the data type of constant value from the other side.

JIT: Fix if expr typing rule

---

cupyx/scipy/special/__init__.py
cupyx/scipy/special/_statistics.py
docs/source/reference/scipy_special.rst
tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py

This PR adds three very simple statistical functions to `cupyx.scipy.special`. This PR is built on top of #5687 to avoid conflicts with the changes to `__init__.py` made there. Only the last commit here is new.
cc @IvanYashchuk

add logit, expit and log_expit to cupyx.scipy.special

---

cupyx/jit/__init__.py
cupyx/jit/_builtin_funcs.py
cupyx/jit/_compile.py
cupyx/jit/_interface.py
tests/cupyx_tests/jit_tests/test_device_function.py

Close https://github.com/cupy/cupy/issues/5421.
Usage:
```py
import numpy
import cupy
@jit.rawkernel(device=True)
def getitem(x, tid):
return x[tid]
def elementwise_copy(x, y):
tid = jit.threadIdx.x + jit.blockDim.x * jit.blockIdx.x
y[tid] = getitem(x, tid)
x = testing.shaped_random((30,), dtype=numpy.int32, seed=0)
y = testing.shaped_random((30,), dtype=numpy.int32, seed=1)
elementwise_copy((5,), (6,), (x, y))
assert bool((x == y).all())
print(elementwise_copy.cached_code)
```
Output:
```cpp
__device__ int getitem_1(CArray<int, 1, true, true> x, unsigned int tid) {
return x[tid];
}
extern "C" __global__ void elementwise_copy(CArray<int, 1, true, true> x, CArray<int, 1, true, true> y) {
unsigned int tid;
tid = (threadIdx.x + …
```

JIT: Support `__device__` function

---

tests/cupyx_tests/fallback_mode_tests/test_notifications.py

`array_equiv` is going to be added in #6254.
Use `get_include`, which is unlikely to be added in CuPy, for fallback test.

Use `get_include` instead of `array_equiv` for fallback test

---

cupyx/tools/install_library.py

Follows-up: #6314
Slow test failed: https://ci.preferred.jp/cupy.linux.cuda-slow/91281/#L4316
Directory structure in cuDNN archive has been changed and installer was not working.

Fix cuDNN installer not working

---

cupyx/tools/install_library.py

Bug added in #6337.
In cuDNN Windows archive,
* `lib` directory only contains static libraries
* `bin` directory contains dynamic libraries (DLL) which are what we need

Fix for cuDNN directory structure in Windows

---

cupyx/jit/__init__.py
cupyx/jit/_compile.py
docs/source/user_guide/kernel.rst

Closes #6320.
This fixes source retrival of JIT to support IPython and notebook environment such as Jupyter.
When JIT is used under Python interpreter, it now recommends using IPython:
```
>>> a = cupy.array([0.4, -0.2, 1.8, -1.2])
>>> relu = cupy.vectorize(lambda x: (x > 0.0) * x)
>>> print(relu(a))
File "/home/maehashi/Development/cupy/cupy/_functional/vectorize.py", line 87, in __call__
result = func._emit_code_from_types(in_types, ret_type)
File "/home/maehashi/Development/cupy/cupyx/jit/_interface.py", line 38, in _emit_code_from_types
return _compile.transpile(
File "/home/maehashi/Development/cupy/cupyx/jit/_compile.py", line 138, in transpile
tree, source = _parse_function_object(func)
File …
```

Fix JIT to support notebook environment

---

cupyx/scipy/special/__init__.py
cupyx/scipy/special/_basic.py
cupyx/scipy/special/_gammainc.py
tests/cupyx_tests/scipy_tests/special_tests/test_basic.py

This PR addresses the following post-merge review comment: https://github.com/cupy/cupy/pull/5687#pullrequestreview-852497622
Thanks, @asi1024!
I benchmarked calling log1p on a vector with 10,000,000 elements both before and after this PR and performance was very similar either way. 
One question: 
It is a little suprising to me that float32 ends up running 6-7 times faster than float64 even though I there is no float32-specific code path.  Do any of you have insight into why this is? Does CuPy somehow use `log1pf` instead of `log1p` when the input is single precision? (I think I did find that some functions like `log` have complex support via Thrust, but wasn't sure if this also extends to single vs. double precision)

Use CUDA's log1p for cupyx.scipy.special.log1p

---

cupy/_core/core.pyx
tests/cupyx_tests/scipy_tests/special_tests/test_ufunc_dispatch.py

This PR makes it possible to pass CuPy arrays to `scipy.special` ufuncs. The actual implementation is dispatched to `cupyx.scipy.special` using `__array_ufunc__`.
Fixes https://github.com/cupy/cupy/issues/6158.

Make scipy.special ufuncs work with CuPy inputs

---

.pfnci/linux/main-flexci-prep.sh
.pfnci/linux/run.sh

This fix allows regenerating CI docker images manually.
The script can be triggered via FlexCI Web UI <https://ci.preferred.jp/cupy.prep-linux/>.
Currently we pin dependent library versions using wildcard:
https://github.com/cupy/cupy/blob/master/.pfnci/linux/tests/cuda-head.Dockerfile#L26
However as CI docker images are cached without expiry, tests won't be able to newer versions of these libraries (e.g., newer RC releases of NumPy/SciPy).

CI: allow discarding docker image cache manually

---

tests/cupy_tests/linalg_tests/test_eigenvalue.py

This PR addresses a problem that caused `eigh()` tests to fail in CUDA 11.6.
The current test for `eigh()` assumes that the results matches Numpy, but due to changes added to CUDA 11.6, or more precisely CUDA 11.6's cuSOLVER, the results does not necessarily match Numpy in the test cases. However, the CUDA 11.6 results are also mathematically correct, so we propose to change the way to test `eigh()`.
This is related to https://github.com/cupy/cupy/issues/6309 and depends on https://github.com/cupy/cupy/pull/6346.

Fix tests for eigh() for CUDA 11.6

---

cupyx/scipy/sparse/_index.py

This small change is to avoid a new `DeprecationWarning` I noticed when using SciPy 1.8.0rc2
```
DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
from scipy.sparse.base import spmatrix
```

avoid DeprecationWarning from SciPy 1.8 (`cupyx.scipy.sparse`)

---

docs/source/conf.py

This is to allow building docs against wheel packages (`cupy-cudaXXX`).
(Background: I sometimes want to generate comparison table to compare the difference between multiple CuPy versions. However CuPy wheels are not recognized by `pkg_resources.get_distribution('cupy')`. It is handy if I can do this using wheel packages.)

DOC: Use `cupy.__version__` instead of `pkg_resources`

---

cupy/testing/__init__.py
cupy/testing/_helper.py
tests/cupy_tests/testing_tests/test_helper.py

This can be used for markers other than `skipif`, e.g., `pytest.mark.xfail(installed('scipy==1.8.*'))`

Add `cupy.testing.installed`

---

cupy/cuda/cupy_thrust.cu

This PR fixes the problem that CuPy may not be buildable with CUDA 11.6 due to the namespace related changes added to thrust in CUDA 11.6.
This is related to https://github.com/cupy/cupy/issues/6309

Fix thrust related build issue with CUDA 11.6

---

cupyx/scipy/sparse/linalg/_lobpcg.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Rel. #6233.
This PR fixes the verbose messages of LOBPCG to make them get along with SciPy 1.8.

Fix verbose LOBPCG for SciPy 1.8

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Rel #6323.
Mark tests as XFAIL, which fail with, at least, SciPy 1.8 rc because of its bug.

Mark XFAIL for SciPy 1.8 release candidate

---

install/cupy_builder/_command.py
install/cupy_builder/cupy_setup_build.py
setup.py
tests/install_tests/test_cupy_builder/test_command.py

This PR reduces the installation time by making the module configuration (`get_ext_modules`) happen only once during the setup process.
Currently, module configuration runs three times when doing `pip install -e .`.
`pip` launches `setup.py` two times:
* `setup.py egg_info` (configuration happens at [setup.py](https://github.com/cupy/cupy/blob/v11.0.0a1/setup.py#L85))
* `setup.py develop` (configuration happens at [setup.py](https://github.com/cupy/cupy/blob/v11.0.0a1/setup.py#L85) & [custom_build_ext](https://github.com/cupy/cupy/blob/v11.0.0a1/install/cupy_builder/cupy_setup_build.py#L796))
However, the first process is only for generating `egg-info` (to list setup requirements etc.), and does not need module configuration (https://github.com/cupy/cupy/issues/5722#issuecomment-1004566726 …

Eliminate unnecessary configuration pass in setup

---

cupy/__init__.py
cupy/_math/arithmetic.py
docs/source/reference/math.rst
tests/cupy_tests/math_tests/test_arithmetic.py

Hi,
This PR **aims** to resovle `cupy.float_power` as requested in #6078.
I am getting the data_type assertion error for complex datatype. 4 testcases are being failed.
expect data_type is `numpy.complex128` whereas output generated is `cupy.complex64`.
Looking for your guidance! Thank You.

added api for `cupy.float_power`

---

cupy/_core/_routines_sorting.pyx
tests/cupy_tests/sorting_tests/test_sort.py

Fix #6384.
- benchmark script
```py
import cupy
a = cupy.ones((300,22,201,201), dtype=cupy.float32)
hook = cupy.cuda.memory_hooks.LineProfileHook()
with hook:
cupy.sort(a)
hook.print_report()
perf = benchmark(cupy.sort, (a,), n_repeat=5, n_warmup=1)
print(perf)
```
- master
```
_root (6.96GB, 6.96GB)
/home/imanishi/cupy1/run.py:10:<module> (6.96GB, 6.96GB)
/home/imanishi/cupy1/cupy/_sorting/sort.py:31:sort (1017.18MB, 1017.18MB)
/home/imanishi/cupy1/cupy/_sorting/sort.py:32:sort (5.96GB, 5.96GB)
sort                :    CPU:184308.036 us   +/-103.517 (min:184198.084 / max:184479.268) us     GPU-0:184334.335 us   +/-124.955 (min:184202.240 / max:184485.886) us
```
- this PR
```
_root (5.00GB, 1.09GB)
/home/imanishi/cupy1/run.py:10:<module> (5.00GB, …
```

Reduce memory usage in `cupy.sort`

---

cupyx/scipy/ndimage/_spline_prefilter_core.py

Fixes an issue with some `cupyx.scipy.ndimage` routines that relied in `spline_filter` for input preprocessing in HIP environments.
This issue is similar to #4504, some of the values are not being updated in memory unless thread synchronization happens.
cc @grlee77 for future reference :)

Fix `cupyx.ndimage.spline_filter1d` for HIP

---

cupy/_core/_kernel.pyx

This will fix the following tests for hip:
```
cupy_tests/core_tests/test_ndarray_copy_and_view.py::TestArrayCopyAndView::test_astype_boolean_view
cupy_tests/core_tests/test_ndarray_elementwise_op.py::TestArrayElementwiseOp::test_add_array_boolarray
cupy_tests/core_tests/test_ndarray_elementwise_op.py::TestArrayElementwiseOp::test_iadd_array_boolarray
```

Fix boolean views for HIP

---

.pfnci/README.md
.pfnci/generate.py

I noticed that we need to run `generate.py` frequently than I initially thought (e.g. when there is a conflict on backport) so let's give these options default values. Now `./generate.py` does everything.

CI: Use default schema/matrix path in `generate.py`

---

docs/source/conf.py

Avoid CI failure until https://github.com/scipy/scipy/issues/14267 gets fixed.

Tentatively pin intersphinx to SciPy 1.7.1 docs

---

cupy/_core/_kernel.pyx
cupy/_core/_reduction.pyx
cupy/_core/core.pyx
cupy/lib/_polynomial.pyx
tests/cupy_tests/lib_tests/test_polynomial.py

Alternative to #6413
in HIP `__cuda_array_interface__` is not well defined, so it causes some functionality that relies on it such as polynomial API to fail where it shouldn't because it is being used as a hack to transform a regular object into a cupy ndarray in a really convoluted way.
We add a method to transform objects into ndarrays explicitly, avoiding the obscurity of the previous approach.
This PR fixes
```
cupy_tests/lib_tests/test_polynomial.py::TestPoly1dPolynomialArithmetic::test_poly1d_arithmetic[_param_8_{func=<lambda>, type_l='ndarray', type_r='poly1d'}]
cupy_tests/lib_tests/test_polynomial.py::TestPoly1dPolynomialArithmetic::test_poly1d_arithmetic[_param_20_{func=<lambda>, type_l='ndarray', type_r='poly1d'}]
cupy_tests/lib_tests/test_polynomial.py::TestPoly1dPolynomialArith …
```

Add `__cupy_get_ndarray__` dunder method to transform objects to arrays'

---

.pfnci/config.pbtxt

This is needed to run head tests every midnight. (c.f. #6340)

CI: Add HEAD tests for stable branch

---

tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

These tests are flaky, and fail if other tests are run in conjunction with them. Standalone runs never fail but
for example 
`pytest tests/cupy_tests/sorting_tests/test_search.py tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py -k 'test_cub_argmin or test_ihfft'` causes the tests to fail. (Even with CUB disabled ...)
Currently I am not sure of where is the issue that causes this and if its solvable, but for the meantime I think it is better to just skip the tests to get a working CI.

Skip hfft related tests in HIP

---

cupy/_core/_reduction.pyx

The calculations done for the block size are not correct in some cases leading to inefficient block sizes when `keepdims=True` in regular reductions. Closes #6425
This PR uses the sizes of the output array to figure this instead of the input ones.
master
`sum` of `(400, 400, 400)` shaped array in all axis with `keepdims=True`
```
CPU:  111.235 us   +/-117.695 (min:   30.789 / max:  340.247) us     GPU-0:1540503.906 us   +/-112.247 (min:1540392.822 / max:1540723.633) us 
```
this pr
```
CPU:   26.479 us   +/- 7.041 (min:   21.125 / max:   44.058) us     GPU-0:50921.146 us   +/-13.583 (min:50900.673 / max:50951.263) us
```

Fix reduction contiguous size calculation

---

.pfnci/linux/main-flexci.sh

`nvidia-smi -pm 0` had to be done before driver update.

CI: Fix CUDA 11.6 driver update steps

---

cupyx/_runtime.py

Both CUDA/ROCm may fail to detect the number of GPUs with errors other than ErrorNoDevice in `cupy.show_config()`. See https://github.com/cupy/cupy/pull/6466#issuecomment-1041104492.

Warn if unexpectedlly failed to detect device count in `cupy.show_config()`

---

.github/workflows/flexci.yml
.github/workflows/flexci_dispatcher.py

This PR adds support for special test tag `/test skip`, which skips all tests.
This will allow using auto-merge for pull-requests that doesn't require manual CIs (e.g., docs only fixes).

CI: allow specifying special `skip` tag

---

docs/source/conf.py

Reverts cupy/cupy#6440. The issue seems resolved.

Revert "Tentatively pin intersphinx to SciPy 1.7.1 docs"

---

tests/cupyx_tests/scipy_tests/special_tests/test_beta.py
tests/cupyx_tests/scipy_tests/special_tests/test_gammainc.py
tests/cupyx_tests/scipy_tests/special_tests/test_ufunc_dispatch.py

```
13:53:34 FAILED cupyx_tests/scipy_tests/special_tests/test_beta.py::TestBeta::test_beta_specific_vals
13:53:34 FAILED cupyx_tests/scipy_tests/special_tests/test_beta.py::TestBeta::test_betaln_specific_vals
```
Tolerance needs to be adjusted.
```
13:53:34 FAILED cupyx_tests/scipy_tests/special_tests/test_gammainc.py::TestGammainc::test_roundtrip
```
This issue seems to be resolved in ROCm 5.0.

Fix failing tests in ROCm

---

setup.cfg

Part of #6455
It seems that Optuna 3.0.0a1/a2 has an issue that emits FutureWarning when using `Trial.suggest_int`.
Let's ignore them until the issue is fixed in Optuna side.
https://github.com/optuna/optuna/releases/tag/v3.0.0-a1
> v3.0.0-a1 contains several changes for this project and you will temporarily see UserWarning when you call Trial.suggest_int and Trial.suggest_float. We apologize for the inconvenience and the warning will be removed from the next release.

Ignore warnings from Optuna 3.0 pre-releases

---

install/cupy_builder/_command.py
install/cupy_builder/_compiler.py

This avoids appending a `--compiler-bindir` if `cl.exe` is already on PATH.
The issue was discovered in conda-forge build:
https://github.com/conda-forge/cupy-feedstock/pull/165#issuecomment-1050536590
conda-forge build env uses nvcc-feedstock that comes with the [wrapper batch file](https://github.com/conda-forge/nvcc-feedstock/blob/master/recipe/windows/nvcc_windows.bat) that prepends `-ccbin "%CXX%"`, and this batch file is used as NVCC command. As CuPy can't tell whether NVCC command is a wrapper or a real executable, this PR just skips appending `--compiler-bindir` and let NVCC find `cl.exe` if it's already on PATH.
cc/ @leofang

Skip appending `--compiler-bindir` if `cl.exe` is already on `PATH`

---

.pfnci/coverage.rst
.pfnci/linux/tests/cuda112.Dockerfile
.pfnci/linux/tests/cuda112.multi.Dockerfile
.pfnci/matrix.yaml

CentOS 8 reached EOL, and `yum` in CentOS-based CUDA images stopped working.
Tentatively disable CentOS 8 in our CI.
I tried to use UBI 8 images but UBI does not offer `readonly-devel` and `tk-devel` RPMs so they did not work.

Disable CentOS 8 test

---

cupy/cusparse.py
cupy_backends/cuda/cupy_cusparse.h
cupy_backends/cuda/libs/cusparse.pxd
cupy_backends/cuda/libs/cusparse.pyx
cupy_backends/hip/cupy_hipsparse.h
cupy_backends/stub/cupy_cusparse.h
cupyx/scipy/sparse/_csr.py
tests/cupy_tests/test_cusparse.py

This is related to https://github.com/cupy/cupy/issues/6463
Currently, CuPy uses [cusparse*csrgemm2()](https://docs.nvidia.com/cuda/cusparse/index.html#csrgemm2) for sparse matrix multiplication, but this function is deprecated and does not reflect recent performance improvements (that is, it's slow). In the future, it is recommended to use [cusparseSpGEMM()](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spgemm) instead of cusparse*csrgemm2, so this PR adds changes to allow cusparseSpGEMM() to be used with CuPy.
The results of comparing the performance using the reproducer of https://github.com/cupy/cupy/issues/6463 are as follows. `cusparse.csrgemm2` is the routine currently used in CuPy for the multiplication of sparse matrices. We have confirmed that …

Support cusparseSpGEMM()

---

cupy/_core/include/cupy/hip_workaround.cuh

Close #6517.
This PR fixes `cupy.cumsum` to use memory fences at the points where CUDA synchronizes threads in a warp. We don't need to synchronize threads in a warp in ROCm as they march in lock-step, but still have to ensure its memory order.
The following is a performance comparison based on the script in #4366 on ROCm 4.3. I think its overhead is reasonably ignorable:
size | dtype | NumPy | CuPy(w/fence) | CuPy(wo/fence)
--|--|--|--|--
1000000 | int32 | 5.057 ms | 0.119 ms | 0.122 ms
1000000 | int64 | 1.710 ms | 0.128 ms | 0.123 ms
1000000 | float32 | 2.536 ms | 0.137 ms | 0.126 ms
1000000 | float64 | 2.560 ms | 0.153 ms | 0.134 ms
10000000 | int32 | 50.272 ms | 0.650 ms | 0.639 ms
10000000 | int64 | 29.694 ms | 0.741 ms | 0.735 ms
10000000 | float32 | 31.232 ms | 0.623 ms | 0.588 ms …

Fix `cupy.cumsum` on ROCm 5.0

---

cupyx/scipy/special/__init__.py
cupyx/scipy/special/_beta.py
cupyx/scipy/special/_gammainc.py
cupyx/scipy/special/_statistics.py
cupyx/scipy/special/_stats_distributions.py
docs/source/reference/scipy_special.rst
tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py
tests/cupyx_tests/scipy_tests/special_tests/test_ufunc_dispatch.py

This PR adds many functions related to statistical distributions. There are many new functions here, but each is quite small (often <10 lines of GPU kernel code) because they mostly call previously implemented gamma and beta functions. They also often share a common testing logic. It was mainly implementing the test cases that was time consuming.
I have grouped these together in their own `_stats_distributions.py` file and moved the existing normal distribution functions into that file as well. I tried to have common logic where possible in the test classes, but there are occasionally subtle differences in dtype behavior (e.g. differences on behavior/warnings around unsafe casting of double->int32). The `ufunc.types` match and are in the same order as those in SciPy to ensure the same …

cupyx.scipy.special: add statistical distributions

---

tests/cupy_tests/cuda_tests/test_memory.py

It seems Windows + TCC does not support async malloc.
https://github.com/cupy/cupy/pull/5889#issuecomment-1063588178
Testing with CUDA 11.6 on Windows:
https://ci.preferred.jp/cupy.win.cuda116/96658/

Skip `async_malloc` tests on unsupported device

---

.github/workflows/flexci.yml
.github/workflows/flexci_dispatcher.py
.pfnci/config.tags.json
.pfnci/matrix.yaml

We have been triggering FlexCI via `push` webhook to run tests against merged commit. However, it is becoming costly to maintain a webhook URL because we have to embed a comma-separated list of FlexCI projects to trigger in the URL, and the list is so long.
This PR lets GitHub Actions trigger FlexCI on push event in addition to `issue_comment` event (`/test`).
(note: after merging this PR we should remove webhook configuration)

CI: Trigger `push` event of FlexCI via GitHub Actions

---

cupy_backends/cuda/cupy_cusparselt.h
cupy_backends/cuda/libs/cusparselt.pyx
cupy_backends/cupy_cusparselt.h

Following up #6507.
This PR fixes cuSPARSELt 0.1.0 support in v10, which was corrupted in #6507.

[v10] Fix cuSPARSELt 0.1.0 support in v10

---

cupyx/jit/_interface.py
tests/cupyx_tests/jit_tests/test_raw.py

Fix #5795 and #6574.
Adds `device_id` to the cache key.

Avoid using the same kernel from different devices in JIT

---

cupy/_logic/truth.py
cupy/_sorting/search.py

Rel. #4018
master:
```
in1d                :    CPU: 8473.098 us   +/-52.090 (min: 8446.542 / max: 8763.044) us     GPU-0:120539.443 us   +/-47.472 (min:120487.938 / max:120788.994) us
```
This PR:
```
in1d                :    CPU: 8428.611 us   +/-44.928 (min: 8408.114 / max: 8835.957) us     GPU-0:64765.102 us   +/-43.197 (min:64736.259 / max:65145.859) us
```
Benchmark:
```py
import cupy
shape = (64, 1024, 1024)
x1 = testing.shaped_random(shape, xp=cupy, dtype='l', seed=0, scale=100000000)
x2 = testing.shaped_random(shape, xp=cupy, dtype='l', seed=1, scale=100000000)
perf = benchmark(cupy.in1d, (x1, x2), n_repeat=100)
print(perf)
print(cupy.in1d(x1, x2).sum())
```
cc: @mrkwjc

Performance improvement of `cupy.in1d`

---

cupyx/scipy/sparse/linalg/_eigen.py

Instead of doing a `gemm` where one of the matrices is a column vector, we can just call `gemv`. This doesn't matter too much on CUDA but for ROCm this performs significantly better.

eigsh: Prefer gemv over gemm

---

cupy/_core/internal.pyx
tests/cupy_tests/core_tests/test_internal.py
tests/cupy_tests/core_tests/test_ndarray.py

Fix #5503.
This PR fixes array creation to be able to take values as NumPy ints and NumPy zero-dim arrays for `shape`.

Fix array creation shape

---

cupy/_manipulation/basic.py
tests/cupy_tests/manipulation_tests/test_basic.py

Rel #6577.
This PR fixes `cupy.copyto` to be able to take NumPy array scalars as its `src` data. I want to change this in advance to fixing #6577 in order to implement `cupy.full` using `cupy.copyto` as `numpy.full` does.

Fix `cupy.copyto` to take NumPy array scalars

---

cupy/_creation/basic.py
cupy/_manipulation/basic.py
tests/cupy_tests/creation_tests/test_basic.py
tests/cupy_tests/manipulation_tests/test_basic.py

Fix cupy.full and cupy.full_like to make unsafe casting

---

.pfnci/schema.yaml
cupy/_core/include/cupy/carray.cuh
cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_filters_generic.py
cupyx/scipy/sparse/_csc.py
examples/custom_struct/complex_struct.py
tests/cupy_tests/core_tests/test_function.py
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/core_tests/test_raw.py
tests/cupy_tests/cuda_tests/test_memory.py
tests/cupy_tests/functional_tests/test_vectorize.py
tests/cupy_tests/linalg_tests/test_product.py
tests/cupyx_tests/fallback_mode_tests/test_fallback.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Rel #6459. Merge #6517 first.
A number of fixes for making CuPy work healthy with ROCm 5.0.

Fix for supporting ROCm 5.0

---

cupy/_logic/truth.py
cupy/_sorting/search.py

Rel. #6402
master:
```
intersect1d         :    CPU:34600.527 us   +/-14.160 (min:34568.779 / max:34668.362) us     GPU-0:35218.770 us   +/-13.787 (min:35187.714 / max:35282.944) us
intersect1d         :    CPU:72343.659 us   +/-71.981 (min:72294.853 / max:72748.705) us     GPU-0:74817.813 us   +/-59.652 (min:74770.432 / max:75154.434) us
```
This PR:
```
intersect1d         :    CPU:24760.175 us   +/-19.352 (min:24705.804 / max:24900.344) us     GPU-0:25380.608 us   +/-18.880 (min:25326.591 / max:25516.031) us
intersect1d         :    CPU:56950.079 us   +/-51.338 (min:56914.579 / max:57307.126) us     GPU-0:58647.603 us   +/-49.220 (min:58611.713 / max:58987.518) us
```
Benchmark:
```py
import cupy
shape = (64, 1024, 1024)
x1 …
```

Performance improvement of `cupy.intersect1d`

---

cupy/_core/_routines_manipulation.pxd
cupy/_core/_routines_manipulation.pyx
cupy/_core/core.pxd
cupy/_core/core.pyx
cupy/_manipulation/shape.py
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
tests/cupy_tests/manipulation_tests/test_shape.py

Fix `flatten` as `ravel` in #6585.
This PR also refactors the test of `ravel`.

Implement `flatten(order)`

---

cupy/_core/include/cupy/carray.cuh
tests/cupy_tests/core_tests/test_include.py

Fix #6615. Following up #6524.

Define float16::operator-() only for ROCm 5.0+

---

cupyx/jit/_builtin_funcs.py
cupyx/jit/_compile.py
cupyx/jit/_cuda_types.py

Rel https://github.com/cupy/cupy/issues/5280#issuecomment-1087142600.
Combines variable declaration and initialization if the variable is first used at the top level.
cc: @leofang

JIT: Avoid calling default constructor if possible

---

cupy/_core/include/cupy/carray.cuh
tests/cupy_tests/core_tests/test_include.py

[hotfix-v10.3.1] [backport] Define float16::operator-() only for ROCm 5.0+

---

cupy/cuda/compiler.py

I believe CC 3.2 (Jetson TK1) is unlikely used but fixing it for sure as we still support CUDA 10.2.

Add CC 3.2 to Tegra arch list

---

cupy_backends/cuda/api/runtime.pxd
tests/cupyx_tests/jit_tests/test_cooperative_groups.py

Should fix CIs
- Skip cooperative groups in CUDA-Python when toolkit < 1.6
- Declare missing types in async allocation APIs

Fix cuda python CI

---

cupyx/jit/_builtin_funcs.py
cupyx/jit/_internal_types.py
docs/source/conf.py
docs/source/reference/kernel.rst

Close #5390. 
Still not perfect but a lot better than before. It'd be nice to backport this.
before | after 
-------|------
before | after 
-------|------

JIT: fix function signatures in the docs

---

cupy/_core/include/cupy/carray.cuh
cupy/_core/include/cupy/tuple/tuple.h
cupy/_functional/vectorize.py
cupyx/jit/_compile.py
cupyx/jit/_cuda_types.py
tests/cupyx_tests/jit_tests/test_raw.py

Based on the discussion between @eternalphane and @asi1024 in #5293.
It'd take some effort to support arrays of `ndim>10` (due to a Thrust limitation, see https://github.com/cupy/cupy/pull/5293#issuecomment-1101766792), but at least with this PR we unblock the most common use cases.

JIT: Support `.shape` and `.strides`

---

cupyx/distributed/_nccl_comm.py
tests/cupyx_tests/distributed_tests/comm_runner.py
tests/cupyx_tests/distributed_tests/test_comm.py

There are several difficult things going on here that need to be discussed.
A proper way to send the shape/sizes of the internal matrix arrays, right now is done in nccl and this ends up syncing the device. Doing through the backing TCP store would be also pretty slow and will require modifying the store too for cases when a process is accessing elements that are not yet set.
cc @leofang do you have some thoughts on this?
Thanks!

Add support for sparse matrices in `cupyx.distributed`

---

.github/workflows/pretest.yml
.gitignore
install/universal_pkg/RELEASE.md
install/universal_pkg/setup.py
tests/install_tests/test_universal_pkg/test_setup.py

This is a RFC PR to introduce universal CuPy package.
CuPy have been providing separate binary packages for each CUDA/ROCm version, but this is making downstream packages difficult to declare a dependency to CuPy.
This PR aims to improve the situation by introducing a new meta PyPI package named `cupy-wheel`, that dynamically declares dependency to one of the "real" CuPy wheel (`cupy-cudaXXX` or `cupy-rocm-X-X`) by looking into CUDA/ROCm installed in the users' environment.
Downstream packages can declare dependency (in `install_requires` or `requiements.txt`) like `cupy-wheel==9.*`.

Add universal CuPy package

---

cupy/_statistics/histogram.py
cupy/cuda/cub.pyx
cupy/cuda/cupy_cub.cu
cupy/cuda/cupy_cub.h

This PR accelerates all histogram related operations. The key insight is `bincount` is internally used to support multi-dimensional histograms (`histogram2d` and `histogramdd`), so if no weighting is required they can all be accelerated using CUB. 
Under the hood, we use CUB's `HistogramEven` instead of `HistogramRange`, as the former does not require constructing an extra `bins` array.
* `cupy.bincount()`:
(Here we also compare the timing of `cupy.histogram()` to show the benefit of not constructing a `bins` array, as for 1D integer inputs the result of the two APIs are identical.)
GPU elapsed time (us) | without CUB | with CUB | speedup | histogram (with CUB)
-----|-----|-----|-----|-----
size=100 | 96.36800214648247  | 118.18240210413933  | 0.8154175277429666  | 198.46399873495102 …

Accelerate `bincount`, `histogram2d`, `histogramdd` with CUB

---

docs/source/user_guide/difference.rst

Rel #6716. This PR removes an unnecessarily used internal name in the user guide, which caused a `cuda-example` CI failure in #6716.

Use exposed name in user guide

---

cupy/_core/__init__.py
cupy/_core/_fusion_trace.pyx
cupy/_core/_kernel.pyx
cupy/_core/_routines_indexing.pyx
cupy/_core/_routines_linalg.pyx
cupy/_core/_routines_manipulation.pyx
cupy/_core/_routines_math.pyx
cupy/_core/_routines_sorting.pyx
cupy/_core/core.pyx
cupy/_core/dlpack.pyx
cupy/cuda/cub.pyx
cupy/cudnn.pyx
cupy/random/_generator_api.pyx
tests/cupy_tests/core_tests/test_core.py
tests/cupy_tests/core_tests/test_ndarray.py

Merge #6718 first.
This PR is a part of supporting `cupy.narray` subclassing. I implement Direct constructor call here.
- Define `cupy._core.core._ndarray` that wraps cdef'ed `cupy._core.core.ndarray`
- Replace codes where directly instantiating ndarrays
- Fix parts where an object is compared to `cupy._core.core.ndarray`
- Add a test

Support cupy.ndarray subclassing - Part 1 - Direct constructor call

---

.pfnci/linux/main-flexci.sh

CUDA 11.6 issue on GCP seems resolved.
https://cloud.google.com/compute/docs/troubleshooting/known-issues
Testing: https://ci.preferred.jp/cupy.linux.cuda116/101922/ (seems not working, investigating...)

Support testing CUDA 11.6+ in FlexCI

---

cupy/_core/include/cupy/carray.cuh

`cupy.cuda.compiler.CompileException: .../cupy/_core/include/cupy/carray.cuh(129): warning #14-D: extra text after expected end of preprocessing directive`

Fix compilation warning caused by ifdef

---

cupy/_core/include/cupy/carray.cuh

[backport] Fix ifdef for ROCm >= 4.2

---

cupy/__init__.py
cupy/_logic/truth.py
docs/source/reference/set.rst
tests/cupy_tests/logic_tests/test_truth.py

Linked Issue: #6078 
Hey! I have implememeted numpy.setxor1d but seems like when you provide a multi-dim array with assume_unique as True, numpy raises an error, since their code concatenates array as - np.concatenate((ar1,ar2)) and not np.concatenate((ar1,ar2), axis=None).
However, when assume_unique is false, the array is flattened as it uses the numpy.unique function which returns a flattened array. Do we replicate the same behaviour in CuPy or allow multi-dim arrays even when assume_unique is set to true?
Attaching a screenshot below to explain the above:
Open discussion in numpy - https://github.com/numpy/numpy/issues/14670
Currently, the code I have written does not throw errors for multi-dim arrays, regardless of where `assume_unique` is True or False. However, tests currently …

add `cupy.setxor1d` api

---

cupy/_core/_routines_statistics.pyx
tests/cupy_tests/statistics_tests/test_meanvar.py

Fixes https://github.com/cupy/cupy/issues/6755.

Fix `cupy.median` for NaN inputs

---

cupy_backends/cuda/api/runtime.pyx
tests/cupy_tests/cuda_tests/test_runtime.py

This will allow using `runtime.runtimeGetVersion()` in all locations where branch based on the current CUDA version (to test feature availability) is needed.

Fix to return correct CUDA version when in CUDA Python mode

---

cupy_backends/cuda/_softlink.pxd
cupy_backends/cuda/_softlink.pyx
cupy_backends/cuda/cupy_nvrtc.h
cupy_backends/cuda/libs/nvrtc.pyx
cupy_backends/hip/cupy_hiprtc.h
cupy_backends/stub/cupy_nvrtc.h
install/cupy_builder/_modules.py

Currently, we are maintaining binary packages for 8 minor versions of CUDA (10.2 & 11.0 ~ 11.6).
However, now that CUDA minor releases are cut every 3~4 months, it is becoming unsustainable to build and distribute wheels for each minor release, both in terms of PyPI's limit and our release load.
This PR aims to make CuPy binary package utilize CUDA Enhanced Compatibility (it seems now a part of [Minor Version Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility)). This way we can reduce the number of packages to one for each CUDA **major** version.
* `cupy-cuda102` # for CUDA 10.2
* `cupy-cuda110` # for CUDA 11.0
* `cupy-cuda111` # for CUDA 11.1
* `cupy-cuda11x` # for CUDA 11.2 ~ 11.x
* `cupy-cuda12x` # for CUDA 12.x (in future)
Note: …

Utilize CUDA Enhanced Compatibility

---

tests/cupy_tests/functional_tests/test_vectorize.py

Hi,
This pull request is a fix to a potential variable misuse bug at `tests/cupy_tests/functional_tests/test_vectorize.py`. Please check the changes.
Best,
Jingxuan

Fix a potential variable misuse bug

---

cupy/_core/core.pyx
docs/source/conf.py

Depends on ~#6746~ (merged)
* Declare `__init__` signature in docstring instead of modifying it in `conf.py`
* Replace `_ndarray_base` that appears in argument types of several functions

Fix docs to hide `ndarray_base`

---

cupy/array_api/__init__.py

There are a lot of other references to "numpy" in the module docstrings, which I did not change, but this one is confusing because it prints to the screen when `cupy.array_api` is imported.

Make the warning for cupy.array_api say "cupy" instead of "numpy"

---

cupy_backends/cuda/cupy_cusparse.h
cupy_backends/cuda/libs/cusparse.pyx
cupy_backends/cuda/libs/nvrtc.pyx
cupy_backends/hip/cupy_hiprtc.h
cupy_backends/stub/cupy_cusparse.h
cupy_backends/stub/cupy_nvrtc.h

This PR completes the support of CUDA Enhanced Compatibility in CuPy.
Using the mechanism introduced in #6730, this PR lazy loads all symbols added in CUDA 11.2 or later.
This should allow CuPy built with any of CUDA 11.2+ to run on any of CUDA 11.2+.

Utilize CUDA Enhanced Compatibility in all wrappers

---

cupy_backends/cuda/cupy_cusparse.h
cupy_backends/cuda/libs/cusparse.pyx

Fixes https://github.com/cupy/cupy/pull/6799#issuecomment-1164125185

Fix required cusparse symbol not loaded in CUDA 11.1.1

---

.pfnci/coverage.rst
.pfnci/linux/main-flexci.sh
.pfnci/linux/tests/cuda-head.Dockerfile
.pfnci/linux/update-cuda-driver.sh
.pfnci/matrix.yaml
.pfnci/schema.yaml

https://ci.preferred.jp/cupy.linux.cuda-head/104273/
```
00:02:43.635232 STDOUT 1603]	#6 46.41 E: Version '2.11.*+cuda11.7' for 'libnccl2' was not found	
00:02:43.635273 STDOUT 1603]	#6 46.41 E: Version '2.11.*+cuda11.7' for 'libnccl-dev' was not found	
```

Fix CI Docker image build failing in head test

---

cupy/_core/_fusion_kernel.pyx
cupy/_core/_kernel.pyx
cupy/_core/_routines_linalg.pyx
cupy/_core/_routines_manipulation.pyx
cupy/_core/_routines_math.pyx
cupy/_core/core.pxd
cupy/_core/core.pyx
cupy/_core/internal.pyx
cupy/cusolver.pyx
cupy/cutensor.pyx
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

Merge #6746 first.
This PR is a part of supporting `cupy.ndarray` subclassing. Following #6716, I implement View casting.

Support cupy.ndarray subclassing - Part 2 - View casting

---

cupy/_core/_kernel.pxd
cupy/_core/_kernel.pyx
cupy/_core/_reduction.pyx
cupy/_core/core.pxd
cupy/_core/core.pyx
cupy/cutensor.pyx
tests/cupy_tests/core_tests/test_ndarray_ufunc.py

Merge #6720 first.
This PR is a part of supporting `cupy.ndarray` subclassing, and support instantiating subclass via ufunc, including two paths: the original one and cutensor one.

Subclass cupy.ndarray subclassing - Part 3 - New from template (ufunc)

---

README.md
docs/source/install.rst

Blocked by https://github.com/cupy/cupy-release-tools/pull/269
I want to do some additional manual confirmation once the above PR has merged, so marking it as draft until then.

Update docs for `cupy-cuda11x` wheel

---

docs/requirements.txt

Render comparison table with NumPy 1.23 which is the baseline API version for v11.
#6764
Follows up #6820

Bump NumPy version used in docs

---

docs/source/upgrade.rst

This covers `no-compat` PRs in v11.
https://github.com/cupy/cupy/pulls?q=is%3Apr+label%3Ano-compat+is%3Aclosed

Add upgrade guide for CuPy v11

---

cupy/cuda/compiler.py
tests/cupy_tests/cuda_tests/test_compiler.py

Raise UserWarning in `cupy.cuda.compile_with_cache`

---

install/universal_pkg/setup.py
tests/install_tests/test_universal_pkg/test_setup.py

Ref #6688
This PR fixes this issue described in the above PR.
> GPUs are required to install cupy-wheel
This PR also fixes the issue that ROCm 4.0/4.2 detection was not working.

cupy-wheel: Use NVRTC to infer the toolkit version

---

cupy/_core/core.pyx
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py

Part of #6821, following a change of NumPy 1.23.
https://numpy.org/devdocs/release/1.23.0-notes.html#changing-to-dtype-of-a-different-size-now-requires-contiguity-of-only-the-last-axis

Relaxed C-contiguous requirement for changing dtype of different size

---

README.md

As we still have one month until v11 stable release, let's keep v10 instruction in README to avoid confusion (#6833)

Reverting to v10 installation instruction until v11 stable release

---

.pfnci/config.tags.json
.pfnci/matrix.yaml

* Add `cuda102` etc. tags to trigger tests based on CUDA versions
* Use CUDA 11.7 (Linux) instead of CUDA 11.5 (Linux) for `mini` tag
* Fix CUDA 11.7 (Windows) missing

Update tags for FlexCI projects

---

cupyx/scipy/stats/__init__.py
cupyx/scipy/stats/_morestats.py
docs/source/reference/scipy_stats.rst
tests/cupyx_tests/scipy_tests/stats_tests/test_morestats.py

Hi, the PR adds `cupyx.scipy.stats.boxcox_llf`!
size | dtype | SciPy | CuPy
-----|-------|-------|-----
1000 | int8 | 0.101 ms | 0.356 ms
1000 | int32 | 0.079 ms | 0.353 ms
1000 | uint32 | 0.080 ms | 0.414 ms
1000 | float32 | 0.076 ms | 0.389 ms
1000 | float64 | 0.084 ms | 0.457 ms
100000 | int8 | 4.178 ms | 0.458 ms
100000 | int32 | 2.964 ms | 0.522 ms
100000 | uint32 | 2.845 ms | 0.521 ms
100000 | float32 | 1.425 ms | 0.550 ms
100000 | float64 | 2.693 ms | 0.521 ms
1000000 | int8 | 41.181 ms | 3.824 ms
1000000 | int32 | 27.627 ms | 4.676 ms
1000000 | uint32 | 27.741 ms | 4.795 ms
1000000 | float32 | 13.221 ms | 4.771 ms
1000000 | float64 | 27.190 ms | 4.804 ms
size | dtype | SciPy | CuPy
-----|-------|-------|-----
1000 | int8 | 0.100 ms | 0.310 ms
1000 | int32 | 0.079 ms | 0.298 ms …

[stats] add `cupyx.scipy.stats.boxcox_llf`

---

install/cupy_builder/_compiler.py

----
I noticed `cupy-cuda11x` (v11rc1) failing on Jetson Xavier Dev Kit (CC 7.2 with CUDA 11.4, aarch64, Linux):
```
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorUnsupportedPtxVersion: the provided PTX was compiled with an unsupported toolchain.
```
Also confirmed the same issue on NVIDIA GeForce GTX TITAN X (CC 5.2 with CUDA 11.4, x86_64, Windows).
This is because `cupy-cuda11x` wheel contains PTX generated with the latest driver (CUDA 11.7), which cannot be executed on earlier drivers.
https://docs.nvidia.com/deploy/cuda-compatibility/index.html#application-considerations
`compute_86` (PTX) is left for compatibility with future GPUs. Note that `compute_87` is not used as it is a CC for Tegra and [Binary Compatibility is not guaranteed between Desktop and …

Generate CUBIN for all supported GPUs at build time

---

cupyx/scipy/stats/_morestats.py
tests/cupyx_tests/scipy_tests/stats_tests/test_morestats.py

Following up https://github.com/cupy/cupy/pull/6849.
This PR fixes `boxcox_llf` to return a scalar array of nan instead of float nan when empty data is given as well as improving its tests on the testing tolerance and input ranges.

Fix `boxcox_llf`

---

cupy/_statistics/meanvar.py
tests/cupy_tests/statistics_tests/test_meanvar.py

Part of https://github.com/cupy/cupy/issues/6821, following a change of NumPy 1.23.
https://numpy.org/devdocs/release/1.23.0-notes.html#keepdims-parameter-for-average

Support `keepdims` parameter for `average`

---

cupy/_manipulation/add_remove.py
tests/cupy_tests/manipulation_tests/test_add_remove.py

Part of https://github.com/cupy/cupy/issues/6821, following a change of NumPy 1.23.
https://numpy.org/devdocs/release/1.23.0-notes.html#new-parameter-equal-nan-added-to-np-unique
Note that `numpy.unique` seems to have a bug that it returns wrong results when it takes float16 ndarrays with one or more `nan`.

Support `equal_nan` parameter for `unique`

---

cupy/_core/__init__.py
cupy/_core/_routines_math.pyx
cupy/_math/arithmetic.py
tests/cupy_tests/math_tests/test_arithmetic.py

There are numerical issues so for negative numbers I try to avoid using fp16 type and anything promoting to fp16.
This is just to reuse the test machinery and avoid creating new tests only for this.
numyp does the full calc in fp16 resulting in 179.9 due to numerical issues. CuPy just returns 180

Support `deg` in `cupy.angle`

---

install/universal_pkg/setup.py
tests/install_tests/test_universal_pkg/test_setup.py

* Update package list
* Fix issue in #6688 (pip caches cupy-wheel) by using build number override technique described in https://discuss.python.org/t/wheel-caching-and-non-deterministic-builds/7687

Update cupy-wheel for v11

---

docs/requirements.txt
docs/source/conf.py

pydata-sphinx-theme v0.9.0 provides the dark mode support!
https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.9.0
----
Let's merge this after the branch cut to avoid unexpected doc build failures.

Bump documentation build requirements

---

cupyx/scipy/special/__init__.py
cupyx/scipy/special/_softmax.py
docs/source/reference/scipy_special.rst
tests/cupyx_tests/scipy_tests/special_tests/test_softmax.py

Adds `cupyx.scipy.special.softmax`.
size | dtype | SciPy | CuPy
-----|-------|-------|-----
1000 | int8 | 0.106 ms | 0.104 ms
1000 | int32 | 0.062 ms | 0.104 ms
1000 | float32 | 0.046 ms | 0.106 ms
1000 | float64 | 0.058 ms | 0.105 ms
100000 | int8 | 5.711 ms | 0.111 ms
100000 | int32 | 1.761 ms | 0.139 ms
100000 | float32 | 0.378 ms | 0.115 ms
100000 | float64 | 1.620 ms | 0.138 ms
1000000 | int8 | 56.208 ms | 0.225 ms
1000000 | int32 | 17.004 ms | 0.774 ms
1000000 | float32 | 2.805 ms | 0.270 ms
1000000 | float64 | 17.225 ms | 0.925 ms
<details>
<summary>Script (Click Please)</summary>
<p>
```python
import cupy
import cupyx
import cupyx.scipy.stats
import scipy
import scipy.stats
n_warmup = 1
n_repeat = 10
dtype_set = …
```

[special] add `cupyx.scipy.special.softmax`

---

examples/cg/cg.py

The sum of two matrices is in general not positive definite but the
product is. This is needed in order to guarantee that the CG iteration
is well-defined.
Fixes #6938

Make matrix in CG example positive definite

---

cupy_backends/cuda/_softlink.pxd
cupy_backends/cuda/_softlink.pyx
cupy_backends/cuda/libs/cusparse.pyx
cupy_backends/cuda/libs/nvrtc.pyx

This reduces the code needed to support new CUDA APIs.
Follows-up #6730 and #6799.

Remove proxy functions for softlink

---

cupy/cuda/compiler.py

source: https://forums.developer.nvidia.com/t/what-is-the-compute-capability-for-the-orion-update-your-page/211447/3
> BTW the Orin GPU is CUDA compute capability 8.7.

Add CC 8.7 for Jetson Orin

---

cupy/_sorting/sort.py
cupy/array_api/_sorting_functions.py
tests/cupy_tests/array_api_tests/test_sorting_functions.py

This is for both NumPy compliance (#5701) and Array API compliance (#6779).
What this PR does is to simply add the kw-arg `kind`, allowing passing through of the argument.
However, given that currently there's only one sorting algorithm implemented in CuPy (from Thrust), we can't support `kind` being anything other than `None` or `"stable"`. So for Array API internally we always set `kind` to `None` regardless if users set `stable` to `True` or `False`. (Confirmed during a meeting that this was the intent of the standard.)
Close #5701. Close #6779.
cc: @asmeurer

Accept `kind` in `sort`/`argsort` and fix `cupy.array_api.{sort,argsort}` accordingly

---

cupy/_core/_routines_math.pyx
cupy/_math/misc.py
tests/cupy_tests/math_tests/test_misc.py

Fixes #6901 
Fixed the 'only `a_max` or `a_min` is given' issue by removing the default value of `None` for `a_min` and `a_max`.
Fixed the '`a_max` < `a_min`' issue by tweaking the cythonic implementation for the function.
Added test cases for the same.

Fix `cupy.clip` to match numpy

---

cupyx/jit/_builtin_funcs.py
cupyx/jit/_compile.py
tests/cupyx_tests/jit_tests/test_device_function.py

Reproducer:
```py
import cupy
import cupyx
@cupyx.jit.rawkernel(device=True)
def g(x):
x[0] += 1
return 1
@cupyx.jit.rawkernel()
def f(x):
x[g(x)] += 1
x = cupy.zeros((2,))
f[1, 1](x)
print(x)
print(f.cached_code)
```
master:
```cc
[2. 1.]
__device__ int g_1(CArray<double, 1, true, true> x) {
x[0] = (x[0] + (double)(1));
return 1;
}
extern "C" __global__ void f(CArray<double, 1, true, true> x) {
x[g_1(x)] = (x[g_1(x)] + (double)(1));
}
```
This PR:
```cc
[1. 1.]
__device__ int g_1(CArray<double, 1, true, true> x) {
{ double &tmp__ = x[0]; tmp__ = (tmp__ + (double)(1)); }
return 1;
}
extern "C" __global__ void f(CArray<double, 1, true, true> x) {
{ double &tmp__ = x[g_1(x)]; tmp__ = (tmp__ + (double)(1)); }
}
```

Fix augassign target is evaluated twice in JIT

---

docs/source/conf.py

This fixes the master branch doc build (LaTeX) broken.
https://readthedocs.org/projects/cupy/builds/
This `assert` check was improper as the filenames for extension objects are not existing filenames after #6126 (which manually crafts the PYX filename by removing `~.so` and appending `.pyx` from the real extension object file).
Depending on the module discovery order of Sphinx, this assert triggers and build fails.

Fix docs build failure

---

cupy/cuda/cub.pyx
tests/cupy_tests/core_tests/test_ndarray_reduction.py

Close #6937.
Both `device_reduce` and `device_segmented_reduce` can now handle zero-size arrays correctly. In particular, if CUB is enabled we won't leave this case for the "default" backend to handle, so as to return the result as early as possible.
I also did a minor clean up of the tests to
1. combine two test classes into one
2.  modernize (ex: use pytest) and fix (ex: `rtol` is not needed for min/max tests, etc)

Fix CUB reduction with zero-size arrays

---

cupy/linalg/_einsum_cutn.py

Fix two bugs:
1. The cuTensorNet handle was not reused
2. The `memory_limit` was too large (4**31 bytes = 4294967296 GB)
- In cuQuantum Python, the semantics of `memory_limit` is different from that of `{numpy,cupy}.einsum()`. In the latter it is the size of the largest intermediate tensor, but in the former it is used
- as a constraint for max device memory to guide the contraction path optimizer
- additionally, as a hard limit to determine if the actual workspace size is too large
- Since there's no perfect way to map the two `memory_limit`s, I just disable it entirely and let cuQuantum Python's default kick in.

Fix cuTensorNet shim layer

---

cupy/random/_generator.py
tests/cupy_tests/random_tests/test_generator.py

Fixes #1644
When any of `low` or `high` are multidimensional and `size` is `None`, then the final shape is computed before sampling the values

Make sure that uniform sampling respects broadcasting

---

install/cupy_builder/install_build.py

Part of https://github.com/cupy/cupy/issues/4983#issuecomment-1020816566
`distutils.utils.split_quoted` and `shlex.split` is interchangable except for the difference of the control character handling. I think there's no problem in our case.
https://stackoverflow.com/questions/54999301/what-is-the-difference-between-distutils-util-split-quoted-and-shlex-split

Remove use of `distutils.utils`

---

cupy/_core/_routines_sorting.pyx
tests/cupy_tests/sorting_tests/test_sort.py

Fixes #3287
Fixes #6812 
`argpartition` now uses an indirect-sort version of the `partition` kernel

Let argpartition use the kth argument properly

---

cupy/cusparse.py

Close #6978. cc: @anaruse @anadodik 
Note that csrsm2 is deprecated and will be removed from cuSPARSE, otherwise there're some optimization opportunities that one may exploit (ex: the info struct can be used in multiple `solve` calls for the same input matrix, see the documentation) for iterative solvers.

Fix `csrsm2` memory leak

---

cupyx/scipy/sparse/_data.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Fixes #3640
The aforementioned issue only happened when `argmax/min` was called without an `axis` defined. Now `argmin/max` returns a scalar array with the index.

Make sparse argmin/max return a scalar array containing the index

---

.pfnci/linux/main-flexci-prep.sh
.pfnci/linux/main-flexci.sh
.pfnci/linux/run.sh

Closes #6561.
GCS bucket has also been changed to region-only (no code changes needed).

CI: Migrate to GAR from GCR

---

cupy/lib/_shape_base.py
tests/cupy_tests/lib_tests/test_shape_base.py

Fix `cupy.apply_along_axis` for tuple retval

---

cupyx/scipy/spatial/distance.py
docs/source/reference/scipy_spatial_distance.rst
tests/cupyx_tests/scipy_tests/spatial_tests/test_distance.py

This PR exposes all the pairwise distance functions offered by RAFT, increasing the compatibility between `cupyx.scipy.distance` and `scipy.spatial.distance`

Expose pairwise distance functions

---

setup.py

hypothesis 65.5.0 started to infer array api spec version from `__array_api_version__` attribute. https://github.com/HypothesisWorks/hypothesis/releases/tag/hypothesis-python-6.55.0
This broke the CI so until we decide the proper value for that attribute pin the hypothesis version to the previous one.
https://data-apis.org/array-api/latest/future_API_evolution.html#versioning
`numpy.array_api` doesn't seem to have the attribute either.

CI: tentatively fix hypothesis version

---

cupy_backends/cuda/libs/cutensor.pxd
cupy_backends/cuda/libs/cutensor.pyx
cupy_backends/stub/cupy_cutensor.h

Starting cuTENSOR 1.6.0 the performance of `cutensorPermutation` is improved significantly. It'd be nice to make use of it:
1. Expose the API to Python (this PR)
2. Make cuTENSOR an optional backend for permutation-related functions such as `reshape`, where actual data movement may be required (future work)
It'd be nice to backport this PR to the v11 branch 🙂

Add wrapper for `cutensorPermutation`

---

tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py

It seems that ROCm outputs NaN on a float16 input generated by `xp.linspace`. This PR reverts the test code.
https://github.com/cupy/cupy/pull/7036/files#r986430809

Fix bessel test to pass ROCm CI

---

docker/python3/Dockerfile
docker/rocm/Dockerfile

Assets section of GitHub Releases are now lazy-loaded and so pip cannot find links from there.

Find wheels from pip.cupy.dev in Dockerfile

---

cupy/_core/_routines_binary.pyx
cupy/_core/_routines_indexing.pyx
cupy/_core/_routines_math.pyx
tests/cupy_tests/core_tests/test_ufunc_methods.py

Part of https://github.com/cupy/cupy/issues/7082.
~Blocked by https://github.com/cupy/cupy/pull/7077.~

Support `subtract.at`, `bitwise_and.at`, `bitwise_or.at`, `bitwise_xor.at`

---

cupy/_core/fusion.pyx
tests/cupy_tests/core_tests/fusion_tests/test_reduction.py

Fusion `TypeError` in `cupy._core.fusion._call_ufunc()`

---

cupy/_core/dlpack.pyx

https://data-apis.org/array-api/latest/design_topics/data_interchange.html
> If an array that is accessed via the interchange protocol lives on a device that the requesting library does not support, it is recommended to raise a TypeError.
ref. #7131

Raise `TypeError` instead of `ValueError` in `cupy.from_dlpack` when CPU tensor is passed

---

tests/cupyx_tests/jit_tests/test_thrust.py

Rel. https://github.com/cupy/cupy/pull/7139#issuecomment-1298198379
```
22:48:26 cupyx_tests/jit_tests/test_thrust.py .......xxsstimeout: the monitored command dumped core
22:48:27 /src/.pfnci/linux/tests/actions/unittest.sh: line 26:  1401 Aborted                 timeout --signal INT --kill-after 60 18000 python3 -m pytest "${pytest_opts[@]}" "${PYTEST_FILES[@]}"
22:48:33 + test_retval=134
```

JIT: Skip HIP `thrust::sort` test

---

.pfnci/windows/_flexci.ps1
.pfnci/windows/test.ps1

The new CI image (which is already deployed) has cuDNN in a separate path.

CI: Add support for the latest FlexCI Windows image

---

cupy/random/_generator_api.pyx
cupyx/cudnn.pyx

I presume the base type was forgotten in these two cases?
(found whilst testing out a [cython linter](https://github.com/MarcoGorelli/cython-lint))

Add missing base type to cdef declarations

---

cupyx/profiler/_time.py
tests/cupyx_tests/profiler_tests/test_benchmark.py
tests/cupyx_tests/test_time.py

Adds always spaces after `:` and `+/-` to improve parseability. In some cases spaces are not added so it is difficult to create generic scripts.
Before
```
rotate              :    CPU: 6083.005 us   +/-88.593 (min: 5992.784 / max: 6270.549) us     GPU-0:16082.317 us   +/-414.647 (min:15755.200 / max:17056.192) us
multiply            :    CPU:   20.559 us   +/- 0.455 (min:   20.134 / max:   22.139) us     GPU-0:   24.645 us   +/- 0.750 (min:   23.744 / max:   26.624) us
```
After
```
rotate              :    CPU:  6010.878 us   +/- 16.831 (min:  5975.687 / max:  6044.528) us     GPU-0: 15774.685 us   +/- 38.317 (min: 15732.384 / max: 15928.736) us
multiply            :    CPU:    21.008 us   +/-  0.636 (min:    20.439 / max:    23.427) us     GPU-0:    25.150 us   +/-  0.877 (min: …
```

Improve `_PerfCaseResult.to_str` format

---

cupy/_core/core.pyx

The argument to `warnings.warn()`, added when `ndarray.scatter_max()` and `ndarray.scatter_min()` were deprecated, is not correct and `cupyx.scatter_max()` and `cupyx.scatter_min()` would result in the following error.
```
>>> import cupyx
>>> a = cp.zeros(10)
>>> b = cp.arange(20)
>>> c = cp.arange(20)
>>> cupyx.scatter_max(a, b, c)
File "/usr/local/lib/python3.8/dist-packages/cupyx/_scatter.py", line 91, in scatter_max
a.scatter_max(slices, value)
File "cupy/_core/core.pyx", line 1624, in cupy._core.core._ndarray_base.scatter_max
TypeError: 'type' object cannot be interpreted as an integer
```
This PR is to correct this problem.

Fix wrong argument in warnings.warn()

---

cupyx/scipy/ndimage/_interpolation.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_interpolation.py

This PR fixes a bug in `cupyx.scipy.ndimage.zoom` that occurs when `mode='opencv'` and an image output size is 1 along any axis (it includes resizing grayscale images (N, M, 1) or batches of images (1, N, M, C)). The bug is caused by incorrectly setting zoom coefficients for output axes of size 1 and eventually [division by 0](https://github.com/cupy/cupy/blob/ec7bd5434f7f41a8c4d57367ef9afc05ccdaf121/cupyx/scipy/ndimage/_interpolation.py#L453) during the affine transform stage.

Fix cupyx.scipy.ndimage.zoom for outputs of size 1 when mode is 'opencv'

---

cupy/random/_generator_api.pyx

The amount of elements that can be calculated at once is limited by the size of the cuRand device state, we split the calculation in chunks due to this.
However, we are not splitting the input arrays, so the inputs of the first chunk are being reused for every chunk causing incorrect calculations in some distributions.
Fixes #7164

Split inputs to random routines

---

cupy_backends/cuda/cupy_cusparse.h
cupy_backends/cuda/libs/cusparse.pyx
cupy_backends/hip/cupy_hipsparse.h
cupy_backends/stub/cupy_cusparse.h

CUDA 11.x basically have minor version compatibility. However, they have some APIs that are introduced in the middle of 11.x minor versions, which APIs do not exist in CUDA toolkit before they're introduced. In such a case we have to dlopen the APIs at runtime instead of (dynamic-)link them at build-time against the latest 11.x minor version. Otherwise, the process complains when the depending (cython-origin) shared object is loaded.

Fix cusparseSpSM compatibility

---

cupyx/scipy/interpolate/_rbfinterp.py

Follows up #7218. We fixed to use `math.comb()` instead of `scipy.special.comb()` there to remove scipy dependency, however, it requires Python 3.8 or higher.

Use naive comb() for Python 3.7

---

cupy/random/_generator_api.pyx
tests/cupy_tests/random_tests/common_distributions.py
tests/cupy_tests/random_tests/test_generator_api.py

Implementing this method: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.uniform.html

Adding uniform() to random generator, since numpy has this functionality

---

cupyx/scipy/sparse/linalg/_solve.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Make `cupyx.scipy.sparse.spsolve` loop over the columns of `b` --- this matches the behavior of the scipy equivalent, which accepts 2D `B` arrays/matrices in `A @ X = B`: https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.spsolve.html
This is  a pure python loop since the underlying cusolver routine IIUC only accepts vectors. 
Several things to note:
1. This does not handle the case where A is real and b is complex. This still needs an upcast or looping on the user side 
2. This patch removes `b.ravel()` --- I tried testing with non-contiguous `b` arrays, so am *pretty sure* that it's OK, but please advise about how far one has to bend backwards to assert contiguity of inputs to cusolver routines.
3. Fortran ordering: this PR explicitly casts the result to be Fortran …

`cupyx.scipy.sparse.linalg.spsolve` : allow two-dimensional right-hand sides in `A @ X = B`

---

tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py

Allow tests to run without SciPy.
https://ci.preferred.jp/cupy.linux.cuda111/118681/
> E           ModuleNotFoundError: No module named 'scipy'
ref #7195

Skip tests if SciPy is unavailable

---

.pfnci/generate.py
.pfnci/linux/tests/benchmark.Dockerfile
.pfnci/linux/tests/benchmark.head.Dockerfile
.pfnci/linux/tests/cuda-example.Dockerfile
.pfnci/linux/tests/cuda-head.Dockerfile
.pfnci/linux/tests/cuda-slow.Dockerfile
.pfnci/linux/tests/cuda110.Dockerfile
.pfnci/linux/tests/cuda110.multi.Dockerfile
.pfnci/linux/tests/cuda111.Dockerfile
.pfnci/linux/tests/cuda111.multi.Dockerfile
.pfnci/linux/tests/cuda112.Dockerfile
.pfnci/linux/tests/cuda112.multi.Dockerfile
.pfnci/linux/tests/cuda113.Dockerfile
.pfnci/linux/tests/cuda113.multi.Dockerfile
.pfnci/linux/tests/cuda114.Dockerfile
.pfnci/linux/tests/cuda114.multi.Dockerfile
.pfnci/linux/tests/cuda115.Dockerfile
.pfnci/linux/tests/cuda115.multi.Dockerfile
.pfnci/linux/tests/cuda116.Dockerfile
.pfnci/linux/tests/cuda116.multi.Dockerfile
.pfnci/linux/tests/cuda117.Dockerfile
.pfnci/linux/tests/cuda117.multi.Dockerfile
.pfnci/linux/tests/cuda118.Dockerfile
.pfnci/linux/tests/cuda118.multi.Dockerfile
.pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
.pfnci/linux/tests/setup/update-alternatives-cutensor.sh

cuTENSOR's deb/rpm packages now setup libraries for CUDA 12 by default.
So it is needed to switch to the appropriate binary depending on the current CUDA version.
This was discovered during review of #7235 (https://ci.preferred.jp/cupy.linux.cuda-example/118609/).
```
00:25:57.151677 STDOUT 1621]	+ python3 cutensor/contraction.py	1.7s
00:25:58.826849 STDOUT 1621]	Traceback (most recent call last):	
00:25:58.826859 STDOUT 1621]	  File "cutensor/contraction.py", line 6, in <module>	
00:25:58.826866 STDOUT 1621]	    from cupyx import cutensor	
00:25:58.826990 STDOUT 1621]	  File "cupyx/cutensor.pyx", line 1, in init cupyx.cutensor	
00:25:58.827087 STDOUT 1621]	ImportError: libcublasLt.so.12: cannot open shared object file: No such file or directory	
```

CI: Support cuTENSOR 1.6.2 which defaults to CUDA 12

---

.pfnci/windows/test.ps1
cupy/__init__.py
cupy/_sorting/sort.py
tests/cupy_tests/binary_tests/test_elementwise.py
tests/cupy_tests/core_tests/test_core.py
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
tests/cupy_tests/math_tests/test_arithmetic.py
tests/cupy_tests/sorting_tests/test_sort.py

Refs #7243
https://numpy.org/devdocs/release/1.24.0-notes.html
Deprecated in NumPy 1.24:
* Deprecate msort
* np.str0 and similar are now deprecated
Expired deprecations in NumPy 1.24:
* The deprecation for the aliases np.object, np.bool, np.float, np.complex, np.str, and np.int is expired (introduces NumPy 1.20). Some of these will now give a FutureWarning in addition to raising an error since they will be mapped to the NumPy scalars in the future.

Update for deprecations in NumPy 1.24

---

cupy/cuda/compiler.py
cupy/cuda/jitify.pyx
install/cupy_builder/cupy_setup_build.py

This fixes a race condition in jitify that `cupy_headers` (static variable) being modified under `with nogil:`. Reported in https://github.com/cupy/cupy/issues/6793#issuecomment-1308791091 and https://github.com/cupy/cupy/issues/6793#issuecomment-1360368533.
Reproducer
```
$ export CUPY_CACHE_IN_MEMORY=1
$ ./test.py 10
```
`test.py`:
```py
import sys
import threading
import cupy
def run():
kern = cupy.RawKernel(code='''
#include <cupy/cuda_workaround.h>
#include <cupy/cub/cub/block/block_reduce.cuh>
#include <cupy/cub/cub/block/block_load.cuh>
extern "C" __global__ void mykernel() {}''', name='mykernel', jitify=True)
kern.compile()
threads = []
for i in range(int(sys.argv[1])):
threads.append(threading.Thread(target=run))
for t in threads:
t.start()
for t in threads:
t.join()
```

Fix race condition in Jitify

---

docs/source/user_guide/kernel.rst

#7107 
I added explanation for the first two entries of elementwise_copy() functions, and added the link of CUDA programming model for details.

Add explanation for JIT kernel.

---

cupy/_core/_routines_indexing.pyx
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py

Part of NumPy 1.24 support #7243.
NumPy 1.24:
```pycon
>>> import numpy as np
>>> np.arange(10)[[1,2,[3]]]
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
```
NumPy 1.23:
```pycon
>>> import numpy as np
>>> np.arange(10)[[1,2,[3]]]
<stdin>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
IndexError: only …
```

Check if the slice does not have inhomogeneous shape before converting it to array

---

cupy/_environment.py
install/cupy_builder/_command.py
install/cupy_builder/cupy_setup_build.py

This PR improves the import error message to output Windows DLL dependency in a format similar to `ldd` on Linux.
Unlike Linux, on Windows it is difficult for users to diagnose DLL dependency issues because the error message only says `The specified module could not be found`. This PR improves the error message as follows:
```pycon
...
File "C:\Users\maehashi\dev\cupy\cupy\__init__.py", line 17, in <module>
from cupy import _core  # NOQA
File "C:\Users\maehashi\dev\cupy\cupy\_core\__init__.py", line 3, in <module>
from cupy._core import core  # NOQA
File "cupy\_core\core.pyx", line 1, in init cupy._core.core
File "C:\Users\maehashi\dev\cupy\cupy\cuda\__init__.py", line 8, in <module>
from cupy.cuda import compiler  # NOQA
File …
```

Add function to diagnose Windows DLL load issue

---

.pfnci/windows/test.ps1
tests/cupy_tests/binary_tests/test_elementwise.py
tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
tests/cupy_tests/math_tests/test_arithmetic.py
tests/cupy_tests/sorting_tests/test_sort.py

Backport of #7245 by @kmaehashi
Only fixes in test code is backported as the v11 baseline API is NumPy 1.23.

[backport] Update for deprecations in NumPy 1.24

---

cupy/_core/_routines_manipulation.pyx
tests/cupy_tests/manipulation_tests/test_dims.py

Reported internally. `broadcast_to` should accept int as shape.
https://numpy.org/doc/stable/reference/generated/numpy.broadcast_to.html
> shape : tuple or int
> The shape of the desired array. A single integer i is interpreted as (i,).

Support passing int as shape to `broadcast_to`

---

cupy/__init__.py

Backport of #7245 for v11. (I forgot to do this in #7263)
This avoids emitting DeprecationWarning when importing CuPy in NumPy 1.24 environment.

[v11] Lazy load dtypes deprecated in NumPy 1.24

---

cupyx/tools/install_library.py

Follow up #7284.
Found in https://github.com/cupy/cupy-release-tools/pull/322 (https://ci.preferred.jp/cupy-release-tools/120571/)

Update cuTENSOR installer for CUDA 12.x

---

cupy/cuda/compiler.py

We noticed that kernel caching (`~/.cupy/kernel_cache`) is not working on CUDA 12.0. This is because PTX generated by CUDA 12.0 NVRTC includes identifiers randomly generated for every invocation.
CUDA 11.6 NVRTC:
```ptx
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-30794723
// Cuda compilation tools, release 11.6, V11.6.55
// Based on NVVM 7.0.1
//
.version 7.6
.target sm_61
.address_size 64
```
CUDA 12.0 NVRTC:
```ptx
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-31968024
// Cuda compilation tools, release 12.0, V12.0.76
// Based on NVVM 7.0.1
//
.version 8.0
.target sm_90
.address_size 64
.global .align 8 .u64 _ZN53_INTERNAL_00000000_15_default_program_26edde23_8009862nv6target6detail9all_hostsE = 1;
.global .align 8 .u64 …
```

Fix kernel cache not working in CUDA 12.0

---

cupy/_core/__init__.py
cupy/_core/_kernel.pyx
cupy/_core/_routines_indexing.pyx
cupy/_core/_routines_math.pyx
cupyx/jit/_interface.py
tests/cupyx_tests/jit_tests/test_raw.py

Close #6523
cc: @ajflood @amathews-amd @kmaehashi @leofang @takagi

Use warp size from `runtime.getDeviceProperties`

---

setup.cfg
tests/cupy_tests/math_tests/test_misc.py

I found `pytest.mark.skipIf` in test code but it is not working (it should be `pytest.mark.skipif`).
Removed the decorator as it seems unneeded, and also enable checkign unused markers.
https://docs.pytest.org/en/7.1.x/example/markers.html#registering-markers

Remove invalid pytest markers and turn on strict mode

---

tests/cupy_tests/core_tests/test_ndarray_math.py

Part of https://github.com/cupy/cupy/issues/7243
```
E   AssertionError: Both cupy and numpy raise exceptions
E
E   cupy
E   Traceback (most recent call last):
E     File ".../cupy/testing/_loops.py", line 45, in _call_func
E       result = impl(*args, **kw)
E     File ".../tests/cupy_tests/core_tests/test_ndarray_math.py", line 72, in test_round_halfway_int
E       a *= xp.array(scale, dtype=dtype)
E     File ".../cupy/_creation/from_data.py", line 46, in array
E       return _core.array(obj, dtype, copy, order, subok, ndmin)
E     File "cupy/_core/core.pyx", line 2390, in cupy._core.core.array
E       cpdef _ndarray_base array(obj, dtype=None, bint copy=True, order='K',
E     File "cupy/_core/core.pyx", line 2414, in cupy._core.core.array
E       return _array_default(obj, dtype, order, …
```

Avoid int8 overflow warning in `TestRoundHalfway`

---

.pre-commit-config.yaml

> Warning: The 'files' field in hook 'ci-generate' is a regex, not a glob -- matching '/*' probably isn't what you want here

Fix pre-commit configuration error

---

cupy/_core/_kernel.pyx
cupy/cuda/memory.pxd
cupyx/distributed/_array.py
tests/cupyx_tests/distributed_tests/test_array.py

Adds a private experimental API `cupyx.distributed._array` that is wip and subject to change.
Currently it works with ufuncs and custom elementwise kernels but with lots of limitations.
This is only intra-node, won't support inter-node communication like dask does.

Initial experimental & private `cupyx.distributed._array` implementation

---

cupy/_core/dlpack.pyx
cupy/_core/include/cupy/dlpack/README.md
cupy/_core/include/cupy/dlpack/dlpack.h
tests/cupy_tests/core_tests/test_dlpack.py

Would fix #7144. Part of #7306.
This PR updates CuPy's DLPack support to the latest version (before the proposed ABI break).

Update DLPack to v0.8 to support bool arrays

---

cupy_backends/cuda/libs/profiler.pyx

Mark `cupy.cuda.profiler.initialize` deprecated as it is removed in CUDA 12

---

docs/requirements.txt

Closes #7374.
Let's stick with v0.11.0 until https://github.com/pydata/pydata-sphinx-theme/pull/1133 got merged.
discussion: https://github.com/pydata/pydata-sphinx-theme/issues/1161

Doc: downgrade pydata-sphinx-theme to v0.11.0

---

install/cupy_builder/_context.py
install/cupy_builder/cupy_setup_build.py
install/cupy_builder/install_build.py
tests/install_tests/test_build.py
tests/install_tests/test_cupy_builder/test_context.py
tests/install_tests/test_cupy_builder/test_features.py

This closes #5751.
(I'm going to use this one in v11 to support building NVTX1 on CUDA 12.0 / Windows)

Add `CUPY_INCLUDE_PATH` and `CUPY_LIBRARY_PATH` env vars

---

cupy/_statistics/histogram.py
cupy/cuda/cub.pyx
tests/cupy_tests/statistics_tests/test_histogram.py

Thanks @ogreen for reporting and providing the reproducer.
This PR adds a workaround to avoid CUB histogram from asking for unrealistic amount of workspace (NVIDIA/cub#613). For example, the reproducer (added as a standalone test) would ask for 91.6 GB of device memory on my system. The added workaround ensures that if such extreme cases happen, we fall back to CuPy's existing histogram implementation.
Note that the workaround is made as thin as possible, with the eventual removal in mind once it's fixed upstream. In `cub.pyx` we have never checked for unrealistic workspace requests (we always assume no OOM), and so I do not intend to make too much change, as it might need a separate PR to properly handle all CUB functions 😅

Work around a potential OOM error raised by CUB histogram 

---

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

Avoid `fillvalue` overflow in `cupyx.scipy.signal` test

---

cupy/_creation/ranges.py
tests/cupy_tests/creation_tests/test_ranges.py
tests/cupy_tests/indexing_tests/test_generate.py

Fix `arange()` to raise `TypeError` in boolean case

---

cupy/fft/_fft.py

This changes the fftshifts to generate the amount of shift for each shifted axis and then execute the shift with a single call to cupy roll. For 1D shifts (i.e., where there is a single axis being shifted, regardless of the dimension of the array) there is no effective change, but for shifts along multiple axes, this decreases the amount of working memory required. Specifically, for an array of size N, and shifting along k axes, this requires only O(N) memory instead of O(kN) memory as before.
For FFTs that take most of the GPU's memory, this can mean the difference between completing the computation and an out of memory error or having to chunk the computation.

Change implementation of fftshift and ifftshift

---

tests/cupy_tests/core_tests/test_core.py

Avoid int8 overflow in core test

---

cupyx/scipy/spatial/distance.py

Added user-friendly runtime error in cupyx.scipy.spatial.* functions replacing previous "pairwise_distance not defined" error .
**Linked Issue** : #7406

Added runtime error if pylibraft unavailable

---

docs/source/install.rst

Splines use banded linear algebra, which we emulate with sparse solvers, and those are not available on ROCm, so document the limitation.

DOC: cupyx.interpolate: document limitations on ROCm

---

cupy/cuda/device.pyx
tests/cupy_tests/cuda_tests/test_device.py

This reverts #5853 as discussed in #6965.
Closes #6965 and #7315.
I've tested interoperability with PyTorch and looks working as expected:
```py
import cupy
import torch
dev1 = cupy.cuda.Device(1)
with dev1:
t1 = torch.arange(10, device='cuda')
assert 'cuda:1' == str(t1.device)
assert ((t1 - torch.from_dlpack(cupy.arange(10))).sum() == 0).item() is True
with torch.cuda.device(2):
t2 = torch.arange(10).cuda()
assert 'cuda:2' == str(t2.device)
assert cupy.cuda.Device().id == 2
with dev1:
assert 1 == torch.cuda.current_device()
assert cupy.cuda.Device().id == 1
assert 0 == torch.cuda.current_device()
```
cc/ @leofang

Revert cupy.cuda.Device behavior to v9

---

.github/workflows/backport.yml
.github/workflows/flexci.yml
.pfnci/BRANCH
.pfnci/coverage.rst
.pfnci/linux/tests/actions/benchmark.sh
.pfnci/matrix.yaml
.pre-commit-config.yaml
README.md
docs/source/conf.py
docs/source/contribution.rst
docs/source/user_guide/kernel.rst

Closes #7294.
Note: backport to v12 must exclude changes to BRANCH file.

Update branch name from `master` to `main`

---

cupy/_core/internal.pyx
tests/cupy_tests/creation_tests/test_from_data.py

In this case, NumPy will prefer the C contiguous strides, not the F contiguous ones.
I will note that I do not think users should reuly on strides if they rely on contiguity, and the old strides could be considered just as valid as the new one.
Just as NumPy the strides of an F- and C-contiguous array created as an F-contiguous one will have strides mutate on copy after this. Currently, this happens for C contiguous ones.
Closes gh-5897

BUG: Fix new strides when array is both C and F-contiguous

---

.pfnci/config.pbtxt
.pfnci/config.tags.json
.pfnci/coverage.rst
.pfnci/generate.py
.pfnci/linux/tests/cuda121.Dockerfile
.pfnci/linux/tests/cuda121.multi.Dockerfile
.pfnci/linux/tests/cuda121.multi.sh
.pfnci/linux/tests/cuda121.sh
.pfnci/matrix.yaml
.pfnci/schema.yaml
.pfnci/windows/_flexci.ps1
cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.h

Depends on ~#7472~ (merged)
Ref #7441, #7378, #7471
CI for CUDA 12.1:
* https://ci.preferred.jp/cupy.linux.cuda121/126591/
* https://ci.preferred.jp/cupy.linux.cuda121.multi/126592/
* https://ci.preferred.jp/cupy.win.cuda121/126632/

Support CUDA 12.1

---

tests/cupyx_tests/linalg_tests/test_solve.py

Closes #7309.
Skip tests as we are using CUDA 12.0.1 on Linux (note that `nvidia/cuda:12.0.0-*` Docker images actually contains libraries from CUDA 12.0.1) and CUDA 12.0.0 on Windows.

Remove xfail for invh

---

cupy/_core/core.pyx
tests/cupy_tests/creation_tests/test_from_data.py

This is a small followup to also prefer C order over F when converting from a NumPy array.
I had not realized that the original issue mentioned another similar path where it may be better to prefer C order strides (just for symmetry to NumPy, since I don't think the strides were ever wrong).

Fixup array/asarray call to prefer C order on plain NumPy arrays

---

cupy_backends/cuda/_softlink.pyx

Fixes:
```
warning: cupy_backends/cuda/_softlink.pyx:43:4: Unreachable code
warning: cupy_backends/cuda/_softlink.pyx:53:4: Unreachable code
```

Fix cythonize warnings

---

README.md
docs/source/install.rst

Starting in CuPy v12, aarch64 wheels are now on PyPI.

Update aarch64 install insturctions

---

cupyx/scipy/interpolate/__init__.py
cupyx/scipy/interpolate/_interpolate.py
docs/source/reference/scipy_interpolate.rst
tests/cupyx_tests/scipy_tests/interpolate_tests/test_ppoly.py

Add NdPPoly to cupyx.scipy.interpolate

---

cupy/testing/_array.py

Added `strict` option to the two related functions `assert_array_equal()` and `assert_array_list_equal()` conforming to the respective new feature in NumPy 1.24, discussed in #7250.
_[This is my very first PR in a big project. Let me know if I violated anything :) ]_

Support NumPy 1.24: Adding `strict` option to `testing.assert_array_equal`

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_splines.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py

Depends on https://github.com/cupy/cupy/pull/7511

Add symiirorder2 to cupyx.scipy.signal

---

cupyx/scipy/special/__init__.py
cupyx/scipy/special/_basic.py
docs/source/reference/scipy_special.rst
tests/cupyx_tests/scipy_tests/special_tests/test_exprel.py

Adds `cupyx.scipy.special.exprel`
Benchmarks:
size | dtype | SciPy | CuPy
-----|-------|-------|-----
1000 | float32 | 0.137 ms | 0.092 ms
1000 | float64 | 0.030 ms | 0.309 ms
100000 | float32 | 1.972 ms | 0.149 ms
100000 | float64 | 1.685 ms | 0.270 ms
1000000 | float32 | 26.247 ms | 0.414 ms
1000000 | float64 | 22.007 ms | 2.114 ms
<details>
<summary>Script</summary>
```
import cupy
import cupyx
import cupyx.scipy.stats
import scipy
import scipy.stats
n_warmup = 1
n_repeat = 10
dtype_set = ('float32', 'float64')
n_set = (1000, 100000, 1000000)
def get_time(pref):
cpu_time = pref.cpu_times.mean()
gpu_time = pref.gpu_times.mean()
return max(cpu_time, gpu_time) * 1000  # ms
def time(a):
cp_a = cupy.array(a)
times = []
perf = …
```

add `cupyx.scipy.special.exprel`

---

cupy/_manipulation/join.py
tests/cupy_tests/manipulation_tests/test_join.py

Following the items listed in #7250, adding `dtype` and `casting` keyword arguments for `hstack`, `vstack`, `stack`.
The addition of these kwargs should not make CuPy incompatible with NumPy versions before 1.24, as the under-the-hood `concatenate` supports these two kwargs since NumPy 1.20.

Support NumPy 1.24: `dtype` and `casting` keyword arguments for `hstack`, `vstack`, `stack`

---

tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline.py

This diff asserts that design matrix test raises ValueError when `extrapolate=False`

Fix TestBSpline::test_design_matrix_same_as_BSpline_call

---

cupyx/scipy/signal/_arraytools.py
cupyx/scipy/signal/_signaltools.py

Followup to https://github.com/cupy/cupy/pull/7442
This is necessary after trying to benchmark symiirorder1/symiirorder2, where it was found out that the starting state concatenation for the FIR pass caused several delays due to additional copy operations, specially on huge inputs where CuPy outperforms SciPy. 
In order to prevent unnecessary operations, this PR prevents input manipulation when the FIR order is less than two, thus preventing additional calls when an IIR filter is applied (such as the `symiirorder` filter family). It also reduces the quantity of copy operations by replacing `concatenate` with slice manipulation.
It also handles cases where the FIR convolution is not being computed properly by padding the input with zeros at the beginning, this introduces an additional …

Replace concatenate by slice manipulation in lfilter

---

cupyx/scipy/special/__init__.py
cupyx/scipy/special/_spherical_bessel.py
docs/source/reference/scipy_special.rst
tests/cupyx_tests/scipy_tests/special_tests/test_spherical_bessel.py

This PR adds `scipy.special.spherical_yn`.
This implementation supports real numbers and uses almost the same algorithm as in scipy.
Calculation for complex number requires other unimplemented Bessel functions, and therefore not supported in this PR.
Linked Issue : #6324

Add `scipy.special.spherical_yn`

---

tests/cupyx_tests/scipy_tests/special_tests/test_exprel.py

Hi Team, apologies for the delay in PR, came down with a fever. 
This PR follows the https://github.com/cupy/cupy/pull/7474#issuecomment-1512348466 comment and imports SciPy in `cupyx.scipy.special.exprel` tests.

Import SciPy in tests

---

tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py

Following up #7511 and #7518.
We can see some signal filter fixes on SciPy 1.9.0 release.
https://docs.scipy.org/doc/scipy/release.1.9.0.html
This fixes https://ci.preferred.jp/cupy.linux.cuda115/128715/

Require newer SciPy in a test

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_arraytools.py
cupyx/scipy/signal/_signaltools.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

This is basically a line-per-line port from SciPy, the only changes are related to the initial state differences between CuPy and SciPy's `lfilter` implementation

Add filtfilt to cupyx.scipy.signal

---

cupy/cuda/texture.pyx
cupy_backends/cuda/api/runtime.pxd
cupy_backends/cuda/api/runtime.pyx

Close #7533.
I belive commit ec99a210875f3af3c383d78a8fbd810500cac4ab is the real fix; commit 6db0ea9373402bbcfe30d7d36b4fe2a119ec44da is just nice-to-have (if any error happens, `ptr` remains 0 and `free(0)` should be a no-op).
Unfortunately, none of the reproducers offered by @kalvdans in #7533 would trigger the error, so I did not add any test. But I believe the change should work.

Fix cudart errors raised by texture APIs swallowed by Cython 

---

cupy/random/_bit_generator.pyx
cupy/random/_generator_api.pyx
cupy/random/cupy_distributions.cu
cupy/random/cupy_distributions.cuh

Simplified the code, added missing support for fp32 and changed the splitting by state to be inside the kernel so its much clearer and faster now.
Performance using a simplified script from #7515
Main/Master
```
********
TIMING STANDARD NORMAL
********
********************************************************
Timing `standard_normal` with array size 100000, shape: (100000,)...
Benchmarking cp.random.standard_normal ...
<lambda>            :    CPU:    27.143 us   +/-  1.011 (min:    26.302 / max:    38.236) us     GPU-0:    30.346 us   +/-  1.230 (min:    28.672 / max:    41.984) us
Benchmarking [cp.random.XORWOW()].standard_normal ...
<lambda>            :    CPU:    30.759 us   +/-  6.240 (min:    23.974 / max:    38.324) us     GPU-0:    33.915 us   +/-  6.275 (min:    25.600 / max: …
```

Fix random module performance regression

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_iir_utils.py
cupyx/scipy/signal/_signaltools.py
tests/cupyx_tests/scipy_tests/signal_tests/test_iir_utils.py
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

This implementation will contemplate the performance against the following baselines:
1. N sequential calls to `lfilter`, where each one of them computes each second order section.
3. N calls to convolve1d  to compute the FIR part and a extension of the `apply_iir` kernel to chained second order sections (the kernel would compute the IIR part from the FIR output in a chained fashion).
4. A generalization of `apply_iir` where the function would compute both FIR and IIR sections sequentially one after another with custom kernels for both parts.
If the third option improves the performance, then it would be possible to think about improving `lfilter` this route.

Add sosfilt to cupyx.scipy.signal 

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_iir_filter_conversions.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_conversion.py

cross-ref gh-7403
Add IIR filter converters in the TF and ZPK formats:
All is pure python. Much of the content can be moved to cuda kernels, but inputs are typically very short, so not sure if this is worth it.
https://github.com/cupy/cupy/pull/7537#issuecomment-1537144791 is relevant, will need to update the PR with the outcome of that discussion.

cupyx.scipy.signal: add bilinear & bilinear_zpk

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_signaltools.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

Add `cupux.scipy.signal.detrend`. This is fairly trivial subtraction of a linear LSQ fit from the input, real work is done in `lstsq`, so the rest can stay in pure python. 
Tests are mirroring those in scipy.signal, the corresponding scipy PR is https://github.com/scipy/scipy/pull/18383

ENH: scipy.signal: add detrend

---

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

After https://github.com/cupy/cupy/pull/7496, some failures started to appear in the `cuda102` CIs regarding `nan` and zeros mismatches. Since these errors do not appear (and cannot be reproduced) in CIs that run newer CUDA versions, they are most probably related to unstable input coefficients which cause `lfilter_zi` to be `nan`, which then when they are applied to a signal that is zero, it will output `nan` as opposed to zero.

Try to fix nan value mismatches in filtfilt tests

---

install/cupy_builder/_command.py

The feature added in #7279 was not working in shipped wheels as the `_depends.json` file is not included in the wheel.
c.f. https://github.com/pypa/setuptools/issues/1064

Fix `_depends.json` not included in wheel

---

README.md
docs/source/install.rst

Recently we are getting more reports of installation failures, and it looks most issues are happening with CuPy wheels installed on conda env. This PR adds the instruction for Conda users to README to promote using packages from conda-forge.
This PR also removed Coveralls badge which is out-dated, and added several wording improvements.

Improve README and Installation Guide

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_iir_filter_conversions.py
cupyx/scipy/special/__init__.py
cupyx/scipy/special/_ellip.py
docs/source/reference/scipy_special.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_conversion.py
tests/cupyx_tests/scipy_tests/special_tests/test_ellipk.py

filter design "prototypes"

---

.github/ISSUE_TEMPLATE/bug.yml

Fixes the command line so that Windows users can copy-and-paste and run.

Fix command in issue template for Windows

---

.flake8.cython
.pre-commit-config.yaml
cupy/_core/core.pyx

This had to be in #7595 to enable flake8 lint against Cython.
I think these config can be removed after a certain period of time, once #7508 got merged.

Fix flake8-cython not working

---

cupyx/scipy/sparse/linalg/_eigen.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Sometimes a good initial guess for an eigenvector is known and it is advantageous to use it within the eigensolver. This patch adds the keyword argument ``v0`` to ``eigsh`` so that it behaves in the same way as in ``scipy.sparse.linalg``.

Let the user specify a starting vector for eigsh.

---

.github/workflows/pretest.yml

`restore-keys` were not working since #7546... :bow:

Fix build-cuda test `restore-keys` not working

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_czt.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_czt.py

Adapt code and its tests from scipy.
Heavy lifting is all done in `cupyx.fft`, so the rest is kept in pure python.
cross-ref gh-7403

cupyx.scipy.signal: add CZT and ZoomFFT

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_signaltools.py
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

Depends on https://github.com/cupy/cupy/pull/7528
This PR is an extension of `lfilter_zi`, which uses the same principle applied to chained second order sections.

Add sosfilt_zi to cupyx.scipy.signal

---

cupy/_core/new_fusion.pyx
cupy/_core/raw.pyx
cupy/cuda/cufft.pyx
cupy_backends/cuda/libs/cublas.pyx
cupy_backends/cuda/libs/cudnn.pyx

Found by cython-lint in #7508 review. Also removes some more `no-cython-lint`s.

Fix returned CUDA statuses not being checked

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_signaltools.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

ENH: cupyx.scipy.signal: add hilbert and hilbert2

---

install/universal_pkg/setup.py

Fixes #7593.
`META_VERSION` has been introduced to allow releasing a hot-fix for `cupy-wheel`, e.g., `cupy-wheel==12.1.0.post1` install `cupy-cuda12x==12.1.0`.

Fix `cupy-wheel` package installation fails with pip 23.1+

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_iir_filter_conversions.py
cupyx/scipy/signal/_iir_filter_design.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_conversion.py
tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_design.py

Add `iirfilter` and its matlab-styled aliases. While at it, add converters from zero-poles-gain format to transfer function and SOS formats:
.
What's missing / suboptimal:
- bessel filters. This requires finding roots of certain Bessel functions, will port separately.
- zpk2sos loses precision for higher order filters. This happens on CUDA for lower orders than than in NumPy, can be traced to `xp.convolve` based multiplication of polynomials. Will investigate separately.
<s>This PR is based off gh-7553, will rebase once that one is ready. For now, only commits starting from https://github.com/cupy/cupy/pull/7591/commits/fe2dfe4985ea3885f274f00d7a47eeb2af88cd51 are revelant.</s> rebased

add iirfilter and related filter design functions

---

tests/cupy_tests/random_tests/test_generator.py

TestChoiceChi::test_goodness_of_fit(https://github.com/cupy/cupy/blob/main/tests/cupy_tests/random_tests/test_generator.py#L830) is sensitive to data randomness and fails on ROCm with its current setup. The test generates random numbers using cupy random generator, which is seeded with random numbers from numpy.random(https://github.com/cupy/cupy/blob/main/cupy/testing/_random.py#L90). 
The numpy.random is hardcoded to a seed of 100(https://github.com/cupy/cupy/blob/main/cupy/testing/_random.py#L37). 
The test runs for 10 test cases following the seed, but one of them fails on ROCm, which is fine based on significance level used for the test(more details in https://github.com/cupy/cupy/issues/7544). This PR changes test passing condition to let it pass on ROCm as mentioned here - …

Change test pass condition for TestChoiceChi::test_goodness_of_fit

---

install/universal_pkg/setup.py

Backport of #7597 by @kmaehashi
**This PR targets the hotfix branch `hotfix-v12.1.0.post1`, which is branched from `v12.1.0` tag.**

[hotfix] [backport] Fix `cupy-wheel` package installation fails with pip 23.1+

---

cupy/__init__.py
cupy/_math/rounding.py
cupyx/scipy/special/__init__.py
tests/cupy_tests/core_tests/fusion_tests/test_routines.py
tests/cupy_tests/math_tests/test_rounding.py
tests/cupyx_tests/scipy_tests/fft_tests/test_fftlog.py

`numpy.round_` will be deprecated in NumPy 1.25.

Deprecate `cupy.round_`

---

cupyx/jit/thrust.py

This commit just fixes a couple of spelling typos.
Background: I'm doing a research study on function comments that may be incorrect. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
 
Thanks for reviewing!

Fix small typos in docstrings

---

tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py
tests/cupyx_tests/scipy_tests/signal_tests/test_iir_filter_design.py

Older CUDA versions seem to have precision issues, had to make test tolerances *very* loose. So instead tighten tolerances, conditionally skip tests on older CUDA versions.
As suggested in https://github.com/cupy/cupy/pull/7591#issuecomment-1586561815

cupyx/signal: skip tests against older SciPy versions, adjust test tolerances

---

.github/workflows/pr-project.yml
.github/workflows/pr-updated.yml

This fixes the problem that:
* The workflow is triggered even if it is an issue, e.g., https://github.com/cupy/cupy/actions/runs/5330383404/jobs/9657009231
* The workflow fails if pull-request is closed, e.g. https://github.com/cupy/cupy/actions/runs/5332268592
* Limit triggering workflows for many times

Fix project automation to skip when pull-request is already closed

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_fir_filter_design.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py

<s>This PR is on top of gh-7537 to minimize git conflicts  going forward.</s>

ENH: add `cupyx.scipy.signal.minimum_phase`

---

tests/cupy_tests/math_tests/test_rounding.py
tests/cupyx_tests/scipy_tests/fft_tests/test_fftlog.py

[v12] Require numpy<1.25 for `round_` tests

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_filter_design.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py

As discussed on gitter, this PR delegates to `numpy.roots`  on CPU. The issue is that root-finding is typically done as the eigenvalue problem for the companion matrix, but `eigvals` is only available in MAGMA which is not a CuPy dependency.
<s>PR is on top of https://github.com/cupy/cupy/pull/7638 , will rebase</s> rebased.

ENH: add cupyx.signal.{freqs, freqs_zpk, findfreqs}

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Locally confirmed that the test passes with CUDA 12.1.0, and fails with CUDA 12.1.1.

Skip `TestLOBPCG::test_maxit_None` in CUDA 12.1.1 & cuSOVLER 11.4.5

---

cupy/__init__.py
cupy/_indexing/insert.py
cupy/_logic/truth.py
cupy/_math/sumprod.py
tests/cupy_tests/logic_tests/test_truth.py
tests/cupy_tests/math_tests/test_sumprod.py

Part of #7616.
Deprecated in NumPy 1.25.

Deprecate `product`, `cumproduct`, `alltrue` and `sometrue`

---

.pfnci/linux/tests/cuda112.Dockerfile
.pfnci/linux/tests/cuda112.multi.Dockerfile
.pfnci/linux/tests/cuda114.Dockerfile
.pfnci/linux/tests/cuda114.multi.Dockerfile
.pfnci/linux/tests/cuda115.Dockerfile
.pfnci/linux/tests/cuda115.multi.Dockerfile
.pfnci/linux/tests/cuda116.Dockerfile
.pfnci/linux/tests/cuda116.multi.Dockerfile
.pfnci/linux/tests/cuda117.Dockerfile
.pfnci/linux/tests/cuda117.multi.Dockerfile
.pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
.pfnci/linux/tests/cuda120.Dockerfile
.pfnci/linux/tests/cuda120.multi.Dockerfile
.pfnci/linux/tests/cuda121.Dockerfile
.pfnci/linux/tests/cuda121.multi.Dockerfile
.pfnci/schema.yaml

Ref #7548
Outdated minor versions will be removed from Docker Hub:
https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/container_tags.pdf
https://gitlab.com/nvidia/container-images/cuda/-/issues/209

Bump CUDA minor versions used in CI

---

cupy_backends/cuda/libs/cusparse.pyx
cupy_backends/hip/cupy_hipsparse.h
cupy_backends/stub/cupy_cusparse.h
tests/cupy_tests/cuda_tests/test_cusparse.py

The error code `CUSPARSE_STATUS_INSUFFICIENT_RESOURCES` (11) was missing in the mapping.
This fixes `CuSparseError` to generate an error message using `cusparseGetError` and `cusparseGetErrorString` available since CUDA 10.2.
Closes #7677.

Fix cuSPARSE error message

---

cupy/cuda/memory.pyx
tests/cupy_tests/cuda_tests/test_memory.py

This fixes the problem that CuPy memory allocator does not call `free_all_blocks()` / `gc.collect()` when the limit is set, causing an OOM error immediately if the memory chunk is fragmented.
Closes #7678.

Fix memory pool to try resolve fragmentation when limit is set

---

.pfnci/linux/tests/cuda-rapids.Dockerfile
cupyx/scipy/sparse/csgraph/_traversal.py
tests/cupyx_tests/scipy_tests/sparse_tests/csgraph_tests/test_traversal.py

A breaking `pylibcugraph` [PR](https://github.com/rapidsai/cugraph/pull/2866/files) updated the function signature of weakly connected components thereby breaking the weak connection of CuPy `connected components`. Furthermore, both `pylibcugraph` strongly and weakly connected components no longer returns ordered labels and the starting value is now 0. 
This PR updates the `pylibcugraph.weakly_connected_components` call in cupy `connected_components` along with the tests to always adjust labels since in most cases, the labels returned by both CuPy and SciPy are un-ordered.
closes #7672

Update pylibcugraph weakly connected components call

---

.pfnci/generate.py
.pfnci/linux/tests/cuda102.Dockerfile
.pfnci/linux/tests/cuda102.multi.Dockerfile
.pfnci/schema.yaml

This is a manual backport of #7689.
As CUDA 10.2 docker image has been removed (#7548), I've made a mirror repository at https://hub.docker.com/r/cupy/nvidia-cuda/tags. The repository is only for CuPy CI, and only minimal copies of images required for CI are mirrored.

[v12] Allow specifying Docker repository for CI images

---

cupy/_core/_routines_linalg.pyx
cupy_backends/cuda/api/_runtime_enum.pxd
cupy_backends/cuda/libs/cublas.pxd
cupy_backends/cuda/libs/cublas.pyx

This PR adds mixed precision support for matrix-matrix multiplies on ROCm, which is available in hipBLAS through `hipblasGemmEx`. On MI200 GPUs, this utilizes the MFMA (matrix fused-multiply add) instructions, which are intended as analogues of the NVIDIA tensor cores.
For `cupy.float16` arrays, we allow the use of the hipBLAS primitive, which was previously disabled, and fp16 values were casted to single precision, albeit issuing a warning. I am not entirely sure if the reason for this was the lack of hardware and/or API support in earlier versions of the AMD libraries, therefore a version check for hipBLAS might be required. It appears though that support has been stable since ROCm 4.2.0 (https://github.com/ROCmSoftwarePlatform/hipBLAS/blob/develop/CHANGELOG.md).
To verify that the code …

Add mixed precision (FP16) support for ROCm

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_fir_filter_design.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py

add kaiser{ord,_beta,_atten} functions

---

.github/workflows/flexci.yml

Currently, list of CI tags ("/test TAGS") are always read from main branch for pull-requests. As a result, "/test" comments in PRs targetting v12 branch did not fire tests for CUDA 10.2-11.1 as they are removed from the main branch.

Use "/test" tag configuration from pull-request base branch

---

.github/workflows/pr-project.yml
.github/workflows/pr-updated.yml

- `@octokit/app.js` dropped support for node v16 and stopped working. https://github.com/octokit/app.js/releases/tag/v14.0.0 Use external action to generate GitHub App token instead of doing it on our own.
- Remove concurrency restriction to avoid noisy "Cancelled" notification to contributors.

Fix project update workflow

---

cupy/_statistics/correlation.py

Fixes: #7697 
A quick typo fix only.

fix a typo in `cupy.cov`

---

install/cupy_builder/_context.py

Introduces the env var `CUPY_INSTALL_NO_RPATH=1` which disables RPATH embedding.
RPATH embedding is disabled in wheels through `python setup.py bdist_wheel --cupy-no-rpath` argument, but I'd like to add an option to disable RPATH through env var so that it can be used when `pip install -e`.
By disabling RPATH, locally-built CuPy binaries can utilize CUDA enhanced compatibility. This is very handy when testing the local build against various CUDA versions, e.g.:
```
LD_LIBRARY_PATH=/usr/local/cuda-11.3.0/lib64 python -c 'import cupy; cupy.show_config()'
LD_LIBRARY_PATH=/usr/local/cuda-11.4.0/lib64 python -c 'import cupy; cupy.show_config()'
```
This option is for developers, and thus I'm thinking of keeping this undocumented.

Add env var to disable RPATH

---

cupyx/cusparse.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/test_cusparse.py

This fixes the following test failure:
CUDA 11.2 on Windows:
https://ci.preferred.jp/cupy.win.cuda112/136285/
```
tests/cupyx_tests/test_cusparse.py::TestSpgemm::test_spgemm_ab[_param_6_{dtype=complex128, shape=(2, 3, 4)}] Windows fatal exception: access violation
Current thread 0x00000e50 (most recent call first):
File "C:\Users\chainer\cupy\cupyx\cusparse.py", line 2081 in spgemm
File "C:\Users\chainer\cupy\tests\cupyx_tests\test_cusparse.py", line 390 in test_spgemm_ab
File "C:\Development\Python\Python39\lib\site-packages\_pytest\python.py", line 194 in pytest_pyfunc_call
File "C:\Development\Python\Python39\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
File "C:\Development\Python\Python39\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
File …
```

XFAIL known test failures in cuSPARSE module

---

.github/workflows/pretest-rocm-test.sh
.github/workflows/pretest.yml

CI failing as Cython 3.0.0 is out. Fix the version to Cython 0.29.* for now.

CI: remove explicit Cython installation

---

cupy/linalg/_einsum_cutn.py
docs/source/conf.py

1. Update link to cuQuantum docs (the old link will soon be invalidated!)
2. Restore `cupy.einsum()`'s async behavior when dispatching to cuTensorNet
3. ~~Support computing trace `ii->` with cuTensorNet~~
- I still see issues with general singleton expressions, so I disable it for now
4. Support multi-threading (each thread will use its own handle)
5. Fix leaking the handle at shutdown
Recall that currently the CI does not test this integration, so manual testing is still required:
```
pip install cuquantum-python-cu11  # or -cu12 for CUDA 12
CUPY_ACCELERATORS=cub,cutensornet pytest tests/cupy_tests/linalg_tests/test_einsum.py
````
Please kindly backport this PR, thanks! 😅

Minor updates for cuQuantum/cuTensorNet support

---

tests/cupyx_tests/scipy_tests/fft_tests/test_fftlog.py

[backport] Fix `test_fht` not to feed `cupy.ndarray` to `scipy.fft.fhtoffset`

---

cupyx/scipy/signal/_filter_design.py
cupyx/scipy/signal/_polyutils.py

Trivial code health tweak: remove a duplicate wrapper for `np.roots`, so that all calls go through the _polyutils version. Will also be easier to remove if/when CuPy grows a general unsymmetric eigenvalue solver.

MAINT: centralize np.roots calls

---

cupyx/distributed/_nccl_comm.py

`op` is not a supported parameter for `all_gather(in_array, out_array, count, stream=None)`
original code: https://github.com/cupy/cupy/blob/main/cupyx/distributed/_nccl_comm.py#L206

Remove incorrect `cupyx.distributed.NCCLBackend.all_gather` comment

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_iir_filter_conversions.py
cupyx/scipy/signal/_ltisys.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_cont2discrete.py
tests/cupyx_tests/scipy_tests/signal_tests/test_dltisys.py
tests/cupyx_tests/scipy_tests/signal_tests/test_ltisys.py

.
.
.
Also add the matrix exponential, `cupyx.scipy.linalg.expm` (needed for lsim, cont2discrete).

ENH: add LTI class hierarchy and lti/dlti related functions

---

cupy/_core/include/cupy/_cuda/README.md
cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.h
cupy/_core/include/cupy/_cuda/cuda-12/cuda_fp16.hpp

Follows-up #7748. FP16 headers from CUDA 12.2.0 added dependency to `vector_types.h`, `vector_functions.h`, `cuda_runtime_api.h`, etc., causing compilation errors in environment without these headers.
CUDA 12.1.1:
```
% grep '#include' /usr/local/cuda-12.1.1/include/cuda_fp16.h
/usr/local/cuda-12.1.1/include/cuda_fp16.h:#include "cuda_fp16.hpp"
```
CUDA 12.2.0:
```
% grep '#include' /usr/local/cuda-12.2.0/include/cuda_fp16.h
/usr/local/cuda-12.2.0/include/cuda_fp16.h:#include "vector_types.h"
/usr/local/cuda-12.2.0/include/cuda_fp16.h:#include "vector_functions.h"
/usr/local/cuda-12.2.0/include/cuda_fp16.h:#include "cuda_fp16.hpp"
% grep '#include' /usr/local/cuda-12.2.0/include/vector_types.h
#include "crt/host_defines.h"
% grep '#include' …
```

Revert FP16 headers from CUDA 12.2.0 to CUDA 12.1.1

---

docs/source/install.rst

Backport of #7777 by @kmaehashi

[backport] Add notes for CUDA 12.2 on Windows support

---

.github/workflows/publish.yml

Add a workflow to publish packages to PyPI to reduce the release effort.
This removes the need of manually downloading all baked wheels to local.

Add workflow to publish to PyPI

---

.github/workflows/publish.yml

Another minor fixes to https://github.com/cupy/cupy/pull/7779. Let me self-merge.
Uploading checked assets via `actions/upload-artifacts` was slower than expected (20+ minutes). Let's upload directly from GitHub Releases.

Improve publish workflow

---

.github/workflows/publish.yml

Minor fix to #7779. Fix broken permission. Let me self merge.

Fix publish workflow permission and output for review

---

docker/rocm/Dockerfile

This PR fixes the issue that ROCm Docker images not working due to missing `hipfft` and `LD_LIBRARY_PATH`. Also, now that Ubuntu 18.04 and Python 3.8 are deprecated in CuPy v13, we have to migrate to Ubuntu 20.04 and Python 3.9 instead.
To prevent the future error, I've added `RUN python3 -c "import cupy; cupy.show_config()"` line to verify that CuPy can be imported.

Fix ROCm Dockerfile not working

---

cupy/lib/stride_tricks.py
tests/cupy_tests/lib_tests/test_strided_tricks.py

This pull request introduces the `sliding_window_view` function to CuPy, enhancing its alignment with the NumPy API. The addition of this feature allows users to create a sliding window view of n-dimensional arrays, providing powerful and flexible functionality for array manipulation. Please see #6078. 
- Implements the `sliding_window_view` function in CuPy, similar to its counterpart in the NumPy API.
- Resolves: Issue #6956 and part of #6078.  Also relevant to [cupy-xarray/9](https://github.com/xarray-contrib/cupy-xarray/issues/9)
The integration of this function enables a more seamless transition for users who switch between or use both NumPy and CuPy in their projects. 
Importantly, this feature is critical for Xarray-Cupy integration (see …

Add `cupy.lib.stride_tricks.sliding_window_view`

---

cupy/__init__.py
cupy/linalg/_norms.py
cupyx/scipy/sparse/linalg/_norm.py
cupyx/scipy/sparse/linalg/_solve.py
examples/gmm/gmm.py
tests/cupy_tests/linalg_tests/test_norms.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Hi!
Due to NumPy's main namespace being changed in https://github.com/numpy/numpy/pull/24357, here I update warning imports. Here I delete aliases that were decided to be removed.

ENH: Remove `NINF`, `PINF`, `Inf`,... usages

---

install/cupy_builder/_context.py
setup.py

(Not required for release.)
PyPI upload emits warning if `long_description_content_type` is not specified.
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#description

Avoid warning when uploading packages

---

cupyx/scipy/sparse/_csr.py

Close https://github.com/cupy/cupy/issues/7713.

Fix csr2dense to avoid race conditions

---

cupyx/cutensor.pyx
tests/cupyx_tests/test_cutensor.py

Close #7318. Close #7812.
The mode labels encapsulated by the `Mode` object should be cached, not just the pointer to it as the same memory could be garbage collected and reused, leading to erroneous cache hits. 
The added tests would fail without the fix.

Fix cuTENSOR contraction descriptor cache

---

.github/workflows/pretest.yml
cupy/_creation/basic.py
cupy/typing/_types.py
docs/source/conf.py
tests/typing_tests/.gitignore
tests/typing_tests/cupy_tests/creation_tests/test_basic.pyi
tests/typing_tests/mypy.ini
tests/typing_tests/test_typing.py

Part of https://github.com/cupy/cupy/issues/4831.
Blocked by ~https://github.com/cupy/cupy/pull/7738~ (merged).

Add type annotation in _creation.basic

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_spectral.py
cupyx/scipy/signal/_spectral_impl.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py

This is the first spectral analysis function ported from CuSignal, the port was 1:1, there was no need to introduce additional changes, since the kernel already worked from CuPy

Port lombscargle from CuSignal to cupyx.scipy.signal

---

cupy_backends/cuda/libs/nccl.pyx

Since there are no official nccl bindings from nvidia, there is no method of using NCCL from python or other libraries outside of cuPy. By allowing the cuPy nccl handle to be directly accessed, cuPy can interop with other NCCL enabled libraries by passing the nccl handle direclty.

Add a property to get access to the nccl handle.

---

cupy/cuda/__init__.py
cupy/cuda/device.pyx

These flags have been marked deprecated in CuPy v8.

Remove `cusolver_enabled`, `cub_enabled`, `thrust_enabled` flags

---

cupy_backends/cuda/libs/nvrtc.pyx

Fix nvrtc initialize not inlined for CUDA Python

---

.github/workflows/pretest.yml
cupy/cuda/__init__.py
cupy/cuda/device.pyx
cupy/linalg/_decomposition.py
cupy/linalg/_eigenvalue.py
cupyx/lapack.py
cupyx/linalg/sparse/_solve.py
cupyx/scipy/linalg/_decomp_lu.py
cupyx/scipy/sparse/linalg/_solve.py

This is a part of #7620.
I tried to softlink cuSOLVER as I did in NVRTC but found there is a native function calls to cuSOLVER in [`cupy_lapack.h`](https://github.com/kmaehashi/cupy/blob/401c3243a5d3bf88eaa1fe79572050609e788020/cupy_backends/cupy_lapack.h) where softlink doesn't work.
For cuSOLVER I'm thinking of using lazy-import instead of softlink.
Depends on ~#7840~ (merged).

Lazy import cuSOLVER

---

cupy/_indexing/generate.py
cupyx/scipy/signal/_splines.py
tests/cupy_tests/indexing_tests/test_generate.py
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

After https://github.com/cupy/cupy/pull/7651, `cupy_r` stopped working with floating point scalars, which were being interpreted as integer ones. This was due to the use of the positions of the values (integer values) as opposed to the values themselves.
For example:
See https://github.com/cupy/cupy/pull/7721#issuecomment-1688923731

Fix handling of scalars in cupy.r_

---

.github/workflows/pretest.yml
tests/typing_tests/cupy_tests/creation_tests/test_basic.pyi
tests/typing_tests/test_run.py

Part of https://github.com/cupy/cupy/issues/4831.

Execution tests for typing tests passing rows in `typing_tests`

---

install/cupy_builder/_command.py
install/cupy_builder/_features.py
install/cupy_builder/cupy_setup_build.py

This is a part of #7620.
As discussed in https://github.com/cupy/cupy/pull/7843#issuecomment-1705200327 and #7727, statically link libcudart to CUB to avoid dependency to CTK.

Static link to CUDA Runtime in CUB module

---

.pfnci/windows/_error_handler.ps1
.pfnci/windows/test.ps1

Currently Windows CIs for branch tests take more than the hard limit (10 hours) set in `.pfnci/config.pbtxt`.
This is preventing the kernel cache to grow and taking 8 hours for each pull request tests.
This PR intends to add soft timeout to Windows CI to grow kernel cache incrementally.

Add timeout to Windows CI

---

.github/workflows/pr-updated.yml

`github.event.issue.assignees` is an object, whereas `github.actor` is a string (GitHub login ID). `contains` check had to be done in all login IDs in the object.

Avoid triggering Project Updates for updates from assignees

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_arraytools.py
cupyx/scipy/signal/_spectral.py
cupyx/scipy/signal/_spectral_impl.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py

Depends on https://github.com/cupy/cupy/pull/7563 to ensure that the files do not get merge conflicts
Depends on https://github.com/cupy/cupy/pull/7536 to implement `csd`
Depends on https://github.com/cupy/cupy/pull/7568 to implement `spectral_analysis`, it depends on `get_window`
This port implies Python-only functions and therefore can be copied 1:1 from the original CuSignal implementation.

Port periodogram, welch and csd from CuSignal to cupyx.signal

---

cupyx/scipy/sparse/_csc.py
cupyx/scipy/sparse/_csr.py

Documentation for `cupyx.scipy.sparse.csc_matrix` and `cupyx.scipy.sparse.csr_matrix` currently does not specify that `.transpose(...)` changes the sparse representation.

Clarify sparse .transpose() return type in docstrings

---

cupy/cuda/stream.pxd
cupy/cuda/stream.pyx
tests/cupy_tests/cuda_tests/test_stream.py

`cupy.cuda.stream._ThreadLocal.get_current_stream` has an optional parameter `device_id`. However its wrapper `cupy.cuda.stream.get_current_stream` currently does not have that parameter, and it can only check the active device.
This change gives the optional parameter `device_id` to `cupy.cuda.stream.get_current_stream` too. It is then directly passed to `_ThreadLocal.get_current_stream`.
This is going to be used in #7881, which involves changing streams on multiple devices.

Add optional argument `device_id=-1` to `get_current_stream`

---

cupy/_core/_fusion_interface.py
tests/cupy_tests/core_tests/fusion_tests/test_misc.py

Reported at https://github.com/cupy/cupy/issues/7878.
This PR fixes to raise TypeError when trying to cast `_VariableProxy` to Python scalar.

Prohibit conversion from Variable to Python scalar in fusion

---

cupyx/scipy/interpolate/_interpolate.py
cupyx/scipy/signal/_splines.py
tests/cupy_tests/core_tests/test_ndarray_complex_ops.py
tests/cupy_tests/core_tests/test_ndarray_indexing.py
tests/cupy_tests/io_tests/test_formatting.py
tests/cupyx_tests/fallback_mode_tests/test_fallback.py
tests/cupyx_tests/scipy_tests/interpolate_tests/test_ppoly.py
tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py

Part of https://github.com/cupy/cupy/issues/7616.

Remove conversions of array with ndim > 0 to a scalar

---

cupy/_core/core.pyx
tests/cupy_tests/core_tests/test_ndarray.py

Add `__slots__` to `cupy.ndarray`

---

cupyx/scipy/sparse/_compressed.py

This PR implements the change proposed in https://github.com/cupy/cupy/issues/7876.
Run with CuPy 11.0.0 on Google Colab because I don't have a local GPU.
```python
def test_update_only(size, nnz):
import cupy
import cupyx
rows = cupy.random.randint(0, size, nnz)
cols = cupy.random.randint(0, size, nnz)
old_vals = cupy.random.random(nnz)
new_vals = cupy.random.random(nnz)
mat_cupy_old = cupyx.scipy.sparse.csr_matrix((old_vals, (rows, cols)))
mat_cupy_new = cupyx.scipy.sparse.csr_matrix((old_vals, (rows, cols)))
def run_old():
vals = cupy.roll(new_vals, -1)
mat_cupy_old._set_many(rows, cols, vals)
return mat_cupy_old.get()
def run_new():
vals = cupy.roll(new_vals, -1)
_set_many(mat_cupy_new, rows, cols, vals)
return mat_cupy_new.get()
print(f"{size = }, {nnz = }") …
```

Optimize spmatrix._set_many

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_upfirdn.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_upfirdn.py

cross-ref gh-7403
<s>Depends on gh-7568 for windows.get_window and gh-7722 for `firwin`.
The commit history is messy, will rewrite when these two merge.</s> 
Notes:
- This ports cuSignal code + SciPy tests.
- cuSignal caches kernels explicitly, do not port this part; delegate to RawKernels.
- Follow cuSignal, which does not support the full set of `scipy.signal.upfirdn` functionality: 
- `mode` parameter is not supported
- 1D and 2D signals only (scipy allows any nD).
A minor style point: cuSignal's C++ sources do not conform to the strict 80-symbol line length check. We can of course 
- reformat them (makes code provenance harder?)
- move them back to `.cu`  files (makes python side a trifle messier, with reading from local files etc)
- allow flake8 violations.

port `upfirdn` from cuSignal

---

cupyx/scipy/linalg/_special_matrices.py
tests/cupyx_tests/scipy_tests/linalg_tests/test_special_matrices.py

https://scipy.github.io/devdocs/release/1.11.0-notes.html#deprecated-features

`scipy.linalg.{tri/tril/triu}` are deprecated in SciPy 1.11.0

---

cupyx/scipy/signal/_signaltools.py
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

Fix `signal.medfilt` complex error type for SciPy>=1.11

---

cupyx/scipy/sparse/_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

`csr_matrix.__truediv__(dense_array)` returns `coo_matrix` in SciPy 1.11.
https://docs.scipy.org/doc/scipy/release/1.11.0-notes.html#scipy-sparse-improvements

Fix return type of division of csr_matrix and dense array for SciPy 1.11

---

cupyx/scipy/sparse/_base.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_base.py

Part of #7664.
https://docs.scipy.org/doc/scipy/release/1.11.0-notes.html#scipy-sparse-improvements

Fix `cupyx.scipy.sparse._base` tests for SciPy 1.11

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

https://docs.scipy.org/doc/scipy/release/1.11.0-notes.html#scipy-sparse-linalg-improvements

Fix `maxiter` in `TestLOBPCG`

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Reverts https://github.com/cupy/cupy/pull/7908.

Skip some LOBPCG tests failing with SciPy 1.11

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_base.py

Manual backport of #7905 by @asi1024

[v12] Skip `TestSpmatrix` on SciPy 1.11 or later

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_iir_filter_design.py
cupyx/scipy/signal/_resample.py
cupyx/scipy/signal/_signaltools.py
cupyx/scipy/signal/_upfirdn.py
docs/source/reference/scipy_signal.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_resample.py

Depends on https://github.com/cupy/cupy/pull/7749

Port decimate, resample and resample_poly from CuSignal to cupyx.scipy.signal

---

cupy/_indexing/insert.py
tests/cupy_tests/logic_tests/test_truth.py
tests/cupy_tests/math_tests/test_sumprod.py

[v12] Fix test of `product`, `cumproduct`, `alltrue` and `sometrue` for deprecation

---

tests/cupy_tests/core_tests/fusion_tests/test_routines.py

Backport of #7623.
Related to https://github.com/cupy/cupy/pull/7642.

[v12] Skip fusion `round_` tests

---

.github/workflows/pretest.yml
.gitmodules
.pfnci/windows/test.ps1
cupy/_core/core.pyx
cupy/_core/include/cupy/README.md
cupy/_core/include/cupy/_cccl/LICENSE
cupy/_core/include/cupy/_cccl/cub/cub
cupy/_core/include/cupy/_cccl/libcudacxx
cupy/_core/include/cupy/_cccl/thrust/thrust
cupy/_environment.py
install/cupy_builder/_preflight.py
install/cupy_builder/install_build.py
setup.py
third_party/README.md

~(Do not merge, raising for discussion)~ Ready for review.
The current `main` branch generates a binary package with many files originated from the CCCL repository, which are essentially not required for CuPy's functionalities (C/C++ code, images, documentation, etc.)
This PR tries to mitigate the situation by placing `cccl` to `thrid_party/cccl` and taking only the necessary parts from there.
`python setup.py bdist_wheel` generates a wheel of:
* `main`: 53 MB, containing 4001 files
* This PR: 48 MB, containing 1949 files
Another idea could be to implement a filter in Python (like eb4922ebc0dc46c365149dff1729ebb4d2f82cc9), but I think it is harder to maintain.
If this is acceptable, we can also use the same strategy for Jitify and DLPack (which is not submodule currently due to directory …

Reorganize directory structure around CCCL

---

cupy/__init__.py
cupy/_core/core.pxd
cupy/_core/core.pyx
docs/source/upgrade.rst
tests/cupy_tests/core_tests/test_ndarray_get.py
tests/cupy_tests/test_numpy_interop.py

Close #7820. 
As discussed in the linked issue, this PR adds a new, optional argument `blocking` to control the copy behavior, and make it default to `True` to avoid data race. A test that can easily expose the data race is added.
Note that during the discussion, it was proposed to name the new argument as `async`. However, `async` is a reserved Python keyword (for coroutines), so I changed it to `blocking`, but I am happy to make changes if requested.

Ensure D2H copies are stream ordered and by default blocking

---

cupyx/jit/_compile.py

`ast.Num`, `ast.Str` and `ast.NameConstant` are deprecated since Python 3.8, and raise DeprecationWarning since Python Python 3.12.

Remove deprecated ast expr in CuPy JIT

---

cupy/_core/include/cupy/_cccl/.gitattributes
cupy/_core/include/cupy/_cccl/cub/.gitattributes
cupy/_core/include/cupy/_cccl/thrust/.gitattributes
install/cupy_builder/_preflight.py
install/cupy_builder/cupy_setup_build.py

This PR:
* Adds `.gitattributes` to allow checking out directory symlinks pointing to submodules.
* Fix sdist to pass preflight check. sdist does not contain `third_party`.
This is a blocker for a release.

Improve symlink handling and preflight

---

tests/cupy_tests/creation_tests/test_ranges.py

skip logspace test in NumPy 1.25 & 1.26 (#7946)

---

.pfnci/config.pbtxt
.pfnci/windows/_flexci.ps1
.pfnci/windows/test.ps1
docs/source/install.rst
setup.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

Part of #7899
- Update Python versions used in Windows CI
- Add classifier
- Update docs
I'm now installing Python 3.12 to Windows CI image... ⏳ -> Done

Support Python 3.12, add Windows CI

---

cupy_backends/cuda/libs/nvrtc.pyx

In most cases this bug does not affect users unless users are manually instantiating `NVRTCError` before calling NVRTC routines.

Fix `NVRTCError` not calling `initialize()`

---

.pfnci/windows/_flexci.ps1
.pfnci/windows/test.ps1

- Reduce verbosity of pip install output
- Install ZLIB from local to fix the unstability issue
```
00:26:54.883675 STDERR 4280]      0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to www.winimage.com port 80: Timed out    20s
00:27:15.664927 STDERR 4280]    Command failed (exit code = 7): curl.exe -LO    
```

Fix Windows test scripts

---

tests/cupy_tests/testing_tests/test_parameterized.py

names of the tests are a bit different,
7.4.3 creates the tests with
`test_b[A-c-_param_0_{x='D'}-e]`
while we expect
`test_b[A-_param_0_{x='D'}-e-c]` as the output.
I have skipped this test meanwhile, I am not sure if this is a bug in Pytest side, or if this change is expected (seems like a bug to me)

Skip `test_parameterize_pytest_impl` test for pytest 7.4.3

---

cupy/linalg/_solve.py

After https://github.com/cupy/cupy/pull/7921/ `cupy.linalg.solve` stopped working due to `cupyx.lapack` not being located. This PR adds an explicit import inside `solve` in order to solve this issue.
This is an example traceback that demonstrates this issue:
```python
File "/home/andfoy/Documentos/Quansight/cupy/../iir_plot.py", line 49, in <module>
zi = signal.lfilter_zi(b, a)
File "/home/andfoy/Documentos/Quansight/cupy/cupyx/scipy/signal/_signaltools.py", line 929, in lfilter_zi
y_zi = cupy.linalg.solve(C1 - C2, y2 - y1)
File "/home/andfoy/Documentos/Quansight/cupy/cupy/linalg/_solve.py", line 67, in solve
cupyx.lapack.gesv(a, b)
AttributeError: module 'cupyx' has no attribute 'lapack'
```

Import cupyx.lapack inside cupy.linalg.solve

---

cupy/_environment.py
cupy_backends/cuda/_softlink.pxd
cupy_backends/cuda/_softlink.pyx

This PR adds the new environment variable `CUPY_DEBUG_LIBRARY_LOAD` which allows users to diagnose issues related to library load. This was originally proposed in #7929.

Add debug feature to preloading and softlink

---

cupyx/__init__.py

Fixes an regression in #7921 (https://github.com/cupy/cupy/pull/7921/files#diff-7713c972868d47b980b78c3d42e87accb70ae862be91b32506e7f7bb4d43b951L12)
Closes #7967.

Add lazy load for `cupyx.lapack`

---

cupyx/_runtime.py

Show local runtime version in `cupy.show_config()`

---

docs/requirements.txt
docs/source/install.rst
setup.py

Bump supported NumPy & SciPy versions

---

docs/source/install.rst

Also remove the mention of CUDA 10.2-11.1 wheels.
Close #7983.

Update installation guide to note about cuTENSOR 2.0 support

---

setup.cfg

Backport of https://github.com/cupy/cupy/commit/822361561c (#7666).

[v12] Filter DeprecationWarning for distutils.dep_util used in Cython

---

cupyx/scipy/signal/_signaltools.py

Fixes https://github.com/cupy/cupy/issues/7990
The issue presented by the OP raised some NaN values, which were caused when `sosfilt_zi` tried to solve the equation `0x = 0`, which was due to a lack of IIR coefficients in the example `bessel` filter. This change is analogous to this call in `lfilter`:  https://github.com/cupy/cupy/blob/ff9b39bb107864f086b7a049562d4d48a9720834/cupyx/scipy/signal/_signaltools.py#L930

Fix issues with the initial state when a SOS filter has no IIR part

---

cupyx/jit/_compile.py
tests/cupyx_tests/jit_tests/test_raw.py

Allows functions with "break" and "continue" keywords to be compiled by @jit.rawkernel
Added a test to cupy/tests/cupyx_tests/jit_tests/test_raw.py for both keywords, in both for and while loops.

Support for break and continue keywords

---

cupyx/scipy/signal/_signaltools.py
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

Fixes #8028 
This PR fixes a major issue when initial state conditions were computed for filters whose IIR coefficients contained any zero value. Such cases caused the solver to handle a singular matrix, which in turn, produced NaNs and Inf values as output. Now, a least square solution is produced whenever an IIR coefficient is zero.
This PR also fixes the order of the initial state produced by the `lfilter_zi` and `sosfilt_zi` functions, which were reversed prior to this fix. We didn't detected this error previously, since most of the time, the initial conditions are symmetrical, thus are invariant with respect to the order. However, when zero coefficients are defined, then the state will contain zeros in the same positions as the missing coefficients, therefore order does matter. …

Fix lfilter_zi and sosfilt_zi when any IIR coefficient is zero

---

docs/source/user_guide/interoperability.rst

Because old interface is removed in numpy and sometime breaks compatibility of numpy and cupy
```
>>> t = torch.rand(10, 10)
>>> numpy.from_dlpack(to_dlpack(t))
AttributeError: type object 'PyCapsule' has no attribute '__dlpack__'
```

Use modern dlpack interface in torch interoperability document

---

cupyx/scipy/signal/_signaltools.py
tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

Fix `scp.signal.{medfilt,medfilt2d}` to raise ValueError for complex64 inputs

---

cupyx/scipy/sparse/_base.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Fix `csrmatrix.__pow__` to raise ValueError for non-int other

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Fix scipy.linalg not to raise DeprecationWarning for zero-size inputs

---

cupyx/scipy/special/_stats_distributions.py
tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py

https://scipy.github.io/devdocs/reference/generated/scipy.special.btdtr.html

`scipy.special.{btdtr,btdtri}` are deprecated since SciPy 1.12

---

tests/cupyx_tests/scipy_tests/special_tests/test_statistics.py

[backport] scipy.special.{btdtr,btdtri} are deprecated since SciPy

---

cupyx/scipy/signal/windows/__init__.py
cupyx/scipy/signal/windows/_windows.py
docs/source/reference/scipy_signal_windows.rst
tests/cupyx_tests/scipy_tests/signal_tests/test_windows.py

cross-ref https://github.com/cupy/cupy/issues/7404
Both windows are trivial enough so that just copy pasting scipy implementations seems enough.

ENH: signal: add `lanczos` and `kaiser_bessel_derived` windows

---

cupyx/scipy/signal/_wavelets.py
tests/cupyx_tests/scipy_tests/signal_tests/test_wavelets.py

According to [the SciPy 1.12 release notes](https://scipy.github.io/devdocs/release/1.12.0-notes.html#deprecated-features), all wavelet functions will be deprecated and it is recommended to use PyWavelets instead. Should we move the wavelet functions from `cupyx.signal` to the `cupyx.pywt` namespace?

Deprecate `cupyx.scipy` wavelet functions

---

tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py

In these test cases, CuPy should not guarantee compatibility of `phase` because it is computed with `angle(0 + 0j)`.
```py
>>> x = numpy.array([0, 0.25, 0.5, 0.75])
>>> scipy.signal.vectorstrength(x, 1.)
(6.206335383118183e-17, 2.677945044588987)
>>> x = numpy.array([0 + 1e-11, 0.25, 0.5, 0.75])
>>> scipy.signal.vectorstrength(x, 1.)
(1.570801821958273e-11, 1.5707998607321798)
>>> x = numpy.array([0, 0.25 + 1e-11, 0.5, 0.75])
>>> scipy.signal.vectorstrength(x, 1.)
(1.5708018219509164e-11, 3.1415908866211515)
>>> x = numpy.array([0, 0.25, 0.5, 0.75 + 1e-11])
>>> scipy.signal.vectorstrength(x, 1.)
(1.5707823930479852e-11, 1.7669904971232676e-06)
```

Fix invalid `vectorstength` tests

---

cupy/_core/include/cupy/special/.clang-format
cupy/_core/include/cupy/special/config.h
cupy/_core/include/cupy/special/error.h
cupy/_core/include/cupy/special/evalpoly.h
cupy/_core/include/cupy/special/lambertw.h
cupyx/scipy/special/__init__.py
cupyx/scipy/special/_lambertw.py
docs/source/reference/scipy_special.rst
tests/cupyx_tests/scipy_tests/special_tests/test_lambertw.py

Closes #4450 
This PR adds the `lambertw` function. The implementation is taken from a header only C++ library @izaid and I have been working on within SciPy. Our plan was discussed in https://github.com/scipy/scipy/issues/19404. We are using conditional compilation to write the library in such a way that it will work on either CPU or on GPU compiled by NVRTC (https://github.com/scipy/scipy/pull/19601/). Our hope is that this library could eventually be vendored as a submodule by both SciPy and CuPy, but as a start, we think the best thing to do is to add functions to CuPy which are currently missing by copying relevant parts of the code over.
Our goal is to eventually add every special function currently in SciPy to this header only library, and make improvements and bug fixes as needed, …

Add lambertw function

---

cupy/cuda/jitify.pyx

Jitify version can be `<unknown>`, so need to strip the "<", ">" characters. 
Close #8147.

Prevent angular brackets from appearing in Jitify's cache filename

---

cupy/cuda/compiler.py
tests/cupy_tests/core_tests/test_raw.py

Close #8155.
I verified locally that this is the right fix, see my analysis in https://github.com/cupy/cupy/issues/8155#issuecomment-1924812326. Also, I assume this patch must have been used by @mrakgr in his journey of #8156? 🙂

Set `-arch` in the compiler options unconditionally

---

cupy/_core/include/cupy/special/binom.h
cupy/_core/include/cupy/special/cephes/beta.h
cupy/_core/include/cupy/special/cephes/const.h
cupy/_core/include/cupy/special/cephes/expn.h
cupy/_core/include/cupy/special/cephes/gamma.h
cupy/_core/include/cupy/special/cephes/mconf.h
cupy/_core/include/cupy/special/cephes/polevl.h
cupy/_core/include/cupy/special/cephes/psi.h
cupy/_core/include/cupy/special/cephes/trig.h
cupy/_core/include/cupy/special/cephes/zeta.h
cupy/_core/include/cupy/special/config.h
cupy/_core/include/cupy/special/digamma.h
cupy/_core/include/cupy/special/evalpoly.h
cupy/_core/include/cupy/special/lambertw.h
cupy/_core/include/cupy/special/loggamma.h
cupy/_core/include/cupy/special/trig.h
cupy/_core/include/cupy/special/zlog1.h
cupyx/scipy/special/_digamma.py
tests/cupyx_tests/scipy_tests/special_tests/test_digamma.py

This PR adds support for complex values to the `digamma` function. This is made possible by the recent translation of SciPy's complex valued `digamma` implementation to CUDA compatible C++, https://github.com/scipy/scipy/pull/19834. This PR also makes an improvement to the real valued `digamma` implementation which was made in SciPy but had not been ported to CuPy (https://github.com/scipy/scipy/pull/8129).
I've copied over the entirety of the SciPy special C++ library as it exists now, despite it not all being used for `digamma`, but if you'd like, I can go through and try to add only the minimum number of headers that are actually needed. I just thought it would be easier to maintain if SciPy and CuPy vendor the same version of this set of files.
`polevl_definition` in `_digamma.py` is …

Add complex support for the digamma function

---

cupyx/scipy/interpolate/_rgi.py

Just a cleanup: a helper function was vendored from scipy twice in two source files.

MAINT: cupyx/interpolate: remove a duplicate function

---

.gitignore
cupyx/scipy/spatial/__init__.py
cupyx/scipy/spatial/_delaunay.py
cupyx/scipy/spatial/_triangulation_2d.py
cupyx/scipy/spatial/delaunay_2d/_kernels.py
cupyx/scipy/spatial/delaunay_2d/_schewchuk.py
cupyx/scipy/spatial/delaunay_2d/_tri.py
tests/cupyx_tests/scipy_tests/spatial_tests/test_delaunay.py

This PR intends to add a two dimensional Delaunay triangulation in the `cupyx.scipy.spatial` namespace. This is required as part of https://github.com/cupy/cupy/issues/7186, where some interpolants such as `CloughTocher2DInterpolator` require them.
This implementation is derived from https://doi.org/10.1145/2556700.2556710, where the implementation is reduced from 3D to 2D.

Add 2D Delaunay triangulation

---

cupyx/scipy/interpolate/__init__.py
cupyx/scipy/interpolate/_bspline.py
cupyx/scipy/interpolate/_bspline2.py
cupyx/scipy/interpolate/_cubic.py
docs/source/reference/scipy_interpolate.rst
tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py

cross-ref https://github.com/cupy/cupy/issues/7186
The functionality is almost but not completely covered by `make_interp_spline`, so delegate to it whenever works. The edge cases of n=2, 3 are basically copy-paste of what the scipy counterpart does.
The LOC count in this PR is mostly gymnastics needed to retrofit a factory function into an LSP-breaking subclass.

Add cupyx.scipy.interpolate.CubicSpline

---

cupyx/scipy/interpolate/_interpolate.py
cupyx/scipy/signal/_iir_utils.py
cupyx/scipy/signal/_max_len_seq.py
cupyx/scipy/signal/_peak_finding.py
cupyx/scipy/signal/_spectral_impl.py
cupyx/scipy/signal/_splines.py
cupyx/scipy/signal/_waveforms.py
cupyx/scipy/spatial/_kdtree_utils.py

The `cuda_runtime.h` header is hard-wired in the compiler (for the device API bits; for host APIs we don't care), so there is really no point in including it. It also caused issues in deployment, because we can't bundle CUDA headers.
Close #8162.

Fix: remove unnecessary include that causes deployment issue

---

install/cupy_builder/_features.py

Recent Thrust has changed such that it's no longer safe to use the host compiler to compile the headers. Making a new choice based on the discussion in https://github.com/NVIDIA/cccl/issues/1373. This also aligns the treatment with ROCm builds.

Fix build system for Thrust detection

---

cupy/cuda/jitify.pyx
install/cupy_builder/cupy_setup_build.py

- Part of #8209: Add a Jitify warning as a stop-gap solution to avoid the hanging user experience.
- Suppress Jitify logs being printed to stdout to avoid surprises, e.g.
- https://stackoverflow.com/questions/77961021/cupy-cooperative-groups-h-jitify-file-not-found
- https://stackoverflow.com/questions/78060784/jitify-file-not-found
- https://github.com/rapidsai/dask-cuda/issues/1317

Various Jitify improvements

---

cupy/_statistics/order.py
tests/cupy_tests/statistics_tests/test_order.py

I'd been going through the issue #6229 and thought I'd finish off the to-do, since the docs say we already support the `nearest` interpolation method.
https://docs.cupy.dev/en/stable/reference/generated/cupy.percentile.html

Add the `nearest` method for percentile/quantile estimation

---

install/cupy_builder/install_build.py

Fix: always switch to the submodule dir before checking git tag/commit

---

cupy/random/_bit_generator.pyx

Fixes the problem in random Generator API that the number of threads is unexpectedly fixed at 8 * 256 * 16 regardless of the SM count on the hardware.
`cudaDevAttrMultiProcessorCount` is a constant (16) for querying the attribute and should not have been used directly.
cc/ @emcastillo

Fix Generator API parallelism

---

setup.py
tests/cupyx_tests/scipy_tests/signal_tests/mpsig.py
tests/cupyx_tests/scipy_tests/signal_tests/test_filter_design.py

fixes https://github.com/cupy/cupy/issues/8255
The test is a clone of the eponymous test in scipy, so drop in the mpmath-using file from scipy and actually test the cupyx.scipy function.

BUG: cupyx/scipy/signal: fix mpmath test

---

cupy/cuda/jitify.pyx

Close #8249. Follow-up of #8200.
Starting CUDA 12.3 there are some internal NVRTC compiler changes that led to issues with the CG & cudart headers (e.g. nvbugs 4130337). From the user perspective, it manifests as compile-time errors. Since the CG headers are not redistributable, vendoring them is not a viable option, and the warm-up kernel should only include headers that are guaranteed default-accessible in all package formats (it means CCCL headers + other CuPy headers, after this PR), so I simply remove the CG headers. 
It could be possible to include `cuda_device_runtime_api.h` before the CG headers to fix the compile-time error, however it raises a compiler warning 
```
/usr/local/cuda-12.0.0/include/crt/host_defines.h(54): warning #1105-D: #warning directive: "crt/host_defines.h is …
```

Fix jitify warmup kernel - Cont'd

---

.pfnci/windows/test.ps1

Ref #8272
Test failures are observed after SciPy v1.13.0. Pin Windows tests to use SciPy v1.12 until further investigation. https://ci.preferred.jp/cupy.win.cuda122/159080/

Tentatively pin SciPy to v1.12 in CI

---

cupy_backends/cuda/libs/cusparse.pxd
cupyx/cusparse.py
tests/cupyx_tests/test_cusparse.py

This PR closes #7699. It is adding support for SPGEMM ALG2 of cusparse that requires a much lower memory usage than the default, used only when the default algorithm would fail.

Support fallback allgorithm for spgemm

---

cupyx/scipy/interpolate/__init__.py
cupyx/scipy/interpolate/_bspline2.py
cupyx/scipy/interpolate/_fitpack_repro.py
docs/source/reference/scipy_interpolate.rst
tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py
tests/cupyx_tests/scipy_tests/interpolate_tests/test_fitpack2.py

Add UnivariateSpline family of classes.  
SciPy plans to refactor / rework the matching part of scipy.interpolate, the current SciPy proposal is to add two two new functions, `make_splrep` and `make_splprep` and slowly phase out `splrep`, `splprep` and `*UnivariateSpline`s, see https://github.com/scipy/scipy/pull/19970 . Since this is still under discussion in SciPy, here we add two layers: 
- new-style `make_splrep` : add internally but do not expose to the public API. If/when this lands in SciPy, CuPy will only need to add them to `__init__` to expose them.
- backwards compatible `*UnivariateSpline` classes. These reuse the `make_splrep` internally and adjust the API to match the venerable SciPy API. 
The differences to the SciPy API are minimal:
- FITPACK in SciPy has a limitation that …

ENH: cupyx/scipy/interpolate: add *UnivariateSpline for 1D smoothing splines

---

cupyx/scipy/interpolate/_interpnd.py

After https://github.com/cupy/cupy/pull/8276, we found a major bug where all input points may not be processed, if `n_points * n_dims > 512 * 128`. This PR ensures that all points are processed, independent of the number of points or dimensions.

Fix bounds issue in Clough-Tocher computation

---

cupy/_environment.py
cupyx/tools/install_library.py

Support for cuTENSORMg has been added in #8212 but the library was not loaded. As a result `cupy_backends.cuda.libs.cutensor` import was failing as the library could not be found.
No backport required as cuTENSORMg support is new in v14.

Preload cuTENSORMg

---

cupyx/scipy/interpolate/_ndbspline.py
cupyx/scipy/interpolate/_rgi.py
tests/cupyx_tests/scipy_tests/interpolate_tests/test_ndbspline.py
tests/cupyx_tests/scipy_tests/interpolate_tests/test_rgi.py

Add a constructor for N-dimensional b-splines from data, which is new in SciPy 1.13.0. 
The user API matches that of SciPy 1.13.0:
- the constructor is exposed via the RegularGridInterpolator only
- there is a slight backwards compat change: RGI(..., method="cubic") now goes through the NdBSpline. Previous behavior is available via `RGI(..., method="cubic_legacy")`
- the new way is parametrically slower for construction of an interpolator (previously: essentially zero work; currently: construct and solve a large sparse linear system)
- the new way is parametrically faster for evaluations: previously the evaluation went through a python loop over the data points, and for each data point a loop over the dimensions; the new way delegates to NdBSpline, which has a GPU kernel for evaluations. …

add NdBSpline based interpolation methods to RGI

---

.github/workflows/publish.yml

It seems that it takes a while before our published items are shown on PyPI.
https://github.com/cupy/cupy/actions/runs/8748240002/attempts/1

Wait before published items shown on PyPI

---

cupyx/scipy/interpolate/__init__.py
cupyx/scipy/interpolate/_polyint.py
docs/source/reference/scipy_interpolate.rst
tests/cupyx_tests/scipy_tests/interpolate_tests/test_polyint.py

Port `interp1d` routine from `scipy.interpolate`.
The routine itself is not very interesting: for `nearest`-like modes it delegates to `cupy.searchsorted`; for `cubic`-like modes it delegates to `make_interp_spline`. And it adds heaps and heaps of overhead on top.
It's public in SciPy though, and is used under the hood by `griddata`. So it's easier to port it and be done with it.
cross-ref https://github.com/cupy/cupy/issues/7186

ENH: cupyx/interpolate: port interp1d from scipy

---

cupyx/scipy/ndimage/_filters.py
cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_morphology.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py

This MR backports an efficiency improvement for binary morphology functions that were made in cuCIM's vendored copy of `cupyx.scipy.ndimage` code. See additional background in https://github.com/cupy/cupy/pull/8126#issuecomment-2081554814
The CUDA kernels themselves do not have to change to support this as we already previously merged support for not providing a weights array. The changes here just allow the higher level binary morphology functions to make use of that existing optimization.
For NumPy, allocating a small (e.g. 3x3) binary array of ones takes on the order of 1 microsecond, so this would be a micro-optimization if proposed for SciPy itself. For CuPy, though, the array creation time is > 10 microseconds and also involves synchronization.  In addition to the synchronization …

improve efficiency of binary morphology functions by accepting a tuple for `footprint`

---

cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_morphology.py

This MR backports a limited number of style changes made for cuCIM's vendored copy of ndimage code. It is intended to improve readability and ease maintenance of the CUDA kernels used by `cupyx.scipy.ndimage`.
This is split out from other formatting changes in #8126

Use f-strings in ndimage kernel generation code

---

tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py

The purpose of this MR is to refactor existing binary morphology tests from a single dense product over all parameters to 2 or 3 products over a small subset of the parameters. The functionality tested should be equivalent while reducing the total number of test cases run by an order of magnitude.
When running the morphology tests with `pytest` flag `-k Binary`, the number of tests that run is reduced from 4054 (before) to 412 (after).

ndimage: more efficient testing of binary morphology functions

---

cupy/_manipulation/kind.py
cupyx/scipy/_lib/_util.py
cupyx/scipy/interpolate/_bspline.py
cupyx/scipy/interpolate/_interpolate.py
cupyx/scipy/interpolate/_polyint.py
cupyx/scipy/ndimage/_interpolation.py
cupyx/scipy/ndimage/_util.py
cupyx/scipy/signal/_iir_filter_conversions.py
cupyx/scipy/signal/_waveforms.py

This MR has some minor housekeeping changes, mostly in `cupyx.scipy` modules so they are not using functionality deprecated for NumPy 2.0.
This should complement the changes being made by @ev-br in #8314
related to #8306

cupyx: cleanup use of deprecated NumPy functionality (NumPy 2.0 compatibility)

---

cupyx/scipy/interpolate/__init__.py
cupyx/scipy/interpolate/_ndgriddata.py
docs/source/reference/scipy_interpolate.rst
tests/cupyx_tests/scipy_tests/interpolate_tests/test_ndgriddata.py

See #7186
Depends on #8208 for module ordering

Add NearestNDInterpolator to cupyx.scipy.interpolate

---

cupy/fft/__init__.py
cupy/linalg/__init__.py

Otherwise, all array API implementors resort to `exec` via `array_api_compat`:  https://github.com/data-apis/array-api-compat/blob/main/array_api_compat/cupy/fft.py#L2

MAINT: fft, linalg: add __all__ lists

---

cupy/_core/core.pyx
tests/cupy_tests/indexing_tests/test_indexing.py

Close https://github.com/cupy/cupy/issues/8130.
Fix the condition for generating a kernel using 32-bit indexing.

Fix overflow indexing ndarray generated with as_strided

---

.github/workflows/pretest.yml
cupy/__init__.py
cupy/_core/_routines_indexing.pyx
cupy/_core/_routines_manipulation.pyx
cupy/_core/_routines_sorting.pyx
cupy/_core/_routines_statistics.pyx
cupy/_core/core.pyx
cupy/_core/fusion.pyx
cupy/_core/internal.pyx
cupy/exceptions/__init__.py
cupy/lib/_routines_poly.py
cupy/lib/_shape_base.py
cupy/testing/_loops.py
cupyx/jit/_compile.py
cupyx/scipy/fft/_realtransforms.py
cupyx/scipy/interpolate/_bspline2.py
setup.cfg
setup.py
tests/cupy_tests/core_tests/fusion_tests/test_reduction.py
tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
tests/cupy_tests/functional_tests/test_vectorize.py
tests/cupy_tests/lib_tests/test_polynomial.py
tests/cupy_tests/logic_tests/test_truth.py
tests/cupy_tests/manipulation_tests/test_join.py
tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_fourier.py

As suggested in https://github.com/cupy/cupy/issues/8306#issuecomment-2139695574: make CuPy import under numpy 2.0. 
- top-level names removed in numpy 2.0 are removed here as well. An alternative is to have, e.g. `cupy.float_` conditionally available depending on the numpy version. This feels a bit strange TBH.
- tests should pass with numpy 1.26.x 
If this is the way to go, the sequence is, I suppose:
- this PR: CuPy imports on 2.0, is inconsistent with either numpy 1.x or 2.x
- NEP50: https://github.com/cupy/cupy/pull/8323
- NEP52: https://github.com/cupy/cupy/pull/8314 (will need to be rebased on the two previous PRs)

make CuPy import under NumPy 2.0

---

cupy/__init__.py
cupy/cuda/nccl.py
cupyx/_runtime.py

Closes #8354 (part of #5641)
This PR changes CuPy to load NCCL shared library at the time of `import cupy.cuda.nccl` (which also runs when `import cupyx.distributed`), instead of `import cupy`.
xref: #5677 (which implements lazy-preload of cuDNN)
NCCL compatibility among the ecosystem libraries is becoming important now that everyone is using NCCL for large-scale model training with complicated mixed-library environments :)

Lazy-preload NCCL

---

.github/workflows/pr-project.yml
.github/workflows/pr-updated.yml

Use the latest/standard GitHub actions.
* `actions/create-github-app-token@v1` (official equivalent) instead of `tibdex/github-app-token`
* `actions/download-artifact@v4` (now supports downloading artifacts from other workflow runs) instead of our own implementation
* `actions/upload-artifact@v4` instead of `actions/upload-artifact@v3` to avoid deprecation warnings ([example](https://github.com/cupy/cupy/actions/runs/9437786961))

Fix pull request project board workflows

---

cupyx/scipy/interpolate/_rbfinterp.py
tests/cupyx_tests/scipy_tests/interpolate_tests/test_rbfinterp.py

Sync the RBF implementation with scipy 1.13, which removed a spurious warning in a corner case. See https://github.com/scipy/scipy/pull/20364 for the discussion.

MAINT: interpolate: update RBF to scipy 1.13

---

cupyx/scipy/interpolate/_bspline2.py

See https://github.com/cupy/cupy/pull/8290#issuecomment-2175220453
This prevents the `d_boor` kernel from performing an out-of-bounds array access, this was caused due to the size of `temp` in `make_interp_spline`, which was shorter than the expected value. After this PR, the confirmed segfault caused when running the following test no longer appears:
```
compute-sanitizer --tool memcheck --padding 32 python -m pytest -v  tests/cupyx_tests/scipy_tests/interpolate_tests/test_bspline2.py  -k test_minimum_points_and_deriv
```

Fix spline temp container size in make_interp_spline

---

cupy/fft/_fft.py

This was removed in 2.0, since it is just `int` anyway since Python 2 is not a thing anymore.
A better pattern is probably:
```
try:
axes = (operator.index(axes),)
except TypeError:
pass
```
(broadening this to non Python integers).  But it doens't matter much and this is the more trivial change.

MAINT: Avoid using np.compat.integer_types

---

cupy/_core/include/cupy/type_dispatcher.cuh

In ARM, char is an unsigned int which causes several tests to fail.
https://developer.arm.com/documentation/den0013/latest/Porting/Miscellaneous-C-porting-issues/unsigned-char-and-signed-char

Fix type dispatcher for arm64

---

.pfnci/coverage.rst
.pfnci/linux/tests/cuda-example.Dockerfile
.pfnci/matrix.yaml

This is required because `matplotlib` 3.9.0 (installed [here](https://github.com/cupy/cupy/blob/64c3b26df94907716f8f24f72dcec9676c75533a/.pfnci/linux/tests/actions/example.sh#L10)) now requires NumPy 1.23+.

Bump NumPy/SciPy versions in cuda-example CI

---

cupy/_manipulation/basic.py

NumPy two has some bad definitions with `copyto` and NEP 50 in that `copyto` currently ignores it. That is a trickier NumPy problem.
However, it is very hard to write code that does the right thing on both versions and even harder to do the same thing as NumPy 2 (because it is not quite consistent).
Short of a version switch, the only good way seems to be to just call `copyto` directly for Python scalar input.
Closes gh-8408, gh-8391
(I'll test this with cuml to be sure.)
---
As you can see, I gave up on trying to find a solution that doesn't just try with NumPy directly.  Yes, unfortunately `can_cast` is almost twice as fast as `copyto` (~200ns for me).
Hopefully that is just small compared to all the other overheads here?
The alternative would be to special case integers and check for …

Fix copyto for NumPy 2 compatibility

---

cupy/cuda/compiler.py

The popup of the nvcc.exe console only happens in cythonized code.
This will fix issue #8431

Update compiler.py to avoid the popup of the nvcc.exe console

---

cupy/random/_generator.py

Without value based casting allowing "safe" casts from signed to unsigned integer scalars, NumPy 2 rejects practically all inputs here.
Unfortunately, even same-kind does not allow for signed -> unsigned so we need to do a larger dance.
The given diff was used together with cudf and cuml to successfully run tests with NumPy 2 and cupy 13.2.
Closes gh-8407, gh-8392

Fix `RandomState.seed()` for NumPy 2 compatibility

---

cupy/cuda/cub.pyx

This should be one of potential causes of illegal memory access we're facing at #8290.
ref:
- https://github.com/NVIDIA/cccl/blob/7a3dae72b36d2ce939de1d1b68e0b251d287074f/cub/cub/util_type.cuh#L667
- https://github.com/NVIDIA/cccl/blob/694e963e72c60384d85abdcf7affed504aa9ed04/thrust/thrust/complex.h#L76

Fix the size of temporary CUB output space to consider its alignment

---

cupy/_core/include/cupy/special/cephes/ellie.h
cupy/_core/include/cupy/special/cephes/ellik.h
cupy/_core/include/cupy/special/cephes/ellpe.h
cupy/_core/include/cupy/special/cephes/ellpk.h
cupy/_core/include/cupy/special/cephes/unity.h
cupyx/scipy/special/__init__.py
cupyx/scipy/special/_ellip.py
tests/cupyx_tests/scipy_tests/special_tests/test_ellipk.py

This PR adds the functions `ellipkinc` and `ellipeinc` to special for Incomplete Elliptic Integrals of the first and second kind respectively.

Add Incomplete Elliptic Integrals to special

---

docs/source/_comparison_generator.py

Generate a comparison table that lists all APIs in `(cupyx.)scipy.sparse.*_matrix` classes as in #7762. 
Please check whether the naming for the comparison table is appropriate. Thank you.

Add comparison table for `(cupyx.)scipy.sparse.*_matrix classes` class methods

---

cupy/_core/include/cupy/complex/arithmetic.h
cupy/_core/include/cupy/complex/catrig.h
cupy/_core/include/cupy/complex/catrigf.h
cupy/_core/include/cupy/complex/ccosh.h
cupy/_core/include/cupy/complex/ccoshf.h
cupy/_core/include/cupy/complex/cexp.h
cupy/_core/include/cupy/complex/cexpf.h
cupy/_core/include/cupy/complex/clog.h
cupy/_core/include/cupy/complex/clogf.h
cupy/_core/include/cupy/complex/complex.h
cupy/_core/include/cupy/complex/complex_inl.h
cupy/_core/include/cupy/complex/cpow.h
cupy/_core/include/cupy/complex/cproj.h
cupy/_core/include/cupy/complex/csinh.h
cupy/_core/include/cupy/complex/csinhf.h
cupy/_core/include/cupy/complex/csqrt.h
cupy/_core/include/cupy/complex/csqrtf.h
cupy/_core/include/cupy/complex/ctanh.h
cupy/_core/include/cupy/complex/ctanhf.h
cupy/_core/include/cupy/complex/math_private.h
cupy/cuda/cupy_thrust.cu

Thrust has introduced a wrapped versioning namespace. This is colliding with the namespace introduced in `cupy/complex`
To avoid that issue pull in the thrust config and use the proper thrust namespace macro

Do not use plain thrust namespace in complex clone

---

.pfnci/linux/tests/actions/build.sh

It seems the memory usage has increased during the build phase.
e.g. Example CI in main branch failing with `[ABORTED] excessive memory usage is detected`:
https://ci.preferred.jp/cupy.linux.cuda-example/166617/

Decrease number of threads to avoid "system error: excessive memory usage is detected"

---

.pfnci/config.tags.json
.pfnci/matrix.yaml

As far as I recall we haven't experienced any issues specific to these CUDA versions, so I think it's ok to skip these tests on `/test mini` trigger (to reduce 💰). Note that these tests will run continue to run when PR got merged OR `/test full` is triggered.
Coverage: https://github.com/cupy/cupy/blob/main/.pfnci/coverage.rst

CI: skip CUDA 12.1/12.2/12.3/12.4 CI on "mini" trigger

---

cupyx/jit/cub.py
cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_filters_generic.py
cupyx/signal/_filtering/_filtering.py

Follow-up of #8412. This PR addresses the first item from https://github.com/cupy/cupy/issues/8209#issuecomment-2272753019:
> 1. There are a few places where the similar treatment can be done to avoid using Jitify
This is not critical to be merged/backported if time is short, just a nice to have.

Avoid using Jitify everywhere inside CuPy

---

cupyx/fallback_mode/fallback.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
tests/cupyx_tests/scipy_tests/signal_tests/test_ltisys.py
tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py

Some of the routines here rely in scipy functions that don't return the same results in x86/arm. Seems that the CUDA routines are written to mach the results in x86 causing several tests to fail.
https://github.com/scipy/scipy/issues/20158
https://github.com/scipy/scipy/issues/20160

Skip some tests in aarch64 CI

---

cupyx/scipy/signal/_upfirdn.py
tests/cupyx_tests/scipy_tests/signal_tests/test_upfirdn.py

scipy.signal.upfirdn supports a number of modes, of which the default is "constant". cupyx supports only this mode, but used `None` to select it. Code that didn't pass the argument would work interchangeably between scipy and cupyx, but code that explicitly passed `mode="constant"` would raise an exception under cupyx.
With this change, cupyx behaves the same as scipy for this mode: not passing the argument, or explicitly passing `mode="constant"` works, and explicit passing `mode=None` raises an exception. Note that the latter is a **backwards-incompatible** change.
Closes #8449.

upfirdn: mode=None -> mode="constant"

---

cupy/random/_generator.py

Fix https://github.com/cupy/cupy/issues/8477.
current master:
```
CPU:   528.909 us   +/-  8.817 (min:   513.830 / max:   556.690) us     GPU-0: 22175.946 us   +/- 21.370 (min: 22132.736 / max: 22215.679) us
```
This PR:
```
CPU:   542.260 us   +/- 226.564 (min:   510.556 / max:  2789.806) us     GPU-0:   548.843 us   +/- 227.403 (min:   517.088 / max:  2804.736) u
```
Reproducer:
```py
def f():
cp.random.choice(10000, size=10000, p=cp.ones(10000)/10000)
print(benchmark(f, (), n_repeat=20))
```

Improving performance of `cupy.random.choice`

---

cupy/_environment.py
cupy/cuda/compiler.py
cupyx/_runtime.py

As CuPy also needs a bit of help searching for headers in the conda case, extend the logic used to search for wheel headers in PR ( https://github.com/cupy/cupy/pull/8489 ) to also search for conda headers. In particular this searches the targets directory for the platform where CuPy is being run on so that it can find headers there.
Fixes https://github.com/cupy/cupy/issues/8466

Extend runtime header search logic to conda

---

cupyx/scipy/signal/_fir_filter_design.py
tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py

Follow https://github.com/scipy/scipy/pull/19706

Support `half` option in `scipy.signal.minimum_phase`

---

cupy/random/_generator.py

Reverts cupy/cupy#8501 as discussed in https://github.com/cupy/cupy/pull/8483#issuecomment-2297857073

[v13] Revert "[backport] Improving performance of `cupy.random.choice`"

---

cupy/_core/core.pyx

Do not use bundled headers for unsupported future CUDA 12.x releases, as headers from the bundled `cuda-12` directory are unlikely to work with them.
Once new CUDA version is out, users can either install the full CTK with headers or do `pip install -U nvidia-cuda-runtime-cu12` to continue using CuPy without waiting for a new release.
cc/ @leofang

Fallback to system headers for future CUDA 12.x versions

---

cupy/_core/include/cupy/complex/namespace.h

`THRUST_NAMESPACE_BEGIN` looks new in ROCm 5.

Fix ROCm 4.3 binary package build broken

---

cupy/_core/core.pyx

The assumption of `0 <= len(wheel_dir_count) <=1` is no longer valid as we now support loading from conda packages: https://github.com/cupy/cupy/blob/d717917e1d72c4318fcdcb73b4c9b29fbda176ff/cupy/_environment.py#L476-L479
xref #8519

Fix cudart header detection for conda

---

cupyx/scipy/sparse/linalg/_iterative.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#expired-deprecations

Fix `sparse.linalg` function signatures following SciPy 1.14

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_base.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

- Use `.toarray()` instead of `.A`
- `sparse._base._spbase()` => `sparse._base._spbase(dummy)`
- `str(spmatrix)` is changed
https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#scipy-sparse-improvements

Fix `cupyx.scipy.sparse` tests for SciPy 1.14

---

tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py

We should add a support for empty inputs after reduction functions support the `initial` option: https://github.com/cupy/cupy/issues/6935

Skip `special.logsumexp` test for empty input

---

tests/cupyx_tests/scipy_tests/special_tests/test_beta.py

Background: https://github.com/scipy/scipy/issues/21426

Skip betaincinv test with SciPy 1.14.1

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_base.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_dia.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Backport of https://github.com/cupy/cupy/pull/8527.

[v13] Fix cupyx.scipy.sparse tests for SciPy 1.14

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py

Backport of https://github.com/cupy/cupy/pull/8526.

[v13] Skip sparse.linalg.{cg, cgs, gmres} tests for scipy>=1.14

---

tests/cupyx_tests/scipy_tests/stats_tests/test_distributions.py

Backport of https://github.com/cupy/cupy/pull/8547

[v13] Skip `cupy.scipy.stats.entropy` tessts for SciPy 1.14 dtype rule change

---

tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py

Backport of https://github.com/cupy/cupy/pull/8510

[v13] Skip test_homomorphic in scipy>=1.14

---

cupyx/scipy/ndimage/_filters.py
cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_morphology.py
cupyx/scipy/ndimage/_util.py
cupyx/scipy/signal/_bsplines.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py

This MR updates several `cupyx.scipy.ndimage` filters with support for the `axes` arguments that was added in SciPy 1.11.

add axes support in ndimage filters module

---

docs/source/install.rst

Follows up #8466, document CUDA header requirments for CUDA 12.2+.
https://github.com/cupy/cupy/issues/8162#issuecomment-2339462954
https://github.com/cupy/cupy/issues/8592
Preview: https://cupy--8593.org.readthedocs.build/en/8593/install.html#cupy-always-raises-nvrtc-error-compilation-6

Add docs about CUDA headers

---

cupy/_creation/basic.py

Fix allocation size on *_like array creation, which caused potentially illegal memory access. We had wrong allocation size when the order is K and the shape is different from that of the prototype array.

Fix order 'K' with shape given for *_like array creation

---

.github/workflows/self-hosted-ci.yml

Add CI that uses on-premise self-hosted GitHub Actions runners.
This replaces the Jenkins CI.
1. The workflow in `cupy/cupy` repository (added in this PR) triggers when a new comment is added to pull-request.
2. If the comment contains `/test ... rocm ...` line, dispatch the CI request to [`cupy/self-hosted-ci`](https://github.com/cupy/self-hosted-ci/) repository.
3. CI runs on self-hosted runners registered to `cupy/self-hosted-ci` repository with [this workflow](https://github.com/cupy/self-hosted-ci/blob/main/.github/workflows/ci.yml).
This complicated setup is required to use self-hosted on-premise GitHub Actions runners securely in public repositories.

Add self-hosted CI

---

tests/cupyx_tests/scipy_tests/interpolate_tests/test_rbfinterp.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py
tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py

Related to #8621 .
MEMO: I simplified the version ranges a bit because `scipy` 1.4 is already EOL.

Use `testing.with_requires` to skip broken tests

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py

This PR partially cherry-picks e9f921f .
See #8621 for why it's necessary.

Catch `ValueError`

---

cupy/linalg/_solve.py
tests/cupy_tests/linalg_tests/test_solve.py

Related to #8306 .
Now shape of `b` (right hand side) must be either `(M,)` or `(..., M, K)` rather than `(..., M)` or `(..., M, K)` (`numpy` v1).
See https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html#numpy.linalg.solve for details.

Make `cupy.linalg.solve` compatible with `numpy` v2

---

tests/cupyx_tests/scipy_tests/signal_tests/test_max_len_seq.py
tests/cupyx_tests/scipy_tests/signal_tests/test_resample.py
tests/cupyx_tests/scipy_tests/signal_tests/test_spectral.py
tests/cupyx_tests/scipy_tests/signal_tests/test_wavelets.py
tests/cupyx_tests/scipy_tests/signal_tests/test_windows.py
tests/cupyx_tests/signal_tests/filtering_tests/test_filtering.py
tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py

- Use `try ... except ImportError ...` to detect `scipy` without crashing `pytest`
- Add `testing.with_requires("scipy")`

Skip tests if `scipy` is not installed

---

cupy/linalg/_solve.py
tests/cupy_tests/linalg_tests/test_solve.py

Related to #8306 .
See https://numpy.org/doc/2.0/reference/generated/numpy.linalg.lstsq.html for details.

Silence `FutureWarning` emitted when `rcond` is missing

---

tests/cupy_tests/manipulation_tests/test_basic.py

Related to #8306 .
Make tests aware of `OverflowError` raised when casting negative numbers to unsigned types.

Accept `OverflowError` in `TestCopytoFromScalar` for NumPy v2

---

cupy/_environment.py

* Some systems return an empty string for `platform.processor()` (https://docs.python.org/3.10/library/platform.html#platform.processor)
Closes #8654

Switch to using platform.machine() instead of platform.processor()

---

cupy/random/_generator_api.pyx
tests/cupy_tests/random_tests/test_generator_api.py

Fix to properly allocate output arrays for some RNG methods when dtype is specified. This potentially had illegal memory access.

Properly allocate in RNG when specified dtype is neither float32/float64

---

.pre-commit-config.yaml

This small PR eliminates the following warning.
> [WARNING] repo `https://github.com/pre-commit/pre-commit-hooks` uses deprecated stage names (commit, push) which will be removed in a future version.  Hint: often `pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks` will fix this.  if it does not -- consider reporting an issue to that repo.

Upgrade pre-commit hooks to silence warnings

---

install/cupy_builder/install_build.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
tests/cupyx_tests/scipy_tests/signal_tests/test_fir_filter_design.py
tests/cupyx_tests/scipy_tests/signal_tests/test_ltisys.py
tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py

Use `platform.machine()` instead of `platform.processor()`

---

cupy/_core/_reduction.pyx
tests/cupy_tests/manipulation_tests/test_join.py

Replace `numpy.ComplexWarning` with `cupy.exceptions.ComplexWarning`

---

cupyx/scipy/signal/_iir_utils.py
tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

See https://github.com/scipy/scipy/pull/21713#discussion_r1802139152
This PR ensures that `sosfilt` returns the stage state in the correct shape when the input is not 2-dimensional. This was causing compatibility issues when testing against SciPy

Fix sosfilt state output shape when ndim < 2

---

cupy/__init__.py
cupy/_core/_routines_indexing.pyx
cupy/_core/_routines_math.pyx
cupy/_manipulation/join.py
cupy/_manipulation/rearrange.py
tests/cupy_tests/manipulation_tests/test_join.py
tests/cupy_tests/manipulation_tests/test_rearrange.py
tests/cupy_tests/math_tests/test_misc.py
tests/cupy_tests/random_tests/test_sample.py
tests/cupy_tests/sorting_tests/test_search.py

Related to #8565 .
This PR partly fixes https://ci.preferred.jp/cupy.linux.cuda126/176161/ .
- `cupy_tests/manipulation_tests/test_join.py::TestJoin::test_row_stack`
- `cupy_tests/manipulation_tests/test_rearrange.py::TestRollTypeError::test_roll_invalid_shift`
- `cupy_tests/math_tests/test_misc.py::TestMisc::test_clip_min_max_none`
- `cupy_tests/math_tests/test_misc.py::TestMisc::test_fabs_negative`
- `cupy_tests/random_tests/test_sample.py::TestRandintDtype::test_dtype`
- `cupy_tests/sorting_tests/test_search.py::TestNonzeroZeroDimension::test_nonzero` (x2)

Fix NumPy 2.x CI failures

---

tests/cupy_tests/manipulation_tests/test_join.py
tests/cupy_tests/manipulation_tests/test_rearrange.py
tests/cupy_tests/math_tests/test_misc.py
tests/cupy_tests/random_tests/test_sample.py
tests/cupy_tests/sorting_tests/test_search.py

This PR adds `testing.with_requires("numpy<2.0")` to ensure that v13 branch passes the test even without the changes made in #8690 .

[v13] Backport the changes introduced in #8690

---

cupy/_util.pyx

This PR resolves the circular import between `cupy/_util.pyx` and `cupy/cuda/device.pyx`.

Resolve import loop

---

cupy/_math/rounding.py
cupy/random/_generator.py
tests/cupy_tests/math_tests/test_rounding.py
tests/cupy_tests/random_tests/test_generator.py
tests/cupy_tests/statistics_tests/test_meanvar.py
tests/cupy_tests/testing_tests/test_helper.py

Related to #8565 and #8690 .
This PR also partly fixes https://ci.preferred.jp/cupy.linux.cuda126/176161/ .
- `cupy_tests/statistics_tests/test_meanvar.py::TestMeanVar::test_mean_all_float64_dtype`
- `cupy_tests/testing_tests/test_helper.py::TestPackageRequirements::test_installed`
- `cupy_tests/testing_tests/test_helper.py::TestPackageRequirements::test_with_requires`
- `cupy_tests/random_tests/test_generator.py::TestRandint::test_randint_int64_1`
- `cupy_tests/math_tests/test_rounding.py::TestRounding::test_ceil`
- `cupy_tests/math_tests/test_rounding.py::TestRounding::test_floor`
- `cupy_tests/math_tests/test_rounding.py::TestRounding::test_trunc`
- `cupy_tests/math_tests/test_rounding.py::TestRounding::test_fix`

Fix some NumPy 2.x CI failures (cont.)

---

cupy/__init__.py

Following up #8531. CuPy submodules with CUDA dependencies should not be imported before `cupy._core`, as this breaks import error diagnosis.
https://github.com/cupy/cupy/blob/5179721274b688ca2501c6c7c8e3f3253d87297d/cupy/__init__.py#L17-L22

Fix import order

---

cupyx/scipy/signal/_peak_finding.py
tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
tests/cupyx_tests/test_lapack.py

Related to #8565  , #8690 and #8695 .
This PR also partly fixes https://ci.preferred.jp/cupy.linux.cuda126/176161/ .
- `cupyx_tests/scipy_tests/signal_tests/test_peak_finding.py::TestPeakProminences::test_wlen`
- `cupyx_tests/scipy_tests/signal_tests/test_peak_finding.py::TestFindPeaks::test_wlen_smaller_plateau`
- `cupyx_tests/scipy_tests/special_tests/test_basic.py::TestBasic::test_sinc`
- `cupyx_tests/scipy_tests/special_tests/test_basic.py::TestBasic::test_sinc_integer_valued`
- `cupyx_tests/test_lapack.py::TestPosv_param_0_{nrhs=None, shape=(3, 4, 2, 2)}::test_posv`
- `cupyx_tests/test_lapack.py::TestPosv_param_1_{nrhs=None, shape=(5, 3, 3)}::test_posv`

Fix some NumPy 2.x CI failures (cupyx)

---

.pfnci/coverage.rst
.pfnci/linux/tests/cuda11x-cuda-python.Dockerfile
.pfnci/matrix.yaml
cupyx/_runtime.py

Fix https://ci.preferred.jp/cupy.linux.cuda11x-cuda-python/178207/.

Bump CUDA version in cuda11x-cuda-python CI

---

tests/cupyx_tests/fallback_mode_tests/test_fallback.py

`numpy.ndarray.ptp` was removed in NumPy 2.0.

Remove ndarray.ptp from fallback tests

---

docs/source/reference/array_api.rst
docs/source/reference/array_api_array.rst
docs/source/reference/array_api_functions.rst

context: https://github.com/cupy/cupy/issues/8470#issuecomment-2285383328.
Closes #8470 and #8747.
cc/ @leofang

Add notice about `cupy.array_api` removal

---

docs/source/user_guide/difference.rst

Since the NumPy 2.x series adopted the NEP 50 type promotion rules, it is no longer necessary to refer to specific values to determine the dtype of the return value. Now CuPy can aim for full compatibility with NumPy's type promotion rules.
NEP50: https://numpy.org/neps/nep-0050-scalar-promotion.html

Remove "Type promotion" section from user guide

---

cupyx/scipy/interpolate/_bspline.py

`result != n` must be evaluated before `xp >= *&t[result]`.

Fix bspline kernel to avoid out of bounds error

---

cupy/_sorting/search.py
tests/cupy_tests/sorting_tests/test_search.py

Closes https://github.com/cupy/cupy/issues/8782.  Closes https://github.com/cupy/cupy/issues/8784. This PR (1) fixes nanargmin and nanargmax's parameter order and (2) passes optional parameters to `argmin` and `argmax` for `biu`-type ndarrays.

fix nanargmin and nanargmax's parameter order and pass optional parameters

---

cupyx/scipy/sparse/linalg/_norm.py

The sparse matrix `.A` attribute is deprecated in SciPy (and [removed in 1.14.0]( https://docs.scipy.org/doc/scipy-1.14.1/release/1.14.0-notes.html#expired-deprecations )) and is sometimes used with NumPy & SciPy in the tests. So swap it out for the `.todense()` method, which is not deprecated. The behavior and results should be the same. This just avoids deprecation warnings or errors from SciPy.
xref: https://github.com/scipy/scipy/pull/14822
xref: https://github.com/scipy/scipy/pull/20499

Switch from `.A` attribute to `.todense()` method

---

tests/conftest.py

Fix https://ci.preferred.jp/cupy.linux.cuda-head/180775/.
`numpy._set_promotion_state` was removed in NumPy 2.2.

Set `numpy._set_promotion_state("weak")` only for test with NumPy 1.x

---

.github/workflows/flexci.yml

This PR introduces "skip-ci" label support, which omits triggering full CIs when merging a PR.

CI: support "skip-ci" label

---

cupy/_core/core.pyx
cupy/cuda/pinned_memory.pyx

Closes #8789.
- Keep reference to source when doing async H2D copy to avoid lifetime hazard.
- Check for event completion in `free_all_blocks` to free more blocks that are no longer in use.

Fix handling of pinned memory

---

cupyx/scipy/signal/_wavelets.py
tests/cupyx_tests/scipy_tests/signal_tests/test_wavelets.py

The wavelet functions `scipy.signal` have been removed in SciPy 1.15.
https://docs.scipy.org/doc/scipy/release/1.15.0-notes.html#expired-deprecations
Discussion: https://github.com/cupy/cupy/issues/8864.

Raise VisibleDeprecationWarning for wavelet functions

---

cupyx/scipy/ndimage/_filters.py
cupyx/scipy/ndimage/_filters_core.py
cupyx/scipy/ndimage/_morphology.py
cupyx/scipy/ndimage/_util.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_filters.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py

This MR adds `axes` kwarg support to several remaining filter functions and all binary and grayscale morphology functions. These correspond to upstream features merged for SciPy 1.15.0.
- Implements scipy/scipy#20811
- Implements scipy/scipy#21549
The new tests were verified to pass locally when using SciPy **1.15.0rc2**

add axes support for additional functions in cupyx.scipy.ndimage (from SciPy 1.15.0)

---

cupy/_sorting/search.py
tests/cupy_tests/sorting_tests/test_search.py

Fix return type of `cupy.where` for scalar arguments for NumPy 2.0

---

cupyx/scipy/special/_logsumexp.py
tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py

Blocked by https://github.com/cupy/cupy/pull/8835.

Fix `cupyx.scipy.special.logsumexp` for NumPy 2.0

---

cupy/_statistics/histogram.py
tests/cupy_tests/statistics_tests/test_histogram.py

Fix `cupy.histogramdd` for NumPy 2.x

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py

In SciPy 1.15, the result of the matrix product of COO sparse matrices and dense matrices is returned in a C-contiguous array, which is different from the behaviour in SciPy 1.14 and earlier. However, for performance reasons, CuPy should continue to return a non-contiguous array.

Disable contiguous_check for COO/dense matmul test

---

cupyx/scipy/sparse/_index.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py

https://docs.scipy.org/doc/scipy-1.15.0/release/1.15.0-notes.html#scipy-sparse-improvements

Support empty tuple indexing for sparse matrix

---

tests/cupyx_tests/scipy_tests/interpolate_tests/test_interpnd.py

Fix test_interpnd for removed interpolate.interpnd namespace

---

tests/cupyx_tests/scipy_tests/signal_tests/test_cont2discrete.py

The difference of contiguity between SciPy and CuPy stems from the return value of `xp.linalg.solve`. `lapack.gesv` handles F-contiguous ndarrays, it is difficult to resolve this difference without performance degradation.

Disable contiguous_check for some `signal.cont2discrete` tests

---

cupyx/scipy/linalg/_special_matrices.py
tests/cupyx_tests/scipy_tests/linalg_tests/test_special_matrices.py

`scipy.linalg.kron` is deprecated in favour of `numpy.kron` in SciPy 1.15.
https://docs.scipy.org/doc/scipy-1.15.0/release/1.15.0-notes.html#deprecated-features-and-future-changes

Deprecate `cupyx.scipy.linalg.kron`

---

cupyx/scipy/special/__init__.py
cupyx/scipy/special/_sph_harm.py
tests/cupyx_tests/scipy_tests/special_tests/test_sph_harm.py

`scipy.special.sph_harm` has been deprecated in favor of `scipy.special.sph_harm_y`.
https://docs.scipy.org/doc/scipy-1.15.0/release/1.15.0-notes.html#deprecated-features-and-future-changes

Add `special.sph_harm_y` and deprecate `special.sph_harm`

---

cupyx/scipy/ndimage/__init__.py
cupyx/scipy/ndimage/_bbox_slices.pxd
cupyx/scipy/ndimage/_bbox_slices.pyx
cupyx/scipy/ndimage/_measurements.py
cupyx/scipy/ndimage/_util.py
docs/source/reference/scipy_ndimage.rst
install/cupy_builder/_features.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_measurements.py

This MR implements the `find_objects` functions from SciPy. This function finds the Cartesian bounding boxes for all integer-labeled objects in an image as in the example image shown below:
So, conceptually the kernel is very simple and just needs to find the minimum and maximum coordinate index associated with each label value. In the first commit, a simple elementwise kernel was created for this. 
This was refined in a subsequent commit which updated the kernel to process multiple sequential pixels per GPU thread to reduce the overhead of atomic operations. This makes the kernel harder to read, but has substantial performance benefit (see benchmark results below)
A simple Cython function was also implemented to perform the final loop over the coordinates that creates the Python slice …

Add cupyx.scipy.ndimage.find_objects

---

tests/cupyx_tests/scipy_tests/signal_tests/test_splines.py

`for_all_dtypes_combination` does not check all combinations of dtype unless `CUPY_TEST_FULL_COMBINATION="1"` is set.

Fix splines tests to remove unexpected skips

---

.gitmodules
.pfnci/coverage.rst
.pfnci/linux/tests/cuda123.multi.sh
.pfnci/linux/tests/cuda123.sh
.pfnci/matrix.yaml
.pfnci/windows/_flexci.ps1
cupy/_core/core.pyx
cupy/cuda/compiler.py
tests/cupyx_tests/scipy_tests/stats_tests/test_morestats.py

Follow-up of #8899. Close #8588.
This PR switches to use the [2.8.x](https://github.com/NVIDIA/cccl/tree/branch/2.8.x) branch, as discussed in https://github.com/cupy/cupy/pull/8899#issuecomment-2626174099. Currently I manually backported https://github.com/NVIDIA/cccl/pull/3644 on top of it, using the existing `cupy/cccl` fork. If it gets done tomorrow we can switch back.

Use CCCL 2.8.x branch + Use `CUPY_CACHE_KEY` in hash keys

---

tests/cupy_tests/fft_tests/test_callback.py

~~Merge after #8919.~~ **Update**: I rebased against the latest main. This PR can be reviewed/merged independently now.
Changes:
- Skip testing cuFFT callbacks for CTK 12.8 + sm120 (https://github.com/cupy/cupy/pull/8899#discussion_r1928089350)

Minor updates for sm120

---

cupy/_core/core.pyx

Cython knows how to [`decode` a `const char*` directly to `str`]( https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#decoding-bytes-to-text ) without needing to create a `bytes` object. So this drops the use of `bytes` here when constructing the Python value of `CUPY_CACHE_KEY`.
xref: https://github.com/cupy/cupy/pull/8919#discussion_r1940412605
cc @leofang

Drop unneeded `bytes` copy of `CUPY_CACHE_KEY`

---

install/cupy_builder/_context.py

Previously, the cache key was calculated based on the absolute path + content of each header file. This PR changes the logic to use relative path + content instead.
This does not affect end-user use case at all. In the CI environment, source tree is checked out to a temporary directory whose name changes every time. This causes kernel cache to be invalidated every time since #8919.

Use relative path of header files to generate cache key

---

cupyx/jit/_compile.py

This looks required to support the latest CCCL 2.8.x in CUDA 11.2 on Windows.
xref: https://github.com/cupy/cupy/pull/8915#issuecomment-2649595959
cc/ @leofang @jakirkham

Use C++17 in JIT compile

---

cupy/cuda/memory_hooks/line_profile.py

Corrected spelling for `_create_frame_tree` function of `LineProfileHook`. Previous name was `_cretate_frame_tree` with a superfluous `t`.

Fix typo in _cretate_frame_tree

---

cupy/_core/_cub_reduction.pyx
cupy/_functional/vectorize.py

Follow up on this discussion in PR: https://github.com/cupy/cupy/pull/8951
Switch more C++14 flags to C++17.
This should help with compilation issues we have seen (like Windows CUDA 11.2).

Broaden usage of C++17

---

cupy/_core/core.pyx

In Python it seems `TypeError` is expected:
```python
>>> memoryview(123)
TypeError: memoryview: a bytes-like object is required, not 'int'
```
which was discovered by @ZzEeKkAa offline. cc @gmarkall for vis

Fix buffer protocol to raise TypeError when it is not meant to be supported

---

.pfnci/coverage.rst

Fix the static-check CI failure. The coverage table became outdated due to merge order of pull requests.

[v13] Regenerate coverage matrix

---

install/cupy_builder/_compiler.py

In the [release-tools CI](https://ci.preferred.jp/cupy-release-tools.win/186048/#L11407) I found CUB build is failing with error:
```
C:\Windows\TEMP\tmpxft_00000fac_00000000-10_cupy_cub.compute_120.cudafe1.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
```
This fixes the issue by passing `/bigobj`.
(Note: Windows CI in the CuPy repository cannot detect this because it [only builds for the native device](https://github.com/cupy/cupy/blob/9ec2184716a2dc05c3e11d856a981d061dd563bf/.pfnci/windows/test.ps1#L78) as there's no `ccache nvcc` on Windows)

Use `/bigobj` on Windows build

---

tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py

https://github.com/scipy/scipy/issues/22368
In SciPy 1.15.1,
```py
>>> import numpy
>>> import scipy
>>> volume = numpy.arange(10, dtype='q')
>>> scipy.signal.medfilt(volume)
TypeError: Unsupported array type
The above exception was the direct cause of the following exception:
File "/.../.pyenv/versions/3.11.11/lib/python3.11/site-packages/scipy/signal/_signaltools.py", line 1599, in medfilt
result = ndimage.rank_filter(volume, size // 2, size=kernel_size,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.../.pyenv/versions/3.11.11/lib/python3.11/site-packages/scipy/ndimage/_filters.py", line 1630, in rank_filter
return _rank_filter(input, rank, size, …
```

Skip some signal tests for TypeError for inputs of `np.longlong` dtype

---

.pfnci/linux/tests/cuda-rapids.Dockerfile
cupyx/scipy/spatial/distance.py

Fixes a bug in `cupyx.scipy.spatial.distance`'s implementation of `cdist`, which relies on RAPIDS. The current implementation was broken with RAPIDS 24.12 due to a bug in RAPIDS. This includes a fix to workaround the RAPIDS 24.12 bug and remain compatible with RAPIDS pre-24.12 and 25.02+. 
Also update RAPIDS CI testing to use released RAPIDS 25.02 Docker images (instead of nightlies).
Note: RAPIDS dropped CUDA 12.5 images and replaced them with CUDA 12.8.
ref: https://docs.rapids.ai/notices/rsn0042/
cc @cjnolet @grlee77

Fix `cupyx.scipy.spatial.distance`'s `cdist` for RAPIDS 24.12 compatibility

---

cupy/_statistics/histogram.py
tests/cupy_tests/statistics_tests/test_histogram.py

This MR reverts #7708 now that it seems CuPy bundles a recent version of CUB from CCCL instead of relying on a version shipped with CUDA.
One test case was added to cover the original issue reported in #7698

restore CUB histogram and bincount

---

cupyx/scipy/spatial/distance.py

cc @cjnolet , @jakirkham 
This MR is to avoid overhead of explicitly writing zeros into the output array before calling the cuVS/raft `pairwise_distance` function. Unit tests continue to pass when I tried this locally.
Checking in cuVS and raft sources, it seems
- cuVS defaults to [empty-initialized `out` array](https://github.com/rapidsai/cuvs/blob/v25.02.00/python/cuvs/cuvs/distance/distance.pyx)
- at least since RAFT 22.12, it also uses an [empty `out` array](https://github.com/rapidsai/raft/blob/v24.10.00/python/pylibraft/pylibraft/distance/pairwise_distance.pyx#L181) by default.
Given that, I think this is likely safe to merge for CuPy 14.x.
---
Aside from the performance issue, I found that the recommendation of "cuVS>=24.12" does not work for 24.12 (25.02 worked as expected): see …

cupyx.scipy.distance: initialize output array with empty instead of zeros

---

tests/typing_tests/test_run.py

Following up #8953, fixes Python 3.13 CI failure
https://ci.preferred.jp/cupy.linux.cuda126/186849/#L28875
```
FAILED typing_tests/test_run.py::test_run[/tmp/tmp.frF0r0nEHN/tests/typing_tests/cupy_tests/creation_tests/test_basic.pyi]
```
The same reason as https://github.com/cupy/cupy-release-tools/pull/397#discussion_r1959125638

Pass `locals` dict to `exec`

---

cupyx/scipy/spatial/distance.py

sorry, I was out of office just before !8971 was merged and had missed addressing [this comment](https://github.com/cupy/cupy/pull/8971#issuecomment-2667149879)
This MR removes an unnecessary zeroing of user-provided `out` array in `cupyx.scipy.spatial.distance.cdist`
cc @jakirkham, @kmaehashi

`cupyx.scipy.spatial.distance.cdist` remove explicit zeroing of user-provided output array

---

.github/workflows/docker.yml
docker/python3/Dockerfile
docker/rocm/Dockerfile

As per https://github.com/cupy/cupy/issues/8607#issuecomment-2658763950 ROCm packages are unavailable this time. We will work on resolving this issue targeting the next release.

[v13] Bump docker images for v13.4.0 release

---

.pfnci/windows/test.ps1

It seems that on these platforms the compilation is extremely slow that could not complete the full combination tests within reasonable resources.
Here is the latest CI results for the recent commit in the `main` branch: https://ci.preferred.jp/p/dashboard_by_commit_id?commit_id=d44993a49f920f6e53812791ad2e85bbc04b76fd
I attempted several approaches (#8949 etc.) but couldn't find the root cause. The CUDA 12.3.0 release notes mentions the compiler performance improvement, so I guess this got fixed somehow in the recent versions of CUDA.
https://docs.nvidia.com/cuda/archive/12.3.0/cuda-toolkit-release-notes/index.html#cuda-compilers
> * Improved compile time in some common scenarios:
>   * Extended split compilation to cubin for LTO.
>   * Turned on concurrent NVVM processing by default, …

CI: Do not run full CI on CUDA 12.0/12.1/12.2 + Windows

---

cupy/_core/dlpack.pyx
tests/cupy_tests/core_tests/test_dlpack.py

This was an oversight in the original PR, even if this is basically deprecated, we should not have changed the default here.
We noticed this in downstream code, but the impact was not very big (use `__dlpack__()` and not common code) for now.
As this reverts behavior, I think it would probably only be useful if backported to a 13.4.1 in the not-so-far future.
(So if that is unlikely to happen, we can probably just close it. Those running into the issue should use `__dlpack__()`.)
---
CC @leofang.

[v13] API: Revert toDlpack() default to the old unversioned one

---

cupy/_core/dlpack.pyx
tests/cupy_tests/core_tests/test_dlpack.py

[v13.4.1] API: Revert toDlpack() default to the old unversioned one

---

cupy/_core/fusion.pyx
tests/cupy_tests/core_tests/fusion_tests/test_ufunc.py

Scalars are a problem, and I am not convinced that this is a complete fix (for example w.r.t. integers).  OTOH v14 should already be working here, I believe.
But I think this is safe and could be back-portable.
---
Closes gh-8536
~Need to still check if v14 is indeed fine, we may want to forward port the test to make sure.~  v14 is fine as expected.

[v13] BUG: Hot fix for numpy 2 support in some fusion paths

---

install/cupy_builder/cupy_setup_build.py
install/cupy_builder/install_build.py

This commit fixes `/opt/rocm/include/thrust/version.h:34:10: fatal error: cuda/version: No such file or directory` error when try to build cupy for ROCm 6.3. See https://github.com/ROCm/rocThrust/issues/502. 
It also addresses the C++ version warning by changing compiler argument from c++11 to c++14

Fix rocThrust build for ROCm 6.3

---

cupyx/scipy/ndimage/_morphology.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py

There was a bug in the recently added axes support for some morphology functions. The default structuring element in that case must have `ndim=len(axes)` and rather than the full image dimension.
The tests were updated to also run cases with `structure=None`

ndimage: fix bug in morphology `axes` support when `structure=None`

---

cupy/_environment.py
cupyx/tools/_generate_wheel_metadata.py
cupyx/tools/install_library.py

Allow loading cuTENSOR 2.x wheels regardless of the version used at build time (currently 2.1). Fixes #9017.
This PR also moves the generation logic of wheel metadata file (`cupy/.data/_wheel.json`) from [cupy-release-tools](https://github.com/cupy/cupy-release-tools/blob/3e75f4c5b20f62f6898770ed5f190ba1e2fb221e/dist.py#L75-L96) to cupy, so that CuPy developers can generate the wheel metadata by
```
$ python cupyx/tools/_generate_wheel_metadata.py --cuda 12.x --library cutensor --library cudnn --library nccl > cupy/.data/_wheel.json
```
and easily test the preload mechanism like:
```
$ export CUPY_DEBUG_LIBRARY_LOAD=1
$ python -c 'import cupy'
```

Allow discovering cuTENSOR using major version

---

.pfnci/windows/test.ps1

Tentatively workaround Windows build error with setuptools v76.0.0.
The fix is ongoing at https://github.com/pypa/distutils/pull/342

CI: Pin setuptools version on Windows

---

cupy/fft/_callback.pyx
cupy/random/_generator.py

FIPS enabled machines prohibit MD5 hashing for security reasons. Using hashlib.md5 in Python will throw the error ValueError: [digital envelope routines] unsupported. There are typically 2 resolutions to this problem: use the usedforsecrutiy=False flag or use SHA1 hashing. The usedforsecurity flag is easier to implement and was introduced in Python 3.9, which is the minimum Python version for this library, so that is the method I chose.

Support FIPS enabled machines with MD5 hashing

---

cupyx/scipy/special/_basic.py
cupyx/scipy/special/_bessel.py
cupyx/scipy/special/_beta.py
cupyx/scipy/special/_gamma.py
cupyx/scipy/special/_gammaln.py
cupyx/scipy/special/_gammasgn.py
cupyx/scipy/special/_logsumexp.py
cupyx/scipy/special/_spherical_bessel.py
cupyx/scipy/special/_zetac.py
tests/cupyx_tests/scipy_tests/special_tests/test_basic.py
tests/cupyx_tests/scipy_tests/special_tests/test_bessel.py
tests/cupyx_tests/scipy_tests/special_tests/test_beta.py
tests/cupyx_tests/scipy_tests/special_tests/test_binom.py
tests/cupyx_tests/scipy_tests/special_tests/test_convex_analysis.py
tests/cupyx_tests/scipy_tests/special_tests/test_digamma.py
tests/cupyx_tests/scipy_tests/special_tests/test_exprel.py
tests/cupyx_tests/scipy_tests/special_tests/test_gamma.py
tests/cupyx_tests/scipy_tests/special_tests/test_gammaln.py
tests/cupyx_tests/scipy_tests/special_tests/test_logsumexp.py
tests/cupyx_tests/scipy_tests/special_tests/test_polygamma.py
tests/cupyx_tests/scipy_tests/special_tests/test_spherical_bessel.py
tests/cupyx_tests/scipy_tests/special_tests/test_zeta.py
tests/cupyx_tests/scipy_tests/special_tests/test_zetac.py

- Fix for test failures caused by dtype mismatch
- Minor fix for inf/nan handling
- Enhanced tests for more comprehensive input dtype coverage
- Fix tests to suppress overflow warning

Update cupyx.scipy.special functions for SciPy 1.15

---

cupyx/scipy/ndimage/_morphology.py
tests/cupyx_tests/scipy_tests/ndimage_tests/test_morphology.py

This MR is built on top of a bug fix from https://github.com/cupy/cupy/pull/8954, so please review that one first.
partially resolves #8867 (it does not fix the slow performance of iterative binary morphology, but provides a way to perform `binary_fill_holes` without needing to use iteration)
see https://github.com/cupy/cupy/issues/8867#issuecomment-2659471046

Improve performance of `cupyx.scipy.ndimage.binary_fill_holes`

---

cupyx/scipy/spatial/delaunay_2d/_tri.py
tests/cupyx_tests/scipy_tests/spatial_tests/test_delaunay.py

Fixes #8765 
This PR makes sure that inputs to Delaunay triangulation are cast as `double`

Cast points when computing Delaunay triangulation on dtype != float64

---

tests/cupy_tests/random_tests/common_distributions.py
tests/cupy_tests/random_tests/test_generator.py

CuPy v13 does not guarantee the compatibility with NumPy 2.x.

[v13] Skip some dtype checks with NumPy 2.x

---

tests/cupy_tests/math_tests/test_sumprod.py

CuPy v13 does not guarantee the compatibility with NumPy 2.x.

[v13] Skip tests for different behavior of integer overflow from NumPy 2

---

tests/cupyx_tests/scipy_tests/signal_tests/test_polyutils.py
tests/cupyx_tests/signal_tests/radartools_tests/test_radartools.py

CuPy v13 does not guarantee the compatibility with NumPy 2.x.

[v13] Skip some tests for numerical error from NumPy 2

---

cupyx/tools/_generate_wheel_metadata.py

Follows-up #9030.
AArch64 wheels are currently not built with support for optional libraries such as cuDNN/cuTENSOR. `_generate_wheel_metadata.py` must be able to generate a wheel metadata containing no preload libraries for that case.

Allow specifing no libraries when generating wheel metadata

---

MANIFEST.in

Follows-up #8916. `pxd` files must be explicitly added via `MANIFEST.in`, otherwise source build from sdist does not work.

Include `pxd` files in `cupyx`

---

.github/workflows/docker.yml
docker/python3/Dockerfile
docker/rocm/Dockerfile

This includes a forward-port of #8999 (which disables ROCm docker images).

Update Docker images for v14.0.0a1 release

---

tests/cupy_tests/cuda_tests/memory_hooks_tests/test_debug_print.py
tests/cupy_tests/cuda_tests/memory_hooks_tests/test_line_profile.py
tests/cupy_tests/cuda_tests/test_memory_hook.py

Closes #9077
I repeatedly ran the test locally but could not reproduce the origianl issue. My guess is that Python GC has triggered somewhere between `with self.hook:` and `alloc_postprocess`, which caused `free_postprocess` (for a memory block acquired in the previous test cases) to be triggered.
https://github.com/cupy/cupy/blob/1e8ade16f7f0af01e748e706e8c8302ffd2fc873/tests/cupy_tests/cuda_tests/memory_hooks_tests/test_debug_print.py#L22-L23
Adding `gc.collect()` to `setUp` to avoid `free_*` to be triggered.

Do `gc.collect()` in MemoryHook test code to avoid `free` hook to happen

---

cupy/linalg/_einsum_cutn.py

This PR implements lazy load for `cuquantum` in `cupy.einsum`.
Currently `cuquantum/cutensornet` is an optional accelerator of `cupy.einsum`. However the optional module will be loaded regardless of whether it has been set as `CUPY_ACCELERATOR` if it's installed. Since `cuquantum` has its own dependencies with some overhead during import,  we here switch to lazy import for `cuquantum` such that non-einsum users will not need to load it into their environment.

Implement lazy load for cuquantum

---

cupyx/scipy/signal/__init__.py
cupyx/scipy/signal/_filter_design.py
docs/source/reference/scipy_signal.rst

In SciPy 1.15, `scipy.signal.sosfreqz` was renamed to `freqz_sos`, and the original name is kept as a "legacy" alias for backwards compatibility.
Thus, follow the rename/aliasing in `cupyx.scipy.signal`.

ENH: cupyx/signal: add freqz_sos, a preferred alias for sosfreqz

---

cupyx/scipy/signal/_filter_design.py

Currently, one of `gammatone` return values is an array or a list, depending on other inputs. Fix it to always return arrays.
Observed in https://github.com/scipy/scipy/pull/22914, which delegates to `cupyx.scipy.signal.gammatone` from `scipy.signal.gammatone`.

BUG: cupyx.scipy.signal: make gammatone return arrays

---

docs/source/contribution.rst
pyproject.toml

To prevent build breakage like #9131 from happening in the future, limiting supported Cython version used for the build time.
xref #9128

Limit Cython version to 3.0 or 3.1

---

cupyx/scipy/linalg/_matfuncs.py
tests/cupyx_tests/scipy_tests/linalg_tests/test_matfuncs.py

closes gh-9138
Fix a math error in `expm` implementation, where a formula from the paper was incorrectly translated from math to python.

BUG: fix `cupyx.scipy.linalg.expm`

---

docs/source/_comparison_generator.py
docs/source/reference/indexing.rst

- **alias should not be on API reference**
- **hide private NumPy APIs from comparison table**

Improve API reference list

---

tests/cupy_tests/manipulation_tests/test_add_remove.py

Part of https://github.com/cupy/cupy/issues/9157.
https://numpy.org/devdocs/release/2.3.0-notes.html#unique-values-may-return-unsorted-data

`np.unique_values` may return unsorted data from NumPy 2.3

---

cupy/_core/internal.pyx
tests/cupy_tests/core_tests/test_internal.py
tests/cupy_tests/core_tests/test_ndarray.py
tests/cupy_tests/creation_tests/test_basic.py

Part of https://github.com/cupy/cupy/issues/9157.
https://numpy.org/devdocs/release/2.3.0-notes.html#expired-deprecations

Fix `cp.empty(None)` to raise `TypeError`

---

.gitignore
install/cupy_builder/_context.py
install/cupy_builder/cupy_setup_build.py

This PR intends to make try-and-error iteration faster during CuPy development for better DX.
I confirmed the build time (measured by `time pip install --no-build-isolation -e . -v`) decreased from 9.5 sec. to 5.1 sec when rebuilding CuPy without any modification. While the difference might seem small, for CuPy developers who are repeatedly rebuilding Cython code, it accumulates into a significant impact.
Specifically, this PR:
1. Introduces an environment variable `CUPY_INSTALL_CONFIGURE_CACHE=1` which persists/reuses the module configuration results to/from `.cupy_builder.cache`. When rebuilding, configuration step will be skipped (i.e. you won't see `-------- Configuring Module: cuda --------` etc. at all.) This was made possible as `cupy_builder.Context` is now defined using …

Make rebuild faster for development

---

cupy/_environment.py
cupyx/tools/install_library.py

Allow loading NCCL from pip/wheel pacakges. This will give users flexibility of using arbitrary NCCL versions installed in the user's environment with CuPy.
We already supports this for cuTENSOR (#6999/#7025).

Support loading NCCL from Pip packages

---

.pfnci/config.tags.json
.pfnci/matrix.yaml

Follows-up #9200. Without this configuration CUDA 12.9 + Windows matrix will not be triggered.

Add `cupy.win.cuda129` CI

---

cupyx/scipy/spatial/delaunay_2d/_kernels.py

Close https://github.com/cupy/cupy/issues/8933.
`nextNearest` can become `-1` when the all opposites of `nearest` are visited. This PR stops the search for the closest points and concludes that there is no triangle covering the query point in such a case.
cc: @andfoy

Fix illegal memory access in LinearNDInterpolator

---

cupy/_math/misc.py
tests/cupy_tests/math_tests/test_misc.py

Fixes https://github.com/cupy/cupy/issues/9143
Following numpy here: https://github.com/numpy/numpy/blob/3ccbc6c29bb56795d32ee685bccdc1e9ca8ae47f/numpy/lib/_type_check_impl.py#L469-L492,
I don't think that cupy should check for `cupy.isnan(x)` and `cupy.isinf(x)` for the user defined arguments `nan`, `posinf`, and `neginf`. Numpy doesn't care about them, and does the `copyto` anyway. I believe that `cupy.asanyarray(x, dtype)` is enough here.
cc @leofang since we went over this at the SciPy sprints.

feat: make `cupy.nan_to_num` broadcast `nan`, `posinf`, and `neginf` kwargs

---

cupy/_core/core.pyx
tests/cupy_tests/creation_tests/test_from_data.py

This PR fixes `UnboundLocalError` when creating CuPy ndarray with `blocking` e.g. `cp.array(..., blocking=True)`. Closes #9271.
xref #8442, #7939
cc/ @rongou @leofang

Fix `UnboundLocalError` when `blocking=True`

---

cupy/cuda/cupy_cub.h
cupyx/scipy/signal/_upfirdn.py

This is the fix for Issue [#9074](https://github.com/cupy/cupy/issues/9074).
Since cupy no longer supports CUDA 11.1 or earlier, the #if checks from [cupy/cupyx/scipy/signal/_upfirdn.py](https://github.com/cupy/cupy/blob/53127099fe5c441fec97567f57974504342f304d/cupyx/scipy/signal/_upfirdn.py#L62) and [cupy/cupyx/scipy/signal/_upfirdn.py](https://github.com/cupy/cupy/blob/53127099fe5c441fec97567f57974504342f304d/cupyx/scipy/signal/_upfirdn.py#L175) have been removed.

CUDA 11.1 or earlier is no longer supported

---

README.md
docs/source/install.rst

Readme and install guide updated
Not sure if we should update the examples in the install guide to refer to 13x instead of 12x. I feel that keeping those in 12x for a while is better since it is more "tested"
xref https://github.com/cupy/cupy/issues/9286

CUDA 13 Update docs

---

.pfnci/linux/tests/cuda124.Dockerfile
.pfnci/linux/tests/cuda124.multi.Dockerfile
.pfnci/schema.yaml

Fixes regression in #9295. It seems `cuda_fp16.h` bundled with CUDA 12.4.0 has a problem and causing the following error:
https://ci.preferred.jp/cupy.linux.cuda124/198208/
```
ptxas fatal   : Unresolved extern function '_ZN6__halfC1Ef'
```
I locally confirmed this is fixed in CUDA 12.4.1.

Fix CI failure in CUDA 12.4

---

tests/cupyx_tests/scipy_tests/sparse_tests/test_coo.py

Close https://github.com/cupy/cupy/issues/9292.
CuPy v13 supports SciPy 1.7.

[v13] Fix scipy version condition of COO matrix test

---

.pfnci/windows/test.ps1

Adjust the Windows cache size. CI is taking longer than expected (and some variants time out) as the cache no longer fits within 1 GB.
https://ci.preferred.jp/cupy.win.cuda118/198389/
```
05:12:37.640040 STDERR 5808]	Total:   1327341061 bytes, 93202 files	
05:12:37.640040 STDERR 5808]	Valid:   999999309 bytes, 77738 files	
05:12:37.640040 STDERR 5808]	Expired: 327341752 bytes, 15464 files	
```
This PR bumps the size limit to 3 GiB, aligning with Linux CI:
https://github.com/cupy/cupy/blob/541b9c6af4045172cd97a3c045e375189c811519/.pfnci/linux/tests/actions/cleanup.sh#L5

CI: Extend Windows cache size

---

cupy/_core/core.pyx

To help modernize development, AMD would like to bump the default RTC c++ standard from 11 to 14. 
This would give projects using cupy and AMD hardware zero day support for ROCm 7.0.0 and encourage
development using newer standards. Some new features in c++ 14:
* Generic lambdas (`[] (auto x, auto y) { … }`)
* Lambda init-capture (`[p = std::move(p)] { … }`)
* Return type deduction for normal functions (`auto f(){ … }`)
* Relaxed `constexpr` (loops/branches allowed in `constexpr` functions)
* Variable templates (`template<class T> constexpr T k = …;`)
* `std::integer_sequence` / `std::index_sequence`
* `_t` type aliases (e.g., `std::enable_if_t`, `std::decay_t`, `std::remove_reference_t`)
* `std::exchange`
* Binary literals & digit separators (`0b1010`, `1'000'000`)
* `[[deprecated]]` …

Change default c++ RTC standard from 11 to 14

---

cupy/__init__.py

As part of the import time investigations I have been doing regarding #9324 and #9325 I also noticed that cupy.testing adds significant testing overhead in environments where pytest is installed. I considered making the pytest import lazy or trying to hide its cost in other ways, but ultimately I decided that since most users of cupy do not need the testing module directly the best option would be to make the testing module import in cupy's `__init__.py` lazy and hide all of the overhead. The module load is fast enough that for users actually accessing the testing module the first attribute access (which triggers the load, and is therefore made slower by making this module load lazy) is still less than 0.1 s so it doesn't degrade that experience much (in exchange for making the majority …

Lazy load the testing module

---

.github/workflows/self-hosted-ci.yml
.pfnci/coverage.rst
.pfnci/linux/tests/rocm-6-4.Dockerfile
.pfnci/linux/tests/rocm-6-4.sh
.pfnci/matrix.yaml
.pfnci/schema.yaml

Added support for ROCm 6.4.3 in CI. Using the complete image so that we don't have to download additional dependencies. 
Confirmed that the build compiles on gfx90a. Let me know if there is anything else that I have to do.

feat(CI) ROCm 6.4.3

---

cupyx/scipy/signal/windows/_windows.py
cupyx/signal/_acoustics/_cepstrum.py

`const bool odd{ _ind.size() & 1 };` triggered a hard compile error under clang/HIPRTC:
> non-constant-expression cannot be narrowed from type ‘ptrdiff\_t’ to ‘bool’ in initializer list \[-Wc++11-narrowing]
C++11 **list-initialization** (`{...}`) forbids implicit narrowing conversions. Here `_ind.size()` returns an integral type (e.g., `ptrdiff_t`), and brace- initializing a `bool` from a non-constant integral expression is ill-formed.
Change the expression to produce a real `bool`:
```cpp
const bool odd{ (_ind.size() & 1) != 0 };  // (or: _ind.size() % 2 != 0)
```
This avoids narrowing, keeps brace-init, and restores compatibility with HIPRTC/clang and other strict compilers/flags.
We have also updated kernels to use the default hipRTC compilation standard (14). This enables cepstrum …

feat(kernels) fix HIPRTC build error ROCm 6/7

---

cupy_backends/cuda/libs/cutensor.pxd
cupy_backends/cuda/libs/cutensor.pyx
cupy_backends/stub/cupy_cutensor.h
cupyx/cutensor.pyx

closes #9350
This MR updates cutensor contraction backend with improvement on the workspace size inquiry. 
An additional call to `cutensorPlanGetAttribute` is made to reduce the workspace size actually needed to execute the contraction. A few extra bindings were added to support this improvement. Example usage from [here](https://github.com/NVIDIA/CUDALibrarySamples/blob/a2433ef214c238e0abdb5e4307ba4b1862f81d1a/cuTENSOR/contraction.cu#L286)

Fix cuTENSOR workspace size query

---

cupy/_core/core.pyx

Cupy bundles cccl include directories inside of it's wheel. When building compilation commands, cupy will also place CCCL directories first in the include path. This means that if any kernel includes a CCCL header (thrust, cub, etc), hipcc or hiprtc will read the actual CUDA header rather than the system thrust/cub/etc. This will result in failures on hip systems.
This commit now only adds CCCL headers if on CUDA.
@kmaehashi It would be great to get this into v13 since it is just a bug fix.

feat(JIT) Remove CCCL includes dir

---

cupyx/scipy/sparse/_csr.py
tests/cupyx_tests/scipy_tests/sparse_tests/test_csr.py

Related to https://github.com/cupy/cupy/pull/8844.

Fix return dtype of csr_matrix minmax with scalar
